"""Picture boards, batch 3 -- filling the subjects the first two batches missed.

After batch 2 the picture pool was lopsided: eight boards for Geografie and
none at all for Sport or Film & Fernsehen, which is exactly the imbalance
`drafting.py` cannot fix, since it deals evenly across the subjects a host
picks. These boards are chosen to close that gap.

Film is the awkward one. Stills and posters are copyrighted, so Commons has
none -- but it has plenty of freely licensed *people* and *places*, so the
boards ask about directors, actors and real filming locations instead of frames
from the film.
"""

BOARDS = [
    # --- Sport: nothing existed before ------------------------------------
    dict(
        subject="sport", slug="bild-sportler-disziplinen",
        title="Sportgrößen im Bild",
        description="In welcher Sportart wurde die Person berühmt?",
        difficulty="medium", source_title="Sport",
        source_url="https://de.wikipedia.org/wiki/Sport",
        pairs=[
            ("Usain Bolt", "Leichtathletik", "Weltrekorde über 100 und 200 Meter."),
            ("Michael Phelps", "Schwimmen", "23 olympische Goldmedaillen."),
            ("Serena Williams", "Tennis", "23 Grand-Slam-Titel im Einzel."),
            ("Michael Jordan", "Basketball", "Sechs Meisterschaften mit den Chicago Bulls."),
            ("Lionel Messi", "Fußball", "Achtmal mit dem Ballon d'Or ausgezeichnet."),
            ("Muhammad Ali", "Boxen", "Dreimal Weltmeister im Schwergewicht."),
            ("Michael Schumacher", "Formel 1", "Sieben Weltmeistertitel."),
            ("Tiger Woods", "Golf", "Fünfzehn Major-Titel."),
            ("Wayne Gretzky", "Eishockey", "Seine Nummer 99 ist ligaweit gesperrt."),
            ("Eddy Merckx", "Radsport", "Fünfmal Sieger der Tour de France."),
            ("Nadia Comăneci", "Turnen", "Erste perfekte Zehn bei Olympischen Spielen."),
            ("Katarina Witt", "Eiskunstlauf", "Zweimal olympisches Gold in Folge."),
        ],
    ),
    dict(
        subject="sport", slug="bild-stadien-laender",
        title="Stadien im Bild",
        description="In welchem Land steht das Stadion?",
        difficulty="hard", source_title="Stadion",
        source_url="https://de.wikipedia.org/wiki/Stadion",
        pairs=[
            ("Camp Nou", "Spanien", "Größtes Stadion Europas nach Plätzen."),
            ("Wembley-Stadion", "England", "Erkennbar am Bogen über dem Dach."),
            ("Estádio do Maracanã", "Brasilien", "1950 sahen dort fast 200000 Menschen ein Endspiel."),
            ("Allianz Arena", "Deutschland", "Die Außenhaut lässt sich farbig beleuchten."),
            ("Giuseppe-Meazza-Stadion", "Italien", "Zwei Vereine teilen sich das Haus."),
            ("Stade de France", "Frankreich", "Für die Weltmeisterschaft 1998 gebaut."),
            ("Estadio Azteca", "Mexiko", "Schauplatz zweier WM-Endspiele."),
            ("Luschniki-Stadion", "Russland", "Finalort der Weltmeisterschaft 2018."),
            ("Johan Cruijff Arena", "Niederlande", "Erstes europäisches Stadion mit verschiebbarem Dach."),
            ("Melbourne Cricket Ground", "Australien", "Fasst über 100000 Zuschauer."),
            ("Yankee Stadium", "USA", "Heimstätte eines Baseballteams aus der Bronx."),
            ("Ernst-Happel-Stadion", "Österreich", "Größtes Stadion des Landes."),
        ],
    ),
    dict(
        subject="sport", slug="bild-sportgeraete",
        title="Sportgeräte im Bild",
        description="Zu welcher Sportart gehört das Gerät?",
        difficulty="hard", source_title="Sportgerät",
        source_url="https://de.wikipedia.org/wiki/Sportger%C3%A4t",
        pairs=[
            ("Puck (Eishockey)", "Eishockey", "Hartgummischeibe, vor dem Spiel gekühlt."),
            ("Curlingstein", "Curling", "Granitstein von rund zwanzig Kilogramm."),
            ("Federball", "Badminton", "Fliegt schneller als jeder andere Spielball."),
            ("Florett", "Fechten", "Treffer zählen nur am Rumpf."),
            ("Queue (Billard)", "Billard", "Die Lederkuppe wird gekreidet."),
            ("Diskus (Sportgerät)", "Leichtathletik", "Aus dem Ring heraus geworfen."),
            ("Boxhandschuh", "Boxen", "Erst seit dem 19. Jahrhundert vorgeschrieben."),
            ("Steigeisen", "Bergsteigen", "Zacken für Eis und harten Firn."),
            ("Skateboard", "Skateboarding", "Aus dem Surfen an Land entstanden."),
            ("Pfeilbogen", "Bogenschießen", "Gespannt wird mit drei Fingern."),
            ("Surfbrett", "Wellenreiten", "Früher aus einem Stück Holz geschnitzt."),
            ("Golfschläger", "Golf", "Ein Satz umfasst höchstens vierzehn Stück."),
            ("Tischtennisschläger", "Tischtennis", "Eine Seite rot, eine schwarz."),
        ],
    ),

    # --- Film & Fernsehen: nothing existed before --------------------------
    dict(
        subject="film-fernsehen", slug="bild-regisseure-filme",
        title="Regisseure im Bild",
        description="Von wem stammt dieser Film?",
        difficulty="hard", source_title="Filmregisseur",
        source_url="https://de.wikipedia.org/wiki/Filmregisseur",
        pairs=[
            ("Steven Spielberg", "Jurassic Park", "Maßstab für digitale Effekte."),
            ("Quentin Tarantino", "Pulp Fiction", "Goldene Palme 1994."),
            ("Alfred Hitchcock", "Psycho", "Berühmt für die Duschszene."),
            ("Martin Scorsese", "Taxi Driver", "New York als Fiebertraum."),
            ("Christopher Nolan", "Inception", "Verschachtelte Traumebenen."),
            ("Sofia Coppola", "Lost in Translation", "Zwei Fremde in einem Tokioter Hotel."),
            ("Pedro Almodóvar", "Volver", "Farbenstarkes Melodram mit Penélope Cruz."),
            ("Akira Kurosawa", "Die sieben Samurai", "Vorbild für unzählige Westernfilme."),
            ("Werner Herzog", "Fitzcarraldo", "Ein Schiff wurde wirklich über den Berg gezogen."),
            ("Bong Joon-ho", "Parasite", "Erster nicht englischsprachiger Oscar als bester Film."),
            ("Wim Wenders", "Der Himmel über Berlin", "Engel hören den Gedanken der Stadt zu."),
            ("Greta Gerwig", "Lady Bird", "Erwachsenwerden in Sacramento."),
        ],
    ),
    dict(
        subject="film-fernsehen", slug="bild-schauspieler-rollen",
        title="Schauspieler im Bild",
        description="Welche Rolle ist mit dieser Person verbunden?",
        difficulty="medium", source_title="Schauspieler",
        source_url="https://de.wikipedia.org/wiki/Schauspieler",
        pairs=[
            ("Harrison Ford", "Indiana Jones", "Hut und Peitsche als Markenzeichen."),
            ("Sigourney Weaver", "Ellen Ripley", "Die Rolle war ursprünglich männlich geschrieben."),
            ("Anthony Hopkins", "Hannibal Lecter", "Nur sechzehn Minuten Leinwandzeit, ein Oscar."),
            ("Arnold Schwarzenegger", "Terminator", "Wenige Sätze, alle davon berühmt."),
            ("Meryl Streep", "Miranda Priestly", "Die Bosheit klingt hier nur geflüstert."),
            ("Keanu Reeves", "Neo", "Monatelanges Kampftraining vor dem Dreh."),
            ("Daniel Radcliffe", "Harry Potter", "Mit elf Jahren besetzt."),
            ("Gal Gadot", "Wonder Woman", "Ehemalige Soldatin der israelischen Armee."),
            ("Tom Hanks", "Forrest Gump", "Er läuft quer durch die US-Geschichte."),
            ("Johnny Depp", "Jack Sparrow", "Vorbild war ein Rockgitarrist."),
            ("Jennifer Lawrence", "Katniss Everdeen", "Bogenschießen extra gelernt."),
            ("Robert Downey Jr.", "Tony Stark", "Viele Dialoge entstanden beim Drehen."),
        ],
    ),

    # --- Musik, Geschichte, Technik, Essen: thin before ---------------------
    dict(
        subject="musik", slug="bild-musiker-instrumente",
        title="Musiker im Bild",
        description="Welches Instrument spielte die Person?",
        difficulty="medium", source_title="Musiker",
        source_url="https://de.wikipedia.org/wiki/Musiker",
        pairs=[
            ("Jimi Hendrix", "E-Gitarre", "Spielte linkshändig auf umgedrehter Gitarre."),
            ("Miles Davis", "Trompete", "Prägte gleich mehrere Jazzstile."),
            ("John Coltrane", "Saxophon", "Sein Album A Love Supreme gilt als Meilenstein."),
            ("Glenn Gould", "Klavier", "Berühmt für seine Bach-Aufnahmen."),
            ("Yo-Yo Ma", "Violoncello", "Spielte bei mehreren Amtseinführungen."),
            ("Ravi Shankar", "Sitar", "Brachte indische Musik in den Westen."),
            ("Keith Moon", "Schlagzeug", "Trommler von The Who."),
            ("James Galway", "Querflöte", "Bekannt für seine goldene Flöte."),
            ("Andrés Segovia", "Konzertgitarre", "Machte die klassische Gitarre konzertfähig."),
            ("Toots Thielemans", "Mundharmonika", "Auch als Pfeifer auf Filmmusiken zu hören."),
            ("Jaco Pastorius", "E-Bass", "Spielte bundlos und veränderte die Rolle des Basses."),
            ("Anne-Sophie Mutter", "Violine", "Mit dreizehn von Karajan entdeckt."),
        ],
    ),
    dict(
        subject="musik", slug="bild-opernhaeuser-staedte",
        title="Opernhäuser im Bild",
        description="In welcher Stadt steht das Haus?",
        difficulty="hard", source_title="Opernhaus",
        source_url="https://de.wikipedia.org/wiki/Opernhaus",
        pairs=[
            ("Teatro alla Scala", "Mailand", "Eröffnet 1778, Maßstab für Sängerkarrieren."),
            ("Metropolitan Opera", "New York", "Seit 1966 am Lincoln Center."),
            ("Bolschoi-Theater", "Moskau", "Bekannt für sein Ballettensemble."),
            ("Royal Opera House", "London", "Im Viertel Covent Garden."),
            ("Palais Garnier", "Paris", "Prunktreppe und Deckengemälde von Chagall."),
            ("Teatro Colón", "Buenos Aires", "Berühmt für seine Akustik."),
            ("Wiener Staatsoper", "Wien", "Einmal im Jahr wird sie zum Ballsaal."),
            ("Gran Teatre del Liceu", "Barcelona", "Zweimal abgebrannt und wieder aufgebaut."),
            ("Teatro La Fenice", "Venedig", "Der Name bedeutet Phönix, was zur Geschichte passt."),
            ("Elbphilharmonie", "Hamburg", "Konzerthaus auf einem alten Kaispeicher."),
            ("Semperoper", "Dresden", "Nach der Zerstörung 1985 neu eröffnet."),
            ("Oslo Opera House", "Oslo", "Das Dach lässt sich begehen."),
        ],
    ),
    dict(
        subject="geschichte", slug="bild-antike-staetten",
        title="Antike Stätten im Bild",
        description="In welchem heutigen Land liegt die Stätte?",
        difficulty="hard", source_title="Archäologie",
        source_url="https://de.wikipedia.org/wiki/Arch%C3%A4ologie",
        pairs=[
            ("Akropolis", "Griechenland", "Tempelberg über Athen mit dem Parthenon."),
            ("Pyramiden von Gizeh", "Ägypten", "Einziges erhaltenes der antiken Weltwunder."),
            ("Chichén Itzá", "Mexiko", "Maya-Stadt mit der Pyramide des Kukulcán."),
            ("Angkor Wat", "Kambodscha", "Größte Tempelanlage der Welt."),
            ("Persepolis", "Iran", "Residenz der Perserkönige."),
            ("Palmyra", "Syrien", "Oasenstadt der Königin Zenobia."),
            ("Ephesos", "Türkei", "Mit der Fassade der Celsus-Bibliothek."),
            ("Karthago", "Tunesien", "Von Rom 146 v. Chr. zerstört."),
            ("Timgad", "Algerien", "Römische Koloniestadt im Schachbrettgrundriss."),
            ("Leptis Magna", "Libyen", "Heimatstadt des Kaisers Septimius Severus."),
            ("Mohenjo-Daro", "Pakistan", "Planstadt der Indus-Kultur mit Kanalisation."),
            ("Great Zimbabwe", "Simbabwe", "Steinstadt, die dem Staat den Namen gab."),
        ],
    ),
    dict(
        subject="geschichte", slug="bild-erfindungen-erfinder",
        title="Erfindungen im Bild",
        description="Wer steckt hinter dem Gerät?",
        difficulty="hard", source_title="Erfindung",
        source_url="https://de.wikipedia.org/wiki/Erfindung",
        pairs=[
            ("Benz Patent-Motorwagen Nummer 1", "Carl Benz", "Der erste Wagen mit Verbrennungsmotor, 1886."),
            ("Gutenberg-Bibel", "Johannes Gutenberg", "Erstes bedeutendes Buch aus beweglichen Lettern."),
            ("Wright Flyer", "Brüder Wright", "Erster gesteuerter Motorflug, 1903."),
            ("Zuse Z3", "Konrad Zuse", "Erster frei programmierbarer Rechner."),
            ("Enigma (Maschine)", "Arthur Scherbius", "Rotoren verschlüsselten jeden Anschlag neu."),
            ("Sputnik 1", "Sergei Koroljow", "Erster Satellit im Erdorbit."),
            ("Dieselmotor", "Rudolf Diesel", "Zündung allein durch verdichtete Luft."),
            ("Nipkow-Scheibe", "Paul Nipkow", "Zerlegte Bilder für die frühe Fernsehtechnik."),
            ("Telefon", "Alexander Graham Bell", "Erhielt 1876 das US-Patent."),
            ("Glühlampe", "Thomas Alva Edison", "Machte die Kohlefadenlampe marktreif."),
            ("Dynamit", "Alfred Nobel", "1867 patentiert, Grundlage der Nobelpreise."),
            ("Luftschiff", "Ferdinand von Zeppelin", "Erster Aufstieg 1900 über dem Bodensee."),
        ],
    ),
    dict(
        subject="technik", slug="bild-heimcomputer-hersteller",
        title="Heimcomputer im Bild",
        description="Von welchem Hersteller stammt das Gerät?",
        difficulty="hard", source_title="Heimcomputer",
        source_url="https://de.wikipedia.org/wiki/Heimcomputer",
        pairs=[
            ("Commodore 64", "Commodore", "Meistverkaufter Heimcomputer aller Zeiten."),
            ("Sinclair ZX Spectrum", "Sinclair", "Gummitastatur und Farbe auf dem Fernseher."),
            ("Apple II", "Apple", "Mit VisiCalc im Büro angekommen."),
            ("IBM Personal Computer", "IBM", "Der offene Aufbau ermöglichte die Nachbauten."),
            ("Atari 2600", "Atari", "Machte Steckmodule zum Standard."),
            ("Nintendo Entertainment System", "Nintendo", "Rettete den Konsolenmarkt nach 1983."),
            ("Sega Mega Drive", "Sega", "Der große Rivale des Super Nintendo."),
            ("PlayStation", "Sony", "Setzte auf CD statt auf Module."),
            ("Xbox", "Microsoft", "Erste Konsole mit Festplatte serienmäßig."),
            ("Amstrad CPC", "Amstrad", "In Deutschland als Schneider CPC verkauft."),
            ("Amiga 500", "Commodore International", "Grafik und Ton weit über dem Zeitüblichen."),
        ],
    ),
    dict(
        subject="essen-trinken", slug="bild-getraenke-laender",
        title="Getränke im Bild",
        description="Aus welchem Land stammt das Getränk?",
        difficulty="medium", source_title="Spirituose",
        source_url="https://de.wikipedia.org/wiki/Spirituose",
        pairs=[
            ("Sake", "Japan", "Aus Reis gebraut, nicht gebrannt."),
            ("Tequila", "Mexiko", "Aus blauer Agave, mit geschützter Herkunft."),
            ("Scotch Whisky", "Schottland", "Muss mindestens drei Jahre reifen."),
            ("Grappa", "Italien", "Aus Traubentrester gebrannt."),
            ("Ouzo", "Griechenland", "Anisschnaps, der sich mit Wasser trübt."),
            ("Wodka", "Russland", "Aus Getreide oder Kartoffeln gebrannt."),
            ("Cachaça", "Brasilien", "Grundlage der Caipirinha."),
            ("Soju", "Südkorea", "Meistverkaufte Spirituose der Welt."),
            ("Portwein", "Portugal", "Die Gärung wird mit Weinbrand gestoppt."),
            ("Calvados", "Frankreich", "Apfelbrand aus der Normandie."),
            ("Mate-Tee", "Argentinien", "Wird aus einer Kalebasse getrunken."),
            ("Baijiu", "China", "Aus Hirse oder Sorghum gebrannt."),
        ],
    ),
]
