"""Picture boards, batch 1. Data only -- `build_pictures.py` resolves and writes them.

Every category here is a photograph and every answer a word. `properties`
defaults to P18, Wikidata's curated "image of this thing".
"""

BOARDS = [
    dict(
        subject="geografie", slug="bild-wahrzeichen-laender",
        title="Wahrzeichen der Welt", description="In welchem Land steht dieses Bauwerk?",
        difficulty="medium", source_title="Wahrzeichen",
        source_url="https://de.wikipedia.org/wiki/Wahrzeichen",
        pairs=[
            ("Eiffelturm", "Frankreich", "Für die Weltausstellung 1889 gebaut."),
            ("Kolosseum", "Italien", "Amphitheater für rund 50000 Zuschauer."),
            ("Freiheitsstatue", "USA", "Ein Geschenk Frankreichs zum Unabhängigkeitsjubiläum."),
            ("Taj Mahal", "Indien", "Grabmal aus weißem Marmor in Agra."),
            ("Sagrada Família", "Spanien", "Seit 1882 im Bau, Entwurf von Gaudí."),
            ("Big Ben", "Vereinigtes Königreich", "Eigentlich der Name der Glocke, nicht des Turms."),
            ("Brandenburger Tor", "Deutschland", "Nach dem Vorbild der Athener Propyläen."),
            ("Atomium", "Belgien", "Eine Eisenzelle, milliardenfach vergrößert."),
            ("Chinesische Mauer", "China", "Über Jahrhunderte in Abschnitten errichtet."),
            ("Opernhaus von Sydney", "Australien", "Die Schalendächer wirken wie geblähte Segel."),
            ("Machu Picchu", "Peru", "Inkastadt auf 2400 Metern Höhe."),
            ("Burj Khalifa", "Vereinigte Arabische Emirate", "Mit 828 Metern das höchste Bauwerk der Welt."),
            ("Christus der Erlöser", "Brasilien", "30 Meter hoch über der Bucht von Rio."),
            ("Petra (Stadt)", "Jordanien", "In roten Sandstein geschlagene Nabatäerstadt."),
        ],
    ),
    dict(
        subject="geografie", slug="bild-bruecken-laender",
        title="Brücken der Welt", description="In welchem Land steht die Brücke?",
        difficulty="hard", source_title="Brücke",
        source_url="https://de.wikipedia.org/wiki/Br%C3%BCcke",
        pairs=[
            ("Golden Gate Bridge", "USA", "Ihr Rot heißt offiziell International Orange."),
            ("Tower Bridge", "Vereinigtes Königreich", "Eine Klappbrücke, keine Hängebrücke."),
            ("Karlsbrücke", "Tschechien", "Über die Moldau, gesäumt von Heiligenfiguren."),
            ("Rialtobrücke", "Italien", "Älteste der Brücken über den Canal Grande."),
            ("Kapellbrücke", "Schweiz", "Überdachte Holzbrücke mit Wasserturm."),
            ("Erasmusbrücke", "Niederlande", "Wegen ihrer Form der Schwan genannt."),
            ("Vasco-da-Gama-Brücke", "Portugal", "Über zwölf Kilometer lang, über den Tejo."),
            ("Sydney Harbour Bridge", "Australien", "Wegen ihrer Form Kleiderbügel genannt."),
            ("Akashi-Kaikyō-Brücke", "Japan", "Ein Erdbeben verlängerte sie während des Baus."),
            ("Viadukt von Millau", "Frankreich", "Höher als der Eiffelturm."),
            ("Ponte Vecchio", "Italien", "Doppelt"),
            ("Stari Most", "Bosnien und Herzegowina", "1993 zerstört, 2004 wieder aufgebaut."),
            ("Chengyang-Brücke", "China", "Holzbrücke mit Pagodentürmen, ohne Nägel gebaut."),
            ("Ólafsvíkurbrú", "Island", "Doppelt"),
        ],
    ),
    dict(
        subject="kunst-kultur", slug="bild-gemaelde-maler",
        title="Gemälde & ihre Maler", description="Wer hat dieses Bild gemalt?",
        difficulty="hard", source_title="Malerei",
        source_url="https://de.wikipedia.org/wiki/Malerei",
        pairs=[
            ("Mona Lisa", "Leonardo da Vinci", "Um 1503 entstanden, heute im Louvre."),
            ("Die Nachtwache", "Rembrandt", "Eine Schützengilde, dramatisch beleuchtet."),
            ("Der Schrei", "Edvard Munch", "Es existieren mehrere Fassungen."),
            ("Sternennacht", "Vincent van Gogh", "Gemalt aus dem Fenster einer Heilanstalt."),
            ("Der Kuss (Klimt)", "Gustav Klimt", "Höhepunkt seiner Goldenen Periode."),
            ("Die Geburt der Venus (Botticelli)", "Sandro Botticelli", "Venus steht auf einer Muschel."),
            ("Das Mädchen mit dem Perlenohrgehänge", "Jan Vermeer", "Ein Blick über die Schulter."),
            ("Der Wanderer über dem Nebelmeer", "Caspar David Friedrich", "Rückenfigur über der Wolkendecke."),
            ("Die Erschaffung Adams", "Michelangelo", "Deckenfresko der Sixtinischen Kapelle."),
            ("Impression, Sonnenaufgang", "Claude Monet", "Gab dem Impressionismus den Namen."),
            ("Die Schule von Athen", "Raffael", "Platon und Aristoteles in der Bildmitte."),
            ("Der Turmbau zu Babel (Bruegel)", "Pieter Bruegel der Ältere", "Der Turm wächst schon schief."),
            ("Das Abendmahl (Leonardo da Vinci)", "Doppelt", "Doppelt"),
            ("Die Freiheit führt das Volk", "Eugène Delacroix", "Sinnbild der Julirevolution von 1830."),
        ],
    ),
    dict(
        subject="naturwissenschaft", slug="bild-hunderassen-herkunft",
        title="Hunderassen & Herkunft", description="Aus welchem Land stammt die Rasse?",
        difficulty="hard", source_title="Hunderassen",
        source_url="https://de.wikipedia.org/wiki/Hunderassen",
        pairs=[
            ("Dackel", "Deutschland", "Als Erdhund für den Bau gezüchtet."),
            ("Chihuahua (Hunderasse)", "Mexiko", "Kleinste Hunderasse der Welt."),
            ("Akita (Hunderasse)", "Japan", "Hachiko war ein Vertreter dieser Rasse."),
            ("Siberian Husky", "Russland", "Als Schlittenhund in Sibirien gezüchtet."),
            ("Labrador Retriever", "Kanada", "Ursprünglich Helfer der Fischer in Neufundland."),
            ("Berner Sennenhund", "Schweiz", "Früher Zughund auf Bauernhöfen."),
            ("Pudel", "Frankreich", "Ursprünglich ein Wasserapportierhund."),
            ("Chow-Chow", "China", "Auffällig ist die blauschwarze Zunge."),
            ("Afghanischer Windhund", "Afghanistan", "Langes Fell schützt im Gebirge."),
            ("Basenji", "Demokratische Republik Kongo", "Bellt nicht, sondern jodelt."),
            ("Border Collie", "Schottland", "Treibt Schafe durch bloßen Blick."),
            ("Ungarischer Vorstehhund", "Ungarn", "Doppelt"),
            ("Sankt-Bernhards-Hund", "Doppelt", "Doppelt"),
            ("Shar Pei", "Doppelt", "Doppelt"),
        ],
    ),
    dict(
        subject="geografie", slug="bild-berge-laender",
        title="Berge im Bild", description="In welchem Land steht der Berg?",
        difficulty="medium", source_title="Berg",
        source_url="https://de.wikipedia.org/wiki/Berg",
        pairs=[
            ("Matterhorn", "Schweiz", "Pyramide über Zermatt, 1865 erstbestiegen."),
            ("Kilimanjaro", "Tansania", "Höchster Berg Afrikas."),
            ("Denali", "USA", "Höchster Berg Nordamerikas, in Alaska."),
            ("Uluru", "Australien", "Heiliger Berg der Anangu."),
            ("Mount Everest", "Nepal", "8849 Meter, höchster Berg der Erde."),
            ("Aconcagua", "Argentinien", "Höchster Berg außerhalb Asiens."),
            ("Zugspitze", "Deutschland", "Höchster Berg des Landes, 2962 Meter."),
            ("Großglockner", "Österreich", "Höchster Berg des Landes, mit der Pasterze."),
            ("Olymp", "Griechenland", "Sitz der Götter der antiken Mythologie."),
            ("Ben Nevis", "Schottland", "Höchster Berg der Britischen Inseln."),
            ("Fudschi", "Japan", "Vulkankegel und Wahrzeichen des Landes."),
            ("Tafelberg (Südafrika)", "Südafrika", "Flache Bergkulisse über Kapstadt."),
            ("Table Mountain", "Doppelt", "Doppelt"),
            ("Cotopaxi", "Ecuador", "Einer der höchsten aktiven Vulkane der Erde."),
        ],
    ),
    dict(
        subject="essen-trinken", slug="bild-gerichte-laender",
        title="Gerichte im Bild", description="Aus welchem Land stammt das Gericht?",
        difficulty="medium", source_title="Nationalgericht",
        source_url="https://de.wikipedia.org/wiki/Nationalgericht",
        pairs=[
            ("Sushi", "Japan", "Gesäuerter Reis, meist mit rohem Fisch."),
            ("Paella", "Spanien", "Reisgericht aus Valencia, in flacher Pfanne."),
            ("Pizza Margherita", "Italien", "1889 nach der Königin benannt."),
            ("Wiener Schnitzel", "Österreich", "Die Bezeichnung ist rechtlich geschützt."),
            ("Moussaka", "Griechenland", "Auflauf aus Auberginen und Hackfleisch."),
            ("Taco", "Mexiko", "Gefaltete Maistortilla mit Füllung."),
            ("Borschtsch", "Ukraine", "Rote Bete gibt die Farbe."),
            ("Currywurst", "Deutschland", "Angeblich 1949 in Berlin erfunden."),
            ("Poutine", "Kanada", "Pommes mit Bratensauce und Käsebruch."),
            ("Ceviche", "Peru", "Roher Fisch, in Limettensaft mariniert."),
            ("Bibimbap", "Südkorea", "Alles wird vor dem Essen verrührt."),
            ("Phở", "Vietnam", "Nudelsuppe mit lange gezogener Brühe."),
            ("Falafel", "Israel", "Doppelt"),
            ("Käsefondue", "Schweiz", "Wer das Brot verliert, gibt eine Runde aus."),
        ],
    ),
    dict(
        subject="geschichte", slug="bild-schloesser-laender",
        title="Schlösser & Burgen im Bild", description="In welchem Land steht der Bau?",
        difficulty="medium", source_title="Schloss (Architektur)",
        source_url="https://de.wikipedia.org/wiki/Schloss_%28Architektur%29",
        pairs=[
            ("Schloss Neuschwanstein", "Deutschland", "Ludwig II. ließ es ab 1869 bauen."),
            ("Schloss Chambord", "Frankreich", "Renaissanceschloss mit doppelter Wendeltreppe."),
            ("Alhambra", "Spanien", "Rote Festung der Nasriden über Granada."),
            ("Windsor Castle", "Vereinigtes Königreich", "Älteste durchgehend bewohnte Burg der Welt."),
            ("Prager Burg", "Tschechien", "Größte geschlossene Burganlage der Welt."),
            ("Moskauer Kreml", "Russland", "Festung im Herzen der Hauptstadt."),
            ("Himeji-jō", "Japan", "Weiße Burg, die Erdbeben und Bomben überstand."),
            ("Törzburg", "Rumänien", "Wird als Draculaschloss vermarktet."),
            ("Schloss Kronborg", "Dänemark", "Schauplatz von Shakespeares Hamlet."),
            ("Marienburg (Ordensburg)", "Polen", "Größte Backsteinburg der Welt."),
            ("Palácio Nacional da Pena", "Portugal", "Bunter Romantikbau über Sintra."),
            ("Schloss Schönbrunn", "Österreich", "Sommerresidenz der Habsburger."),
            ("Schloss Chillon", "Schweiz", "Am Ufer des Genfersees gelegen."),
            ("Schloss Frederiksborg", "Doppelt", "Doppelt"),
        ],
    ),
    dict(
        subject="technik", slug="bild-flugzeuge-hersteller",
        title="Flugzeuge im Bild", description="Von welchem Hersteller stammt das Flugzeug?",
        difficulty="hard", source_title="Flugzeug",
        source_url="https://de.wikipedia.org/wiki/Flugzeug",
        pairs=[
            ("Boeing 747", "Boeing", "Der Jumbo mit dem markanten Buckel."),
            ("Airbus A380", "Airbus", "Zwei durchgehende Passagierdecks."),
            ("Aérospatiale-BAC Concorde", "Aérospatiale und BAC", "Überschallverkehr bis 2003."),
            ("Supermarine Spitfire", "Supermarine", "Elliptische Tragflächen als Erkennungszeichen."),
            ("Junkers Ju 52/3m", "Junkers", "Wellblechrumpf mit drei Motoren."),
            ("Douglas DC-3", "Douglas", "Machte den Linienflug wirtschaftlich."),
            ("Mikojan-Gurewitsch MiG-21", "Mikojan-Gurewitsch", "Meistgebautes Überschallflugzeug."),
            ("Antonow An-225", "Antonow", "Sechs Triebwerke, größtes Flugzeug der Welt."),
            ("Cessna 172", "Cessna", "Meistgebautes Flugzeug der Geschichte."),
            ("Lockheed SR-71", "Lockheed", "Flog schneller als Mach drei."),
            ("Saab 39 Gripen", "Saab", "Für Starts von Landstraßen ausgelegt."),
            ("Embraer E-Jets", "Embraer", "Regionaljets aus Brasilien."),
        ],
    ),
    dict(
        subject="naturwissenschaft", slug="bild-tiere-kontinente",
        title="Tiere & ihre Heimat", description="Wo lebt das Tier in freier Wildbahn?",
        difficulty="medium", source_title="Tier",
        source_url="https://de.wikipedia.org/wiki/Tier",
        pairs=[
            ("Rotes Riesenkänguru", "Australien", "Größtes lebendes Beuteltier."),
            ("Großer Panda", "China", "Frisst fast ausschließlich Bambus."),
            ("Amerikanischer Bison", "Nordamerika", "Bestand einst fast ausgerottet."),
            ("Königspinguin", "Antarktis", "Brütet das Ei auf den Füßen aus."),
            ("Ringelschwanzmaki", "Madagaskar", "Kommt nur auf dieser Insel vor."),
            ("Zweifingerfaultier", "Südamerika", "Verbringt fast das ganze Leben hängend."),
            ("Bengaltiger", "Indien", "Größte lebende Katzenart."),
            ("Eisbär", "Arktis", "Unter dem weißen Fell ist die Haut schwarz."),
            ("Erdmännchen", "Südliches Afrika", "Wache steht aufrecht am Bau."),
            ("Komodowaran", "Indonesien", "Größte lebende Echse."),
            ("Kiwis", "Neuseeland", "Flugunfähiger Vogel mit langem Schnabel."),
            ("Braunbär", "Europa", "In den Karpaten lebt der größte Bestand."),
        ],
    ),
    dict(
        subject="kunst-kultur", slug="bild-bauwerke-baustile",
        title="Bauwerke & Baustile", description="In welchem Baustil wurde der Bau errichtet?",
        difficulty="hard", source_title="Baustil",
        source_url="https://de.wikipedia.org/wiki/Baustil",
        pairs=[
            ("Kölner Dom", "Gotik", "Spitzbögen und Strebewerk, begonnen 1248."),
            ("Hagia Sophia", "Byzantinische Architektur", "Riesenkuppel über Pendentifs."),
            ("Schloss Versailles", "Barock", "Prunk und strenge Symmetrie."),
            ("Bauhaus (Gebäude)", "Moderne", "Glasvorhangfassade von 1926."),
            ("Petersdom", "Renaissance", "Kuppel nach dem Entwurf Michelangelos."),
            ("Alhambra", "Maurische Architektur", "Stuckornamente und Muqarnas."),
            ("Sydney Opera House", "Doppelt", "Doppelt"),
            ("Chrysler Building", "Art déco", "Spitze aus rostfreiem Stahl."),
            ("Basilius-Kathedrale", "Russische Architektur", "Bunte Zwiebeltürme am Roten Platz."),
            ("Pantheon (Rom)", "Römische Antike", "Größte unbewehrte Betonkuppel der Welt."),
            ("Guggenheim-Museum Bilbao", "Dekonstruktivismus", "Titanhülle ohne gerade Flächen."),
            ("Wieskirche", "Rokoko", "Verspielte Stuckdekoration im Innenraum."),
            ("Chichén Itzá", "Maya-Architektur", "Die Stufenpyramide des Kukulcán."),
        ],
    ),
]
