"""Picture boards, batch 2. Data only -- `build_pictures.py` resolves and writes them.

`properties` names the Wikidata image properties to follow, tried in order.
P18 ("image") is the default and the one the ingest pipeline uses. It is not the
only curated image Wikidata keeps, and the others open boards P18 cannot fill:

    P41   flag                    a country's flag
    P94   coat of arms            a state's arms
    P242  locator map image       its outline on the globe

Everything still lands on a Commons file name, which is what `image_file` stores
and what `Special:FilePath` can render. A board that cannot reach ten verified
images is dropped by the generator rather than padded.
"""

BOARDS = [
    # --- boards that P18 alone cannot fill ---------------------------------
    dict(
        subject="geografie", slug="bild-flaggen-hauptstaedte",
        title="Flaggen & Hauptstädte",
        description="Welche Stadt ist die Hauptstadt zu dieser Flagge?",
        difficulty="medium", source_title="Flagge",
        source_url="https://de.wikipedia.org/wiki/Flagge", properties=("P41",),
        pairs=[
            ("Japan", "Tokio", "Die rote Scheibe steht für die Sonne."),
            ("Brasilien", "Brasília", "Der Sternenhimmel zeigt einen Novemberabend 1889."),
            ("Kanada", "Ottawa", "Das Ahornblatt hat elf Zacken."),
            ("Ägypten", "Kairo", "In der Mitte der Adler des Saladin."),
            ("Norwegen", "Oslo", "Ein blaues Kreuz im weißen Kreuz."),
            ("Portugal", "Lissabon", "Die Armillarsphäre erinnert an die Seefahrt."),
            ("Griechenland", "Athen", "Neun Streifen für die Silben eines Freiheitsrufs."),
            ("Südkorea", "Seoul", "In der Mitte das Yin-und-Yang-Zeichen."),
            ("Mexiko", "Mexiko-Stadt", "Ein Adler mit Schlange auf einem Kaktus."),
            ("Kenia", "Nairobi", "Ein Massai-Schild mit zwei Speeren."),
            ("Vietnam", "Hanoi", "Ein gelber Stern auf rotem Grund."),
            ("Argentinien", "Buenos Aires", "Die Sonne des Mai in der Mitte."),
        ],
    ),
    dict(
        subject="geografie", slug="bild-flaggen-waehrungen",
        title="Flaggen & Währungen",
        description="Womit wird in diesem Land bezahlt?",
        difficulty="hard", source_title="Flagge",
        source_url="https://de.wikipedia.org/wiki/Flagge", properties=("P41",),
        pairs=[
            ("Schweiz", "Franken", "Eine der beiden quadratischen Nationalflaggen."),
            ("Polen", "Złoty", "Der Name der Währung bedeutet golden."),
            ("Indien", "Rupie", "Das Rad in der Mitte heißt Ashoka-Chakra."),
            ("Russland", "Rubel", "Eine der ältesten noch genutzten Währungen."),
            ("Dänemark", "Dänische Krone", "Gilt als älteste durchgehend genutzte Flagge."),
            ("Vereinigtes Königreich", "Pfund Sterling", "Drei Kreuze in einer Flagge vereint."),
            ("Südafrika", "Rand", "Sechs Farben, mehr als jede andere Nationalflagge."),
            ("Thailand", "Baht", "Fünf Streifen für Nation, Religion und König."),
            ("Israel", "Schekel", "Der Davidstern zwischen zwei Streifen."),
            ("Türkei", "Türkische Lira", "Halbmond und Stern auf Rot."),
            ("Schweden", "Schwedische Krone", "Gelbes Kreuz auf blauem Grund."),
            ("Japan", "Yen", "Die Sonne ohne jedes weitere Zeichen."),
        ],
    ),
    dict(
        subject="geografie", slug="bild-umrisse-groesste-staedte",
        title="Länder auf der Karte",
        description="Welche Stadt ist die größte des Landes — die Hauptstadt ist es nicht?",
        difficulty="hard", source_title="Landkarte",
        source_url="https://de.wikipedia.org/wiki/Landkarte", properties=("P242",),
        pairs=[
            ("Türkei", "Istanbul", "Ankara regiert, doch Istanbul ist weit größer."),
            ("USA", "New York", "Washington ist nur Regierungssitz."),
            ("Kanada", "Toronto", "Ottawa wurde 1857 als Kompromiss gewählt."),
            ("Australien", "Sydney", "Canberra entstand als Kompromiss zu Melbourne."),
            ("Brasilien", "São Paulo", "Größte Stadt der Südhalbkugel."),
            ("Indien", "Mumbai", "Finanzzentrum des Landes, früher Bombay."),
            ("Schweiz", "Zürich", "Bern ist lediglich Bundesstadt."),
            ("Marokko", "Casablanca", "Wirtschaftszentrum an der Atlantikküste."),
            ("Vietnam", "Ho-Chi-Minh-Stadt", "Früher Saigon, größer als Hanoi."),
            ("Neuseeland", "Auckland", "Rund ein Drittel des Landes lebt hier."),
            ("Nigeria", "Lagos", "Eine der größten Städte Afrikas."),
            ("Pakistan", "Karatschi", "Hafenstadt, bis 1959 Hauptstadt."),
        ],
    ),
    dict(
        subject="geografie", slug="bild-wappen-landeshauptstaedte",
        title="Wappen der Bundesländer",
        description="Welche Stadt ist die Landeshauptstadt?",
        difficulty="hard", source_title="Wappen",
        source_url="https://de.wikipedia.org/wiki/Wappen", properties=("P94",),
        pairs=[
            ("Bayern", "München", "Die weiß-blauen Rauten in der Mitte."),
            ("Sachsen", "Dresden", "Ein Rautenkranz quert die Balken."),
            ("Hessen", "Wiesbaden", "Der rot-weiß gestreifte Löwe."),
            ("Thüringen", "Erfurt", "Ein Löwe mit acht Sternen."),
            ("Saarland", "Saarbrücken", "Vier Felder für vier historische Gebiete."),
            ("Brandenburg", "Potsdam", "Der rote Adler auf Weiß."),
            ("Niedersachsen", "Hannover", "Das weiße Ross auf Rot."),
            ("Schleswig-Holstein", "Kiel", "Zwei Löwen und ein Nesselblatt."),
            ("Mecklenburg-Vorpommern", "Schwerin", "Stierkopf und Greif in einem Schild."),
            ("Rheinland-Pfalz", "Mainz", "Rad, Kreuz und Löwe nebeneinander."),
            ("Baden-Württemberg", "Stuttgart", "Drei schwarze Löwen auf Gold."),
            ("Sachsen-Anhalt", "Magdeburg", "Geteilt zwischen Adler und Bär."),
        ],
    ),

    # --- further P18 boards -------------------------------------------------
    dict(
        subject="naturwissenschaft", slug="bild-elemente-symbole",
        title="Elemente im Bild",
        description="Welches Symbol steht für dieses Element?",
        difficulty="hard", source_title="Chemisches Element",
        source_url="https://de.wikipedia.org/wiki/Chemisches_Element",
        pairs=[
            ("Gold", "Au", "Vom lateinischen aurum."),
            ("Schwefel", "S", "Gelbe Kristalle, brennt mit blauer Flamme."),
            ("Kupfer", "Cu", "Vom lateinischen cuprum, nach Zypern."),
            ("Quecksilber", "Hg", "Einziges bei Raumtemperatur flüssiges Metall."),
            ("Eisen", "Fe", "Vom lateinischen ferrum."),
            ("Blei", "Pb", "Vom lateinischen plumbum."),
            ("Zink", "Zn", "Schützt als Überzug den Stahl vor Rost."),
            ("Silber", "Ag", "Bester elektrischer Leiter aller Metalle."),
            ("Wismut", "Bi", "Bildet auffällig treppenförmige Kristalle."),
            ("Aluminium", "Al", "War vor der Elektrolyse teurer als Gold."),
            ("Iod", "I", "Sublimiert zu violettem Dampf."),
            ("Kohlenstoff", "C", "Als Diamant und als Graphit dasselbe Element."),
        ],
    ),
    dict(
        subject="geschichte", slug="bild-persoenlichkeiten-wirken",
        title="Porträts der Geschichte",
        description="Wofür steht diese Person?",
        difficulty="hard", source_title="Porträt",
        source_url="https://de.wikipedia.org/wiki/Portr%C3%A4t",
        pairs=[
            ("Albert Einstein", "Relativitätstheorie", "Den Nobelpreis erhielt er für etwas anderes."),
            ("Marie Curie", "Radioaktivität", "Zwei Nobelpreise in zwei Fächern."),
            ("Charles Darwin", "Evolutionstheorie", "Fünf Jahre an Bord der Beagle."),
            ("Nikola Tesla", "Wechselstrom", "Setzte sich gegen Edisons Gleichstrom durch."),
            ("Mahatma Gandhi", "Gewaltloser Widerstand", "Der Salzmarsch als bekannteste Aktion."),
            ("Rosa Parks", "Busboykott von Montgomery", "Sie blieb 1955 einfach sitzen."),
            ("Alan Turing", "Turingmaschine", "Modell dessen, was berechenbar ist."),
            ("Ada Lovelace", "Erstes Computerprogramm", "Für eine Maschine, die nie gebaut wurde."),
            ("Ludwig van Beethoven", "Neunte Sinfonie", "Komponiert, als er längst taub war."),
            ("Frida Kahlo", "Selbstbildnisse", "Ein Großteil ihres Werks zeigt sie selbst."),
            ("Nelson Mandela", "Ende der Apartheid", "27 Jahre Haft, dann Präsident."),
            ("Johannes Gutenberg", "Buchdruck mit Lettern", "Bewegliche Metalllettern, um 1450."),
        ],
    ),
    dict(
        subject="kunst-kultur", slug="bild-sakralbauten-religionen",
        title="Sakralbauten & Religionen",
        description="Zu welcher Religion gehört der Bau?",
        difficulty="hard", source_title="Sakralbau",
        source_url="https://de.wikipedia.org/wiki/Sakralbau",
        pairs=[
            ("Kölner Dom", "Christentum", "Gotische Kathedrale, 1880 vollendet."),
            ("Sultan-Ahmed-Moschee", "Islam", "Wegen der Fliesen Blaue Moschee genannt."),
            ("Harmandir Sahib", "Sikhismus", "Der Goldene Tempel von Amritsar."),
            ("Borobudur", "Buddhismus", "Größte buddhistische Tempelanlage der Welt."),
            ("Meenakshi-Tempel", "Hinduismus", "Türme voller bunt bemalter Figuren."),
            ("Große Synagoge (Budapest)", "Judentum", "Größte Synagoge Europas."),
            ("Ise-jingū", "Shintō", "Wird alle zwanzig Jahre neu errichtet."),
            ("Lotustempel", "Bahaitum", "Neun Seiten, allen Religionen offen."),
            ("Himmelstempel", "Daoismus", "Hier beteten die Kaiser um gute Ernten."),
            ("Dilwara-Tempel", "Jainismus", "Marmorarbeiten von außerordentlicher Feinheit."),
            ("Atashkadeh-ye Yazd", "Zoroastrismus", "Das Feuer soll seit Jahrhunderten brennen."),
        ],
    ),
    dict(
        subject="naturwissenschaft", slug="bild-katzenrassen-herkunft",
        title="Katzenrassen & Herkunft",
        description="Aus welchem Land stammt die Rasse?",
        difficulty="hard", source_title="Katzenrassen",
        source_url="https://de.wikipedia.org/wiki/Katzenrassen",
        pairs=[
            ("Siamkatze", "Thailand", "Die dunklen Abzeichen entstehen durch Wärme."),
            ("Perserkatze", "Iran", "Langes Fell, kurze Nase."),
            ("Maine Coon", "USA", "Eine der größten Hauskatzenrassen."),
            ("Norwegische Waldkatze", "Norwegen", "Dichtes Fell gegen den Winter."),
            ("Russisch Blau", "Russland", "Silbrig schimmerndes Doppelfell."),
            ("Britisch Kurzhaar", "Vereinigtes Königreich", "Rundes Gesicht, plüschiges Fell."),
            ("Türkisch Angora", "Türkei", "Eine der ältesten bekannten Rassen."),
            ("Abessinierkatze", "Äthiopien", "Getickte Haare wie bei einem Wildkaninchen."),
            ("Sphynx (Katze)", "Kanada", "Fast haarlos, dafür sehr warm."),
            ("Chartreux", "Frankreich", "Der Sage nach von Mönchen gezüchtet."),
            ("Japanese Bobtail", "Japan", "Kurzer, geknickter Schwanz."),
        ],
    ),
    dict(
        subject="geografie", slug="bild-wasserfaelle-laender",
        title="Wasserfälle im Bild",
        description="In welchem Land stürzt der Wasserfall?",
        difficulty="hard", source_title="Wasserfall",
        source_url="https://de.wikipedia.org/wiki/Wasserfall",
        pairs=[
            ("Salto Ángel", "Venezuela", "Höchster freifallender Wasserfall der Erde."),
            ("Gullfoss", "Island", "Der goldene Wasserfall im Süden der Insel."),
            ("Rheinfall", "Schweiz", "Größter Wasserfall Europas nach Wassermenge."),
            ("Krimmler Wasserfälle", "Österreich", "385 Meter in drei Stufen."),
            ("Yosemite Falls", "USA", "Höchster Wasserfall Nordamerikas."),
            ("Kaieteur-Fälle", "Guyana", "Einstufig, mitten im Regenwald."),
            ("Tugela Falls", "Südafrika", "Stürzt von den Drakensbergen."),
            ("Jog Falls", "Indien", "Fällt in vier getrennten Strahlen."),
            ("Sutherland Falls", "Neuseeland", "580 Meter im Fiordland."),
            ("Montmorency-Fälle", "Kanada", "Höher als die Niagarafälle."),
            ("Ban Gioc", "Vietnam", "Terrassenfall an der Grenze zu China."),
        ],
    ),
    dict(
        subject="technik", slug="bild-autos-marken",
        title="Klassische Autos",
        description="Von welcher Marke stammt das Auto?",
        difficulty="hard", source_title="Automobil",
        source_url="https://de.wikipedia.org/wiki/Automobil",
        pairs=[
            ("VW Käfer", "Volkswagen", "Über 21 Millionen Mal gebaut."),
            ("Citroën 2CV", "Citroën", "Die Ente, gebaut für schlechte Landstraßen."),
            ("Fiat Nuova 500", "Fiat", "Der Cinquecento motorisierte Italien."),
            ("Ford Modell T", "Ford", "Erstes Auto vom Fließband."),
            ("Porsche 911", "Porsche", "Der Motor sitzt hinter der Hinterachse."),
            ("Renault 4", "Renault", "Erstes Großserienauto mit Steilheck."),
            ("Jaguar E-Type", "Jaguar", "Von Enzo Ferrari als schönstes Auto gelobt."),
            ("Chevrolet Corvette", "Chevrolet", "Karosserie aus Kunststoff."),
            ("Trabant 601", "Sachsenring", "Karosserie aus Duroplast."),
            ("Lada Niva", "Lada", "Geländewagen mit selbsttragender Karosserie."),
            ("DeLorean DMC-12", "DeLorean Motor Company", "Flügeltüren und blanke Edelstahlhaut."),
        ],
    ),
    dict(
        subject="essen-trinken", slug="bild-kaese-laender",
        title="Käse im Bild",
        description="Aus welchem Land stammt der Käse?",
        difficulty="hard", source_title="Käse",
        source_url="https://de.wikipedia.org/wiki/K%C3%A4se",
        pairs=[
            ("Gorgonzola (Käse)", "Italien", "Blauschimmelkäse aus der Lombardei."),
            ("Roquefort (Käse)", "Frankreich", "Reift in Kalkhöhlen der Causses."),
            ("Manchego", "Spanien", "Schafskäse aus La Mancha."),
            ("Feta", "Griechenland", "In Salzlake gereifter Schafskäse."),
            ("Gouda (Käse)", "Niederlande", "Benannt nach der Marktstadt."),
            ("Cheddar (Käse)", "England", "Benannt nach einem Dorf in Somerset."),
            ("Emmentaler", "Schweiz", "Bekannt für seine großen Löcher."),
            ("Halloumi", "Zypern", "Bleibt beim Braten in Form."),
            ("Danablu", "Dänemark", "In den 1920er Jahren entwickelt."),
            ("Oscypek", "Polen", "Geräucherter Schafskäse aus der Tatra."),
            ("Harzer Käse", "Deutschland", "Sauermilchkäse, fast ohne Fett."),
            ("Parmigiano Reggiano", "Italien", "Mindestens zwölf Monate gereift."),
            ("Graviera", "Griechenland", "Hartkäse, meist aus Schafmilch."),
            ("Gruyère", "Frankreich", "Doppelt"),
        ],
    ),
    dict(
        subject="musik", slug="bild-instrumente-herkunft",
        title="Instrumente im Bild",
        description="Woher stammt das Instrument?",
        difficulty="medium", source_title="Musikinstrument",
        source_url="https://de.wikipedia.org/wiki/Musikinstrument",
        pairs=[
            ("Didgeridoo", "Australien", "Blasinstrument der Aborigines."),
            ("Sitar", "Indien", "Mitschwingende Resonanzsaiten geben den Klang."),
            ("Balalaika", "Russland", "Dreieckiger Korpus, drei Saiten."),
            ("Dudelsack", "Schottland", "Der Luftsack hält den Ton beim Atmen."),
            ("Alphorn", "Schweiz", "Bis zu vier Meter lang, ohne Ventile."),
            ("Koto", "Japan", "Wölbbrettzither mit verschiebbaren Stegen."),
            ("Erhu", "China", "Zweisaitige Fiedel, Bogen zwischen den Saiten."),
            ("Bouzouki", "Griechenland", "Prägt den Klang des Rebetiko."),
            ("Ukulele", "Hawaii", "Aus einem portugiesischen Instrument entstanden."),
            ("Bandoneon", "Argentinien", "In Deutschland erfunden, im Tango zu Hause."),
            ("Djembe", "Mali", "Bechertrommel, mit bloßen Händen gespielt."),
            ("Panflöte", "Peru", "Rohre unterschiedlicher Länge nebeneinander."),
            ("Charango", "Bolivien", "Kleine Laute, früher aus einem Gürteltierpanzer."),
            ("Nyckelharpa", "Schweden", "Tasten verkürzen die Saiten statt der Finger."),
            ("Bodhrán", "Irland", "Rahmentrommel, mit einem Doppelschlägel gespielt."),
        ],
    ),
]
