-- Essen & Trinken, file 1 of 2. Twenty questions, medium and hard.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs, fakes) as (
    values

    ('essen-trinken', 'gewuerze-pflanzenteile', 'Gewürze & Pflanzenteile',
     'Welcher Teil der Pflanze ist das Gewürz?',
     'hard', 'Gewürz', 'https://de.wikipedia.org/wiki/Gew%C3%BCrz',
     '[["Zimt", "Rinde", "Die innere Rinde wird abgeschält und rollt sich beim Trocknen."],
       ["Safran", "Blütennarben", "Für ein Kilo braucht es rund 150000 Blüten."],
       ["Gewürznelken", "Blütenknospen", "Vor dem Aufblühen gepflückt und getrocknet."],
       ["Vanille", "Fruchtkapsel einer Orchidee", "Nur wenige Orchideenarten liefern sie."],
       ["Muskatnuss", "Samenkern", "Die rote Hülle wird als Macis getrennt verkauft."],
       ["Ingwer", "Wurzelstock", "Botanisch ein unterirdischer Spross."],
       ["Kardamom", "Samenkapseln", "Nach Safran und Vanille das teuerste Gewürz."],
       ["Lorbeer", "Blätter", "Werden mitgekocht und vor dem Servieren entfernt."],
       ["Pfeffer", "Unreife Beeren", "Schwarz, grün und weiß stammen von derselben Pflanze."],
       ["Kümmel", "Früchte", "Oft mit Kreuzkümmel verwechselt, botanisch weit entfernt."],
       ["Wacholder", "Beerenzapfen", "Botanisch keine Beere, sondern ein Zapfen."],
       ["Paprikapulver", "Getrocknete Fruchtschoten", "Ungarn unterscheidet acht Schärfegrade."]]'::jsonb,
     '[["Harz des Stammes", "So gewinnt man Weihrauch und Myrrhe, die hier fehlen."],
       ["Zwiebel der Pflanze", "Das wären Knoblauch und Schalotte, beide stehen nicht auf dem Brett."]]'::jsonb),

    ('essen-trinken', 'pastaformen', 'Pastaformen & ihre Namen',
     'Was bedeutet der Name auf Italienisch?',
     'medium', 'Teigwaren', 'https://de.wikipedia.org/wiki/Teigwaren',
     '[["Spaghetti", "Schnürchen", "Von spago, die Schnur."],
       ["Penne", "Federkiele", "Schräg abgeschnitten wie eine Schreibfeder."],
       ["Farfalle", "Schmetterlinge", "In der Mitte zusammengedrückt."],
       ["Fusilli", "Spindeln", "Ursprünglich um einen Stab gedreht."],
       ["Linguine", "Zünglein", "Flach statt rund im Querschnitt."],
       ["Orecchiette", "Öhrchen", "Mit dem Daumen geformt, aus Apulien."],
       ["Conchiglie", "Muscheln", "Die Wölbung fängt die Sauce auf."],
       ["Vermicelli", "Würmchen", "Dünner als Spaghetti."],
       ["Rigatoni", "Geriffelte", "Die Rillen halten die Sauce."],
       ["Tagliatelle", "Geschnittene", "Aus Bandnudelteig gerollt und geschnitten."],
       ["Cannelloni", "Große Rohre", "Werden gefüllt und überbacken."],
       ["Capellini", "Härchen", "Die dünnste gebräuchliche Nudel."]]'::jsonb,
     '[["Heizkörper", "So heißen Radiatori, die hier nicht stehen."],
       ["Fingerhüte", "Das wären Ditalini, und die fehlen auf dem Brett."]]'::jsonb),

    ('essen-trinken', 'nationalgetraenke', 'Nationalgetränke',
     'Aus welchem Land stammt das Getränk?',
     'medium', 'Getränk', 'https://de.wikipedia.org/wiki/Getr%C3%A4nk',
     '[["Caipirinha", "Brasilien", "Aus Cachaça, Limette und Zucker."],
       ["Pisco Sour", "Peru", "Mit Eiweißschaum und Angosturatropfen."],
       ["Mojito", "Kuba", "Rum, Minze, Limette und Soda."],
       ["Mate", "Argentinien", "Wird aus einer Kalebasse mit Metallhalm getrunken."],
       ["Minztee", "Marokko", "Aus großer Höhe eingeschenkt, damit er schäumt."],
       ["Masala Chai", "Indien", "Schwarztee mit Milch und Gewürzen."],
       ["Soju", "Südkorea", "Meistverkaufte Spirituose der Welt."],
       ["Baijiu", "China", "Aus Hirse oder Sorghum gebrannt."],
       ["Raki", "Türkei", "Trübt sich mit Wasser, daher Löwenmilch genannt."],
       ["Pilsner Bier", "Tschechien", "Das erste helle Lagerbier, 1842 in Pilsen."],
       ["Stout", "Irland", "Dunkles Bier mit geröstetem Malz."],
       ["Rum Punch", "Jamaika", "Ein Teil sauer, zwei süß, drei stark, vier schwach."]]'::jsonb,
     '[["Mexiko", "Tequila wäre das Getränk dazu, es steht nicht auf dem Brett."],
       ["Japan", "Sake fehlt in dieser Liste."]]'::jsonb),

    ('essen-trinken', 'kochtechniken', 'Kochtechniken',
     'Was geschieht bei dieser Technik?',
     'hard', 'Garen', 'https://de.wikipedia.org/wiki/Garen',
     '[["Blanchieren", "Kurz kochen, dann abschrecken", "Erhält Farbe und stoppt das Garen."],
       ["Pochieren", "Knapp unter dem Siedepunkt", "Für Eier und Fisch, ohne Sprudeln."],
       ["Sautieren", "Schwenken bei hoher Hitze", "Vom französischen sauter, springen."],
       ["Schmoren", "Anbraten, dann Flüssigkeit", "Macht zähe Stücke zart."],
       ["Sous-vide", "Vakuumbeutel im Wasserbad", "Stundenlang bei genau geregelter Temperatur."],
       ["Flambieren", "Alkohol abbrennen lassen", "Der Geschmack bleibt, der Alkohol geht."],
       ["Gratinieren", "Oberhitze für die Kruste", "Käse oder Semmelbrösel obenauf."],
       ["Karamellisieren", "Zucker bräunen lassen", "Neue Aromen entstehen erst beim Bräunen."],
       ["Konfieren", "Garen in Fett", "Klassisch für Entenkeulen."],
       ["Fermentieren", "Mikroorganismen arbeiten lassen", "Aus Kohl wird Sauerkraut."],
       ["Räuchern", "Rauch als Konservierung", "Kalt für Lachs, heiß für Makrele."],
       ["Sieden", "Gleichmäßig ohne starkes Wallen", "Schont die Struktur des Garguts."]]'::jsonb,
     '[["Bei niedriger Hitze trocknen", "Das ist Dörren, keine Technik auf diesem Brett."],
       ["Über offener Flamme rösten", "Grillen kommt in dieser Liste nicht vor."]]'::jsonb),

    ('essen-trinken', 'brotsorten', 'Brotsorten & Länder',
     'Woher stammt das Brot?',
     'medium', 'Brot', 'https://de.wikipedia.org/wiki/Brot',
     '[["Baguette", "Frankreich", "Gesetzlich sind nur vier Zutaten erlaubt."],
       ["Ciabatta", "Italien", "Erst in den 1980er Jahren erfunden."],
       ["Pumpernickel", "Deutschland", "Bis zu 24 Stunden bei niedriger Hitze gebacken."],
       ["Naan", "Indien", "An der Wand des Tandoor-Ofens gebacken."],
       ["Pita", "Griechenland", "Bildet beim Backen eine Tasche."],
       ["Tortilla", "Mexiko", "Aus mit Kalkwasser behandeltem Mais."],
       ["Injera", "Äthiopien", "Aus Teffmehl, dient zugleich als Teller."],
       ["Knäckebrot", "Schweden", "Früher mit einem Loch zum Aufhängen."],
       ["Challa", "Israel", "Geflochten, für den Sabbat."],
       ["Lavash", "Armenien", "Hauchdünn, als Welterbe anerkannt."],
       ["Bannock", "Schottland", "Flach, ursprünglich auf einer Platte gebacken."],
       ["Damper", "Australien", "In der Glut des Lagerfeuers gebacken."]]'::jsonb,
     '[["Türkei", "Simit und Pide wären dort zu Hause, hier fehlen sie."],
       ["Irland", "Das Sodabrot steht nicht auf dem Brett."]]'::jsonb),

    ('essen-trinken', 'weinregionen', 'Weinregionen & Länder',
     'In welchem Land liegt die Region?',
     'hard', 'Weinbaugebiet',
     'https://de.wikipedia.org/wiki/Weinbaugebiet',
     '[["Bordeaux", "Frankreich", "Berühmt für Verschnitte aus mehreren Rebsorten."],
       ["Rioja", "Spanien", "Reifung im Eichenfass bestimmt die Klassifikation."],
       ["Chianti", "Italien", "Erkennbar am schwarzen Hahn auf dem Etikett."],
       ["Douro", "Portugal", "Terrassen am Fluss, Heimat des Portweins."],
       ["Mosel", "Deutschland", "Steilster Weinberg Europas liegt hier."],
       ["Napa Valley", "USA", "1976 schlugen die Weine in Paris die französischen."],
       ["Barossa Valley", "Australien", "Sehr alte Shiraz-Reben."],
       ["Marlborough", "Neuseeland", "Machte Sauvignon Blanc weltweit bekannt."],
       ["Mendoza", "Argentinien", "Weinberge auf über tausend Metern Höhe."],
       ["Stellenbosch", "Südafrika", "Zentrum des südafrikanischen Weinbaus."],
       ["Tokaj", "Ungarn", "Süßwein aus edelfaulen Beeren."],
       ["Wachau", "Österreich", "Terrassen an der Donau, Welterbe."]]'::jsonb,
     '[["Chile", "Das Colchagua-Tal fehlt auf diesem Brett."],
       ["Griechenland", "Nemea und Santorin stehen hier nicht."]]'::jsonb),

    ('essen-trinken', 'eierspeisen', 'Eierzubereitungen',
     'Wie wird das Ei zubereitet?',
     'medium', 'Ei (Lebensmittel)',
     'https://de.wikipedia.org/wiki/Ei_%28Lebensmittel%29',
     '[["Pochiertes Ei", "Ohne Schale gegart", "Ein Schuss Essig hilft dem Eiweiß."],
       ["Spiegelei", "Dotter bleibt oben", "Das Eiweiß stockt, der Dotter bleibt flüssig."],
       ["Rührei", "Ständig bewegt garen", "Bei niedriger Hitze bleibt es cremig."],
       ["Omelett", "Flach gestockt und gefaltet", "Die Füllung kommt vor dem Falten hinein."],
       ["Onsen-Ei", "Lange bei Badetemperatur", "Benannt nach japanischen heißen Quellen."],
       ["Baiser", "Eiweiß mit Zucker aufgeschlagen", "Bei niedriger Temperatur getrocknet."],
       ["Mayonnaise", "Eigelb mit Öl emulgiert", "Das Lecithin hält Öl und Wasser zusammen."],
       ["Zabaione", "Über dem Wasserbad aufgeschlagen", "Mit Eigelb, Zucker und Marsala."],
       ["Hartgekochtes Ei", "Rund zehn Minuten gekocht", "Ein grüner Rand zeigt zu langes Kochen."],
       ["Eier Benedict", "Pochiert mit Sauce hollandaise", "Auf getoastetem Muffin serviert."]]'::jsonb,
     '[["In Tee und Gewürzen eingelegt", "Das wäre das chinesische Teeei, es fehlt hier."],
       ["In Essig und Salzlake eingelegt", "Das Soleier steht nicht auf dem Brett."]]'::jsonb),

    ('essen-trinken', 'suessspeisen-laender', 'Süßspeisen & Länder',
     'Aus welchem Land stammt die Süßspeise?',
     'medium', 'Dessert', 'https://de.wikipedia.org/wiki/Dessert',
     '[["Tiramisu", "Italien", "Der Name bedeutet zieh mich hoch."],
       ["Crème brûlée", "Frankreich", "Die Zuckerkruste wird abgeflämmt."],
       ["Baklava", "Türkei", "Dünne Teigblätter mit Nüssen und Sirup."],
       ["Sachertorte", "Österreich", "Um das Original wurde jahrelang prozessiert."],
       ["Pavlova", "Neuseeland", "Auch Australien beansprucht die Erfindung."],
       ["Churros", "Spanien", "Werden in heiße Schokolade getunkt."],
       ["Mochi", "Japan", "Reisteig, im Mörser gestampft."],
       ["Gulab Jamun", "Indien", "Frittierte Bällchen in Rosensirup."],
       ["Stollen", "Deutschland", "Die Form soll ein gewickeltes Kind darstellen."],
       ["Brownie", "USA", "Angeblich als misslungener Kuchen entstanden."],
       ["Rote Grütze", "Dänemark", "Beeren mit Stärke gebunden."],
       ["Pastel de Nata", "Portugal", "Rezept aus einem Kloster in Belém."]]'::jsonb,
     '[["Griechenland", "Galaktoboureko wäre die Süßspeise dazu, hier fehlt sie."],
       ["Schweden", "Die Prinzessinnentorte steht nicht auf dem Brett."]]'::jsonb),

    ('essen-trinken', 'kueche-koeche', 'Köche & ihre Restaurants',
     'Welches Haus ist mit dem Namen verbunden?',
     'hard', 'Koch', 'https://de.wikipedia.org/wiki/Koch',
     '[["Ferran Adrià", "elBulli", "Schloss das Restaurant auf dem Höhepunkt des Ruhms."],
       ["René Redzepi", "Noma", "Nordische Küche mit Fermenten und Wildkräutern."],
       ["Massimo Bottura", "Osteria Francescana", "Auch Reste werden zu Gerichten."],
       ["Heston Blumenthal", "The Fat Duck", "Bekannt für die Küche im Labor."],
       ["Paul Bocuse", "Auberge de Collonges", "Über fünfzig Jahre ohne Unterbrechung drei Sterne."],
       ["Anne-Sophie Pic", "Maison Pic", "Dritte Generation in derselben Küche."],
       ["Eckart Witzigmann", "Aubergine", "Erster deutscher Koch mit drei Sternen."],
       ["Grant Achatz", "Alinea", "Menüs als Abfolge von Überraschungen."],
       ["Dabiz Muñoz", "DiverXO", "Sehr laute, sehr eigene Küche in Madrid."],
       ["Clare Smyth", "Core", "Erste britische Köchin mit drei Sternen."],
       ["Yotam Ottolenghi", "Ottolenghi", "Machte Gemüse zur Hauptsache."],
       ["Alain Ducasse", "Le Louis XV", "Erstes Hotelrestaurant mit drei Sternen."]]'::jsonb,
     '[["The French Laundry", "Das Haus von Thomas Keller, der hier nicht steht."],
       ["Mugaritz", "Geführt von Andoni Luis Aduriz, und der fehlt auf dem Brett."]]'::jsonb),

    ('essen-trinken', 'kuechengeraete', 'Küchengeräte & Zweck',
     'Wozu dient das Gerät?',
     'medium', 'Küchengerät',
     'https://de.wikipedia.org/wiki/K%C3%BCchenger%C3%A4t',
     '[["Mörser", "Zerstoßen von Gewürzen", "Zerreibt Zellen und setzt Öle frei."],
       ["Schneebesen", "Luft unterschlagen", "Aus Sahne wird Schaum."],
       ["Mandoline", "Gleichmäßig dünn hobeln", "Ohne Schutz eine gefährliche Sache."],
       ["Fleischwolf", "Grob zerkleinern", "Die Lochscheibe bestimmt die Feinheit."],
       ["Passiermühle", "Pürieren und Schalen zurückhalten", "Klassisch für Kartoffelpüree."],
       ["Wok", "Sehr schnell scharf braten", "Die runde Form verteilt die Hitze."],
       ["Tajine", "Schmoren im eigenen Dampf", "Der Deckel führt Kondenswasser zurück."],
       ["Sushi-Matte", "Rollen formen", "Aus Bambus, mit Frischhaltefolie geschützt."],
       ["Zestenreißer", "Aromatische Schale abziehen", "Nur die Farbe, nicht das Weiße darunter."],
       ["Spätzlehobel", "Teig ins Wasser schaben", "Alternative zum Brett mit dem Messer."],
       ["Dampfgarer", "Ohne Wasserkontakt garen", "Vitamine bleiben besser erhalten."],
       ["Küchenthermometer", "Kerntemperatur messen", "Entscheidend beim Braten großer Stücke."]]'::jsonb,
     '[["Teig gleichmäßig ausrollen", "Dafür gibt es das Nudelholz, es steht nicht auf dem Brett."],
       ["Kaffee unter Druck brühen", "Das leistet die Espressomaschine, hier fehlt sie."]]'::jsonb),

    ('essen-trinken', 'gerichte-namensgeber', 'Gerichte & ihre Namensgeber',
     'Nach wem ist das Gericht benannt?',
     'hard', 'Eponym', 'https://de.wikipedia.org/wiki/Eponym',
     '[["Sandwich", "Earl of Sandwich", "Er wollte beim Spielen nicht aufstehen."],
       ["Carpaccio", "Vittore Carpaccio", "Nach den Rottönen auf den Bildern des Malers."],
       ["Pfirsich Melba", "Nellie Melba", "Für die Sängerin im Londoner Savoy erdacht."],
       ["Chateaubriand", "François-René de Chateaubriand", "Sein Koch soll das Stück erfunden haben."],
       ["Beef Stroganoff", "Graf Stroganow", "Aus der russischen Adelsküche."],
       ["Praline", "Herzog du Plessis-Praslin", "Sein Koch überzog Mandeln mit Karamell."],
       ["Bismarckhering", "Otto von Bismarck", "Der Kanzler bekam ein Fass geschickt."],
       ["Caesar Salad", "Caesar Cardini", "Ein Wirt in Tijuana, nicht der Feldherr."],
       ["Nachos", "Ignacio Anaya", "Sein Spitzname war Nacho."],
       ["Sacher", "Franz Sacher", "Mit sechzehn Jahren als Lehrling erfunden."],
       ["Béchamel", "Marquis de Béchameil", "Er ließ sich die Sauce widmen."],
       ["Margarita", "Königin Margherita", "Farben der italienischen Flagge auf dem Teig."]]'::jsonb,
     '[["Fürst Pückler", "Nach ihm ist das Eis benannt, das auf diesem Brett fehlt."],
       ["Giuseppe Garibaldi", "Der Garibaldi-Keks trägt seinen Namen, er steht hier nicht."]]'::jsonb),

    ('essen-trinken', 'fleischstuecke', 'Fleischstücke',
     'Woher am Tier stammt das Stück?',
     'hard', 'Fleisch', 'https://de.wikipedia.org/wiki/Fleisch',
     '[["Filet", "Innere Lende", "Kaum beansprucht und deshalb sehr zart."],
       ["Rumpsteak", "Roastbeef vom Rücken", "Mit Fettrand, der Geschmack bringt."],
       ["Entrecôte", "Zwischenrippenstück", "Fein marmoriert, mit Fettauge."],
       ["T-Bone", "Rücken mit Knochen", "Filet und Roastbeef in einem Stück."],
       ["Flanksteak", "Bauchlappen", "Quer zur Faser aufschneiden."],
       ["Tafelspitz", "Schwanzstück der Hüfte", "In Wien im Sud gegart."],
       ["Brisket", "Brust", "Klassiker im amerikanischen Barbecue."],
       ["Short Ribs", "Querrippe", "Lange geschmort, sehr saftig."],
       ["Nacken", "Hals", "Durchzogen und ideal für Schmorgerichte."],
       ["Haxe", "Unterschenkel", "Reich an Kollagen, wird beim Schmoren weich."]]'::jsonb,
     '[["Zunge", "Ein Stück für sich, aber keines auf diesem Brett."],
       ["Backe", "Die Rinderbacke fehlt in dieser Liste."]]'::jsonb),

    ('essen-trinken', 'fermentiertes', 'Fermentierte Spezialitäten',
     'Woher stammt das Ferment?',
     'hard', 'Fermentation',
     'https://de.wikipedia.org/wiki/Fermentation',
     '[["Kimchi", "Korea", "In Erdtöpfen vergorener Kohl mit Chili."],
       ["Miso", "Japan", "Sojabohnen mit Koji-Schimmel."],
       ["Kefir", "Kaukasus", "Knollen aus Bakterien und Hefen."],
       ["Tempeh", "Indonesien", "Sojabohnen, von Pilzmyzel zusammengehalten."],
       ["Skyr", "Island", "Streng genommen ein Frischkäse."],
       ["Surströmming", "Schweden", "Die Dose wölbt sich vom Gärgas."],
       ["Fischsauce", "Vietnam", "Monatelang gesalzene Sardellen."],
       ["Kwass", "Russland", "Aus altem Brot vergoren."],
       ["Pu-Erh-Tee", "China", "Wird nach der Ernte nachgereift."],
       ["Kombucha", "Mandschurei", "Der Teepilz ist eine Symbiose."],
       ["Ayran", "Türkei", "Joghurt mit Wasser und Salz."],
       ["Idli", "Südindien", "Reis und Linsen über Nacht vergoren."]]'::jsonb,
     '[["Georgien", "Auch dort wird viel fermentiert, hier steht nichts davon."],
       ["Frankreich", "Der Rohmilchkäse gehörte dazu, auf dem Brett fehlt er."]]'::jsonb),

    ('essen-trinken', 'nutzpflanzen-herkunft', 'Nutzpflanzen & ihre Heimat',
     'Woher stammt die Pflanze ursprünglich?',
     'medium', 'Nutzpflanze', 'https://de.wikipedia.org/wiki/Nutzpflanze',
     '[["Kiwi", "China", "Trotz des Namens keine neuseeländische Pflanze."],
       ["Kartoffel", "Anden", "Erst im 16. Jahrhundert nach Europa gebracht."],
       ["Tomate", "Mittelamerika", "Galt in Europa lange als Zierpflanze."],
       ["Mais", "Mexiko", "Über Jahrtausende aus einem Wildgras gezüchtet."],
       ["Kakao", "Amazonasgebiet", "Bei den Maya ein Getränk mit Chili."],
       ["Kaffee", "Äthiopien", "Der Sage nach von tanzenden Ziegen entdeckt."],
       ["Banane", "Südostasien", "Die Kulturbanane ist samenlos."],
       ["Apfel", "Zentralasien", "Die Wildform wächst noch in Kasachstan."],
       ["Avocado", "Guatemala", "Ihre Verbreiter, große Urzeittiere, sind längst ausgestorben."],
       ["Reis", "Ostasien", "Vor über 8000 Jahren am Jangtse angebaut."],
       ["Chili", "Bolivien", "Die Wildform stammt aus dem südamerikanischen Tiefland."],
       ["Wassermelone", "Afrika", "Ursprünglich als Wasserspeicher genutzt."]]'::jsonb,
     '[["Neuguinea", "Von dort stammt das Zuckerrohr, das hier nicht steht."],
       ["Australien", "Die Macadamia wäre die Pflanze dazu, sie fehlt auf dem Brett."]]'::jsonb),

    ('essen-trinken', 'cocktails-zutaten', 'Cocktails & Zutaten',
     'Woraus besteht der Cocktail vor allem?',
     'hard', 'Cocktail', 'https://de.wikipedia.org/wiki/Cocktail',
     '[["Mojito", "Rum und Minze", "Dazu Limette, Zucker und Soda."],
       ["Margarita", "Tequila und Limette", "Salzrand am Glas."],
       ["Negroni", "Gin und Campari", "Zu gleichen Teilen mit rotem Wermut."],
       ["Caipirinha", "Cachaça und Limette", "Zuckerrohrbrand statt Rum."],
       ["Bloody Mary", "Wodka und Tomatensaft", "Mit Sellerie und Pfeffer serviert."],
       ["Aperol Spritz", "Aperol und Prosecco", "Drei Teile, zwei Teile, ein Spritzer."],
       ["Manhattan", "Whiskey und Wermut", "Mit einem Spritzer Angostura."],
       ["Piña Colada", "Kokos und Ananas", "Nationalgetränk von Puerto Rico."],
       ["Old Fashioned", "Bourbon und Zucker", "Einer der ältesten bekannten Cocktails."],
       ["Gin Tonic", "Gin und Tonic Water", "Das Chinin stammt aus der Malariavorsorge."],
       ["Espresso Martini", "Wodka und Espresso", "In den 1980ern in London erfunden."],
       ["Daiquiri", "Rum und Limettensaft", "Benannt nach einem Ort in Kuba."]]'::jsonb,
     '[["Whiskey und Zitrone", "Das wäre ein Whiskey Sour, er fehlt auf dem Brett."],
       ["Wodka und Ginger Beer", "So entsteht ein Moscow Mule, der hier nicht steht."]]'::jsonb),

    ('essen-trinken', 'tischsitten', 'Tischsitten weltweit',
     'Was gilt in diesem Land bei Tisch?',
     'medium', 'Tischsitten', 'https://de.wikipedia.org/wiki/Tischsitten',
     '[["Japan", "Schlürfen ist erlaubt", "Bei Nudeln gilt es sogar als Kompliment."],
       ["Indien", "Nur die rechte Hand", "Die linke gilt als unrein."],
       ["China", "Stäbchen nie senkrecht abstellen", "Es erinnert an Räucherstäbchen für die Toten."],
       ["Italien", "Cappuccino nur morgens", "Milch gilt danach als schwer."],
       ["Frankreich", "Brot neben den Teller", "Nicht auf dem Teller, sondern daneben."],
       ["Südkorea", "Ältere greifen zuerst zu", "Auch beim Einschenken gilt die Rangfolge."],
       ["Äthiopien", "Gemeinsam von einer Platte", "Man reicht einander Bissen an."],
       ["Russland", "Trinksprüche gehören dazu", "Getrunken wird selten ohne Anlass."],
       ["Portugal", "Nicht nachsalzen", "Es gilt als Kritik am Koch."],
       ["Thailand", "Gegessen wird vom Löffel", "Gegessen wird vom Löffel."]]'::jsonb,
     '[["Nach dem Essen wird laut aufgestoßen", "Das sagt man Ägypten nach, und das Land fehlt hier."],
       ["Erst wenn alle sitzen, wird angestoßen", "Eine deutsche Regel, und Deutschland steht nicht auf dem Brett."]]'::jsonb),

    ('essen-trinken', 'gastronomie-begriffe', 'Begriffe der Gastronomie',
     'Was bezeichnet der Begriff?',
     'hard', 'Gastronomie', 'https://de.wikipedia.org/wiki/Gastronomie',
     '[["Mise en place", "Alles vorbereitet bereitstellen", "Die halbe Arbeit passiert vor dem Service."],
       ["À la carte", "Auswahl von der Speisekarte", "Im Gegensatz zum festen Menü."],
       ["Sommelier", "Fachkraft für Wein", "Berät und stellt die Weinkarte zusammen."],
       ["Amuse-Gueule", "Gruß aus der Küche", "Kleiner Gang, der nicht bestellt wird."],
       ["Degustationsmenü", "Viele kleine Gänge", "Die Küche bestimmt die Abfolge."],
       ["Chef de Partie", "Leitung eines Postens", "Etwa Saucen, Fisch oder Patisserie."],
       ["Michelin-Stern", "Auszeichnung für Küchenleistung", "Bewertet wird nur der Teller."],
       ["Trattoria", "Einfaches italienisches Lokal", "Zwischen Osteria und Ristorante."],
       ["Izakaya", "Japanische Kneipe mit Speisen", "Getrunken und dazu gegessen wird gemeinsam."],
       ["Brasserie", "Französisches Lokal mit Bierausschank", "Der Name bedeutet Brauerei."],
       ["Tapas-Bar", "Kleine Gerichte zum Teilen", "Ursprünglich ein Deckel auf dem Glas."],
       ["Service compris", "Bedienung im Preis enthalten", "Trinkgeld wird dann nur aufgerundet."]]'::jsonb,
     '[["Küchenchef des ganzen Hauses", "Das wäre der Chef de Cuisine, der hier nicht steht."],
       ["Feste Speisenfolge zum festen Preis", "Das Menü prix fixe fehlt auf dem Brett."]]'::jsonb),

    ('essen-trinken', 'herkunftsbezeichnungen', 'Geschützte Herkunft',
     'Aus welchem Land darf das Produkt allein kommen?',
     'hard', 'Herkunftsbezeichnung',
     'https://de.wikipedia.org/wiki/Herkunftsbezeichnung',
     '[["Parmigiano Reggiano", "Italien", "Nur aus fünf norditalienischen Provinzen."],
       ["Champagner", "Frankreich", "Zweite Gärung muss in der Flasche stattfinden."],
       ["Kalamata-Oliven", "Griechenland", "Aus Messenien auf dem Peloponnes."],
       ["Jamón Serrano", "Spanien", "Luftgetrocknet in den Bergen."],
       ["Lübecker Marzipan", "Deutschland", "Hoher Mandelanteil ist vorgeschrieben."],
       ["Melton Mowbray Pork Pie", "England", "Der Teig wird frei geformt, nicht in der Form."],
       ["Tiroler Speck", "Österreich", "Gepökelt, kalt geräuchert und luftgetrocknet."],
       ["Bündnerfleisch", "Schweiz", "In trockener Bergluft gereift."],
       ["Ungarische Salami", "Ungarn", "Mit Edelschimmel im Reifekeller."],
       ["Portwein", "Portugal", "Die Gärung wird mit Weinbrand gestoppt."],
       ["Havarti", "Dänemark", "Benannt nach einem Bauernhof bei Kopenhagen."],
       ["Ementálsky syr", "Slowakei", "Eigene geschützte Bezeichnung neben dem Schweizer Vorbild."]]'::jsonb,
     '[["Belgien", "Auch das Lambic-Bier ist geschützt, es fehlt auf dem Brett."],
       ["Polen", "Der Oscypek trägt den Schutz, steht aber nicht auf diesem Brett."]]'::jsonb),

    ('essen-trinken', 'backzutaten', 'Backzutaten & ihre Wirkung',
     'Was bewirkt die Zutat im Teig?',
     'hard', 'Backen', 'https://de.wikipedia.org/wiki/Backen',
     '[["Hefe", "Treibt durch Gärung", "Braucht Zeit und Wärme."],
       ["Backpulver", "Treibt durch Gasbildung", "Reagiert erst mit Feuchtigkeit und Hitze."],
       ["Eiweiß", "Bindet aufgeschlagene Luft", "Geschlagen entsteht ein stabiler Schaum."],
       ["Butter", "Macht mürbe", "Fett unterbricht das Klebergerüst."],
       ["Salz", "Verstärkt Geschmack und Kleber", "Zu viel bremst die Hefe."],
       ["Zucker", "Bräunt und hält feucht", "Karamellisiert an der Kruste."],
       ["Milch", "Macht die Krume weicher", "Und die Kruste dunkler."],
       ["Stärke", "Bindet Flüssigkeit", "Verkleistert beim Erhitzen."],
       ["Gelatine", "Geliert kalte Massen", "Wird beim Erwärmen wieder flüssig."],
       ["Pektin", "Geliert Fruchtmassen", "Steckt natürlich in Äpfeln und Zitrusschalen."],
       ["Sauerteig", "Säuert und lockert zugleich", "Nötig, damit Roggen überhaupt backfähig wird."],
       ["Xanthan", "Bindet ohne Klebereiweiß", "Wichtig für glutenfreies Backen."]]'::jsonb,
     '[["Färbt den Teig gelb", "Das täte Safran, und der steht nicht auf dem Brett."],
       ["Verhindert das Anhaften am Blech", "Das leistet Backpapier, keine Zutat im Teig."]]'::jsonb),

    ('essen-trinken', 'streetfood', 'Streetfood weltweit',
     'Woher kommt das Straßengericht?',
     'medium', 'Imbiss', 'https://de.wikipedia.org/wiki/Imbiss',
     '[["Currywurst", "Berlin", "Angeblich 1949 an einem Kiosk erfunden."],
       ["Falafel", "Naher Osten", "Frittierte Bällchen aus Kichererbsen oder Bohnen."],
       ["Bánh mì", "Vietnam", "Französisches Baguette mit vietnamesischer Füllung."],
       ["Arepa", "Venezuela", "Maisfladen, aufgeschnitten und gefüllt."],
       ["Empanada", "Argentinien", "Der Rand wird je nach Füllung anders gefaltet."],
       ["Takoyaki", "Japan", "Teigbällchen mit Oktopusstückchen."],
       ["Jerk Chicken", "Jamaika", "Über Pimentholz gegrillt."],
       ["Poutine", "Kanada", "Pommes mit Bratensauce und Käsebruch."],
       ["Simit", "Türkei", "Sesamkringel, auf dem Kopf getragen verkauft."],
       ["Bunny Chow", "Südafrika", "Ausgehöhltes Brot, mit Curry gefüllt."],
       ["Pierogi", "Polen", "Gefüllte Teigtaschen, gekocht oder gebraten."],
       ["Baozi", "China", "Gedämpfte Hefeteigtaschen."]]'::jsonb,
     '[["Indien", "Pani Puri wäre das Gericht dazu, hier fehlt es."],
       ["Griechenland", "Gyros im Pitabrot steht nicht auf dem Brett."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

-- The answers that belong to no category. Numbered after the pairs so the two
-- sets never collide on `position`, though nothing reads it for a fake: the
-- pool is shuffled before a player sees it, and the review lists fakes on their
-- own rather than in board order.
fakes as (
    select q.id                                         as quiz_id,
           k.value ->> 0                                as label,
           k.value ->> 1                                as explanation,
           (jsonb_array_length(sp.pairs) + k.ord)::int  as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.fakes) with ordinality k(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
),

paired as (
    insert into items (quiz_id, category_id, label, position, explanation)
    select f.quiz_id, c.id, f.answer, f.position, f.explanation
      from flat f
      join new_categories c
        on c.quiz_id = f.quiz_id
       and c.label = f.label
    returning id
)

-- Same table, `category_id` left null. Both inserts run in the one statement,
-- so `items_quiz_id_label_key` still sees the pairs above: a fake written to
-- repeat an answer already on its own board fails the file rather than becoming
-- a second row nobody can tell apart.
insert into items (quiz_id, category_id, label, position, explanation)
select k.quiz_id, null, k.label, k.position, k.explanation
  from fakes k;
