-- Essen & Trinken, leichte Fragen. Zwanzig Fragen, alle 'easy'.
--
-- Gefragt wird nach dem, was auf jedem Küchentisch steht, nicht nach
-- Grundsaucen und geschützten Ursprungsbezeichnungen.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs) as (
    values

    ('essen-trinken', 'leicht-woraus-gemacht', 'Woraus wird das gemacht?',
     'Woraus entsteht das Lebensmittel?',
     'easy', 'Lebensmittel', 'https://de.wikipedia.org/wiki/Lebensmittel',
     '[["Brot", "Mehl", "Dazu Wasser, Salz und Hefe."],
       ["Käse", "Milch", "Sie wird dick gelegt und gepresst."],
       ["Pommes frites", "Kartoffeln", "In Streifen geschnitten und frittiert."],
       ["Wein", "Weintrauben", "Der Saft vergärt zu Alkohol."],
       ["Marmelade", "Früchte", "Mit Zucker eingekocht."],
       ["Schokolade", "Kakaobohnen", "Sie werden geröstet und gemahlen."],
       ["Olivenöl", "Oliven", "Kalt gepresst schmeckt es am besten."],
       ["Butter", "Sahne", "Sie wird so lange geschlagen, bis sie fest wird."],
       ["Zucker", "Zuckerrüben", "In warmen Ländern aus Zuckerrohr."],
       ["Bier", "Gerste und Hopfen", "Dazu Wasser und Hefe."],
       ["Tofu", "Sojabohnen", "Wie Käse gerinnen gelassen."],
       ["Popcorn", "Maiskörner", "Sie platzen bei großer Hitze auf."]]'::jsonb),

    ('essen-trinken', 'leicht-obst-farben', 'Obst & Gemüse nach Farbe',
     'Welche Farbe hat es innen oder außen?',
     'easy', 'Obst', 'https://de.wikipedia.org/wiki/Obst',
     '[["Banane", "Gelb", "Grün, wenn sie noch nicht reif ist."],
       ["Kirsche", "Dunkelrot", "Mit einem Kern in der Mitte."],
       ["Gurke", "Grün", "Zu über neunzig Prozent Wasser."],
       ["Aubergine", "Violett", "Sie saugt Öl auf wie ein Schwamm."],
       ["Blumenkohl", "Weiß", "Gegessen wird die Blüte."],
       ["Karotte", "Orange", "Früher gab es auch violette Sorten."],
       ["Heidelbeere", "Blau", "Sie färbt Zunge und Finger."],
       ["Kiwi", "Braun außen", "Innen leuchtend grün."],
       ["Rote Bete", "Tiefrot", "Der Saft färbt fast alles."],
       ["Mais", "Goldgelb", "Am Kolben oder aus der Dose."],
       ["Zwiebel", "Weiß bis rot", "Die Schale schützt vor dem Austrocknen."],
       ["Avocado", "Grün mit großem Kern", "Sie reift erst nach der Ernte."]]'::jsonb),

    ('essen-trinken', 'leicht-mahlzeiten', 'Mahlzeiten am Tag',
     'Wann isst man das?',
     'easy', 'Mahlzeit', 'https://de.wikipedia.org/wiki/Mahlzeit',
     '[["Brötchen mit Marmelade", "Frühstück", "Die erste Mahlzeit des Tages."],
       ["Warmes Essen um die Mittagszeit", "Mittagessen", "In vielen Familien die Hauptmahlzeit."],
       ["Kuchen und Kaffee am Nachmittag", "Kaffeetrinken", "Ein sonntäglicher Brauch."],
       ["Brot mit Käse am Abend", "Abendbrot", "In Deutschland oft kalt."],
       ["Kleiner Happen zwischendurch", "Snack", "Obst oder ein Riegel."],
       ["Erstes Essen nach dem Fasten", "Fastenbrechen", "Im Ramadan nach Sonnenuntergang."],
       ["Feiertagsessen im Dezember", "Weihnachtsessen", "Oft mit Gans oder Karpfen."],
       ["Essen im Freien auf einer Decke", "Picknick", "Der Korb kommt mit."],
       ["Gemeinsames Essen mit vielen Gängen", "Festessen", "Zu Hochzeiten und Jubiläen."],
       ["Spätes Essen nach dem Ausgehen", "Mitternachtssnack", "Meist etwas Herzhaftes."]]'::jsonb),

    ('essen-trinken', 'leicht-kueche-geraete', 'In der Küche',
     'Womit macht man das?',
     'easy', 'Küche', 'https://de.wikipedia.org/wiki/K%C3%BCche',
     '[["Gemüse klein schneiden", "Messer", "Ein scharfes ist sicherer als ein stumpfes."],
       ["Nudeln abgießen", "Sieb", "Das Wasser läuft ab, die Nudeln bleiben."],
       ["Sahne steif schlagen", "Schneebesen", "Oder das Handrührgerät."],
       ["Kartoffeln schälen", "Sparschäler", "Er nimmt nur die Schale."],
       ["Käse fein raspeln", "Reibe", "Verschiedene Lochgrößen für verschiedene Zwecke."],
       ["Suppe umrühren", "Kochlöffel", "Aus Holz, damit er nicht heiß wird."],
       ["Teig ausrollen", "Nudelholz", "Vorher die Fläche bemehlen."],
       ["Mehl genau abmessen", "Waage", "Genauer als jeder Messbecher."],
       ["Etwas im Ofen backen", "Backblech", "Mit Backpapier darauf."],
       ["Wasser zum Kochen bringen", "Topf", "Mit Deckel geht es schneller."],
       ["Ein Steak braten", "Pfanne", "Sie muss richtig heiß sein."],
       ["Eine Flasche öffnen", "Flaschenöffner", "Der Korkenzieher ist für Wein."]]'::jsonb),

    ('essen-trinken', 'leicht-getraenke', 'Getränke',
     'Was für ein Getränk ist das?',
     'easy', 'Getränk', 'https://de.wikipedia.org/wiki/Getr%C3%A4nk',
     '[["Kommt aus der Leitung", "Wasser", "In Deutschland streng kontrolliert."],
       ["Gepresste Früchte", "Saft", "Direktsaft oder aus Konzentrat."],
       ["Heißes Getränk aus gerösteten Bohnen", "Kaffee", "Das meistgetrunkene Heißgetränk hier."],
       ["Heißes Getränk aus Blättern", "Tee", "Grün, schwarz oder als Kräutertee."],
       ["Aus Gerste gebraut", "Bier", "Mit Hopfen für die Bitterkeit."],
       ["Aus Trauben vergoren", "Wein", "Weiß, rot oder rosé."],
       ["Milch mit Kakaopulver", "Kakao", "Warm besonders beliebt im Winter."],
       ["Wasser mit Kohlensäure", "Sprudel", "Die Bläschen sind Kohlendioxid."],
       ["Milch und Saft gemischt und geschüttelt", "Milchshake", "Meist mit Eis dazu."],
       ["Getränk aus Zitronen und Zucker", "Limonade", "Klassisch selbst gemacht."],
       ["Warmer Wein mit Gewürzen", "Glühwein", "Auf jedem Weihnachtsmarkt."],
       ["Getränk mit Alkohol und Früchten", "Bowle", "In einer großen Schüssel angesetzt."]]'::jsonb),

    ('essen-trinken', 'leicht-gerichte-laender', 'Gerichte & Länder',
     'Aus welchem Land kommt das Gericht?',
     'easy', 'Nationalgericht',
     'https://de.wikipedia.org/wiki/Nationalgericht',
     '[["Pizza", "Italien", "Aus Neapel in die ganze Welt."],
       ["Sushi", "Japan", "Reis mit rohem Fisch."],
       ["Tacos", "Mexiko", "Gefaltete Maistortillas."],
       ["Paella", "Spanien", "Reis in flacher Pfanne."],
       ["Currywurst", "Deutschland", "Angeblich in Berlin erfunden."],
       ["Wiener Schnitzel", "Österreich", "Paniertes Kalbfleisch."],
       ["Gulasch", "Ungarn", "Mit viel Paprika."],
       ["Fish and Chips", "England", "Früher in Zeitungspapier."],
       ["Croissant", "Frankreich", "Aus Blätterteig, morgens frisch."],
       ["Kebab", "Türkei", "Fleisch vom Drehspieß."],
       ["Pfannkuchen mit Ahornsirup", "Kanada", "Der Sirup kommt vom Ahornbaum."],
       ["Fondue", "Schweiz", "Brot in geschmolzenen Käse getunkt."]]'::jsonb),

    ('essen-trinken', 'leicht-geschmack', 'Wie schmeckt das?',
     'Welche Geschmacksrichtung ist das?',
     'easy', 'Geschmackssinn',
     'https://de.wikipedia.org/wiki/Geschmackssinn',
     '[["Zucker", "Süß", "Kinder mögen ihn besonders."],
       ["Zitrone", "Sauer", "Die Säure lässt das Gesicht verziehen."],
       ["Meersalz", "Salzig", "Zu viel davon macht durstig."],
       ["Schwarzer Kaffee", "Bitter", "Viele gewöhnen sich erst daran."],
       ["Sojasauce", "Herzhaft", "Diese Richtung heißt auch umami."],
       ["Chili", "Scharf", "Genau genommen ein Schmerzreiz."],
       ["Pfefferminze", "Kühlend", "Sie täuscht Kälte vor."],
       ["Unreife Banane", "Mehlig", "Die Stärke ist noch nicht Zucker."],
       ["Sehr starker Tee", "Herb", "Die Gerbstoffe ziehen den Mund zusammen."],
       ["Frisches Brot", "Mild", "Der Duft macht den halben Geschmack."]]'::jsonb),

    ('essen-trinken', 'leicht-fruehstueck-welt', 'Frühstück in aller Welt',
     'Wo frühstückt man so?',
     'easy', 'Frühstück', 'https://de.wikipedia.org/wiki/Fr%C3%BChst%C3%BCck',
     '[["Brötchen, Wurst und Käse", "Deutschland", "Dazu ein gekochtes Ei."],
       ["Croissant und Milchkaffee", "Frankreich", "Am Tresen im Stehen."],
       ["Rührei, Bohnen und Speck", "England", "Das volle englische Frühstück."],
       ["Reis, Suppe und Fisch", "Japan", "Auch morgens warm und herzhaft."],
       ["Joghurt, Honig und Oliven", "Griechenland", "Dazu Fladenbrot."],
       ["Pfannkuchen mit Sirup", "USA", "Dazu Speck und Kaffee."],
       ["Fladenbrot mit Bohnenmus", "Ägypten", "Ful mit Kreuzkümmel."],
       ["Käse, Oliven, Gurke und Tee", "Türkei", "Viele kleine Schälchen."],
       ["Süßes Milchbrot mit Kaffee", "Brasilien", "Dazu frische Früchte."],
       ["Haferbrei mit Salz", "Schottland", "Porridge, traditionell ohne Zucker."]]'::jsonb),

    ('essen-trinken', 'leicht-suess', 'Süßes',
     'Was ist das?',
     'easy', 'Süßware', 'https://de.wikipedia.org/wiki/S%C3%BC%C3%9Fware',
     '[["Gummibärchen", "Weiche Fruchtgummis", "Aus Gelatine und Zucker."],
       ["Lolli", "Bonbon am Stiel", "Zum langen Lutschen."],
       ["Eis in der Waffel", "Gefrorene Süßspeise", "Am liebsten im Sommer."],
       ["Schokoriegel", "Riegel mit Füllung", "Karamell oder Nuss innen."],
       ["Lebkuchen", "Würziges Weihnachtsgebäck", "Aus Nürnberg besonders bekannt."],
       ["Krapfen", "Frittiertes Hefegebäck", "Mit Marmelade gefüllt."],
       ["Baiser", "Gebackener Eischnee", "Sehr leicht und sehr süß."],
       ["Nougat", "Nuss-Zucker-Masse", "Weich und sehr süß."],
       ["Marzipan", "Masse aus Mandeln", "Zu Figuren geformt."],
       ["Karamellbonbon", "Erhitzter Zucker", "Er wird braun und zäh."],
       ["Waffel mit Puderzucker", "Gebackener Teig", "Auf jedem Jahrmarkt."],
       ["Zuckerwatte", "Gesponnener Zucker", "Fast nur Luft."]]'::jsonb),

    ('essen-trinken', 'leicht-tisch-decken', 'Den Tisch decken',
     'Wofür braucht man das?',
     'easy', 'Gedeck', 'https://de.wikipedia.org/wiki/Gedeck',
     '[["Gabel", "Feste Speisen aufspießen", "Links neben dem Teller."],
       ["Messer", "Schneiden", "Rechts neben dem Teller."],
       ["Löffel", "Suppe essen", "Auch für Nachtisch."],
       ["Teller", "Speisen darauf legen", "Flach oder tief."],
       ["Glas", "Getränke", "Rechts über dem Messer."],
       ["Serviette", "Mund abwischen", "Aus Stoff oder Papier."],
       ["Schüssel", "Salat servieren", "Für alle in der Mitte."],
       ["Tischdecke", "Tisch schützen", "Bei Festen aus Stoff."],
       ["Untersetzer", "Hitze abhalten", "Damit die Platte nicht leidet."],
       ["Kerze", "Stimmung machen", "Vorsicht bei langen Ärmeln."]]'::jsonb),

    ('essen-trinken', 'leicht-tiere-lebensmittel', 'Vom Tier zum Lebensmittel',
     'Von welchem Tier kommt das?',
     'easy', 'Lebensmittel', 'https://de.wikipedia.org/wiki/Lebensmittel',
     '[["Milch für den Kaffee", "Kuh", "Auch Ziegen und Schafe geben Milch."],
       ["Frühstücksei", "Huhn", "Braune und weiße Eier schmecken gleich."],
       ["Honig", "Biene", "Für ein Glas fliegen Bienen weit."],
       ["Schinken", "Schwein", "Gepökelt und geräuchert."],
       ["Lammkotelett", "Schaf", "Vom jungen Tier."],
       ["Lachsfilet", "Lachs", "Wandert zum Laichen flussaufwärts."],
       ["Rinderfilet", "Rind", "Das zarteste Stück."],
       ["Ziegenkäse", "Ziege", "Kräftiger als Kuhkäse."],
       ["Gänsebraten", "Gans", "Klassisch an Weihnachten."],
       ["Garnelen im Salat", "Garnele", "Ein Krebstier aus dem Meer."],
       ["Kaviar", "Stör", "Der Rogen des Fisches."],
       ["Entenbrust", "Ente", "Mit knuspriger Haut gebraten."]]'::jsonb),

    ('essen-trinken', 'leicht-lagern', 'Wie hält es sich?',
     'Wo lagert man das am besten?',
     'easy', 'Lebensmittelkonservierung',
     'https://de.wikipedia.org/wiki/Lebensmittelkonservierung',
     '[["Frische Milch", "Im Kühlschrank", "Am besten nicht in der Tür."],
       ["Kartoffeln", "Dunkel und kühl", "Bei Licht werden sie grün."],
       ["Tiefkühlpizza", "Im Gefrierfach", "Bei minus achtzehn Grad."],
       ["Mehl und Nudeln", "Trocken im Schrank", "Gut verschlossen gegen Motten."],
       ["Tomaten", "Bei Zimmertemperatur", "Im Kühlschrank verlieren sie Aroma."],
       ["Bananen", "Getrennt von anderem Obst", "Sie lassen anderes schneller reifen."],
       ["Angebrochene Konserve", "Umfüllen und kühlen", "Nicht in der Dose aufbewahren."],
       ["Frische Kräuter", "Im Wasserglas", "Wie ein kleiner Blumenstrauß."],
       ["Eier", "Kühl und gleichmäßig", "Einmal gekühlt, immer gekühlt."],
       ["Brot", "Im Brotkasten", "Nicht im Kühlschrank, dort wird es altbacken."]]'::jsonb),

    ('essen-trinken', 'leicht-gewuerze', 'Gewürze & Kräuter',
     'Wozu passt das besonders gut?',
     'easy', 'Gewürz', 'https://de.wikipedia.org/wiki/Gew%C3%BCrz',
     '[["Basilikum", "Tomate und Mozzarella", "Am besten frisch und zum Schluss."],
       ["Zimt", "Milchreis und Gebäck", "Die Rinde eines Baumes."],
       ["Petersilie", "Kartoffeln und Suppen", "Krause oder glatte Sorte."],
       ["Rosmarin", "Kartoffeln aus dem Ofen", "Nadeln wie ein kleiner Nadelbaum."],
       ["Vanille", "Pudding und Eis", "Die Schote einer Orchidee."],
       ["Knoblauch", "Nudelsauce", "Der Geruch bleibt lange."],
       ["Pfeffer", "Fast jedes herzhafte Gericht", "Frisch gemahlen am besten."],
       ["Dill", "Fisch und Gurkensalat", "Feine, fedrige Blätter."],
       ["Muskat", "Kartoffelpüree", "Nur eine Prise, sonst wird es bitter."],
       ["Oregano", "Pizza", "Getrocknet kräftiger als frisch."],
       ["Ingwer", "Tee und asiatische Gerichte", "Scharf und frisch zugleich."],
       ["Schnittlauch", "Quark und Rührei", "Mit der Schere geschnitten."]]'::jsonb),

    ('essen-trinken', 'leicht-brot-baecker', 'Beim Bäcker',
     'Was ist das?',
     'easy', 'Brot', 'https://de.wikipedia.org/wiki/Brot',
     '[["Kleines rundes Weißgebäck", "Brötchen", "Regional Semmel oder Schrippe."],
       ["Langes französisches Weißbrot", "Baguette", "Außen knusprig, innen weich."],
       ["Sehr dunkles Brot aus Westfalen", "Pumpernickel", "Stundenlang bei niedriger Hitze gebacken."],
       ["Geflochtenes süßes Brot", "Hefezopf", "Oft zu Ostern."],
       ["Gebäck mit Loch in der Mitte", "Bagel", "Zuerst gekocht, dann gebacken."],
       ["Gebäck mit verschlungenen Armen", "Brezel", "In Bayern und Schwaben zu Hause."],
       ["Blätterteig in Hörnchenform", "Croissant", "Sehr viel Butter im Teig."],
       ["Brot aus Roggen und Sauerteig", "Roggenbrot", "Kräftig und lange haltbar."],
       ["Flaches Brot aus dem heißen Ofen", "Fladenbrot", "In vielen Küchen der Welt."],
       ["Süßes Teilchen mit Rosinen", "Rosinenschnecke", "Aus aufgerolltem Hefeteig."]]'::jsonb),

    ('essen-trinken', 'leicht-essen-feste', 'Essen zu Festen',
     'Wann isst man das?',
     'easy', 'Fest', 'https://de.wikipedia.org/wiki/Fest',
     '[["Weihnachtsgans", "An Weihnachten", "Dazu Rotkohl und Klöße."],
       ["Ostereier", "An Ostern", "Bunt gefärbt und versteckt."],
       ["Berliner mit Marmelade", "Im Karneval", "Manchmal mit Senf als Scherz."],
       ["Martinsgans", "Am Martinstag", "Am 11. November."],
       ["Lebkuchen und Spekulatius", "Im Advent", "Sie stehen schon im September im Regal."],
       ["Grillwurst und Salate", "Im Sommer", "Wenn das Wetter mitspielt."],
       ["Neujahrsbrezel", "An Silvester", "Sie soll Glück bringen."],
       ["Hochzeitstorte", "Bei einer Hochzeit", "Das Paar schneidet gemeinsam an."],
       ["Kuchen mit Kerzen", "Am Geburtstag", "Einmal kräftig pusten."],
       ["Zuckertüte voller Naschwerk", "Zur Einschulung", "Am ersten Schultag."]]'::jsonb),

    ('essen-trinken', 'leicht-milchprodukte', 'Aus Milch gemacht',
     'Was ist das?',
     'easy', 'Milchprodukt',
     'https://de.wikipedia.org/wiki/Milchprodukt',
     '[["Dickgelegte Milch mit Kulturen", "Joghurt", "Lebende Bakterien machen ihn sauer."],
       ["Fett, das aus Sahne geschlagen wird", "Butter", "Etwa zwanzig Liter Milch je Kilo."],
       ["Cremiger Aufstrich, mild und weiß", "Frischkäse", "Sofort verzehrfertig."],
       ["Gereifter Käse mit Löchern", "Emmentaler", "Die Löcher entstehen durch Gase."],
       ["Milch mit hohem Fettanteil", "Sahne", "Sie lässt sich steif schlagen."],
       ["Dickmilch mit besonderen Kulturen", "Kefir", "Leicht prickelnd im Geschmack."],
       ["Gefrorene Süßspeise aus Milch", "Speiseeis", "Ständig gerührt beim Gefrieren."],
       ["Käse aus Schafmilch in Salzlake", "Feta", "Er bröckelt beim Schneiden."],
       ["Magerer Quark", "Speisequark", "Beliebt mit Leinöl und Kartoffeln."],
       ["Getrocknete Milch als Pulver", "Milchpulver", "Lange haltbar ohne Kühlung."]]'::jsonb),

    ('essen-trinken', 'leicht-restaurant', 'Im Restaurant',
     'Wer oder was ist das?',
     'easy', 'Restaurant', 'https://de.wikipedia.org/wiki/Restaurant',
     '[["Bringt das Essen an den Tisch", "Kellner", "Er nimmt auch die Bestellung auf."],
       ["Kocht in der Küche", "Koch", "Er trägt oft eine weiße Jacke."],
       ["Liste aller Gerichte", "Speisekarte", "Mit Preisen daneben."],
       ["Erster kleiner Gang", "Vorspeise", "Sie macht Appetit."],
       ["Der größte Gang", "Hauptgericht", "Meist mit Beilage."],
       ["Der süße Abschluss", "Nachtisch", "Eis, Pudding oder Kuchen."],
       ["Zettel mit dem Betrag", "Rechnung", "Man bittet darum am Ende."],
       ["Etwas mehr als der Betrag", "Trinkgeld", "In Deutschland üblich, aber freiwillig."],
       ["Vorher einen Tisch sichern", "Reservierung", "Besonders am Wochenende ratsam."],
       ["Essen zum Mitnehmen", "Außer Haus", "In der Box statt auf dem Teller."]]'::jsonb),

    ('essen-trinken', 'leicht-gesunde-ernaehrung', 'Gesund essen',
     'Was gilt hier?',
     'easy', 'Ernährung', 'https://de.wikipedia.org/wiki/Ern%C3%A4hrung',
     '[["Obst und Gemüse am Tag", "Fünf Portionen", "Eine Handvoll ist eine Portion."],
       ["Wichtigstes Getränk", "Wasser", "Etwa anderthalb Liter täglich."],
       ["Vollkorn statt Weißmehl", "Mehr Ballaststoffe", "Sie sättigen länger."],
       ["Zu viel Zucker", "Schlecht für die Zähne", "Und für den Blutzucker."],
       ["Zu viel Salz", "Belastet den Blutdruck", "Sechs Gramm am Tag genügen."],
       ["Fisch in der Woche", "Ein- bis zweimal", "Wegen der Omega-3-Fettsäuren."],
       ["Langsam essen", "Sättigung kommt später", "Das Gefühl braucht Minuten."],
       ["Frühstück", "Guter Start", "Auch wenn nicht jeder es braucht."],
       ["Selbst kochen", "Zutaten selbst bestimmen", "Meist auch günstiger."],
       ["Bewegung nach dem Essen", "Hilft der Verdauung", "Ein Spaziergang genügt."]]'::jsonb),

    ('essen-trinken', 'leicht-kochbegriffe', 'Wörter aus dem Kochbuch',
     'Was soll man tun?',
     'easy', 'Kochen', 'https://de.wikipedia.org/wiki/Kochen',
     '[["Anbraten", "Kurz scharf braten", "Für Farbe und Röstaromen."],
       ["Köcheln lassen", "Ganz leicht sieden", "Es soll kaum blubbern."],
       ["Abschmecken", "Zum Schluss würzen", "Erst probieren, dann salzen."],
       ["Pürieren", "Fein zerkleinern", "Mit dem Stabmixer."],
       ["Marinieren", "Vorher einlegen", "Am besten über Nacht."],
       ["Blanchieren", "Kurz kochen und abschrecken", "Das Gemüse bleibt grün."],
       ["Panieren", "Mehl, Ei, Brösel", "In dieser Reihenfolge."],
       ["Abschöpfen", "Schaum entfernen", "Damit die Brühe klar wird."],
       ["Ruhen lassen", "Nach dem Braten warten", "Der Saft verteilt sich."],
       ["Vorheizen", "Ofen vorher aufheizen", "Sonst stimmt die Backzeit nicht."]]'::jsonb),

    ('essen-trinken', 'leicht-eis-sorten', 'Eis & Kaltes',
     'Was steckt drin?',
     'easy', 'Speiseeis', 'https://de.wikipedia.org/wiki/Speiseeis',
     '[["Vanilleeis", "Vanille", "Die Punkte sind Vanillemark."],
       ["Schokoladeneis", "Kakao", "Das beliebteste Eis nach Vanille."],
       ["Erdbeereis", "Erdbeeren", "Am besten mit reifen Früchten."],
       ["Zitronensorbet", "Zitrone", "Ganz ohne Milch."],
       ["Pistazieneis", "Pistazien", "Von Natur aus eher blass."],
       ["Stracciatella", "Schokosplitter in Sahneeis", "Der Name heißt Fetzen."],
       ["Bananensplit", "Banane mit Eis", "Dazu Sahne und Sauce."],
       ["Spaghettieis", "Vanilleeis durch die Presse", "Erdbeersauce als Tomatensauce."],
       ["Frozen Yogurt", "Gefrorener Joghurt", "Etwas säuerlicher als Eis."],
       ["Wassereis am Stiel", "Gefrorener Saft", "Ohne Milch und ohne Sahne."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
)

insert into items (quiz_id, category_id, label, position, explanation)
select f.quiz_id, c.id, f.answer, f.position, f.explanation
  from flat f
  join new_categories c
    on c.quiz_id = f.quiz_id
   and c.label = f.label;
