-- Essen & Trinken, file 2 of 2. Twenty questions, medium and hard.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs, fakes) as (
    values

    ('essen-trinken', 'klassische-saucen', 'Saucen & ihre Grundlage',
     'Woraus besteht die Sauce im Kern?',
     'hard', 'Sauce', 'https://de.wikipedia.org/wiki/Sauce',
     '[["Béchamel", "Mehlschwitze mit Milch", "Eine der Grundsaucen der französischen Küche."],
       ["Velouté", "Heller Fond mit Einbrenne", "Von velours, samtig."],
       ["Sauce espagnole", "Brauner Kalbsfond", "Basis für viele dunkle Saucen."],
       ["Hollandaise", "Butter und Eigelb", "Trennt sich, wenn es zu heiß wird."],
       ["Beurre blanc", "Butter und Weißwein", "Wird kalt eingerührt, nie gekocht."],
       ["Béarnaise", "Estragon und Schalotten", "Verwandt mit der Hollandaise."],
       ["Aioli", "Knoblauch und Öl", "Im Original ohne Ei gemörsert."],
       ["Sauce tartare", "Mayonnaise mit Kapern", "Dazu Gurke, Zwiebel und Kräuter."],
       ["Chimichurri", "Petersilie und Knoblauch", "Argentinische Sauce zum Grillfleisch."],
       ["Ponzu", "Zitrus und Sojasauce", "Japanische Dip-Sauce mit Säure."],
       ["Sauce tomate", "Tomaten und Gemüse", "Als einzige Grundsauce vegetarisch."],
       ["Sauce hoisin", "Fermentierte Sojabohnen", "Süßlich, für Ente und Wok-Gerichte."]]'::jsonb,
     '[["Sahne und Meerrettich", "Das wäre eine Meerrettichsauce, sie fehlt auf dem Brett."],
       ["Joghurt und Gurke", "So entsteht Tzatziki, das hier nicht steht."]]'::jsonb),

    ('essen-trinken', 'biersorten', 'Biersorten & ihre Machart',
     'Was kennzeichnet das Bier?',
     'hard', 'Bier', 'https://de.wikipedia.org/wiki/Bier',
     '[["Weizenbier", "Hoher Weizenanteil", "Obergärig, mit Bananen- und Nelkennoten."],
       ["Kölsch", "Hell und obergärig", "Nur in Köln so gebraut, im Stangenglas serviert."],
       ["Altbier", "Dunkel und obergärig", "Die Düsseldorfer Antwort auf das Kölsch."],
       ["India Pale Ale", "Sehr stark gehopft", "Der Hopfen sollte die Seereise überstehen."],
       ["Trappistenbier", "In Klöstern gebraut", "Nur wenige Abteien dürfen die Bezeichnung führen."],
       ["Lambic", "Spontangärung mit Wildhefen", "Aus dem Tal der Senne bei Brüssel."],
       ["Rauchbier", "Über Buchenfeuer gedarrt", "Spezialität aus Bamberg."],
       ["Berliner Weisse", "Säuerlich durch Milchsäure", "Traditionell mit Sirup gemischt."],
       ["Bockbier", "Sehr hoher Stammwürzegehalt", "Ursprünglich aus Einbeck."],
       ["Märzen", "Im März eingebraut", "Vor der Kühltechnik eine Notwendigkeit."],
       ["Porter", "Dunkel mit Röstmalz", "Benannt nach den Trägern der Londoner Märkte."],
       ["Gose", "Salzig und säuerlich", "Mit Koriander gewürzt, aus Goslar."]]'::jsonb,
     '[["Ohne Alkohol vergoren", "Alkoholfreies Bier steht nicht auf diesem Brett."],
       ["Mit Kirschen nachvergoren", "Das wäre ein Kriek, und der fehlt hier."]]'::jsonb),

    ('essen-trinken', 'kaffeezubereitung', 'Kaffee & Zubereitung',
     'Wie wird der Kaffee gemacht?',
     'medium', 'Kaffee', 'https://de.wikipedia.org/wiki/Kaffee',
     '[["Espresso", "Mit neun bar Druck", "In etwa 25 Sekunden extrahiert."],
       ["Filterkaffee", "Wasser läuft durch Papier", "Die Schwerkraft macht die Arbeit."],
       ["French Press", "Stempel presst den Satz", "Ergibt einen körperreichen Kaffee."],
       ["Mokka", "Im Kupferkännchen aufgekocht", "Das Pulver bleibt im Getränk."],
       ["Cold Brew", "Stunden im kalten Wasser", "Wenig Säure, dafür Zeitaufwand."],
       ["AeroPress", "Handdruck über Kolben", "Zum Reisen entwickelt."],
       ["Cappuccino", "Espresso mit Milchschaum", "Zu gleichen Teilen Kaffee, Milch, Schaum."],
       ["Latte macchiato", "Geschichtet im Glas", "Die Milch kommt zuerst, der Espresso obenauf."],
       ["Flat White", "Feinporiger Mikroschaum", "Aus Australien und Neuseeland."],
       ["Karlsbader Kanne", "Porzellansieb ohne Papier", "Traditionell für sehr grob gemahlenen Kaffee."],
       ["Türkischer Kaffee", "Staubfein aufgekocht", "Der Satz setzt sich in der Tasse ab."],
       ["Instantkaffee", "Extrakt getrocknet", "Wird mit heißem Wasser rückverwandelt."]]'::jsonb,
     '[["Espresso mit heißem Wasser gestreckt", "Das ist ein Americano, er fehlt auf dem Brett."],
       ["Durch Unterdruck im Glaskolben", "Der Syphon steht nicht in dieser Liste."]]'::jsonb),

    ('essen-trinken', 'teesorten', 'Tee & Verarbeitung',
     'Was kennzeichnet diesen Tee?',
     'hard', 'Tee', 'https://de.wikipedia.org/wiki/Tee',
     '[["Grüner Tee", "Nicht oxidiert", "Direkt nach der Ernte erhitzt."],
       ["Schwarzer Tee", "Vollständig oxidiert", "In Ostasien heißt er roter Tee."],
       ["Oolong", "Teilweise oxidiert", "Zwischen grünem und schwarzem Tee."],
       ["Weißer Tee", "Kaum bearbeitet", "Nur welken und trocknen."],
       ["Matcha", "Zu Pulver vermahlen", "Wird aufgeschlagen, nicht aufgegossen."],
       ["Sencha", "Mit Dampf fixiert", "Der japanische Alltagstee."],
       ["Darjeeling", "Aus dem Himalaya-Vorland", "Wird der Champagner unter den Tees genannt."],
       ["Assam", "Aus dem indischen Tiefland", "Kräftig und malzig."],
       ["Earl Grey", "Mit Bergamotteöl aromatisiert", "Benannt nach einem britischen Premier."],
       ["Rooibos", "Gar kein echter Tee", "Aus einem südafrikanischen Strauch."],
       ["Gunpowder", "Zu Kugeln gerollt", "Entfaltet sich erst im Wasser."],
       ["Lapsang Souchong", "Über Kiefernholz geräuchert", "Riecht deutlich nach Rauch."]]'::jsonb,
     '[["Nachträglich mit Jasmin beduftet", "Das wäre Jasmintee, der hier nicht steht."],
       ["Über Jahre nachgereift", "So entsteht Pu-Erh, und der fehlt auf diesem Brett."]]'::jsonb),

    ('essen-trinken', 'meeresfruechte', 'Meeresfrüchte',
     'Was kennzeichnet das Tier auf dem Teller?',
     'medium', 'Meeresfrüchte',
     'https://de.wikipedia.org/wiki/Meeresfr%C3%BCchte',
     '[["Auster", "Roh mit Zitrone geschlürft", "Muss beim Kauf fest geschlossen sein."],
       ["Jakobsmuschel", "Nur der Schließmuskel", "Wird sehr kurz gebraten."],
       ["Hummer", "Zwei kräftige Scheren", "Eine zum Knacken, eine zum Schneiden."],
       ["Languste", "Ohne große Scheren", "Dafür mit langen Fühlern."],
       ["Miesmuschel", "Mit Bart am Gehäuse", "Wird vor dem Garen entfernt."],
       ["Tintenfisch", "Kann Tinte ausstoßen", "Sie färbt Pasta und Risotto schwarz."],
       ["Garnele", "Dunkler Darm im Rücken", "Wird vor dem Garen herausgezogen."],
       ["Seeigel", "Gegessen wird der Rogen", "Orangefarbene Zungen im Inneren."],
       ["Venusmuschel", "Klein und feinsandig", "In Italien Grundlage der Vongole."],
       ["Nordseekrabbe", "Wird von Hand gepult", "Trotz des Namens eine Garnele."]]'::jsonb,
     '[["Panzer wird zur Brühe ausgekocht", "Das täte man mit dem Flusskrebs, der hier fehlt."],
       ["Wächst festgewachsen im Gezeitenbereich", "Das wäre die Entenmuschel, sie steht nicht auf dem Brett."]]'::jsonb),

    ('essen-trinken', 'oele-fette', 'Öle & Fette',
     'Was zeichnet das Fett aus?',
     'hard', 'Speisefette und Speiseöle',
     'https://de.wikipedia.org/wiki/Speisefette_und_Speise%C3%B6le',
     '[["Natives Olivenöl", "Kalt gepresst", "Über 180 Grad verliert es sein Aroma."],
       ["Rapsöl", "Günstiges Fettsäureverhältnis", "Viel Omega-3 für ein heimisches Öl."],
       ["Kokosfett", "Bei Zimmertemperatur fest", "Schmilzt knapp über 20 Grad."],
       ["Butterschmalz", "Ohne Wasser und Eiweiß", "Deshalb hoch erhitzbar."],
       ["Geröstetes Sesamöl", "Wird zum Würzen genutzt", "Kommt erst zum Schluss ins Gericht."],
       ["Erdnussöl", "Sehr hoher Rauchpunkt", "Klassisch zum Frittieren im Wok."],
       ["Leinöl", "Trocknet an der Luft", "Wird schnell ranzig, kühl lagern."],
       ["Ghee", "Indisch geklärte Butter", "Lange haltbar auch ohne Kühlung."],
       ["Sonnenblumenöl", "Neutral im Geschmack", "Standardöl für Salat und Küche."],
       ["Walnussöl", "Nur für kalte Speisen", "Hitze zerstört das Aroma sofort."],
       ["Schweineschmalz", "Klassisch für Deftiges", "Trägt Röstaromen besonders gut."],
       ["Traubenkernöl", "Fein und hitzestabil", "Nebenprodukt der Weinherstellung."]]'::jsonb,
     '[["Aus Oliventrester gewonnen", "Das ist Tresteröl, es steht nicht auf dem Brett."],
       ["Fest durch gehärtetes Pflanzenöl", "Das beschreibt Margarine, die hier fehlt."]]'::jsonb),

    ('essen-trinken', 'maerkte-staedte', 'Markthallen & Städte',
     'In welcher Stadt steht der Markt?',
     'medium', 'Markt', 'https://de.wikipedia.org/wiki/Markt',
     '[["La Boqueria", "Barcelona", "Direkt an der Rambla gelegen."],
       ["Toyosu-Markt", "Tokio", "Nachfolger des Fischmarkts von Tsukiji."],
       ["Borough Market", "London", "Unter den Bahngleisen bei London Bridge."],
       ["Mercado de San Miguel", "Madrid", "Gusseiserne Halle, heute vor allem Tapas."],
       ["Naschmarkt", "Wien", "Über anderthalb Kilometer lang."],
       ["Viktualienmarkt", "München", "Mit einem eigenen Biergarten in der Mitte."],
       ["Großer Basar", "Istanbul", "Über 4000 Läden unter einem Dach."],
       ["Djemaa el Fna", "Marrakesch", "Abends verwandelt er sich in eine Garküche."],
       ["Chatuchak", "Bangkok", "Tausende Stände nur am Wochenende."],
       ["Pike Place Market", "Seattle", "Bekannt für geworfene Fische."],
       ["Mercado Central", "Valencia", "Jugendstilhalle mit Kuppeln."],
       ["Ver-o-Peso", "Belém", "Größter Freiluftmarkt am Amazonas."]]'::jsonb,
     '[["Budapest", "Dort steht die Große Markthalle, auf dem Brett fehlt sie."],
       ["Lissabon", "Der Mercado da Ribeira ist hier nicht aufgeführt."]]'::jsonb),

    ('essen-trinken', 'weinbegriffe', 'Begriffe rund um den Wein',
     'Was bezeichnet der Begriff?',
     'hard', 'Wein', 'https://de.wikipedia.org/wiki/Wein',
     '[["Tannin", "Gerbstoff der Schalen", "Sorgt für das pelzige Gefühl im Mund."],
       ["Terroir", "Zusammenspiel des Standorts", "Boden, Klima und Handschrift des Winzers."],
       ["Barrique", "Kleines Eichenfass", "225 Liter, gibt Vanillenoten ab."],
       ["Dekantieren", "Umgießen vom Depot", "Trennt den Wein vom Bodensatz."],
       ["Cuvée", "Verschnitt mehrerer Weine", "In Frankreich völlig üblich."],
       ["Brut", "Sehr wenig Restzucker", "Bei Schaumwein trockener als trocken."],
       ["Jahrgang", "Jahr der Traubenernte", "Bei Schaumwein oft nicht angegeben."],
       ["Maischegärung", "Gärung mit Schalen", "Nur so entsteht Rotwein aus roten Trauben."],
       ["Korkschmecker", "Fehlton durch Korkfehler", "Riecht nach feuchtem Karton."],
       ["Restsüße", "Verbliebener Zucker", "Bestimmt die Einstufung von trocken bis süß."],
       ["Prädikatswein", "Nach Mostgewicht eingestuft", "Von Kabinett bis Trockenbeerenauslese."],
       ["Assemblage", "Zusammenstellung der Partien", "Die eigentliche Kunst im Weinkeller."]]'::jsonb,
     '[["Zweite Gärung in der Flasche", "Das ist die Méthode traditionnelle, sie steht nicht auf dem Brett."],
       ["Alkoholzugabe stoppt die Gärung", "So entsteht ein Likörwein, der hier fehlt."]]'::jsonb),

    ('essen-trinken', 'konservierung', 'Haltbarmachen',
     'Wie wird das Lebensmittel haltbar gemacht?',
     'medium', 'Konservierung',
     'https://de.wikipedia.org/wiki/Konservierung',
     '[["Einkochen", "Hitze und luftdichtes Glas", "Beim Abkühlen entsteht der Unterdruck."],
       ["Einfrieren", "Wasser wird zu Eis", "Mikroben können ohne freies Wasser nicht arbeiten."],
       ["Trocknen", "Wasser wird entzogen", "Älteste Methode überhaupt."],
       ["Pökeln", "Salz und Nitritsalz", "Das Fleisch bleibt zugleich rot."],
       ["Einlegen in Essig", "Säure hemmt Keime", "Unter pH 4,5 wird es kritisch für Bakterien."],
       ["Zuckern", "Hoher Zuckeranteil bindet Wasser", "Prinzip jeder Konfitüre."],
       ["Vakuumieren", "Ohne Sauerstoff verpacken", "Bremst Fäulnisbakterien und Ranzigkeit."],
       ["Sterilisieren", "Erhitzen im Überdruck", "Auch Sporen werden abgetötet."],
       ["Kandieren", "In Zuckersirup einlegen", "Für Früchte und Blüten."],
       ["Schutzatmosphäre", "Luft durch Gasgemisch ersetzt", "Meist Stickstoff und Kohlendioxid."]]'::jsonb,
     '[["Rauch legt sich auf die Oberfläche", "Räuchern steht nicht auf diesem Brett."],
       ["Bestrahlung tötet die Keime ab", "Ein zugelassenes Verfahren, das hier fehlt."]]'::jsonb),

    ('essen-trinken', 'ueberraschende-herkunft', 'Überraschende Herkunft',
     'Woher stammt das Gericht wirklich?',
     'hard', 'Esskultur', 'https://de.wikipedia.org/wiki/Esskultur',
     '[["Ketchup", "China", "Ursprünglich eine fermentierte Fischsauce namens ke-tsiap."],
       ["Pommes frites", "Belgien", "Belgien beansprucht die Erfindung für sich."],
       ["Croissant", "Wien", "Aus dem Kipferl, in Paris verfeinert."],
       ["Chicken Tikka Masala", "Glasgow", "Angeblich für einen Gast erfunden, der Sauce wollte."],
       ["Tempura", "Japan über Portugal", "Portugiesische Missionare brachten das Frittieren mit."],
       ["Glückskeks", "Japan", "In Kalifornien populär geworden, in China unbekannt."],
       ["Vindaloo", "Portugal", "Aus carne de vinha d''alhos, Fleisch in Wein und Knoblauch."],
       ["Spaghetti Bolognese", "Großbritannien", "In Bologna gibt es sie in dieser Form nicht."],
       ["Hawaii-Pizza", "Kanada", "Von einem griechischstämmigen Wirt in Ontario erfunden."],
       ["Döner im Fladenbrot", "Berlin", "Das Fleisch ist türkisch, die Imbissform entstand hier."],
       ["Nudel", "Zentralasien", "Der älteste Fund einer Nudel ist rund 4000 Jahre alt."],
       ["Kartoffelchips", "USA", "Angeblich aus Ärger über einen Gast entstanden."]]'::jsonb,
     '[["Mexiko", "Der Caesar Salad entstand dort, er steht nicht auf dem Brett."],
       ["Neuseeland", "Die Pavlova wird dort beansprucht, hier fehlt sie."]]'::jsonb),

    ('essen-trinken', 'suesswaren-marken', 'Süßwaren & Herkunftsländer',
     'Aus welchem Land stammt die Marke?',
     'medium', 'Süßware', 'https://de.wikipedia.org/wiki/S%C3%BC%C3%9Fware',
     '[["Toblerone", "Schweiz", "Die Bergform zeigt das Matterhorn."],
       ["Haribo", "Deutschland", "Der Name steht für Hans Riegel Bonn."],
       ["Cadbury", "England", "Von einer Quäkerfamilie gegründet."],
       ["Ferrero", "Italien", "Aus einer Konditorei im Piemont."],
       ["Godiva", "Belgien", "Benannt nach einer englischen Sagengestalt."],
       ["Marabou", "Schweden", "Nach dem Vogel im Firmenlogo."],
       ["Fazer", "Finnland", "Das Blau der Verpackung ist markenrechtlich geschützt."],
       ["Hershey", "USA", "Baute eine ganze Fabrikstadt in Pennsylvania."],
       ["Meiji", "Japan", "Auch für die Pilzkekse bekannt."],
       ["Manner", "Österreich", "Die rosa Schnitten heißen nach dem Stephansdom."],
       ["Anthon Berg", "Dänemark", "Marzipan und Likörpralinen."],
       ["Wedel", "Polen", "Warschauer Traditionsschokolade seit 1851."]]'::jsonb,
     '[["Frankreich", "Carambar käme von dort, die Marke fehlt auf dem Brett."],
       ["Niederlande", "Venco und sein Lakritz stehen hier nicht."]]'::jsonb),

    ('essen-trinken', 'deutsche-spezialitaeten', 'Regionale Spezialitäten',
     'Aus welcher Region stammt das Gericht?',
     'medium', 'Deutsche Küche',
     'https://de.wikipedia.org/wiki/Deutsche_K%C3%BCche',
     '[["Weißwurst", "Bayern", "Soll das Zwölfuhrläuten nicht erleben."],
       ["Labskaus", "Hamburg", "Seemannsgericht mit Rote Bete und Spiegelei."],
       ["Handkäs mit Musik", "Hessen", "Die Musik sind Zwiebeln in Essig und Öl."],
       ["Maultaschen", "Schwaben", "Auch Herrgottsbscheißerle genannt."],
       ["Grünkohl mit Pinkel", "Niedersachsen", "Wird traditionell nach dem ersten Frost gegessen."],
       ["Halve Hahn", "Köln", "Kein Hähnchen, sondern Roggenbrötchen mit Käse."],
       ["Saumagen", "Pfalz", "Durch einen Bundeskanzler international bekannt."],
       ["Spreewaldgurken", "Brandenburg", "Geschützte geografische Angabe."],
       ["Königsberger Klopse", "Ostpreußen", "Mit Kapernsauce serviert."],
       ["Thüringer Rostbratwurst", "Thüringen", "Mindestens 15 Zentimeter lang."],
       ["Schwarzwälder Kirschtorte", "Baden", "Kirschwasser gehört zwingend hinein."],
       ["Rollmops", "Ostseeküste", "Marinierter Hering um eine Gurke gerollt."]]'::jsonb,
     '[["Sachsen", "Der Dresdner Christstollen käme von dort, er fehlt hier."],
       ["Saarland", "Der Dibbelabbes steht nicht auf dem Brett."]]'::jsonb),

    ('essen-trinken', 'suppen-laender', 'Suppen der Welt',
     'Aus welchem Land stammt die Suppe?',
     'medium', 'Suppe', 'https://de.wikipedia.org/wiki/Suppe',
     '[["Borschtsch", "Ukraine", "Rote Bete gibt die Farbe."],
       ["Gazpacho", "Spanien", "Wird kalt gegessen, aus rohem Gemüse."],
       ["Misosuppe", "Japan", "Wird nie gekocht, sondern nur erhitzt."],
       ["Pho", "Vietnam", "Die Brühe zieht viele Stunden."],
       ["Tom Yum", "Thailand", "Sauer und scharf, mit Zitronengras."],
       ["Minestrone", "Italien", "Was der Garten hergibt, kommt hinein."],
       ["Gulaschsuppe", "Ungarn", "Ursprünglich das Essen der Rinderhirten."],
       ["Bouillabaisse", "Frankreich", "Aus Marseille, ursprünglich aus unverkäuflichem Fisch."],
       ["Harira", "Marokko", "Wird im Ramadan zum Fastenbrechen gegessen."],
       ["Kimchi-Jjigae", "Südkorea", "Je älter das Kimchi, desto besser."],
       ["Soljanka", "Russland", "Sauer durch Salzgurken und Zitrone."],
       ["Callaloo", "Karibik", "Aus grünen Blättern und Kokosmilch."]]'::jsonb,
     '[["Griechenland", "Avgolemono wäre die Suppe dazu, sie fehlt hier."],
       ["China", "Die scharf-saure Suppe steht nicht auf dem Brett."]]'::jsonb),

    ('essen-trinken', 'reissorten', 'Reissorten',
     'Wofür wird der Reis verwendet oder woher kommt er?',
     'hard', 'Reis', 'https://de.wikipedia.org/wiki/Reis',
     '[["Basmati", "Indien und Pakistan", "Duftreis, der beim Kochen länger wird."],
       ["Jasminreis", "Thailand", "Klebt leicht, duftet blumig."],
       ["Arborio", "Risotto", "Gibt Stärke ab und macht cremig."],
       ["Sushi-Reis", "Japan", "Wird mit Essig, Zucker und Salz gewürzt."],
       ["Bomba", "Paella", "Saugt viel Flüssigkeit auf, ohne zu zerfallen."],
       ["Wildreis", "Nordamerika", "Botanisch ein Wassergras, kein Reis."],
       ["Klebreis", "Südostasien", "Wird gedämpft und mit der Hand gegessen."],
       ["Schwarzer Reis", "China", "Galt einst als dem Kaiser vorbehalten."],
       ["Parboiled", "Vorbehandelt im Dampf", "Vitamine wandern dabei nach innen."],
       ["Milchreis", "Rundkorn für Süßspeisen", "Kocht besonders weich."]]'::jsonb,
     '[["Iran", "Der Sadri-Reis käme von dort, er steht nicht auf dem Brett."],
       ["Rot durch die Schale", "Das wäre roter Camargue-Reis, und der fehlt hier."]]'::jsonb),

    ('essen-trinken', 'ernaehrungsformen', 'Ernährungsformen',
     'Was bedeutet die Ernährungsweise?',
     'medium', 'Ernährung', 'https://de.wikipedia.org/wiki/Ern%C3%A4hrung',
     '[["Vegetarisch", "Ohne Fleisch und Fisch", "Eier und Milch bleiben meist erlaubt."],
       ["Vegan", "Ohne alle Tierprodukte", "Auch Honig und Gelatine fallen weg."],
       ["Pescetarisch", "Fisch ja, Fleisch nein", "Häufig aus gesundheitlichen Gründen."],
       ["Flexitarisch", "Selten und bewusst Fleisch", "Menge statt Verzicht als Prinzip."],
       ["Paleo", "Angelehnt an die Steinzeit", "Ohne Getreide, Milch und Zucker."],
       ["Ketogen", "Sehr wenig Kohlenhydrate", "Der Körper stellt auf Fettverbrennung um."],
       ["Halal", "Nach islamischen Regeln erlaubt", "Kein Schwein, kein Alkohol."],
       ["Koscher", "Nach jüdischen Speisegesetzen", "Fleisch und Milch bleiben getrennt."],
       ["Rohkost", "Nichts stark erhitzt", "Enzyme sollen erhalten bleiben."],
       ["Frutarisch", "Nur freiwillige Pflanzengaben", "Ohne die Pflanze selbst zu töten."],
       ["Makrobiotik", "Vollkorn im Gleichgewicht", "Aus japanischer Tradition abgeleitet."],
       ["Ayurvedisch", "Nach Konstitutionstypen", "Gewürze werden gezielt eingesetzt."]]'::jsonb,
     '[["Nur in festen Zeitfenstern essen", "Das ist Intervallfasten, es steht nicht auf dem Brett."],
       ["Ohne Klebereiweiß", "Nötig bei Zöliakie, aber keine Zeile auf diesem Brett."]]'::jsonb),

    ('essen-trinken', 'kuechenchemie', 'Chemie in der Küche',
     'Was passiert dabei?',
     'hard', 'Lebensmittelchemie',
     'https://de.wikipedia.org/wiki/Lebensmittelchemie',
     '[["Maillard-Reaktion", "Bräunung mit neuen Aromen", "Zucker und Eiweiß reagieren über 140 Grad."],
       ["Denaturierung", "Eiweiß gerinnt", "Deshalb wird das Ei fest."],
       ["Emulsion", "Fett in Wasser verteilt", "Ein Emulgator hält beides zusammen."],
       ["Verkleisterung", "Stärke bindet Flüssigkeit", "Grundlage jeder Sauce mit Mehl."],
       ["Osmose", "Salz zieht Wasser heraus", "Deshalb salzt man Auberginen vor."],
       ["Umami", "Der fünfte Geschmack", "1908 an Kombu-Algen beschrieben."],
       ["Capsaicin", "Schärfe im Chili", "Reizt Wärmerezeptoren, nicht die Geschmacksknospen."],
       ["Menthol", "Kühlender Eindruck", "Löst das Kältesignal ohne Kälte aus."],
       ["Gluten", "Klebernetz im Teig", "Entsteht erst beim Kneten mit Wasser."],
       ["Enzymatische Bräunung", "Apfel wird braun", "Zitronensaft bremst die Reaktion."],
       ["Karamellisierung", "Zucker zerfällt und bräunt", "Läuft ohne Eiweiß ab."],
       ["Sphärifikation", "Flüssigkeit in einer Gelhülle", "Mit Alginat und Calcium."]]'::jsonb,
     '[["Alkohol verdampft vor dem Wasser", "Stimmt, ist hier aber keine Antwort."],
       ["Backpulver setzt Kohlendioxid frei", "Das treibt den Teig, steht auf diesem Brett aber nicht."]]'::jsonb),

    ('essen-trinken', 'gewuerzmischungen', 'Gewürzmischungen',
     'Aus welcher Küche stammt die Mischung?',
     'hard', 'Gewürzmischung',
     'https://de.wikipedia.org/wiki/Gew%C3%BCrzmischung',
     '[["Garam Masala", "Indien", "Wird oft erst am Ende zugegeben."],
       ["Ras el-Hanout", "Marokko", "Der Name bedeutet Kopf des Ladens."],
       ["Za''atar", "Levante", "Thymian, Sesam und Sumach."],
       ["Berbere", "Äthiopien", "Scharf, mit Bockshornklee und Chili."],
       ["Shichimi Togarashi", "Japan", "Sieben Zutaten, darunter Orangenschale."],
       ["Fünf-Gewürze-Pulver", "China", "Deckt alle fünf Geschmacksrichtungen ab."],
       ["Herbes de Provence", "Frankreich", "Thymian, Rosmarin, Oregano und Bohnenkraut."],
       ["Cajun-Mischung", "Louisiana", "Paprika, Cayenne und Knoblauch."],
       ["Baharat", "Arabische Halbinsel", "Der Name heißt schlicht Gewürze."],
       ["Curry-Pulver", "Britisch-Indien", "Eine britische Erfindung für den Export."],
       ["Chimichurri-Mischung", "Argentinien", "Trockene Variante der Kräutersauce."],
       ["Adjika", "Georgien", "Scharfe Paste aus Chili und Kräutern."]]'::jsonb,
     '[["Mexiko", "Die Adobo-Paste käme von dort, sie fehlt auf dem Brett."],
       ["Ungarn", "Edelsüßes Paprikapulver steht hier nicht."]]'::jsonb),

    ('essen-trinken', 'botanik-obst', 'Obst botanisch betrachtet',
     'Was ist es botanisch wirklich?',
     'hard', 'Frucht', 'https://de.wikipedia.org/wiki/Frucht',
     '[["Erdbeere", "Scheinfrucht", "Die echten Früchte sind die Nüsschen darauf."],
       ["Banane", "Beere", "Die Kulturform bildet keine Samen mehr aus."],
       ["Ananas", "Fruchtverband", "Viele Einzelfrüchte verwachsen zu einer."],
       ["Feige", "Umgestülpter Blütenstand", "Die Blüten liegen im Inneren."],
       ["Kokosnuss", "Steinfrucht", "Trotz des Namens keine Nuss."],
       ["Himbeere", "Sammelsteinfrucht", "Jedes Kügelchen ist eine eigene Frucht."],
       ["Apfel", "Kernobst mit Blütenboden", "Das Fleisch stammt nicht vom Fruchtknoten."],
       ["Erdnuss", "Hülsenfrucht", "Reift unter der Erde heran."],
       ["Rhabarber", "Blattstiel", "Gemüse, das wie Obst verwendet wird."],
       ["Zitrone", "Panzerbeere", "Eine Beere mit lederiger Schale."],
       ["Walnuss", "Schließfrucht mit harter Schale", "Die grüne Hülle fällt vorher ab."],
       ["Avocado", "Einsamige Beere", "Der größte Kern im Obstregal."]]'::jsonb,
     '[["Zwiebelgewächs", "Auf keinen Eintrag dieser Liste trifft das zu."],
       ["Wurzelknolle", "Das wäre die Süßkartoffel, und die steht nicht auf dem Brett."]]'::jsonb),

    ('essen-trinken', 'trinkgefaesse', 'Gläser & Getränke',
     'Wofür ist das Gefäß gedacht?',
     'medium', 'Trinkgefäß',
     'https://de.wikipedia.org/wiki/Trinkgef%C3%A4%C3%9F',
     '[["Weizenglas", "Weizenbier", "Die Form gibt dem Schaum Platz."],
       ["Sektflöte", "Schaumwein", "Schmal, damit die Perlen lange steigen."],
       ["Tumbler", "Whisky pur", "Dicker Boden, keine Verjüngung."],
       ["Kupferbecher", "Moscow Mule", "Das Metall hält den Drink länger kalt."],
       ["Ballonglas", "Gin Tonic", "Viel Platz für Eis und Aromen."],
       ["Espressotasse", "Espresso", "Vorgewärmt, damit die Crema hält."],
       ["Sherryglas", "Sherry", "Kleines Kelchglas, Copita genannt."],
       ["Sake-Schale", "Sake", "Wird traditionell dem Gegenüber eingeschenkt."],
       ["Bierstange", "Kölsch", "Schmal und klein, damit es frisch bleibt."],
       ["Burgunderglas", "Rotwein mit feinem Bukett", "Große Kugel für viel Luftkontakt."]]'::jsonb,
     '[["Portwein", "Das Portweinglas fehlt auf diesem Brett."],
       ["Grüner Tee", "Die japanische Teeschale steht hier nicht."]]'::jsonb),

    ('essen-trinken', 'kuechensprache', 'Küchensprache',
     'Was bedeutet die Anweisung?',
     'hard', 'Kochen', 'https://de.wikipedia.org/wiki/Kochen',
     '[["Ablöschen", "Bratensatz mit Flüssigkeit lösen", "Der Geschmack sitzt im Angebratenen."],
       ["Montieren", "Kalte Butter einschwenken", "Gibt der Sauce Glanz und Bindung."],
       ["Blindbacken", "Teig ohne Füllung vorbacken", "Mit Hülsenfrüchten beschwert."],
       ["Abschrecken", "In kaltem Wasser stoppen", "Erhält Farbe und Biss."],
       ["Al dente", "Mit Biss gegart", "Wörtlich: für den Zahn."],
       ["Legieren", "Binden mit Eigelb", "Darf danach nicht mehr kochen."],
       ["Tournieren", "In gleiche Form schneiden", "Sieht gut aus und gart gleichmäßig."],
       ["Bardieren", "Mageres mit Speck umwickeln", "Schützt vor dem Austrocknen."],
       ["Glasieren", "Glänzend einkochen lassen", "Klassisch für Möhren."],
       ["Panieren", "Mehl, Ei und Semmelbrösel", "In genau dieser Reihenfolge."],
       ["Mise en place", "Alles vorher bereitstellen", "Ohne sie wird jeder Service hektisch."],
       ["Abschmecken", "Zum Schluss anpassen", "Salz, Säure, Süße und Schärfe."]]'::jsonb,
     '[["Fleisch vor dem Garen einlegen", "Das ist Marinieren, es steht nicht auf dem Brett."],
       ["Durch ein feines Sieb streichen", "Das heißt Passieren, und es fehlt hier."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

-- The answers that belong to no category. Numbered after the pairs so the two
-- sets never collide on `position`, though nothing reads it for a fake: the
-- pool is shuffled before a player sees it, and the review lists fakes on their
-- own rather than in board order.
fakes as (
    select q.id                                         as quiz_id,
           k.value ->> 0                                as label,
           k.value ->> 1                                as explanation,
           (jsonb_array_length(sp.pairs) + k.ord)::int  as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.fakes) with ordinality k(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
),

paired as (
    insert into items (quiz_id, category_id, label, position, explanation)
    select f.quiz_id, c.id, f.answer, f.position, f.explanation
      from flat f
      join new_categories c
        on c.quiz_id = f.quiz_id
       and c.label = f.label
    returning id
)

-- Same table, `category_id` left null. Both inserts run in the one statement,
-- so `items_quiz_id_label_key` still sees the pairs above: a fake written to
-- repeat an answer already on its own board fails the file rather than becoming
-- a second row nobody can tell apart.
insert into items (quiz_id, category_id, label, position, explanation)
select k.quiz_id, null, k.label, k.position, k.explanation
  from fakes k;
