-- Film & Fernsehen, leichte Fragen. Zwanzig Fragen, alle 'easy'.
--
-- Gefragt wird nach dem, was jeder schon gesehen hat, nicht nach
-- Erzählformen und Festivaltrophäen.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs, fakes) as (
    values

    ('film-fernsehen', 'leicht-trickfilmfiguren', 'Trickfilmfiguren',
     'Aus welchem Film oder welcher Serie stammt die Figur?',
     'easy', 'Zeichentrickfilm',
     'https://de.wikipedia.org/wiki/Zeichentrickfilm',
     '[["Simba", "Der König der Löwen", "Ein Löwenjunges wird König."],
       ["Arielle", "Arielle, die Meerjungfrau", "Sie will an Land leben."],
       ["Woody", "Toy Story", "Ein Cowboy aus Stoff."],
       ["Elsa", "Die Eiskönigin", "Sie kann Eis erschaffen."],
       ["Nemo", "Findet Nemo", "Ein Clownfisch verirrt sich."],
       ["Prinzessin Fiona", "Shrek", "Sie verwandelt sich bei Sonnenuntergang."],
       ["Remy", "Ratatouille", "Eine Ratte will kochen."],
       ["EVE", "WALL·E", "Ein weißer Suchroboter."],
       ["Bart", "Die Simpsons", "Er schreibt zur Strafe an die Tafel."],
       ["Spongebob", "Spongebob Schwammkopf", "Er wohnt in einer Ananas."],
       ["Pikachu", "Pokémon", "Gelb, mit Blitzschwanz."],
       ["Olaf", "Frozen-Filme", "Ein Schneemann, der Sommer mag."]]'::jsonb,
     '[["Cinderella", "Der Film steht nicht auf diesem Brett."],
       ["Bambi", "Auch ein Zeichentrickfilm, aber keine Figur hier stammt daraus."]]'::jsonb),

    ('film-fernsehen', 'leicht-berufe-film', 'Wer macht was beim Film?',
     'Wer ist dafür zuständig?',
     'easy', 'Film', 'https://de.wikipedia.org/wiki/Film',
     '[["Spielt eine Rolle", "Schauspieler", "Er lernt seinen Text auswendig."],
       ["Sagt, wie gespielt wird", "Regisseur", "Er ruft Action und Cut."],
       ["Hält das Bild fest", "Kameramann", "Er wählt Ausschnitt und Licht."],
       ["Schreibt die Geschichte", "Drehbuchautor", "Eine Seite ist etwa eine Minute Film."],
       ["Schneidet die Szenen zusammen", "Cutter", "Er bestimmt den Rhythmus."],
       ["Schminkt und frisiert", "Maskenbildner", "Auch Wunden und Alterung."],
       ["Sucht die Kleidung aus", "Kostümbildner", "Die Kleidung erzählt mit."],
       ["Nimmt den Ton auf", "Tonmeister", "Die Angel bleibt knapp außerhalb des Bildes."],
       ["Bezahlt den Film", "Produzent", "Ohne ihn wird nicht gedreht."],
       ["Springt bei gefährlichen Szenen ein", "Stuntman", "Er trainiert jede Bewegung."],
       ["Spricht die deutsche Fassung", "Synchronsprecher", "Er sieht dabei das Bild mit."],
       ["Schreibt die Musik", "Filmkomponist", "Sie erzählt ohne Worte mit."]]'::jsonb,
     '[["Beleuchter", "Er stellt das Licht, und danach wird hier nicht gefragt."],
       ["Requisiteur", "Er sorgt für die Gegenstände, die auf dem Brett nicht vorkommen."]]'::jsonb),

    ('film-fernsehen', 'leicht-genres', 'Filmarten',
     'Welche Filmart ist das?',
     'easy', 'Filmgenre', 'https://de.wikipedia.org/wiki/Filmgenre',
     '[["Zum Lachen gemacht", "Komödie", "Am Ende geht meist alles gut aus."],
       ["Zum Fürchten gemacht", "Horrorfilm", "Dunkelheit und plötzliche Geräusche."],
       ["Mit Cowboys und Prärie", "Western", "Meist im 19. Jahrhundert."],
       ["Mit Raumschiffen und Zukunft", "Science-Fiction", "Technik, die es noch nicht gibt."],
       ["Mit Drachen und Zauberei", "Fantasyfilm", "Eigene Welten mit eigenen Regeln."],
       ["Mit Verfolgungsjagden", "Actionfilm", "Viel Tempo, wenig Ruhe."],
       ["Über eine echte Begebenheit", "Dokumentarfilm", "Ohne erfundene Handlung."],
       ["Über eine Liebesgeschichte", "Liebesfilm", "Zwei finden sich, verlieren sich, finden sich."],
       ["Mit einem Kriminalfall", "Krimi", "Am Ende wird aufgeklärt."],
       ["Für die ganze Familie", "Familienfilm", "Auch Erwachsene langweilen sich nicht."],
       ["Gezeichnet statt gefilmt", "Zeichentrickfilm", "Früher Bild für Bild gemalt."],
       ["Mit Gesang und Tanz", "Musicalfilm", "Die Handlung geht im Lied weiter."]]'::jsonb,
     '[["Kriegsfilm", "Eine eigene Filmart, die hier nicht beschrieben wird."],
       ["Stummfilm", "Ganz ohne gesprochenes Wort, auf dem Brett steht das nicht."]]'::jsonb),

    ('film-fernsehen', 'leicht-kino', 'Im Kino',
     'Was ist das?',
     'easy', 'Kino', 'https://de.wikipedia.org/wiki/Kino',
     '[["Große weiße Fläche vorn", "Leinwand", "Das Bild wird darauf geworfen."],
       ["Gerät, das das Bild wirft", "Projektor", "Heute meist digital."],
       ["Kurzer Film vor dem Hauptfilm", "Trailer", "Er wirbt für kommende Filme."],
       ["Papier, das den Platz zeigt", "Eintrittskarte", "Reihe und Sitznummer stehen darauf."],
       ["Beliebter Knabberkram", "Popcorn", "Er wird direkt im Kino gemacht."],
       ["Namen am Ende des Films", "Abspann", "Manchmal kommt danach noch eine Szene."],
       ["Text unten im Bild", "Untertitel", "Für fremdsprachige Filme."],
       ["Brille für räumliches Sehen", "3D-Brille", "Jedes Auge sieht ein anderes Bild."],
       ["Der erste Tag eines Films", "Premiere", "Oft mit den Schauspielern vor Ort."],
       ["Kino unter freiem Himmel", "Open-Air-Kino", "Im Sommer nach Sonnenuntergang."]]'::jsonb,
     '[["Kinoorgel", "Sie begleitete früher Stummfilme, hier ist sie keine Antwort."],
       ["Garderobe", "Für die Mäntel, danach fragt auf dem Brett niemand."]]'::jsonb),

    ('film-fernsehen', 'leicht-fernsehformate', 'Sendungen im Fernsehen',
     'Was für eine Sendung ist das?',
     'easy', 'Fernsehen', 'https://de.wikipedia.org/wiki/Fernsehen',
     '[["Berichtet, was heute passiert ist", "Nachrichten", "In Deutschland um 20 Uhr."],
       ["Sagt das Wetter voraus", "Wetterbericht", "Direkt nach den Nachrichten."],
       ["Zeigt Tore und Ergebnisse", "Sportsendung", "Samstags nach den Spielen."],
       ["Ratefragen um Geld", "Quizshow", "Der Kandidat sitzt gegenüber."],
       ["Menschen kochen um die Wette", "Kochshow", "Eine Jury probiert."],
       ["Erklärt Kindern die Welt", "Kindersendung", "Oft mit Zeichentrick dazwischen."],
       ["Geschichte in vielen Folgen", "Serie", "Eine Staffel hat mehrere Folgen."],
       ["Zeigt Tiere und Natur", "Tierdokumentation", "Oft mit ruhiger Erzählstimme."],
       ["Gespräche mit Gästen im Studio", "Talkshow", "Meist am späten Abend."],
       ["Wirbt für Produkte", "Werbung", "Sie unterbricht das Programm."]]'::jsonb,
     '[["Hörspiel", "Das läuft im Radio, nicht im Fernsehen."],
       ["Livekonzert", "Eine Übertragung, die auf diesem Brett fehlt."]]'::jsonb),

    ('film-fernsehen', 'leicht-superhelden', 'Superhelden',
     'Welche Fähigkeit oder welches Zeichen gehört dazu?',
     'easy', 'Superheld', 'https://de.wikipedia.org/wiki/Superheld',
     '[["Superman", "Fliegen und Superkraft", "Kryptonit schwächt ihn."],
       ["Spider-Man", "An Wänden klettern", "Nach dem Biss einer Spinne."],
       ["Batman", "Reich, aber ohne Superkraft", "Er verlässt sich auf Technik."],
       ["Wonder Woman", "Lasso der Wahrheit", "Wer gefesselt ist, lügt nicht."],
       ["Iron Man", "Anzug aus Metall", "Gebaut von ihm selbst."],
       ["Hulk", "Wird grün und riesig", "Wenn er wütend wird."],
       ["Thor", "Hammer aus dem Norden", "Nur Würdige können ihn heben."],
       ["Flash", "Rennt unglaublich schnell", "Schneller als das Auge sieht."],
       ["Captain America", "Runder Schild", "Er wirft ihn wie ein Wurfgeschoss."],
       ["Black Panther", "König von Wakanda", "Sein Anzug speichert Energie."]]'::jsonb,
     '[["Kann sich unsichtbar machen", "Das kann die Unsichtbare, und die steht hier nicht."],
       ["Spricht mit Fischen", "Aquaman wäre das, und der fehlt auf dem Brett."]]'::jsonb),

    ('film-fernsehen', 'leicht-kinderfilme', 'Kinderfilme',
     'Worum geht es?',
     'easy', 'Kinderfilm', 'https://de.wikipedia.org/wiki/Kinderfilm',
     '[["Das Dschungelbuch", "Junge unter Tieren", "Balu bringt ihm die Gemütlichkeit bei."],
       ["Bambi", "Ein Reh im Wald", "Der Waldbrand ist die berühmteste Szene."],
       ["Pinocchio", "Holzpuppe will Junge werden", "Beim Lügen wächst die Nase."],
       ["Aschenputtel", "Ein Schuh entscheidet alles", "Um Mitternacht endet der Zauber."],
       ["Die Unendliche Geschichte", "Junge liest sich hinein", "Fantasien droht das Nichts."],
       ["E.T.", "Ein Außerirdischer will heim", "Ein Fahrrad fliegt vor dem Mond."],
       ["Kevin allein zu Haus", "Ein Kind bleibt zurück", "Es verteidigt das Haus mit Fallen."],
       ["Paddington", "Bär in London", "Er trägt Dufflecoat und Hut."],
       ["Die Kinder von Bullerbü", "Sommer auf dem Land", "Nach einem Buch von Astrid Lindgren."],
       ["Findet Dorie", "Fisch ohne Gedächtnis", "Sie sucht ihre Eltern."]]'::jsonb,
     '[["Ein Haus fliegt an Luftballons davon", "Das ist Oben, der Film fehlt hier."],
       ["Ein Mädchen fällt in ein Kaninchenloch", "Alice steht nicht auf diesem Brett."]]'::jsonb),

    ('film-fernsehen', 'leicht-serienfiguren', 'Figuren aus Serien',
     'Aus welcher Serie stammt die Figur?',
     'easy', 'Fernsehserie',
     'https://de.wikipedia.org/wiki/Fernsehserie',
     '[["Homer Simpson", "Die Simpsons", "Er arbeitet im Kernkraftwerk."],
       ["Sheldon Cooper", "The Big Bang Theory", "Er hat einen festen Sitzplatz."],
       ["Michael Scott", "The Office", "Er hält sich für den besten Chef."],
       ["Eleven", "Stranger Things", "Ein Mädchen mit besonderen Kräften."],
       ["Walter White", "Breaking Bad", "Ein Chemielehrer schlägt einen falschen Weg ein."],
       ["Jon Schnee", "Game of Thrones", "Er zieht an die Mauer im Norden."],
       ["Der Schäferhund Rex", "Kommissar Rex", "Er löst Wiener Kriminalfälle mit."],
       ["Amerikanischer Trainer in London", "Ted Lasso", "Er kennt die Fußballregeln kaum."],
       ["Kobold in der Schreinerei", "Pumuckl", "Nur Meister Eder kann ihn sehen."],
       ["Mann mit dem grünen Mini", "Mr. Bean", "Er kommt fast ohne Worte aus."],
       ["Sprechender Elefant aus Neustadt", "Benjamin Blümchen", "Sein Ruf klingt wie Törööö."]]'::jsonb,
     '[["Raumschiff Enterprise", "Captain Kirk käme daher, die Serie fehlt hier."],
       ["Wickie und die starken Männer", "Keine Figur auf diesem Brett stammt daraus."]]'::jsonb),

    ('film-fernsehen', 'leicht-filmtiere', 'Tiere im Film',
     'Welches Tier ist das?',
     'easy', 'Film', 'https://de.wikipedia.org/wiki/Film',
     '[["Lassie", "Collie", "Sie findet immer nach Hause."],
       ["Flipper", "Delfin", "Er hilft Menschen in Not."],
       ["Free Willy", "Orca", "Ein Junge lässt ihn frei."],
       ["King Kong", "Riesenaffe", "Er klettert auf ein Hochhaus."],
       ["Babe", "Schwein", "Es hütet Schafe."],
       ["Beethoven", "Bernhardiner", "Ein sehr großer Familienhund."],
       ["Dumbo", "Elefant", "Seine Ohren tragen ihn."],
       ["Simba", "Löwe", "Er wird König der Tiere."],
       ["Nemo", "Clownfisch", "Er lebt in einer Anemone."],
       ["Balu", "Bär", "Er singt vom Nötigsten im Leben."],
       ["Shere Khan", "Tiger", "Der Gegner im Dschungelbuch."],
       ["Hachiko", "Akita", "Er wartete jahrelang am Bahnhof."]]'::jsonb,
     '[["Pferd", "Kein Filmtier auf diesem Brett ist ein Pferd."],
       ["Papagei", "Kein Tier in dieser Liste ist ein Vogel."]]'::jsonb),

    ('film-fernsehen', 'leicht-filmsprache', 'Wörter vom Filmset',
     'Was bedeutet das?',
     'easy', 'Film', 'https://de.wikipedia.org/wiki/Film',
     '[["Action", "Die Aufnahme beginnt", "Der Ruf des Regisseurs."],
       ["Cut", "Die Aufnahme stoppt", "Danach folgt oft ein neuer Versuch."],
       ["Take", "Ein einzelner Versuch", "Manche Szenen brauchen dutzende."],
       ["Klappe", "Zeigt Szene und Nummer", "Das Knacken hilft beim Ton."],
       ["Statist", "Person im Hintergrund", "Ohne Sprechrolle."],
       ["Kulisse", "Gebauter Hintergrund", "Oft nur eine Fassade."],
       ["Double", "Ersatz für den Schauspieler", "Bei gefährlichen Szenen."],
       ["Greenscreen", "Grüner Hintergrund", "Er wird später ersetzt."],
       ["Drehtag", "Ein Tag am Set", "Meist zwölf Stunden lang."],
       ["Premiere", "Erste Vorführung", "Mit rotem Teppich."]]'::jsonb,
     '[["Die Pause zum Essen am Set", "Die Drehpause steht nicht auf dem Brett."],
       ["Der Plan für den Drehtag", "Der Drehplan kommt hier nicht vor."]]'::jsonb),

    ('film-fernsehen', 'leicht-maerchenfilme', 'Märchen im Film',
     'Welches Märchen wird erzählt?',
     'easy', 'Märchenfilm',
     'https://de.wikipedia.org/wiki/M%C3%A4rchenfilm',
     '[["Ein Mädchen und sieben Zwerge", "Schneewittchen", "Der Apfel ist vergiftet."],
       ["Ein verlorener Schuh", "Aschenputtel", "Er passt nur einer."],
       ["Ein Mädchen mit roter Kappe", "Rotkäppchen", "Der Wolf wartet im Wald."],
       ["Ein Turm und sehr langes Haar", "Rapunzel", "Es dient als Leiter."],
       ["Hundert Jahre Schlaf", "Dornröschen", "Eine Hecke wächst um das Schloss."],
       ["Ein Lebkuchenhaus im Wald", "Hänsel und Gretel", "Eine Hexe wohnt darin."],
       ["Ein Frosch am Brunnen", "Der Froschkönig", "Eine goldene Kugel fällt hinein."],
       ["Ein Männlein mit geheimem Namen", "Rumpelstilzchen", "Es kann Stroh zu Gold spinnen."],
       ["Vier alte Tiere auf dem Weg", "Die Bremer Stadtmusikanten", "Sie vertreiben Räuber."],
       ["Sieben auf einen Streich", "Das tapfere Schneiderlein", "Gemeint sind Fliegen."]]'::jsonb,
     '[["Ein Esel, der Gold spuckt", "Tischlein deck dich steht nicht auf dem Brett."],
       ["Ein Mädchen mit Zündhölzern", "Das Märchen fehlt in dieser Liste."]]'::jsonb),

    ('film-fernsehen', 'leicht-filmreihen', 'Filmreihen',
     'Worum geht es in der Reihe?',
     'easy', 'Film', 'https://de.wikipedia.org/wiki/Film',
     '[["Star Wars", "Kampf im Weltraum", "Mit Lichtschwertern und der Macht."],
       ["Harry Potter", "Zauberschule in Schottland", "Sieben Bücher, acht Filme."],
       ["Der Herr der Ringe", "Ein Ring muss verschwinden", "Gedreht in Neuseeland."],
       ["Jurassic Park", "Dinosaurier im Themenpark", "Sie brechen natürlich aus."],
       ["James Bond", "Ein britischer Agent", "Mehrere Schauspieler in der Rolle."],
       ["Fluch der Karibik", "Piraten auf hoher See", "Mit einem sehr eigenwilligen Kapitän."],
       ["Ice Age", "Tiere in der Eiszeit", "Ein Eichhörnchen jagt eine Eichel."],
       ["Die Tribute von Panem", "Ein tödlicher Wettkampf", "Nach einer Jugendbuchreihe."],
       ["Findet Nemo und Findet Dorie", "Zwei Fische suchen jemanden", "Beide spielen im Meer."],
       ["Minions", "Kleine gelbe Helfer", "Sie sprechen eine erfundene Sprache."]]'::jsonb,
     '[["Autos, die sprechen können", "Das wäre Cars, und die Reihe fehlt hier."],
       ["Ein Boxer aus Philadelphia", "Rocky steht nicht auf dem Brett."]]'::jsonb),

    ('film-fernsehen', 'leicht-filmlaender', 'Filme & Länder',
     'Aus welchem Land kommt das?',
     'easy', 'Film', 'https://de.wikipedia.org/wiki/Film',
     '[["Hollywood", "USA", "Der bekannteste Filmstandort der Welt."],
       ["Bollywood", "Indien", "Filme mit viel Musik und Tanz."],
       ["Anime", "Japan", "Gezeichnete Filme und Serien."],
       ["Tatort", "Deutschland", "Sonntagabend im Ersten."],
       ["Asterix-Verfilmungen", "Frankreich", "Nach einer Comicreihe."],
       ["Spaghettiwestern", "Italien", "Gedreht meist in Spanien."],
       ["Pippi Langstrumpf", "Schweden", "Nach den Büchern von Astrid Lindgren."],
       ["Wallace & Gromit", "Vereinigtes Königreich", "Knetfiguren aus Bristol."],
       ["Squid Game", "Südkorea", "Eine Serie, die weltweit lief."],
       ["Tim und Struppi", "Belgien", "Ein Reporter mit weißem Hund."]]'::jsonb,
     '[["Spanien", "Keine Zeile auf diesem Brett führt dorthin."],
       ["Australien", "Auch von dort kommen Filme, hier steht keiner."]]'::jsonb),

    ('film-fernsehen', 'leicht-geraeusche', 'Ton & Musik im Film',
     'Wozu dient das?',
     'easy', 'Filmmusik', 'https://de.wikipedia.org/wiki/Filmmusik',
     '[["Spannende Musik", "Erzeugt Anspannung", "Oft schnelle, tiefe Streicher."],
       ["Ruhige Musik", "Beruhigt die Szene", "Sie lässt Bilder wirken."],
       ["Titelmelodie", "Erkennungszeichen des Films", "Man erkennt ihn an drei Tönen."],
       ["Geräusche von Schritten", "Wirkt echter", "Sie werden im Studio nachgemacht."],
       ["Stille an einer Stelle", "Betont den Moment", "Das Fehlen von Ton fällt auf."],
       ["Lied im Abspann", "Lässt nachklingen", "Oft eigens dafür geschrieben."],
       ["Stimme aus dem Off", "Erklärt oder erzählt", "Die Person ist nicht im Bild."],
       ["Lautes Krachen", "Schreckt auf", "Der Klassiker im Horrorfilm."],
       ["Musik einer Figur", "Kennzeichnet sie", "Sie erklingt, wenn die Figur kommt."],
       ["Originalton am Drehort", "Klingt natürlich", "Wind und Vögel inklusive."]]'::jsonb,
     '[["Verrät, wo die Kamera steht", "Kein Ton auf diesem Brett tut das."],
       ["Ersetzt die Untertitel", "Dafür ist keine Zeile hier gedacht."]]'::jsonb),

    ('film-fernsehen', 'leicht-fernsehgeraet', 'Fernsehen zu Hause',
     'Was ist das?',
     'easy', 'Fernsehen', 'https://de.wikipedia.org/wiki/Fernsehen',
     '[["Gerät mit Bildschirm", "Fernseher", "Heute meist flach an der Wand."],
       ["Damit schaltet man um", "Fernbedienung", "Sie funkt meist mit Infrarot."],
       ["Liste aller Sendungen", "Programm", "Früher stand sie in der Zeitung."],
       ["Sendungen zum Abruf", "Mediathek", "Auch nach der Ausstrahlung."],
       ["Abgabe für den Rundfunk", "Rundfunkbeitrag", "Je Wohnung, nicht je Gerät."],
       ["Zeit mit den meisten Zuschauern", "Hauptsendezeit", "Am Abend nach den Nachrichten."],
       ["Zahl der Zuschauer", "Einschaltquote", "Sie entscheidet über Fortsetzungen."],
       ["Sendung, die gerade läuft", "Livesendung", "Fehler sind sofort zu sehen."],
       ["Wiederholung einer alten Folge", "Wiederholung", "Beliebt am Nachmittag."],
       ["Dienst mit Serien im Netz", "Streamingdienst", "Ohne festen Sendeplan."]]'::jsonb,
     '[["Satellitenschüssel", "Sie holt das Signal, danach fragt hier niemand."],
       ["Videorekorder", "Ein Gerät von früher, das auf dem Brett nicht vorkommt."]]'::jsonb),

    ('film-fernsehen', 'leicht-schauspieler-bekannt', 'Bekannte Gesichter',
     'Wofür ist die Person bekannt?',
     'easy', 'Schauspieler',
     'https://de.wikipedia.org/wiki/Schauspieler',
     '[["Charlie Chaplin", "Der stumme Tramp", "Melone, Stock und große Schuhe."],
       ["Arnold Schwarzenegger", "Der Terminator", "Später Gouverneur von Kalifornien."],
       ["Tom Hanks", "Forrest Gump", "Er lief quer durch die USA."],
       ["Harrison Ford", "Indiana Jones", "Hut und Peitsche gehören dazu."],
       ["Daniel Radcliffe", "Harry Potter", "Er war elf beim ersten Film."],
       ["Meryl Streep", "Viele Oscar-Nominierungen", "Mehr als jede andere Person."],
       ["Til Schweiger", "Deutsche Kinokomödien", "Regie und Hauptrolle in einem."],
       ["Mr. Bean", "Komik fast ohne Worte", "Gespielt von Rowan Atkinson."],
       ["Jackie Chan", "Kampfszenen mit Humor", "Er macht viele Stunts selbst."],
       ["Emma Watson", "Hermine Granger", "Sie studierte nebenbei."]]'::jsonb,
     '[["Bud Spencer", "Bekannt für Prügelkomödien, er steht nicht auf dem Brett."],
       ["Louis de Funès", "Der französische Komiker fehlt in dieser Liste."]]'::jsonb),

    ('film-fernsehen', 'leicht-orte-film', 'Orte im Film',
     'Wo spielt das?',
     'easy', 'Film', 'https://de.wikipedia.org/wiki/Film',
     '[["Hogwarts", "Zauberschule", "Erreichbar von Gleis neundreiviertel."],
       ["Entenhausen", "Comicstadt der Enten", "Dort wohnt Donald."],
       ["Bullerbü", "Schwedisches Dorf", "Drei Höfe an einer Straße."],
       ["Springfield", "Heimat der Simpsons", "Der Bundesstaat bleibt offen."],
       ["Mittelerde", "Welt der Hobbits", "Vom Auenland bis Mordor."],
       ["Titanic", "Schiff auf Jungfernfahrt", "Es sinkt nach dem Eisberg."],
       ["Jurassic Park", "Insel mit Dinosauriern", "Vor der Küste Costa Ricas."],
       ["Gotham City", "Stadt von Batman", "Immer dunkel und regnerisch."],
       ["Hundertmorgenwald", "Zuhause von Winnie Puuh", "Mit Ferkel und I-Aah."],
       ["Lummerland", "Insel mit zwei Bergen", "Dort wohnt Jim Knopf."]]'::jsonb,
     '[["Narnia", "Die Welt hinter dem Schrank steht nicht auf dem Brett."],
       ["Atlantis", "Die versunkene Stadt fehlt in dieser Liste."]]'::jsonb),

    ('film-fernsehen', 'leicht-filmtechnik-einfach', 'Wie Filme gemacht werden',
     'Wie nennt man das?',
     'easy', 'Film', 'https://de.wikipedia.org/wiki/Film',
     '[["Sehr langsam gezeigte Bewegung", "Zeitlupe", "Mehr Bilder pro Sekunde aufgenommen."],
       ["Stunden in Sekunden gezeigt", "Zeitraffer", "Zum Beispiel eine Blüte, die aufgeht."],
       ["Puppen Bild für Bild bewegt", "Stop-Motion", "Sehr langsam und sehr aufwendig."],
       ["Gezeichnete Bilder in Folge", "Zeichentrick", "24 Bilder für eine Sekunde."],
       ["Bilder aus dem Computer", "Computeranimation", "Heute in fast jedem Film."],
       ["Kamera fährt mit", "Kamerafahrt", "Auf Schienen oder mit dem Kran."],
       ["Rückblick in die Vergangenheit", "Rückblende", "Oft anders eingefärbt."],
       ["Ende mit offenem Ausgang", "Cliffhanger", "Man wartet auf die nächste Folge."],
       ["Szene ganz ohne Schnitt", "Plansequenz", "Alles muss auf Anhieb sitzen."],
       ["Schauspieler in dicker Maske", "Maskenbild", "Stunden im Stuhl vor dem Dreh."]]'::jsonb,
     '[["Zwei Bilder nebeneinander", "Der geteilte Bildschirm steht nicht auf dem Brett."],
       ["Das Bild wird langsam dunkel", "Die Abblende kommt hier nicht vor."]]'::jsonb),

    ('film-fernsehen', 'leicht-preise-film', 'Preise & Erfolg',
     'Was ist das?',
     'easy', 'Filmpreis', 'https://de.wikipedia.org/wiki/Filmpreis',
     '[["Goldene Figur aus Hollywood", "Oscar", "Der bekannteste Filmpreis der Welt."],
       ["Preis der Berlinale", "Goldener Bär", "Der Bär ist Berlins Wappentier."],
       ["Preis von Cannes", "Goldene Palme", "Die Palme steht im Stadtwappen."],
       ["Deutscher Filmpreis", "Lola", "So heißt die Trophäe."],
       ["Film mit sehr hohen Einnahmen", "Kassenschlager", "Millionen sehen ihn im Kino."],
       ["Film, der kaum jemand sah", "Flop", "Er spielt die Kosten nicht ein."],
       ["Bewertung durch Fachleute", "Filmkritik", "Sie erscheint zum Kinostart."],
       ["Feierliche Verleihung", "Gala", "Mit rotem Teppich davor."],
       ["Nominierung", "Vorschlag für den Preis", "Gewonnen hat man damit noch nicht."],
       ["Fortsetzung eines Erfolgs", "Zweiter Teil", "Selten so gut wie der erste."]]'::jsonb,
     '[["Der Publikumspreis", "Eine Auszeichnung, die hier nicht beschrieben wird."],
       ["Die Goldene Himbeere", "Der Preis für den schlechtesten Film fehlt auf dem Brett."]]'::jsonb),

    ('film-fernsehen', 'leicht-comicverfilmung', 'Von Papier auf die Leinwand',
     'Woher stammt die Figur ursprünglich?',
     'easy', 'Comic', 'https://de.wikipedia.org/wiki/Comic',
     '[["Asterix", "Französischer Comic", "Von Goscinny und Uderzo."],
       ["Tim und Struppi", "Belgischer Comic", "Von Hergé gezeichnet."],
       ["Spider-Man", "Marvel-Comic", "Erstauftritt 1962."],
       ["Batman", "DC-Comic", "Erstauftritt 1939."],
       ["Die Schlümpfe", "Belgische Comicreihe", "Zuerst Nebenfiguren."],
       ["Lucky Luke", "Franko-belgischer Comic", "Der Mann, der schneller zieht."],
       ["Die Simpsons", "Kurze Zeichentrickfilme", "Zuerst als Einspieler im Fernsehen."],
       ["Werner", "Deutscher Comic", "Von Rötger Feldmann."],
       ["Mangas wie Naruto", "Japanischer Comic", "Von rechts nach links gelesen."],
       ["Der kleine Maulwurf", "Tschechischer Zeichentrick", "Fast ohne Worte."]]'::jsonb,
     '[["Britischer Comic", "Keine Figur auf diesem Brett stammt von dort."],
       ["Amerikanischer Zeitungsstrip", "Garfield käme daher, und der steht hier nicht."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

-- The answers that belong to no category. Numbered after the pairs so the two
-- sets never collide on `position`, though nothing reads it for a fake: the
-- pool is shuffled before a player sees it, and the review lists fakes on their
-- own rather than in board order.
fakes as (
    select q.id                                         as quiz_id,
           k.value ->> 0                                as label,
           k.value ->> 1                                as explanation,
           (jsonb_array_length(sp.pairs) + k.ord)::int  as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.fakes) with ordinality k(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
),

paired as (
    insert into items (quiz_id, category_id, label, position, explanation)
    select f.quiz_id, c.id, f.answer, f.position, f.explanation
      from flat f
      join new_categories c
        on c.quiz_id = f.quiz_id
       and c.label = f.label
    returning id
)

-- Same table, `category_id` left null. Both inserts run in the one statement,
-- so `items_quiz_id_label_key` still sees the pairs above: a fake written to
-- repeat an answer already on its own board fails the file rather than becoming
-- a second row nobody can tell apart.
insert into items (quiz_id, category_id, label, position, explanation)
select k.quiz_id, null, k.label, k.position, k.explanation
  from fakes k;
