-- Film & Fernsehen, file 1 of 2. Twenty questions, medium and hard.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs, fakes) as (
    values

    ('film-fernsehen', 'filmzitate', 'Berühmte Filmsätze',
     'Aus welchem Film stammt der Satz?',
     'hard', 'Filmzitat', 'https://de.wikipedia.org/wiki/Filmzitat',
     '[["Möge die Macht mit dir sein", "Star Wars", "Abschiedsformel der Jedi-Ritter."],
       ["Ein Angebot, das er nicht ablehnen kann", "Der Pate", "Höflich formulierte Drohung."],
       ["Bond. James Bond", "James Bond", "Die Vorstellung, die zur Marke wurde."],
       ["Sie werden ein größeres Boot brauchen", "Der weiße Hai", "Improvisiert, nachdem der Hai größer wirkte als geplant."],
       ["Nach Hause telefonieren", "E.T.", "Ein Außerirdischer mit Heimweh."],
       ["Ich komme wieder", "Terminator", "Kurz darauf fährt ein Auto durch die Wache."],
       ["Das Leben ist wie eine Schachtel Pralinen", "Forrest Gump", "Weisheit von einer Parkbank."],
       ["Ich sehe tote Menschen", "The Sixth Sense", "Der Satz, der den Film erklärt."],
       ["Wir sind nicht mehr in Kansas", "Der Zauberer von Oz", "Der Moment, in dem der Film farbig wird."],
       ["Sag Hallo zu meinem kleinen Freund", "Scarface", "Der Schlussakt eines Aufstiegs."],
       ["Freiheit", "Braveheart", "Der letzte Ruf des schottischen Rebellen."],
       ["Hasta la vista, Baby", "Terminator 2", "Spanisch, gelernt von einem Kind."]]'::jsonb,
     '[["Apocalypse Now", "Der Satz über den Napalmgeruch stammt daher, der Film fehlt hier."],
       ["Casablanca", "Ich sehe dir in die Augen, Kleines -- auf diesem Brett steht der Film nicht."]]'::jsonb),

    ('film-fernsehen', 'drehorte', 'Filme & ihre Drehorte',
     'Wo wurde der Film überwiegend gedreht?',
     'hard', 'Drehort', 'https://de.wikipedia.org/wiki/Drehort',
     '[["Der Herr der Ringe", "Neuseeland", "Das Land warb danach jahrelang mit Mittelerde."],
       ["Lawrence von Arabien", "Jordanien", "Das Wadi Rum spielte die arabische Wüste."],
       ["Der Pate", "Sizilien", "Die Rückzugsszenen entstanden in Savoca und Forza d''Agrò."],
       ["Mad Max", "Australien", "Leere Highways in Victoria und später in Namibia."],
       ["Trainspotting", "Edinburgh", "Die Eröffnungsjagd führt die Princes Street entlang."],
       ["Lost in Translation", "Tokio", "Gedreht teils ohne Drehgenehmigung."],
       ["Slumdog Millionär", "Mumbai", "Große Teile in Dharavi entstanden."],
       ["Die fabelhafte Welt der Amélie", "Montmartre", "Das Café des Deux Moulins gibt es wirklich."],
       ["Der englische Patient", "Tunesien", "Die Wüstenszenen entstanden nahe Tozeur."],
       ["Gladiator", "Malta", "Rom wurde im Fort Ricasoli nachgebaut."],
       ["Titanic", "Baja California", "Ein eigenes Studio mit Wassertank wurde gebaut."],
       ["Harry Potter und der Stein der Weisen", "Alnwick Castle", "Die Burg diente als Hogwarts von außen."]]'::jsonb,
     '[["Island", "Interstellar entstand dort, und der Film fehlt auf dem Brett."],
       ["Prag", "Amadeus wurde dort gedreht, er steht nicht in dieser Liste."]]'::jsonb),

    ('film-fernsehen', 'serien-laender', 'Serienhits & ihre Länder',
     'Aus welchem Land stammt die Serie?',
     'medium', 'Fernsehserie',
     'https://de.wikipedia.org/wiki/Fernsehserie',
     '[["Squid Game", "Südkorea", "Kinderspiele mit tödlichem Ausgang."],
       ["Dark", "Deutschland", "Zeitreisen in einer Kleinstadt namens Winden."],
       ["Haus des Geldes", "Spanien", "Überfall auf die Banknotendruckerei."],
       ["The Crown", "Vereinigtes Königreich", "Jede Staffel altert die Besetzung mit."],
       ["Lupin", "Frankreich", "Ein Meisterdieb nach literarischem Vorbild."],
       ["Borgen", "Dänemark", "Politikserie um eine Ministerpräsidentin."],
       ["Gomorrha", "Italien", "Nach dem Buch über die Camorra."],
       ["Fauda", "Israel", "Der Titel bedeutet Chaos auf Arabisch."],
       ["Narcos", "Kolumbien", "Zweisprachig gedreht, in Medellín angesiedelt."],
       ["Die Brücke", "Schweden", "Eine Leiche genau auf der Grenze zu Dänemark."],
       ["Trapped", "Island", "Ein Schneesturm sperrt den Ort ab."],
       ["Sacred Games", "Indien", "Erste indische Netflix-Eigenproduktion."]]'::jsonb,
     '[["Norwegen", "Skam käme von dort, die Serie fehlt hier."],
       ["Japan", "Keine Serie auf diesem Brett stammt von dort."]]'::jsonb),

    ('film-fernsehen', 'regie-handschrift', 'Regisseure & ihre Handschrift',
     'Woran erkennt man die Regie?',
     'hard', 'Filmregisseur',
     'https://de.wikipedia.org/wiki/Filmregisseur',
     '[["Alfred Hitchcock", "Kurzer eigener Auftritt", "In fast jedem seiner Filme läuft er durchs Bild."],
       ["Quentin Tarantino", "Erzählung in Kapiteln", "Die Reihenfolge der Szenen wird bewusst gebrochen."],
       ["Stanley Kubrick", "Streng symmetrische Bilder", "Fluchtpunkt genau in der Mitte."],
       ["Wes Anderson", "Puppenhaus-Kulissen", "Pastellfarben und frontale Einstellungen."],
       ["Christopher Nolan", "Verschachtelte Zeitebenen", "Erzählstränge laufen verschieden schnell."],
       ["Terrence Malick", "Naturbilder und Flüsterstimme", "Handlung tritt hinter Stimmung zurück."],
       ["David Lynch", "Traumlogik statt Erklärung", "Szenen folgen einer Assoziation, nicht einer Ursache."],
       ["Pedro Almodóvar", "Grelle Farben und Melodram", "Rot ist bei ihm nie zufällig."],
       ["Hayao Miyazaki", "Fliegende Maschinen", "Und Heldinnen, die keine Rettung brauchen."],
       ["David Fincher", "Dunkle, kühle Bilder", "Szenen werden bis zur Erschöpfung wiederholt."],
       ["Werner Herzog", "Dreharbeiten als Grenzerfahrung", "Ein Schiff wurde tatsächlich über den Berg gezogen."],
       ["Greta Gerwig", "Erwachsenwerden aus weiblicher Sicht", "Dialoge, die einander überlappen."]]'::jsonb,
     '[["Handkamera ganz ohne Stativ", "Das wäre Lars von Trier, der hier nicht steht."],
       ["Filme ganz ohne Musik", "Auf keine Regie in dieser Liste trifft das zu."]]'::jsonb),

    ('film-fernsehen', 'festivals-trophaeen', 'Festivals & ihre Trophäen',
     'Welchen Preis vergibt das Festival?',
     'medium', 'Filmfestival',
     'https://de.wikipedia.org/wiki/Filmfestival',
     '[["Cannes", "Goldene Palme", "Die Palme steht im Wappen der Stadt."],
       ["Berlinale", "Goldener Bär", "Der Bär ist das Wappentier Berlins."],
       ["Venedig", "Goldener Löwe", "Ältestes Filmfestival der Welt."],
       ["Locarno", "Goldener Leopard", "Vorführungen auf der Piazza Grande."],
       ["San Sebastián", "Goldene Muschel", "Wichtigstes Festival Spaniens."],
       ["Karlovy Vary", "Kristallglobus", "Traditionsfestival in Tschechien."],
       ["Sundance", "Grand Jury Prize", "Sprungbrett des unabhängigen US-Kinos."],
       ["Annecy", "Cristal", "Das größte Festival für Animationsfilm."],
       ["Toronto", "Publikumspreis", "Gilt als Vorzeichen für die Oscar-Saison."],
       ["Shanghai", "Goldener Pokal", "Größtes Festival Ostasiens."]]'::jsonb,
     '[["Goldene Himbeere", "Ein Negativpreis, der zu keinem Festival auf dem Brett gehört."],
       ["Goldener Delfin", "Diesen Preis vergibt keines der Festivals hier."]]'::jsonb),

    ('film-fernsehen', 'animationsstudios', 'Animationsstudios & Filme',
     'Welches Studio steckt dahinter?',
     'medium', 'Animation', 'https://de.wikipedia.org/wiki/Animation',
     '[["Toy Story", "Pixar", "Erster vollständig am Computer erzeugter Kinofilm."],
       ["Chihiros Reise ins Zauberland", "Studio Ghibli", "Gewann als erster Anime einen Oscar."],
       ["Shrek", "DreamWorks", "Märchenparodie mit einem Oger als Held."],
       ["Der König der Löwen", "Walt Disney Animation", "Handgezeichnet, mit einer Gnu-Herde aus dem Rechner."],
       ["Wallace & Gromit", "Aardman", "Knetfiguren, Bild für Bild bewegt."],
       ["Ich – Einfach unverbesserlich", "Illumination", "Die Minions wurden zum Selbstläufer."],
       ["Coraline", "Laika", "Puppen mit tausenden gedruckten Gesichtern."],
       ["Wolfwalkers", "Cartoon Saloon", "Irische Sagenwelt in flächiger Grafik."],
       ["Spider-Man: A New Universe", "Sony Pictures Animation", "Comicraster als bewusster Bildstil."],
       ["Ice Age", "Blue Sky Studios", "Ein Eichhörnchen jagt eine Eichel durch alle Teile."],
       ["Dragon Ball", "Toei Animation", "Prägte Generationen von Fernsehanime."]]'::jsonb,
     '[["Warner Bros. Animation", "Auch ein großes Studio, nur steht kein Film davon hier."],
       ["Nickelodeon Animation", "Kein Werk auf diesem Brett stammt daher."]]'::jsonb),

    ('film-fernsehen', 'filmtechnik', 'Handwerk des Films',
     'Was bezeichnet der Begriff?',
     'hard', 'Film', 'https://de.wikipedia.org/wiki/Film',
     '[["Plansequenz", "Szene ohne einen Schnitt", "Erfordert genaue Choreografie von Kamera und Spiel."],
       ["Schuss-Gegenschuss", "Wechsel zwischen zwei Blickwinkeln", "Standard für Dialoge."],
       ["Establishing Shot", "Einführende Totale", "Zeigt, wo man sich befindet."],
       ["Schwenk", "Drehung der Kamera", "Der Standort bleibt dabei gleich."],
       ["Zoom", "Änderung der Brennweite", "Wirkt anders als eine echte Fahrt."],
       ["Zeitlupe", "Gedehnte Bewegung", "Bewegung wirkt gedehnt."],
       ["Zeitraffer", "Weniger Bilder aufgenommen", "Stunden schrumpfen auf Sekunden."],
       ["Rückblende", "Sprung in die Vergangenheit", "Oft durch Bildstil markiert."],
       ["Voice-over", "Stimme aus dem Off", "Kommentiert, ohne im Bild zu sein."],
       ["Greenscreen", "Hintergrund wird ersetzt", "Grün, weil es selten in Hauttönen vorkommt."],
       ["Match Cut", "Schnitt auf ähnliche Form", "Verbindet zwei Orte über ein Bildmotiv."],
       ["Kamerafahrt", "Kamera bewegt sich mit", "Auf Schienen oder mit dem Kran."]]'::jsonb,
     '[["Das Bild wird zum Standbild angehalten", "Der Freeze Frame steht nicht auf dem Brett."],
       ["Zwei Bilder übereinander geblendet", "Die Doppelbelichtung fehlt in dieser Liste."]]'::jsonb),

    ('film-fernsehen', 'durchbruchsrollen', 'Schauspieler & Durchbruchsrollen',
     'Mit welchem Film gelang der Durchbruch?',
     'hard', 'Schauspieler', 'https://de.wikipedia.org/wiki/Schauspieler',
     '[["Leonardo DiCaprio", "Titanic", "Der Film machte ihn weltweit zum Star."],
       ["Keanu Reeves", "Matrix", "Monatelanges Kampftraining vor dem Dreh."],
       ["Uma Thurman", "Pulp Fiction", "Der Twist-Tanz wurde zur Ikone."],
       ["Daniel Radcliffe", "Harry Potter", "Mit elf Jahren besetzt."],
       ["Jennifer Lawrence", "Winter''s Bone", "Kleines Independent-Drama, große Wirkung."],
       ["Christoph Waltz", "Inglourious Basterds", "Vier Sprachen in einer Rolle."],
       ["Lupita Nyong''o", "12 Years a Slave", "Oscar für die erste große Kinorolle."],
       ["Timothée Chalamet", "Lady Bird", "Nebenrolle, die ihn schlagartig bekannt machte."],
       ["Florence Pugh", "Midsommar", "Horror bei strahlendem Tageslicht."],
       ["Anya Taylor-Joy", "Das Damengambit", "Schach wurde plötzlich Fernsehunterhaltung."],
       ["Song Kang-ho", "The Host", "Lange vor dem internationalen Erfolg ein Star in Korea."],
       ["Jodie Comer", "Killing Eve", "Eine Auftragsmörderin mit ständig neuen Akzenten."]]'::jsonb,
     '[["Good Will Hunting", "Damit kam Matt Damon heraus, und der steht hier nicht."],
       ["Der Pianist", "Adrien Brody wurde damit bekannt, er fehlt auf dem Brett."]]'::jsonb),

    ('film-fernsehen', 'filmfiguren-darsteller', 'Filmfiguren & Darsteller',
     'Wer spielte die Figur?',
     'medium', 'Schauspieler',
     'https://de.wikipedia.org/wiki/Schauspieler',
     '[["Indiana Jones", "Harrison Ford", "Hut und Peitsche als Markenzeichen."],
       ["Hannibal Lecter", "Anthony Hopkins", "Nur sechzehn Minuten Leinwandzeit, ein Oscar."],
       ["Ellen Ripley", "Sigourney Weaver", "Die Rolle war ursprünglich männlich geschrieben."],
       ["Vito Corleone", "Marlon Brando", "Watte in den Wangen für die Stimme."],
       ["Forrest Gump", "Tom Hanks", "Er läuft quer durch die US-Geschichte."],
       ["Tony Stark", "Robert Downey Jr.", "Viele Dialoge entstanden beim Drehen."],
       ["Jack Sparrow", "Johnny Depp", "Vorbild war ein Rockgitarrist."],
       ["Wonder Woman", "Gal Gadot", "Ehemalige Soldatin der israelischen Armee."],
       ["T-800", "Arnold Schwarzenegger", "Wenige Sätze, alle davon berühmt."],
       ["Miranda Priestly", "Meryl Streep", "Die Bosheit klingt hier nur geflüstert."],
       ["Joker", "Joaquin Phoenix", "Für die Rolle stark abgemagert."],
       ["Katniss Everdeen", "Jennifer Lawrence", "Bogenschießen extra gelernt."]]'::jsonb,
     '[["Kate Winslet", "Sie spielte Rose, und die Figur steht nicht auf dem Brett."],
       ["Ian McKellen", "Als Gandalf, der hier fehlt."]]'::jsonb),

    ('film-fernsehen', 'deutscher-film', 'Deutsche Filme & Regie',
     'Wer führte Regie?',
     'hard', 'Deutscher Film',
     'https://de.wikipedia.org/wiki/Deutscher_Film',
     '[["Das Cabinet des Dr. Caligari", "Robert Wiene", "Schiefe Kulissen als Bild eines kranken Blicks."],
       ["M – Eine Stadt sucht einen Mörder", "Fritz Lang", "Ein gepfiffenes Motiv verrät den Täter."],
       ["Aguirre, der Zorn Gottes", "Werner Herzog", "Gedreht im peruanischen Regenwald."],
       ["Die Blechtrommel", "Volker Schlöndorff", "Erster deutscher Auslands-Oscar."],
       ["Das Boot", "Wolfgang Petersen", "Die Kamera fuhr durch das enge U-Boot."],
       ["Lola rennt", "Tom Tykwer", "Dieselben zwanzig Minuten, dreimal anders."],
       ["Good Bye, Lenin!", "Wolfgang Becker", "Die DDR wird für eine Kranke am Leben gehalten."],
       ["Das Leben der Anderen", "Florian Henckel von Donnersmarck", "Ein Stasi-Offizier hört sich selbst um."],
       ["Der Untergang", "Oliver Hirschbiegel", "Die letzten Tage im Führerbunker."],
       ["Nirgendwo in Afrika", "Caroline Link", "Eine Familie flieht nach Kenia."],
       ["Toni Erdmann", "Maren Ade", "Ein Vater als Störfaktor mit falschem Gebiss."],
       ["Im Westen nichts Neues", "Edward Berger", "Vier Oscars für die Neuverfilmung."]]'::jsonb,
     '[["Rainer Werner Fassbinder", "Die Ehe der Maria Braun stammt von ihm, der Film fehlt hier."],
       ["Doris Dörrie", "Männer wäre ihr Film, und der steht nicht auf dem Brett."]]'::jsonb),

    ('film-fernsehen', 'sitcom-schauplaetze', 'Sitcoms & Schauplätze',
     'Wo spielt die Serie?',
     'medium', 'Sitcom', 'https://de.wikipedia.org/wiki/Sitcom',
     '[["Friends", "New York", "Eine unbezahlbar große Wohnung in Manhattan."],
       ["Cheers", "Boston", "Eine Bar, in der jeder deinen Namen kennt."],
       ["Frasier", "Seattle", "Ein Radiopsychologe mit Bruder und Vater."],
       ["The Office", "Scranton", "Papiergroßhandel in Pennsylvania."],
       ["Parks and Recreation", "Pawnee", "Erfundene Kleinstadt in Indiana."],
       ["Brooklyn Nine-Nine", "Brooklyn", "Polizeirevier mit sehr wenig Ernst."],
       ["It''s Always Sunny in Philadelphia", "Philadelphia", "Eine Kneipe und fünf sehr schlechte Menschen."],
       ["Modern Family", "Los Angeles", "Drei Familienzweige, eine Kamera als Beobachter."],
       ["Stromberg", "Finsdorf", "Ein Büroleiter, der sich für witzig hält."],
       ["Türkisch für Anfänger", "Berlin", "Patchworkfamilie zwischen zwei Kulturen."],
       ["Fawlty Towers", "Torquay", "Ein Hotelier, der Gäste als Störung empfindet."],
       ["Ted Lasso", "London", "Ein amerikanischer Trainer im englischen Fußball."]]'::jsonb,
     '[["Chicago", "Keine Serie auf diesem Brett spielt dort."],
       ["San Francisco", "Full House spielte dort, die Serie fehlt hier."]]'::jsonb),

    ('film-fernsehen', 'fiktive-welten', 'Fiktive Welten & ihre Filme',
     'Zu welchem Werk gehört der Ort?',
     'hard', 'Science-Fiction-Film',
     'https://de.wikipedia.org/wiki/Science-Fiction-Film',
     '[["Tatooine", "Star Wars", "Wüstenplanet mit zwei Sonnen."],
       ["Pandora", "Avatar", "Schwebende Berge und leuchtende Wälder."],
       ["Arrakis", "Dune", "Wüstenplanet, auf dem das Gewürz wächst."],
       ["LV-426", "Alien", "Ein Notsignal, dem man besser nicht folgt."],
       ["Panem", "Die Tribute von Panem", "Zwölf Distrikte und ein Kapitol."],
       ["Gotham City", "Batman", "Dauerhaft nächtliche Großstadt."],
       ["Mittelerde", "Der Herr der Ringe", "Vom Auenland bis Mordor."],
       ["Westeros", "Game of Thrones", "Sieben Königslande und eine Mauer aus Eis."],
       ["Hogwarts", "Harry Potter", "Erreichbar von Gleis neundreiviertel."],
       ["Wakanda", "Black Panther", "Hochtechnologie hinter einem Tarnschild."],
       ["Zion", "Matrix", "Die letzte menschliche Stadt tief im Erdinneren."],
       ["Rapture", "BioShock", "Eine Stadt am Meeresgrund, gescheiterte Utopie."]]'::jsonb,
     '[["Narnia", "Die Chroniken von Narnia stehen nicht auf dem Brett."],
       ["Oz", "Der Zauberer von Oz fehlt in dieser Liste."]]'::jsonb),

    ('film-fernsehen', 'filmberufe', 'Berufe am Filmset',
     'Wofür ist die Person zuständig?',
     'medium', 'Filmstab', 'https://de.wikipedia.org/wiki/Filmstab',
     '[["Regie", "Inszenierung des Films", "Trifft die Entscheidungen vor der Kamera."],
       ["Produktion", "Geld und Organisation", "Sorgt dafür, dass überhaupt gedreht werden kann."],
       ["Drehbuch", "Vorlage mit Dialogen", "Eine Seite entspricht grob einer Minute Film."],
       ["Kamera", "Bildgestaltung und Licht", "Entscheidet über Ausschnitt und Bewegung."],
       ["Schnitt", "Auswahl und Reihenfolge", "Bestimmt Rhythmus und Spannung."],
       ["Szenenbild", "Bauten und Ausstattung", "Von der Tapete bis zur ganzen Straße."],
       ["Kostümbild", "Kleidung der Figuren", "Erzählt Herkunft und Wandel mit."],
       ["Maske", "Frisur und Make-up", "Auch Alterung und Wunden."],
       ["Ton", "Aufnahme am Set", "Die Angel bleibt knapp außerhalb des Bildes."],
       ["Casting", "Besetzung der Rollen", "Sucht auch die kleinen Rollen aus."],
       ["Stuntkoordination", "Gefährliche Szenen", "Plant Sicherheit und Ablauf."],
       ["Continuity", "Anschlüsse zwischen Einstellungen", "Achtet darauf, dass das Glas gleich voll bleibt."]]'::jsonb,
     '[["Musik für den Film schreiben", "Die Filmmusik steht nicht auf diesem Brett."],
       ["Kinostart und Werbung planen", "Der Verleih kommt hier nicht vor."]]'::jsonb),

    ('film-fernsehen', 'fernsehgeschichte', 'Meilensteine des Fernsehens',
     'In welchem Jahr geschah das?',
     'hard', 'Geschichte des Fernsehens',
     'https://de.wikipedia.org/wiki/Geschichte_des_Fernsehens',
     '[["Erste Fernsehübertragung Olympischer Spiele", "1936", "In wenige Berliner Fernsehstuben übertragen."],
       ["Erste Tagesschau", "1952", "Zunächst dreimal pro Woche."],
       ["Erstes Fernsehduell im Wahlkampf", "1960", "Kennedy wirkte im Bild überzeugender als Nixon."],
       ["Farbfernsehen in Deutschland", "1967", "Ein Knopfdruck auf der Funkausstellung."],
       ["Mondlandung live im Fernsehen", "1969", "Weltweit sahen Hunderte Millionen zu."],
       ["Start von MTV", "1981", "Das erste Video hieß Video Killed the Radio Star."],
       ["Erste Folge der Simpsons", "1989", "Aus kurzen Einspielern wurde eine eigene Serie."],
       ["Erste Staffel von Big Brother", "1999", "In den Niederlanden erfunden."],
       ["Gründung von YouTube", "2005", "Das erste Video zeigte einen Zoobesuch."],
       ["Netflix beginnt mit Streaming", "2007", "Zuvor verschickte die Firma DVDs per Post."]]'::jsonb,
     '[["1994", "Kein Meilenstein auf diesem Brett fällt in dieses Jahr."],
       ["2013", "House of Cards startete damals, das steht hier nicht."]]'::jsonb),

    ('film-fernsehen', 'stummfilm-stars', 'Stummfilmstars',
     'Wofür steht der Name?',
     'hard', 'Stummfilm', 'https://de.wikipedia.org/wiki/Stummfilm',
     '[["Charlie Chaplin", "Der Tramp", "Melone, Stock und zu große Schuhe."],
       ["Buster Keaton", "Das steinerne Gesicht", "Er lachte nie, egal was einstürzte."],
       ["Harold Lloyd", "Hängen am Uhrzeiger", "Die Szene entstand ohne Tricktechnik in großer Höhe."],
       ["Rudolph Valentino", "Der Liebhaber-Typ", "Sein Tod löste Massenhysterie aus."],
       ["Mary Pickford", "Amerikas Liebling", "Mitgründerin eines eigenen Studios."],
       ["Lillian Gish", "Griffiths Hauptdarstellerin", "Über 70 Jahre lang vor der Kamera."],
       ["Louise Brooks", "Der Bubikopf", "Ihr Haarschnitt prägte ein Jahrzehnt."],
       ["Douglas Fairbanks", "Mantel-und-Degen-Held", "Machte seine Sprünge meist selbst."],
       ["Asta Nielsen", "Der erste europäische Filmstar", "Aus Dänemark, in Deutschland gefeiert."],
       ["Fatty Arbuckle", "Der frühe Slapstick-Komiker", "Ein Skandal beendete seine Karriere."]]'::jsonb,
     '[["Der Vampir aus Nosferatu", "Das wäre Max Schreck, und der steht nicht auf dem Brett."],
       ["Die Erfinderin des Farbfilms", "Auf niemanden in dieser Liste trifft das zu."]]'::jsonb),

    ('film-fernsehen', 'untergenres', 'Untergenres des Films',
     'Was macht das Genre aus?',
     'hard', 'Filmgenre', 'https://de.wikipedia.org/wiki/Filmgenre',
     '[["Spaghettiwestern", "Western aus Italien", "Gedreht in Spanien, oft mit deutschem Geld."],
       ["Screwball-Komödie", "Schlagfertiges Wortgefecht", "Zwei Ebenbürtige reden sich in die Liebe."],
       ["Slasher", "Maskierter Serienmörder", "Meist bleibt eine Person übrig."],
       ["Found Footage", "Angeblich gefundenes Material", "Wackelkamera als Echtheitsbeweis."],
       ["Mockumentary", "Erfundene Dokumentation", "Ernste Form, komischer Inhalt."],
       ["Heist-Film", "Planung eines großen Coups", "Das Team wird zuerst zusammengestellt."],
       ["Coming-of-Age", "Erwachsenwerden", "Ein Sommer, der alles verändert."],
       ["Buddy Movie", "Ungleiches Paar auf Mission", "Die Reibung ist der Motor."],
       ["Road Movie", "Reise als Handlung", "Das Ziel zählt weniger als der Weg."],
       ["Neo-Noir", "Film noir in Farbe", "Regen, Neon und moralische Grauzonen."],
       ["Kammerspiel", "Wenige Figuren, ein Raum", "Der Druck entsteht durch Enge."],
       ["Katastrophenfilm", "Ereignis bedroht alle", "Ein Ensemble kämpft gegen die Naturgewalt."]]'::jsonb,
     '[["Gesungene Dialoge statt gesprochener", "Das Musical fehlt auf diesem Brett."],
       ["Verhandlung im Gerichtssaal", "Ein Genre, das hier nicht vorkommt."]]'::jsonb),

    ('film-fernsehen', 'anime-regisseure', 'Anime & ihre Macher',
     'Wer steht hinter dem Werk?',
     'hard', 'Anime', 'https://de.wikipedia.org/wiki/Anime',
     '[["Chihiros Reise ins Zauberland", "Hayao Miyazaki", "Ein Mädchen arbeitet in einem Badehaus für Götter."],
       ["Akira", "Katsuhiro Otomo", "Neo-Tokio, gezeichnet mit enormem Aufwand."],
       ["Your Name", "Makoto Shinkai", "Zwei Jugendliche tauschen die Körper."],
       ["Perfect Blue", "Satoshi Kon", "Realität und Wahn verschwimmen."],
       ["Ghost in the Shell", "Mamoru Oshii", "Was bleibt vom Menschen im Cyberkörper?"],
       ["Neon Genesis Evangelion", "Hideaki Anno", "Riesenroboter und sehr viel Psychologie."],
       ["Die letzten Glühwürmchen", "Isao Takahata", "Zwei Kinder im Krieg, ohne jeden Trost."],
       ["Cowboy Bebop", "Shinichirō Watanabe", "Kopfgeldjäger zu Jazzmusik."],
       ["Wolfskinder", "Mamoru Hosoda", "Eine Mutter zieht Kinder groß, die Wölfe sein können."],
       ["Devilman Crybaby", "Masaaki Yuasa", "Ausgesprochen eigenwilliger Zeichenstil."]]'::jsonb,
     '[["Osamu Tezuka", "Astro Boy stammt von ihm, das Werk fehlt hier."],
       ["Gorō Miyazaki", "Er führte bei Die Chroniken von Erdsee Regie, die nicht auf dem Brett steht."]]'::jsonb),

    ('film-fernsehen', 'kultfilme-jahre', 'Kultfilme & Erscheinungsjahre',
     'Wann kam der Film ins Kino?',
     'hard', 'Filmgeschichte',
     'https://de.wikipedia.org/wiki/Filmgeschichte',
     '[["Casablanca", "1942", "Entstand mitten im Krieg, das Ende stand lange nicht fest."],
       ["Der Pate", "1972", "Der Studioleitung war Al Pacino zu unbekannt."],
       ["Star Wars", "1977", "Kaum jemand rechnete mit einem Erfolg."],
       ["Zurück in die Zukunft", "1985", "Der Hauptdarsteller wurde nach Drehbeginn ausgetauscht."],
       ["Jurassic Park", "1993", "Der Wasserglas-Trick entstand mit einer Gitarrensaite."],
       ["Pulp Fiction", "1994", "Gewann in Cannes und drehte das Kinojahrzehnt."],
       ["Titanic", "1997", "Teuerster Film seiner Zeit, dann erfolgreichster."],
       ["Matrix", "1999", "Die Kugelzeit-Aufnahmen brauchten 120 Kameras."],
       ["Der Herr der Ringe: Die Gefährten", "2001", "Alle drei Teile wurden am Stück gedreht."],
       ["Avatar", "2009", "Machte 3D-Kino für Jahre zum Standard."],
       ["Parasite", "2019", "Erster nicht englischsprachiger Film mit dem Hauptoscar."],
       ["Barbie", "2023", "Der Filmdreh ließ weltweit rosa Farbe knapp werden."]]'::jsonb,
     '[["1968", "2001: Odyssee im Weltraum kam damals, der Film fehlt hier."],
       ["2008", "The Dark Knight startete in dem Jahr, er steht nicht auf dem Brett."]]'::jsonb),

    ('film-fernsehen', 'serienfiguren-berufe', 'Serienfiguren & ihre Berufe',
     'Was macht die Figur beruflich?',
     'medium', 'Fernsehserie',
     'https://de.wikipedia.org/wiki/Fernsehserie',
     '[["Gregory House", "Diagnostiker", "Löst medizinische Rätsel, verachtet Patienten."],
       ["Saul Goodman", "Strafverteidiger", "Wirbt mit einem Fernsehspot in Eigenregie."],
       ["Dexter Morgan", "Blutspuranalytiker", "Arbeitet für die Polizei von Miami."],
       ["Jessica Fletcher", "Krimiautorin", "In ihrer Nähe stirbt auffallend oft jemand."],
       ["Sherlock Holmes", "Beratender Detektiv", "Ein Beruf, den er selbst erfunden hat."],
       ["Lorelai Gilmore", "Hotelmanagerin", "Führt später ein eigenes Gasthaus."],
       ["Carrie Bradshaw", "Kolumnistin", "Schreibt über das Liebesleben ihrer Stadt."],
       ["Villanelle", "Auftragsmörderin", "Wählt Kleidung wie andere Waffen."],
       ["Ted Mosby", "Architekt", "Erzählt seinen Kindern eine sehr lange Geschichte."],
       ["Rick Grimes", "Sheriff", "Wacht im Krankenhaus in eine andere Welt auf."],
       ["Jack Bauer", "Antiterror-Agent", "Jede Staffel umfasst 24 Stunden."],
       ["Leslie Knope", "Beamtin im Stadtpark-Amt", "Bürokratie mit ungebremstem Idealismus."]]'::jsonb,
     '[["Chemielehrer", "Walter White wäre das, und die Figur fehlt auf dem Brett."],
       ["Werbefachmann", "Don Draper steht nicht in dieser Liste."]]'::jsonb),

    ('film-fernsehen', 'filmpreise-laender', 'Nationale Filmpreise',
     'In welchem Land wird der Preis vergeben?',
     'medium', 'Filmpreis', 'https://de.wikipedia.org/wiki/Filmpreis',
     '[["Oscar", "USA", "Vergeben von der Academy in Los Angeles."],
       ["César", "Frankreich", "Benannt nach dem Bildhauer, der die Trophäe schuf."],
       ["BAFTA", "Vereinigtes Königreich", "Findet kurz vor den Oscars statt."],
       ["Goya", "Spanien", "Nach dem Maler benannt."],
       ["David di Donatello", "Italien", "Trophäe nach Donatellos David."],
       ["Deutscher Filmpreis", "Deutschland", "Die Trophäe heißt Lola."],
       ["Guldbagge", "Schweden", "Der Name bedeutet Goldkäfer."],
       ["Genie Award", "Kanada", "Heute unter dem Namen Canadian Screen Award."],
       ["Filmfare Award", "Indien", "Wichtigster Preis des Hindi-Kinos."],
       ["Japan Academy Film Prize", "Japan", "Seit 1978 vergeben."],
       ["Ariel", "Mexiko", "Ältester Filmpreis Lateinamerikas."]]'::jsonb,
     '[["Österreich", "Der Österreichische Filmpreis fehlt auf dem Brett."],
       ["Südkorea", "Die Blue Dragon Awards stehen hier nicht."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

-- The answers that belong to no category. Numbered after the pairs so the two
-- sets never collide on `position`, though nothing reads it for a fake: the
-- pool is shuffled before a player sees it, and the review lists fakes on their
-- own rather than in board order.
fakes as (
    select q.id                                         as quiz_id,
           k.value ->> 0                                as label,
           k.value ->> 1                                as explanation,
           (jsonb_array_length(sp.pairs) + k.ord)::int  as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.fakes) with ordinality k(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
),

paired as (
    insert into items (quiz_id, category_id, label, position, explanation)
    select f.quiz_id, c.id, f.answer, f.position, f.explanation
      from flat f
      join new_categories c
        on c.quiz_id = f.quiz_id
       and c.label = f.label
    returning id
)

-- Same table, `category_id` left null. Both inserts run in the one statement,
-- so `items_quiz_id_label_key` still sees the pairs above: a fake written to
-- repeat an answer already on its own board fails the file rather than becoming
-- a second row nobody can tell apart.
insert into items (quiz_id, category_id, label, position, explanation)
select k.quiz_id, null, k.label, k.position, k.explanation
  from fakes k;
