-- Film & Fernsehen, file 2 of 2. Twenty questions, medium and hard.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs, fakes) as (
    values

    ('film-fernsehen', 'originaltitel', 'Deutsche Titel & Originaltitel',
     'Wie heißt der Film im Original?',
     'hard', 'Film', 'https://de.wikipedia.org/wiki/Film',
     '[["Die Verurteilten", "The Shawshank Redemption", "Der deutsche Titel verrät mehr als der englische."],
       ["Der weiße Hai", "Jaws", "Das Original heißt schlicht Kiefer."],
       ["Stirb langsam", "Die Hard", "Aus einem Roman über einen Hochhausbrand entwickelt."],
       ["Der Pate", "The Godfather", "Titel und Buchvorlage stammen von Mario Puzo."],
       ["Ziemlich beste Freunde", "Intouchables", "Das Original heißt die Unberührbaren."],
       ["Vom Winde verweht", "Gone with the Wind", "Der Satz stammt aus einem Gedicht."],
       ["Manche mögen''s heiß", "Some Like It Hot", "Der Titel spielt auf heißen Jazz an."],
       ["Der mit dem Wolf tanzt", "Dances with Wolves", "Der Name, den die Lakota der Hauptfigur geben."],
       ["Und täglich grüßt das Murmeltier", "Groundhog Day", "Der Feiertag heißt wörtlich Murmeltiertag."],
       ["Das Fenster zum Hof", "Rear Window", "Ein Fotograf beobachtet aus dem Rollstuhl."],
       ["Vertigo – Aus dem Reich der Toten", "Vertigo", "Der Titel bezeichnet den Höhenschwindel."],
       ["Meine Lieder, meine Träume", "The Sound of Music", "In Österreich lange fast unbekannt."]]'::jsonb,
     '[["Sunset Boulevard", "Boulevard der Dämmerung wäre der deutsche Titel, der Film fehlt hier."],
       ["North by Northwest", "Der unsichtbare Dritte steht nicht auf diesem Brett."]]'::jsonb),

    ('film-fernsehen', 'serien-schoepfer', 'Serien & ihre Schöpfer',
     'Wer hat die Serie entwickelt?',
     'hard', 'Showrunner', 'https://de.wikipedia.org/wiki/Showrunner',
     '[["Breaking Bad", "Vince Gilligan", "Zuvor Autor bei Akte X."],
       ["The Wire", "David Simon", "Früher Polizeireporter in Baltimore."],
       ["Die Sopranos", "David Chase", "Wollte eigentlich Kinofilme machen."],
       ["Mad Men", "Matthew Weiner", "Das Pilotdrehbuch lag jahrelang in der Schublade."],
       ["Game of Thrones", "Benioff und Weiss", "Zwei Autoren überzeugten den Romanautor beim Mittagessen."],
       ["Die Simpsons", "Matt Groening", "Die Figuren sind nach seiner Familie benannt."],
       ["Seinfeld", "Larry David", "Die Serie über nichts."],
       ["Fleabag", "Phoebe Waller-Bridge", "Aus einem Bühnenmonolog entstanden."],
       ["Chernobyl", "Craig Mazin", "Zuvor bekannt für Komödien."],
       ["Dark", "Baran bo Odar", "Gemeinsam mit Jantje Friese entwickelt."],
       ["Stranger Things", "Duffer-Brüder", "Der Stoff wurde von vielen Sendern abgelehnt."],
       ["The Office", "Ricky Gervais", "Das britische Original umfasst nur zwölf Folgen."]]'::jsonb,
     '[["Aaron Sorkin", "The West Wing stammt von ihm, die Serie fehlt hier."],
       ["Shonda Rhimes", "Grey''s Anatomy wäre ihre Serie, und die steht nicht auf dem Brett."]]'::jsonb),

    ('film-fernsehen', 'requisiten', 'Figuren & ihre Requisiten',
     'Was gehört untrennbar zur Figur?',
     'medium', 'Requisit', 'https://de.wikipedia.org/wiki/Requisit',
     '[["Indiana Jones", "Peitsche", "Dazu ein Hut, der nie verloren geht."],
       ["Thor", "Hammer", "Nur der Würdige kann ihn heben."],
       ["James Bond", "Walther PPK", "Von einem Waffenexperten empfohlen."],
       ["Harry Potter", "Zauberstab", "Aus Stechpalme, mit Phönixfeder."],
       ["Luke Skywalker", "Lichtschwert", "Die Klinge summt beim Schwingen."],
       ["Wonder Woman", "Lasso der Wahrheit", "Wer gefesselt ist, kann nicht lügen."],
       ["Mary Poppins", "Regenschirm", "Damit fliegt sie ins Haus."],
       ["Charlie Chaplin", "Spazierstock", "Dazu Melone und watschelnder Gang."],
       ["Freddy Krueger", "Klingenhandschuh", "Das Geräusch kündigt ihn an."],
       ["Captain America", "Runder Schild", "Aus einem fiktiven Metall aus Wakanda."],
       ["Sherlock Holmes", "Lupe", "Die Deerstalker-Mütze stammt erst von Illustratoren."],
       ["Zorro", "Degen", "Er hinterlässt ein Z als Unterschrift."]]'::jsonb,
     '[["Fedora aus Filz", "Ein Hut gehört zu mancher Figur, hier ist er keine Antwort."],
       ["Dreizack", "Die Waffe des Poseidon, und der steht nicht auf dem Brett."]]'::jsonb),

    ('film-fernsehen', 'oscar-rekorde', 'Oscar-Rekorde',
     'Wer oder was hält diesen Rekord?',
     'hard', 'Oscar', 'https://de.wikipedia.org/wiki/Oscar',
     '[["Meiste Schauspiel-Oscars", "Katharine Hepburn", "Vier Auszeichnungen, keine davon persönlich abgeholt."],
       ["Meiste Schauspiel-Nominierungen", "Meryl Streep", "Über zwanzig Nominierungen."],
       ["Erste schwarze Hauptdarstellerin", "Halle Berry", "Ausgezeichnet 2002."],
       ["Jüngste Preisträgerin", "Tatum O''Neal", "Mit zehn Jahren als beste Nebendarstellerin."],
       ["Ältester Preisträger im Schauspiel", "Anthony Hopkins", "Mit 83 Jahren ausgezeichnet."],
       ["Erste Frau mit Regie-Oscar", "Kathryn Bigelow", "2010 für ein Kriegsdrama."],
       ["Meiste Oscars insgesamt", "Walt Disney", "22 Auszeichnungen zu Lebzeiten."],
       ["Erster nicht englischsprachiger Hauptpreisträger", "Parasite", "2020 für den besten Film."],
       ["Meiste Regie-Oscars", "John Ford", "Viermal ausgezeichnet."],
       ["Erster Preis für einen Animationsfilm", "Shrek", "Die Kategorie wurde 2002 eingeführt."]]'::jsonb,
     '[["Alfred Hitchcock", "Er gewann nie einen Regie-Oscar, hält also keinen Rekord hier."],
       ["Titanic", "Der Film teilt sich den Rekord an Einzelpreisen, der steht aber nicht auf dem Brett."]]'::jsonb),

    ('film-fernsehen', 'kinderserien-laender', 'Kinderserien & Herkunftsländer',
     'Aus welchem Land stammt die Serie?',
     'medium', 'Kinderfernsehen',
     'https://de.wikipedia.org/wiki/Kinderfernsehen',
     '[["Sesamstraße", "USA", "Mit Lerninhalten im Werbespot-Format."],
       ["Die Sendung mit der Maus", "Deutschland", "Erklärstücke zwischen Zeichentrickfilmen."],
       ["Pettersson und Findus", "Schweden", "Ein alter Mann und sein sprechender Kater."],
       ["Peppa Pig", "Vereinigtes Königreich", "In Dutzende Sprachen übersetzt."],
       ["Miffy", "Niederlande", "Klare Linien, wenige Farben."],
       ["Barbapapa", "Frankreich", "Formwandler in Pastellfarben."],
       ["Pingu", "Schweiz", "Knetfiguren mit eigener Fantasiesprache."],
       ["Doraemon", "Japan", "Ein Roboterkater aus der Zukunft."],
       ["Mascha und der Bär", "Russland", "Weltweit eine der meistgesehenen Kinderserien."],
       ["Bluey", "Australien", "Eine Hundefamilie mit sehr geduldigen Eltern."],
       ["Caillou", "Kanada", "Aus einer Bilderbuchreihe aus Québec."],
       ["Pocoyó", "Spanien", "Weißer Hintergrund statt gezeichneter Kulisse."]]'::jsonb,
     '[["Dänemark", "Die Olsenbande für Kinder käme von dort, hier fehlt sie."],
       ["Belgien", "Die Schlümpfe stammen von dort, sie stehen nicht auf dem Brett."]]'::jsonb),

    ('film-fernsehen', 'studio-logos', 'Filmstudios & ihre Logos',
     'Welches Studio erkennt man daran?',
     'medium', 'Filmstudio', 'https://de.wikipedia.org/wiki/Filmstudio',
     '[["Berg im Sternenkranz", "Paramount", "Ältestes noch bestehendes Hollywood-Studio."],
       ["Brüllender Löwe", "MGM", "Mehrere Löwen spielten das Maskottchen."],
       ["Drehende Erdkugel", "Universal", "Seit 1912 in wechselnden Fassungen."],
       ["Suchscheinwerfer mit Fanfare", "20th Century Studios", "Die Fanfare stammt von Alfred Newman."],
       ["Schild mit zwei Buchstaben", "Warner Bros.", "Gegründet von vier Brüdern."],
       ["Frau mit Fackel", "Columbia Pictures", "Die Fackelträgerin steht vor Wolken."],
       ["Springende Schreibtischlampe", "Pixar", "Aus einem frühen Kurzfilm des Studios."],
       ["Junge auf der Mondsichel", "DreamWorks", "Ursprünglich als Gemälde entworfen."],
       ["Waldgeist mit Regenschirm", "Studio Ghibli", "Die Figur stammt aus einem eigenen Film."],
       ["Ineinandergreifende Zahnräder", "Lionsgate", "Aus Kanada, heute in Kalifornien."]]'::jsonb,
     '[["Schloss mit Feuerwerk", "Das ist die Walt-Disney-Vorspannmarke, sie fehlt auf dem Brett."],
       ["Freiheitsstatue im Kreis", "Kein Studio in dieser Liste führt so ein Zeichen."]]'::jsonb),

    ('film-fernsehen', 'spin-offs', 'Ableger & Ursprungsserien',
     'Aus welcher Serie ging der Ableger hervor?',
     'hard', 'Spin-off', 'https://de.wikipedia.org/wiki/Spin-off',
     '[["Better Call Saul", "Breaking Bad", "Vorgeschichte des Anwalts, sechs Staffeln lang."],
       ["Frasier", "Cheers", "Der Psychiater aus der Bar zieht nach Seattle."],
       ["Angel", "Buffy", "Der Vampir mit Seele bekommt eine eigene Stadt."],
       ["The Originals", "Vampire Diaries", "Die Urvampire ziehen nach New Orleans."],
       ["Joey", "Friends", "Der Schauspieler versucht es in Los Angeles."],
       ["Torchwood", "Doctor Who", "Der Titel ist ein Anagramm der Mutterserie."],
       ["House of the Dragon", "Game of Thrones", "Spielt fast zwei Jahrhunderte früher."],
       ["Fear the Walking Dead", "The Walking Dead", "Zeigt den Beginn der Seuche."],
       ["Young Sheldon", "The Big Bang Theory", "Kindheit einer Nebenfigur in Texas."],
       ["Laverne & Shirley", "Happy Days", "Zwei Nebenfiguren bekommen eine eigene Serie."]]'::jsonb,
     '[["Star Trek", "Deep Space Nine wäre der Ableger dazu, er steht nicht auf dem Brett."],
       ["Grey''s Anatomy", "Private Practice ging daraus hervor, hier fehlt beides."]]'::jsonb),

    ('film-fernsehen', 'gegenspieler', 'Helden & ihre Gegenspieler',
     'Wer ist der Widersacher?',
     'hard', 'Antagonist', 'https://de.wikipedia.org/wiki/Antagonist',
     '[["Batman", "Joker", "Ordnung gegen Chaos, ohne Ende."],
       ["Sherlock Holmes", "Professor Moriarty", "Der Napoleon des Verbrechens."],
       ["Harry Potter", "Lord Voldemort", "Sein Name wird lieber nicht ausgesprochen."],
       ["Luke Skywalker", "Darth Vader", "Die Verwandtschaft ist Teil des Konflikts."],
       ["James Bond", "Ernst Stavro Blofeld", "Weiße Katze auf dem Schoß."],
       ["Frodo", "Sauron", "Ein Auge, das nach dem Ring sucht."],
       ["Neo", "Agent Smith", "Ein Programm, das sich selbst vervielfältigt."],
       ["Marty McFly", "Biff Tannen", "Der Schläger in jeder Zeitebene."],
       ["Ellen Ripley", "Alien-Königin", "Mutter gegen Mutter im Frachtraum."],
       ["Road Runner", "Wile E. Coyote", "Der Verfolger scheitert an eigenen Erfindungen."],
       ["Simba", "Scar", "Der Onkel will den Thron."],
       ["John McClane", "Hans Gruber", "Ein sehr höflicher Geiselnehmer."]]'::jsonb,
     '[["Professor Snape", "Er ist keiner der Widersacher, die hier zugeordnet werden."],
       ["Nurse Ratched", "Aus Einer flog über das Kuckucksnest, das nicht auf dem Brett steht."]]'::jsonb),

    ('film-fernsehen', 'kinotechnik', 'Technik des Kinos',
     'Was steckt hinter dem Verfahren?',
     'hard', 'Kinematografie',
     'https://de.wikipedia.org/wiki/Kinematografie',
     '[["CinemaScope", "Breitwand durch Anamorphot", "Das Bild wird gestaucht aufgenommen und gedehnt projiziert."],
       ["Technicolor", "Farbe aus drei Filmstreifen", "Kräftige Farben mit riesigen Kameras."],
       ["IMAX", "Sehr großes Filmformat", "Der Film läuft quer statt längs durch die Kamera."],
       ["Stereoskopie", "Zwei leicht versetzte Bilder", "Erzeugt räumlichen Eindruck."],
       ["Dolby Surround", "Ton aus mehreren Richtungen", "Erst im Kino, dann im Wohnzimmer."],
       ["Steadicam", "Ruhiges Bild beim Gehen", "Ein Federarm gleicht Schritte aus."],
       ["Computergenerierte Bilder", "Objekte aus dem Rechner", "Erstmals umfassend in Jurassic Park."],
       ["Motion Capture", "Bewegung wird abgenommen", "Punkte am Körper werden von Kameras verfolgt."],
       ["Bullet Time", "Eingefrorene Bewegung im Raum", "Viele Kameras lösen nacheinander aus."],
       ["Digitale Projektion", "Kino ohne Filmrolle", "Der Film kommt als Datei ins Haus."]]'::jsonb,
     '[["Duft im Kinosaal", "Smell-O-Vision blieb ein Versuch und steht nicht auf dem Brett."],
       ["Bewegliche Sitze im Saal", "Das 4D-Kino kommt in dieser Liste nicht vor."]]'::jsonb),

    ('film-fernsehen', 'sender-laender', 'Fernsehsender & Länder',
     'Aus welchem Land sendet die Anstalt?',
     'medium', 'Fernsehsender',
     'https://de.wikipedia.org/wiki/Fernsehsender',
     '[["BBC", "Vereinigtes Königreich", "Finanziert über eine Rundfunkgebühr."],
       ["ARD", "Deutschland", "Ein Verbund von Landesrundfunkanstalten."],
       ["ORF", "Österreich", "Sitz am Küniglberg in Wien."],
       ["SRF", "Schweiz", "Sendet in drei Landessprachen."],
       ["RAI", "Italien", "Drei große Hauptkanäle."],
       ["RTVE", "Spanien", "Öffentlich-rechtlich, gegründet 1956."],
       ["France Télévisions", "Frankreich", "Bündelt mehrere öffentliche Kanäle."],
       ["NHK", "Japan", "Betreibt auch einen Auslandsdienst."],
       ["CBC", "Kanada", "Sendet auf Englisch und Französisch."],
       ["PBS", "USA", "Wird über Spenden mitfinanziert."],
       ["ABC", "Australien", "Nicht zu verwechseln mit dem gleichnamigen US-Sender."],
       ["TVP", "Polen", "Öffentlicher Rundfunk mit mehreren Kanälen."]]'::jsonb,
     '[["Niederlande", "Die NOS sendet von dort, sie fehlt auf diesem Brett."],
       ["Schweden", "SVT wäre die Anstalt dazu, und die steht hier nicht."]]'::jsonb),

    ('film-fernsehen', 'filmszenen', 'Legendäre Szenen',
     'Aus welchem Film stammt die Szene?',
     'hard', 'Szene (Film)',
     'https://de.wikipedia.org/wiki/Szene_%28Film%29',
     '[["Kinderwagen auf der Freitreppe", "Panzerkreuzer Potemkin", "Die Montage wurde zum Lehrbeispiel."],
       ["Tanz im Regen mit Laterne", "Singin'' in the Rain", "Der Darsteller hatte dabei Fieber."],
       ["Fahrradflug vor dem Vollmond", "E.T.", "Das Bild wurde zum Studiologo."],
       ["Wagenrennen in der Arena", "Ben Hur", "Wochenlang mit Hunderten Beteiligten gedreht."],
       ["Pferdekopf im Bett", "Der Pate", "Ein Produzent lernt Verhandlungsstil kennen."],
       ["Twist-Wettbewerb im Diner", "Pulp Fiction", "Zwei Tänzer ohne Schuhe."],
       ["Zahnbehandlung ohne Betäubung", "Der Marathon-Mann", "Die Frage lautet: Ist es sicher?"],
       ["Ohr und Rasiermesser", "Reservoir Dogs", "Die Kamera dreht sich im entscheidenden Moment weg."],
       ["Schlittenverbrennung am Ende", "Citizen Kane", "Ein Wort erklärt ein ganzes Leben."],
       ["Ausbreiten der Arme am Bug", "Titanic", "Der König der Welt, für wenige Minuten."],
       ["Duell mit drei Blicken", "Zwei glorreiche Halunken", "Immer engere Einstellungen, immer lautere Musik."],
       ["Wiederholter Weckerklang am Morgen", "Groundhog Day", "Derselbe Tag beginnt immer wieder von vorn."]]'::jsonb,
     '[["Duschvorhang und Messer", "Das ist Psycho, und der Film fehlt auf dem Brett."],
       ["Der Kopf in der Kiste am Ende", "Das ist Sieben, es steht nicht in dieser Liste."]]'::jsonb),

    ('film-fernsehen', 'serien-sender', 'Serien & ihre Sender',
     'Wo lief die Serie zuerst?',
     'medium', 'Fernsehsender',
     'https://de.wikipedia.org/wiki/Fernsehsender',
     '[["Die Sopranos", "HBO", "Die Serie, mit der das Quality-TV begann."],
       ["Breaking Bad", "AMC", "Ein Kabelsender ohne großen Namen wagte es."],
       ["Stranger Things", "Netflix", "Alle Folgen auf einmal veröffentlicht."],
       ["The Mandalorian", "Disney+", "Startete zeitgleich mit dem Dienst."],
       ["The Boys", "Amazon Prime Video", "Superhelden als Konzernprodukt."],
       ["Ted Lasso", "Apple TV+", "Aus einem Werbespot entstanden."],
       ["Doctor Who", "BBC", "Läuft mit Unterbrechungen seit 1963."],
       ["Tatort", "ARD", "Sonntagabend, seit 1970."],
       ["Twin Peaks", "ABC", "Ungewöhnlich für das Hauptabendprogramm."],
       ["Akte X", "Fox", "Machte Mystery zum Serienformat."]]'::jsonb,
     '[["Showtime", "Dexter lief dort zuerst, die Serie fehlt auf dem Brett."],
       ["ZDF", "Der Alte lief dort, und der steht hier nicht."]]'::jsonb),

    ('film-fernsehen', 'filmtiere', 'Berühmte Filmtiere',
     'Welches Tier steckt hinter dem Namen?',
     'medium', 'Film', 'https://de.wikipedia.org/wiki/Film',
     '[["Lassie", "Collie", "Gespielt meist von Rüden, obwohl die Rolle weiblich ist."],
       ["Flipper", "Delfin", "Mehrere Tiere spielten die Rolle."],
       ["Willy", "Orca", "Der Film löste eine echte Freilassungskampagne aus."],
       ["King Kong", "Riesenaffe", "Zuerst als Stop-Motion-Modell animiert."],
       ["Babe", "Schwein", "Sprechende Tiere mit früher Computertechnik."],
       ["Beethoven", "Bernhardiner", "Benannt nach dem Komponisten."],
       ["Hachiko", "Akita", "Nach einer wahren Geschichte aus Tokio."],
       ["Rex", "Schäferhund", "Ein Wiener Kriminalfall pro Folge."],
       ["Bambi", "Reh", "Im Buch ist es ein Reh, im Film ein Weißwedelhirsch."],
       ["Dumbo", "Elefant", "Große Ohren als Flügel."],
       ["Balu", "Lippenbär", "Sein Lied über Gemütlichkeit wurde berühmt."],
       ["Shere Khan", "Tiger", "Der Gegenspieler im Dschungelbuch."]]'::jsonb,
     '[["Papagei", "Kein Filmtier auf diesem Brett ist ein Vogel."],
       ["Rentier", "Sven aus Die Eiskönigin wäre das, er fehlt in dieser Liste."]]'::jsonb),

    ('film-fernsehen', 'regisseurinnen', 'Regisseurinnen & ihre Filme',
     'Welcher Film stammt von ihr?',
     'hard', 'Filmregisseur',
     'https://de.wikipedia.org/wiki/Filmregisseur',
     '[["Kathryn Bigelow", "Tödliches Kommando", "Erster Regie-Oscar für eine Frau."],
       ["Jane Campion", "Das Piano", "Goldene Palme für ein Kammerspiel in Neuseeland."],
       ["Chloé Zhao", "Nomadland", "Laiendarsteller spielen sich weitgehend selbst."],
       ["Agnès Varda", "Vogelfrei", "Eine junge Frau zieht durch Südfrankreich."],
       ["Ava DuVernay", "Selma", "Der Marsch für das Wahlrecht 1965."],
       ["Céline Sciamma", "Petite Maman", "Ein Kind begegnet der eigenen Mutter als Kind."],
       ["Lina Wertmüller", "Sieben Schönheiten", "Erste Frau mit einer Regie-Nominierung."],
       ["Julia Ducournau", "Titane", "Goldene Palme für einen Körperhorrorfilm."],
       ["Justine Triet", "Anatomie eines Falls", "Ein Prozess ohne eindeutige Wahrheit."],
       ["Leni Riefenstahl", "Das blaue Licht", "Ihr Spielfilmdebüt, vor den Propagandafilmen."]]'::jsonb,
     '[["Lost in Translation", "Der Film von Sofia Coppola, die nicht auf dem Brett steht."],
       ["Der Pferdeflüsterer", "Von Robert Redford, und der gehört ohnehin nicht hierher."]]'::jsonb),

    ('film-fernsehen', 'synchronstimmen', 'Deutsche Synchronstimmen',
     'Wen spricht die Stimme im Deutschen?',
     'hard', 'Synchronisation (Film)',
     'https://de.wikipedia.org/wiki/Synchronisation_%28Film%29',
     '[["Manfred Lehmann", "Bruce Willis", "Die Stimme ist bekannter als der Sprecher."],
       ["Christian Brückner", "Robert De Niro", "Auch als Erzähler in Dokumentationen gefragt."],
       ["David Nathan", "Johnny Depp", "Spricht außerdem Christian Bale."],
       ["Arne Elsholtz", "Tom Hanks", "Sprach auch Bill Murray."],
       ["Daniela Hoffmann", "Julia Roberts", "Seit Pretty Woman ihre Standardstimme."],
       ["Gert Günther Hoffmann", "Sean Connery", "Auch die Stimme von Paul Newman."],
       ["Thomas Danneberg", "Arnold Schwarzenegger", "Sprach ebenso Sylvester Stallone."],
       ["Randolf Kronberg", "Eddie Murphy", "Prägte den Ton der Komödien der 1980er."],
       ["Klaus Sonnenschein", "Morgan Freeman", "Auch als Erzähler im Fernsehen zu hören."],
       ["Marion von Stengel", "Sandra Bullock", "Langjährige Stammstimme."]]'::jsonb,
     '[["Al Pacino", "Auch er hat feste deutsche Stimmen, hier steht keine davon."],
       ["Meryl Streep", "Ihre Stimme fehlt auf diesem Brett."]]'::jsonb),

    ('film-fernsehen', 'wahre-begebenheiten', 'Filme & ihre wahren Vorbilder',
     'Wessen Geschichte erzählt der Film?',
     'medium', 'Filmbiografie',
     'https://de.wikipedia.org/wiki/Filmbiografie',
     '[["Schindlers Liste", "Oskar Schindler", "Ein Fabrikant rettet über tausend Menschen."],
       ["The Social Network", "Mark Zuckerberg", "Gründung eines Netzwerks als Gerichtsdrama."],
       ["Bohemian Rhapsody", "Freddie Mercury", "Der Auftritt bei Live Aid als Höhepunkt."],
       ["Apollo 13", "Jim Lovell", "Aus einer Mondlandung wird eine Rettungsaktion."],
       ["A Beautiful Mind", "John Nash", "Ein Mathematiker zwischen Genie und Krankheit."],
       ["Die Entdeckung der Unendlichkeit", "Stephen Hawking", "Physik und eine fortschreitende Krankheit."],
       ["Rush", "Niki Lauda", "Rivalität zweier Formel-1-Fahrer."],
       ["Catch Me If You Can", "Frank Abagnale", "Ein Betrüger als Pilot, Arzt und Anwalt."],
       ["Der Pianist", "Władysław Szpilman", "Überleben im Warschauer Ghetto."],
       ["Selma", "Martin Luther King", "Der Marsch nach Montgomery."],
       ["Oppenheimer", "Robert Oppenheimer", "Der Bau der Bombe und die Folgen."],
       ["Die Eiserne Lady", "Margaret Thatcher", "Erzählt aus der Erinnerung im Alter."]]'::jsonb,
     '[["Alan Turing", "The Imitation Game erzählt seine Geschichte, der Film fehlt hier."],
       ["Erin Brockovich", "Auch ein wahres Vorbild, aber keines auf diesem Brett."]]'::jsonb),

    ('film-fernsehen', 'verwandlungen', 'Rollen mit Verwandlung',
     'Wer verwandelte sich für welche Rolle?',
     'hard', 'Schauspiel', 'https://de.wikipedia.org/wiki/Schauspiel',
     '[["Christian Bale", "Der Maschinist", "Extremer Gewichtsverlust für die Rolle."],
       ["Charlize Theron", "Monster", "Prothesen und Gewichtszunahme."],
       ["Robert De Niro", "Wie ein wilder Stier", "Zunahme von rund 27 Kilo für die Spätphase."],
       ["Matthew McConaughey", "Dallas Buyers Club", "Monatelange Diät vor dem Dreh."],
       ["Gary Oldman", "Die dunkelste Stunde", "Stundenlanges Maskenbild für Churchill."],
       ["Nicole Kidman", "The Hours", "Eine künstliche Nase veränderte das Gesicht."],
       ["Renée Zellweger", "Judy", "Sang die Lieder selbst."],
       ["Tilda Swinton", "Suspiria", "Spielte gleich mehrere Rollen unter Maske."],
       ["Brendan Fraser", "The Whale", "Tägliche Stunden im Ganzkörperkostüm."],
       ["Jamie Lee Curtis", "Everything Everywhere", "Bewusst ohne kaschierendes Make-up gespielt."]]'::jsonb,
     '[["Joaquin Phoenix", "Für Joker nahm er stark ab, der Film steht nicht auf dem Brett."],
       ["Daniel Day-Lewis", "Für Mein linker Fuß, und der fehlt in dieser Liste."]]'::jsonb),

    ('film-fernsehen', 'fernsehpreise', 'Fernsehpreise & Länder',
     'In welchem Land wird der Preis vergeben?',
     'medium', 'Fernsehpreis',
     'https://de.wikipedia.org/wiki/Fernsehpreis',
     '[["Emmy", "USA", "Der wichtigste Preis der US-Fernsehbranche."],
       ["Grimme-Preis", "Deutschland", "Ausgezeichnet wird Qualität, nicht Quote."],
       ["Romy", "Österreich", "Benannt nach Romy Schneider."],
       ["BAFTA TV Award", "Vereinigtes Königreich", "Schwester des britischen Filmpreises."],
       ["Rose d''Or", "Schweiz", "Ursprünglich in Montreux verliehen."],
       ["Prix Italia", "Italien", "Ältester internationaler Rundfunkpreis."],
       ["Gemini Award", "Kanada", "Heute Teil der Canadian Screen Awards."],
       ["Logie Award", "Australien", "Publikumsabstimmung als Kern der Verleihung."],
       ["Seoul International Drama Award", "Südkorea", "Zeichnet Serien aus aller Welt aus."],
       ["Nymphe von Monte Carlo", "Monaco", "Trophäe des dortigen Fernsehfestivals."]]'::jsonb,
     '[["Frankreich", "Der Sept d''or wurde dort vergeben, er steht nicht auf dem Brett."],
       ["Japan", "Kein Preis in dieser Liste wird dort verliehen."]]'::jsonb),

    ('film-fernsehen', 'erzaehlformen', 'Erzählformen im Film',
     'Was bezeichnet die Technik?',
     'hard', 'Dramaturgie', 'https://de.wikipedia.org/wiki/Dramaturgie',
     '[["Rahmenhandlung", "Geschichte in der Geschichte", "Der Erzähler sitzt außerhalb der Handlung."],
       ["Unzuverlässiger Erzähler", "Die Erzählstimme täuscht", "Am Ende stimmt das Gesehene nicht mehr."],
       ["Episodenfilm", "Mehrere lose Geschichten", "Verbunden durch Ort, Thema oder Zufall."],
       ["Parallelmontage", "Zwei Handlungen im Wechsel", "Erzeugt Spannung ohne Worte."],
       ["Umgekehrte Chronologie", "Erzählung von hinten", "Jede Szene liegt vor der vorigen."],
       ["Zeitschleife", "Derselbe Tag wiederholt sich", "Die Figur behält als Einzige die Erinnerung."],
       ["Multiperspektive", "Dasselbe aus mehreren Blickwinkeln", "Jede Fassung widerspricht der anderen."],
       ["Split Screen", "Geteiltes Bild", "Zwei Orte gleichzeitig sichtbar."],
       ["Cliffhanger", "Abbruch im Spannungsmoment", "Erfunden für Fortsetzungsromane."],
       ["Deus ex machina", "Rettung aus dem Nichts", "Der Begriff stammt aus dem antiken Theater."],
       ["Chekhovs Gewehr", "Eingeführtes muss zünden", "Sonst gehört es nicht in die Geschichte."],
       ["Twist Ending", "Wendung am Schluss", "Sie zwingt zum zweiten Ansehen."]]'::jsonb,
     '[["Der Erzähler spricht das Publikum an", "Das ist der Bruch der vierten Wand, er fehlt hier."],
       ["Vorgriff auf das spätere Ende", "Die Vorausblende steht nicht auf diesem Brett."]]'::jsonb),

    ('film-fernsehen', 'filmwirtschaft', 'Begriffe der Filmwirtschaft',
     'Was bedeutet der Begriff?',
     'medium', 'Filmwirtschaft',
     'https://de.wikipedia.org/wiki/Filmwirtschaft',
     '[["Blockbuster", "Film mit Rekordumsatz", "Der Begriff stammt aus dem Bombenkrieg."],
       ["Sleeper Hit", "Später Überraschungserfolg", "Startet klein und wächst durch Mundpropaganda."],
       ["Box Office", "Einspielergebnis an der Kasse", "Wöchentlich veröffentlichte Ranglisten."],
       ["Franchise", "Markenreihe mit Ablegern", "Filme, Serien und Spielzeug zusammen."],
       ["Reboot", "Neustart einer Reihe", "Die bisherige Handlung zählt nicht mehr."],
       ["Remake", "Neuverfilmung eines Stoffs", "Oft in anderer Sprache oder Zeit."],
       ["Sequel", "Fortsetzung der Handlung", "Spielt nach dem ersten Teil."],
       ["Prequel", "Vorgeschichte", "Spielt vor dem bereits Erzählten."],
       ["Director''s Cut", "Fassung der Regie", "Weicht von der Kinoversion ab."],
       ["Product Placement", "Bezahlte Markenauftritte", "Die Kaffeetasse steht nicht zufällig da."],
       ["Merchandising", "Verkauf von Begleitprodukten", "Bei manchen Reihen einträglicher als der Film."],
       ["Streaming-Auswertung", "Veröffentlichung im Abo", "Verdrängt zunehmend das Kinofenster."]]'::jsonb,
     '[["Aufwendige Vorabwerbung vor dem Start", "Die Marketingkampagne kommt hier nicht vor."],
       ["Auswertung direkt auf Datenträger", "Das Direct-to-Video steht nicht auf dem Brett."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

-- The answers that belong to no category. Numbered after the pairs so the two
-- sets never collide on `position`, though nothing reads it for a fake: the
-- pool is shuffled before a player sees it, and the review lists fakes on their
-- own rather than in board order.
fakes as (
    select q.id                                         as quiz_id,
           k.value ->> 0                                as label,
           k.value ->> 1                                as explanation,
           (jsonb_array_length(sp.pairs) + k.ord)::int  as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.fakes) with ordinality k(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
),

paired as (
    insert into items (quiz_id, category_id, label, position, explanation)
    select f.quiz_id, c.id, f.answer, f.position, f.explanation
      from flat f
      join new_categories c
        on c.quiz_id = f.quiz_id
       and c.label = f.label
    returning id
)

-- Same table, `category_id` left null. Both inserts run in the one statement,
-- so `items_quiz_id_label_key` still sees the pairs above: a fake written to
-- repeat an answer already on its own board fails the file rather than becoming
-- a second row nobody can tell apart.
insert into items (quiz_id, category_id, label, position, explanation)
select k.quiz_id, null, k.label, k.position, k.explanation
  from fakes k;
