-- Geografie, file 1 of 2. Twenty questions, medium and hard.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs) as (
    values

    ('geografie', 'hauptstaedte-afrikas', 'Hauptstädte Afrikas',
     'Welche Stadt ist die Hauptstadt des Landes?',
     'medium', 'Liste der Staaten Afrikas',
     'https://de.wikipedia.org/wiki/Liste_der_Staaten_Afrikas',
     '[["Ägypten", "Kairo", "Größte Stadt Afrikas, am Nil gelegen."],
       ["Marokko", "Rabat", "Regierungssitz; die größte Stadt des Landes ist Casablanca."],
       ["Nigeria", "Abuja", "1991 auf dem Reißbrett gebaut und löste Lagos ab."],
       ["Kenia", "Nairobi", "Entstand 1899 als Station der Ugandabahn."],
       ["Äthiopien", "Addis Abeba", "Sitz der Afrikanischen Union, 1886 gegründet."],
       ["Tansania", "Dodoma", "1974 zur Hauptstadt bestimmt, anstelle von Daressalam."],
       ["Senegal", "Dakar", "Liegt auf der Halbinsel Kap Verde, dem Westzipfel Afrikas."],
       ["Ghana", "Accra", "Hafenstadt am Golf von Guinea."],
       ["Simbabwe", "Harare", "Hieß bis 1982 Salisbury."],
       ["Algerien", "Algier", "Die weiße Stadt an der Mittelmeerküste."],
       ["Tunesien", "Tunis", "Liegt neben den Ruinen von Karthago."],
       ["Uganda", "Kampala", "Auf Hügeln nahe dem Viktoriasee erbaut."]]'::jsonb),

    ('geografie', 'hauptstaedte-suedamerikas', 'Hauptstädte Südamerikas',
     'Welche Stadt ist die Hauptstadt des Landes?',
     'medium', 'Hauptstadt', 'https://de.wikipedia.org/wiki/Hauptstadt',
     '[["Brasilien", "Brasília", "1960 im Landesinneren neu gebaut, statt Rio de Janeiro."],
       ["Argentinien", "Buenos Aires", "Liegt am Río de la Plata."],
       ["Chile", "Santiago", "1541 von Pedro de Valdivia gegründet."],
       ["Peru", "Lima", "1535 von Pizarro als Stadt der Könige gegründet."],
       ["Kolumbien", "Bogotá", "Liegt auf 2600 Metern in den Anden."],
       ["Venezuela", "Caracas", "Geburtsstadt von Simón Bolívar."],
       ["Ecuador", "Quito", "Liegt fast auf dem Äquator, auf 2850 Metern."],
       ["Bolivien", "La Paz", "Regierungssitz auf 3600 Metern; Sucre bleibt Verfassungshauptstadt."],
       ["Uruguay", "Montevideo", "Liegt Buenos Aires am Río de la Plata gegenüber."],
       ["Paraguay", "Asunción", "1537 gegründet, eine der ältesten Städte des Kontinents."],
       ["Guyana", "Georgetown", "Liegt unter dem Meeresspiegel, geschützt von einer Seemauer."],
       ["Suriname", "Paramaribo", "Die niederländisch geprägte Innenstadt ist Welterbe."]]'::jsonb),

    ('geografie', 'fluesse-muendungen', 'Flüsse & Mündungen',
     'In welches Meer mündet der Fluss?',
     'hard', 'Fluss', 'https://de.wikipedia.org/wiki/Fluss',
     '[["Nil", "Mittelmeer", "Mündet in einem weiten Delta bei Alexandria."],
       ["Amazonas", "Atlantischer Ozean", "Führt mehr Wasser als die nächsten sieben Flüsse zusammen."],
       ["Wolga", "Kaspisches Meer", "Längster Fluss Europas, mündet bei Astrachan."],
       ["Donau", "Schwarzes Meer", "Mündet im Delta zwischen Rumänien und der Ukraine."],
       ["Rhein", "Nordsee", "Mündet im Delta bei Rotterdam."],
       ["Mississippi", "Golf von Mexiko", "Mündet südlich von New Orleans."],
       ["Ganges", "Golf von Bengalen", "Bildet mit dem Brahmaputra das größte Delta der Erde."],
       ["Indus", "Arabisches Meer", "Mündet südöstlich von Karatschi."],
       ["Jangtse", "Ostchinesisches Meer", "Mündet bei Shanghai."],
       ["Lena", "Laptewsee", "Mündet in Sibirien in ein Randmeer des Nordpolarmeers."],
       ["Ob", "Karasee", "Mündet über einen 800 Kilometer langen Meeresarm."],
       ["Colorado", "Golf von Kalifornien", "Erreicht das Meer wegen der Entnahmen kaum noch."]]'::jsonb),

    ('geografie', 'inseln-laender', 'Inseln & Länder',
     'Zu welchem Land gehört die Insel?',
     'medium', 'Insel', 'https://de.wikipedia.org/wiki/Insel',
     '[["Sizilien", "Italien", "Größte Insel des Mittelmeers, getrennt durch die Straße von Messina."],
       ["Korsika", "Frankreich", "Geburtsinsel Napoleons, seit 1768 französisch."],
       ["Mallorca", "Spanien", "Größte der Balearen."],
       ["Kreta", "Griechenland", "Zentrum der minoischen Kultur."],
       ["Bornholm", "Dänemark", "Liegt östlich von Schweden in der Ostsee."],
       ["Gotland", "Schweden", "Größte Insel der Ostsee, mit der Hansestadt Visby."],
       ["Rügen", "Deutschland", "Größte Insel des Landes, mit den Kreidefelsen am Königsstuhl."],
       ["Sansibar", "Tansania", "Gewürzinsel, seit 1964 Teil des Landes."],
       ["Tasmanien", "Australien", "Durch die Bass-Straße vom Festland getrennt."],
       ["Hokkaidō", "Japan", "Nördlichste der vier Hauptinseln."],
       ["Jeju", "Südkorea", "Vulkaninsel südlich des Festlands."],
       ["Vancouver Island", "Kanada", "Vor der Pazifikküste, mit der Provinzhauptstadt Victoria."]]'::jsonb),

    ('geografie', 'seen-laender', 'Seen & Länder',
     'In welchem Land liegt der See?',
     'medium', 'See', 'https://de.wikipedia.org/wiki/See',
     '[["Baikalsee", "Russland", "Tiefster See der Erde, mit einem Fünftel des flüssigen Süßwassers."],
       ["Balaton", "Ungarn", "Größter See Mitteleuropas, flach und im Sommer warm."],
       ["Vänern", "Schweden", "Größter See der Europäischen Union."],
       ["Inarisee", "Finnland", "See in Lappland, nördlich des Polarkreises."],
       ["Loch Ness", "Schottland", "Langer schmaler See im Great Glen."],
       ["Tonle Sap", "Kambodscha", "Wächst zur Regenzeit auf ein Vielfaches an."],
       ["Eyresee", "Australien", "Salzsee, der meist trocken liegt."],
       ["Tanasee", "Äthiopien", "Quellsee des Blauen Nils."],
       ["Michigansee", "USA", "Einziger der Großen Seen, der ganz in einem Land liegt."],
       ["Poyang-See", "China", "Größter Süßwassersee des Landes, am Jangtse."],
       ["Chiemsee", "Deutschland", "Bayerisches Meer genannt, mit der Herreninsel."],
       ["Wörthersee", "Österreich", "Kärntner See, im Sommer einer der wärmsten der Alpen."]]'::jsonb),

    ('geografie', 'wuesten-laender', 'Wüsten & Länder',
     'In welchem Land liegt die Wüste?',
     'hard', 'Wüste', 'https://de.wikipedia.org/wiki/W%C3%BCste',
     '[["Atacama", "Chile", "Trockenste Wüste der Erde, im Norden des Landes."],
       ["Namib", "Namibia", "Nebelwüste an der Atlantikküste, mit sehr hohen Dünen."],
       ["Kalahari", "Botswana", "Bedeckt den größten Teil des Landes."],
       ["Simpsonwüste", "Australien", "Rote Sanddünen im Zentrum des Kontinents."],
       ["Thar", "Indien", "Auch Große Indische Wüste genannt, in Rajasthan."],
       ["Taklamakan", "China", "Sandwüste im Tarimbecken, von der Seidenstraße umgangen."],
       ["Rub al-Chali", "Saudi-Arabien", "Das leere Viertel, größte Sandwüste der Erde."],
       ["Mojave", "USA", "Wüste in Kalifornien, mit dem Death Valley."],
       ["Karakum", "Turkmenistan", "Bedeckt rund 70 Prozent des Landes."],
       ["Negev", "Israel", "Trockenes Bergland im Süden des Landes."],
       ["Danakil", "Äthiopien", "Senke mit Salzseen, eine der heißesten Gegenden der Erde."],
       ["Sinai", "Ägypten", "Wüstenhalbinsel zwischen Rotem Meer und Mittelmeer."]]'::jsonb),

    ('geografie', 'vulkane-laender', 'Vulkane & Länder',
     'In welchem Land steht der Vulkan?',
     'medium', 'Vulkan', 'https://de.wikipedia.org/wiki/Vulkan',
     '[["Ätna", "Italien", "Höchster aktiver Vulkan Europas, auf Sizilien."],
       ["Fudschi", "Japan", "Heiliger Berg und Wahrzeichen des Landes, 3776 Meter hoch."],
       ["Krakatau", "Indonesien", "Sein Ausbruch 1883 war noch in 4000 Kilometern zu hören."],
       ["Popocatépetl", "Mexiko", "Raucht in Sichtweite der Hauptstadt."],
       ["Cotopaxi", "Ecuador", "Einer der höchsten aktiven Vulkane der Erde."],
       ["Eyjafjallajökull", "Island", "Sein Ausbruch 2010 legte den Flugverkehr Europas lahm."],
       ["Kilauea", "USA", "Einer der aktivsten Vulkane der Erde, auf Hawaii."],
       ["Teide", "Spanien", "Höchster Berg des Landes, auf Teneriffa."],
       ["Nyiragongo", "Demokratische Republik Kongo", "Sein Lavasee liegt über der Stadt Goma."],
       ["Pinatubo", "Philippinen", "Sein Ausbruch 1991 kühlte weltweit das Klima."],
       ["Villarrica", "Chile", "Schneebedeckter Kegel über dem Ort Pucón."],
       ["Ol Doinyo Lengai", "Tansania", "Einziger Vulkan, der Karbonatit-Lava fördert."]]'::jsonb),

    ('geografie', 'nationalparks-laender', 'Nationalparks & Länder',
     'In welchem Land liegt der Nationalpark?',
     'medium', 'Nationalpark', 'https://de.wikipedia.org/wiki/Nationalpark',
     '[["Yellowstone", "USA", "1872 gegründet, der erste Nationalpark der Welt."],
       ["Serengeti", "Tansania", "Schauplatz der großen Gnu-Wanderung."],
       ["Krüger-Nationalpark", "Südafrika", "Größtes Wildschutzgebiet des Landes, an der Grenze zu Mosambik."],
       ["Banff", "Kanada", "Ältester Nationalpark des Landes, in den Rocky Mountains."],
       ["Torres del Paine", "Chile", "Granittürme in Patagonien."],
       ["Galápagos", "Ecuador", "Inselgruppe, an der Darwin seine Beobachtungen machte."],
       ["Plitvicer Seen", "Kroatien", "Sechzehn Seen, verbunden durch Wasserfälle."],
       ["Sundarbans", "Bangladesch", "Größter Mangrovenwald der Erde, Heimat des Königstigers."],
       ["Uluru-Kata Tjuta", "Australien", "Um den roten Sandsteinberg im Zentrum des Kontinents."],
       ["Fiordland", "Neuseeland", "Fjorde im Südwesten der Südinsel."],
       ["Bayerischer Wald", "Deutschland", "Erster Nationalpark des Landes, gegründet 1970."],
       ["Doñana", "Spanien", "Feuchtgebiet an der Mündung des Guadalquivir."]]'::jsonb),

    ('geografie', 'bruecken-staedte', 'Brücken & Städte',
     'In welcher Stadt steht die Brücke?',
     'medium', 'Brücke', 'https://de.wikipedia.org/wiki/Br%C3%BCcke',
     '[["Golden Gate Bridge", "San Francisco", "Rot gestrichene Hängebrücke über die Einfahrt zur Bucht."],
       ["Tower Bridge", "London", "Klappbrücke neben dem Tower, 1894 eröffnet."],
       ["Karlsbrücke", "Prag", "Steinbrücke über die Moldau, gesäumt von Heiligenfiguren."],
       ["Rialtobrücke", "Venedig", "Älteste der Brücken über den Canal Grande."],
       ["Ponte Vecchio", "Florenz", "Brücke über den Arno, bebaut mit Goldschmiedeläden."],
       ["Brooklyn Bridge", "New York", "Verbindet Manhattan mit Brooklyn, eröffnet 1883."],
       ["Harbour Bridge", "Sydney", "Stahlbogen neben dem Opernhaus, Kleiderbügel genannt."],
       ["Kapellbrücke", "Luzern", "Überdachte Holzbrücke über die Reuss, mit dem Wasserturm."],
       ["Bosporus-Brücke", "Istanbul", "Verbindet Europa und Asien über die Meerenge."],
       ["Stari Most", "Mostar", "1993 zerstört und 2004 wieder aufgebaut."],
       ["Erasmusbrücke", "Rotterdam", "Weiße Schrägseilbrücke, der Schwan genannt."],
       ["Vasco-da-Gama-Brücke", "Lissabon", "Über zwölf Kilometer lang, über den Tejo."]]'::jsonb),

    ('geografie', 'landeshauptstaedte-deutschland', 'Landeshauptstädte Deutschlands',
     'In welchem Bundesland liegt die Stadt?',
     'medium', 'Landeshauptstadt',
     'https://de.wikipedia.org/wiki/Landeshauptstadt',
     '[["München", "Bayern", "Landeshauptstadt an der Isar."],
       ["Stuttgart", "Baden-Württemberg", "Landeshauptstadt im Talkessel am Neckar."],
       ["Dresden", "Sachsen", "Landeshauptstadt an der Elbe, Elbflorenz genannt."],
       ["Erfurt", "Thüringen", "Landeshauptstadt mit der bebauten Krämerbrücke."],
       ["Kiel", "Schleswig-Holstein", "Landeshauptstadt an der Förde, am Nord-Ostsee-Kanal."],
       ["Mainz", "Rheinland-Pfalz", "Landeshauptstadt am Rhein, Wirkungsort Gutenbergs."],
       ["Magdeburg", "Sachsen-Anhalt", "Landeshauptstadt an der Elbe, Grablege Ottos des Großen."],
       ["Hannover", "Niedersachsen", "Landeshauptstadt an der Leine, bekannt für ihre Messen."],
       ["Schwerin", "Mecklenburg-Vorpommern", "Kleinste Landeshauptstadt, mit dem Schloss im See."],
       ["Saarbrücken", "Saarland", "Landeshauptstadt an der Saar, nahe der französischen Grenze."],
       ["Potsdam", "Brandenburg", "Landeshauptstadt mit Schloss Sanssouci."],
       ["Wiesbaden", "Hessen", "Landeshauptstadt, obwohl Frankfurt die größere Stadt ist."]]'::jsonb),

    ('geografie', 'kantone-hauptorte', 'Kantone & Hauptorte',
     'Welcher Ort ist der Hauptort des Kantons?',
     'hard', 'Kanton (Schweiz)',
     'https://de.wikipedia.org/wiki/Kanton_%28Schweiz%29',
     '[["Wallis", "Sitten", "Französisch Sion, im Rhonetal gelegen."],
       ["Waadt", "Lausanne", "Am Genfersee, Sitz des Internationalen Olympischen Komitees."],
       ["Graubünden", "Chur", "Älteste Stadt der Schweiz, im Rheintal."],
       ["Tessin", "Bellinzona", "Bekannt für drei Burgen, die zum Welterbe gehören."],
       ["Aargau", "Aarau", "1798 für ein halbes Jahr Hauptstadt der Helvetischen Republik."],
       ["Thurgau", "Frauenfeld", "Liegt an der Murg im Nordosten des Landes."],
       ["Appenzell Ausserrhoden", "Herisau", "Größte Gemeinde des Halbkantons."],
       ["Nidwalden", "Stans", "Am Fuß des Stanserhorns."],
       ["Obwalden", "Sarnen", "Liegt am Sarnersee."],
       ["Uri", "Altdorf", "Schauplatz der Tell-Sage, mit dem Telldenkmal."],
       ["Jura", "Delsberg", "Französisch Delémont, Hauptort des jüngsten Kantons."],
       ["Basel-Landschaft", "Liestal", "Kleiner Hauptort südöstlich von Basel."]]'::jsonb),

    ('geografie', 'us-bundesstaaten-hauptstaedte', 'US-Bundesstaaten & Hauptstädte',
     'Welche Stadt ist die Hauptstadt des Bundesstaates?',
     'hard', 'Bundesstaat der Vereinigten Staaten',
     'https://de.wikipedia.org/wiki/Bundesstaat_der_Vereinigten_Staaten',
     '[["Kalifornien", "Sacramento", "Wuchs mit dem Goldrausch von 1849."],
       ["New York", "Albany", "Nicht New York City, sondern die Stadt am Hudson."],
       ["Texas", "Austin", "Benannt nach Stephen F. Austin, dem Vater von Texas."],
       ["Florida", "Tallahassee", "Liegt im Norden des Staates, weit weg von Miami."],
       ["Illinois", "Springfield", "Wirkungsort von Abraham Lincoln."],
       ["Washington", "Olympia", "Am Südende des Puget Sound, nicht Seattle."],
       ["Nevada", "Carson City", "Kleine Stadt nahe dem Lake Tahoe, nicht Las Vegas."],
       ["Oregon", "Salem", "Im Willamette Valley, nicht Portland."],
       ["Georgia", "Atlanta", "Zugleich die größte Stadt des Bundesstaates."],
       ["Colorado", "Denver", "Die Mile High City, 1609 Meter über dem Meer."],
       ["Louisiana", "Baton Rouge", "Am Mississippi, nicht New Orleans."],
       ["Michigan", "Lansing", "In der Mitte des Staates, nicht Detroit."]]'::jsonb),

    ('geografie', 'groesste-staedte-laender', 'Größte Städte, nicht Hauptstädte',
     'Welche Stadt ist die größte des Landes — die Hauptstadt ist es nicht?',
     'medium', 'Millionenstadt', 'https://de.wikipedia.org/wiki/Millionenstadt',
     '[["Türkei", "Istanbul", "Ankara regiert, doch diese Stadt ist weit größer."],
       ["USA", "New York", "Größte Stadt des Landes; Washington ist Regierungssitz."],
       ["Kanada", "Toronto", "Ottawa wurde 1857 als Kompromiss zur Hauptstadt gewählt."],
       ["Australien", "Sydney", "Canberra entstand 1913 als Kompromiss zwischen ihr und Melbourne."],
       ["Brasilien", "São Paulo", "Größte Stadt der Südhalbkugel."],
       ["Indien", "Mumbai", "Finanzzentrum des Landes, früher Bombay."],
       ["Schweiz", "Zürich", "Größte Stadt, während Bern Bundesstadt ist."],
       ["Marokko", "Casablanca", "Wirtschaftszentrum an der Atlantikküste."],
       ["Vietnam", "Ho-Chi-Minh-Stadt", "Früher Saigon, größer als Hanoi."],
       ["Neuseeland", "Auckland", "Etwa ein Drittel des Landes lebt hier; Wellington regiert."],
       ["Nigeria", "Lagos", "Eine der größten Städte Afrikas; Abuja ist Hauptstadt."],
       ["Pakistan", "Karatschi", "Hafenstadt am Arabischen Meer, bis 1959 Hauptstadt."]]'::jsonb),

    ('geografie', 'nationalitaetszeichen', 'Länder & Nationalitätszeichen',
     'Welches Nationalitätszeichen führt das Land?',
     'medium', 'Nationalitätszeichen',
     'https://de.wikipedia.org/wiki/Nationalit%C3%A4tszeichen',
     '[["Schweiz", "CH", "Von Confoederatio Helvetica, dem lateinischen Landesnamen."],
       ["Österreich", "A", "Vom lateinischen Austria."],
       ["Spanien", "E", "Von España."],
       ["Polen", "PL", "Von Polska."],
       ["Ungarn", "H", "Vom lateinischen Hungaria."],
       ["Portugal", "P", "Der Landesname beginnt selbst mit diesem Buchstaben."],
       ["Norwegen", "N", "Von Norge."],
       ["Kroatien", "HR", "Von Hrvatska."],
       ["Tschechien", "CZ", "Von Cesko, ohne die Häkchen geschrieben."],
       ["Slowenien", "SLO", "Von Slovenija."],
       ["Griechenland", "GR", "Vom lateinischen Graecia."],
       ["Schweden", "S", "Von Sverige."]]'::jsonb),

    ('geografie', 'meerengen-anrainer', 'Meerengen & Anrainer',
     'Welche Küsten trennt die Meerenge?',
     'hard', 'Meerenge', 'https://de.wikipedia.org/wiki/Meerenge',
     '[["Straße von Gibraltar", "Spanien und Marokko", "Trennt Europa von Afrika, an der engsten Stelle 14 Kilometer."],
       ["Straße von Dover", "England und Frankreich", "Engste Stelle des Ärmelkanals, mit dem Tunnel darunter."],
       ["Bosporus", "Türkei", "Trennt die beiden Hälften Istanbuls."],
       ["Straße von Malakka", "Malaysia und Indonesien", "Wichtigste Route zwischen Indischem und Pazifischem Ozean."],
       ["Beringstraße", "Russland und USA", "Trennt Asien von Amerika, rund 85 Kilometer breit."],
       ["Straße von Hormus", "Iran und Oman", "Durch sie läuft ein großer Teil des Öls der Welt."],
       ["Öresund", "Dänemark und Schweden", "Seit 2000 von Brücke und Tunnel überspannt."],
       ["Straße von Messina", "Italien", "Trennt Sizilien vom Festland."],
       ["Torres-Straße", "Australien und Papua-Neuguinea", "Flache Meerenge voller Riffe."],
       ["Magellanstraße", "Chile", "1520 von Magellan durchfahren, nördlich von Feuerland."],
       ["Straße von Taiwan", "China und Taiwan", "Rund 130 Kilometer breit an der engsten Stelle."],
       ["Skagerrak", "Norwegen und Dänemark", "Verbindet die Nordsee mit dem Kattegat."]]'::jsonb),

    ('geografie', 'kanaele-laender', 'Kanäle & Länder',
     'In welchem Land liegt der Kanal?',
     'medium', 'Kanal (Wasserbau)',
     'https://de.wikipedia.org/wiki/Kanal_%28Wasserbau%29',
     '[["Sueskanal", "Ägypten", "Verbindet Mittelmeer und Rotes Meer, 1869 eröffnet."],
       ["Panamakanal", "Panama", "Verbindet Atlantik und Pazifik über Schleusen und einen Stausee."],
       ["Nord-Ostsee-Kanal", "Deutschland", "Meistbefahrener künstlicher Wasserweg der Welt."],
       ["Kanal von Korinth", "Griechenland", "Durchschneidet den Isthmus, 1893 fertiggestellt."],
       ["Götakanal", "Schweden", "Quert das Land vom Kattegat zur Ostsee."],
       ["Canal du Midi", "Frankreich", "Verbindet Toulouse mit dem Mittelmeer, im 17. Jahrhundert gebaut."],
       ["Wolga-Don-Kanal", "Russland", "Verbindet zwei große Ströme, 1952 eröffnet."],
       ["Eriekanal", "USA", "Verband ab 1825 die Großen Seen mit dem Hudson."],
       ["Kaiserkanal", "China", "Ältester und längster künstlicher Wasserweg der Welt."],
       ["Nordseekanal", "Niederlande", "Verbindet Amsterdam mit der Nordsee bei IJmuiden."],
       ["Wellandkanal", "Kanada", "Überwindet den Höhenunterschied der Niagarafälle."]]'::jsonb),

    ('geografie', 'flughafencodes-staedte', 'Flughafencodes & Städte',
     'Zu welcher Stadt gehört der Flughafencode?',
     'medium', 'IATA-Flughafencode',
     'https://de.wikipedia.org/wiki/IATA-Flughafencode',
     '[["JFK", "New York", "Benannt nach dem 1963 ermordeten Präsidenten."],
       ["LHR", "London", "Heathrow, größter Flughafen Europas nach Passagierzahl."],
       ["CDG", "Paris", "Benannt nach dem General und Staatspräsidenten."],
       ["HND", "Tokio", "Der stadtnahe Flughafen Haneda, nicht Narita."],
       ["FRA", "Frankfurt", "Größter Flughafen Deutschlands, Drehkreuz der Lufthansa."],
       ["DXB", "Dubai", "Drehkreuz für Flüge zwischen Europa und Asien."],
       ["SIN", "Singapur", "Flughafen Changi, bekannt für den Wasserfall im Terminal."],
       ["LAX", "Los Angeles", "Das X kam dazu, als zwei Buchstaben nicht mehr reichten."],
       ["MEX", "Mexiko-Stadt", "Flughafen Benito Juárez, auf 2200 Metern Höhe."],
       ["GRU", "São Paulo", "Flughafen Guarulhos, größter Brasiliens."],
       ["SYD", "Sydney", "Ältester durchgehend betriebener Flughafen der Welt."],
       ["ZRH", "Zürich", "Größter Flughafen der Schweiz, in Kloten."]]'::jsonb),

    ('geografie', 'nationalfeiertage', 'Länder & Nationalfeiertage',
     'An welchem Tag feiert das Land seinen Nationalfeiertag?',
     'hard', 'Nationalfeiertag', 'https://de.wikipedia.org/wiki/Nationalfeiertag',
     '[["Frankreich", "14. Juli", "Erinnert an den Sturm auf die Bastille 1789."],
       ["USA", "4. Juli", "Tag der Unabhängigkeitserklärung von 1776."],
       ["Deutschland", "3. Oktober", "Tag der Deutschen Einheit, seit 1990."],
       ["Österreich", "26. Oktober", "Erinnert an das Neutralitätsgesetz von 1955."],
       ["Schweiz", "1. August", "Erinnert an den Bundesbrief von 1291."],
       ["Italien", "2. Juni", "Erinnert an das Referendum für die Republik 1946."],
       ["Indien", "15. August", "Unabhängigkeit von Großbritannien 1947."],
       ["Mexiko", "16. September", "Der Ruf von Dolores 1810 begann den Aufstand."],
       ["Brasilien", "7. September", "Unabhängigkeit von Portugal 1822."],
       ["Griechenland", "25. März", "Beginn des Aufstands gegen die Osmanen 1821."],
       ["Irland", "17. März", "Todestag des Nationalheiligen Patrick."],
       ["Kanada", "1. Juli", "Gründung des Dominions 1867."]]'::jsonb),

    ('geografie', 'plaetze-staedte', 'Plätze & Straßen',
     'In welcher Stadt liegt der Platz oder die Straße?',
     'medium', 'Platz', 'https://de.wikipedia.org/wiki/Platz',
     '[["Champs-Élysées", "Paris", "Führt von der Place de la Concorde zum Triumphbogen."],
       ["Times Square", "New York", "Benannt nach dem Verlagshaus der dortigen Zeitung."],
       ["Roter Platz", "Moskau", "Liegt vor dem Kreml, mit der Basilius-Kathedrale."],
       ["Kurfürstendamm", "Berlin", "Boulevard im Westen der Stadt, 3,5 Kilometer lang."],
       ["La Rambla", "Barcelona", "Führt vom Plaça de Catalunya hinunter zum Hafen."],
       ["Wenzelsplatz", "Prag", "Schauplatz der Samtenen Revolution 1989."],
       ["Piccadilly Circus", "London", "Kreuzung mit den großen Leuchtreklamen."],
       ["Shibuya-Kreuzung", "Tokio", "Meistbegangene Straßenkreuzung der Welt."],
       ["Spanische Treppe", "Rom", "137 Stufen hinauf zur Kirche Trinità dei Monti."],
       ["Nyhavn", "Kopenhagen", "Bunter Kanal mit Segelschiffen, Wohnort Andersens."],
       ["Grand-Place", "Brüssel", "Marktplatz mit Rathaus und Gildehäusern, Welterbe."],
       ["Bahnhofstrasse", "Zürich", "Eine der teuersten Einkaufsstraßen der Welt."]]'::jsonb),

    ('geografie', 'halbinseln-laender', 'Halbinseln & Länder',
     'Zu welchem Land gehört die Halbinsel?',
     'medium', 'Halbinsel', 'https://de.wikipedia.org/wiki/Halbinsel',
     '[["Krim", "Ukraine", "Liegt am Schwarzen Meer, seit 2014 von Russland besetzt."],
       ["Jütland", "Dänemark", "Der Festlandsteil des Landes."],
       ["Kola", "Russland", "Halbinsel am Nordpolarmeer, mit der Stadt Murmansk."],
       ["Yucatán", "Mexiko", "Kalksteinplatte mit den Ruinen von Chichén Itzá."],
       ["Sinai", "Ägypten", "Verbindet Afrika mit Asien."],
       ["Peloponnes", "Griechenland", "Südlicher Teil des Festlands, mit Sparta und Olympia."],
       ["Istrien", "Kroatien", "Größte Halbinsel der Adria."],
       ["Kap-York-Halbinsel", "Australien", "Nördlichster Zipfel des Kontinents."],
       ["Malakka", "Malaysia", "Trennt die Andamanensee vom Südchinesischen Meer."],
       ["Anatolien", "Türkei", "Auch Kleinasien genannt."],
       ["Bretagne", "Frankreich", "Ragt in den Atlantik, mit keltischem Erbe."],
       ["Nova Scotia", "Kanada", "Atlantikprovinz, deren Name Neuschottland bedeutet."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
)

insert into items (quiz_id, category_id, label, position, explanation)
select f.quiz_id, c.id, f.answer, f.position, f.explanation
  from flat f
  join new_categories c
    on c.quiz_id = f.quiz_id
   and c.label = f.label;
