-- Geografie, leichte Fragen. Zwanzig Fragen, alle 'easy'.
--
-- Gefragt wird nach dem, was auf jeder Weltkarte im Klassenzimmer steht, nicht
-- nach Enklaven und Kartennetzentwürfen.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs) as (
    values

    ('geografie', 'leicht-hauptstaedte-europa', 'Hauptstädte in Europa',
     'Welche Stadt ist die Hauptstadt?',
     'easy', 'Hauptstadt', 'https://de.wikipedia.org/wiki/Hauptstadt',
     '[["Italien", "Rom", "Die Stadt mit dem Kolosseum."],
       ["Frankreich", "Paris", "Der Eiffelturm steht hier."],
       ["Spanien", "Madrid", "Sie liegt fast in der Mitte des Landes."],
       ["Vereinigtes Königreich", "London", "An der Themse gelegen."],
       ["Österreich", "Wien", "Bekannt für Kaffeehäuser und Walzer."],
       ["Schweiz", "Bern", "Nicht Zürich, wie viele denken."],
       ["Niederlande", "Amsterdam", "Eine Stadt voller Grachten."],
       ["Belgien", "Brüssel", "Hier sitzt die EU-Kommission."],
       ["Dänemark", "Kopenhagen", "Mit der kleinen Meerjungfrau am Hafen."],
       ["Norwegen", "Oslo", "Am Ende eines langen Fjords."],
       ["Schweden", "Stockholm", "Auf vierzehn Inseln gebaut."],
       ["Polen", "Warschau", "Nach dem Krieg wieder aufgebaut."]]'::jsonb),

    ('geografie', 'leicht-staedte-laender', 'Städte & Länder',
     'In welchem Land liegt die Stadt?',
     'easy', 'Stadt', 'https://de.wikipedia.org/wiki/Stadt',
     '[["Barcelona", "Spanien", "Am Mittelmeer gelegen."],
       ["Mailand", "Italien", "Bekannt für Mode und Design."],
       ["Hamburg", "Deutschland", "Die größte Hafenstadt des Landes."],
       ["New York", "USA", "Mit der Freiheitsstatue."],
       ["Sydney", "Australien", "Mit dem Opernhaus am Wasser."],
       ["Rio de Janeiro", "Brasilien", "Bekannt für Strand und Karneval."],
       ["Kapstadt", "Südafrika", "Am Fuß des Tafelbergs."],
       ["Toronto", "Kanada", "Die größte Stadt des Landes."],
       ["Mumbai", "Indien", "Zentrum der indischen Filmindustrie."],
       ["Istanbul", "Türkei", "Sie liegt auf zwei Kontinenten."],
       ["Zürich", "Schweiz", "Am Ende eines Sees."],
       ["Marseille", "Frankreich", "Ein alter Hafen am Mittelmeer."]]'::jsonb),

    ('geografie', 'leicht-flaggen-farben', 'Flaggen & Farben',
     'Wie sieht die Flagge aus?',
     'easy', 'Flagge', 'https://de.wikipedia.org/wiki/Flagge',
     '[["Deutschland", "Schwarz, Rot, Gold", "Drei waagerechte Streifen."],
       ["Frankreich", "Blau, Weiß, Rot", "Drei senkrechte Streifen."],
       ["Italien", "Grün, Weiß, Rot", "Ebenfalls senkrecht gestreift."],
       ["Japan", "Rote Scheibe auf Weiß", "Die Sonne in der Mitte."],
       ["Schweiz", "Weißes Kreuz auf Rot", "Quadratisch statt rechteckig."],
       ["Schweden", "Gelbes Kreuz auf Blau", "Ein liegendes Kreuz."],
       ["Kanada", "Rotes Ahornblatt", "Zwischen zwei roten Streifen."],
       ["Griechenland", "Blau-weiß gestreift", "Mit einem Kreuz in der Ecke."],
       ["Österreich", "Rot, Weiß, Rot", "Eine der ältesten Flaggen."],
       ["Belgien", "Schwarz, Gelb, Rot", "Senkrecht angeordnet."],
       ["Niederlande", "Rot, Weiß, Blau", "Waagerecht gestreift."],
       ["Spanien", "Rot, Gelb, Rot", "Mit dem Wappen links."]]'::jsonb),

    ('geografie', 'leicht-himmelsrichtungen', 'Auf der Landkarte',
     'Was bedeutet das?',
     'easy', 'Himmelsrichtung',
     'https://de.wikipedia.org/wiki/Himmelsrichtung',
     '[["Norden", "Oben auf der Karte", "Fast alle Karten sind so gedruckt."],
       ["Süden", "Unten auf der Karte", "Dort steht mittags die Sonne."],
       ["Osten", "Rechts auf der Karte", "Dort geht die Sonne auf."],
       ["Westen", "Links auf der Karte", "Dort geht die Sonne unter."],
       ["Kompass", "Zeigt immer nach Norden", "Die Nadel folgt dem Erdmagnetfeld."],
       ["Äquator", "Trennt Nord und Süd", "Nord und Süd treffen sich hier."],
       ["Nordpol", "Nördlichster Punkt der Erde", "Dort gibt es kein Land, nur Eis."],
       ["Südpol", "Südlichster Punkt der Erde", "Er liegt auf dem Festland."],
       ["Maßstab", "Verhältnis zur Wirklichkeit", "Ein Zentimeter kann ein Kilometer sein."],
       ["Legende", "Erklärung der Zeichen", "Sie steht am Kartenrand."]]'::jsonb),

    ('geografie', 'leicht-rekorde-erde', 'Rekorde der Erde',
     'Was ist gesucht?',
     'easy', 'Geographie', 'https://de.wikipedia.org/wiki/Geographie',
     '[["Größtes Land der Erde", "Russland", "Es reicht über elf Zeitzonen."],
       ["Kleinstes Land der Erde", "Vatikanstadt", "Man geht in einer Stunde herum."],
       ["Höchster Berg der Erde", "Mount Everest", "8849 Meter hoch."],
       ["Längster Fluss der Erde", "Nil", "Er fließt durch Afrika."],
       ["Größte Sandwüste", "Sahara", "So groß wie die USA."],
       ["Größter Ozean", "Pazifik", "Er bedeckt ein Drittel der Erde."],
       ["Größte Insel", "Grönland", "Trotzdem kein Kontinent."],
       ["Größter See", "Kaspisches Meer", "Er heißt Meer, ist aber ein See."],
       ["Tiefste Stelle im Meer", "Marianengraben", "Fast elf Kilometer tief."],
       ["Kontinent ohne feste Bewohner", "Antarktika", "Nur Forscher leben zeitweise dort."]]'::jsonb),

    ('geografie', 'leicht-sprachen-laender', 'Sprachen & Länder',
     'Welche Sprache spricht man dort?',
     'easy', 'Sprache', 'https://de.wikipedia.org/wiki/Sprache',
     '[["Frankreich", "Französisch", "Auch in Teilen Kanadas gesprochen."],
       ["Italien", "Italienisch", "Aus dem Lateinischen entstanden."],
       ["Spanien", "Spanisch", "In fast ganz Lateinamerika ebenfalls."],
       ["Portugal", "Portugiesisch", "Auch in Brasilien."],
       ["Polen", "Polnisch", "Eine slawische Sprache."],
       ["Griechenland", "Griechisch", "Mit einem eigenen Alphabet."],
       ["Schweden", "Schwedisch", "Nahe verwandt mit Norwegisch."],
       ["Ungarn", "Ungarisch", "Mit keiner Nachbarsprache verwandt."],
       ["Niederlande", "Niederländisch", "Dem Deutschen sehr ähnlich."],
       ["Türkei", "Türkisch", "Seit 1928 mit lateinischen Buchstaben."],
       ["Finnland", "Finnisch", "Verwandt mit dem Ungarischen."],
       ["Tschechien", "Tschechisch", "Mit vielen Häkchen über den Buchstaben."]]'::jsonb),

    ('geografie', 'leicht-deutschland-sehenswert', 'Sehenswertes in Deutschland',
     'In welcher Stadt oder Region steht das?',
     'easy', 'Sehenswürdigkeit',
     'https://de.wikipedia.org/wiki/Sehensw%C3%BCrdigkeit',
     '[["Brandenburger Tor", "Berlin", "Wahrzeichen der Hauptstadt."],
       ["Kölner Dom", "Köln", "Direkt neben dem Hauptbahnhof."],
       ["Frauenkirche", "Dresden", "Nach dem Krieg wieder aufgebaut."],
       ["Elbphilharmonie", "Hamburg", "Auf einem alten Kaispeicher."],
       ["Hofbräuhaus", "München", "Ein sehr bekanntes Wirtshaus."],
       ["Porta Nigra", "Trier", "Ein römisches Stadttor."],
       ["Schwebebahn", "Wuppertal", "Sie hängt über dem Fluss."],
       ["Völkerschlachtdenkmal", "Leipzig", "Ein sehr wuchtiger Bau."],
       ["Zeche Zollverein", "Essen", "Früher Kohle, heute Welterbe."],
       ["Bremer Stadtmusikanten", "Bremen", "Vier Tiere übereinander."],
       ["Schloss Neuschwanstein", "Bayern", "Vorbild für Märchenschlösser."],
       ["Loreley", "Rheintal", "Ein Felsen über dem Fluss."]]'::jsonb),

    ('geografie', 'leicht-fluesse-laender', 'Flüsse & Länder',
     'Durch welches Land fließt er vor allem?',
     'easy', 'Fluss', 'https://de.wikipedia.org/wiki/Fluss',
     '[["Nil", "Ägypten", "Ohne ihn wäre dort nur Wüste."],
       ["Amazonas", "Brasilien", "Der wasserreichste Fluss der Erde."],
       ["Rhein", "Deutschland", "Er mündet in die Nordsee."],
       ["Themse", "England", "Sie fließt durch London."],
       ["Seine", "Frankreich", "Sie teilt Paris."],
       ["Wolga", "Russland", "Der längste Fluss Europas."],
       ["Ganges", "Indien", "Er gilt als heilig."],
       ["Mississippi", "USA", "Er fließt bis in den Golf von Mexiko."],
       ["Jangtse", "China", "Der längste Fluss Asiens."],
       ["Tiber", "Italien", "Rom entstand an seinen Ufern."],
       ["Weichsel", "Polen", "Sie fließt durch Warschau."],
       ["Ebro", "Spanien", "Er mündet ins Mittelmeer."]]'::jsonb),

    ('geografie', 'leicht-meere', 'Meere & Ozeane',
     'Was stimmt?',
     'easy', 'Ozean', 'https://de.wikipedia.org/wiki/Ozean',
     '[["Pazifik", "Der größte Ozean", "Zwischen Asien und Amerika."],
       ["Atlantik", "Zwischen Europa und Amerika", "Kolumbus überquerte ihn."],
       ["Indischer Ozean", "Südlich von Asien", "Zwischen Afrika und Australien."],
       ["Nordsee", "Nördlich von Deutschland", "Bekannt für Ebbe und Flut."],
       ["Ostsee", "Östlich von Dänemark", "Weniger salzig als die Nordsee."],
       ["Mittelmeer", "Zwischen Europa und Afrika", "Ein beliebtes Urlaubsziel."],
       ["Rotes Meer", "Zwischen Afrika und Arabien", "Bekannt für Korallenriffe."],
       ["Schwarzes Meer", "Östlich des Balkans", "Über den Bosporus verbunden."],
       ["Totes Meer", "Salziger als jedes Meer", "Untergehen ist kaum möglich."],
       ["Karibisches Meer", "Bei Mittelamerika", "Bekannt für seine Inseln."]]'::jsonb),

    ('geografie', 'leicht-laender-typisch', 'Typisch für das Land',
     'Zu welchem Land gehört das?',
     'easy', 'Staat', 'https://de.wikipedia.org/wiki/Staat',
     '[["Pizza und Pasta", "Italien", "Beides längst in aller Welt."],
       ["Schokolade und Uhren", "Schweiz", "Dazu Käse und Berge."],
       ["Tulpen und Windmühlen", "Niederlande", "Beides gehört zum Bild."],
       ["Kirschblüte und Sushi", "Japan", "Die Blüte wird landesweit verfolgt."],
       ["Pyramiden und der Nil", "Ägypten", "Beides seit Jahrtausenden."],
       ["Känguru und Koala", "Australien", "Beide gibt es nur dort frei lebend."],
       ["Ahornsirup und Elche", "Kanada", "Das Ahornblatt steht auf der Flagge."],
       ["Karneval und Samba", "Brasilien", "Der Höhepunkt ist in Rio."],
       ["Oliven und Antike", "Griechenland", "Tempel und Inseln."],
       ["Curry und Bollywood", "Indien", "Filme mit viel Musik."],
       ["Große Mauer und Pandas", "China", "Beides Wahrzeichen des Landes."],
       ["Baguette und Eiffelturm", "Frankreich", "Beides Sinnbilder von Paris."]]'::jsonb),

    ('geografie', 'leicht-landschaften', 'Landschaften',
     'Was zeichnet die Landschaft aus?',
     'easy', 'Landschaft', 'https://de.wikipedia.org/wiki/Landschaft',
     '[["Wüste", "Sehr trocken", "Kaum Regen im ganzen Jahr."],
       ["Regenwald", "Warm und sehr feucht", "Es regnet fast täglich."],
       ["Gebirge", "Hohe Berge und Täler", "Oft mit Schnee auf den Gipfeln."],
       ["Küste", "Land trifft Meer", "Mit Stränden oder Klippen."],
       ["Insel", "Ringsum von Wasser umgeben", "Mit dem Boot oder Flugzeug erreichbar."],
       ["Steppe", "Weites Grasland", "Zu trocken für Wald."],
       ["Tundra", "Kalt und baumlos", "Der Boden bleibt tief gefroren."],
       ["Moor", "Nasser, weicher Boden", "Es speichert viel Kohlenstoff."],
       ["Tal", "Senke zwischen Bergen", "Oft mit einem Fluss darin."],
       ["Hochebene", "Flach, aber weit oben", "Zum Beispiel in Tibet."]]'::jsonb),

    ('geografie', 'leicht-europa-nachbarn', 'Nachbarn Deutschlands',
     'Was gehört zum Nachbarland?',
     'easy', 'Deutschland', 'https://de.wikipedia.org/wiki/Deutschland',
     '[["Dänemark", "Im Norden", "Verbunden über Schleswig-Holstein."],
       ["Polen", "Im Osten", "Getrennt durch Oder und Neiße."],
       ["Tschechien", "Im Südosten", "Getrennt durch Mittelgebirge."],
       ["Österreich", "Im Südosten der Alpen", "Gleiche Sprache, andere Wörter."],
       ["Schweiz", "Im Süden am Bodensee", "Nicht in der Europäischen Union."],
       ["Frankreich", "Im Südwesten", "Getrennt durch den Rhein."],
       ["Luxemburg", "Ein kleines Nachbarland", "Sehr klein, sehr wohlhabend."],
       ["Belgien", "Im Westen", "Mit Brüssel als EU-Sitz."],
       ["Niederlande", "Im Nordwesten", "Viel Land liegt unter dem Meeresspiegel."],
       ["Nordsee und Ostsee", "Deutschlands zwei Meere", "Beide im Norden."]]'::jsonb),

    ('geografie', 'leicht-inseln', 'Inseln',
     'Zu welchem Meer oder Land gehört die Insel?',
     'easy', 'Insel', 'https://de.wikipedia.org/wiki/Insel',
     '[["Sylt", "Nordsee", "Bekannt für ihre Dünen."],
       ["Rügen", "Ostsee", "Die größte Insel Deutschlands."],
       ["Mallorca", "Mittelmeer", "Ein beliebtes Urlaubsziel."],
       ["Island", "Nordatlantik", "Vulkane und heiße Quellen."],
       ["Madagaskar", "Indischer Ozean", "Vor der Küste Afrikas."],
       ["Hawaii", "Pazifik", "Aus Vulkanen entstanden."],
       ["Sizilien", "Italien", "Mit dem Ätna darauf."],
       ["Kreta", "Griechenland", "Die größte griechische Insel."],
       ["Grönland", "Dänemark", "Weitgehend selbst verwaltet."],
       ["Korsika", "Frankreich", "Geburtsinsel Napoleons."]]'::jsonb),

    ('geografie', 'leicht-reisen', 'Auf Reisen',
     'Was braucht oder macht man da?',
     'easy', 'Reise', 'https://de.wikipedia.org/wiki/Reise',
     '[["Ausweis für das Ausland", "Reisepass", "In der EU reicht oft der Personalausweis."],
       ["Behälter für Kleidung", "Koffer", "Am Flughafen wird er gewogen."],
       ["Ort für Starts und Landungen", "Flughafen", "Mit Sicherheitskontrolle davor."],
       ["Ort, an dem Züge halten", "Bahnhof", "Mit Gleisen und Anzeigetafel."],
       ["Ort, an dem Schiffe anlegen", "Hafen", "Mit Kränen für die Fracht."],
       ["Papier oder App zum Einsteigen", "Ticket", "Ohne kommt man nicht mit."],
       ["Unterkunft für die Nacht", "Hotel", "Frühstück oft inklusive."],
       ["Andere Uhrzeit im Zielland", "Zeitverschiebung", "Sie macht müde."],
       ["Kontrolle an der Grenze", "Zoll", "Manches darf man nicht mitbringen."],
       ["Kleines Andenken", "Souvenir", "Es erinnert an die Reise."]]'::jsonb),

    ('geografie', 'leicht-berge-bekannt', 'Bekannte Berge',
     'In welchem Land oder Gebirge steht er?',
     'easy', 'Berg', 'https://de.wikipedia.org/wiki/Berg',
     '[["Zugspitze", "Deutschland", "Der höchste Berg des Landes."],
       ["Matterhorn", "Schweiz", "Eine berühmte Bergpyramide."],
       ["Mount Everest", "Nepal", "Der höchste Berg der Erde."],
       ["Kilimandscharo", "Tansania", "Der höchste Berg Afrikas."],
       ["Fudschi", "Japan", "Ein Vulkankegel und Wahrzeichen."],
       ["Großglockner", "Österreich", "Der höchste Berg des Landes."],
       ["Ätna", "Italien", "Ein sehr aktiver Vulkan."],
       ["Uluru", "Australien", "Ein großer roter Felsen."],
       ["Tafelberg", "Südafrika", "Er hat oben eine flache Fläche."],
       ["Brocken", "Harz", "Der höchste Berg Norddeutschlands."]]'::jsonb),

    ('geografie', 'leicht-kontinente-tiere', 'Wo lebt das Tier?',
     'Auf welchem Kontinent lebt es frei?',
     'easy', 'Kontinent', 'https://de.wikipedia.org/wiki/Kontinent',
     '[["Känguru", "Australien", "Es trägt sein Junges im Beutel."],
       ["Eisbär", "Arktis", "Auf dem Meereis unterwegs."],
       ["Pinguin", "Antarktis", "Er kann nicht fliegen."],
       ["Elefant mit großen Ohren", "Afrika", "Die Ohren dienen der Kühlung."],
       ["Großer Panda", "Asien", "Er frisst fast nur Bambus."],
       ["Braunbär in den Karpaten", "Europa", "Der größte Bestand des Kontinents."],
       ["Faultier", "Südamerika", "Es hängt fast immer in Bäumen."],
       ["Bison", "Nordamerika", "Früher in riesigen Herden."],
       ["Kiwi", "Neuseeland", "Ein Vogel, der nicht fliegen kann."],
       ["Kamel mit zwei Höckern", "Zentralasien", "Es hält Kälte gut aus."]]'::jsonb),

    ('geografie', 'leicht-wetter-orte', 'Wetter & Orte',
     'Wie ist das Wetter dort meistens?',
     'easy', 'Klima', 'https://de.wikipedia.org/wiki/Klima',
     '[["Sahara", "Heiß und sehr trocken", "Nachts wird es dennoch kalt."],
       ["Amazonasgebiet", "Warm und schwül", "Fast täglich Regen."],
       ["Nordpol", "Eisig kalt", "Im Winter geht die Sonne nicht auf."],
       ["Mittelmeerküste", "Trockene, heiße Sommer", "Milde, feuchte Winter."],
       ["Alpen im Winter", "Kalt mit viel Schnee", "Gut für den Wintersport."],
       ["Großbritannien", "Oft bewölkt und wechselhaft", "Regenschirm gehört dazu."],
       ["Wüste Gobi", "Kalte Wüste", "Im Winter tief unter null."],
       ["Island", "Kühl und windig", "Das Wetter wechselt sehr schnell."],
       ["Indien im Sommer", "Regenzeit mit Monsun", "Wochenlang starker Regen."],
       ["Kanarische Inseln", "Ganzjährig mild", "Deshalb Insel des ewigen Frühlings genannt."]]'::jsonb),

    ('geografie', 'leicht-europa-fakten', 'Europa',
     'Was gilt für Europa?',
     'easy', 'Europa', 'https://de.wikipedia.org/wiki/Europa',
     '[["Gemeinsame Währung vieler Länder", "Euro", "Nicht alle EU-Länder haben ihn."],
       ["Sitz vieler EU-Behörden", "Brüssel", "Auch Straßburg spielt eine Rolle."],
       ["Höchstes Gebirge Europas", "Alpen", "Sie ziehen sich durch acht Länder."],
       ["Längster Fluss Europas", "Wolga", "Sie fließt durch Russland."],
       ["Kleinster Staat Europas", "Vatikanstadt", "Mitten in Rom."],
       ["Nördlichstes Land des Festlands", "Norwegen", "Mit dem Nordkap."],
       ["Insel im Nordatlantik", "Island", "Vulkanisch sehr aktiv."],
       ["Meer zwischen Europa und Afrika", "Mittelmeer", "Über Gibraltar mit dem Atlantik verbunden."],
       ["Land mit den meisten Einwohnern", "Deutschland", "Über achtzig Millionen Menschen."],
       ["Halbinsel mit Spanien und Portugal", "Iberische Halbinsel", "Durch die Pyrenäen abgetrennt."]]'::jsonb),

    ('geografie', 'leicht-karte-lesen', 'Karte lesen',
     'Was zeigt das auf der Karte?',
     'easy', 'Landkarte', 'https://de.wikipedia.org/wiki/Landkarte',
     '[["Blaue Flächen", "Wasser", "Meere, Seen und Flüsse."],
       ["Grüne Flächen", "Tiefland und Wälder", "Je grüner, desto flacher."],
       ["Braune Flächen", "Berge und Hochland", "Je dunkler, desto höher."],
       ["Dicke rote Linien", "Autobahnen", "Dünnere Linien sind kleinere Straßen."],
       ["Schwarze Punkte mit Namen", "Städte", "Große Punkte, große Städte."],
       ["Gestrichelte Linien", "Grenzen", "Zwischen Ländern oder Regionen."],
       ["Kleines Flugzeugsymbol", "Flughafen", "Meist am Rand einer Stadt."],
       ["Zahl neben einem Gipfel", "Höhe in Metern", "Über dem Meeresspiegel gemessen."],
       ["Nordpfeil", "Ausrichtung der Karte", "Er zeigt, wo Norden liegt."],
       ["Balken mit Kilometerangabe", "Maßstab", "Damit misst man Entfernungen."]]'::jsonb),

    ('geografie', 'leicht-welt-zahlen', 'Die Erde in Zahlen',
     'Wie viele sind es?',
     'easy', 'Erde', 'https://de.wikipedia.org/wiki/Erde',
     '[["Kontinente", "7", "Von Afrika bis Australien."],
       ["Ozeane", "5", "Seit 2000 zählt auch der Südliche Ozean."],
       ["Stunden eines Tages", "24", "Eine Umdrehung der Erde."],
       ["Tage eines normalen Jahres", "365", "Im Schaltjahr einer mehr."],
       ["Jahreszeiten", "4", "In den Tropen gibt es sie so nicht."],
       ["Bundesländer in Deutschland", "16", "Drei davon sind Stadtstaaten."],
       ["Länder in der Europäischen Union", "27", "Nach dem Austritt Großbritanniens."],
       ["Grad zwischen Nord- und Südpol", "180", "Vom Pol zum Pol gemessen."],
       ["Bundesländer in Österreich", "9", "Wien ist eines davon."],
       ["Kantone der Schweiz", "26", "Sechs davon sind Halbkantone."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
)

insert into items (quiz_id, category_id, label, position, explanation)
select f.quiz_id, c.id, f.answer, f.position, f.explanation
  from flat f
  join new_categories c
    on c.quiz_id = f.quiz_id
   and c.label = f.label;
