-- Geografie, file 2 of 2. Twenty questions, medium and hard.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs) as (
    values

    ('geografie', 'wolkenkratzer-staedte', 'Wolkenkratzer & Städte',
     'In welcher Stadt steht das Hochhaus?',
     'medium', 'Wolkenkratzer', 'https://de.wikipedia.org/wiki/Wolkenkratzer',
     '[["Burj Khalifa", "Dubai", "828 Meter, seit 2010 das höchste Bauwerk der Welt."],
       ["Empire State Building", "New York", "1931 fertig und 40 Jahre lang das höchste Gebäude der Welt."],
       ["The Shard", "London", "Glasspitze an der Themse, 310 Meter hoch."],
       ["Taipei 101", "Taipeh", "Ein Pendel im Inneren dämpft Taifune und Erdbeben."],
       ["Petronas Towers", "Kuala Lumpur", "Zwillingstürme, verbunden durch eine Brücke im 41. Stock."],
       ["Commerzbank-Tower", "Frankfurt", "Höchstes Hochhaus Deutschlands, 259 Meter."],
       ["Willis Tower", "Chicago", "Hieß bis 2009 Sears Tower."],
       ["Lotte World Tower", "Seoul", "555 Meter, höchstes Gebäude Südkoreas."],
       ["Shanghai Tower", "Shanghai", "632 Meter, die gedrehte Fassade bricht den Wind."],
       ["Torre Agbar", "Barcelona", "Turm in Form eines Geysirs, von Jean Nouvel."],
       ["Marina Bay Sands", "Singapur", "Drei Türme mit einem Schiff als Dachgarten."],
       ["Ostankino-Turm", "Moskau", "Fernsehturm von 1967, 540 Meter hoch."]]'::jsonb),

    ('geografie', 'staedte-fluesse-weltweit', 'Städte & ihre Flüsse',
     'An welchem Fluss liegt die Stadt?',
     'hard', 'Fluss', 'https://de.wikipedia.org/wiki/Fluss',
     '[["Kairo", "Nil", "Die Stadt wuchs an der Spitze des Deltas."],
       ["Bagdad", "Tigris", "762 als Rundstadt am Ufer gegründet."],
       ["Wuhan", "Jangtse", "Drei Städte am Zusammenfluss mit dem Han."],
       ["Buenos Aires", "Río de la Plata", "Trichtermündung, an der die Stadt 1580 neu gegründet wurde."],
       ["Washington", "Potomac", "Der Regierungssitz wurde 1790 an diesen Fluss gelegt."],
       ["New Orleans", "Mississippi", "Die Altstadt liegt in einer Flussschleife über dem Delta."],
       ["Montreal", "Sankt-Lorenz-Strom", "Stromschnellen stoppten hier früher die Schifffahrt."],
       ["Bangkok", "Chao Phraya", "Seine Kanäle brachten der Stadt den Beinamen Venedig des Ostens."],
       ["Delhi", "Yamuna", "Größter Nebenfluss des Ganges."],
       ["Hamburg", "Elbe", "Der Hafen liegt 100 Kilometer vor der Mündung."],
       ["Sankt Petersburg", "Newa", "Peter der Große ließ die Stadt 1703 im Delta anlegen."],
       ["Lyon", "Rhone", "Die Stadt liegt am Zusammenfluss mit der Saône."]]'::jsonb),

    ('geografie', 'einziges-nachbarland', 'Länder mit nur einem Nachbarn',
     'Welches ist das einzige Nachbarland?',
     'hard', 'Politische Grenze',
     'https://de.wikipedia.org/wiki/Politische_Grenze',
     '[["Portugal", "Spanien", "Die einzige Landgrenze ist eine der ältesten Europas."],
       ["Dänemark", "Deutschland", "Die einzige Landgrenze verläuft quer durch Schleswig."],
       ["Kanada", "USA", "Längste Landgrenze der Welt, rund 8900 Kilometer."],
       ["Südkorea", "Nordkorea", "Getrennt durch die entmilitarisierte Zone."],
       ["Irland", "Vereinigtes Königreich", "Die Grenze zu Nordirland ist die einzige des Landes."],
       ["Monaco", "Frankreich", "Der Zwergstaat ist ganz vom Nachbarn umschlossen."],
       ["San Marino", "Italien", "Älteste Republik der Welt, mitten im Nachbarland."],
       ["Gambia", "Senegal", "Ein schmaler Streifen entlang des Flusses, sonst umschlossen."],
       ["Lesotho", "Südafrika", "Bergkönigreich, vollständig vom Nachbarn umgeben."],
       ["Osttimor", "Indonesien", "Teilt sich eine Insel mit dem Nachbarn."],
       ["Katar", "Saudi-Arabien", "Halbinsel im Persischen Golf mit nur einer Landgrenze."],
       ["Haiti", "Dominikanische Republik", "Teilt sich die Insel Hispaniola."]]'::jsonb),

    ('geografie', 'staedte-frueherer-name', 'Städte & ihre früheren Namen',
     'Wie hieß die Stadt früher?',
     'hard', 'Stadt', 'https://de.wikipedia.org/wiki/Stadt',
     '[["Istanbul", "Konstantinopel", "Davor Byzantion; der heutige Name gilt amtlich seit 1930."],
       ["Sankt Petersburg", "Leningrad", "So genannt zwischen 1924 und 1991."],
       ["Ho-Chi-Minh-Stadt", "Saigon", "1976 nach dem Staatsgründer umbenannt."],
       ["Mumbai", "Bombay", "1995 amtlich auf den Marathi-Namen umgestellt."],
       ["Chennai", "Madras", "1996 umbenannt, Hauptstadt von Tamil Nadu."],
       ["Jakarta", "Batavia", "Der Name aus der niederländischen Kolonialzeit."],
       ["Oslo", "Christiania", "Trug bis 1925 den Namen eines dänischen Königs."],
       ["Kaliningrad", "Königsberg", "Bis 1946 ostpreußische Stadt, Geburtsort Kants."],
       ["Harare", "Salisbury", "Bis 1982 nach einem britischen Premierminister benannt."],
       ["Kinshasa", "Léopoldville", "Bis 1966 nach dem belgischen König benannt."],
       ["Wolgograd", "Stalingrad", "So genannt zwischen 1925 und 1961."],
       ["Tokio", "Edo", "Sitz der Shogune, bis der Kaiser 1868 dorthin zog."]]'::jsonb),

    ('geografie', 'wasserfaelle-laender', 'Wasserfälle & Länder',
     'In welchem Land stürzt der Wasserfall?',
     'hard', 'Wasserfall', 'https://de.wikipedia.org/wiki/Wasserfall',
     '[["Salto Ángel", "Venezuela", "Höchster freifallender Wasserfall der Erde, 979 Meter."],
       ["Rheinfall", "Schweiz", "Größter Wasserfall Europas nach Wassermenge, bei Schaffhausen."],
       ["Gullfoss", "Island", "Der goldene Wasserfall auf der Route des Golden Circle."],
       ["Sutherland Falls", "Neuseeland", "580 Meter hoch, im Fiordland gelegen."],
       ["Jog Falls", "Indien", "Fällt in vier Strahlen über 250 Meter tief."],
       ["Tugela-Fälle", "Südafrika", "Stürzt in fünf Stufen von den Drakensbergen."],
       ["Krimmler Wasserfälle", "Österreich", "Höchste Wasserfälle des Landes, 385 Meter."],
       ["Yosemite Falls", "USA", "Höchster Wasserfall Nordamerikas, in Kalifornien."],
       ["Kaieteur", "Guyana", "Einer der größten einstufigen Wasserfälle der Erde."],
       ["Montmorency", "Kanada", "Höher als die Niagarafälle, bei Québec."],
       ["Vettisfossen", "Norwegen", "275 Meter freier Fall im Jotunheimen."],
       ["Cachoeira da Fumaça", "Brasilien", "Rauchfall genannt, weil der Wind das Wasser zerstäubt."]]'::jsonb),

    ('geografie', 'inselstaaten-ozeanien', 'Inselstaaten Ozeaniens',
     'Welche Stadt ist die Hauptstadt des Inselstaats?',
     'hard', 'Ozeanien', 'https://de.wikipedia.org/wiki/Ozeanien',
     '[["Fidschi", "Suva", "Größte Stadt des Südpazifiks, auf Viti Levu."],
       ["Samoa", "Apia", "Sterbeort von Robert Louis Stevenson."],
       ["Tonga", "Nuku''alofa", "Hauptstadt des einzigen Königreichs im Pazifik."],
       ["Vanuatu", "Port Vila", "Liegt auf der Insel Efate."],
       ["Salomonen", "Honiara", "Auf Guadalcanal, Schauplatz schwerer Kämpfe 1942."],
       ["Papua-Neuguinea", "Port Moresby", "Größte Stadt des Landes, an der Südküste."],
       ["Palau", "Ngerulmud", "Kleinste Hauptstadt der Welt nach Einwohnerzahl."],
       ["Marshallinseln", "Majuro", "Atoll aus mehr als 60 einzelnen Inselchen."],
       ["Kiribati", "Tarawa", "Atoll, Schauplatz einer schweren Schlacht 1943."],
       ["Nauru", "Yaren", "Der Inselstaat hat offiziell gar keine Hauptstadt."],
       ["Mikronesien", "Palikir", "Liegt auf der Insel Pohnpei."],
       ["Tuvalu", "Funafuti", "Atoll, dessen Landebahn zugleich Sportplatz ist."]]'::jsonb),

    ('geografie', 'karibik-hauptstaedte', 'Hauptstädte der Karibik',
     'Welche Stadt ist die Hauptstadt?',
     'hard', 'Karibik', 'https://de.wikipedia.org/wiki/Karibik',
     '[["Kuba", "Havanna", "Größte Stadt der Karibik, gegründet 1519."],
       ["Jamaika", "Kingston", "Geburtsstadt des Reggae."],
       ["Haiti", "Port-au-Prince", "2010 von einem schweren Erdbeben verwüstet."],
       ["Dominikanische Republik", "Santo Domingo", "Älteste dauerhaft bewohnte Europäerstadt Amerikas."],
       ["Bahamas", "Nassau", "Liegt auf der Insel New Providence."],
       ["Barbados", "Bridgetown", "Seit 2021 Hauptstadt einer Republik."],
       ["Trinidad und Tobago", "Port of Spain", "Bekannt für den größten Karneval der Karibik."],
       ["Puerto Rico", "San Juan", "Von einer spanischen Festungsanlage bewacht."],
       ["Grenada", "St. George''s", "Hafenstadt in einem alten Vulkankrater."],
       ["Saint Lucia", "Castries", "Liegt unterhalb der beiden Pitons."],
       ["Antigua und Barbuda", "St. John''s", "Mit dem historischen Marinehafen Nelsons."],
       ["Dominica", "Roseau", "Am Fuß eines Regenwaldgebirges."]]'::jsonb),

    ('geografie', 'osteuropa-hauptstaedte', 'Hauptstädte Osteuropas',
     'Welche Stadt ist die Hauptstadt des Landes?',
     'medium', 'Osteuropa', 'https://de.wikipedia.org/wiki/Osteuropa',
     '[["Rumänien", "Bukarest", "Mit dem Parlamentspalast, einem der größten Gebäude der Welt."],
       ["Bulgarien", "Sofia", "Eine der ältesten Städte Europas, unter dem Witoscha."],
       ["Serbien", "Belgrad", "Liegt am Zusammenfluss von Save und Donau."],
       ["Kroatien", "Zagreb", "Ober- und Unterstadt, verbunden durch eine Standseilbahn."],
       ["Slowenien", "Ljubljana", "Der Drache im Wappen bewacht die Brücke."],
       ["Slowakei", "Bratislava", "Einzige Hauptstadt, die an zwei Staaten grenzt."],
       ["Belarus", "Minsk", "Nach 1945 im Stil des sozialistischen Klassizismus aufgebaut."],
       ["Moldau", "Chisinau", "Zentrum eines bekannten Weinbaulands."],
       ["Albanien", "Tirana", "Die grauen Fassaden wurden ab 2000 bunt gestrichen."],
       ["Ukraine", "Kiew", "Mit der Sophienkathedrale aus dem 11. Jahrhundert."],
       ["Nordmazedonien", "Skopje", "Geburtsstadt von Mutter Teresa."],
       ["Bosnien und Herzegowina", "Sarajevo", "1984 Austragungsort der Olympischen Winterspiele."]]'::jsonb),

    ('geografie', 'zentralasien-hauptstaedte', 'Hauptstädte zwischen Kaukasus und Himalaya',
     'Welche Stadt ist die Hauptstadt des Landes?',
     'hard', 'Zentralasien', 'https://de.wikipedia.org/wiki/Zentralasien',
     '[["Kasachstan", "Astana", "1997 zur Hauptstadt gemacht, zwischenzeitlich Nur-Sultan genannt."],
       ["Usbekistan", "Taschkent", "Größte Stadt Zentralasiens, nach dem Beben 1966 neu gebaut."],
       ["Turkmenistan", "Aschgabat", "Bekannt für ihre weißen Marmorbauten."],
       ["Kirgisistan", "Bischkek", "Hieß zu Sowjetzeiten Frunse."],
       ["Tadschikistan", "Duschanbe", "Der Name bedeutet Montag, nach dem Markttag."],
       ["Afghanistan", "Kabul", "Liegt in einem Tal auf 1800 Metern Höhe."],
       ["Aserbaidschan", "Baku", "Hafenstadt am Kaspischen Meer, mit den Flame Towers."],
       ["Georgien", "Tiflis", "Liegt an der Kura, mit Schwefelbädern in der Altstadt."],
       ["Armenien", "Jerewan", "Blickt auf den Ararat, der heute in der Türkei liegt."],
       ["Nepal", "Kathmandu", "Liegt in einem Talkessel im Himalaya."],
       ["Bhutan", "Thimphu", "Hauptstadt ohne eine einzige Ampel."],
       ["Bangladesch", "Dhaka", "Eine der am dichtesten besiedelten Städte der Welt."]]'::jsonb),

    ('geografie', 'stadtteile-staedte', 'Stadtviertel & Städte',
     'In welcher Stadt liegt das Viertel?',
     'medium', 'Ortsteil', 'https://de.wikipedia.org/wiki/Ortsteil',
     '[["Manhattan", "New York", "Insel zwischen Hudson und East River."],
       ["Montmartre", "Paris", "Künstlerviertel auf dem Hügel unter Sacré-Cœur."],
       ["Kreuzberg", "Berlin", "Bekannt für den Karneval der Kulturen und den 1. Mai."],
       ["Copacabana", "Rio de Janeiro", "Strand mit dem Wellenmuster im Gehweg."],
       ["Ginza", "Tokio", "Teuerstes Einkaufsviertel des Landes."],
       ["Beverly Hills", "Los Angeles", "Eigene Stadt, ringsum von der Großstadt umschlossen."],
       ["Trastevere", "Rom", "Viertel jenseits des Tibers, mit engen Gassen."],
       ["Gràcia", "Barcelona", "Früher eigenes Dorf, nahe dem Park Güell."],
       ["Jordaan", "Amsterdam", "Grachtenviertel, früher Wohnort der Arbeiter."],
       ["Sankt Pauli", "Hamburg", "Viertel rund um die Reeperbahn."],
       ["Vesterbro", "Kopenhagen", "Ehemaliges Schlachthofviertel, heute Ausgehviertel."],
       ["Shoreditch", "London", "Viertel im Osten, bekannt für seine Streetart."]]'::jsonb),

    ('geografie', 'amtssprachen-laender', 'Länder & Amtssprachen',
     'Welche Sprache ist im Land Amtssprache?',
     'medium', 'Amtssprache', 'https://de.wikipedia.org/wiki/Amtssprache',
     '[["Brasilien", "Portugiesisch", "Einziges Land Amerikas mit dieser Amtssprache."],
       ["Suriname", "Niederländisch", "Erbe der Kolonialzeit, einzig in Südamerika."],
       ["Senegal", "Französisch", "Amtssprache neben Wolof als Verkehrssprache."],
       ["Belize", "Englisch", "Einziges Land Mittelamerikas mit dieser Amtssprache."],
       ["Kuba", "Spanisch", "Seit der Eroberung im 16. Jahrhundert."],
       ["Äthiopien", "Amharisch", "Wird in einer eigenen Silbenschrift geschrieben."],
       ["Iran", "Persisch", "Im Land selbst Farsi genannt."],
       ["Israel", "Hebräisch", "Im 20. Jahrhundert als Alltagssprache wiederbelebt."],
       ["Marokko", "Arabisch", "Amtssprache neben Tamazight seit 2011."],
       ["Tansania", "Swahili", "Verkehrssprache in weiten Teilen Ostafrikas."],
       ["Philippinen", "Filipino", "Beruht auf dem Tagalog, amtlich neben Englisch."],
       ["Kasachstan", "Kasachisch", "Wird von kyrillischer auf lateinische Schrift umgestellt."]]'::jsonb),

    ('geografie', 'zeitzonen-staedte', 'Städte & Zeitzonen',
     'In welcher Zonenzeit liegt die Stadt im Winter?',
     'hard', 'Zeitzone', 'https://de.wikipedia.org/wiki/Zeitzone',
     '[["London", "UTC+0", "Durch Greenwich verläuft der Nullmeridian."],
       ["Berlin", "UTC+1", "Mitteleuropäische Zeit."],
       ["Athen", "UTC+2", "Osteuropäische Zeit."],
       ["Moskau", "UTC+3", "Seit 2014 ganzjährig, ohne Sommerzeit."],
       ["Dubai", "UTC+4", "Golfstaatenzeit, ohne Zeitumstellung."],
       ["Karatschi", "UTC+5", "Ganz Pakistan nutzt eine einzige Zonenzeit."],
       ["Dhaka", "UTC+6", "Bangladesch verzichtet auf die Sommerzeit."],
       ["Bangkok", "UTC+7", "Indochinazeit."],
       ["Peking", "UTC+8", "Ganz China nutzt trotz seiner Breite eine Zeit."],
       ["Tokio", "UTC+9", "Japan kennt keine Sommerzeit."],
       ["Sydney", "UTC+10", "Ostaustralische Zeit, im Südsommer eine Stunde mehr."],
       ["Auckland", "UTC+12", "Eines der ersten Länder im neuen Tag."]]'::jsonb),

    ('geografie', 'grenzfluesse', 'Grenzflüsse',
     'Welche Länder trennt der Fluss?',
     'hard', 'Liste von Grenzflüssen',
     'https://de.wikipedia.org/wiki/Liste_von_Grenzfl%C3%BCssen',
     '[["Rio Grande", "USA und Mexiko", "Bildet die Grenze auf rund 2000 Kilometern."],
       ["Oder", "Deutschland und Polen", "Grenze seit 1945, zusammen mit der Neiße."],
       ["Amur", "Russland und China", "Einer der längsten Grenzflüsse der Welt."],
       ["Jordan", "Israel und Jordanien", "Fließt vom See Genezareth zum Toten Meer."],
       ["Drina", "Bosnien und Serbien", "Tiefe Schluchten, mit der Brücke von Višegrad."],
       ["Evros", "Griechenland und Türkei", "Auf Türkisch Meriç, mündet in die Ägäis."],
       ["Sambesi", "Sambia und Simbabwe", "Stürzt an der Grenze über die Victoriafälle."],
       ["Detroit River", "USA und Kanada", "Verbindet den Eriesee mit dem Huronsee."],
       ["Mosel", "Deutschland und Luxemburg", "Auf einem Abschnitt Grenze, mündet bei Koblenz."],
       ["Save", "Kroatien und Bosnien", "Fließt an Zagreb vorbei und mündet bei Belgrad."],
       ["Saluen", "Myanmar und Thailand", "Bildet abschnittsweise die Grenze im Bergland."]]'::jsonb),

    ('geografie', 'bahnstrecken-laender', 'Bahnstrecken & Länder',
     'In welchem Land fährt der Zug?',
     'medium', 'Eisenbahnstrecke',
     'https://de.wikipedia.org/wiki/Eisenbahnstrecke',
     '[["Transsibirische Eisenbahn", "Russland", "9288 Kilometer von Moskau nach Wladiwostok."],
       ["Glacier Express", "Schweiz", "Langsamster Schnellzug der Welt, Zermatt bis St. Moritz."],
       ["Rocky Mountaineer", "Kanada", "Panoramazug durch die Rocky Mountains."],
       ["Indian Pacific", "Australien", "Fährt quer durch die baumlose Nullarbor-Ebene."],
       ["Shinkansen", "Japan", "1964 zu den Olympischen Spielen eröffnet."],
       ["TGV", "Frankreich", "Hält seit 2007 den Schienenrekord von 574 km/h."],
       ["Blue Train", "Südafrika", "Luxuszug zwischen Pretoria und Kapstadt."],
       ["Darjeeling Himalayan Railway", "Indien", "Schmalspurbahn mit Spitzkehren, seit 1999 Welterbe."],
       ["Flåmbahn", "Norwegen", "Eine der steilsten Bahnen ohne Zahnrad."],
       ["Ferrocarril Central Andino", "Peru", "Eine der höchstgelegenen Bahnstrecken der Welt."],
       ["Semmeringbahn", "Österreich", "Erste Gebirgsbahn Europas, seit 1854 in Betrieb."],
       ["Jacobite", "Schottland", "Dampfzug über das Glenfinnan-Viadukt."]]'::jsonb),

    ('geografie', 'inselgruppen-laender', 'Inselgruppen & Länder',
     'Zu welchem Land gehört die Inselgruppe?',
     'medium', 'Archipel', 'https://de.wikipedia.org/wiki/Archipel',
     '[["Kanaren", "Spanien", "Vulkaninseln vor der Küste Afrikas."],
       ["Azoren", "Portugal", "Neun Inseln mitten im Atlantik."],
       ["Färöer", "Dänemark", "Autonome Inselgruppe im Nordatlantik."],
       ["Åland", "Finnland", "Schwedischsprachige, entmilitarisierte Inseln."],
       ["Lofoten", "Norwegen", "Steile Inselkette nördlich des Polarkreises."],
       ["Kykladen", "Griechenland", "Liegen im Kreis um die heilige Insel Delos."],
       ["Äolische Inseln", "Italien", "Vulkaninseln nördlich von Sizilien, mit Stromboli."],
       ["Kornaten", "Kroatien", "Karge Inseln in der Adria, heute Nationalpark."],
       ["Hebriden", "Schottland", "Inseln vor der Westküste, mit Skye."],
       ["Aleuten", "USA", "Inselkette zwischen Alaska und Kamtschatka."],
       ["Ryūkyū-Inseln", "Japan", "Kette bis fast nach Taiwan, mit Okinawa."],
       ["Juan-Fernández-Inseln", "Chile", "Schauplatz der Vorlage zu Robinson Crusoe."]]'::jsonb),

    ('geografie', 'talsperren-fluesse', 'Talsperren & Flüsse',
     'Welchen Fluss staut die Talsperre?',
     'hard', 'Talsperre', 'https://de.wikipedia.org/wiki/Talsperre',
     '[["Assuan-Staudamm", "Nil", "Staut den Nassersee, fertiggestellt 1970."],
       ["Drei-Schluchten-Damm", "Jangtse", "Größtes Wasserkraftwerk der Welt."],
       ["Hoover-Damm", "Colorado", "Staut den Lake Mead, gebaut in der Weltwirtschaftskrise."],
       ["Itaipú", "Paraná", "Gemeinschaftswerk von Brasilien und Paraguay."],
       ["Kariba", "Sambesi", "Staut einen der größten Stauseen der Erde."],
       ["Atatürk-Staudamm", "Euphrat", "Herzstück des südostanatolischen Projekts."],
       ["Sajano-Schuschensker Damm", "Jenissei", "Größte Talsperre Russlands."],
       ["Grand Coulee", "Columbia", "Größtes Kraftwerk der USA, im Bundesstaat Washington."],
       ["Bratsk", "Angara", "Stausee in Sibirien, so groß wie ein Binnenmeer."],
       ["Akosombo", "Volta", "Staut den nach Fläche größten künstlichen See der Erde."],
       ["Tarbela", "Indus", "Größte Talsperre Pakistans."],
       ["Guri", "Caroní", "Liefert einen Großteil des Stroms in Venezuela."]]'::jsonb),

    ('geografie', 'welterbe-laender', 'Welterbestätten & Länder',
     'In welchem Land liegt die Welterbestätte?',
     'medium', 'UNESCO-Welterbe',
     'https://de.wikipedia.org/wiki/UNESCO-Welterbe',
     '[["Angkor Wat", "Kambodscha", "Größte Tempelanlage der Welt, im 12. Jahrhundert erbaut."],
       ["Machu Picchu", "Peru", "Inkastadt auf 2400 Metern, 1911 bekannt gemacht."],
       ["Chichén Itzá", "Mexiko", "Maya-Stadt mit der Pyramide des Kukulcán."],
       ["Stonehenge", "Vereinigtes Königreich", "Steinkreis aus der Jungsteinzeit in Wiltshire."],
       ["Persepolis", "Iran", "Residenz der Perserkönige, von Alexander verbrannt."],
       ["Timbuktu", "Mali", "Lehmmoscheen und Handschriften am Rand der Sahara."],
       ["Lalibela", "Äthiopien", "Elf Kirchen, aus dem Fels herausgeschlagen."],
       ["Borobudur", "Indonesien", "Größte buddhistische Tempelanlage, auf Java."],
       ["Bagan", "Myanmar", "Ebene mit Tausenden Pagoden am Irrawaddy."],
       ["Mesa Verde", "USA", "Felsensiedlungen der Pueblo-Kultur in Colorado."],
       ["Meteora", "Griechenland", "Klöster auf Felsnadeln in Thessalien."],
       ["Mont-Saint-Michel", "Frankreich", "Klosterberg, den die Flut zur Insel macht."]]'::jsonb),

    ('geografie', 'hauptstaedte-nordwesteuropa', 'Hauptstädte Nord- und Westeuropas',
     'Welche Stadt ist die Hauptstadt des Landes?',
     'medium', 'Nordeuropa', 'https://de.wikipedia.org/wiki/Nordeuropa',
     '[["Schweden", "Stockholm", "Auf 14 Inseln zwischen Mälarsee und Ostsee."],
       ["Norwegen", "Oslo", "Am Ende des Oslofjords, mit dem Holmenkollen."],
       ["Dänemark", "Kopenhagen", "Über den Öresund mit Schweden verbunden."],
       ["Finnland", "Helsinki", "Weiße Domkirche über dem Hafen."],
       ["Island", "Reykjavík", "Nördlichste Hauptstadt der Welt."],
       ["Estland", "Tallinn", "Hansestadt mit fast vollständig erhaltener Stadtmauer."],
       ["Lettland", "Riga", "Größte Stadt des Baltikums, bekannt für Jugendstil."],
       ["Litauen", "Vilnius", "Barocke Altstadt, seit 1994 Welterbe."],
       ["Irland", "Dublin", "An der Mündung des Liffey, gegründet von Wikingern."],
       ["Vereinigtes Königreich", "London", "Sitz von Krone und Parlament an der Themse."],
       ["Niederlande", "Amsterdam", "Hauptstadt, während die Regierung in Den Haag sitzt."],
       ["Belgien", "Brüssel", "Sitz der EU-Kommission und der NATO."]]'::jsonb),

    ('geografie', 'berge-laender', 'Berühmte Berge & Länder',
     'In welchem Land steht der Berg?',
     'medium', 'Berg', 'https://de.wikipedia.org/wiki/Berg',
     '[["Matterhorn", "Schweiz", "Pyramide über Zermatt, 1865 erstbestiegen."],
       ["Kilimandscharo", "Tansania", "Höchster Berg Afrikas, mit schrumpfendem Gletscher."],
       ["Denali", "USA", "Höchster Berg Nordamerikas, in Alaska."],
       ["Tafelberg", "Südafrika", "Flache Bergkulisse über Kapstadt."],
       ["K2", "Pakistan", "Zweithöchster Berg der Erde, im Karakorum."],
       ["Mount Kenya", "Kenia", "Erloschener Vulkan fast auf dem Äquator."],
       ["Zugspitze", "Deutschland", "Höchster Berg des Landes, 2962 Meter."],
       ["Großglockner", "Österreich", "Höchster Berg des Landes, mit der Pasterze."],
       ["Olymp", "Griechenland", "Sitz der Götter der antiken Mythologie."],
       ["Ararat", "Türkei", "Vulkan, an dem die Arche Noah gestrandet sein soll."],
       ["Mont Ventoux", "Frankreich", "Kahler Gipfel in der Provence, gefürchtet bei Radrennen."],
       ["Ben Nevis", "Schottland", "Höchster Berg der Britischen Inseln."]]'::jsonb),

    ('geografie', 'haefen-laender', 'Große Häfen & Länder',
     'In welchem Land liegt der Hafen?',
     'medium', 'Hafen', 'https://de.wikipedia.org/wiki/Hafen',
     '[["Rotterdam", "Niederlande", "Größter Hafen Europas, an der Maasmündung."],
       ["Shanghai", "China", "Größter Containerhafen der Welt."],
       ["Hamburg", "Deutschland", "Tor zur Welt, 100 Kilometer stromauf der Nordsee."],
       ["Antwerpen", "Belgien", "Zweitgrößter Hafen Europas, an der Schelde."],
       ["Piräus", "Griechenland", "Hafen der Hauptstadt, seit der Antike genutzt."],
       ["Busan", "Südkorea", "Größter Hafen des Landes, im Südosten."],
       ["Santos", "Brasilien", "Größter Kaffeeumschlagplatz der Welt."],
       ["Durban", "Südafrika", "Größter Hafen des afrikanischen Kontinents."],
       ["Valencia", "Spanien", "Wichtigster Mittelmeerhafen des Landes."],
       ["Felixstowe", "Vereinigtes Königreich", "Größter Containerhafen des Landes, in Suffolk."],
       ["Le Havre", "Frankreich", "An der Seinemündung, nach 1945 neu aufgebaut."],
       ["Vancouver", "Kanada", "Größter Hafen des Landes, am Pazifik."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
)

insert into items (quiz_id, category_id, label, position, explanation)
select f.quiz_id, c.id, f.answer, f.position, f.explanation
  from flat f
  join new_categories c
    on c.quiz_id = f.quiz_id
   and c.label = f.label;
