-- Geografie, file 3. Twenty questions, medium and hard.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs, fakes) as (
    values

    ('geografie', 'extreme-der-erde', 'Extreme der Erde',
     'Welcher Ort hält diesen Rekord?',
     'hard', 'Geographie', 'https://de.wikipedia.org/wiki/Geographie',
     '[["Tiefster Punkt an Land", "Totes Meer", "Über 400 Meter unter dem Meeresspiegel."],
       ["Tiefste Stelle im Meer", "Marianengraben", "Fast elf Kilometer unter der Oberfläche."],
       ["Kältester dauerhaft bewohnter Ort", "Oimjakon", "Bis unter minus 60 Grad gemessen."],
       ["Heißeste je gemessene Lufttemperatur", "Death Valley", "56,7 Grad im Jahr 1913."],
       ["Größte Insel der Erde", "Grönland", "Australien zählt bereits als Kontinent."],
       ["Größter See nach Fläche", "Kaspisches Meer", "Ein See, obwohl er Meer heißt."],
       ["Größte Wüste der Erde", "Antarktis", "Wüste heißt trocken, nicht heiß."],
       ["Höchstgelegene Stadt", "La Rinconada", "Goldgräberort in über 5000 Metern Höhe."],
       ["Größter Wasserfall nach Menge", "Inga-Fälle", "Am Kongo, mit gewaltiger Durchflussmenge."],
       ["Regenreichster bewohnter Ort", "Mawsynram", "Über elf Meter Niederschlag im Jahr."],
       ["Windigster Kontinent", "Antarktika", "Fallwinde erreichen Orkanstärke."],
       ["Längster Fluss", "Nil", "Der Vergleich mit dem Amazonas wird bis heute geführt."]]'::jsonb,
     '[["Atacama", "Der trockenste Ort der Erde, aber kein Rekord auf diesem Brett."],
       ["Mount Everest", "Der höchste Berg, und danach fragt hier keine Zeile."]]'::jsonb),

    ('geografie', 'laenderrekorde', 'Länderrekorde',
     'Welches Land ist gemeint?',
     'hard', 'Staat', 'https://de.wikipedia.org/wiki/Staat',
     '[["Kleinster Staat der Welt", "Vatikanstadt", "Rund 0,44 Quadratkilometer."],
       ["Größter Staat nach Fläche", "Russland", "Erstreckt sich über elf Zeitzonen."],
       ["Längste Küstenlinie", "Kanada", "Mit allen Inseln über 200000 Kilometer."],
       ["Land mit den meisten Inseln", "Schweden", "Über 200000 gezählte Inseln."],
       ["Land ohne einen einzigen Fluss", "Saudi-Arabien", "Nur zeitweise wasserführende Wadis."],
       ["Jüngster anerkannter Staat", "Südsudan", "Unabhängig seit 2011."],
       ["Meistbesuchtes Reiseland", "Frankreich", "Seit Jahrzehnten an der Spitze."],
       ["Am dichtesten besiedelt", "Monaco", "Über 19000 Menschen je Quadratkilometer."],
       ["Am dünnsten besiedelt", "Mongolei", "Weniger als zwei Menschen je Quadratkilometer."],
       ["Staat auf zwei Kontinenten", "Türkei", "Die Grenze verläuft durch Istanbul."],
       ["Höchstgelegene Hauptstadt", "Bolivien", "Der Regierungssitz liegt auf 3600 Metern."],
       ["Land mit den meisten Nachbarn", "China", "Vierzehn Länder grenzen an."]]'::jsonb,
     '[["Nauru", "Der kleinste Inselstaat, aber kein Rekord in dieser Liste."],
       ["Indien", "Das bevölkerungsreichste Land, und danach wird hier nicht gefragt."]]'::jsonb),

    ('geografie', 'flaggen-merkmale', 'Flaggen & ihre Besonderheiten',
     'Zu welchem Land gehört die Flagge?',
     'medium', 'Flagge', 'https://de.wikipedia.org/wiki/Flagge',
     '[["Einzige nicht rechteckige Nationalflagge", "Nepal", "Zwei übereinanderliegende Wimpel."],
       ["Ahornblatt in der Mitte", "Kanada", "Seit 1965 die Nationalflagge."],
       ["Zeder als Wappenbaum", "Libanon", "Der Baum steht schon in der Bibel."],
       ["Ein Sturmgewehr im Wappen", "Mosambik", "Zusammen mit Hacke und Buch."],
       ["Weißer Drache auf der Flagge", "Bhutan", "Der Donnerdrache hält Juwelen in den Klauen."],
       ["Halbmond und Stern", "Türkei", "Der Ursprung wird bis in die Antike zurückgeführt."],
       ["Rote Scheibe auf Weiß", "Japan", "Die Sonne als einziges Motiv."],
       ["Landkarte auf der Flagge", "Zypern", "Dazu zwei Olivenzweige."],
       ["Sternenhimmel mit Schriftband", "Brasilien", "Der Himmel über Rio am Tag der Republik."],
       ["Quadratische Nationalflagge", "Schweiz", "Nur zur See wird sie rechteckig geführt."],
       ["Löwe mit Schwert", "Sri Lanka", "Dazu Streifen für die Minderheiten."],
       ["Zwei Sterne und ein Kreuz", "Neuseeland", "Das Kreuz des Südens am Nachthimmel."]]'::jsonb,
     '[["Südkorea", "Das Yin-Yang-Zeichen wäre das Merkmal, es fehlt auf dem Brett."],
       ["Bhutan und Wales", "Beide führen Drachen, gefragt ist hier aber nur einer."]]'::jsonb),

    ('geografie', 'enklaven', 'Enklaven & Exklaven',
     'Zu welchem Land gehört das Gebiet?',
     'hard', 'Enklave', 'https://de.wikipedia.org/wiki/Enklave',
     '[["Kaliningrad", "Russland", "Vom Mutterland durch Litauen und Polen getrennt."],
       ["Büsingen am Hochrhein", "Deutschland", "Vollständig von der Schweiz umschlossen."],
       ["Campione d''Italia", "Italien", "Liegt am Luganersee, mitten im Tessin."],
       ["Baarle-Hertog", "Belgien", "Die Grenze verläuft durch einzelne Häuser."],
       ["Llívia", "Spanien", "Ein Städtchen mitten in Frankreich."],
       ["Nachitschewan", "Aserbaidschan", "Nur über Iran oder die Türkei erreichbar."],
       ["Alaska", "USA", "Durch Kanada vom Rest des Landes getrennt."],
       ["Cabinda", "Angola", "Durch einen Streifen der Nachbarn abgetrennt."],
       ["Musandam", "Oman", "An der Meerenge von Hormus."],
       ["Gibraltar", "Vereinigtes Königreich", "Seit 1713 britisch."],
       ["Kleinwalsertal", "Österreich", "Nur über Deutschland auf der Straße erreichbar."]]'::jsonb,
     '[["Frankreich", "Kein Gebiet auf diesem Brett gehört dazu."],
       ["Indien", "Die Enklaven in Bangladesch waren indisch, sie stehen hier nicht."]]'::jsonb),

    ('geografie', 'gebirgspaesse', 'Gebirgspässe & Straßen',
     'In welchem Land liegt der Pass?',
     'hard', 'Gebirgspass', 'https://de.wikipedia.org/wiki/Gebirgspass',
     '[["Gotthardpass", "Schweiz", "Seit dem Mittelalter der wichtigste Alpenübergang."],
       ["Stilfser Joch", "Italien", "48 nummerierte Kehren auf der Nordrampe."],
       ["Col du Galibier", "Frankreich", "Legendärer Anstieg der Tour de France."],
       ["Großglockner-Hochalpenstraße", "Österreich", "In den 1930er Jahren gebaut, mautpflichtig."],
       ["Transfăgărășan", "Rumänien", "Unter Ceaușescu quer durch die Karpaten gesprengt."],
       ["Trollstigen", "Norwegen", "Elf Haarnadelkurven an der Steilwand."],
       ["Khyberpass", "Pakistan", "Über Jahrtausende ein Tor nach Südasien."],
       ["Chang La", "Indien", "Einer der höchsten befahrbaren Pässe."],
       ["Sani Pass", "Lesotho", "Nur mit Geländewagen zu befahren."],
       ["Los Caracoles", "Chile", "Serpentinen hinunter aus den Anden."],
       ["Milford Road", "Neuseeland", "Führt durch einen Tunnel im Fels zum Fjord."],
       ["Wakhan-Korridor", "Afghanistan", "Ein schmaler Streifen zwischen zwei Großmächten."]]'::jsonb,
     '[["Peru", "Der Ticlio läge dort, und der Pass fehlt auf dem Brett."],
       ["Georgien", "Die Heerstraße über den Kaukasus steht nicht in dieser Liste."]]'::jsonb),

    ('geografie', 'meere-besonderheiten', 'Meere & ihre Besonderheiten',
     'Was zeichnet das Gewässer aus?',
     'hard', 'Meer', 'https://de.wikipedia.org/wiki/Meer',
     '[["Totes Meer", "Extrem hoher Salzgehalt", "Man kann darin nicht untergehen."],
       ["Sargassosee", "Meer ohne Küsten", "Begrenzt nur von Strömungen."],
       ["Schwarzes Meer", "Sauerstofffreie Tiefe", "Unter 150 Metern lebt fast nichts."],
       ["Ostsee", "Brackwasser mit geringem Salzgehalt", "Fast ein Binnenmeer."],
       ["Rotes Meer", "Sehr warm und salzreich", "Kaum Zuflüsse, starke Verdunstung."],
       ["Kaspisches Meer", "Größter See der Erde", "Heißt Meer, ist aber vom Ozean getrennt."],
       ["Aralsee", "Fast vollständig ausgetrocknet", "Bewässerung leitete die Zuflüsse um."],
       ["Weddellmeer", "Klarstes Meerwasser", "Sichtweite von über siebzig Metern."],
       ["Mittelmeer", "Fast vom Ozean abgeschnitten", "Verdunstet mehr, als ihm zufließt."],
       ["Marmarameer", "Zwischen zwei Meerengen", "Verbindet Ägäis und Schwarzes Meer."],
       ["Beringmeer", "Reiche Fischgründe", "Im Winter zu großen Teilen vereist."],
       ["Karibisches Meer", "Zweitgrößtes Korallenriff", "Nach dem Great Barrier Reef."]]'::jsonb,
     '[["Ganz ohne Gezeiten", "Auf kein Gewässer in dieser Liste trifft das zu."],
       ["Tiefste Stelle aller Ozeane", "Das wäre der Pazifik, der hier nicht steht."]]'::jsonb),

    ('geografie', 'fernstrassen', 'Berühmte Straßen & Länder',
     'Wo verläuft die Strecke?',
     'medium', 'Fernstraße', 'https://de.wikipedia.org/wiki/Fernstra%C3%9Fe',
     '[["Route 66", "USA", "Von Chicago nach Santa Monica."],
       ["Great Ocean Road", "Australien", "Von heimgekehrten Soldaten gebaut."],
       ["Ring Road", "Island", "Führt einmal um die ganze Insel."],
       ["Garden Route", "Südafrika", "Zwischen Küste und Bergen entlang."],
       ["Karakorum Highway", "Pakistan", "Höchste asphaltierte Grenzstraße der Welt."],
       ["Romantische Straße", "Deutschland", "Von Würzburg nach Füssen."],
       ["North Coast 500", "Schottland", "Rundkurs durch die nördlichen Highlands."],
       ["Amalfitana", "Italien", "Schmale Küstenstraße über dem Meer."],
       ["Ruta 40", "Argentinien", "Über 5000 Kilometer entlang der Anden."],
       ["Atlantikstraße", "Norwegen", "Springt über Brücken von Insel zu Insel."],
       ["Panamericana", "Amerika", "Unterbrochen nur vom Darién-Dschungel."]]'::jsonb,
     '[["Kanada", "Der Icefields Parkway führte dorthin, er fehlt auf dem Brett."],
       ["Vietnam", "Der Hai-Van-Pass steht nicht in dieser Liste."]]'::jsonb),

    ('geografie', 'vulkanausbrueche', 'Vulkanausbrüche & Jahre',
     'Wann brach der Vulkan aus?',
     'hard', 'Vulkanausbruch',
     'https://de.wikipedia.org/wiki/Vulkanausbruch',
     '[["Santorin", "Um 1600 v. Chr.", "Der Ausbruch traf die minoische Kultur."],
       ["Vesuv", "79 n. Chr.", "Pompeji und Herculaneum verschwanden unter Asche."],
       ["Laki", "1783", "Die Folgen verschlechterten Europas Ernten jahrelang."],
       ["Tambora", "1815", "Das Folgejahr ging als Jahr ohne Sommer ein."],
       ["Krakatau", "1883", "Die Explosion war Tausende Kilometer weit hörbar."],
       ["Mount St. Helens", "1980", "Die halbe Bergflanke rutschte ab."],
       ["Nevado del Ruiz", "1985", "Schlammströme verschütteten eine ganze Stadt."],
       ["Pinatubo", "1991", "Kühlte weltweit die Temperaturen um ein halbes Grad."],
       ["Eyjafjallajökull", "2010", "Legte den europäischen Flugverkehr lahm."],
       ["Hunga Tonga", "2022", "Die Druckwelle umrundete mehrfach die Erde."]]'::jsonb,
     '[["1902", "Der Montagne Pelée brach damals aus, er fehlt auf dem Brett."],
       ["1963", "Der Agung auf Bali, und der steht nicht in dieser Liste."]]'::jsonb),

    ('geografie', 'erdbeben-orte', 'Schwere Erdbeben & Orte',
     'Wo ereignete sich das Beben?',
     'hard', 'Erdbeben', 'https://de.wikipedia.org/wiki/Erdbeben',
     '[["Beben von 1755", "Lissabon", "Es erschütterte auch das Weltbild der Aufklärung."],
       ["Beben von 1906", "San Francisco", "Der anschließende Brand richtete den größten Schaden an."],
       ["Kantō-Beben 1923", "Tokio", "Große Teile der Stadt brannten nieder."],
       ["Stärkstes je gemessenes Beben", "Chile", "Magnitude 9,5 im Jahr 1960."],
       ["Beben von 1976", "Tangshan", "Eine Industriestadt wurde fast ausgelöscht."],
       ["Seebeben von 2004", "Sumatra", "Der Tsunami erreichte Länder rund um den Indischen Ozean."],
       ["Beben von 2010", "Haiti", "Die Hauptstadt lag in Trümmern."],
       ["Tōhoku-Beben 2011", "Japan", "Der Tsunami führte zur Reaktorkatastrophe."],
       ["Beben von 1985", "Mexiko-Stadt", "Der weiche Seeboden verstärkte die Wellen."],
       ["Beben von 2023", "Türkei", "Zwei schwere Stöße innerhalb weniger Stunden."]]'::jsonb,
     '[["Nepal", "Das Beben von 2015 traf Kathmandu, es fehlt auf dem Brett."],
       ["Armenien", "Spitak wurde 1988 zerstört, das Beben steht hier nicht."]]'::jsonb),

    ('geografie', 'mehrsprachige-laender', 'Mehrsprachige Länder',
     'Wie steht es dort um die Sprachen?',
     'hard', 'Mehrsprachigkeit',
     'https://de.wikipedia.org/wiki/Mehrsprachigkeit',
     '[["Schweiz", "Vier Landessprachen", "Rätoromanisch ist die kleinste davon."],
       ["Belgien", "Drei Amtssprachen", "Niederländisch, Französisch und Deutsch."],
       ["Kanada", "Zwei Amtssprachen", "Bundesbehörden arbeiten in beiden."],
       ["Südafrika", "Zwölf Amtssprachen", "Seit 2023 gehört auch die Gebärdensprache dazu."],
       ["Indien", "Zweiundzwanzig anerkannte Sprachen", "Hindi und Englisch für den Bund."],
       ["Singapur", "Vier Amtssprachen", "Englisch ist die gemeinsame Verkehrssprache."],
       ["Paraguay", "Guaraní gleichberechtigt", "Eine indigene Sprache als Amtssprache."],
       ["Irland", "Irisch vor Englisch genannt", "Als erste Amtssprache in der Verfassung."],
       ["Finnland", "Finnisch und Schwedisch", "Beide mit gleichem Rang."],
       ["Luxemburg", "Drei Sprachen im Alltag", "Luxemburgisch, Französisch, Deutsch."],
       ["Malta", "Maltesisch und Englisch", "Maltesisch ist die einzige semitische EU-Amtssprache."],
       ["Bolivien", "Über dreißig Amtssprachen", "Alle indigenen Sprachen sind anerkannt."]]'::jsonb,
     '[["Elf Amtssprachen bis 2023", "Südafrika hatte so viele, gefragt ist hier der heutige Stand."],
       ["Nur eine Amtssprache", "Kein Land auf diesem Brett steht dafür."]]'::jsonb),

    ('geografie', 'ortsnamen-bedeutung', 'Namen & ihre Bedeutung',
     'Was bedeutet der Name ursprünglich?',
     'hard', 'Ortsname', 'https://de.wikipedia.org/wiki/Ortsname',
     '[["Australien", "Südland", "Von terra australis, dem vermuteten Südkontinent."],
       ["Sierra Leone", "Löwengebirge", "Portugiesische Seefahrer hörten Donner wie Gebrüll."],
       ["Costa Rica", "Reiche Küste", "Der erhoffte Reichtum blieb aus."],
       ["Puerto Rico", "Reicher Hafen", "Ursprünglich der Name der Hafenstadt."],
       ["Singapur", "Löwenstadt", "Aus dem Sanskrit, obwohl es dort keine Löwen gab."],
       ["Buenos Aires", "Gute Lüfte", "Nach einer Schutzheiligen der Seefahrer."],
       ["Rio de Janeiro", "Januarfluss", "Die Bucht wurde für eine Flussmündung gehalten."],
       ["Montenegro", "Schwarzer Berg", "Nach den dunklen Wäldern am Lovćen."],
       ["Island", "Eisland", "Ein Siedler benannte es nach Treibeis im Fjord."],
       ["Sahara", "Wüste", "Der Name bedeutet schlicht das, was sie ist."],
       ["Kap Verde", "Grünes Kap", "Benannt nach der Küste Senegals, nicht nach den Inseln."],
       ["Ecuador", "Äquator", "Die Linie verläuft mitten durch das Land."]]'::jsonb,
     '[["Wüstenland", "Auf keinen Namen in dieser Liste trifft das zu."],
       ["Land des Feuers", "Aserbaidschan wäre gemeint, und das fehlt auf dem Brett."]]'::jsonb),

    ('geografie', 'stadt-beinamen', 'Städte & ihre Beinamen',
     'Welche Stadt trägt den Beinamen?',
     'hard', 'Beiname', 'https://de.wikipedia.org/wiki/Beiname',
     '[["Die Ewige Stadt", "Rom", "Schon in der Antike so genannt."],
       ["Big Apple", "New York", "Der Ausdruck stammt aus der Jazzszene."],
       ["Stadt der hundert Türme", "Prag", "Tatsächlich sind es weit mehr."],
       ["Perle des Orients", "Hongkong", "Vom Hafen aus gesehen bei Nacht."],
       ["Windy City", "Chicago", "Gemeint waren angeblich auch die Politiker."],
       ["Serenissima", "Venedig", "Die Durchlauchtigste, aus der Zeit der Republik."],
       ["Stadt der Engel", "Los Angeles", "Der vollständige Gründungsname war weit länger."],
       ["Elbflorenz", "Dresden", "Der Vergleich stammt von Reisenden des 18. Jahrhunderts."],
       ["Venedig des Nordens", "Stockholm", "Auf vierzehn Inseln erbaut."],
       ["Athen des Nordens", "Edinburgh", "Wegen der klassizistischen Bauten."],
       ["Stadt der Bruderliebe", "Philadelphia", "Der Name bedeutet genau das."],
       ["Bierhauptstadt der Welt", "München", "Wegen des Oktoberfests und der Brauereien."]]'::jsonb,
     '[["Paris", "Die Stadt der Liebe, und sie steht nicht auf dem Brett."],
       ["Wien", "Die Stadt der Musik fehlt in dieser Liste."]]'::jsonb),

    ('geografie', 'kartenprojektionen', 'Kartenprojektionen',
     'Was leistet die Projektion?',
     'hard', 'Kartennetzentwurf',
     'https://de.wikipedia.org/wiki/Kartennetzentwurf',
     '[["Mercator", "Winkeltreu für die Navigation", "Grönland erscheint dabei riesig."],
       ["Peters-Projektion", "Flächentreu", "Länder nahe dem Äquator wirken gestreckt."],
       ["Robinson", "Kompromiss ohne Treue", "Sieht ausgewogen aus, ist aber nirgends exakt."],
       ["Azimutalprojektion", "Blick vom Pol aus", "Grundlage des UN-Emblems."],
       ["Mollweide", "Ellipse mit flächentreuer Fläche", "Beliebt für Weltkarten in Atlanten."],
       ["Dymaxion", "Erde als aufgefaltetes Polyeder", "Von Buckminster Fuller entworfen."],
       ["Winkel-Tripel", "Ausgleich dreier Verzerrungen", "Standard bei National Geographic."],
       ["Gnomonische Projektion", "Großkreise werden Geraden", "Für die Flugroutenplanung nützlich."],
       ["Sinusoidalprojektion", "Flächentreu mit gekrümmten Rändern", "Früh in Atlanten benutzt."],
       ["Stereografische Projektion", "Winkeltreu vom Gegenpol", "Wird in der Kristallografie genutzt."]]'::jsonb,
     '[["Zeigt die Erde als Scheibe", "Keine Projektion auf diesem Brett tut das."],
       ["Längentreu in jede Richtung", "Eine solche Karte gibt es nicht."]]'::jsonb),

    ('geografie', 'monarchien-titel', 'Monarchien & Titel',
     'Wie heißt das Staatsoberhaupt dort?',
     'hard', 'Monarchie', 'https://de.wikipedia.org/wiki/Monarchie',
     '[["Japan", "Tennō", "Der einzige Kaiser der Welt."],
       ["Vatikanstadt", "Papst", "Wahlmonarchie auf Lebenszeit."],
       ["Monaco", "Fürst", "Aus dem Haus Grimaldi."],
       ["Luxemburg", "Großherzog", "Einziges Großherzogtum der Welt."],
       ["Katar", "Emir", "Aus der Familie al-Thani."],
       ["Oman", "Sultan", "Der Titel ist dort seit Jahrhunderten üblich."],
       ["Andorra", "Zwei Kofürsten", "Ein Bischof und der französische Präsident."],
       ["Malaysia", "Gewählter König", "Neun Sultane wechseln sich alle fünf Jahre ab."],
       ["Bhutan", "Drachenkönig", "Der Titel lautet Druk Gyalpo."],
       ["Eswatini", "Ngwenyama", "Der Titel bedeutet Löwe."],
       ["Vereinigtes Königreich", "König", "Zugleich Oberhaupt mehrerer Commonwealth-Staaten."],
       ["Liechtenstein", "Regierender Fürst", "Mit ungewöhnlich weitreichenden Rechten."]]'::jsonb,
     '[["Schah", "Der Titel im Iran, der heute keine Monarchie mehr ist."],
       ["Zar", "Ein Titel, den kein Staat auf diesem Brett führt."]]'::jsonb),

    ('geografie', 'naturwunder', 'Naturwunder & Länder',
     'In welchem Land liegt das Naturwunder?',
     'medium', 'UNESCO-Welterbe',
     'https://de.wikipedia.org/wiki/UNESCO-Welterbe',
     '[["Grand Canyon", "USA", "Der Colorado hat sich fast zwei Kilometer tief gegraben."],
       ["Great Barrier Reef", "Australien", "Aus dem Weltall sichtbar."],
       ["Halong-Bucht", "Vietnam", "Tausende Kalksteinfelsen im Meer."],
       ["Komodo", "Indonesien", "Heimat der größten lebenden Echse."],
       ["Puerto-Princesa-Fluss", "Philippinen", "Ein Fluss, der unterirdisch ins Meer mündet."],
       ["Vulkan Parícutin", "Mexiko", "Wuchs ab 1943 aus einem Maisfeld."],
       ["Bucht von Rio de Janeiro", "Brasilien", "Zwischen Zuckerhut und Corcovado."],
       ["Sundarbans-Mangroven", "Bangladesch", "Der Wald wandert mit den Gezeiten."],
       ["Giant''s Causeway", "Nordirland", "Vierzigtausend Basaltsäulen."],
       ["Salar de Uyuni", "Bolivien", "Größte Salzpfanne der Erde, spiegelglatt bei Regen."],
       ["Sokotra", "Jemen", "Ein Drittel der Pflanzen wächst nur dort."],
       ["Pamukkale", "Türkei", "Weiße Kalkterrassen mit warmem Wasser."]]'::jsonb,
     '[["Sambia", "Die Victoriafälle lägen dort, sie fehlen auf dem Brett."],
       ["Neuseeland", "Der Milford Sound steht nicht in dieser Liste."]]'::jsonb),

    ('geografie', 'plattentektonik', 'Plattentektonik',
     'Wo zeigt sich das?',
     'hard', 'Plattentektonik',
     'https://de.wikipedia.org/wiki/Plattentektonik',
     '[["San-Andreas-Verwerfung", "Kalifornien", "Zwei Platten schieben sich aneinander vorbei."],
       ["Ostafrikanischer Graben", "Kenia", "Der Kontinent reißt langsam auseinander."],
       ["Mittelatlantischer Rücken über Wasser", "Island", "Die Insel wächst jedes Jahr auseinander."],
       ["Feuerring", "Pazifik", "Rund um den Ozean häufen sich Beben und Vulkane."],
       ["Auffaltung durch Kollision", "Himalaya", "Indien schiebt sich unter Asien."],
       ["Subduktion unter einen Kontinent", "Anden", "Ozeanplatte taucht unter Südamerika ab."],
       ["Grabenbruch in Mitteleuropa", "Oberrheingraben", "Mit vulkanischen Spuren am Kaiserstuhl."],
       ["Verwerfung im Nahen Osten", "Totes Meer", "Der tiefste Landpunkt liegt an dieser Naht."],
       ["Tiefseegraben vor der Küste", "Japan", "Hier entstand das Beben von 2011."],
       ["Gebirge aus zwei Kontinenten", "Alpen", "Afrika drückt gegen Europa."]]'::jsonb,
     '[["Kamtschatka", "Auch dort schiebt sich Kruste unter Kruste, hier steht es nicht."],
       ["Mittelozeanischer Rücken unter Wasser", "Gefragt ist die Stelle, an der er herausragt."]]'::jsonb),

    ('geografie', 'deutsche-fluesse-staedte', 'Deutsche Flüsse & Städte',
     'An welchem Fluss liegt die Stadt?',
     'medium', 'Fluss', 'https://de.wikipedia.org/wiki/Fluss',
     '[["München", "Isar", "Der Fluss wurde in der Stadt renaturiert."],
       ["Frankfurt am Main", "Main", "Der Name der Stadt nennt den Fluss mit."],
       ["Heidelberg", "Neckar", "Die Alte Brücke ist ihr Wahrzeichen."],
       ["Dresden", "Elbe", "Das Elbtal war zeitweise Welterbe."],
       ["Bremen", "Weser", "Der Hafen liegt flussabwärts in Bremerhaven."],
       ["Trier", "Mosel", "Älteste Stadt Deutschlands, römisch gegründet."],
       ["Regensburg", "Donau", "Mit der Steinernen Brücke aus dem 12. Jahrhundert."],
       ["Essen", "Ruhr", "Der Baldeneysee ist ein Stausee des Flusses."],
       ["Marburg", "Lahn", "Universitätsstadt mit Schloss über dem Tal."],
       ["Halle", "Saale", "Die Salzgewinnung gab der Stadt den Namen."],
       ["Emden", "Ems", "Hafenstadt kurz vor der Mündung."],
       ["Görlitz", "Neiße", "Die östlichste Stadt Deutschlands, geteilt mit Polen."]]'::jsonb,
     '[["Havel", "Potsdam läge daran, und die Stadt fehlt auf dem Brett."],
       ["Spree", "Berlin steht nicht in dieser Liste."]]'::jsonb),

    ('geografie', 'inselstaaten-hauptstaedte', 'Inselstaaten & Hauptstädte',
     'Welche Stadt ist die Hauptstadt?',
     'hard', 'Staat', 'https://de.wikipedia.org/wiki/Staat',
     '[["Malediven", "Malé", "Eine der am dichtesten besiedelten Städte der Welt."],
       ["Mauritius", "Port Louis", "Nach einem französischen König benannt."],
       ["Seychellen", "Victoria", "Eine der kleinsten Hauptstädte der Welt."],
       ["Komoren", "Moroni", "Am Fuß eines aktiven Vulkans."],
       ["Madagaskar", "Antananarivo", "Der Name bedeutet Stadt der Tausend."],
       ["Zypern", "Nikosia", "Letzte geteilte Hauptstadt Europas."],
       ["Malta", "Valletta", "Von einem Ritterorden angelegt."],
       ["Island", "Reykjavík", "Der Name bedeutet Rauchbucht."],
       ["Kap Verde", "Praia", "Auf der Insel Santiago."],
       ["São Tomé und Príncipe", "São Tomé", "Kleinster afrikanischer Staat nach Fläche."],
       ["Bahrain", "Manama", "Durch einen Damm mit Saudi-Arabien verbunden."],
       ["Osttimor", "Dili", "Erst 2002 unabhängig geworden."]]'::jsonb,
     '[["Colombo", "Der Regierungssitz Sri Lankas, und der Staat fehlt auf dem Brett."],
       ["Suva", "Die Hauptstadt Fidschis, das hier nicht steht."]]'::jsonb),

    ('geografie', 'gletscher-eis', 'Gletscher & Eis',
     'Wo liegt das Eis?',
     'hard', 'Geographie', 'https://de.wikipedia.org/wiki/Geographie',
     '[["Aletschgletscher", "Schweiz", "Größter Gletscher der Alpen."],
       ["Vatnajökull", "Island", "Unter dem Eis liegen aktive Vulkane."],
       ["Perito Moreno", "Argentinien", "Kalbt regelmäßig vor Zuschauern."],
       ["Jakobshavn Isbræ", "Grönland", "Einer der schnellsten Gletscher der Welt."],
       ["Pasterze", "Österreich", "Am Fuß des Großglockners."],
       ["Franz-Josef-Gletscher", "Neuseeland", "Reicht bis fast in den Regenwald."],
       ["Lambert-Gletscher", "Antarktika", "Größter Gletscher der Erde."],
       ["Baltoro", "Pakistan", "Führt zu den Achttausendern des Karakorum."],
       ["Columbia-Gletscher", "Alaska", "Hat sich in Jahrzehnten weit zurückgezogen."],
       ["Khumbu-Eisbruch", "Nepal", "Gefährlichste Passage auf dem Weg zum Everest."]]'::jsonb,
     '[["Norwegen", "Der Jostedalsbreen läge dort, er fehlt auf dem Brett."],
       ["Italien", "Der Marmolata-Gletscher steht nicht in dieser Liste."]]'::jsonb),

    ('geografie', 'grenzkuriosa', 'Kuriose Grenzen',
     'Um welche Grenze geht es?',
     'hard', 'Enklave', 'https://de.wikipedia.org/wiki/Enklave',
     '[["Grenze quer durch Häuser", "Baarle", "Türschwellen entscheiden über das Land."],
       ["Grenze mitten in einer Bibliothek", "Derby Line", "Ein Strich auf dem Boden trennt USA und Kanada."],
       ["Grenze durch ein Hotel", "Arbez", "Das Bett steht in Frankreich, der Eingang in der Schweiz."],
       ["Grenze mit Golfplatz dazwischen", "Zypern", "Die Pufferzone teilt die Insel."],
       ["Grenze, die niemand betreten darf", "Koreanische DMZ", "Vier Kilometer breit, seit 1953."],
       ["Grenze auf einem Gletscher", "Siachen", "Der höchstgelegene Konfliktort der Welt."],
       ["Grenze in einem See", "Bodensee", "Sein Verlauf ist bis heute nicht festgelegt."],
       ["Grenze mit Wechselstaatlichkeit", "Fasaneninsel", "Halbjährlich zwischen Spanien und Frankreich."],
       ["Grenze mitten im Meer", "Hans-Insel", "Jahrzehntelang mit Flaschen Schnaps umkämpft."],
       ["Grenze fast nur aus Geraden", "Ägypten und Sudan", "Auf dem Reißbrett gezogen."]]'::jsonb,
     '[["Grenze mitten durch eine Insel", "Sankt Martin wäre das, und es fehlt auf dem Brett."],
       ["Grenze, die einmal im Jahr wandert", "So etwas gibt es nirgends in dieser Liste."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

-- The answers that belong to no category. Numbered after the pairs so the two
-- sets never collide on `position`, though nothing reads it for a fake: the
-- pool is shuffled before a player sees it, and the review lists fakes on their
-- own rather than in board order.
fakes as (
    select q.id                                         as quiz_id,
           k.value ->> 0                                as label,
           k.value ->> 1                                as explanation,
           (jsonb_array_length(sp.pairs) + k.ord)::int  as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.fakes) with ordinality k(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
),

paired as (
    insert into items (quiz_id, category_id, label, position, explanation)
    select f.quiz_id, c.id, f.answer, f.position, f.explanation
      from flat f
      join new_categories c
        on c.quiz_id = f.quiz_id
       and c.label = f.label
    returning id
)

-- Same table, `category_id` left null. Both inserts run in the one statement,
-- so `items_quiz_id_label_key` still sees the pairs above: a fake written to
-- repeat an answer already on its own board fails the file rather than becoming
-- a second row nobody can tell apart.
insert into items (quiz_id, category_id, label, position, explanation)
select k.quiz_id, null, k.label, k.position, k.explanation
  from fakes k;
