-- Geschichte, leichte Fragen. Zwanzig Fragen, alle 'easy'.
--
-- Gefragt wird nach dem, was aus Schulbuch, Museum und Film hängen bleibt,
-- nicht nach Jahreszahlen von Verträgen.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs) as (
    values

    ('geschichte', 'leicht-erfinder', 'Erfinder & Erfindungen',
     'Was hat diese Person erfunden?',
     'easy', 'Erfindung', 'https://de.wikipedia.org/wiki/Erfindung',
     '[["Johannes Gutenberg", "Buchdruck", "Bewegliche Metalllettern, um 1450."],
       ["Thomas Edison", "Glühlampe", "Er machte sie marktreif."],
       ["Alexander Graham Bell", "Telefon", "Patent im Jahr 1876."],
       ["Carl Benz", "Automobil", "Der Motorwagen von 1886."],
       ["Brüder Wright", "Motorflugzeug", "Erster Flug 1903."],
       ["Alfred Nobel", "Dynamit", "Aus dem Vermögen wurden die Nobelpreise."],
       ["Guglielmo Marconi", "Funktelegrafie", "Nachrichten ohne Kabel."],
       ["Konrad Zuse", "Erster Computer", "Gebaut in einer Berliner Wohnung."],
       ["Levi Strauss", "Jeanshose", "Zuerst Arbeitshose für Goldgräber."],
       ["Melitta Bentz", "Kaffeefilter", "Sie benutzte Löschpapier ihres Sohnes."],
       ["Rudolf Diesel", "Dieselmotor", "Er zündet ohne Zündkerze."],
       ["Karl Drais", "Laufrad", "Der Urahn des Fahrrads."]]'::jsonb),

    ('geschichte', 'leicht-beruehmte-personen', 'Berühmte Personen',
     'Wofür ist die Person bekannt?',
     'easy', 'Geschichte', 'https://de.wikipedia.org/wiki/Geschichte',
     '[["Christoph Kolumbus", "Fahrt nach Amerika", "Er glaubte, in Indien zu sein."],
       ["Napoleon Bonaparte", "Kaiser der Franzosen", "Er endete verbannt auf St. Helena."],
       ["Kleopatra", "Letzte Herrscherin Ägyptens", "Danach wurde Ägypten römisch."],
       ["Martin Luther", "Reformation der Kirche", "Er übersetzte die Bibel ins Deutsche."],
       ["Karl der Große", "Kaiserkrönung im Jahr 800", "Sein Grab liegt in Aachen."],
       ["Mahatma Gandhi", "Gewaltloser Widerstand", "Er führte Indien in die Unabhängigkeit."],
       ["Nelson Mandela", "Ende der Apartheid", "27 Jahre saß er im Gefängnis."],
       ["Julius Caesar", "Römischer Feldherr", "Er wurde im Senat ermordet."],
       ["Marie Curie", "Zwei Nobelpreise", "Als erste Frau überhaupt ausgezeichnet."],
       ["Anne Frank", "Tagebuch im Versteck", "Es wurde in viele Sprachen übersetzt."],
       ["Neil Armstrong", "Erster Mann im Mondstaub", "1969 mit Apollo 11."],
       ["Königin Elisabeth II.", "Längste Regentschaft Großbritanniens", "Über siebzig Jahre auf dem Thron."]]'::jsonb),

    ('geschichte', 'leicht-aegypten', 'Im alten Ägypten',
     'Was ist das?',
     'easy', 'Altes Ägypten',
     'https://de.wikipedia.org/wiki/Altes_%C3%84gypten',
     '[["Spitzes Grabmal aus Stein", "Pyramide", "Die größte steht in Gizeh."],
       ["Herrscher des Landes", "Pharao", "Er galt als Sohn eines Gottes."],
       ["Einbalsamierter Toter in Binden", "Mumie", "So sollte der Körper erhalten bleiben."],
       ["Bilderschrift auf Stein", "Hieroglyphen", "Entziffert mit dem Stein von Rosetta."],
       ["Der Fluss, an dem alles wuchs", "Nil", "Seine Überschwemmung düngte die Felder."],
       ["Löwenkörper mit Menschenkopf", "Sphinx", "Sie bewacht die Pyramiden."],
       ["Beschreibstoff aus einer Sumpfpflanze", "Papyrus", "Vorläufer des Papiers."],
       ["Junger Pharao mit goldener Maske", "Tutanchamun", "Sein Grab war fast unberührt."],
       ["Raum tief in der Pyramide", "Grabkammer", "Dort stand der Sarkophag."],
       ["Amulett in Form eines Käfers", "Skarabäus", "Es sollte Glück bringen."]]'::jsonb),

    ('geschichte', 'leicht-ritter', 'Ritter & Burg',
     'Wie heißt das?',
     'easy', 'Ritter', 'https://de.wikipedia.org/wiki/Ritter',
     '[["Wassergraben um die Burg", "Burggraben", "Er erschwerte den Angriff."],
       ["Brücke, die hochgezogen wird", "Zugbrücke", "Nachts blieb sie oben."],
       ["Höchster Turm der Burg", "Bergfried", "Letzter Rückzugsort bei Belagerung."],
       ["Metallkleidung des Ritters", "Rüstung", "Sie wog bis zu dreißig Kilogramm."],
       ["Wichtigste Waffe des Ritters", "Schwert", "Es hatte oft einen eigenen Namen."],
       ["Wettkampf zweier Ritter zu Pferd", "Turnier", "Mit stumpfen Lanzen."],
       ["Zeichen der Familie auf dem Schild", "Wappen", "Daran erkannte man sich im Kampf."],
       ["Junge in der Ausbildung zum Ritter", "Knappe", "Er trug die Ausrüstung."],
       ["Zacken oben auf der Mauer", "Zinnen", "Dahinter konnte man sich ducken."],
       ["Gefängnis tief in der Burg", "Verlies", "Oft nur von oben zugänglich."],
       ["Langer Stab zum Angriff im Turnier", "Lanze", "Sie zersplitterte beim Treffer."],
       ["Raum für große Feste", "Rittersaal", "Der größte Raum der Burg."]]'::jsonb),

    ('geschichte', 'leicht-steinzeit', 'In der Steinzeit',
     'Was gehört dazu?',
     'easy', 'Steinzeit', 'https://de.wikipedia.org/wiki/Steinzeit',
     '[["Bearbeiteter Stein als Werkzeug", "Faustkeil", "Er diente zum Schneiden und Schaben."],
       ["Bilder an Höhlenwänden", "Höhlenmalerei", "Meist Tiere, gemalt mit Erdfarben."],
       ["Großes Tier mit langen Stoßzähnen", "Mammut", "Es starb am Ende der Eiszeit aus."],
       ["Wärme und Schutz in der Nacht", "Feuer", "Es hielt auch Raubtiere fern."],
       ["Waffe für die Jagd aus der Ferne", "Speer", "Später mit einer Schleuder geworfen."],
       ["Sammeln von Beeren und Wurzeln", "Nahrungssuche", "Sie lieferte den größten Teil der Kost."],
       ["Erste Tiere beim Menschen", "Haustiere", "Der Hund kam zuerst."],
       ["Anbau von Getreide", "Ackerbau", "Die Menschen wurden sesshaft."],
       ["Gefäße aus gebranntem Ton", "Keramik", "Zum Kochen und Aufbewahren."],
       ["Große aufgestellte Steine", "Megalithen", "Stonehenge ist das bekannteste Beispiel."]]'::jsonb),

    ('geschichte', 'leicht-roemer', 'Bei den Römern',
     'Was ist das?',
     'easy', 'Römisches Reich',
     'https://de.wikipedia.org/wiki/R%C3%B6misches_Reich',
     '[["Soldat der römischen Armee", "Legionär", "Er marschierte mit dreißig Kilo Gepäck."],
       ["Kämpfer in der Arena", "Gladiator", "Viele waren Sklaven oder Gefangene."],
       ["Bogenbauwerk für Wasser", "Aquädukt", "Es brachte Wasser über Kilometer."],
       ["Gewand der römischen Bürger", "Toga", "Nur Bürger durften sie tragen."],
       ["Öffentliches Badehaus", "Therme", "Auch Treffpunkt und Sportplatz."],
       ["Sprache der Römer", "Latein", "Aus ihr entstanden Italienisch und Spanisch."],
       ["Große Arena in Rom", "Kolosseum", "Platz für rund 50000 Menschen."],
       ["Grenzwall in Germanien", "Limes", "Er zog sich über Hunderte Kilometer."],
       ["Gepflasterte Fernstraße", "Römerstraße", "Manche sind bis heute erhalten."],
       ["Marktplatz und Zentrum der Stadt", "Forum", "Hier wurde Politik gemacht."],
       ["Wagenrennbahn", "Circus", "Der Circus Maximus war der größte."],
       ["Zahlzeichen aus Buchstaben", "Römische Zahlen", "I, V, X, L, C, D und M."]]'::jsonb),

    ('geschichte', 'leicht-wikinger', 'Die Wikinger',
     'Was stimmt?',
     'easy', 'Wikinger', 'https://de.wikipedia.org/wiki/Wikinger',
     '[["Ihr schnelles Schiff", "Langschiff", "Flach genug für Flüsse."],
       ["Ihre Schrift", "Runen", "In Stein und Holz geritzt."],
       ["Ihr Donnergott", "Thor", "Sein Hammer heißt Mjölnir."],
       ["Der oberste Gott", "Odin", "Er gab ein Auge für Weisheit."],
       ["Halle der gefallenen Krieger", "Walhall", "Walküren bringen sie dorthin."],
       ["Insel, die sie besiedelten", "Island", "Später auch Grönland."],
       ["Land, das sie vor Kolumbus erreichten", "Nordamerika", "Sie nannten es Vinland."],
       ["Ihre Heimat", "Skandinavien", "Dänemark, Norwegen und Schweden."],
       ["Was sie an den Helmen nicht hatten", "Hörner", "Eine Erfindung des 19. Jahrhunderts."],
       ["Versammlung der freien Männer", "Thing", "Dort wurde Recht gesprochen."]]'::jsonb),

    ('geschichte', 'leicht-entdecker', 'Entdecker',
     'Was hat die Person erreicht?',
     'easy', 'Entdecker', 'https://de.wikipedia.org/wiki/Entdecker',
     '[["Christoph Kolumbus", "Erreichte Amerika", "Er landete zuerst auf den Bahamas."],
       ["Ferdinand Magellan", "Erste Weltumsegelung", "Er selbst starb unterwegs."],
       ["James Cook", "Erforschte den Pazifik", "Er kartierte Neuseeland und Australien."],
       ["Roald Amundsen", "Erreichte den Südpol", "Einen Monat vor Scott."],
       ["Marco Polo", "Reiste nach China", "Sein Reisebericht wurde berühmt."],
       ["Vasco da Gama", "Seeweg nach Indien", "Um Afrika herum."],
       ["Alexander von Humboldt", "Erforschte Südamerika", "Fünf Jahre unterwegs."],
       ["Edmund Hillary", "Bestieg den Mount Everest", "Gemeinsam mit Tenzing Norgay."],
       ["Juri Gagarin", "Erster Mensch im All", "Er umrundete die Erde einmal."],
       ["Amelia Earhart", "Alleinflug über den Atlantik", "Später verschwand sie im Pazifik."]]'::jsonb),

    ('geschichte', 'leicht-deutschland', 'Deutsche Geschichte',
     'Was geschah da?',
     'easy', 'Deutsche Wiedervereinigung',
     'https://de.wikipedia.org/wiki/Deutsche_Wiedervereinigung',
     '[["Bau der Berliner Mauer", "1961", "Über Nacht wurde die Stadt geteilt."],
       ["Fall der Berliner Mauer", "1989", "Am Abend des 9. November."],
       ["Tag der Deutschen Einheit", "3. Oktober", "Seit 1990 gesetzlicher Feiertag."],
       ["Erste Fußball-Weltmeisterschaft für Deutschland", "1954", "Das Wunder von Bern."],
       ["Sommermärchen im eigenen Land", "2006", "Die WM im eigenen Land."],
       ["Euro-Bargeld statt D-Mark", "2002", "Die Umstellung kam über Nacht."],
       ["Erste Bundeskanzlerin", "2005", "Angela Merkel übernahm das Amt."],
       ["Ende des Zweiten Weltkriegs", "1945", "Am 8. Mai in Europa."],
       ["Gründung der Bundesrepublik", "1949", "Das Grundgesetz trat in Kraft."],
       ["Erste Mondlandung im Fernsehen", "1969", "Millionen sahen nachts zu."]]'::jsonb),

    ('geschichte', 'leicht-epochen', 'Zeitalter',
     'Was ist typisch für die Epoche?',
     'easy', 'Geschichte', 'https://de.wikipedia.org/wiki/Geschichte',
     '[["Steinzeit", "Werkzeuge aus Stein", "Die längste Epoche der Menschheit."],
       ["Bronzezeit", "Werkzeuge aus Bronze", "Kupfer und Zinn gemischt."],
       ["Eisenzeit", "Werkzeuge aus Eisen", "Härter als Bronze."],
       ["Antike", "Griechen und Römer", "Tempel, Theater und Philosophie."],
       ["Mittelalter", "Burgen und Ritter", "Dazu Klöster und Kathedralen."],
       ["Renaissance", "Wiederentdeckung der Antike", "Kunst und Wissenschaft blühen auf."],
       ["Zeitalter der Entdeckungen", "Fahrten über die Ozeane", "Neue Seewege und Kontinente."],
       ["Industrialisierung", "Fabriken und Dampfmaschinen", "Menschen zogen in die Städte."],
       ["20. Jahrhundert", "Zwei Weltkriege", "Und die Teilung der Welt danach."],
       ["Digitales Zeitalter", "Computer und Internet", "Information wird sofort verfügbar."]]'::jsonb),

    ('geschichte', 'leicht-herrscher-titel', 'Wer regierte?',
     'Wie nennt man diese Person?',
     'easy', 'Herrscher', 'https://de.wikipedia.org/wiki/Herrscher',
     '[["Herrscher in Ägypten", "Pharao", "Er galt zugleich als Gott."],
       ["Herrscher in Russland bis 1917", "Zar", "Vom Wort Caesar abgeleitet."],
       ["Herrscher im Osmanischen Reich", "Sultan", "Er regierte von Istanbul aus."],
       ["Oberhaupt der katholischen Kirche", "Papst", "Er wohnt im Vatikan."],
       ["Gewählter Regierungschef in Deutschland", "Bundeskanzler", "Der Bundestag wählt ihn."],
       ["Gewähltes Staatsoberhaupt in Frankreich", "Präsident", "Direkt vom Volk gewählt."],
       ["Herrscher mit Krone und Thron", "König", "Das Amt wird meist vererbt."],
       ["Herrscher über mehrere Königreiche", "Kaiser", "Ein Rang über dem König."],
       ["Anführer eines Stammes", "Häuptling", "Oft von den Ältesten bestimmt."],
       ["Herrscher in einem Fürstentum", "Fürst", "Etwa in Monaco und Liechtenstein."]]'::jsonb),

    ('geschichte', 'leicht-schule-frueher', 'Schule früher',
     'Was war das?',
     'easy', 'Schule', 'https://de.wikipedia.org/wiki/Schule',
     '[["Tafel aus Stein zum Schreiben", "Schiefertafel", "Sie wurde mit einem Schwamm gewischt."],
       ["Stift für die Schiefertafel", "Griffel", "Er quietschte beim Schreiben."],
       ["Behälter für Tinte im Pult", "Tintenfass", "Die Feder wurde eingetaucht."],
       ["Erstes Lesebuch der Kinder", "Fibel", "Buchstabe für Buchstabe."],
       ["Strafe mit dem Stock", "Prügelstrafe", "In Deutschland seit 1973 verboten."],
       ["Alle Jahrgänge in einem Raum", "Zwergschule", "Ein Lehrer für alle Kinder."],
       ["Sitzmöbel mit fester Bank", "Schulbank", "Tisch und Sitz waren verbunden."],
       ["Tüte voller Süßigkeiten am ersten Tag", "Schultüte", "Ein Brauch aus dem 19. Jahrhundert."],
       ["Zeugnis am Ende des Jahres", "Schulzeugnis", "Mit Noten von eins bis sechs."],
       ["Tafel vorn für den Lehrer", "Wandtafel", "Beschrieben mit Kreide."]]'::jsonb),

    ('geschichte', 'leicht-geld-frueher', 'Geld früher',
     'Womit wurde bezahlt?',
     'easy', 'Geld', 'https://de.wikipedia.org/wiki/Geld',
     '[["Ganz ohne Geld", "Tauschhandel", "Ware gegen Ware."],
       ["Schnecken als Zahlungsmittel", "Kaurimuscheln", "Jahrtausendelang in Afrika und Asien."],
       ["Erste geprägte Stücke aus Metall", "Münzen", "Zuerst in Kleinasien."],
       ["Erstes staatliches Papiergeld", "Banknoten aus China", "Lange vor Europa."],
       ["Deutsche Währung vor dem Euro", "D-Mark", "Eingeführt 1948."],
       ["Währung der DDR", "Mark der DDR", "Im Westen nicht umtauschbar."],
       ["Gemeinsame Währung Europas", "Euro", "Bargeld seit 2002."],
       ["Karte statt Bargeld", "Girocard", "Früher als EC-Karte bekannt."],
       ["Geld ohne Münzen und Scheine", "Digitales Bezahlen", "Per Handy oder Uhr."],
       ["Sehr schnelle Geldentwertung", "Inflation", "1923 kostete ein Brot Milliarden."]]'::jsonb),

    ('geschichte', 'leicht-symbole-macht', 'Zeichen der Macht',
     'Wofür steht das?',
     'easy', 'Herrscher', 'https://de.wikipedia.org/wiki/Herrscher',
     '[["Krone", "Herrschaft eines Königs", "Bei der Krönung aufgesetzt."],
       ["Zepter", "Stab als Herrschaftszeichen", "In der rechten Hand getragen."],
       ["Reichsapfel", "Kugel mit Kreuz", "Sinnbild der Weltherrschaft."],
       ["Thron", "Sitz des Herrschers", "Erhöht über allen anderen."],
       ["Wappen", "Zeichen einer Familie", "Auch Städte führen eines."],
       ["Siegel", "Bestätigung eines Schreibens", "In Wachs gedrückt."],
       ["Fahne", "Zeichen eines Landes", "Wird bei Staatsakten gehisst."],
       ["Purpurmantel", "Farbe der Herrscher", "Der Farbstoff war sehr teuer."],
       ["Ritterschlag", "Aufnahme in den Ritterstand", "Mit der flachen Klinge."],
       ["Denkmal", "Erinnerung an eine Person", "Meist auf einem Sockel."]]'::jsonb),

    ('geschichte', 'leicht-alte-bauwerke', 'Alte Bauwerke',
     'Wo steht das Bauwerk?',
     'easy', 'Weltwunder', 'https://de.wikipedia.org/wiki/Weltwunder',
     '[["Pyramiden von Gizeh", "Ägypten", "Über 4500 Jahre alt."],
       ["Chinesische Mauer", "China", "Über Jahrhunderte gebaut."],
       ["Kolosseum", "Italien", "Amphitheater in Rom."],
       ["Akropolis", "Griechenland", "Tempelberg über Athen."],
       ["Stonehenge", "England", "Ein Steinkreis aus der Jungsteinzeit."],
       ["Machu Picchu", "Peru", "Inkastadt hoch in den Anden."],
       ["Taj Mahal", "Indien", "Ein Grabmal aus weißem Marmor."],
       ["Petra", "Jordanien", "In den Fels geschlagen."],
       ["Chichén Itzá", "Mexiko", "Stufenpyramide der Maya."],
       ["Angkor Wat", "Kambodscha", "Die größte Tempelanlage der Welt."]]'::jsonb),

    ('geschichte', 'leicht-verkehr-frueher', 'Unterwegs früher',
     'Womit reiste man?',
     'easy', 'Verkehrsmittel',
     'https://de.wikipedia.org/wiki/Verkehrsmittel',
     '[["Wagen mit Pferden davor", "Postkutsche", "Die Pferde wurden unterwegs gewechselt."],
       ["Zug mit Dampf und Kohle", "Dampflokomotive", "Sie machte Reisen erschwinglich."],
       ["Schiff nur mit Wind", "Segelschiff", "Wochenlang über den Atlantik."],
       ["Von Menschen getragener Sitz", "Sänfte", "Für Wohlhabende in engen Gassen."],
       ["Boot aus einem Baumstamm", "Einbaum", "Eines der ältesten Boote überhaupt."],
       ["Wagen von einem Menschen gezogen", "Rikscha", "In Asien weit verbreitet."],
       ["Tiere als Lasttiere durch die Wüste", "Kamelkarawane", "Wasserstellen bestimmten die Route."],
       ["Luftschiff mit starrem Gerüst", "Zeppelin", "Bis 1937 über den Atlantik."],
       ["Rad ohne Pedale zum Abstoßen", "Laufrad", "Der Anfang des Fahrrads."],
       ["Schiff mit Schaufelrädern", "Raddampfer", "Vor allem auf Flüssen."]]'::jsonb),

    ('geschichte', 'leicht-alltag-mittelalter', 'Alltag im Mittelalter',
     'Wer oder was war das?',
     'easy', 'Mittelalter', 'https://de.wikipedia.org/wiki/Mittelalter',
     '[["Bauer auf dem Land", "Arbeitete für den Grundherrn", "Er durfte nicht einfach fortziehen."],
       ["Mönch im Kloster", "Betete und schrieb ab", "Bücher entstanden von Hand."],
       ["Handwerker in der Stadt", "Gehörte einer Zunft an", "Sie regelte Preise und Ausbildung."],
       ["Markt in der Stadt", "Wochenmarkt", "Nur mit Marktrecht erlaubt."],
       ["Stadtmauer", "Schutz der Bewohner", "Nachts wurden die Tore geschlossen."],
       ["Wanderer von Baustelle zu Baustelle", "Geselle auf Wanderschaft", "Manche wandern bis heute."],
       ["Person, die Nachrichten überbrachte", "Bote", "Er ging oder ritt weite Strecken."],
       ["Große Kirche in der Stadt", "Kathedrale", "Der Bau dauerte Jahrhunderte."],
       ["Krankheit, die Europa verheerte", "Pest", "Ein Drittel der Menschen starb."],
       ["Bad in der Stadt", "Badestube", "Sie war auch Treffpunkt."]]'::jsonb),

    ('geschichte', 'leicht-jahreszahlen', 'Bekannte Jahreszahlen',
     'Wann war das?',
     'easy', 'Geschichte', 'https://de.wikipedia.org/wiki/Geschichte',
     '[["Entdeckung Amerikas durch Kolumbus", "1492", "Er segelte mit drei Schiffen."],
       ["Beginn des Ersten Weltkriegs", "1914", "Er dauerte vier Jahre."],
       ["Beginn des Zweiten Weltkriegs", "1939", "Mit dem Überfall auf Polen."],
       ["Erste Mondlandung", "1969", "Apollo 11 landete im Juli."],
       ["Fall der Berliner Mauer", "1989", "Im Herbst des Jahres."],
       ["Deutsche Wiedervereinigung", "1990", "Am 3. Oktober."],
       ["Beginn der Reformation", "1517", "Luthers Thesen in Wittenberg."],
       ["Untergang der Titanic", "1912", "Auf der Jungfernfahrt."],
       ["Erfindung des Buchdrucks", "Um 1450", "In Mainz durch Gutenberg."],
       ["Ausbruch des Vesuvs über Pompeji", "79", "Die Stadt verschwand unter Asche."]]'::jsonb),

    ('geschichte', 'leicht-museum-geschichte', 'Spuren der Geschichte',
     'Was ist das?',
     'easy', 'Archäologie',
     'https://de.wikipedia.org/wiki/Arch%C3%A4ologie',
     '[["Suche nach Spuren im Boden", "Ausgrabung", "Schicht für Schicht abgetragen."],
       ["Zerbrochenes Stück Tongefäß", "Scherbe", "Der häufigste Fund überhaupt."],
       ["Sehr alter, gut erhaltener Körper", "Moorleiche", "Das Moor hält sie erstaunlich frisch."],
       ["Mann aus dem Eis der Alpen", "Ötzi", "Über 5000 Jahre alt."],
       ["Versteinerter Rest eines Lebewesens", "Fossil", "Knochen wurden zu Stein."],
       ["Alte Handschrift auf Pergament", "Manuskript", "Von Hand geschrieben."],
       ["Alte Münze im Acker", "Münzfund", "Sie verrät oft das Alter der Fundstelle."],
       ["Bestimmung des Alters über Kohlenstoff", "Radiokarbonmethode", "Sie reicht rund 50000 Jahre zurück."],
       ["Nachbau zum Ausprobieren", "Rekonstruktion", "So versteht man alte Technik."],
       ["Ort, an dem Funde gezeigt werden", "Museum", "Vitrinen schützen die Stücke."]]'::jsonb),

    ('geschichte', 'leicht-feiertage', 'Feiertage & ihre Herkunft',
     'Woran erinnert der Tag?',
     'easy', 'Feiertag', 'https://de.wikipedia.org/wiki/Feiertag',
     '[["Tag der Deutschen Einheit", "Wiedervereinigung 1990", "Gefeiert am 3. Oktober."],
       ["1. Mai", "Tag der Arbeit", "Er geht auf Arbeiterproteste zurück."],
       ["Reformationstag", "Luthers Thesen", "Gefeiert am 31. Oktober."],
       ["Volkstrauertag", "Erinnerung an Kriegstote", "Im November begangen."],
       ["Sankt Martin", "Der geteilte Mantel", "Kinder ziehen mit Laternen."],
       ["Nikolaustag", "Bischof, der beschenkte", "Stiefel vor der Tür."],
       ["Ostern", "Auferstehung Jesu", "Termin richtet sich nach dem Mond."],
       ["Weihnachten", "Geburt Jesu", "Gefeiert am 25. Dezember."],
       ["Silvester", "Letzter Tag des Jahres", "Benannt nach einem Papst."],
       ["Karneval", "Zeit vor der Fastenzeit", "In Köln beginnt er im November."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
)

insert into items (quiz_id, category_id, label, position, explanation)
select f.quiz_id, c.id, f.answer, f.position, f.explanation
  from flat f
  join new_categories c
    on c.quiz_id = f.quiz_id
   and c.label = f.label;
