-- Geschichte, file 3. Twenty questions, medium and hard.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs) as (
    values

    ('geschichte', 'archaeologische-raetsel', 'Rätsel der Archäologie',
     'Wo liegt der Fundort?',
     'hard', 'Archäologie', 'https://de.wikipedia.org/wiki/Arch%C3%A4ologie',
     '[["Nazca-Linien", "Peru", "Nur aus der Luft als Figuren erkennbar."],
       ["Moai-Statuen", "Osterinsel", "Bis zu 80 Tonnen schwer, ohne Räder bewegt."],
       ["Göbekli Tepe", "Türkei", "Älter als Ackerbau und Keramik."],
       ["Antikythera-Mechanismus", "Griechenland", "Ein Zahnradgerät zur Berechnung von Gestirnen."],
       ["Höhle von Lascaux", "Frankreich", "Von Jugendlichen bei der Suche nach einem Hund entdeckt."],
       ["Ötzi", "Ötztaler Alpen", "Eine Pfeilspitze in der Schulter verriet die Todesursache."],
       ["Sutton Hoo", "England", "Ein ganzes Schiff diente als Grab."],
       ["Sanxingdui", "China", "Bronzemasken einer bis dahin unbekannten Kultur."],
       ["Cahokia", "USA", "Erdpyramiden einer Großstadt am Mississippi."],
       ["Nebra", "Sachsen-Anhalt", "Die Himmelsscheibe zeigt Sonne, Mond und Sterne."]]'::jsonb),

    ('geschichte', 'verschollenes', 'Verschollene Dinge & Menschen',
     'Wo verliert sich die Spur?',
     'hard', 'Verschollen', 'https://de.wikipedia.org/wiki/Verschollen',
     '[["Bernsteinzimmer", "Königsberg", "1945 aus dem Schloss verschwunden."],
       ["Kolonie Roanoke", "Nordamerika", "Nur das Wort Croatoan blieb zurück."],
       ["Franklin-Expedition", "Arktis", "Beide Schiffe wurden erst nach 170 Jahren gefunden."],
       ["Amelia Earhart", "Pazifik", "Auf dem letzten Abschnitt ihres Weltflugs."],
       ["Mary Celeste", "Atlantik", "Das Schiff war seetüchtig, die Besatzung fort."],
       ["Flug MH370", "Indischer Ozean", "Nur Wrackteile an ostafrikanischen Küsten."],
       ["Neuntes Adlerbanner Roms", "Britannien", "Die Legende von der verlorenen Legion."],
       ["Peking-Mensch", "Schanghai", "Die Fossilien gingen 1941 im Kriegsgewirr verloren."],
       ["Schatz der Nibelungen", "Rhein", "Der Sage nach im Fluss versenkt."],
       ["Percy Fawcett", "Mato Grosso", "Suchte eine Stadt, die er Z nannte."]]'::jsonb),

    ('geschichte', 'geschichtsmythen', 'Hartnäckige Geschichtsmythen',
     'Was ist daran falsch?',
     'hard', 'Geschichtsmythos',
     'https://de.wikipedia.org/wiki/Geschichtsmythos',
     '[["Wikinger mit Hörnerhelmen", "Erfindung des 19. Jahrhunderts", "Kam über Opernkostüme in die Welt."],
       ["Napoleon war auffallend klein", "Falsche Maßeinheit", "Französische Zoll waren länger als englische."],
       ["Im Mittelalter galt die Erde als Scheibe", "Erst später behauptet", "Gelehrte wussten es seit der Antike besser."],
       ["Marie Antoinette und der Kuchen", "Nirgends belegt", "Der Satz kursierte schon vor ihrer Zeit."],
       ["Einstein war schlecht in Mathematik", "Er war sehr gut", "Der Irrtum entstand durch ein anderes Notensystem."],
       ["Römer hatten Erbrechzimmer", "Vomitorium heißt Ausgang", "Es entließ die Zuschauer aus dem Theater."],
       ["Gladiatoren starben fast immer", "Zu teuer ausgebildet", "Die meisten Kämpfe endeten ohne Tod."],
       ["Kolumbus wollte die Kugelgestalt beweisen", "Die war längst bekannt", "Umstritten war nur der Umfang der Erde."],
       ["Nero spielte Geige beim Brand", "Geigen gab es nicht", "Er war zudem nicht in der Stadt."],
       ["Die Große Mauer ist vom Mond sichtbar", "Viel zu schmal", "Schon aus der Erdumlaufbahn kaum zu erkennen."]]'::jsonb),

    ('geschichte', 'kuriose-steuern', 'Kuriose Steuern der Geschichte',
     'Wo wurde diese Steuer erhoben?',
     'hard', 'Steuer', 'https://de.wikipedia.org/wiki/Steuer',
     '[["Bartsteuer", "Russland", "Peter der Große wollte den Hof europäisch aussehen lassen."],
       ["Fenstersteuer", "England", "Manche mauerten Fenster einfach zu."],
       ["Urinsteuer", "Römisches Reich", "Geld stinkt nicht, soll Vespasian gesagt haben."],
       ["Salzsteuer Gabelle", "Frankreich", "Eine der meistgehassten Abgaben vor der Revolution."],
       ["Teesteuer", "Britisch-Amerika", "Führte zur Boston Tea Party."],
       ["Hutsteuer", "Großbritannien", "Jeder Hut brauchte eine Steuermarke im Futter."],
       ["Ziegelsteuer", "Irland", "Man baute daraufhin größere Ziegel."],
       ["Kaminsteuer", "Schottland", "Erhoben nach der Zahl der Feuerstellen."],
       ["Junggesellensteuer", "Italien", "In den 1920er Jahren zur Förderung von Geburten."],
       ["Schaumweinsteuer", "Deutsches Reich", "Sollte die Kriegsflotte finanzieren, gilt bis heute."]]'::jsonb),

    ('geschichte', 'aufstaende-anfuehrer', 'Aufstände & ihre Anführer',
     'Wer führte den Aufstand an?',
     'hard', 'Aufstand', 'https://de.wikipedia.org/wiki/Aufstand',
     '[["Sklavenaufstand gegen Rom", "Spartacus", "Zwei Jahre lang schlug er römische Heere."],
       ["Aufstand der Icener", "Boudica", "Sie brannte das römische London nieder."],
       ["Englischer Bauernaufstand 1381", "Wat Tyler", "Er wurde vor dem König erschlagen."],
       ["Hussitenkriege", "Jan Žižka", "Verteidigte sich mit Wagenburgen."],
       ["Deutscher Bauernkrieg", "Thomas Müntzer", "Predigte die Sache der Bauern und fiel bei Frankenhausen."],
       ["Aufstand in Peru 1780", "Túpac Amaru II.", "Gegen die spanische Kolonialverwaltung."],
       ["Haitianische Revolution", "Toussaint Louverture", "Erster erfolgreicher Sklavenaufstand der Neuzeit."],
       ["Sklavenaufstand in Virginia", "Nat Turner", "Führte zu drastischen Verschärfungen der Gesetze."],
       ["Mexikanische Revolution", "Emiliano Zapata", "Land und Freiheit als Losung."],
       ["Kubanische Guerilla", "Che Guevara", "Aus Argentinien, Arzt von Beruf."]]'::jsonb),

    ('geschichte', 'beruehmte-prozesse', 'Berühmte Prozesse',
     'Wo fand der Prozess statt?',
     'hard', 'Prozess (Recht)',
     'https://de.wikipedia.org/wiki/Prozess_%28Recht%29',
     '[["Prozess gegen Sokrates", "Athen", "Verurteilt wegen Verderbnis der Jugend."],
       ["Prozess gegen Jeanne d''Arc", "Rouen", "Ein kirchliches Gericht sprach das Urteil."],
       ["Prozess gegen Galileo Galilei", "Rom", "Er musste dem Weltbild abschwören."],
       ["Hexenprozesse von 1692", "Salem", "Zwanzig Menschen wurden hingerichtet."],
       ["Dreyfus-Affäre", "Frankreich", "Ein Justizirrtum spaltete das Land."],
       ["Scopes-Prozess", "Tennessee", "Es ging um Evolution im Schulunterricht."],
       ["Rivonia-Prozess", "Südafrika", "Nelson Mandela hielt seine berühmteste Rede."],
       ["Eichmann-Prozess", "Jerusalem", "Erstmals sagten viele Überlebende öffentlich aus."],
       ["Prozess gegen Thomas Morus", "London", "Er verweigerte den Eid auf den König als Kirchenoberhaupt."],
       ["Reichstagsbrandprozess", "Leipzig", "Der Hauptangeklagte wurde freigesprochen."]]'::jsonb),

    ('geschichte', 'kalendersysteme', 'Kalender & ihr Ausgangspunkt',
     'Womit beginnt die Zählung?',
     'hard', 'Kalender', 'https://de.wikipedia.org/wiki/Kalender',
     '[["Julianischer Kalender", "Reform unter Caesar", "45 v. Chr. eingeführt, mit Schaltjahr alle vier Jahre."],
       ["Gregorianischer Kalender", "Korrektur von 1582", "Zehn Tage wurden übersprungen."],
       ["Islamischer Kalender", "Auswanderung nach Medina", "Das Jahr 622 ist das Jahr eins."],
       ["Jüdischer Kalender", "Angenommene Weltschöpfung", "Gezählt wird ab 3761 v. Chr."],
       ["Französischer Revolutionskalender", "Ausrufung der Republik", "Mit zehntägigen Wochen."],
       ["Chinesischer Kalender", "Mond- und Sonnenjahr zugleich", "Der Jahreswechsel wandert im Winter."],
       ["Maya-Kalender", "Lange Zählung", "Das Ende eines Zyklus fiel auf 2012."],
       ["Äthiopischer Kalender", "Abweichendes Christusjahr", "Er liegt rund sieben Jahre zurück."],
       ["Japanische Ärenrechnung", "Regierungsantritt des Kaisers", "Mit jedem Kaiser beginnt eine neue Ära."],
       ["Buddhistischer Kalender", "Tod des Buddha", "In Thailand amtlich in Gebrauch."]]'::jsonb),

    ('geschichte', 'nachrichtenwege', 'Nachrichten vor dem Telefon',
     'Wie wurden Nachrichten übermittelt?',
     'hard', 'Kommunikation',
     'https://de.wikipedia.org/wiki/Kommunikation',
     '[["Chasqui", "Läufer im Inkareich", "Staffeln legten Hunderte Kilometer am Tag zurück."],
       ["Optischer Telegraf", "Signalarme auf Türmen", "Eine Nachricht lief in Stunden durch Frankreich."],
       ["Brieftaube", "Vogel mit Heimfindevermögen", "Bis ins 20. Jahrhundert militärisch genutzt."],
       ["Pony Express", "Reiterstaffel durch den Westen", "Nur achtzehn Monate lang in Betrieb."],
       ["Rauchzeichen", "Sichtsignale über weite Strecken", "Auch die Papstwahl nutzt bis heute Rauch."],
       ["Sprechende Trommeln", "Nachbildung der Sprachmelodie", "In Westafrika über Kilometer verständlich."],
       ["Flaschenpost", "Botschaft mit der Meeresströmung", "Auch zur Erforschung von Strömungen genutzt."],
       ["Postkutsche", "Feste Route mit Pferdewechsel", "Stationen im Abstand einer Tagesetappe."],
       ["Kerbholz", "Eingeritzte Zeichen als Beleg", "Daher stammt die Redensart vom Kerbholz."],
       ["Feuerkette", "Signalfeuer auf Bergen", "Warnte vor herannahenden Schiffen."]]'::jsonb),

    ('geschichte', 'zufallserfindungen', 'Erfindungen aus Versehen',
     'Wie kam es zu der Entdeckung?',
     'hard', 'Serendipität',
     'https://de.wikipedia.org/wiki/Serendipit%C3%A4t',
     '[["Mikrowelle", "Geschmolzener Schokoriegel", "Ein Techniker stand vor einem Radargerät."],
       ["Post-it", "Zu schwacher Klebstoff", "Erst Jahre später fand sich die Anwendung."],
       ["Teflon", "Rückstand im Gasbehälter", "Gesucht war ein neues Kältemittel."],
       ["Vulkanisierter Kautschuk", "Auf den Ofen gefallen", "Erst dadurch wurde Gummi haltbar."],
       ["Klettverschluss", "Kletten im Hundefell", "Unter dem Mikroskop zeigten sich Häkchen."],
       ["Sacharin", "Süße an den Fingern", "Nach dem Arbeiten im Labor bemerkt."],
       ["Coca-Cola", "Als Medizin gemischt", "Sollte gegen Kopfschmerzen helfen."],
       ["Sekundenkleber", "Unbrauchbar klebrig", "Gesucht war ein durchsichtiges Zielfernrohr."],
       ["Kaugummi", "Ersatzstoff für Kautschuk", "Der Chicle klebte nicht, aber ließ sich kauen."],
       ["Sildenafil", "Nebenwirkung im Herztest", "Die Probanden wollten die Tabletten behalten."]]'::jsonb),

    ('geschichte', 'waehrungsreformen', 'Währungsreformen',
     'Wann geschah das?',
     'hard', 'Währungsreform',
     'https://de.wikipedia.org/wiki/W%C3%A4hrungsreform',
     '[["Ende der Hyperinflation mit der Rentenmark", "1923", "Eine Billion Mark wurde zu einer Rentenmark."],
       ["Einführung der D-Mark", "1948", "Jeder bekam zunächst vierzig Mark Kopfgeld."],
       ["Neuer Franc in Frankreich", "1960", "Hundert alte Francs wurden zu einem neuen."],
       ["Ende des Goldstandards in den USA", "1971", "Der Dollar war nicht mehr in Gold einlösbar."],
       ["Währungsunion mit der DDR", "1990", "Löhne wurden eins zu eins umgestellt."],
       ["Euro als Buchgeld", "1999", "Die Kurse wurden unwiderruflich festgelegt."],
       ["Euro-Bargeld", "2002", "Zwölf Länder tauschten gleichzeitig."],
       ["Redenominierung der türkischen Lira", "2005", "Sechs Nullen fielen weg."],
       ["Einführung des Bitcoin", "2009", "Erste dezentrale Währung ohne Zentralbank."],
       ["Dezimalisierung des britischen Pfunds", "1971 in London", "240 Pence wurden zu hundert."]]'::jsonb),

    ('geschichte', 'abolition', 'Das Ende der Sklaverei',
     'Wo wurde das beschlossen?',
     'hard', 'Sklaverei', 'https://de.wikipedia.org/wiki/Sklaverei',
     '[["Verbot des Sklavenhandels 1807", "Großbritannien", "Der Handel, noch nicht die Sklaverei selbst."],
       ["Abschaffung im Kolonialreich 1833", "Britisches Empire", "Mit hohen Entschädigungen an die Halter."],
       ["Endgültige Abschaffung 1848", "Frankreich", "Nach einem ersten, wieder zurückgenommenen Versuch."],
       ["Aufhebung der Leibeigenschaft 1861", "Russland", "Über zwanzig Millionen Bauern betroffen."],
       ["Emanzipationsproklamation 1863", "Nordstaaten", "Sie galt zunächst nur für die abtrünnigen Staaten."],
       ["Dreizehnter Zusatzartikel 1865", "USA", "Erst er verbot die Sklaverei landesweit."],
       ["Goldenes Gesetz 1888", "Brasilien", "Das letzte Land Amerikas, das sie abschaffte."],
       ["Abschaffung 1962", "Saudi-Arabien", "Auf internationalen Druck hin."],
       ["Verbot 1981", "Mauretanien", "Strafbar wurde es erst 2007."],
       ["Sklavereiverbot in der Menschenrechtserklärung", "Vereinte Nationen", "1948 in Artikel vier festgehalten."]]'::jsonb),

    ('geschichte', 'antiker-alltag', 'Alltag im Römischen Reich',
     'Was war das?',
     'hard', 'Römisches Reich',
     'https://de.wikipedia.org/wiki/R%C3%B6misches_Reich',
     '[["Insula", "Mehrstöckiges Mietshaus", "Oben wohnten die Ärmsten, im Brandfall gefährlich."],
       ["Domus", "Stadthaus der Wohlhabenden", "Nach innen orientiert, mit Atrium."],
       ["Villa rustica", "Landgut mit Betrieb", "Wirtschaftshof und Herrenteil zugleich."],
       ["Thermen", "Öffentliches Badehaus", "Auch Treffpunkt, Bibliothek und Sportplatz."],
       ["Taberna", "Ladenlokal zur Straße", "Oft mit Wohnraum darüber."],
       ["Forum", "Marktplatz und Zentrum", "Hier wurde Politik gemacht und Recht gesprochen."],
       ["Circus", "Bahn für Wagenrennen", "Der Circus Maximus fasste über 150000 Zuschauer."],
       ["Amphitheater", "Ovale Arena für Kämpfe", "Anders als das halbrunde Theater."],
       ["Latrine", "Gemeinschaftstoilette", "Man saß nebeneinander und unterhielt sich."],
       ["Cloaca Maxima", "Große Abwasserleitung", "Sie entwässerte das Forum, teils bis heute."]]'::jsonb),

    ('geschichte', 'geschichte-des-geldes', 'Die Geschichte des Geldes',
     'Wo oder wann war das im Gebrauch?',
     'hard', 'Geld', 'https://de.wikipedia.org/wiki/Geld',
     '[["Kaurischnecken als Zahlungsmittel", "Afrika und Asien", "Jahrtausendelang über weite Räume anerkannt."],
       ["Rai-Steine", "Insel Yap", "Tonnenschwere Scheiben, die liegen bleiben."],
       ["Erste geprägte Münzen", "Lydien", "Aus Elektron, im 7. Jahrhundert v. Chr."],
       ["Erstes staatliches Papiergeld", "China", "Unter der Song-Dynastie ausgegeben."],
       ["Wechselbriefe im Fernhandel", "Oberitalien", "Machten den Transport von Bargeld überflüssig."],
       ["Erste Banknoten Europas", "Schweden", "Ausgegeben ab 1661, gedeckt durch Kupfer."],
       ["Goldstandard", "19. Jahrhundert", "Währungen waren an eine feste Goldmenge gebunden."],
       ["Erste Kreditkarte", "New York", "Angeblich nach einem vergessenen Portemonnaie erdacht."],
       ["Ende der Goldbindung des Dollars", "1971", "Seitdem sind Währungen reines Vertrauensgeld."],
       ["Erste Kryptowährung", "Bitcoin", "2009 gestartet, ohne Notenbank dahinter."]]'::jsonb),

    ('geschichte', 'ddr-alltag', 'Wörter aus der DDR',
     'Was bedeutete das Wort?',
     'medium', 'Deutsche Demokratische Republik',
     'https://de.wikipedia.org/wiki/Deutsche_Demokratische_Republik',
     '[["Broiler", "Brathähnchen", "Der Begriff kam aus dem Englischen."],
       ["Datsche", "Wochenendhaus im Grünen", "Aus dem Russischen übernommen."],
       ["Plaste", "Kunststoff", "Im Westen sagte man Plastik."],
       ["Intershop", "Laden für Westwaren", "Bezahlt wurde nur mit Devisen."],
       ["Ampelmännchen", "Figur der Fußgängerampel", "Überlebte die Wende als Kultobjekt."],
       ["Jugendweihe", "Feier zum Erwachsenwerden", "Weltliche Alternative zur Konfirmation."],
       ["Trabant", "Kleinwagen mit Zweitaktmotor", "Karosserie aus Duroplast."],
       ["Republikflucht", "Straftatbestand Ausreise", "Wer ging, machte sich strafbar."],
       ["Schwalbe", "Moped aus Suhl", "Kultfahrzeug für Jugendliche."],
       ["Kaufhalle", "Selbstbedienungsladen", "Das Wort Supermarkt war unüblich."],
       ["Feierabendheim", "Altenheim", "Amtliche Bezeichnung im Osten."],
       ["Kollektiv", "Arbeitsgruppe im Betrieb", "Auch für Auszeichnungen die maßgebliche Einheit."]]'::jsonb),

    ('geschichte', 'historische-verkehrsmittel', 'Verkehrsmittel der Vergangenheit',
     'Was kennzeichnet es?',
     'medium', 'Verkehrsmittel',
     'https://de.wikipedia.org/wiki/Verkehrsmittel',
     '[["Sänfte", "Von Trägern geschultert", "Verkehrsmittel der Wohlhabenden in engen Gassen."],
       ["Postkutsche", "Fester Fahrplan mit Pferdewechsel", "Vorbild für spätere Linienverkehre."],
       ["Hochrad", "Riesiges Vorderrad ohne Kette", "Ein Sturz endete kopfüber."],
       ["Pferdestraßenbahn", "Schienen und Zugtiere", "Der Vorläufer der elektrischen Tram."],
       ["Klipper", "Sehr schnelles Segelschiff", "Für Tee und Wolle über die Weltmeere."],
       ["Raddampfer", "Schaufelräder an den Seiten", "Prägte den Verkehr auf dem Mississippi."],
       ["Zeppelin", "Starres Luftschiff mit Traggas", "Transatlantikverkehr bis 1937."],
       ["Ozeandampfer", "Linienschiff für Auswanderer", "Wochenlange Passagen in Klassen getrennt."],
       ["Rikscha", "Von einem Menschen gezogen", "In Asien im 19. Jahrhundert verbreitet."],
       ["Kamelkarawane", "Lasttiere durch die Wüste", "Wasserstellen bestimmten die Route."]]'::jsonb),

    ('geschichte', 'historische-buendnisse', 'Historische Bündnisse',
     'Wer schloss sich zusammen?',
     'hard', 'Bündnis', 'https://de.wikipedia.org/wiki/B%C3%BCndnis',
     '[["Delisch-Attischer Seebund", "Athen und die Inselstaaten", "Aus dem Schutzbündnis wurde ein Reich."],
       ["Hanse", "Nord- und ostdeutsche Städte", "Ein Bund von Kaufleuten, kein Staat."],
       ["Schmalkaldischer Bund", "Protestantische Fürsten", "Gegen den katholischen Kaiser gerichtet."],
       ["Heilige Liga von 1571", "Spanien, Venedig, Papst", "Sie siegte bei Lepanto."],
       ["Rheinbund", "Deutsche Staaten unter Napoleon", "Das Ende des Alten Reiches."],
       ["Heilige Allianz", "Russland, Österreich und Preußen", "Ordnung gegen Revolutionen."],
       ["Dreibund", "Deutschland, Österreich und Italien", "Italien wechselte im Krieg die Seite."],
       ["Entente cordiale", "Frankreich und Großbritannien", "Beilegung kolonialer Streitpunkte."],
       ["Warschauer Pakt", "Sowjetunion und Ostblock", "1991 aufgelöst."],
       ["Europäische Gemeinschaft für Kohle und Stahl", "Sechs Gründerstaaten", "Der erste Schritt zur EU."]]'::jsonb),

    ('geschichte', 'historische-mode', 'Mode & ihre Zeit',
     'In welche Zeit gehört das Kleidungsstück?',
     'medium', 'Mode', 'https://de.wikipedia.org/wiki/Mode',
     '[["Toga", "Antikes Rom", "Nur römischen Bürgern erlaubt."],
       ["Wams", "Spätmittelalter", "Enge Oberbekleidung mit Schnürung."],
       ["Halskrause", "Renaissance", "Gestärkt und teils tellerbreit."],
       ["Allongeperücke", "Barock", "Je höher der Rang, desto mehr Locken."],
       ["Reifrock", "Rokoko", "Machte Türen zum Problem."],
       ["Frack", "Klassizismus", "Aus dem Reitrock hervorgegangen."],
       ["Krinoline", "Mitte des 19. Jahrhunderts", "Ein Gestell trug den weiten Rock."],
       ["Charlestonkleid", "1920er Jahre", "Gerade geschnitten, ohne Taille."],
       ["New Look", "1947", "Betonte Taille nach den Jahren des Mangels."],
       ["Minirock", "1960er Jahre", "In London zum Sinnbild einer Generation geworden."],
       ["Schlaghose", "1970er Jahre", "Unten weit ausgestellt."],
       ["Schulterpolster", "1980er Jahre", "Die Silhouette wurde eckig."]]'::jsonb),

    ('geschichte', 'alte-masseinheiten', 'Alte Maßeinheiten',
     'Woher stammt das Maß?',
     'hard', 'Geschichte der Maße und Gewichte',
     'https://de.wikipedia.org/wiki/Geschichte_der_Ma%C3%9Fe_und_Gewichte',
     '[["Elle", "Länge des Unterarms", "Je nach Stadt unterschiedlich lang."],
       ["Fuß", "Länge eines Fußes", "Rund dreißig Zentimeter, regional verschieden."],
       ["Klafter", "Spannweite der ausgebreiteten Arme", "Für Brennholz und Bergbau genutzt."],
       ["Meile", "Tausend Doppelschritte", "Von mille passus im römischen Heer."],
       ["Morgen", "Fläche eines Vormittags", "Deshalb regional sehr unterschiedlich."],
       ["Scheffel", "Ein Gefäß voll Getreide", "Zugleich Hohlmaß und Flächenmaß."],
       ["Karat", "Gewicht eines Johannisbrotkerns", "Erstaunlich gleichmäßig schwer."],
       ["Knoten", "Seemeile pro Stunde", "Gemessen mit Knoten an einer Logleine."],
       ["Faden", "Ausgebreitete Armspanne beim Loten", "Für Wassertiefen genutzt."],
       ["Rute", "Länge einer Messlatte", "Grundmaß der Feldvermessung."],
       ["Unze", "Zwölftel eines Pfunds", "Der Name bedeutet Zwölftel."],
       ["Pferdestärke", "Leistung eines Zugpferds", "Von James Watt zum Vergleich eingeführt."]]'::jsonb),

    ('geschichte', 'stadtgruendungen', 'Städte & ihre Gründung',
     'Wann wurde die Stadt gegründet?',
     'hard', 'Stadt', 'https://de.wikipedia.org/wiki/Stadt',
     '[["Rom", "753 v. Chr.", "Das Datum stammt aus der Sage."],
       ["Alexandria", "331 v. Chr.", "Von Alexander dem Großen angelegt."],
       ["Konstantinopel", "330", "Als neue Hauptstadt des Römischen Reiches geweiht."],
       ["Bagdad", "762", "Als kreisrunde Stadt entworfen."],
       ["Moskau", "1147", "Erste urkundliche Erwähnung."],
       ["Berlin", "1237", "Erste Erwähnung der Schwesterstadt Cölln."],
       ["Amsterdam", "1275", "Ein Zollprivileg gilt als Geburtsurkunde."],
       ["New York", "1624", "Als niederländische Handelsniederlassung."],
       ["Sankt Petersburg", "1703", "Auf Sumpfland an der Ostsee erbaut."],
       ["Washington", "1790", "Auf neutralem Boden zwischen den Staaten."],
       ["Canberra", "1913", "Als Kompromiss zwischen zwei Rivalinnen geplant."],
       ["Brasília", "1960", "In nur vier Jahren aus dem Boden gestampft."]]'::jsonb),

    ('geschichte', 'hofaemter', 'Ämter bei Hofe',
     'Wofür war das Hofamt zuständig?',
     'hard', 'Hofstaat', 'https://de.wikipedia.org/wiki/Hofstaat',
     '[["Mundschenk", "Getränke des Herrschers", "Er kostete oft selbst vor."],
       ["Truchsess", "Aufsicht über die Tafel", "Verantwortlich für Speisen und Diener."],
       ["Marschall", "Pferde und Stallungen", "Aus dem Stallmeister wurde ein Heerführer."],
       ["Kämmerer", "Kasse und Schatz", "Verwaltete die Einnahmen des Hofes."],
       ["Kanzler", "Urkunden und Siegel", "Aus dem Schreibdienst erwuchs die Regierung."],
       ["Hofnarr", "Unterhaltung und Spott", "Er durfte sagen, was andere nicht durften."],
       ["Vorkoster", "Prüfung auf Gift", "Ein Amt mit überschaubarer Lebenserwartung."],
       ["Zeremonienmeister", "Ablauf und Rangordnung", "Er entschied, wer wo stehen durfte."],
       ["Leibarzt", "Gesundheit des Herrschers", "Oft der einzige Gelehrte in seiner Nähe."],
       ["Falkner", "Betreuung der Jagdvögel", "Die Beizjagd war ein Vorrecht des Adels."],
       ["Hofastronom", "Deutung der Gestirne", "Kepler stand in solchen Diensten."],
       ["Kapellmeister", "Musik am Hof", "Bach und Haydn hatten dieses Amt."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
)

insert into items (quiz_id, category_id, label, position, explanation)
select f.quiz_id, c.id, f.answer, f.position, f.explanation
  from flat f
  join new_categories c
    on c.quiz_id = f.quiz_id
   and c.label = f.label;
