-- Geschichte, file 2 of 2. Twenty questions, medium and hard.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs) as (
    values

    ('geschichte', 'kalter-krieg-jahre', 'Kalter Krieg & Jahreszahlen',
     'In welchem Jahr geschah das?',
     'hard', 'Kalter Krieg', 'https://de.wikipedia.org/wiki/Kalter_Krieg',
     '[["Berlin-Blockade", "1948", "Die Luftbrücke versorgte den Westteil der Stadt fast ein Jahr lang."],
       ["Gründung der NATO", "1949", "Zwölf Staaten schlossen das Nordatlantische Bündnis."],
       ["Beginn des Koreakriegs", "1950", "Truppen des Nordens überschritten den 38. Breitengrad."],
       ["Gründung des Warschauer Pakts", "1955", "Antwort des Ostblocks auf den Beitritt der Bundesrepublik zur NATO."],
       ["Start von Sputnik", "1957", "Der erste Satellit löste im Westen einen Schock aus."],
       ["Mauerbau in Berlin", "1961", "Die DDR riegelte über Nacht den Westteil ab."],
       ["Kubakrise", "1962", "Sowjetische Raketen auf Kuba brachten die Welt an den Rand eines Krieges."],
       ["Prager Frühling", "1968", "Panzer des Warschauer Pakts beendeten den Reformversuch."],
       ["Ende des Vietnamkriegs", "1975", "Mit der Einnahme Saigons endete der Krieg."],
       ["Fall der Berliner Mauer", "1989", "Eine missverständliche Pressekonferenz öffnete abends die Grenze."],
       ["Auflösung der Sowjetunion", "1991", "Fünfzehn Republiken wurden eigene Staaten."],
       ["Reaktorkatastrophe von Tschernobyl", "1986", "Die verspätete Information beschädigte das Vertrauen in Moskau."]]'::jsonb),

    ('geschichte', 'paepste-ereignisse', 'Päpste & ihre Entscheidungen',
     'Wofür steht der Name dieses Papstes?',
     'hard', 'Papst', 'https://de.wikipedia.org/wiki/Papst',
     '[["Leo III.", "Krönung Karls des Großen", "Setzte ihm im Jahr 800 die Kaiserkrone auf."],
       ["Gregor VII.", "Investiturstreit", "Stritt mit Heinrich IV. darum, wer Bischöfe einsetzt."],
       ["Urban II.", "Aufruf zum Kreuzzug", "Rief 1095 in Clermont zum Zug nach Jerusalem auf."],
       ["Innozenz III.", "Höhepunkt der Papstmacht", "Setzte Könige ein und ab."],
       ["Alexander VI.", "Der Borgia-Papst", "Vater des Cesare und der Lucrezia Borgia."],
       ["Leo X.", "Bann gegen Luther", "Verhängte 1521 den Kirchenbann über den Reformator."],
       ["Gregor XIII.", "Kalenderreform", "1582 fielen zehn Tage einfach aus."],
       ["Pius IX.", "Unfehlbarkeitsdogma", "Beschlossen 1870 auf dem Ersten Vatikanischen Konzil."],
       ["Johannes XXIII.", "Zweites Vatikanisches Konzil", "Öffnete die Kirche 1962 für Reformen."],
       ["Johannes Paul II.", "Erster Pole im Amt", "Sein Wirken gilt als Beitrag zum Ende des Ostblocks."],
       ["Benedikt XVI.", "Rücktritt vom Amt", "Trat 2013 als erster Papst seit 1415 zurück."],
       ["Franziskus", "Erster Papst aus Amerika", "Nahm den Namen des Heiligen von Assisi an."]]'::jsonb),

    ('geschichte', 'industrielle-revolution-erfinder', 'Industrielle Revolution & Erfinder',
     'Wer steht hinter dieser Neuerung?',
     'medium', 'Industrielle Revolution',
     'https://de.wikipedia.org/wiki/Industrielle_Revolution',
     '[["Verbesserte Dampfmaschine", "James Watt", "Der getrennte Kondensator sparte den größten Teil der Kohle."],
       ["Spinning Jenny", "James Hargreaves", "Eine Spinnerin konnte plötzlich viele Fäden zugleich ziehen."],
       ["Mechanischer Webstuhl", "Edmund Cartwright", "Machte das Weben zur Fabrikarbeit."],
       ["Dampflokomotive", "George Stephenson", "Seine Rocket gewann 1829 das Rennen von Rainhill."],
       ["Telegraf mit Punkt und Strich", "Samuel Morse", "Nachrichten liefen erstmals schneller als Boten."],
       ["Nähmaschine mit Steppstich", "Elias Howe", "Erhielt 1846 das Patent auf den Doppelsteppstich."],
       ["Stahl aus der Birne", "Henry Bessemer", "Eingeblasene Luft brannte den Kohlenstoff aus dem Roheisen."],
       ["Dieselmotor", "Rudolf Diesel", "Zündung allein durch die Hitze der verdichteten Luft."],
       ["Fotografie auf Silberplatte", "Louis Daguerre", "1839 vorgestellt, jedes Bild ein Unikat."],
       ["Starres Luftschiff", "Ferdinand von Zeppelin", "Erster Aufstieg 1900 über dem Bodensee."],
       ["Motorflugzeug", "Brüder Wright", "Erster gesteuerter Motorflug 1903 in Kitty Hawk."],
       ["Ammoniak aus Luft", "Fritz Haber", "Machte Kunstdünger und damit Brot für Milliarden möglich."]]'::jsonb),

    ('geschichte', 'us-praesidenten-taten', 'US-Präsidenten & ihre Amtszeit',
     'Wofür steht der Name dieses Präsidenten?',
     'hard', 'Präsident der Vereinigten Staaten',
     'https://de.wikipedia.org/wiki/Pr%C3%A4sident_der_Vereinigten_Staaten',
     '[["Thomas Jefferson", "Kauf von Louisiana", "Verdoppelte 1803 das Staatsgebiet für 15 Millionen Dollar."],
       ["Abraham Lincoln", "Ende der Sklaverei", "Seine Proklamation von 1863 erklärte die Sklaven für frei."],
       ["Theodore Roosevelt", "Bau des Panamakanals", "Unterstützte die Abspaltung Panamas von Kolumbien."],
       ["Woodrow Wilson", "Vierzehn Punkte", "Sein Programm sollte nach 1918 den Frieden ordnen."],
       ["Franklin D. Roosevelt", "New Deal", "Antwort auf die Weltwirtschaftskrise mit Staatsprogrammen."],
       ["Harry S. Truman", "Marshallplan", "Milliardenhilfe für den Wiederaufbau Westeuropas."],
       ["Dwight D. Eisenhower", "Interstate Highways", "Ließ das Netz der Fernstraßen anlegen."],
       ["John F. Kennedy", "Mondprogramm", "Setzte 1961 das Ziel, noch im Jahrzehnt zum Mond zu fliegen."],
       ["Richard Nixon", "Watergate", "Trat 1974 als bisher einziger Präsident zurück."],
       ["Ronald Reagan", "Aufrüstung und Entspannung", "Erst Rüstungsschub, dann Abrüstungsverträge mit Gorbatschow."],
       ["Bill Clinton", "Abkommen von Dayton", "Vermittelte 1995 das Ende des Bosnienkriegs."],
       ["Barack Obama", "Krankenversicherung für alle", "Sein Gesetz von 2010 versicherte Millionen zusätzlich."]]'::jsonb),

    ('geschichte', 'chinesische-dynastien', 'Chinesische Dynastien',
     'Wofür steht diese Dynastie?',
     'hard', 'Geschichte Chinas',
     'https://de.wikipedia.org/wiki/Geschichte_Chinas',
     '[["Shang", "Orakelknochen", "Älteste chinesische Schriftzeugnisse, in Knochen geritzt."],
       ["Zhou", "Mandat des Himmels", "Begründete den Anspruch, rechtmäßig zu herrschen."],
       ["Qin", "Terrakottaarmee", "Der erste Kaiser ließ sich ein ganzes Heer aus Ton mitgeben."],
       ["Han", "Öffnung der Seidenstraße", "Gesandtschaften nach Westen begründeten den Fernhandel."],
       ["Sui", "Bau des Kaiserkanals", "Verband Nord und Süd über mehr als 1700 Kilometer."],
       ["Tang", "Blütezeit der Dichtung", "Li Bai und Du Fu schrieben in dieser Zeit."],
       ["Song", "Erstes Papiergeld", "Gedruckte Scheine ersetzten schwere Münzen."],
       ["Yuan", "Herrschaft der Mongolen", "Kublai Khan regierte als Kaiser von Peking aus."],
       ["Ming", "Verbotene Stadt", "Bauten den Kaiserpalast und schickten Flotten bis Afrika."],
       ["Qing", "Letzte Kaiserdynastie", "Endete 1912 mit der Abdankung des Kindkaisers Puyi."]]'::jsonb),

    ('geschichte', 'duelle-der-geschichte', 'Gegenspieler der Geschichte',
     'Wer war der große Gegenspieler?',
     'hard', 'Krieg', 'https://de.wikipedia.org/wiki/Krieg',
     '[["Hannibal", "Scipio", "Der Römer schlug ihn 202 v. Chr. bei Zama."],
       ["Caesar", "Pompeius", "Der Bürgerkrieg endete 48 v. Chr. bei Pharsalos."],
       ["Octavian", "Marcus Antonius", "Die Seeschlacht bei Actium entschied das Reich."],
       ["Themistokles", "Xerxes", "Der Perserkönig verlor 480 v. Chr. bei Salamis die Flotte."],
       ["Richard Löwenherz", "Saladin", "Der Dritte Kreuzzug endete mit einem Waffenstillstand."],
       ["Elisabeth I.", "Philipp II.", "Seine Armada scheiterte 1588 vor England."],
       ["Napoleon", "Wellington", "Der britische Feldherr entschied 1815 Waterloo."],
       ["Bismarck", "Napoleon III.", "Der Krieg von 1870 kostete den Franzosen den Thron."],
       ["Abraham Lincoln", "Jefferson Davis", "Präsident des Nordens gegen den Präsidenten der Konföderation."],
       ["Stalin", "Trotzki", "Der Rivale wurde verbannt und 1940 in Mexiko ermordet."],
       ["Cortés", "Moctezuma II.", "Der Aztekenherrscher starb während der Belagerung seiner Hauptstadt."],
       ["Marcus Aurelius", "Markomannen", "Jahrzehntelange Kämpfe an der Donaugrenze."]]'::jsonb),

    ('geschichte', 'koeniginnen-laender', 'Königinnen & ihre Länder',
     'Über welches Land herrschte sie?',
     'medium', 'Königin', 'https://de.wikipedia.org/wiki/K%C3%B6nigin',
     '[["Maria Theresia", "Österreich", "Regierte 40 Jahre und reformierte Schule und Verwaltung."],
       ["Isabella I.", "Kastilien", "Finanzierte die Fahrt des Kolumbus."],
       ["Christina", "Schweden", "Dankte 1654 ab und ging nach Rom."],
       ["Wilhelmina", "Niederlande", "Führte ihr Land aus dem Londoner Exil durch den Krieg."],
       ["Victoria", "Vereinigtes Königreich", "Ihr Name steht für ein ganzes Zeitalter."],
       ["Margarethe I.", "Dänemark", "Vereinte 1397 drei Reiche in der Kalmarer Union."],
       ["Jadwiga", "Polen", "Wurde als Mädchen zum König gekrönt, nicht zur Königin."],
       ["Zenobia", "Palmyra", "Trotzte Rom, bis Kaiser Aurelian sie 272 besiegte."],
       ["Wu Zetian", "China", "Einzige Frau, die als Kaiserin aus eigenem Recht regierte."],
       ["Nzinga", "Ndongo", "Widerstand über Jahrzehnte gegen die Portugiesen."],
       ["Ranavalona I.", "Madagaskar", "Hielt europäische Mächte 33 Jahre lang von der Insel fern."],
       ["Hatschepsut", "Ägypten", "Ihre Nachfolger ließen ihren Namen von Denkmälern tilgen."]]'::jsonb),

    ('geschichte', 'seuchen-zeiten', 'Seuchen & ihre Zeit',
     'Wann brach die Seuche aus?',
     'hard', 'Epidemie', 'https://de.wikipedia.org/wiki/Epidemie',
     '[["Antoninische Pest", "2. Jahrhundert", "Heimkehrende Legionen brachten sie ins Römische Reich."],
       ["Justinianische Pest", "6. Jahrhundert", "Traf Konstantinopel auf der Höhe seiner Macht."],
       ["Schwarzer Tod", "14. Jahrhundert", "Kostete in wenigen Jahren ein Drittel Europas das Leben."],
       ["Große Pest von London", "1665", "Ein Jahr später brannte die Stadt ab."],
       ["Pocken in Amerika", "16. Jahrhundert", "Eingeschleppt von Europäern, verheerend für die Ureinwohner."],
       ["Cholera in Soho", "1854", "John Snow fand die verseuchte Wasserpumpe."],
       ["Irische Hungersnot", "1845", "Die Kartoffelfäule trieb Millionen außer Landes."],
       ["Spanische Grippe", "1918", "Forderte weltweit mehr Opfer als der Erste Weltkrieg."],
       ["Ausrottung der Pocken", "1980", "Bis heute die einzige ausgerottete Menschenkrankheit."],
       ["Beginn der Aids-Epidemie", "1981", "Erste Berichte über eine unbekannte Immunschwäche."],
       ["SARS", "2003", "Eine Lungenkrankheit sprang von Südchina in die Welt."],
       ["Covid-19", "2020", "Innerhalb von Wochen legte sie das öffentliche Leben lahm."]]'::jsonb),

    ('geschichte', 'erste-male-personen', 'Die Ersten & ihre Namen',
     'Wer hat das als Erster oder Erste geschafft?',
     'medium', 'Entdecker', 'https://de.wikipedia.org/wiki/Entdecker',
     '[["Erster Mensch im All", "Juri Gagarin", "Umrundete 1961 in 108 Minuten die Erde."],
       ["Erste Frau im All", "Walentina Tereschkowa", "Flog 1963 allein, 48 Erdumrundungen lang."],
       ["Erster Mensch auf dem Mond", "Neil Armstrong", "Setzte 1969 den Fuß in den Staub des Mare Tranquillitatis."],
       ["Alleinflug über den Atlantik", "Charles Lindbergh", "33 Stunden von New York nach Paris, 1927."],
       ["Erste Frau mit Nobelpreis", "Marie Curie", "Erhielt ihn 1903 für Physik, später noch einmal für Chemie."],
       ["Erste Besteigung des Everest", "Edmund Hillary", "Stand 1953 mit Tenzing Norgay auf dem Gipfel."],
       ["Erste Einhandumsegelung", "Joshua Slocum", "Drei Jahre allein an Bord der Spray."],
       ["Erste Herztransplantation", "Christiaan Barnard", "Operierte 1967 in Kapstadt."],
       ["Erste Fernsehübertragung", "John Logie Baird", "Zeigte 1926 in London bewegte Bilder."],
       ["Erste Regierungschefin der Welt", "Sirimavo Bandaranaike", "Wurde 1960 in Ceylon Premierministerin."],
       ["Erster Flug über den Ärmelkanal", "Louis Blériot", "Landete 1909 nach 37 Minuten in Dover."],
       ["Erste Frau als Pilotin über den Atlantik", "Amelia Earhart", "Flog 1932 allein von Neufundland nach Irland."]]'::jsonb),

    ('geschichte', 'handelsrouten-waren', 'Handelswege & ihre Waren',
     'Womit wurde auf diesem Weg vor allem gehandelt?',
     'medium', 'Handelsweg', 'https://de.wikipedia.org/wiki/Handelsweg',
     '[["Seidenstraße", "Seide", "Der Stoff aus China war in Rom mit Gold aufzuwiegen."],
       ["Weihrauchstraße", "Weihrauch", "Aus Südarabien über die Wüste zum Mittelmeer."],
       ["Bernsteinstraße", "Bernstein", "Von der Ostsee bis an die Adria."],
       ["Transsaharahandel", "Gold", "Karawanen brachten es aus Westafrika nach Norden."],
       ["Alte Salzstraße", "Salz", "Von Lüneburg nach Lübeck, für das Pökeln des Herings."],
       ["Gewürzroute nach Indien", "Pfeffer", "Er war der Grund, den Seeweg überhaupt zu suchen."],
       ["Spanische Silberflotte", "Silber", "Aus den Minen von Potosí nach Sevilla."],
       ["Sibirischer Pelzhandel", "Zobelfelle", "Trieb die russische Ausdehnung bis zum Pazifik."],
       ["Teestraße nach Russland", "Tee", "Kamelkarawanen brauchten von China ein halbes Jahr."],
       ["Hansehandel im Ostseeraum", "Getreide", "Aus dem Osten in die wachsenden Städte des Westens."],
       ["Amber Road der Neuzeit", "Kupfer", "Erz aus Schweden für die Gießereien des Kontinents."],
       ["Kabelverbindung nach Indien", "Nachrichten", "Telegrafenkabel machten Handel über Kontinente hinweg schnell."]]'::jsonb),

    ('geschichte', 'historische-waehrungen', 'Historische Währungen',
     'In welchem Land oder Reich wurde damit bezahlt?',
     'medium', 'Währung', 'https://de.wikipedia.org/wiki/W%C3%A4hrung',
     '[["Sesterz", "Römisches Reich", "Rechnungseinheit der Kaiserzeit."],
       ["Dukaten", "Venedig", "Goldmünze, jahrhundertelang im Mittelmeerhandel anerkannt."],
       ["Reichsmark", "Deutsches Reich", "1924 eingeführt, 1948 durch die D-Mark ersetzt."],
       ["Mark der DDR", "DDR", "Im Westen nicht umtauschbar, im Osten alleiniges Zahlungsmittel."],
       ["Schilling", "Österreich", "Bis zur Einführung des Euro 2002 in Gebrauch."],
       ["Peseta", "Spanien", "Ihr Name bedeutet kleines Gewichtsstück."],
       ["Escudo", "Portugal", "Benannt nach dem Wappenschild auf der Münze."],
       ["Drachme", "Griechenland", "Eine der ältesten Währungen überhaupt, schon in der Antike."],
       ["Gulden", "Niederlande", "Kürzel fl, vom Florin aus Florenz."],
       ["Franc", "Frankreich", "Von 1360 bis zur Euro-Einführung in Gebrauch."],
       ["Lira", "Italien", "Vom lateinischen libra, dem Pfund."],
       ["Rubel der Sowjetunion", "Sowjetunion", "Kurs wurde staatlich festgesetzt, nicht am Markt."]]'::jsonb),

    ('geschichte', 'frauen-der-geschichte', 'Frauen der Geschichte',
     'Wofür steht ihr Name?',
     'medium', 'Frauengeschichte',
     'https://de.wikipedia.org/wiki/Frauengeschichte',
     '[["Jeanne d''Arc", "Entsatz von Orléans", "Brach 1429 die Belagerung und wurde zwei Jahre später verbrannt."],
       ["Florence Nightingale", "Moderne Krankenpflege", "Führte im Krimkrieg Hygiene und Statistik in Lazarette ein."],
       ["Harriet Tubman", "Fluchthilfe für Sklaven", "Führte über die Underground Railroad Dutzende in die Freiheit."],
       ["Ada Lovelace", "Erstes Computerprogramm", "Schrieb Notizen zu einer Rechenmaschine, die nie gebaut wurde."],
       ["Emmeline Pankhurst", "Kampf um das Frauenwahlrecht", "Ihre Bewegung nahm dafür auch Haft in Kauf."],
       ["Clara Zetkin", "Internationaler Frauentag", "Regte ihn 1910 auf einer Konferenz in Kopenhagen an."],
       ["Rosa Parks", "Busboykott von Montgomery", "Blieb 1955 sitzen und löste eine Bewegung aus."],
       ["Sophie Scholl", "Weiße Rose", "Verteilte 1943 Flugblätter gegen das Regime."],
       ["Simone de Beauvoir", "Das andere Geschlecht", "Ihr Buch von 1949 wurde Grundlage der neuen Frauenbewegung."],
       ["Mutter Teresa", "Armenhilfe in Kalkutta", "Ihr Orden pflegte Sterbende, die niemand aufnahm."],
       ["Malala Yousafzai", "Recht auf Schulbildung", "Überlebte ein Attentat und erhielt den Friedensnobelpreis."],
       ["Hildegard von Bingen", "Klostermedizin", "Äbtissin, Komponistin und Verfasserin von Heilkundeschriften."]]'::jsonb),

    ('geschichte', 'alte-universitaeten', 'Alte Universitäten & Länder',
     'In welchem Land steht die Universität?',
     'medium', 'Universität', 'https://de.wikipedia.org/wiki/Universit%C3%A4t',
     '[["Bologna", "Italien", "1088 gegründet, älteste Universität Europas."],
       ["Oxford", "England", "Lehre ist dort seit 1096 bezeugt."],
       ["Sorbonne", "Frankreich", "Aus einem Kolleg von 1257 hervorgegangen."],
       ["Salamanca", "Spanien", "1218 gegründet, Gutachterin für Kolumbus’ Pläne."],
       ["Coimbra", "Portugal", "1290 gegründet, später in den Königspalast verlegt."],
       ["Karls-Universität", "Tschechien", "1348 gegründet, die älteste nördlich der Alpen."],
       ["Jagiellonen-Universität", "Polen", "1364 gegründet, Studienort des Kopernikus."],
       ["Wien", "Österreich", "1365 gegründet, älteste Universität im deutschen Sprachraum in Betrieb."],
       ["Heidelberg", "Deutschland", "1386 gegründet, älteste des heutigen Bundesgebiets."],
       ["Leuven", "Belgien", "1425 gegründet, Wirkungsort von Erasmus."],
       ["Uppsala", "Schweden", "1477 gegründet, älteste Skandinaviens."],
       ["Harvard", "USA", "1636 gegründet, älteste Hochschule des Landes."]]'::jsonb),

    ('geschichte', 'kriege-gegner', 'Kriege & ihre Gegner',
     'Wer stand sich in diesem Krieg gegenüber?',
     'medium', 'Krieg', 'https://de.wikipedia.org/wiki/Krieg',
     '[["Peloponnesischer Krieg", "Athen und Sparta", "27 Jahre Kampf um die Vorherrschaft in Griechenland."],
       ["Punische Kriege", "Rom und Karthago", "Drei Kriege, am Ende lag Karthago in Trümmern."],
       ["Hundertjähriger Krieg", "England und Frankreich", "Streit um den französischen Thron, mit langen Pausen."],
       ["Krimkrieg", "Russland und Osmanen", "Briten und Franzosen kämpften auf osmanischer Seite."],
       ["Opiumkriege", "China und Großbritannien", "Am Ende musste China Hongkong abtreten."],
       ["Sezessionskrieg", "Nord- und Südstaaten", "Elf Südstaaten hatten sich von der Union losgesagt."],
       ["Burenkrieg", "Briten und Buren", "Guerillakrieg im südlichen Afrika um die Goldfelder."],
       ["Winterkrieg", "Finnland und Sowjetunion", "Finnland hielt der Übermacht 105 Tage stand."],
       ["Koreakrieg", "Nord- und Südkorea", "Endete 1953 mit einem Waffenstillstand, nicht mit Frieden."],
       ["Falklandkrieg", "Argentinien und Großbritannien", "Zehn Wochen Kampf um Inseln im Südatlantik."],
       ["Sechstagekrieg", "Israel und arabische Nachbarn", "1967 änderte sich die Landkarte der Region in einer Woche."],
       ["Dreißigjähriger Krieg", "Katholiken und Protestanten", "Aus Glaubensstreit wurde ein Krieg um Macht in Europa."]]'::jsonb),

    ('geschichte', 'konferenzen-orte', 'Konferenzen & Abkommen',
     'Wo wurde verhandelt?',
     'medium', 'Konferenz', 'https://de.wikipedia.org/wiki/Konferenz',
     '[["Konferenz von Jalta", "Krim", "Roosevelt, Churchill und Stalin teilten 1945 die Einflusszonen."],
       ["Konferenz von Teheran", "Iran", "1943 erstes Treffen der drei Großen."],
       ["Konferenz von Casablanca", "Marokko", "1943 beschlossen die Alliierten die bedingungslose Kapitulation als Ziel."],
       ["Abkommen von Bretton Woods", "New Hampshire", "1944 entstanden Weltbank und Währungsfonds."],
       ["Gründung der Vereinten Nationen", "San Francisco", "1945 unterzeichneten 50 Staaten die Charta."],
       ["Bandung-Konferenz", "Indonesien", "1955 fanden die blockfreien Staaten zusammen."],
       ["KSZE-Schlussakte", "Finnland", "1975 verständigten sich Ost und West auf Grundsätze."],
       ["Camp-David-Abkommen", "Maryland", "1978 schlossen Ägypten und Israel Frieden."],
       ["Abkommen von Dayton", "Ohio", "1995 endete der Krieg in Bosnien."],
       ["Kyoto-Protokoll", "Japan", "1997 wurden erstmals Klimaziele völkerrechtlich vereinbart."],
       ["Pariser Klimaabkommen", "Frankreich", "2015 einigten sich fast alle Staaten auf das Zwei-Grad-Ziel."],
       ["Konferenz von Wien", "Österreich", "1815 ordneten die Mächte Europa nach Napoleon neu."]]'::jsonb),

    ('geschichte', 'entdecker-herkunft', 'Entdecker & ihre Herkunft',
     'Aus welchem Land stammte der Reisende?',
     'medium', 'Entdecker', 'https://de.wikipedia.org/wiki/Entdecker',
     '[["Christoph Kolumbus", "Italien", "Geboren in Genua, gefahren im Dienst Spaniens."],
       ["Ferdinand Magellan", "Portugal", "Segelte für die spanische Krone."],
       ["Hernán Cortés", "Spanien", "Aus der Extremadura, wie viele Eroberer."],
       ["James Cook", "England", "Sohn eines Landarbeiters aus Yorkshire."],
       ["Samuel de Champlain", "Frankreich", "Gründete 1608 die Stadt Québec."],
       ["Abel Tasman", "Niederlande", "Nach ihm ist Tasmanien benannt."],
       ["Vitus Bering", "Dänemark", "Fuhr im Dienst des russischen Zaren."],
       ["Roald Amundsen", "Norwegen", "Erreichte den Südpol und durchfuhr die Nordwestpassage."],
       ["David Livingstone", "Schottland", "Missionar und Forscher in Zentralafrika."],
       ["Alexander von Humboldt", "Deutschland", "Bereiste fünf Jahre lang Südamerika."],
       ["Henry Morton Stanley", "Wales", "Fand Livingstone 1871 am Tanganjikasee."],
       ["Adolf Erik Nordenskiöld", "Schweden", "Durchfuhr als Erster die Nordostpassage."]]'::jsonb),

    ('geschichte', 'staatsmaenner-laender', 'Staatsmänner & ihre Staaten',
     'Für welchen Staat stand die Person?',
     'medium', 'Staatsmann', 'https://de.wikipedia.org/wiki/Staatsmann',
     '[["Otto von Bismarck", "Deutsches Reich", "Erster Reichskanzler, im Amt bis 1890."],
       ["Kardinal Richelieu", "Königreich Frankreich", "Baute als Minister die königliche Zentralmacht aus."],
       ["Klemens von Metternich", "Kaisertum Österreich", "Prägte die europäische Ordnung nach 1815."],
       ["Camillo Cavour", "Königreich Sardinien", "Betrieb von Turin aus die Einigung Italiens."],
       ["Winston Churchill", "Vereinigtes Königreich", "Führte das Land durch den Zweiten Weltkrieg."],
       ["Konrad Adenauer", "Bundesrepublik Deutschland", "Erster Kanzler, band das Land an den Westen."],
       ["Jawaharlal Nehru", "Indien", "Erster Premierminister nach der Unabhängigkeit."],
       ["Wladimir Lenin", "Sowjetrussland", "Führte 1917 die Bolschewiki an die Macht."],
       ["Sun Yat-sen", "Republik China", "Gilt als Vater der Revolution von 1911."],
       ["Charles de Gaulle", "Frankreich", "Rief 1940 aus London zum Widerstand auf."],
       ["Willy Brandt", "Bundesrepublik", "Kniefall in Warschau und Ostpolitik."],
       ["Michail Gorbatschow", "Sowjetunion", "Glasnost und Perestroika leiteten das Ende ein."]]'::jsonb),

    ('geschichte', 'bibliotheken-orte', 'Alte Bibliotheken & Wissensorte',
     'Wo stand oder steht die Sammlung?',
     'hard', 'Bibliothek', 'https://de.wikipedia.org/wiki/Bibliothek',
     '[["Bibliothek von Alexandria", "Ägypten", "Größte Sammlung der Antike, über Jahrhunderte verloren."],
       ["Haus der Weisheit", "Bagdad", "Übersetzte griechische Werke ins Arabische."],
       ["Bibliothek von Pergamon", "Türkei", "Der Streit mit Alexandria förderte die Erfindung des Pergaments."],
       ["Stiftsbibliothek Sankt Gallen", "Schweiz", "Barocksaal über einer Sammlung aus dem 8. Jahrhundert."],
       ["Bibliotheca Palatina", "Heidelberg", "1623 als Kriegsbeute nach Rom gebracht."],
       ["Vatikanische Bibliothek", "Rom", "1475 gegründet, mit Handschriften aus dem ganzen Mittelmeerraum."],
       ["Kloster Nalanda", "Indien", "Buddhistische Hochschule, im 12. Jahrhundert zerstört."],
       ["Handschriften von Timbuktu", "Mali", "Zehntausende Bände, vor Angriffen in Sicherheit gebracht."],
       ["Höhlenbibliothek von Dunhuang", "China", "Zugemauerte Kammer voller Schriftrollen an der Seidenstraße."],
       ["Archiv von Ebla", "Syrien", "Tontafeln eines Palastes aus dem 3. Jahrtausend v. Chr."],
       ["Bibliothek des Assurbanipal", "Ninive", "Keilschrifttafeln, darunter das Gilgamesch-Epos."],
       ["Bodleian Library", "Oxford", "Seit 1602 Pflichtexemplarbibliothek des Landes."]]'::jsonb),

    ('geschichte', 'historische-berufe', 'Alte Handwerksberufe',
     'Womit hatte dieser Beruf zu tun?',
     'medium', 'Handwerk', 'https://de.wikipedia.org/wiki/Handwerk',
     '[["Köhler", "Holzkohle", "Verschwelte Holz in Meilern unter Luftabschluss."],
       ["Gerber", "Leder", "Machte Tierhaut mit Lohe haltbar, geruchsintensiv am Stadtrand."],
       ["Böttcher", "Fässer", "Bog Dauben und trieb Reifen darüber."],
       ["Müller", "Mehl", "Mahlte Korn mit Wasser- oder Windkraft."],
       ["Bader", "Rasur und Zähne", "Betrieb die Badestube und zog nebenbei Zähne."],
       ["Seiler", "Seile", "Drehte Hanffasern auf langen Reeperbahnen."],
       ["Schmied", "Eisen", "Formte glühendes Metall auf dem Amboss."],
       ["Zimmerer", "Dachstühle", "Verband Balken ohne Nägel, mit Zapfen und Zargen."],
       ["Färber", "Stofffarben", "Arbeitete mit Waid, Krapp und später Indigo."],
       ["Schuster", "Schuhe", "Nähte Sohlen mit Pech und Draht."],
       ["Pergamenter", "Beschreibstoff", "Bereitete Tierhaut für Handschriften auf."],
       ["Salzsieder", "Salz", "Kochte Sole in flachen Pfannen ein."]]'::jsonb),

    ('geschichte', 'historiker-werke', 'Geschichtsschreiber & ihre Werke',
     'Welches Werk stammt von dieser Person?',
     'hard', 'Geschichtsschreibung',
     'https://de.wikipedia.org/wiki/Geschichtsschreibung',
     '[["Herodot", "Historien", "Gilt als Vater der Geschichtsschreibung."],
       ["Thukydides", "Der Peloponnesische Krieg", "Schrieb über den Krieg, den er selbst miterlebte."],
       ["Sima Qian", "Shiji", "Legte das Muster für zwei Jahrtausende chinesischer Annalen."],
       ["Livius", "Ab urbe condita", "Erzählte Roms Geschichte von der Gründung an."],
       ["Tacitus", "Germania", "Beschrieb die Stämme jenseits des Rheins."],
       ["Sueton", "Kaiserviten", "Zwölf Kaiserbiografien, reich an Anekdoten."],
       ["Flavius Josephus", "Der Jüdische Krieg", "Augenzeuge des Aufstands gegen Rom."],
       ["Beda Venerabilis", "Kirchengeschichte Englands", "Verbreitete die Zählung nach Christi Geburt."],
       ["Ibn Chaldun", "Muqaddima", "Erklärte den Aufstieg und Verfall von Dynastien."],
       ["Edward Gibbon", "Verfall und Untergang Roms", "Sechs Bände über tausend Jahre Reichsgeschichte."],
       ["Leopold von Ranke", "Die römischen Päpste", "Wollte zeigen, wie es eigentlich gewesen ist."],
       ["Fernand Braudel", "Das Mittelmeer", "Schrieb Geschichte über Jahrhunderte statt über Ereignisse."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
)

insert into items (quiz_id, category_id, label, position, explanation)
select f.quiz_id, c.id, f.answer, f.position, f.explanation
  from flat f
  join new_categories c
    on c.quiz_id = f.quiz_id
   and c.label = f.label;
