-- Geschichte, file 1 of 2. Twenty questions, medium and hard.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs) as (
    values

    ('geschichte', 'antike-staetten-laender', 'Antike Stätten & heutige Länder',
     'In welchem heutigen Land liegt die antike Stätte?',
     'hard', 'Archäologie', 'https://de.wikipedia.org/wiki/Arch%C3%A4ologie',
     '[["Karthago", "Tunesien", "Von Rom 146 v. Chr. zerstört, später als Kolonie neu gebaut."],
       ["Babylon", "Irak", "Stadt am Euphrat mit dem Ischtar-Tor."],
       ["Troja", "Türkei", "1871 von Heinrich Schliemann ausgegraben."],
       ["Palmyra", "Syrien", "Oasenstadt der Königin Zenobia, 2015 schwer beschädigt."],
       ["Knossos", "Griechenland", "Palast der minoischen Kultur auf Kreta."],
       ["Teotihuacán", "Mexiko", "Stadt mit Sonnen- und Mondpyramide, schon vor den Azteken verlassen."],
       ["Timgad", "Algerien", "Römische Koloniestadt mit erhaltenem Schachbrettgrundriss."],
       ["Leptis Magna", "Libyen", "Heimatstadt des Kaisers Septimius Severus."],
       ["Mohenjo-Daro", "Pakistan", "Planstadt der Indus-Kultur mit Kanalisation."],
       ["Masada", "Israel", "Bergfestung, in der sich Aufständische 73 n. Chr. ergaben."],
       ["Great Zimbabwe", "Simbabwe", "Steinstadt, die dem heutigen Staat den Namen gab."],
       ["Pompeji", "Italien", "79 n. Chr. unter der Asche des Vesuvs begraben."]]'::jsonb),

    ('geschichte', 'vertraege-jahre', 'Verträge & Jahreszahlen',
     'In welchem Jahr wurde der Vertrag geschlossen?',
     'hard', 'Friedensvertrag', 'https://de.wikipedia.org/wiki/Friedensvertrag',
     '[["Vertrag von Tordesillas", "1494", "Teilte die neu entdeckte Welt zwischen Spanien und Portugal."],
       ["Augsburger Religionsfriede", "1555", "Der Landesherr bestimmt fortan die Konfession."],
       ["Westfälischer Friede", "1648", "Beendete den Dreißigjährigen Krieg."],
       ["Frieden von Utrecht", "1713", "Beendete den Spanischen Erbfolgekrieg."],
       ["Wiener Schlussakte", "1815", "Ordnete Europa nach Napoleons Niederlage neu."],
       ["Vertrag von Versailles", "1919", "Legte Deutschland nach dem Ersten Weltkrieg die Bedingungen auf."],
       ["Vertrag von Trianon", "1920", "Ungarn verlor zwei Drittel seines Gebiets."],
       ["Vertrag von Rapallo", "1922", "Deutschland und Sowjetrussland nahmen Beziehungen auf."],
       ["Römische Verträge", "1957", "Gründeten die Europäische Wirtschaftsgemeinschaft."],
       ["Zwei-plus-Vier-Vertrag", "1990", "Machte den Weg zur deutschen Einheit völkerrechtlich frei."],
       ["Vertrag von Maastricht", "1992", "Gründete die Europäische Union."],
       ["Vertrag von Lissabon", "2007", "Gab der EU ihre heutige Struktur."]]'::jsonb),

    ('geschichte', 'entdecker-leistungen', 'Entdecker & ihre Fahrten',
     'Wofür steht der Name dieses Reisenden?',
     'medium', 'Entdeckungsreise',
     'https://de.wikipedia.org/wiki/Entdeckungsreise',
     '[["Christoph Kolumbus", "Karibische Inseln", "Erreichte 1492 die Bahamas, im Glauben, in Indien zu sein."],
       ["Vasco da Gama", "Seeweg nach Indien", "Erreichte 1498 Calicut um Afrika herum."],
       ["Ferdinand Magellan", "Erste Weltumsegelung", "Er starb unterwegs; seine Mannschaft vollendete die Fahrt."],
       ["Bartolomeu Dias", "Kap der Guten Hoffnung", "Umrundete 1488 die Südspitze Afrikas."],
       ["Hernán Cortés", "Aztekenreich", "Unterwarf 1521 die Hauptstadt Tenochtitlán."],
       ["Francisco Pizarro", "Inkareich", "Nahm 1532 den Herrscher Atahualpa gefangen."],
       ["James Cook", "Ostküste Australiens", "Kartierte sie 1770 auf seiner ersten Reise."],
       ["Roald Amundsen", "Südpol", "Erreichte ihn 1911, einen Monat vor Scott."],
       ["Robert Peary", "Nordpol", "Beanspruchte 1909 als Erster den Pol."],
       ["David Livingstone", "Victoriafälle", "Benannte sie 1855 nach der britischen Königin."],
       ["Alexander von Humboldt", "Orinoco", "Wies die Verbindung zum Amazonasbecken nach."],
       ["Marco Polo", "Handelsweg nach China", "Beschrieb den Hof des Kublai Khan."]]'::jsonb),

    ('geschichte', 'revolutionen-jahre', 'Revolutionen & Jahreszahlen',
     'In welchem Jahr begann der Umsturz?',
     'hard', 'Revolution', 'https://de.wikipedia.org/wiki/Revolution',
     '[["Glorious Revolution", "1688", "Wilhelm von Oranien übernahm den englischen Thron."],
       ["Französische Revolution", "1789", "Der Sturm auf die Bastille wurde ihr Sinnbild."],
       ["Märzrevolution", "1848", "Aufstände in fast ganz Europa, Parlament in der Paulskirche."],
       ["Meiji-Restauration", "1868", "Japan öffnete sich und modernisierte sich im Eiltempo."],
       ["Xinhai-Revolution", "1911", "Beendete die Kaiserzeit in China."],
       ["Oktoberrevolution", "1917", "Die Bolschewiki übernahmen die Macht in Russland."],
       ["Novemberrevolution", "1918", "Beendete die Monarchie in Deutschland."],
       ["Ungarnaufstand", "1956", "Sowjetische Panzer schlugen ihn nieder."],
       ["Kubanische Revolution", "1959", "Fidel Castro stürzte den Machthaber Batista."],
       ["Nelkenrevolution", "1974", "Unblutiger Umsturz in Portugal, benannt nach der Blume."],
       ["Islamische Revolution", "1979", "Der Schah floh, Ajatollah Chomeini kehrte zurück."],
       ["Samtene Revolution", "1989", "Führte in der Tschechoslowakei ohne Gewalt zum Machtwechsel."]]'::jsonb),

    ('geschichte', 'roemische-kaiser', 'Römische Kaiser',
     'Wofür steht der Name dieses Kaisers?',
     'hard', 'Römischer Kaiser',
     'https://de.wikipedia.org/wiki/R%C3%B6mischer_Kaiser',
     '[["Augustus", "Erster Kaiser Roms", "Regierte ab 27 v. Chr. und begründete den Prinzipat."],
       ["Claudius", "Eroberung Britanniens", "Ließ die Insel ab 43 n. Chr. zur Provinz machen."],
       ["Nero", "Brand Roms", "Der Brand von 64 n. Chr. hängt bis heute an seinem Namen."],
       ["Vespasian", "Bau des Kolosseums", "Begann das Amphitheater, das sein Sohn einweihte."],
       ["Titus", "Zerstörung Jerusalems", "Nahm die Stadt 70 n. Chr. ein, mit dem Tempel."],
       ["Trajan", "Größte Ausdehnung", "Unter ihm reichte das Reich bis an den Persischen Golf."],
       ["Hadrian", "Wall in Britannien", "Sicherte die Nordgrenze mit einem 117 Kilometer langen Wall."],
       ["Mark Aurel", "Selbstbetrachtungen", "Schrieb im Feldlager sein philosophisches Tagebuch."],
       ["Diokletian", "Herrschaft zu viert", "Teilte die Macht auf vier Herrscher auf."],
       ["Konstantin", "Duldung der Christen", "Die Mailänder Vereinbarung von 313 beendete die Verfolgung."],
       ["Theodosius", "Endgültige Reichsteilung", "Nach seinem Tod 395 blieb das Reich geteilt."],
       ["Caligula", "Willkürherrschaft", "Wurde nach vier Jahren von der eigenen Garde ermordet."]]'::jsonb),

    ('geschichte', 'pharaonen', 'Pharaonen & ihre Spuren',
     'Wofür steht der Name dieses Pharaos?',
     'hard', 'Pharao', 'https://de.wikipedia.org/wiki/Pharao',
     '[["Djoser", "Stufenpyramide", "Sein Baumeister Imhotep stapelte sechs Mastabas."],
       ["Cheops", "Große Pyramide", "Das einzige erhaltene der sieben antiken Weltwunder."],
       ["Hatschepsut", "Terrassentempel", "Als Frau regierte sie mit falschem Bart als König."],
       ["Thutmosis III.", "Größte Ausdehnung", "Führte siebzehn Feldzüge bis an den Euphrat."],
       ["Echnaton", "Sonnenkult", "Ersetzte die alten Götter durch die Sonnenscheibe Aton."],
       ["Nofretete", "Berühmte Büste", "Ihr Bildnis steht heute im Neuen Museum in Berlin."],
       ["Tutanchamun", "Unversehrtes Grab", "1922 von Howard Carter fast ungeplündert gefunden."],
       ["Ramses II.", "Felsentempel", "Ließ Abu Simbel aus dem Fels schlagen."],
       ["Ramses III.", "Abwehr der Seevölker", "Letzter Pharao, der große Feldzüge gewann."],
       ["Amenophis III.", "Memnonkolosse", "Zwei Sitzstatuen bewachten seinen Totentempel."],
       ["Kleopatra VII.", "Letzte Herrscherin", "Mit ihrem Tod 30 v. Chr. wurde Ägypten römisch."],
       ["Narmer", "Einigung des Reiches", "Seine Palette zeigt die Vereinigung von Ober- und Unterägypten."]]'::jsonb),

    ('geschichte', 'herrscherbeinamen', 'Herrscher & ihre Beinamen',
     'Welchen Beinamen trägt der Herrscher?',
     'hard', 'Beiname', 'https://de.wikipedia.org/wiki/Beiname',
     '[["Wilhelm I. von England", "der Eroberer", "Gewann 1066 die Schlacht bei Hastings."],
       ["Richard I. von England", "Löwenherz", "Kämpfte im Dritten Kreuzzug gegen Saladin."],
       ["Friedrich I.", "Barbarossa", "Der Rotbart ertrank 1190 auf dem Kreuzzug."],
       ["Iwan IV.", "der Schreckliche", "Erster gekrönter Zar Russlands."],
       ["Ludwig XIV.", "Sonnenkönig", "Wählte die Sonne als Sinnbild seiner Macht."],
       ["Karl der Kühne", "Letzter Herzog von Burgund", "Fiel 1477 vor Nancy gegen die Eidgenossen."],
       ["Pippin", "der Kurze", "Erster König aus dem Haus der Karolinger."],
       ["Æthelred II.", "der Unberatene", "Der Beiname spielt mit seinem Namen: edler Rat."],
       ["Karl Martell", "der Hammer", "Stoppte 732 den arabischen Vorstoß bei Tours."],
       ["Heinrich IV.", "Büßer von Canossa", "Ging 1077 im Streit mit dem Papst über die Alpen."],
       ["Suleiman I.", "der Prächtige", "Unter ihm stand das Osmanische Reich auf dem Höhepunkt."],
       ["Ludwig I.", "der Fromme", "Sohn Karls des Großen, teilte das Reich unter seinen Söhnen."]]'::jsonb),

    ('geschichte', 'reiche-hauptstaedte', 'Reiche & ihre Hauptstädte',
     'Von welcher Stadt aus wurde das Reich regiert?',
     'hard', 'Weltreich', 'https://de.wikipedia.org/wiki/Weltreich',
     '[["Byzantinisches Reich", "Konstantinopel", "Fiel 1453 an die Osmanen."],
       ["Inkareich", "Cusco", "Der Name bedeutet Nabel der Welt."],
       ["Aztekenreich", "Tenochtitlán", "Auf einer Insel im Texcoco-See erbaut."],
       ["Perserreich der Achämeniden", "Persepolis", "Von Alexander dem Großen 330 v. Chr. verbrannt."],
       ["Mongolenreich", "Karakorum", "Von Ögedei Khan in der Steppe angelegt."],
       ["Reich Karls des Großen", "Aachen", "Die Pfalzkapelle wurde seine Grablege."],
       ["Römisches Reich", "Rom", "Sieben Hügel am Tiber, sagenhaft 753 v. Chr. gegründet."],
       ["Maurya-Reich", "Pataliputra", "Herrschersitz des Ashoka am Ganges."],
       ["Kalifat der Abbasiden", "Bagdad", "762 als kreisrunde Stadt gegründet."],
       ["Russisches Zarenreich", "Sankt Petersburg", "1712 zur Residenz gemacht, statt Moskau."],
       ["Habsburgermonarchie", "Wien", "Von der Hofburg aus regiert."],
       ["Königreich Preußen", "Berlin", "Residenz der Hohenzollern an der Spree."]]'::jsonb),

    ('geschichte', 'deutsche-geschichte-orte', 'Deutsche Geschichte & Orte',
     'An welchem Ort geschah das?',
     'medium', 'Geschichte Deutschlands',
     'https://de.wikipedia.org/wiki/Geschichte_Deutschlands',
     '[["Thesenanschlag", "Wittenberg", "Luther wandte sich 1517 gegen den Ablasshandel."],
       ["Augsburger Religionsfriede", "Augsburg", "1555 geschlossen: der Landesherr bestimmt die Konfession."],
       ["Westfälischer Friede", "Münster", "1648 gemeinsam mit Osnabrück ausgehandelt."],
       ["Wartburgfest", "Eisenach", "Studenten forderten 1817 einen deutschen Nationalstaat."],
       ["Hambacher Fest", "Neustadt an der Weinstraße", "1832 zogen Tausende mit schwarz-rot-goldenen Fahnen."],
       ["Paulskirchenversammlung", "Frankfurt", "Das erste gesamtdeutsche Parlament tagte 1848."],
       ["Kaiserproklamation", "Versailles", "1871 wurde das Deutsche Reich im Spiegelsaal ausgerufen."],
       ["Weimarer Verfassung", "Weimar", "1919 in der Stadt Goethes beschlossen."],
       ["Mauerbau", "Berlin", "Ab dem 13. August 1961 riegelte die DDR den Westteil ab."],
       ["Nürnberger Prozesse", "Nürnberg", "1945 begann das Verfahren gegen die Hauptkriegsverbrecher."],
       ["Potsdamer Konferenz", "Potsdam", "1945 legten die Siegermächte die Nachkriegsordnung fest."],
       ["Montagsdemonstrationen", "Leipzig", "Ab 1989 gingen sie von der Nikolaikirche aus."]]'::jsonb),

    ('geschichte', 'schlachten-kriege', 'Schlachten & Kriege',
     'Zu welchem Krieg gehört die Schlacht?',
     'hard', 'Krieg', 'https://de.wikipedia.org/wiki/Krieg',
     '[["Salamis", "Perserkriege", "Die griechische Flotte schlug 480 v. Chr. die persische."],
       ["Cannae", "Zweiter Punischer Krieg", "Hannibal umfasste 216 v. Chr. das römische Heer."],
       ["Hastings", "Normannische Eroberung", "1066 fiel König Harold, England wurde normannisch."],
       ["Azincourt", "Hundertjähriger Krieg", "1415 entschieden englische Langbogenschützen die Schlacht."],
       ["Lützen", "Dreißigjähriger Krieg", "1632 fiel der Schwedenkönig Gustav Adolf."],
       ["Waterloo", "Napoleonische Kriege", "1815 endete die Herrschaft Napoleons endgültig."],
       ["Gettysburg", "Amerikanischer Bürgerkrieg", "1863 scheiterte der Vorstoß der Südstaaten in den Norden."],
       ["Königgrätz", "Deutscher Krieg", "1866 setzte sich Preußen gegen Österreich durch."],
       ["Sedan", "Deutsch-Französischer Krieg", "1870 geriet Napoleon III. in Gefangenschaft."],
       ["Verdun", "Erster Weltkrieg", "1916 zermürbten sich beide Seiten zehn Monate lang."],
       ["Stalingrad", "Zweiter Weltkrieg", "1943 kapitulierte die eingeschlossene 6. Armee."],
       ["Dien Bien Phu", "Indochinakrieg", "1954 endete die französische Herrschaft in Vietnam."]]'::jsonb),

    ('geschichte', 'herrscherhaeuser-laender', 'Herrscherhäuser & Länder',
     'Über welches Land herrschte das Haus?',
     'medium', 'Dynastie', 'https://de.wikipedia.org/wiki/Dynastie',
     '[["Tudor", "England", "Von Heinrich VII. bis Elisabeth I."],
       ["Bourbonen", "Frankreich", "Stellten ab 1589 die Könige, bis zur Revolution."],
       ["Habsburger", "Österreich", "Regierten mehr als sechs Jahrhunderte lang."],
       ["Romanows", "Russland", "Von 1613 bis zur Revolution 1917 an der Macht."],
       ["Hohenzollern", "Preußen", "Aus ihrer Linie kamen die deutschen Kaiser."],
       ["Osmanen", "Türkei", "Ihr Reich bestand von 1299 bis 1922."],
       ["Ming", "China", "Unter ihnen entstand die Verbotene Stadt."],
       ["Tokugawa", "Japan", "Ihre Shogune schotteten das Land 250 Jahre lang ab."],
       ["Wittelsbacher", "Bayern", "Regierten dort mehr als 700 Jahre."],
       ["Haus Savoyen", "Italien", "Stellte ab 1861 die Könige des geeinten Landes."],
       ["Oranien-Nassau", "Niederlande", "Aus ihm stammt das heutige Königshaus."],
       ["Wasa", "Schweden", "Gustav I. löste 1523 die Union mit Dänemark."]]'::jsonb),

    ('geschichte', 'schiffe-fahrten', 'Berühmte Schiffe & ihre Fahrten',
     'Wer oder was gehört zu diesem Schiff?',
     'hard', 'Forschungsreise',
     'https://de.wikipedia.org/wiki/Forschungsreise',
     '[["Santa María", "Christoph Kolumbus", "Sein Flaggschiff lief 1492 vor Hispaniola auf Grund."],
       ["Victoria", "Erste Weltumsegelung", "Als einziges von fünf Schiffen kehrte es 1522 zurück."],
       ["Golden Hind", "Francis Drake", "Umsegelte als zweites Schiff die Erde, mit Kaperbeute."],
       ["Mayflower", "Pilgerväter", "Brachte 1620 englische Siedler nach Neuengland."],
       ["Endeavour", "James Cook", "Trug ihn 1768 in den Pazifik zur Beobachtung der Venus."],
       ["Bounty", "Meuterei", "Die Mannschaft setzte 1789 ihren Kapitän im Beiboot aus."],
       ["Beagle", "Charles Darwin", "Fünf Jahre Fahrt, an deren Ende die Evolutionstheorie stand."],
       ["Fram", "Fridtjof Nansen", "Ließ sich absichtlich im Packeis einfrieren."],
       ["Endurance", "Ernest Shackleton", "Zerbrach im Eis; die Mannschaft überlebte dennoch."],
       ["Kon-Tiki", "Thor Heyerdahl", "Floß aus Balsaholz, 1947 quer über den Pazifik."],
       ["Titanic", "Untergang 1912", "Sank auf der Jungfernfahrt nach einer Kollision mit einem Eisberg."],
       ["Gjøa", "Nordwestpassage", "Durchfuhr sie als erstes Schiff vollständig."]]'::jsonb),

    ('geschichte', 'erfindungen-kulturen', 'Erfindungen & Kulturen',
     'Welche Kultur brachte das hervor?',
     'medium', 'Erfindung', 'https://de.wikipedia.org/wiki/Erfindung',
     '[["Keilschrift", "Sumerer", "Schriftzeichen, mit dem Griffel in feuchten Ton gedrückt."],
       ["Papyrus", "Ägypter", "Beschreibstoff aus dem Mark einer Sumpfpflanze."],
       ["Alphabet", "Phönizier", "Zeichen für Laute statt für ganze Wörter."],
       ["Papier", "Chinesen", "Um 100 n. Chr. aus Pflanzenfasern geschöpft."],
       ["Aquädukt", "Römer", "Brachte Wasser über Bögen bis in die Städte."],
       ["Ziffer Null", "Inder", "Machte das Rechnen mit Stellenwerten möglich."],
       ["Volksversammlung", "Athener", "Alle Bürger stimmten selbst ab, nicht Vertreter."],
       ["Straßennetz der Anden", "Inka", "Mehr als 30000 Kilometer, mit Hängebrücken."],
       ["Kalender mit 365 Tagen", "Maya", "Zwei ineinandergreifende Zyklen ergaben das Datum."],
       ["Windmühle", "Perser", "Frühe Mühlen mit senkrechter Achse im Osten Irans."],
       ["Langschiff", "Wikinger", "Flach genug für Flüsse, seetüchtig genug für den Atlantik."],
       ["Buchdruck mit Lettern", "Koreaner", "Metalllettern kamen dort vor Gutenberg in Gebrauch."]]'::jsonb),

    ('geschichte', 'unabhaengigkeit-fuehrer', 'Unabhängigkeit & ihre Köpfe',
     'Wer führte das Land in die Unabhängigkeit oder in den neuen Staat?',
     'medium', 'Dekolonisation',
     'https://de.wikipedia.org/wiki/Dekolonisation',
     '[["Indien", "Mahatma Gandhi", "Gewaltloser Widerstand gegen die britische Herrschaft."],
       ["Südafrika", "Nelson Mandela", "27 Jahre Haft, dann erster frei gewählter Präsident."],
       ["Kuba", "Fidel Castro", "Stürzte 1959 den Machthaber Batista."],
       ["Vietnam", "Ho Chi Minh", "Rief 1945 die Unabhängigkeit von Frankreich aus."],
       ["Ghana", "Kwame Nkrumah", "Führte 1957 die erste Kolonie südlich der Sahara in die Freiheit."],
       ["Kenia", "Jomo Kenyatta", "Erster Präsident nach der Unabhängigkeit 1963."],
       ["Venezuela", "Simón Bolívar", "Befreier, nach dem ein ganzes Land benannt ist."],
       ["Türkei", "Mustafa Kemal Atatürk", "Gründete 1923 die Republik auf den Trümmern des Reiches."],
       ["China", "Mao Zedong", "Rief 1949 die Volksrepublik aus."],
       ["Israel", "David Ben-Gurion", "Verlas 1948 die Unabhängigkeitserklärung."],
       ["USA", "George Washington", "Führte die Kontinentalarmee und wurde erster Präsident."],
       ["Italien", "Giuseppe Garibaldi", "Sein Zug der Tausend brachte den Süden ins geeinte Reich."]]'::jsonb),

    ('geschichte', 'burgen-schloesser-laender', 'Burgen, Schlösser & Länder',
     'In welchem Land steht der Bau?',
     'medium', 'Schloss (Architektur)',
     'https://de.wikipedia.org/wiki/Schloss_%28Architektur%29',
     '[["Neuschwanstein", "Deutschland", "Ludwig II. ließ es ab 1869 als Ritterburg-Traum bauen."],
       ["Chambord", "Frankreich", "Renaissanceschloss an der Loire mit doppelter Wendeltreppe."],
       ["Schönbrunn", "Österreich", "Sommerresidenz der Habsburger mit 1441 Räumen."],
       ["Windsor Castle", "Vereinigtes Königreich", "Älteste durchgehend bewohnte Burg der Welt."],
       ["Prager Burg", "Tschechien", "Größte geschlossene Burganlage der Welt."],
       ["Kreml", "Russland", "Festung im Herzen Moskaus, Sitz des Präsidenten."],
       ["Himeji", "Japan", "Weiße Burg, die Erdbeben und Bomben überstand."],
       ["Edinburgh Castle", "Schottland", "Auf einem erloschenen Vulkan über der Stadt."],
       ["Bran", "Rumänien", "Wird als Draculaschloss vermarktet, ohne echten Bezug."],
       ["Kronborg", "Dänemark", "Schauplatz von Shakespeares Hamlet."],
       ["Marienburg", "Polen", "Größte Backsteinburg der Welt, Sitz des Deutschen Ordens."],
       ["Alcázar von Segovia", "Spanien", "Schiffsförmige Burg über dem Zusammenfluss zweier Flüsse."]]'::jsonb),

    ('geschichte', 'kolonien-kolonialmaechte', 'Kolonien & Kolonialmächte',
     'Welche Macht beherrschte das Gebiet?',
     'medium', 'Kolonie', 'https://de.wikipedia.org/wiki/Kolonie',
     '[["Britisch-Indien", "Großbritannien", "Von 1858 bis 1947 direkt der Krone unterstellt."],
       ["Algerien", "Frankreich", "Ab 1848 sogar als Teil des Mutterlandes verwaltet."],
       ["Angola", "Portugal", "Fast 400 Jahre lang beherrscht, unabhängig 1975."],
       ["Kongo-Freistaat", "Belgien", "Zunächst Privatbesitz des Königs Leopold II."],
       ["Niederländisch-Indien", "Niederlande", "Das heutige Indonesien, unabhängig 1949."],
       ["Philippinen", "Spanien", "Über 300 Jahre spanisch, benannt nach Philipp II."],
       ["Deutsch-Südwestafrika", "Deutschland", "Das heutige Namibia, bis 1915."],
       ["Libyen", "Italien", "Ab 1911 erobert, bis 1943 gehalten."],
       ["Alaska", "Russland", "1867 für 7,2 Millionen Dollar an die USA verkauft."],
       ["Grönland", "Dänemark", "Seit 1979 mit weitgehender Selbstverwaltung."],
       ["Taiwan", "Japan", "Von 1895 bis 1945 japanische Kolonie."],
       ["Puerto Rico", "USA", "1898 im Krieg gegen Spanien gewonnen, bis heute Außengebiet."]]'::jsonb),

    ('geschichte', 'roemische-provinzen', 'Römische Provinzen & heutige Länder',
     'Welches heutige Land deckt die Provinz größtenteils ab?',
     'hard', 'Römische Provinz',
     'https://de.wikipedia.org/wiki/R%C3%B6mische_Provinz',
     '[["Gallia", "Frankreich", "Von Caesar bis 51 v. Chr. unterworfen."],
       ["Britannia", "England", "Ab 43 n. Chr. Provinz, im Norden vom Hadrianswall begrenzt."],
       ["Hispania", "Spanien", "Über zwei Jahrhunderte hinweg erobert."],
       ["Dacia", "Rumänien", "Von Trajan erobert, dokumentiert auf seiner Säule."],
       ["Aegyptus", "Ägypten", "Kornkammer Roms, direkt dem Kaiser unterstellt."],
       ["Numidia", "Algerien", "Heimat des Königs Jugurtha."],
       ["Iudaea", "Israel", "Provinz, in der Pontius Pilatus Statthalter war."],
       ["Pannonia", "Ungarn", "Grenzprovinz an der mittleren Donau."],
       ["Thracia", "Bulgarien", "Südöstlicher Balkan, Heimat des Spartacus."],
       ["Lusitania", "Portugal", "Provinz westlich des Flusses Guadiana."],
       ["Cappadocia", "Türkei", "Hochland mit den späteren Felsenkirchen."],
       ["Mauretania Tingitana", "Marokko", "Nordwestzipfel Afrikas, benannt nach Tingis, dem heutigen Tanger."]]'::jsonb),

    ('geschichte', 'historische-dokumente', 'Historische Dokumente & Länder',
     'Wo entstand das Dokument?',
     'hard', 'Verfassung', 'https://de.wikipedia.org/wiki/Verfassung',
     '[["Codex Hammurapi", "Babylonien", "Steinstele mit 282 Rechtssätzen, um 1750 v. Chr."],
       ["Zwölftafelgesetz", "Römische Republik", "Erste schriftliche Aufzeichnung des römischen Rechts."],
       ["Magna Carta", "England", "1215 zwangen Barone den König, Rechte zu verbriefen."],
       ["Goldene Bulle", "Heiliges Römisches Reich", "Regelte ab 1356 die Königswahl durch sieben Kurfürsten."],
       ["Unabhängigkeitserklärung", "USA", "1776 in Philadelphia beschlossen."],
       ["Erklärung der Menschenrechte", "Frankreich", "1789 von der Nationalversammlung verabschiedet."],
       ["Bundesverfassung von 1848", "Schweiz", "Machte aus dem Staatenbund einen Bundesstaat."],
       ["Meiji-Verfassung", "Japan", "1889 nach preußischem Vorbild erlassen."],
       ["Vertrag von Waitangi", "Neuseeland", "1840 zwischen der Krone und Māori-Häuptlingen geschlossen."],
       ["Pragmatische Sanktion", "Österreich", "Sicherte 1713 die Erbfolge auch für eine Tochter."],
       ["Grundgesetz", "Deutschland", "1949 als Provisorium gedacht, bis heute in Kraft."],
       ["Statut von Westminster", "Britisches Weltreich", "Machte die Dominions 1931 rechtlich selbstständig."]]'::jsonb),

    ('geschichte', 'weltausstellungen-bauten', 'Weltausstellungen & ihre Bauten',
     'Für welche Ausstellung entstand der Bau?',
     'hard', 'Weltausstellung', 'https://de.wikipedia.org/wiki/Weltausstellung',
     '[["Eiffelturm", "Paris 1889", "Als Torbogen der Ausstellung gebaut, gegen viel Protest."],
       ["Crystal Palace", "London 1851", "Halle aus Glas und Eisen, später abgebrannt."],
       ["Atomium", "Brüssel 1958", "Eine Eisen-Elementarzelle, 165 Milliarden Mal vergrößert."],
       ["Space Needle", "Seattle 1962", "Aussichtsturm zum Motto Jahrhundert des 21."],
       ["Habitat 67", "Montreal 1967", "Wohnbau aus gestapelten Betonwürfeln."],
       ["Turm der Sonne", "Osaka 1970", "Skulptur von Tarō Okamoto, bis heute erhalten."],
       ["Barcelona-Pavillon", "Barcelona 1929", "Mies van der Rohes Bau aus Marmor, Stahl und Glas."],
       ["Unisphere", "New York 1964", "Stahlkugel als Sinnbild des Friedens auf der Erde."],
       ["Palais du Trocadéro", "Paris 1878", "Hallenbau mit zwei Minaretttürmen, 1937 abgerissen."],
       ["Erstes Riesenrad", "Chicago 1893", "Gebaut, um dem Eiffelturm etwas entgegenzusetzen."]]'::jsonb),

    ('geschichte', 'antike-gesetzgeber-staaten', 'Antike Reformer & ihre Städte',
     'In welcher Stadt oder welchem Staat wirkte die Person?',
     'hard', 'Antike', 'https://de.wikipedia.org/wiki/Antike',
     '[["Solon", "Athen", "Erließ um 594 v. Chr. Gesetze und strich die Schuldknechtschaft."],
       ["Lykurg", "Sparta", "Ihm wird die strenge Ordnung des Kriegerstaats zugeschrieben."],
       ["Hammurapi", "Babylon", "Ließ seine Rechtssätze auf einer Stele festhalten."],
       ["Cicero", "Rom", "Deckte 63 v. Chr. die Verschwörung Catilinas auf."],
       ["Konfuzius", "Lu", "Beriet die Fürsten seines Heimatstaats im heutigen Shandong."],
       ["Ashoka", "Magadha", "Wandte sich nach blutigem Krieg dem Buddhismus zu."],
       ["Kyros II.", "Persien", "Erlaubte den Juden die Rückkehr aus der Verbannung."],
       ["Echnaton", "Amarna", "Ließ für seinen Sonnenkult eine ganz neue Residenz bauen."],
       ["Pythagoras", "Kroton", "Gründete in der griechischen Kolonie einen Bund von Anhängern."],
       ["Ptolemaios I.", "Alexandria", "Machte die Stadt zur Hauptstadt und begann das Museion."],
       ["Hannibal", "Karthago", "Führte von dort den Krieg, der Rom fast das Ende brachte."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
)

insert into items (quiz_id, category_id, label, position, explanation)
select f.quiz_id, c.id, f.answer, f.position, f.explanation
  from flat f
  join new_categories c
    on c.quiz_id = f.quiz_id
   and c.label = f.label;
