-- Kunst & Kultur, leichte Fragen. Zwanzig Fragen, alle 'easy'.
--
-- Zweites Fach ohne eine einzige leichte Frage. Gefragt wird nach dem, was man
-- aus Kinderzimmer, Kino und Alltag kennt, nicht nach Epochen und Stilkunde.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs) as (
    values

    ('kunst-kultur', 'leicht-maerchenfiguren', 'Märchenfiguren',
     'Aus welchem Märchen stammt die Figur?',
     'easy', 'Märchen', 'https://de.wikipedia.org/wiki/M%C3%A4rchen',
     '[["Mädchen mit der roten Kappe", "Rotkäppchen", "Sie soll nicht vom Weg abkommen."],
       ["Sieben kleine Bergleute", "Schneewittchen", "Sie warnen vergeblich vor der Königin."],
       ["Ein verlorener Schuh um Mitternacht", "Aschenputtel", "Der Schuh passt nur einer."],
       ["Geschwister an einem Lebkuchenhaus", "Hänsel und Gretel", "Brotkrumen weisen den Rückweg nicht."],
       ["Mädchen, das hundert Jahre schläft", "Dornröschen", "Eine Spindel bringt den Schlaf."],
       ["Männlein, das seinen Namen geheim hält", "Rumpelstilzchen", "Es spinnt Stroh zu Gold."],
       ["Frau mit sehr langem Haar im Turm", "Rapunzel", "Das Haar dient als Leiter."],
       ["Vier Tiere ziehen in eine Stadt", "Die Bremer Stadtmusikanten", "Sie kommen nie dort an."],
       ["Junge, dessen Nase beim Lügen wächst", "Pinocchio", "Aus Holz geschnitzt."],
       ["Mädchen, das Streichhölzer verkauft", "Die Schwefelhölzer", "Eine Geschichte von Andersen."],
       ["Ein Frosch, der ein Prinz ist", "Der Froschkönig", "Erst der Wurf an die Wand hilft."],
       ["Tapferes Schneiderlein am Gürtel", "Das tapfere Schneiderlein", "Sieben auf einen Streich."]]'::jsonb),

    ('kunst-kultur', 'leicht-kinderbuchfiguren', 'Figuren aus Kinderbüchern',
     'Wer ist das?',
     'easy', 'Kinder- und Jugendliteratur',
     'https://de.wikipedia.org/wiki/Kinder-_und_Jugendliteratur',
     '[["Mädchen mit roten Zöpfen und einem Pferd", "Pippi Langstrumpf", "Sie wohnt allein in der Villa Kunterbunt."],
       ["Zauberlehrling mit runder Brille und Narbe", "Harry Potter", "Er lebt zunächst unter der Treppe."],
       ["Bär, der Honig über alles liebt", "Winnie Puuh", "Er wohnt im Hundertmorgenwald."],
       ["Mädchen, das bei den Großeltern in den Alpen lebt", "Heidi", "Sie hat Heimweh in Frankfurt."],
       ["Ungeheuer aus dem Wald mit orangen Augen", "Der Grüffelo", "Eine Maus erfindet ihn und trifft ihn dann."],
       ["Junge, der Zeit stehlen sieht", "Momo", "Sie kämpft gegen die grauen Herren."],
       ["Räuber in einer Kinderbuchreihe", "Räuber Hotzenplotz", "Er raubt eine Kaffeemühle."],
       ["Kleine Hexe, die zu jung zum Blocksberg ist", "Die kleine Hexe", "Sie will eine gute Hexe sein."],
       ["Junge mit einer Lokomotive und einem Freund", "Jim Knopf", "Lokomotive Emma trägt ihn."],
       ["Kater in Stiefeln", "Der gestiefelte Kater", "Er macht seinen Herrn zum Grafen."],
       ["Ein Löwe, der eigentlich Angst hat", "Der feige Löwe", "Er sucht Mut beim Zauberer von Oz."],
       ["Kleiner Prinz von einem winzigen Planeten", "Der kleine Prinz", "Er zähmt einen Fuchs."]]'::jsonb),

    ('kunst-kultur', 'leicht-instrumente', 'Instrumente erkennen',
     'Welches Instrument ist gemeint?',
     'easy', 'Musikinstrument',
     'https://de.wikipedia.org/wiki/Musikinstrument',
     '[["Schwarze und weiße Tasten", "Klavier", "88 Tasten hat der Flügel."],
       ["Sechs Saiten, wird gezupft", "Gitarre", "Die bekannteste Begleitung am Lagerfeuer."],
       ["Wird mit einem Bogen gestrichen", "Geige", "Das kleinste Streichinstrument."],
       ["Blechinstrument mit drei Ventilen", "Trompete", "Hell und weit zu hören."],
       ["Große Trommel und Becken zusammen", "Schlagzeug", "Der Takt der ganzen Band."],
       ["Man bläst quer hinein", "Querflöte", "Aus Metall, obwohl Holzblasinstrument."],
       ["Wird auseinandergezogen und zusammengedrückt", "Akkordeon", "Der Balg liefert die Luft."],
       ["Sehr großes Streichinstrument im Sitzen", "Cello", "Es steht auf einem Stachel."],
       ["Kleine Röhre, in die man hineinbläst", "Blockflöte", "Meist das erste Instrument in der Schule."],
       ["Hat Pfeifen und steht in der Kirche", "Orgel", "Die Königin der Instrumente."],
       ["Wird mit Klöppeln geschlagen und ist gestimmt", "Pauke", "Ein Pedal ändert die Tonhöhe."],
       ["Man hält sie in einer Hand und schüttelt sie", "Rassel", "Eines der ältesten Instrumente überhaupt."]]'::jsonb),

    ('kunst-kultur', 'leicht-malen', 'Malen & Basteln',
     'Womit macht man das?',
     'easy', 'Malwerkzeug', 'https://de.wikipedia.org/wiki/Malwerkzeug',
     '[["Farbe auf Papier auftragen", "Pinsel", "Es gibt sie fein wie ein Haar."],
       ["Bleistiftstriche entfernen", "Radiergummi", "Er nimmt den Graphitstaub mit."],
       ["Papier zerteilen", "Schere", "Für Linkshänder gibt es eigene."],
       ["Papier zusammenfügen", "Klebstoff", "Der Klassiker riecht nach Mandel."],
       ["Wasserfarben mischen", "Malkasten", "In der Mitte sitzt das Deckweiß."],
       ["Eine gerade Linie ziehen", "Lineal", "Meist mit Zentimeterskala."],
       ["Einen sauberen Kreis zeichnen", "Zirkel", "Eine Spitze steht fest, die andere dreht."],
       ["Aus Ton eine Figur formen", "Hände", "Getrocknet wird sie hart."],
       ["Bilder aufhängen ohne Nagel", "Klebestreifen", "Hält nur auf glatter Wand."],
       ["Ein Bild einrahmen", "Bilderrahmen", "Das Passepartout hält das Glas fern."]]'::jsonb),

    ('kunst-kultur', 'leicht-museen', 'Im Museum',
     'Was findet man dort?',
     'easy', 'Museum', 'https://de.wikipedia.org/wiki/Museum',
     '[["Kunstmuseum", "Gemälde und Skulpturen", "Oft nach Epochen sortiert."],
       ["Naturkundemuseum", "Dinosaurierskelette", "Meist Abgüsse, nicht die echten Knochen."],
       ["Technikmuseum", "Alte Maschinen", "Viele davon darf man anfassen."],
       ["Heimatmuseum", "Dinge aus der Region", "Getragen von einem Verein oder der Gemeinde."],
       ["Freilichtmuseum", "Ganze alte Häuser", "Sie wurden abgebaut und neu errichtet."],
       ["Aquarium", "Lebende Fische", "Salzwasser und Süßwasser getrennt."],
       ["Planetarium", "Der Sternenhimmel", "Projiziert auf eine Kuppel."],
       ["Spielzeugmuseum", "Puppen und Eisenbahnen", "Oft aus einer Privatsammlung entstanden."],
       ["Archäologisches Museum", "Funde aus der Erde", "Scherben erzählen den Alltag."],
       ["Zoo", "Lebende Tiere", "Heute auch mit Zuchtprogrammen für bedrohte Arten."]]'::jsonb),

    ('kunst-kultur', 'leicht-theater', 'Im Theater',
     'Wer oder was ist das?',
     'easy', 'Theater', 'https://de.wikipedia.org/wiki/Theater',
     '[["Steht auf der Bühne und spielt eine Rolle", "Schauspieler", "Er lernt seinen Text auswendig."],
       ["Sagt leise den Text vor, wenn er stockt", "Souffleur", "Er sitzt versteckt am Bühnenrand."],
       ["Hebt und senkt sich vor der Bühne", "Vorhang", "Am Ende fällt er."],
       ["Sitzt im Zuschauerraum", "Publikum", "Es klatscht am Schluss."],
       ["Bestimmt, wie das Stück gespielt wird", "Regisseur", "Er probt wochenlang mit dem Ensemble."],
       ["Sitzt vor der Bühne und spielt Musik", "Orchester", "In der Oper im tiefer gelegten Graben."],
       ["Gibt den Schauspielern ihr Aussehen", "Maske", "Perücken und Schminke gehören dazu."],
       ["Hängt über der Bühne und leuchtet", "Scheinwerfer", "Farbfolien ändern die Stimmung."],
       ["Steht hinten und zeigt den Ort", "Bühnenbild", "Es wird zwischen den Akten getauscht."],
       ["Kurze Pause in der Mitte des Abends", "Pause", "Zeit für ein Glas im Foyer."],
       ["Zettel mit allen Mitwirkenden", "Programmheft", "Wird vor der Vorstellung verkauft."],
       ["Sitzplatz ganz oben im Rang", "Galerie", "Günstig, aber weit weg."]]'::jsonb),

    ('kunst-kultur', 'leicht-farben-bedeutung', 'Farben & ihre Bedeutung',
     'Wofür steht die Farbe meistens?',
     'easy', 'Farbe', 'https://de.wikipedia.org/wiki/Farbe',
     '[["Rot", "Liebe und Gefahr", "Deshalb ist auch die Ampel rot."],
       ["Grün", "Hoffnung und Natur", "Die Farbe der Wiesen und Wälder."],
       ["Blau", "Ruhe und Ferne", "Himmel und Meer erscheinen blau."],
       ["Gelb", "Sonne und Licht", "Auch Warnfarbe bei Wespen."],
       ["Schwarz", "Trauer in Europa", "In anderen Kulturen trauert man in Weiß."],
       ["Weiß", "Unschuld und Reinheit", "Traditionell die Farbe der Braut."],
       ["Gold", "Reichtum und Sieg", "Die erste Medaille glänzt golden."],
       ["Violett", "Würde und Kirche", "Die Farbe der Fastenzeit."],
       ["Braun", "Erde und Holz", "Die Farbe des Bodens."],
       ["Grau", "Nüchternheit", "Weder hell noch dunkel."]]'::jsonb),

    ('kunst-kultur', 'leicht-weltbekannte-bauwerke', 'Bekannte Bauwerke',
     'In welcher Stadt steht das?',
     'easy', 'Wahrzeichen', 'https://de.wikipedia.org/wiki/Wahrzeichen',
     '[["Eiffelturm", "Paris", "Aus Eisen, über 300 Meter hoch."],
       ["Kolosseum", "Rom", "Hier kämpften Gladiatoren."],
       ["Freiheitsstatue", "New York", "Sie steht auf einer eigenen Insel."],
       ["Brandenburger Tor", "Berlin", "Oben fährt eine Quadriga."],
       ["Big Ben", "London", "Eigentlich der Name der Glocke."],
       ["Schiefer Turm", "Pisa", "Er neigt sich seit dem Bau."],
       ["Sagrada Família", "Barcelona", "Seit über hundert Jahren im Bau."],
       ["Petersdom", "Vatikanstadt", "Die größte Kirche der Welt."],
       ["Goldenes Tor als rote Brücke", "San Francisco", "Sie ist nicht golden, sondern rot."],
       ["Kölner Dom", "Köln", "Zwei Türme direkt am Bahnhof."],
       ["Opernhaus mit Segeldächern", "Sydney", "Am Wasser gelegen."],
       ["Christusstatue über der Bucht", "Rio de Janeiro", "Sie steht auf dem Corcovado."]]'::jsonb),

    ('kunst-kultur', 'leicht-weihnachten', 'Weihnachten & Bräuche',
     'Was gehört dazu?',
     'easy', 'Weihnachten', 'https://de.wikipedia.org/wiki/Weihnachten',
     '[["Vier Kerzen auf einem Kranz", "Advent", "Jede Woche brennt eine mehr."],
       ["Türchen bis zum 24. Dezember", "Adventskalender", "Ursprünglich Kreidestriche an der Tür."],
       ["Geschmückter Baum im Wohnzimmer", "Weihnachtsbaum", "Meist eine Tanne oder Fichte."],
       ["Figuren in einem Stall aus Holz", "Krippe", "Franz von Assisi machte sie bekannt."],
       ["Stiefel vor der Tür am 6. Dezember", "Nikolaus", "Er füllt ihn über Nacht."],
       ["Lieder von Haus zu Haus im Januar", "Sternsinger", "Sie sammeln für Kinder in aller Welt."],
       ["Bunt beleuchtete Buden im Dezember", "Weihnachtsmarkt", "Glühwein und gebrannte Mandeln."],
       ["Kekse in vielen Formen", "Plätzchen", "Werden im Advent gebacken."],
       ["Langer Hefekuchen mit Puderzucker", "Christstollen", "Die Form soll ein gewickeltes Kind darstellen."],
       ["Der Abend der Bescherung", "Heiligabend", "In Deutschland gibt es die Geschenke am 24."]]'::jsonb),

    ('kunst-kultur', 'leicht-sprachen-gruesse', 'Guten Tag in aller Welt',
     'In welcher Sprache grüßt man so?',
     'easy', 'Grußformel', 'https://de.wikipedia.org/wiki/Gru%C3%9Fformel',
     '[["Bonjour", "Französisch", "Wörtlich: guten Tag."],
       ["Buongiorno", "Italienisch", "Nachmittags sagt man buonasera."],
       ["Hola", "Spanisch", "Das H bleibt stumm."],
       ["Hello", "Englisch", "Am Telefon zuerst benutzt."],
       ["Konnichiwa", "Japanisch", "Wird mit einer Verbeugung begleitet."],
       ["Merhaba", "Türkisch", "Auch in vielen arabischen Ländern verstanden."],
       ["Dzień dobry", "Polnisch", "Wörtlich: guter Tag."],
       ["Hej", "Schwedisch", "Kurz und in jeder Situation passend."],
       ["Privet", "Russisch", "Unter Freunden, förmlich heißt es anders."],
       ["Ni hao", "Chinesisch", "Wörtlich: du gut."],
       ["Olá", "Portugiesisch", "Auch in Brasilien üblich."],
       ["Geia sou", "Griechisch", "Wörtlich ein Wunsch nach Gesundheit."]]'::jsonb),

    ('kunst-kultur', 'leicht-comicfiguren', 'Comic- und Trickfiguren',
     'Wer ist gemeint?',
     'easy', 'Comic', 'https://de.wikipedia.org/wiki/Comic',
     '[["Maus mit roter Hose und großen Ohren", "Micky Maus", "Erster Auftritt 1928."],
       ["Ente, die nie eine Hose trägt", "Donald Duck", "Er wohnt in Entenhausen."],
       ["Kleiner Gallier mit Flügelhelm", "Asterix", "Der Zaubertrank macht ihn stark."],
       ["Dicker Gallier mit Hinkelsteinen", "Obelix", "Er fiel als Kind in den Zaubertrank."],
       ["Reporter mit weißem Hund", "Tim", "Sein Hund heißt Struppi."],
       ["Kater, der Lasagne liebt und montags hasst", "Garfield", "Er lebt bei Jon."],
       ["Blaue Wichte mit weißen Mützen", "Die Schlümpfe", "Sie wohnen in Pilzhäusern."],
       ["Junge mit gelbem Kopf und Skateboard", "Bart Simpson", "Er schreibt zur Strafe an die Tafel."],
       ["Cowboy, der schneller zieht als sein Schatten", "Lucky Luke", "Am Ende reitet er in den Sonnenuntergang."],
       ["Kleiner gelber Helfer in Latzhose", "Minion", "Sie sprechen eine erfundene Sprache."],
       ["Rosa Panther ohne Worte", "Der rosarote Panther", "Bekannt durch seine Titelmelodie."],
       ["Hund, der auf seiner Hütte liegt", "Snoopy", "Er träumt sich als Fliegerass."]]'::jsonb),

    ('kunst-kultur', 'leicht-zirkus', 'Im Zirkus',
     'Wer macht das?',
     'easy', 'Zirkus', 'https://de.wikipedia.org/wiki/Zirkus',
     '[["Bringt das Publikum zum Lachen", "Clown", "Rote Nase und viel zu große Schuhe."],
       ["Balanciert hoch oben auf einem Seil", "Seiltänzer", "Eine lange Stange hilft beim Gleichgewicht."],
       ["Hält mehrere Bälle in der Luft", "Jongleur", "Auch Keulen und Ringe sind möglich."],
       ["Arbeitet mit Löwen und Tigern", "Dompteur", "Heute in vielen Ländern verboten."],
       ["Schwingt hoch oben von Stange zu Stange", "Trapezkünstler", "Unten hängt ein Netz."],
       ["Kündigt die Nummern an", "Zirkusdirektor", "Meist im roten Frack mit Zylinder."],
       ["Verbiegt den Körper erstaunlich weit", "Schlangenmensch", "Jahrelanges Training steckt dahinter."],
       ["Lässt Dinge verschwinden", "Zauberer", "Der Trick bleibt sein Geheimnis."],
       ["Reitet stehend auf dem Pferd", "Kunstreiter", "Die älteste Zirkusdisziplin."],
       ["Das große Zelt über allem", "Zirkuszelt", "Die Kuppel heißt Chapiteau."]]'::jsonb),

    ('kunst-kultur', 'leicht-buecher-teile', 'Rund ums Buch',
     'Wie heißt der Teil des Buches?',
     'easy', 'Buch', 'https://de.wikipedia.org/wiki/Buch',
     '[["Vorderseite mit Titel und Bild", "Buchcover", "Es soll zum Lesen verführen."],
       ["Liste aller Kapitel vorn", "Inhaltsverzeichnis", "Mit Seitenzahlen zum Nachschlagen."],
       ["Erklärung schwieriger Wörter hinten", "Glossar", "Alphabetisch geordnet."],
       ["Band, das die Seite markiert", "Lesebändchen", "Fest eingebunden."],
       ["Papier, das lose zwischen den Seiten liegt", "Lesezeichen", "Oft Werbung des Buchladens."],
       ["Person, die das Buch geschrieben hat", "Autor", "Der Name steht auf dem Cover."],
       ["Bilder in einem Kinderbuch", "Illustrationen", "Sie erzählen mit."],
       ["Verlag und Jahr auf einer eigenen Seite", "Impressum", "Rechtlich vorgeschrieben."],
       ["Kurzer Text auf der Rückseite", "Klappentext", "Er verrät möglichst nicht das Ende."],
       ["Ort, an dem man Bücher ausleiht", "Bibliothek", "Meist kostenlos oder sehr günstig."]]'::jsonb),

    ('kunst-kultur', 'leicht-sagen', 'Sagen & Gestalten',
     'Wer oder was ist das?',
     'easy', 'Sage', 'https://de.wikipedia.org/wiki/Sage',
     '[["Frau, die auf einem Felsen am Rhein kämmt", "Loreley", "Die Schiffer verunglücken bei ihrem Anblick."],
       ["Schweizer, der einen Apfel schießt", "Wilhelm Tell", "Vom Kopf seines Sohnes."],
       ["Mann, der die Kinder aus der Stadt führt", "Rattenfänger von Hameln", "Zuerst waren es die Ratten."],
       ["Riese, mit dem ein Hirtenjunge kämpft", "Goliath", "Eine Steinschleuder genügte."],
       ["Held mit unverwundbarer Haut bis auf eine Stelle", "Siegfried", "Ein Lindenblatt war im Weg."],
       ["König mit einer runden Tafel", "König Artus", "Niemand sitzt oben an."],
       ["Junge, der zu nah an die Sonne fliegt", "Ikarus", "Das Wachs seiner Flügel schmilzt."],
       ["Ungeheuer aus einem schottischen See", "Monster von Loch Ness", "Nie zweifelsfrei belegt."],
       ["Wesen, das nachts zu Stein wird", "Troll", "Aus nordischen Erzählungen."],
       ["Kleines Wesen, das einen Goldschatz hütet", "Kobold", "In Irland heißt er Leprechaun."],
       ["Pferd mit einem Horn auf der Stirn", "Einhorn", "Im Mittelalter für echt gehalten."],
       ["Feuer speiendes Wesen mit Flügeln", "Drache", "In Asien gilt er als Glücksbringer."]]'::jsonb),

    ('kunst-kultur', 'leicht-tanz', 'Tanzen',
     'Was gehört zu diesem Tanz?',
     'easy', 'Tanz', 'https://de.wikipedia.org/wiki/Tanz',
     '[["Walzer", "Drehen im Dreivierteltakt", "Der Klassiker auf jedem Ball."],
       ["Ballett", "Tanz auf Spitzenschuhen", "Jahrelanges Training ist nötig."],
       ["Breakdance", "Figuren auf dem Boden", "Aus der Hip-Hop-Bewegung."],
       ["Polonaise", "Reihe durch den Saal", "Beliebt auf Feiern und im Karneval."],
       ["Schuhplattler", "Schlagen auf die Schuhe", "Aus dem Alpenraum."],
       ["Sirtaki", "Reihe mit Schulterfassung", "Wird immer schneller."],
       ["Tango", "Enge Haltung", "Aus den Hafenvierteln von Buenos Aires."],
       ["Samba", "Schnelle Hüftbewegungen", "Herz des Karnevals in Rio."],
       ["Discofox", "Einfache Schritte zu Popmusik", "Der beliebteste Paartanz in Deutschland."],
       ["Line Dance", "Reihen ohne Partner", "Ohne Partner, oft zu Countrymusik."]]'::jsonb),

    ('kunst-kultur', 'leicht-alphabet', 'Buchstaben & Schrift',
     'Was ist gemeint?',
     'easy', 'Buchstabe', 'https://de.wikipedia.org/wiki/Buchstabe',
     '[["Erster Buchstabe im Alphabet", "A", "Vom phönizischen Zeichen für Rind."],
       ["Letzter Buchstabe im deutschen Alphabet", "Z", "Danach folgen nur noch die Umlaute."],
       ["Buchstaben mit zwei Punkten darüber", "Umlaute", "Ä, Ö und Ü."],
       ["Buchstabe, den es nur im Deutschen gibt", "Eszett", "Geschrieben als ß."],
       ["Zeichen am Ende eines Aussagesatzes", "Punkt", "Er beendet den Gedanken."],
       ["Zeichen für eine Frage", "Fragezeichen", "Die Stimme geht nach oben."],
       ["Buchstaben, die man singen kann", "Vokale", "A, E, I, O und U."],
       ["Schrift für blinde Menschen", "Brailleschrift", "Punkte werden ertastet."],
       ["Große Anfangsbuchstaben", "Großbuchstaben", "Im Deutschen bei allen Nomen."],
       ["Zeichen zwischen zwei Wortteilen", "Bindestrich", "Er hält lange Wörter lesbar."]]'::jsonb),

    ('kunst-kultur', 'leicht-berufe-kultur', 'Berufe in der Kultur',
     'Wer macht das?',
     'easy', 'Beruf', 'https://de.wikipedia.org/wiki/Beruf',
     '[["Malt Bilder", "Maler", "Mit Öl, Acryl oder Aquarell."],
       ["Schreibt Bücher", "Schriftsteller", "Manche schreiben jeden Tag zur selben Zeit."],
       ["Formt Figuren aus Stein", "Bildhauer", "Er nimmt weg, statt aufzutragen."],
       ["Spielt in Filmen mit", "Schauspieler", "Oft werden Szenen viele Male wiederholt."],
       ["Macht Fotos für die Zeitung", "Fotograf", "Er braucht schnelle Reflexe."],
       ["Leitet ein Orchester", "Dirigent", "Er steht mit dem Rücken zum Publikum."],
       ["Entwirft Kleidung", "Modedesigner", "Zweimal im Jahr eine neue Kollektion."],
       ["Baut Häuser am Reißbrett", "Architekt", "Er plant, bevor jemand gräbt."],
       ["Repariert alte Gemälde", "Restaurator", "Jeder Eingriff muss rückgängig zu machen sein."],
       ["Erklärt Gruppen im Museum die Bilder", "Museumsführer", "Er kennt die Geschichten dahinter."]]'::jsonb),

    ('kunst-kultur', 'leicht-laender-symbole', 'Länder & ihre Symbole',
     'Zu welchem Land gehört das Symbol?',
     'easy', 'Nationalsymbol', 'https://de.wikipedia.org/wiki/Nationalsymbol',
     '[["Ahornblatt", "Kanada", "Es steht mitten auf der Flagge."],
       ["Känguru", "Australien", "Es kommt nur dort frei vor."],
       ["Eiffelturm", "Frankreich", "Das bekannteste Bauwerk des Landes."],
       ["Windmühle und Tulpe", "Niederlande", "Beides längst ein Wahrzeichen."],
       ["Großer Panda", "China", "Auch ein Geschenk an befreundete Länder."],
       ["Kirschblüte", "Japan", "Ihr Aufblühen wird landesweit verfolgt."],
       ["Kilt und Dudelsack", "Schottland", "Das Muster steht für den Clan."],
       ["Weißkopfseeadler", "USA", "Wappentier seit 1782."],
       ["Matrjoschka", "Russland", "Puppen, die ineinander stecken."],
       ["Stier beim Stierkampf", "Spanien", "Umstritten und regional verboten."],
       ["Wikingerschiff", "Norwegen", "Funde stehen heute im Museum."],
       ["Kuckucksuhr", "Deutschland", "Aus dem Schwarzwald in alle Welt."]]'::jsonb),

    ('kunst-kultur', 'leicht-musik-hoeren', 'Musik im Alltag',
     'Was ist das?',
     'easy', 'Musik', 'https://de.wikipedia.org/wiki/Musik',
     '[["Mehrere Menschen singen gemeinsam", "Chor", "Nach Stimmlagen aufgeteilt."],
       ["Eine Person singt allein", "Solo", "Alle anderen schweigen."],
       ["Wiederkehrender Teil eines Liedes", "Refrain", "Den kennt man nach dem ersten Hören."],
       ["Große Gruppe mit vielen Instrumenten", "Orchester", "Vorne stehen die Streicher."],
       ["Kleine Gruppe, meist mit Gitarren", "Band", "Vier bis fünf Personen sind üblich."],
       ["Text eines Liedes", "Liedtext", "Er wird oft mitgesungen."],
       ["Musik zu einem Film", "Filmmusik", "Sie erzählt mit, ohne Worte."],
       ["Lied zum Geburtstag", "Geburtstagslied", "Weltweit in vielen Sprachen."],
       ["Lied eines Landes zu feierlichen Anlässen", "Nationalhymne", "Man steht dabei auf."],
       ["Gerät, das den Takt vorgibt", "Metronom", "Es tickt gleichmäßig."],
       ["Melodie, die im Ohr bleibt", "Ohrwurm", "Man wird sie schwer wieder los."],
       ["Aufnahme aller Lieder einer Gruppe", "Album", "Früher auf Schallplatte."]]'::jsonb),

    ('kunst-kultur', 'leicht-film-fuer-kinder', 'Zeichentrickfilme',
     'Um welchen Film geht es?',
     'easy', 'Animationsfilm', 'https://de.wikipedia.org/wiki/Animation',
     '[["Löwenjunges wird nach dem Tod des Vaters König", "Der König der Löwen", "Die Handlung erinnert an Hamlet."],
       ["Junge Meerjungfrau will an Land leben", "Arielle, die Meerjungfrau", "Nach einem Märchen von Andersen."],
       ["Spielzeug wird lebendig, wenn niemand hinsieht", "Toy Story", "Der erste ganz am Computer erzeugte Kinofilm."],
       ["Schneemann und zwei Schwestern im Eisreich", "Die Eiskönigin", "Ein Lied daraus lief monatelang überall."],
       ["Fisch sucht seinen verlorenen Sohn", "Findet Nemo", "Vater Marlin schwimmt durch den halben Ozean."],
       ["Grüner Oger rettet eine Prinzessin", "Shrek", "Ein Esel begleitet ihn."],
       ["Ratte will Koch in Paris werden", "Ratatouille", "Sie steuert den Koch an den Haaren."],
       ["Altes Haus fliegt an Luftballons davon", "Oben", "Ein Pfadfinder ist ungewollt an Bord."],
       ["Mädchen arbeitet in einem Badehaus für Geister", "Chihiros Reise ins Zauberland", "Ihre Eltern werden zu Schweinen."],
       ["Roboter räumt allein die Erde auf", "WALL·E", "Fast die erste halbe Stunde ohne Worte."],
       ["Junge Elefant mit sehr großen Ohren", "Dumbo", "Die Ohren werden zu Flügeln."],
       ["Hund und Katze finden nach Hause", "Susi und Strolch", "Bekannt für die Spaghettiszene."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
)

insert into items (quiz_id, category_id, label, position, explanation)
select f.quiz_id, c.id, f.answer, f.position, f.explanation
  from flat f
  join new_categories c
    on c.quiz_id = f.quiz_id
   and c.label = f.label;
