-- Kunst & Kultur, file 1 of 2. Twenty questions, medium and hard.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs) as (
    values

    ('kunst-kultur', 'griechische-goetter', 'Griechische Götter & ihre Bereiche',
     'Wofür war die Gottheit zuständig?',
     'medium', 'Griechische Mythologie',
     'https://de.wikipedia.org/wiki/Griechische_Mythologie',
     '[["Zeus", "Himmel und Blitz", "Oberster der Götter, wohnt auf dem Olymp."],
       ["Poseidon", "Meer", "Sein Dreizack lässt die Erde beben."],
       ["Hades", "Unterwelt", "Herrscht über die Toten, nicht über den Tod selbst."],
       ["Athene", "Weisheit und Handwerk", "Ihr heiliges Tier ist die Eule."],
       ["Ares", "Krieg", "Der ungestüme Kampf, im Gegensatz zur klugen Strategie."],
       ["Aphrodite", "Liebe und Schönheit", "Der Sage nach aus Meerschaum geboren."],
       ["Hermes", "Boten und Händler", "Trägt Flügelschuhe und geleitet die Toten."],
       ["Apollon", "Licht und Musik", "Sein Orakel sprach in Delphi."],
       ["Artemis", "Jagd und Mond", "Zwillingsschwester des Apollon."],
       ["Hephaistos", "Schmiedefeuer", "Schmiedet unter dem Vulkan die Waffen der Götter."],
       ["Demeter", "Ackerbau", "Ihre Trauer um Persephone erklärt den Winter."],
       ["Dionysos", "Wein und Rausch", "Aus seinen Festen entstand das Theater."]]'::jsonb),

    ('kunst-kultur', 'goetter-griechisch-roemisch', 'Griechische & römische Götternamen',
     'Wie heißt die Gottheit bei den Römern?',
     'medium', 'Römische Mythologie',
     'https://de.wikipedia.org/wiki/R%C3%B6mische_Mythologie',
     '[["Zeus", "Jupiter", "Beide schleudern den Blitz und stehen an der Spitze."],
       ["Hera", "Juno", "Schützerin der Ehe, nach ihr ist der Juni benannt."],
       ["Poseidon", "Neptun", "Namensgeber des äußersten Planeten."],
       ["Athene", "Minerva", "Steht für Weisheit, Handwerk und Kriegskunst."],
       ["Ares", "Mars", "Nach ihm sind Planet und Monat März benannt."],
       ["Aphrodite", "Venus", "Der hellste Planet trägt ihren Namen."],
       ["Hermes", "Merkur", "Der sonnennächste Planet ist der schnellste, wie der Bote."],
       ["Artemis", "Diana", "Jägerin mit Bogen und Mondsichel."],
       ["Hephaistos", "Vulcanus", "Aus seinem Namen wurde das Wort Vulkan."],
       ["Demeter", "Ceres", "Von ihrem Namen stammt das englische cereal."],
       ["Dionysos", "Bacchus", "Die Bacchanalien waren in Rom zeitweise verboten."],
       ["Hades", "Pluto", "Der Zwergplanet ist nach ihm benannt."]]'::jsonb),

    ('kunst-kultur', 'literaturepochen-werke', 'Literaturepochen & Werke',
     'Aus welcher Epoche stammt das Werk?',
     'hard', 'Literaturgeschichte',
     'https://de.wikipedia.org/wiki/Literaturgeschichte',
     '[["Simplicissimus", "Barock", "Ein Junge zieht durch den Dreißigjährigen Krieg."],
       ["Nathan der Weise", "Aufklärung", "Die Ringparabel wirbt für religiöse Toleranz."],
       ["Die Räuber", "Sturm und Drang", "Aufbegehren gegen Vaterordnung und Gesetz."],
       ["Iphigenie auf Tauris", "Weimarer Klassik", "Maß, Humanität und antike Form."],
       ["Heinrich von Ofterdingen", "Romantik", "Die blaue Blume wurde zum Sinnbild der Epoche."],
       ["Der Schimmelreiter", "Realismus", "Deichbau und Aberglaube an der Nordseeküste."],
       ["Die Weber", "Naturalismus", "Der Aufstand der schlesischen Weber auf der Bühne."],
       ["Die Verwandlung", "Expressionismus", "Gregor Samsa erwacht als Ungeziefer."],
       ["Berlin Alexanderplatz", "Neue Sachlichkeit", "Großstadtmontage um Franz Biberkopf."],
       ["Draußen vor der Tür", "Trümmerliteratur", "Ein Heimkehrer findet keinen Platz mehr."],
       ["Die Blechtrommel", "Nachkriegsmoderne", "Oskar Matzerath weigert sich zu wachsen."],
       ["Das Parfum", "Postmoderne", "Ein Mörder auf der Suche nach dem vollkommenen Duft."]]'::jsonb),

    ('kunst-kultur', 'kunstepochen-merkmale', 'Kunstepochen & Merkmale',
     'Woran ist die Epoche zu erkennen?',
     'medium', 'Kunstgeschichte',
     'https://de.wikipedia.org/wiki/Kunstgeschichte',
     '[["Gotik", "Spitzbogen und Maßwerk", "Die Wand löst sich in farbiges Glas auf."],
       ["Renaissance", "Zentralperspektive", "Der Raum wird mathematisch konstruiert."],
       ["Barock", "Bewegung und starkes Helldunkel", "Diagonalen und Dramatik statt ruhiger Ordnung."],
       ["Rokoko", "Verspielte Muschelformen", "Helle Farben und heitere Szenen."],
       ["Klassizismus", "Rückgriff auf die Antike", "Säulen, Giebel und klare Linien."],
       ["Romantik", "Sehnsuchtslandschaften", "Ruinen, Nebel und die Nacht als Motiv."],
       ["Impressionismus", "Licht im Freien gemalt", "Sichtbarer Pinselstrich statt glatter Oberfläche."],
       ["Expressionismus", "Grelle Farben und Verzerrung", "Gefühl geht vor Abbild."],
       ["Kubismus", "Zersplitterte Formen", "Mehrere Ansichten zugleich auf einer Fläche."],
       ["Surrealismus", "Traumbilder", "Vertraute Dinge in unmöglichen Zusammenhängen."],
       ["Bauhaus", "Form folgt Funktion", "Schmuck gilt als überflüssig."],
       ["Pop Art", "Motive der Werbung", "Alltagsware und Comic werden zum Bildgegenstand."]]'::jsonb),

    ('kunst-kultur', 'skulpturen-kuenstler', 'Skulpturen & ihre Schöpfer',
     'Wer schuf die Skulptur?',
     'hard', 'Skulptur', 'https://de.wikipedia.org/wiki/Skulptur',
     '[["David", "Michelangelo", "Fünf Meter Marmor, 1504 in Florenz aufgestellt."],
       ["Der Denker", "Auguste Rodin", "Ursprünglich Teil eines Höllentors."],
       ["Die kleine Meerjungfrau", "Edvard Eriksen", "Sitzt seit 1913 am Hafen von Kopenhagen."],
       ["Christus der Erlöser", "Paul Landowski", "30 Meter hoch über Rio de Janeiro."],
       ["Freiheitsstatue", "Auguste Bartholdi", "Geschenk Frankreichs zum Jubiläum der USA."],
       ["Vier-Ströme-Brunnen", "Gian Lorenzo Bernini", "Vier Flüsse für vier Erdteile, auf der Piazza Navona."],
       ["Der schreitende Mann", "Alberto Giacometti", "Dünne Figuren als Sinnbild des Nachkriegsmenschen."],
       ["Cloud Gate", "Anish Kapoor", "Spiegelnde Bohne in Chicago."],
       ["Spiral Jetty", "Robert Smithson", "Steinspirale im Großen Salzsee."],
       ["Endlose Säule", "Constantin Brâncuși", "Rhombenstapel als Denkmal in Rumänien."],
       ["Bavaria", "Ludwig Schwanthaler", "Bronzefigur über der Münchner Theresienwiese."],
       ["Marc Aurel zu Pferde", "Unbekannter Römer", "Einziges erhaltenes antikes Reiterstandbild aus Bronze."]]'::jsonb),

    ('kunst-kultur', 'weltliteratur-laender', 'Weltliteratur & Herkunftsländer',
     'Aus welchem Land stammt das Werk?',
     'medium', 'Weltliteratur',
     'https://de.wikipedia.org/wiki/Weltliteratur',
     '[["Krieg und Frieden", "Russland", "Der Feldzug Napoleons aus Sicht des Adels."],
       ["Don Quijote", "Spanien", "Der Ritter kämpft gegen Windmühlen."],
       ["Die Blechtrommel", "Deutschland", "Danzig und das 20. Jahrhundert aus Kinderperspektive."],
       ["Hundert Jahre Einsamkeit", "Kolumbien", "Die Familie Buendía im Dorf Macondo."],
       ["Der große Gatsby", "USA", "Reichtum und Illusion in den 1920er Jahren."],
       ["Madame Bovary", "Frankreich", "Provinzleben und die Flucht in Träume."],
       ["Die Göttliche Komödie", "Italien", "Reise durch Hölle, Läuterungsberg und Paradies."],
       ["Hamlet", "England", "Der Prinz zögert mit der Rache für seinen Vater."],
       ["Ulysses", "Irland", "Ein einziger Tag in Dublin auf über tausend Seiten."],
       ["Tausendundeine Nacht", "Arabischer Raum", "Schahrasad erzählt, um zu überleben."],
       ["Der Traum der roten Kammer", "China", "Der Niedergang einer großen Familie."],
       ["Genji Monogatari", "Japan", "Um 1000 von einer Hofdame geschrieben."]]'::jsonb),

    ('kunst-kultur', 'comicfiguren-schoepfer', 'Figuren & ihre Erfinder',
     'Wer hat die Figur erfunden?',
     'medium', 'Comic', 'https://de.wikipedia.org/wiki/Comic',
     '[["Tim und Struppi", "Hergé", "Der belgische Reporter erschien ab 1929."],
       ["Asterix", "Goscinny und Uderzo", "Ein gallisches Dorf leistet Widerstand."],
       ["Micky Maus", "Walt Disney", "1928 im Kurzfilm Steamboat Willie."],
       ["Lucky Luke", "Morris", "Der Mann, der schneller zieht als sein Schatten."],
       ["Pippi Langstrumpf", "Astrid Lindgren", "Ein Kind, das allein in einer Villa wohnt."],
       ["Der kleine Prinz", "Antoine de Saint-Exupéry", "Ein Pilot begegnet ihm in der Wüste."],
       ["Harry Potter", "Joanne K. Rowling", "Der erste Band erschien 1997."],
       ["Winnie Puuh", "Alan Alexander Milne", "Ein Bär mit Vorliebe für Honig."],
       ["Die Peanuts", "Charles Schulz", "Charlie Brown und sein Beagle Snoopy."],
       ["Der Grüffelo", "Julia Donaldson", "Eine Maus erfindet ein Ungeheuer, das es gibt."],
       ["Momo", "Michael Ende", "Ein Mädchen kämpft gegen die grauen Herren."],
       ["Die Schlümpfe", "Peyo", "Blaue Wichte, 1958 zuerst als Nebenfiguren."]]'::jsonb),

    ('kunst-kultur', 'architekten-bauwerke', 'Architekten & ihre Bauten',
     'Welches Bauwerk stammt von dieser Person?',
     'hard', 'Architekt', 'https://de.wikipedia.org/wiki/Architekt',
     '[["Antoni Gaudí", "Sagrada Família", "Seit 1882 im Bau, bis heute unvollendet."],
       ["Filippo Brunelleschi", "Domkuppel von Florenz", "Gebaut ohne durchgehendes Lehrgerüst."],
       ["Frank Lloyd Wright", "Fallingwater", "Ein Haus über einem Wasserfall."],
       ["Le Corbusier", "Villa Savoye", "Weißer Kubus auf schlanken Stützen."],
       ["Walter Gropius", "Bauhausgebäude Dessau", "Glasvorhangfassade von 1926."],
       ["Jørn Utzon", "Opernhaus von Sydney", "Schalendächer wie geblähte Segel."],
       ["Frank Gehry", "Guggenheim-Museum Bilbao", "Titanhülle, die eine ganze Stadt bekannt machte."],
       ["Zaha Hadid", "Heydar-Aliyev-Zentrum", "Eine Fassade ganz ohne gerade Kanten."],
       ["Norman Foster", "Reichstagskuppel", "Begehbare Glaskuppel über dem Plenarsaal."],
       ["Ieoh Ming Pei", "Louvre-Pyramide", "Glaspyramide im Hof des alten Palasts."],
       ["Gottfried Semper", "Semperoper", "Opernhaus in Dresden, zweimal wieder aufgebaut."],
       ["Kenzō Tange", "Olympiahallen von Tokio", "Hängedächer für die Spiele 1964."]]'::jsonb),

    ('kunst-kultur', 'theaterstuecke-autoren', 'Theaterstücke & Autoren',
     'Wer schrieb das Stück?',
     'hard', 'Drama', 'https://de.wikipedia.org/wiki/Drama',
     '[["Antigone", "Sophokles", "Gesetz des Staates gegen das Gebot der Familie."],
       ["Die Frösche", "Aristophanes", "Komödie, in der Dionysos in die Unterwelt steigt."],
       ["Ein Sommernachtstraum", "William Shakespeare", "Verwechslungen im Wald bei Athen."],
       ["Das Käthchen von Heilbronn", "Heinrich von Kleist", "Ein Mädchen folgt bedingungslos einem Ritter."],
       ["Nora", "Henrik Ibsen", "Eine Frau verlässt am Ende Mann und Kinder."],
       ["Die Möwe", "Anton Tschechow", "Vier Menschen, die aneinander vorbeireden."],
       ["Cyrano de Bergerac", "Edmond Rostand", "Der Dichter mit der großen Nase leiht seine Worte."],
       ["Mutter Courage", "Bertolt Brecht", "Eine Marketenderin lebt vom Krieg und verliert alles."],
       ["Der Tod eines Handlungsreisenden", "Arthur Miller", "Das Scheitern des amerikanischen Traums."],
       ["Endstation Sehnsucht", "Tennessee Williams", "Blanche DuBois zerbricht in New Orleans."],
       ["Warten auf Godot", "Samuel Beckett", "Zwei Männer warten, und es geschieht nichts."],
       ["Der Besuch der alten Dame", "Friedrich Dürrenmatt", "Eine Milliardärin kauft sich Gerechtigkeit."]]'::jsonb),

    ('kunst-kultur', 'kunstwerke-museen', 'Kunstwerke & ihre Museen',
     'Wo hängt oder steht das Werk?',
     'medium', 'Kunstmuseum', 'https://de.wikipedia.org/wiki/Kunstmuseum',
     '[["Mona Lisa", "Louvre", "Hinter Panzerglas, umringt von Handykameras."],
       ["Die Nachtwache", "Rijksmuseum", "Rembrandts Gruppenporträt einer Schützengilde."],
       ["Guernica", "Museo Reina Sofía", "Kehrte erst 1981 nach Spanien zurück."],
       ["Der Schrei", "Nationalgalerie Oslo", "Mehrere Fassungen, zweimal gestohlen."],
       ["Die Geburt der Venus", "Uffizien", "Botticellis Venus auf der Muschel."],
       ["Der Kuss", "Belvedere", "Klimts Goldbild, Wahrzeichen des Wiener Museums."],
       ["Sternennacht", "Museum of Modern Art", "Van Goghs Wirbelhimmel über dem Dorf."],
       ["Las Meninas", "Prado", "Velázquez malt sich selbst beim Malen."],
       ["Der Wanderer über dem Nebelmeer", "Kunsthalle Hamburg", "Rückenfigur über der Wolkendecke."],
       ["Mädchen mit dem Perlenohrring", "Mauritshuis", "Vermeers Blick über die Schulter."],
       ["David", "Galleria dell''Accademia", "Seit 1873 im Museum, auf der Piazza steht eine Kopie."],
       ["Die Erschaffung Adams", "Sixtinische Kapelle", "Die berühmten zwei Finger an der Decke."]]'::jsonb),

    ('kunst-kultur', 'maltechniken', 'Techniken der Kunst',
     'Was macht die Technik aus?',
     'hard', 'Malerei', 'https://de.wikipedia.org/wiki/Malerei',
     '[["Fresko", "Farbe auf frischen Putz", "Die Farbe bindet beim Trocknen mit der Wand ab."],
       ["Tempera", "Ei als Bindemittel", "Vor der Ölmalerei die übliche Technik."],
       ["Aquarell", "Lasierende Wasserfarbe", "Das Weiß kommt vom Papier, nicht aus der Tube."],
       ["Pastell", "Trockene Farbkreide", "Muss fixiert werden, sonst verwischt sie."],
       ["Enkaustik", "Farben in heißem Wachs", "Schon in ägyptischen Mumienporträts verwendet."],
       ["Radierung", "Säure ätzt die Platte", "Der Druck entsteht aus den vertieften Linien."],
       ["Holzschnitt", "Hochdruck vom Holzstock", "Alles, was weiß bleibt, wird weggeschnitten."],
       ["Lithografie", "Flachdruck vom Stein", "Fett und Wasser stoßen sich ab."],
       ["Siebdruck", "Farbe durch ein Gewebe", "Andy Warhol machte das Verfahren zur Kunst."],
       ["Mosaik", "Bild aus Steinchen", "In Ravenna sogar mit Gold hinterlegtem Glas."],
       ["Collage", "Aufgeklebte Fundstücke", "Zeitung und Tapete werden Bildmaterial."],
       ["Sfumato", "Weiche Übergänge ohne Kontur", "Leonardos Kunstgriff, Haut wie Dunst wirken zu lassen."]]'::jsonb),

    ('kunst-kultur', 'dichter-gedichte', 'Dichter & ihre Gedichte',
     'Von wem stammt das Gedicht?',
     'hard', 'Lyrik', 'https://de.wikipedia.org/wiki/Lyrik',
     '[["Erlkönig", "Goethe", "Ein Vater reitet mit seinem Kind durch die Nacht."],
       ["Das Lied von der Glocke", "Schiller", "Vom Guss der Glocke zum Lauf des Lebens."],
       ["Die Loreley", "Heinrich Heine", "Ihr Kämmen bringt den Schiffer zum Untergang."],
       ["Der Panther", "Rainer Maria Rilke", "Der Blick ist vom Vorübergehen der Stäbe müde."],
       ["Hälfte des Lebens", "Friedrich Hölderlin", "Zwei Strophen zwischen Fülle und Kälte."],
       ["Mondnacht", "Joseph von Eichendorff", "Die Seele spannt weit ihre Flügel aus."],
       ["Herr von Ribbeck", "Theodor Fontane", "Der Birnbaum wächst aus dem Grab des Gutsherrn."],
       ["Todesfuge", "Paul Celan", "Schwarze Milch der Frühe, wir trinken sie abends."],
       ["Der Rabe", "Edgar Allan Poe", "Der Vogel antwortet immer nur Nimmermehr."],
       ["Sonett 18", "William Shakespeare", "Soll ich dich einem Sommertag vergleichen."],
       ["Grodek", "Georg Trakl", "Sein letztes Gedicht, geschrieben nach einer Schlacht 1914."],
       ["Sachliche Romanze", "Erich Kästner", "Zwei Menschen, denen nach acht Jahren die Liebe abhandenkommt."]]'::jsonb),

    ('kunst-kultur', 'sprachen-schriften', 'Sprachen & ihre Schriften',
     'In welcher Schrift wird die Sprache geschrieben?',
     'medium', 'Schrift', 'https://de.wikipedia.org/wiki/Schrift',
     '[["Russisch", "Kyrillisch", "Nach den Mönchen Kyrill und Method benannt."],
       ["Griechisch", "Griechisches Alphabet", "Erstes Alphabet mit eigenen Vokalzeichen."],
       ["Hebräisch", "Quadratschrift", "Wird von rechts nach links geschrieben."],
       ["Arabisch", "Arabische Schrift", "Buchstaben verbinden sich zu Wörtern."],
       ["Hindi", "Devanagari", "Die Zeichen hängen an einer durchgehenden Linie."],
       ["Japanisch", "Kanji und Kana", "Drei Zeichensysteme im selben Satz."],
       ["Koreanisch", "Hangul", "Im 15. Jahrhundert gezielt entworfen."],
       ["Chinesisch", "Han-Zeichen", "Jedes Zeichen steht für eine Silbe mit Bedeutung."],
       ["Thai", "Thailändische Schrift", "Wörter werden ohne Leerzeichen gereiht."],
       ["Georgisch", "Mchedruli", "Kennt keine Groß- und Kleinschreibung."],
       ["Armenisch", "Armenisches Alphabet", "Um 405 von Mesrop Maschtoz geschaffen."],
       ["Amharisch", "Äthiopische Silbenschrift", "Jedes Zeichen trägt Konsonant und Vokal."]]'::jsonb),

    ('kunst-kultur', 'taenze-herkunft', 'Tänze & ihre Herkunft',
     'Woher stammt der Tanz?',
     'medium', 'Tanz', 'https://de.wikipedia.org/wiki/Tanz',
     '[["Tango", "Argentinien", "Entstand in den Hafenvierteln von Buenos Aires."],
       ["Flamenco", "Spanien", "Gesang, Gitarre und Fußarbeit in Andalusien."],
       ["Samba", "Brasilien", "Herzstück des Karnevals von Rio."],
       ["Wiener Walzer", "Österreich", "Galt anfangs als anstößig, weil man sich fasste."],
       ["Polka", "Tschechien", "Aus Böhmen, im 19. Jahrhundert Modetanz Europas."],
       ["Salsa", "Kuba", "Aus Son und Mambo in New York weiterentwickelt."],
       ["Hula", "Hawaii", "Die Handbewegungen erzählen die Geschichte mit."],
       ["Kathak", "Indien", "Erzähltanz mit Fußglöckchen und schnellen Drehungen."],
       ["Sirtaki", "Griechenland", "Für einen Film erfunden, heute Nationalsymbol."],
       ["Csárdás", "Ungarn", "Beginnt langsam und endet in rasendem Tempo."],
       ["Mazurka", "Polen", "Chopin machte den Volkstanz zur Klaviermusik."],
       ["Square Dance", "USA", "Ein Caller ruft die Figuren während des Tanzes an."]]'::jsonb),

    ('kunst-kultur', 'literaturnobelpreis-laender', 'Literaturnobelpreis & Länder',
     'Aus welchem Land stammt die ausgezeichnete Person?',
     'hard', 'Nobelpreis für Literatur',
     'https://de.wikipedia.org/wiki/Nobelpreis_f%C3%BCr_Literatur',
     '[["Selma Lagerlöf", "Schweden", "1909 als erste Frau ausgezeichnet."],
       ["Thomas Mann", "Deutschland", "Ausgezeichnet vor allem für die Buddenbrooks."],
       ["Pablo Neruda", "Chile", "Liebesgedichte und politische Lyrik."],
       ["Yasunari Kawabata", "Japan", "Erster japanischer Preisträger, 1968."],
       ["Gabriel García Márquez", "Kolumbien", "Meister des magischen Realismus."],
       ["Naguib Mahfuz", "Ägypten", "Erster arabischsprachiger Preisträger."],
       ["Toni Morrison", "USA", "Erste schwarze Frau mit dem Literaturnobelpreis."],
       ["Kazuo Ishiguro", "Vereinigtes Königreich", "In Nagasaki geboren, in England aufgewachsen."],
       ["Orhan Pamuk", "Türkei", "Chronist des alten und neuen Istanbul."],
       ["Swetlana Alexijewitsch", "Belarus", "Schreibt Bücher aus vielen Stimmen."],
       ["Mo Yan", "China", "Sein Künstlername bedeutet: sprich nicht."],
       ["Annie Ernaux", "Frankreich", "Erzählt das eigene Leben als Zeitgeschichte."]]'::jsonb),

    ('kunst-kultur', 'gemaelde-epochen', 'Gemälde & Epochen',
     'Welches Werk steht für diese Epoche?',
     'hard', 'Kunstgeschichte',
     'https://de.wikipedia.org/wiki/Kunstgeschichte',
     '[["Hochrenaissance", "Mona Lisa", "Leonardos Bildnis mit dem unbestimmten Lächeln."],
       ["Manierismus", "Die lange Madonna", "Parmigianinos gedehnte Figuren, um 1535 gemalt."],
       ["Barock", "Die Nachtwache", "Rembrandts Lichtregie über einer Schützengruppe."],
       ["Rokoko", "Die Schaukel", "Fragonards heiteres Spiel im Park."],
       ["Klassizismus", "Der Schwur der Horatier", "Davids strenge Komposition mit antikem Stoff."],
       ["Romantik", "Das Nebelmeer", "Caspar David Friedrichs Rückenfigur über der Wolkendecke."],
       ["Realismus", "Die Steinklopfer", "Courbet malt harte Arbeit ohne Beschönigung."],
       ["Impressionismus", "Impression, Sonnenaufgang", "Monets Hafenbild gab der Richtung den Namen."],
       ["Expressionismus", "Der Schrei", "Munchs Figur unter blutrotem Himmel."],
       ["Kubismus", "Les Demoiselles d''Avignon", "Picassos Bruch mit der einen Perspektive."],
       ["Surrealismus", "Die Beständigkeit der Erinnerung", "Dalís zerfließende Uhren."],
       ["Pop Art", "Campbell''s Soup Cans", "Warhol malt zweiunddreißig Suppendosen."]]'::jsonb),

    ('kunst-kultur', 'zeitungen-laender', 'Zeitungen & Länder',
     'In welchem Land erscheint die Zeitung?',
     'medium', 'Zeitung', 'https://de.wikipedia.org/wiki/Zeitung',
     '[["Le Monde", "Frankreich", "1944 auf Wunsch de Gaulles gegründet."],
       ["The Times", "Vereinigtes Königreich", "Erschien erstmals 1785."],
       ["Frankfurter Allgemeine", "Deutschland", "Bekannt für den Kommentar auf der Titelseite."],
       ["El País", "Spanien", "Gegründet 1976, kurz nach dem Ende der Diktatur."],
       ["Corriere della Sera", "Italien", "Größte Tageszeitung des Landes, aus Mailand."],
       ["The New York Times", "USA", "Motto: All the News That''s Fit to Print."],
       ["Neue Zürcher Zeitung", "Schweiz", "Eine der ältesten noch erscheinenden Zeitungen der Welt."],
       ["Der Standard", "Österreich", "Erkennbar am lachsfarbenen Papier."],
       ["Asahi Shimbun", "Japan", "Eine der auflagenstärksten Zeitungen weltweit."],
       ["Gazeta Wyborcza", "Polen", "1989 aus der Solidarność-Bewegung entstanden."],
       ["Politiken", "Dänemark", "Kopenhagener Blatt mit eigenem Verlagshaus am Rathausplatz."],
       ["The Hindu", "Indien", "Erscheint seit 1878 in englischer Sprache."]]'::jsonb),

    ('kunst-kultur', 'philosophen-begriffe', 'Philosophen & ihre Begriffe',
     'Welcher Begriff steht für diese Person?',
     'hard', 'Philosophie', 'https://de.wikipedia.org/wiki/Philosophie',
     '[["Sokrates", "Wissen des Nichtwissens", "Er fragte so lange, bis die Gewissheit zerfiel."],
       ["Platon", "Ideenlehre", "Das Sichtbare ist nur Abbild des wahren Seins."],
       ["Aristoteles", "Zoon politikon", "Der Mensch ist auf Gemeinschaft angelegt."],
       ["Thomas Hobbes", "Leviathan", "Ohne Staat herrscht der Krieg aller gegen alle."],
       ["René Descartes", "Cogito ergo sum", "Am Zweifel selbst zerbricht der Zweifel."],
       ["Jean-Jacques Rousseau", "Gesellschaftsvertrag", "Herrschaft ist nur mit Zustimmung legitim."],
       ["Immanuel Kant", "Kategorischer Imperativ", "Handle so, dass deine Maxime allgemeines Gesetz sein könnte."],
       ["Georg Wilhelm Hegel", "Dialektik", "These, Antithese und ihre Aufhebung."],
       ["Karl Marx", "Klassenkampf", "Die Geschichte als Kampf gesellschaftlicher Klassen."],
       ["Friedrich Nietzsche", "Wille zur Macht", "Umwertung aller bisherigen Werte."],
       ["Ludwig Wittgenstein", "Grenzen der Sprache", "Wovon man nicht sprechen kann, darüber muss man schweigen."],
       ["Jean-Paul Sartre", "Existenz vor Essenz", "Der Mensch ist, wozu er sich macht."]]'::jsonb),

    ('kunst-kultur', 'maerchen-herkunft', 'Märchen & Sagen',
     'Woher stammt die Geschichte?',
     'medium', 'Märchen', 'https://de.wikipedia.org/wiki/M%C3%A4rchen',
     '[["Aschenputtel", "Brüder Grimm", "In ihrer Fassung helfen Tauben beim Lesen der Linsen."],
       ["Die kleine Meerjungfrau", "Hans Christian Andersen", "Ihr Ende ist im Original alles andere als glücklich."],
       ["Ali Baba", "Tausendundeine Nacht", "Sesam öffne dich."],
       ["Der Rattenfänger", "Sage aus Hameln", "Er führt erst die Ratten und dann die Kinder fort."],
       ["König Artus", "Britische Sage", "Das Schwert im Stein und die Tafelrunde."],
       ["Siegfried", "Nibelungenlied", "Unverwundbar bis auf eine Stelle am Rücken."],
       ["Robin Hood", "Englische Ballade", "Er nimmt von den Reichen und gibt den Armen."],
       ["Wilhelm Tell", "Schweizer Sage", "Der Apfelschuss vor dem Landvogt."],
       ["Ikarus", "Griechische Mythologie", "Er flog zu nah an die Sonne."],
       ["Baba Jaga", "Russische Volkserzählung", "Eine Hexe in einer Hütte auf Hühnerfüßen."],
       ["Anansi", "Westafrikanische Erzählung", "Die Spinne siegt mit List statt mit Kraft."],
       ["Momotarō", "Japanische Volkserzählung", "Ein Junge aus einem Pfirsich zieht gegen Dämonen."]]'::jsonb),

    ('kunst-kultur', 'kunsthandwerk-laender', 'Kunsthandwerk & Länder',
     'Aus welchem Land stammt das Handwerk?',
     'medium', 'Kunsthandwerk',
     'https://de.wikipedia.org/wiki/Kunsthandwerk',
     '[["Origami", "Japan", "Papierfalten ohne Schere und Klebstoff."],
       ["Batik", "Indonesien", "Wachs deckt ab, was ungefärbt bleiben soll."],
       ["Fabergé-Eier", "Russland", "Kunstvolle Ostergeschenke für den Zarenhof."],
       ["Delfter Kacheln", "Niederlande", "Blau auf Weiß, nach chinesischem Vorbild."],
       ["Murano-Glas", "Italien", "Die Öfen wurden auf eine Insel verlegt, wegen der Brandgefahr."],
       ["Perserteppich", "Iran", "Knüpfdichte und Muster verraten die Herkunftsregion."],
       ["Klöppelspitze", "Belgien", "Aus Brügge, jahrhundertelang Exportware."],
       ["Tartan", "Schottland", "Jedes Karomuster steht für einen Clan."],
       ["Talavera-Keramik", "Mexiko", "Spanische Technik, in Puebla weiterentwickelt."],
       ["Damaszener Klingen", "Syrien", "Erkennbar an der geflammten Musterung im Stahl."],
       ["Kuckucksuhr", "Deutschland", "Aus dem Schwarzwald in alle Welt verkauft."],
       ["Maori-Schnitzerei", "Neuseeland", "Spiralen aus Holz, Knochen und Jade."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
)

insert into items (quiz_id, category_id, label, position, explanation)
select f.quiz_id, c.id, f.answer, f.position, f.explanation
  from flat f
  join new_categories c
    on c.quiz_id = f.quiz_id
   and c.label = f.label;
