-- Kunst & Kultur, file 2 of 2. Twenty questions, medium and hard.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs, fakes) as (
    values

    ('kunst-kultur', 'nordische-mythologie', 'Nordische Mythologie',
     'Wofür steht der Name in der nordischen Sage?',
     'medium', 'Nordische Mythologie',
     'https://de.wikipedia.org/wiki/Nordische_Mythologie',
     '[["Odin", "Allvater der Götter", "Gab ein Auge für einen Schluck aus dem Brunnen der Weisheit."],
       ["Thor", "Donner und Hammer", "Sein Hammer Mjölnir kehrt von selbst zurück."],
       ["Loki", "List und Betrug", "Mal Helfer, mal Verräter der Götter."],
       ["Freya", "Liebe und Fruchtbarkeit", "Fährt in einem Wagen, den Katzen ziehen."],
       ["Balder", "Licht und Reinheit", "Ein Mistelzweig wurde ihm zum Verhängnis."],
       ["Heimdall", "Wächter der Regenbogenbrücke", "Hört das Gras wachsen."],
       ["Hel", "Reich der Toten", "Wer nicht im Kampf fiel, kam zu ihr."],
       ["Tyr", "Recht und Zweikampf", "Verlor die Hand im Rachen des Fenriswolfs."],
       ["Yggdrasil", "Weltenbaum", "Seine Wurzeln verbinden die neun Welten."],
       ["Walhall", "Halle der gefallenen Krieger", "Walküren führen die Toten dorthin."],
       ["Ragnarök", "Untergang der Welt", "Danach steigt eine neue Erde aus dem Meer."],
       ["Midgard", "Welt der Menschen", "Umschlungen von einer Schlange im Weltmeer."]]'::jsonb,
     '[["Gott der Dichtkunst", "Das wäre Bragi, und der fehlt auf diesem Brett."],
       ["Reich der Riesen", "Jotunheim steht nicht in dieser Liste."]]'::jsonb),

    ('kunst-kultur', 'kirchen-staedte', 'Sakralbauten & Städte',
     'In welcher Stadt steht der Bau?',
     'medium', 'Kirche (Bauwerk)',
     'https://de.wikipedia.org/wiki/Kirche_%28Bauwerk%29',
     '[["Sagrada Família", "Barcelona", "Gaudís Kirche, seit 1882 im Bau."],
       ["Notre-Dame", "Paris", "Nach dem Brand von 2019 wieder aufgebaut."],
       ["Westminster Abbey", "London", "Krönungskirche der englischen Könige."],
       ["Hagia Sophia", "Istanbul", "Kirche, Moschee, Museum und wieder Moschee."],
       ["Petersdom", "Vatikanstadt", "Größte Kirche der Welt, mit Michelangelos Kuppel."],
       ["Basilius-Kathedrale", "Moskau", "Bunte Zwiebeltürme am Roten Platz."],
       ["Kölner Dom", "Köln", "1880 vollendet, 632 Jahre nach Baubeginn."],
       ["Stephansdom", "Wien", "Buntes Ziegeldach mit dem Doppeladler."],
       ["Mailänder Dom", "Mailand", "Marmorfassade mit über 3000 Figuren."],
       ["Alexander-Newski-Kathedrale", "Sofia", "Erinnert an gefallene russische Soldaten."],
       ["Scheich-Zayid-Moschee", "Abu Dhabi", "Weißer Marmorbau mit dem größten handgeknüpften Teppich."],
       ["Goldener Tempel", "Amritsar", "Wichtigstes Heiligtum der Sikhs, umgeben von Wasser."]]'::jsonb,
     '[["Florenz", "Der Dom Santa Maria del Fiore stünde dort, er fehlt auf dem Brett."],
       ["Jerusalem", "Die Grabeskirche steht nicht in dieser Liste."]]'::jsonb),

    ('kunst-kultur', 'romanfiguren-werke', 'Romanfiguren & ihre Bücher',
     'Aus welchem Roman stammt die Figur?',
     'medium', 'Roman', 'https://de.wikipedia.org/wiki/Roman',
     '[["Rodion Raskolnikow", "Schuld und Sühne", "Ein Student erschlägt eine Pfandleiherin."],
       ["Kapitän Ahab", "Moby-Dick", "Die Jagd auf den weißen Wal wird zur Besessenheit."],
       ["Holden Caulfield", "Der Fänger im Roggen", "Ein Jugendlicher irrt durch New York."],
       ["Hans Castorp", "Der Zauberberg", "Aus drei Wochen Sanatorium werden sieben Jahre."],
       ["Winston Smith", "1984", "Er fälscht im Wahrheitsministerium die Vergangenheit."],
       ["Bilbo Beutlin", "Der Hobbit", "Ein Hobbit zieht mit Zwergen zum Drachen."],
       ["Josef K.", "Der Prozess", "Er wird angeklagt, ohne die Anklage zu erfahren."],
       ["Hercule Poirot", "Mord im Orientexpress", "Ein Zug im Schnee und zwölf Verdächtige."],
       ["Jean Valjean", "Die Elenden", "Ein entlassener Sträfling wird zum Wohltäter."],
       ["Dorian Gray", "Roman von Oscar Wilde", "Das Porträt altert an seiner Stelle, er selbst nicht."],
       ["Elizabeth Bennet", "Stolz und Vorurteil", "Sie durchschaut Mr. Darcy erst spät."],
       ["Jean-Baptiste Grenouille", "Das Parfum", "Ein Mörder mit dem feinsten Geruchssinn."]]'::jsonb,
     '[["Der Steppenwolf", "Harry Haller stammt daher, und die Figur fehlt auf dem Brett."],
       ["Krieg und Frieden", "Pierre Besuchow käme von dort, der Roman steht hier nicht."]]'::jsonb),

    ('kunst-kultur', 'schriftarten', 'Schriftarten & ihr Charakter',
     'Was kennzeichnet die Schrift?',
     'hard', 'Schriftart', 'https://de.wikipedia.org/wiki/Schriftart',
     '[["Helvetica", "Schweizer Grotesk", "1957 entworfen, Sinnbild sachlicher Gestaltung."],
       ["Times New Roman", "Zeitungsschrift", "Für die Londoner Times entworfen, platzsparend."],
       ["Garamond", "Renaissance-Antiqua", "Nach einem französischen Stempelschneider benannt."],
       ["Bodoni", "Klassizistische Antiqua", "Starker Kontrast zwischen dicken und dünnen Strichen."],
       ["Futura", "Geometrische Grotesk", "Aus Kreis, Dreieck und Quadrat konstruiert."],
       ["Gill Sans", "Britische Humanistische Grotesk", "Lange Hausschrift der Eisenbahn und der BBC."],
       ["Frutiger", "Schrift für Flughäfen", "Für Roissy entworfen, auf Fernwirkung geprüft."],
       ["Courier", "Schreibmaschinenschrift", "Jeder Buchstabe nimmt dieselbe Breite ein."],
       ["Fraktur", "Gebrochene Schrift", "In Deutschland bis 1941 als Drucktype üblich."],
       ["Comic Sans", "Handschriftliche Anmutung", "Für Sprechblasen gedacht, überall sonst verspottet."]]'::jsonb,
     '[["Nur Großbuchstaben ohne Kleinbuchstaben", "Auf keine Schrift in dieser Liste trifft das zu."],
       ["Eigens für Bildschirme entworfen", "Verdana wäre das, und die fehlt auf dem Brett."]]'::jsonb),

    ('kunst-kultur', 'kulturfeste-laender', 'Feste & Länder',
     'In welchem Land wird gefeiert?',
     'medium', 'Fest', 'https://de.wikipedia.org/wiki/Fest',
     '[["Karneval in Rio", "Brasilien", "Sambaschulen ziehen durch das Sambódromo."],
       ["Oktoberfest", "Deutschland", "Größtes Volksfest der Welt, seit 1810."],
       ["Holi", "Indien", "Das Fest der Farben zum Frühlingsbeginn."],
       ["Songkran", "Thailand", "Neujahr wird mit Wasser gefeiert."],
       ["Día de Muertos", "Mexiko", "Die Toten werden mit Zuckerschädeln empfangen."],
       ["La Tomatina", "Spanien", "Eine Stunde Tomatenschlacht in Buñol."],
       ["Hanami", "Japan", "Picknick unter blühenden Kirschbäumen."],
       ["Karneval von Venedig", "Italien", "Masken und Kostüme bis zum Aschermittwoch."],
       ["Sankt-Patricks-Tag", "Irland", "Weltweit wird an diesem Tag Grün getragen."],
       ["Thanksgiving", "USA", "Erntedank am vierten Donnerstag im November."],
       ["Nouruz", "Iran", "Neujahr zur Tagundnachtgleiche im Frühling."],
       ["Basler Fasnacht", "Schweiz", "Beginnt am Montag um vier Uhr früh im Dunkeln."]]'::jsonb,
     '[["China", "Das Frühlingsfest würde dorthin gehören, und es fehlt auf dem Brett."],
       ["Schottland", "Hogmanay steht nicht in dieser Liste."]]'::jsonb),

    ('kunst-kultur', 'kuenstler-stilrichtungen', 'Künstler & Stilrichtungen',
     'Für welche Richtung steht die Person?',
     'hard', 'Kunst', 'https://de.wikipedia.org/wiki/Kunst',
     '[["Wassily Kandinsky", "Abstrakte Malerei", "Er löste das Bild ganz vom Gegenstand."],
       ["Kasimir Malewitsch", "Suprematismus", "Ein schwarzes Quadrat als Nullpunkt der Malerei."],
       ["Piet Mondrian", "De Stijl", "Nur Waagerechte, Senkrechte und Grundfarben."],
       ["Marcel Duchamp", "Dada", "Ein Urinal wurde zum Kunstwerk erklärt."],
       ["Henri Matisse", "Fauvismus", "Die wilden Farben gaben der Gruppe den Namen."],
       ["Gustav Klimt", "Jugendstil", "Ornament, Fläche und Blattgold."],
       ["Salvador Dalí", "Surrealismus", "Traumbilder mit fotografischer Genauigkeit."],
       ["Jackson Pollock", "Action Painting", "Farbe wurde auf die am Boden liegende Leinwand getropft."],
       ["Andy Warhol", "Pop Art", "Siebdruck machte das Bild zur Serie."],
       ["Joseph Beuys", "Fluxus", "Erweiterter Kunstbegriff: jeder Mensch ein Künstler."],
       ["Frida Kahlo", "Magischer Realismus", "Selbstbildnisse zwischen Schmerz und Symbolik."],
       ["Banksy", "Streetart", "Schablonenbilder an Hauswänden, Identität unbekannt."]]'::jsonb,
     '[["Bauhaus", "Eine Schule und ein Stil, aber keiner Person auf dem Brett zugeordnet."],
       ["Futurismus", "Marinetti stünde dafür, und der fehlt in dieser Liste."]]'::jsonb),

    ('kunst-kultur', 'antike-autoren-werke', 'Antike Autoren & Werke',
     'Welches Werk stammt von dieser Person?',
     'hard', 'Antike', 'https://de.wikipedia.org/wiki/Antike',
     '[["Homer", "Ilias", "Der Zorn des Achill vor Troja."],
       ["Sappho", "Liebeslyrik von Lesbos", "Nur in Bruchstücken überliefert."],
       ["Äsop", "Fabeln", "Tiere handeln, damit Menschen sich erkennen."],
       ["Sophokles", "König Ödipus", "Der Suchende findet sich selbst als Täter."],
       ["Euripides", "Medea", "Eine Mutter rächt sich auf furchtbare Weise."],
       ["Platon", "Der Staat", "Enthält das Höhlengleichnis."],
       ["Aristophanes", "Lysistrata", "Frauen erzwingen mit Liebesentzug den Frieden."],
       ["Caesar", "Der Gallische Krieg", "Ganz Gallien ist in drei Teile geteilt."],
       ["Vergil", "Aeneis", "Von Troja nach Italien, als Gründungsmythos Roms."],
       ["Horaz", "Oden", "Von ihm stammt das carpe diem."],
       ["Ovid", "Metamorphosen", "Verwandlungsgeschichten von der Schöpfung bis Caesar."],
       ["Plinius der Ältere", "Naturalis historia", "Enzyklopädie der antiken Naturkunde."]]'::jsonb,
     '[["Odyssee", "Auch von Homer, doch auf dem Brett steht seine Ilias."],
       ["Die Bekenntnisse", "Von Augustinus, und der fehlt in dieser Liste."]]'::jsonb),

    ('kunst-kultur', 'pigmente-herkunft', 'Farbpigmente & ihre Herkunft',
     'Woraus wurde die Farbe gewonnen?',
     'hard', 'Pigmente', 'https://de.wikipedia.org/wiki/Pigmente',
     '[["Ultramarin", "Lapislazuli", "Teurer als Gold, deshalb dem Mantel Marias vorbehalten."],
       ["Purpur", "Purpurschnecke", "Für ein Gramm brauchte es Tausende Tiere."],
       ["Karmin", "Schildläuse", "Aus Cochenille-Läusen auf Kakteen gewonnen."],
       ["Indigo", "Färberwaid und Indigopflanze", "Färbt bis heute die Jeans blau."],
       ["Ocker", "Eisenhaltige Erde", "Schon in den Höhlenbildern von Lascaux benutzt."],
       ["Umbra", "Erde aus Umbrien", "Gebrannt wird sie noch dunkler."],
       ["Zinnober", "Quecksilbersulfid", "Leuchtend rot und ausgesprochen giftig."],
       ["Bleiweiß", "Blei und Essigdämpfe", "Jahrhundertelang das beste Weiß, mit hohem Preis für die Maler."],
       ["Grünspan", "Kupfer und Essig", "Frisst sich mit der Zeit durch die Malschicht."],
       ["Kobaltblau", "Kobalterz", "Ersetzte ab 1800 das teure Ultramarin."],
       ["Kadmiumgelb", "Kadmiumsulfid", "Kräftig und deckend, ebenfalls giftig."],
       ["Rußschwarz", "Verbrannte Öle und Harze", "Das älteste Schwarz überhaupt."]]'::jsonb,
     '[["Gemahlene Perlmuscheln", "Aus ihnen entsteht kein Pigment auf diesem Brett."],
       ["Safranfäden", "Sie färben Speisen, sind hier aber keine Antwort."]]'::jsonb),

    ('kunst-kultur', 'designklassiker', 'Designklassiker & Gestalter',
     'Wer entwarf das Möbel oder Gerät?',
     'hard', 'Design', 'https://de.wikipedia.org/wiki/Design',
     '[["Thonet Nr. 14", "Michael Thonet", "Kaffeehausstuhl aus gebogenem Buchenholz."],
       ["Wassily-Sessel", "Marcel Breuer", "Stahlrohr, angeregt vom Fahrradlenker."],
       ["Barcelona-Sessel", "Mies van der Rohe", "Für den Pavillon der Weltausstellung 1929."],
       ["Lounge Chair", "Charles und Ray Eames", "Schichtholz und Leder, seit 1956 im Programm."],
       ["Panton Chair", "Verner Panton", "Erster Stuhl aus einem Stück Kunststoff."],
       ["Tolomeo-Leuchte", "Michele De Lucchi", "Gegengewicht und Seilzug halten jede Stellung."],
       ["Juicy Salif", "Philippe Starck", "Zitronenpresse, die eher Skulptur als Werkzeug ist."],
       ["Sacco-Sitzsack", "Gatti, Paolini und Teodoro", "Der Sitz passt sich dem Körper an."],
       ["Braun SK 4", "Dieter Rams", "Wegen der Plexiglashaube Schneewittchensarg genannt."],
       ["iMac G3", "Jonathan Ive", "Durchsichtiges Gehäuse brachte Farbe in die Computer."]]'::jsonb,
     '[["Arne Jacobsen", "Der Ameisenstuhl stammt von ihm, und der fehlt auf dem Brett."],
       ["Alvar Aalto", "Der Hocker 60 steht nicht in dieser Liste."]]'::jsonb),

    ('kunst-kultur', 'gaerten-parks', 'Berühmte Gärten & Orte',
     'Wo liegt der Garten?',
     'medium', 'Garten', 'https://de.wikipedia.org/wiki/Garten',
     '[["Central Park", "New York", "Angelegt ab 1858 mitten auf der Insel Manhattan."],
       ["Keukenhof", "Niederlande", "Millionen Tulpenzwiebeln, nur wenige Wochen geöffnet."],
       ["Englischer Garten", "München", "Größer als der Central Park, mit stehender Welle."],
       ["Kew Gardens", "London", "Botanische Sammlung mit historischen Glashäusern."],
       ["Giardino di Boboli", "Florenz", "Der Garten hinter dem Palazzo Pitti."],
       ["Villa d''Este", "Latium", "Hunderte Brunnen, alle allein durch Gefälle betrieben."],
       ["Ryōan-ji", "Kyoto", "Fünfzehn Steine im Kies, nie alle zugleich sichtbar."],
       ["Tivoli-Garten", "Kopenhagen", "Vergnügungspark von 1843, Vorbild für Disneyland."],
       ["Park Sanssouci", "Potsdam", "Weinbergterrassen unter dem Schloss Friedrichs II."],
       ["Generalife", "Granada", "Sommergarten der Alhambra mit Wasserläufen."],
       ["Butchart Gardens", "Kanada", "In einem ausgebeuteten Kalksteinbruch angelegt."],
       ["Garten von Versailles", "Frankreich", "Le Nôtres Achsen ordnen die Landschaft."]]'::jsonb,
     '[["Wien", "Der Schlosspark Schönbrunn läge dort, er fehlt auf dem Brett."],
       ["Suzhou", "Die Gelehrtengärten stehen nicht in dieser Liste."]]'::jsonb),

    ('kunst-kultur', 'kleidung-laender', 'Traditionelle Kleidung',
     'Woher stammt das Kleidungsstück?',
     'medium', 'Kleidung', 'https://de.wikipedia.org/wiki/Kleidung',
     '[["Kimono", "Japan", "Wird stets links über rechts geschlossen."],
       ["Sari", "Indien", "Mehrere Meter Stoff, ungeschnitten gewickelt."],
       ["Hanbok", "Korea", "Hohe Taille und weiter Rock."],
       ["Cheongsam", "China", "Enges Kleid mit Stehkragen, aus Shanghai."],
       ["Kilt", "Schottland", "Das Karomuster steht für den Clan."],
       ["Dirndl", "Österreich", "Die Schleifenseite verriet früher den Beziehungsstatus."],
       ["Poncho", "Anden", "Ein Umhang aus einem Stück mit Kopfloch."],
       ["Sombrero", "Mexiko", "Breite Krempe gegen die Sonne."],
       ["Kaftan", "Naher Osten", "Langes, weites Obergewand aus Seide oder Baumwolle."],
       ["Boubou", "Westafrika", "Weites Gewand, oft reich bestickt."],
       ["Fez", "Marokko", "Kegelförmige Filzkappe mit Quaste."],
       ["Sarong", "Indonesien", "Ein Tuch, um die Hüfte gebunden."]]'::jsonb,
     '[["Griechenland", "Die Fustanella käme von dort, und sie fehlt auf dem Brett."],
       ["Peru", "Der Chullo steht nicht in dieser Liste."]]'::jsonb),

    ('kunst-kultur', 'heilige-buecher', 'Heilige Schriften & Religionen',
     'Zu welcher Religion gehört die Schrift?',
     'medium', 'Heilige Schriften',
     'https://de.wikipedia.org/wiki/Heilige_Schriften',
     '[["Bibel", "Christentum", "Altes und Neues Testament in einem Band."],
       ["Koran", "Islam", "In 114 Suren, auf Arabisch offenbart."],
       ["Tora", "Judentum", "Die fünf Bücher Mose, in der Synagoge als Rolle."],
       ["Veden", "Hinduismus", "Jahrhundertelang mündlich weitergegeben."],
       ["Tripitaka", "Buddhismus", "Der Name bedeutet drei Körbe."],
       ["Guru Granth Sahib", "Sikhismus", "Wird selbst als lebendiger Lehrer verehrt."],
       ["Avesta", "Zoroastrismus", "Schriften um den Propheten Zarathustra."],
       ["Kojiki", "Shintō", "Älteste erhaltene Chronik Japans."],
       ["Tao Te King", "Daoismus", "Einundachtzig knappe Abschnitte über den Weg."],
       ["Gespräche des Konfuzius", "Konfuzianismus", "Von Schülern gesammelte Aussprüche."],
       ["Buch Mormon", "Mormonen", "1830 von Joseph Smith veröffentlicht."],
       ["Kitab-i-Aqdas", "Bahaitum", "Hauptwerk von Bahāʾullāh."]]'::jsonb,
     '[["Jainismus", "Die Agamas gehören dorthin, und sie fehlen auf dem Brett."],
       ["Manichäismus", "Keine Schrift in dieser Liste gehört dazu."]]'::jsonb),

    ('kunst-kultur', 'fotografen', 'Fotografen & ihre Bilder',
     'Wofür steht dieser Name in der Fotografie?',
     'hard', 'Fotografie', 'https://de.wikipedia.org/wiki/Fotografie',
     '[["Henri Cartier-Bresson", "Der entscheidende Augenblick", "Ein Bild im richtigen Sekundenbruchteil."],
       ["Ansel Adams", "Landschaften des Yosemite", "Schwarzweiß mit ausgereizter Tonwertskala."],
       ["Dorothea Lange", "Migrant Mother", "Gesicht der Wirtschaftskrise in den USA."],
       ["Robert Capa", "Kriegsreportage", "Wenn deine Bilder nicht gut sind, warst du nicht nah genug."],
       ["Steve McCurry", "Das afghanische Mädchen", "Grüne Augen auf einer Titelseite von 1985."],
       ["Sebastião Salgado", "Bilder der Arbeitswelt", "Goldmine, Ölfelder, Wanderungen."],
       ["Annie Leibovitz", "Porträts von Prominenten", "Inszenierte Titelbilder für Magazine."],
       ["Man Ray", "Fotogramme ohne Kamera", "Gegenstände direkt auf lichtempfindliches Papier gelegt."],
       ["Diane Arbus", "Porträts von Außenseitern", "Ihr Blick galt denen am Rand."],
       ["Alfred Stieglitz", "Fotografie als Kunstform", "Kämpfte dafür, dass Museen Fotos aufnehmen."]]'::jsonb,
     '[["Nan Goldin", "Ihre Bilder aus dem eigenen Umfeld fehlen auf diesem Brett."],
       ["Erste Farbfotografie überhaupt", "Sie geht auf Maxwell zurück, der hier nicht steht."]]'::jsonb),

    ('kunst-kultur', 'kunstbegriffe', 'Begriffe des Kunstbetriebs',
     'Was bezeichnet der Begriff?',
     'hard', 'Kunstgeschichte',
     'https://de.wikipedia.org/wiki/Kunstgeschichte',
     '[["Vernissage", "Eröffnung einer Ausstellung", "Ursprünglich der Tag, an dem der Firnis aufgetragen wurde."],
       ["Provenienz", "Herkunftsgeschichte eines Werks", "Entscheidend bei Raubkunst und Fälschungen."],
       ["Triptychon", "Dreiteiliges Bild", "Mittelbild mit zwei klappbaren Flügeln."],
       ["Retrospektive", "Rückschau auf ein Lebenswerk", "Zeigt Arbeiten aus allen Schaffensphasen."],
       ["Kurator", "Zusammenstellung einer Schau", "Entscheidet, was gezeigt wird und in welcher Ordnung."],
       ["Passepartout", "Kartonrahmen um das Blatt", "Hält das Werk vom Glas fern."],
       ["Auflage", "Zahl der Abzüge", "Bei Grafiken auf jedem Blatt vermerkt."],
       ["Biennale", "Alle zwei Jahre", "Die bekannteste findet in Venedig statt."],
       ["Ikonografie", "Deutung der Bildinhalte", "Fragt, wofür Gegenstände im Bild stehen."],
       ["Pentimento", "Übermalte erste Fassung", "Wird mit der Zeit oder im Röntgenbild sichtbar."]]'::jsonb,
     '[["Fälschung mit falscher Signatur", "Die Fälschung ist kein Begriff auf diesem Brett."],
       ["Katalog zur Ausstellung", "Er steht nicht in dieser Liste."]]'::jsonb),

    ('kunst-kultur', 'opernhaeuser-staedte', 'Opernhäuser & Städte',
     'In welcher Stadt steht das Haus?',
     'medium', 'Opernhaus', 'https://de.wikipedia.org/wiki/Opernhaus',
     '[["La Scala", "Mailand", "Eröffnet 1778, Maßstab für Sängerkarrieren."],
       ["Metropolitan Opera", "New York", "Seit 1966 am Lincoln Center."],
       ["Bolschoi-Theater", "Moskau", "Bekannt für sein Ballettensemble."],
       ["Royal Opera House", "London", "Im Viertel Covent Garden."],
       ["Opéra Garnier", "Paris", "Prunktreppe und Deckengemälde von Chagall."],
       ["Teatro Colón", "Buenos Aires", "Berühmt für seine Akustik."],
       ["Staatsoper", "Wien", "Der Opernball verwandelt sie einmal im Jahr in einen Ballsaal."],
       ["Gran Teatre del Liceu", "Barcelona", "Zweimal abgebrannt und wieder aufgebaut."],
       ["La Fenice", "Venedig", "Der Name bedeutet Phönix, was zur Geschichte passt."],
       ["Festspielhaus", "Bayreuth", "Von Wagner für seine eigenen Werke gebaut."],
       ["Elbphilharmonie", "Hamburg", "Konzerthaus auf einem alten Kaispeicher."],
       ["Semperoper", "Dresden", "Nach Krieg und Zerstörung 1985 neu eröffnet."]]'::jsonb,
     '[["Sydney", "Das Opernhaus dort fehlt auf diesem Brett."],
       ["Prag", "Das Ständetheater steht nicht in dieser Liste."]]'::jsonb),

    ('kunst-kultur', 'pseudonyme', 'Künstlernamen & bürgerliche Namen',
     'Wie hieß die Person wirklich?',
     'hard', 'Pseudonym', 'https://de.wikipedia.org/wiki/Pseudonym',
     '[["Mark Twain", "Samuel Clemens", "Der Name stammt aus der Sprache der Flussschiffer."],
       ["George Orwell", "Eric Arthur Blair", "Er nahm den Namen für sein erstes Buch an."],
       ["Lewis Carroll", "Charles Dodgson", "Im Hauptberuf Mathematiker in Oxford."],
       ["Molière", "Jean-Baptiste Poquelin", "Schauspieler und Theaterleiter in Paris."],
       ["Voltaire", "François-Marie Arouet", "Der Name entstand vermutlich als Anagramm."],
       ["George Eliot", "Mary Ann Evans", "Ein männlicher Name, um ernst genommen zu werden."],
       ["Novalis", "Friedrich von Hardenberg", "Der Name bedeutet der Neuland Bestellende."],
       ["Stendhal", "Henri Beyle", "Benannt nach einer Kleinstadt in der Altmark."],
       ["Joseph Conrad", "Józef Korzeniowski", "Schrieb Englisch, seine dritte Sprache."],
       ["Pablo Neruda", "Ricardo Reyes", "Den Namen wählte er nach einem tschechischen Dichter."],
       ["Kurt Tucholsky", "Peter Panter", "Er schrieb unter mehreren Namen zugleich."],
       ["Le Corbusier", "Charles-Édouard Jeanneret", "Der Name geht auf einen Vorfahren zurück."]]'::jsonb,
     '[["Aurore Dupin", "So hieß George Sand, die hier nicht steht."],
       ["Erich Kästner", "Er schrieb unter eigenem Namen, deshalb fehlt er auf dem Brett."]]'::jsonb),

    ('kunst-kultur', 'handschriften', 'Berühmte Handschriften',
     'Wo entstand oder liegt das Manuskript?',
     'hard', 'Schrift', 'https://de.wikipedia.org/wiki/Schrift',
     '[["Book of Kells", "Irland", "Evangeliar mit Zierseiten voller Knotenmuster."],
       ["Codex Manesse", "Zürich", "Sammlung von Minneliedern mit 137 Bildern."],
       ["Gutenberg-Bibel", "Mainz", "Erstes bedeutendes Buch aus beweglichen Lettern."],
       ["Codex Sinaiticus", "Sinai", "Eine der ältesten fast vollständigen Bibeln."],
       ["Schriftrollen vom Toten Meer", "Qumran", "1947 von Hirten in Höhlen gefunden."],
       ["Bayeux-Teppich", "Normandie", "Siebzig Meter Stickerei über die Eroberung Englands."],
       ["Lindisfarne-Evangeliar", "Nordengland", "Auf einer Klosterinsel geschrieben."],
       ["Voynich-Manuskript", "Norditalien", "Bis heute unentzifferte Schrift mit Pflanzenbildern."],
       ["Codex Leicester", "Florenz", "Leonardos Notizbuch über Wasser und Licht."],
       ["Wiener Genesis", "Konstantinopel", "Purpurpergament mit Silberschrift."]]'::jsonb,
     '[["Ägypten", "Die Papyri von Oxyrhynchos stammen von dort, sie fehlen hier."],
       ["Island", "Die Handschriften der Edda liegen dort, sie stehen nicht auf dem Brett."]]'::jsonb),

    ('kunst-kultur', 'mythen-helden', 'Helden der griechischen Sage',
     'Wofür ist die Gestalt bekannt?',
     'medium', 'Griechische Mythologie',
     'https://de.wikipedia.org/wiki/Griechische_Mythologie',
     '[["Herakles", "Zwölf Aufgaben", "Vom Löwen bis zum Höllenhund."],
       ["Odysseus", "Zehn Jahre Irrfahrt", "Er brauchte länger heim als der Krieg dauerte."],
       ["Theseus", "Kampf gegen den Minotaurus", "Der Faden der Ariadne führte ihn hinaus."],
       ["Perseus", "Enthauptung der Medusa", "Er sah sie nur im Spiegel des Schildes an."],
       ["Jason", "Raub des Goldenen Vlieses", "Mit der Argo und ihrer Mannschaft."],
       ["Achilles", "Verwundbare Ferse", "Nur dort war er nicht unverletzlich."],
       ["Prometheus", "Feuer für die Menschen", "Dafür an einen Felsen geschmiedet."],
       ["Sisyphos", "Stein, der zurückrollt", "Sinnbild für vergebliche Mühe."],
       ["Tantalus", "Ewig unerreichbare Speise", "Wasser und Früchte weichen zurück."],
       ["Narziss", "Verliebt ins Spiegelbild", "Er verging am eigenen Anblick."],
       ["Orpheus", "Gang in die Unterwelt", "Ein Blick zurück kostete ihn Eurydike."],
       ["Ödipus", "Rätsel der Sphinx", "Die Antwort lautete: der Mensch."]]'::jsonb,
     '[["Flug zu nah an der Sonne", "Das wäre Ikarus, und der fehlt auf diesem Brett."],
       ["Blick zurück verwandelt zu Stein", "Auf keine Gestalt in dieser Liste trifft das zu."]]'::jsonb),

    ('kunst-kultur', 'sprachfamilien', 'Sprachen & Sprachfamilien',
     'Zu welcher Sprachfamilie gehört die Sprache?',
     'hard', 'Sprachfamilie', 'https://de.wikipedia.org/wiki/Sprachfamilie',
     '[["Deutsch", "Germanisch", "Verwandt mit Niederländisch, Englisch und Schwedisch."],
       ["Spanisch", "Romanisch", "Aus dem gesprochenen Latein hervorgegangen."],
       ["Polnisch", "Slawisch", "Nahe verwandt mit Tschechisch und Slowakisch."],
       ["Hindi", "Indoarisch", "Geht auf das Sanskrit zurück."],
       ["Hebräisch", "Semitisch", "Verwandt mit Arabisch und Aramäisch."],
       ["Finnisch", "Finno-ugrisch", "Mit dem Ungarischen verwandt, nicht mit dem Schwedischen."],
       ["Türkisch", "Turksprachen", "Verwandt mit Kasachisch und Usbekisch."],
       ["Swahili", "Bantusprachen", "Verkehrssprache Ostafrikas mit arabischen Lehnwörtern."],
       ["Mandarin", "Sinotibetisch", "Verwandt mit dem Tibetischen und dem Birmanischen."],
       ["Tamil", "Dravidisch", "Im Süden Indiens gesprochen, keine indoeuropäische Sprache."],
       ["Maori", "Austronesisch", "Verwandt mit Sprachen von Hawaii bis Madagaskar."],
       ["Baskisch", "Isolierte Sprache", "Mit keiner bekannten Sprache verwandt."]]'::jsonb,
     '[["Keltisch", "Irisch gehörte dazu, und die Sprache fehlt auf dem Brett."],
       ["Uto-aztekisch", "Keine Sprache in dieser Liste gehört dazu."]]'::jsonb),

    ('kunst-kultur', 'palaeste-laender', 'Paläste & Länder',
     'In welchem Land steht der Palast?',
     'medium', 'Palast', 'https://de.wikipedia.org/wiki/Palast',
     '[["Versailles", "Frankreich", "Ludwig XIV. machte daraus den Sitz des Hofes."],
       ["Buckingham Palace", "Vereinigtes Königreich", "Die Flagge zeigt an, ob der Monarch da ist."],
       ["Topkapi", "Türkei", "Vier Jahrhunderte Residenz der Sultane."],
       ["Alhambra", "Spanien", "Rote Festung der Nasriden über Granada."],
       ["Winterpalast", "Russland", "Heute Teil der Eremitage."],
       ["Verbotene Stadt", "China", "Fast tausend Gebäude, Bürgern lange unzugänglich."],
       ["Hofburg", "Österreich", "Winterresidenz der Habsburger, heute Amtssitz."],
       ["Amalienborg", "Dänemark", "Vier gleiche Palais um einen achteckigen Platz."],
       ["Pena-Palast", "Portugal", "Bunter Romantikbau über Sintra."],
       ["Drottningholm", "Schweden", "Mit einem Barocktheater samt originaler Bühnentechnik."],
       ["Potala", "Tibet", "Über tausend Räume auf dem Roten Berg in Lhasa."],
       ["Mysore-Palast", "Indien", "An Festtagen von fast hunderttausend Lampen beleuchtet."]]'::jsonb,
     '[["Japan", "Der Kaiserpalast in Tokio fehlt auf diesem Brett."],
       ["Marokko", "Der Bahia-Palast steht nicht in dieser Liste."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

-- The answers that belong to no category. Numbered after the pairs so the two
-- sets never collide on `position`, though nothing reads it for a fake: the
-- pool is shuffled before a player sees it, and the review lists fakes on their
-- own rather than in board order.
fakes as (
    select q.id                                         as quiz_id,
           k.value ->> 0                                as label,
           k.value ->> 1                                as explanation,
           (jsonb_array_length(sp.pairs) + k.ord)::int  as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.fakes) with ordinality k(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
),

paired as (
    insert into items (quiz_id, category_id, label, position, explanation)
    select f.quiz_id, c.id, f.answer, f.position, f.explanation
      from flat f
      join new_categories c
        on c.quiz_id = f.quiz_id
       and c.label = f.label
    returning id
)

-- Same table, `category_id` left null. Both inserts run in the one statement,
-- so `items_quiz_id_label_key` still sees the pairs above: a fake written to
-- repeat an answer already on its own board fails the file rather than becoming
-- a second row nobody can tell apart.
insert into items (quiz_id, category_id, label, position, explanation)
select k.quiz_id, null, k.label, k.position, k.explanation
  from fakes k;
