-- Musik, file 2 of 2. Twenty questions, medium and hard.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs, fakes) as (
    values

    ('musik', 'komponisten-laender', 'Komponisten & Herkunftsländer',
     'Aus welchem Land stammte der Komponist?',
     'medium', 'Komponist', 'https://de.wikipedia.org/wiki/Komponist',
     '[["Johann Sebastian Bach", "Deutschland", "Geboren in Eisenach, gestorben in Leipzig."],
       ["Frédéric Chopin", "Polen", "Lebte ab 1831 in Paris, blieb der Heimat verbunden."],
       ["Franz Liszt", "Ungarn", "Als Klaviervirtuose in ganz Europa gefeiert."],
       ["Edvard Grieg", "Norwegen", "Verarbeitete Volksmelodien seiner Heimat."],
       ["Jean Sibelius", "Finnland", "Seine Finlandia wurde zur nationalen Hymne."],
       ["Antonín Dvořák", "Tschechien", "Schrieb in den USA die Sinfonie Aus der Neuen Welt."],
       ["Giuseppe Verdi", "Italien", "Sein Name wurde zum Ruf der Einigungsbewegung."],
       ["Claude Debussy", "Frankreich", "Löste die Harmonik von der klassischen Regel."],
       ["Edward Elgar", "England", "Bekannt für Pomp and Circumstance."],
       ["Modest Mussorgski", "Russland", "Bilder einer Ausstellung stammen von ihm."],
       ["Manuel de Falla", "Spanien", "Verband andalusische Volksmusik mit der Moderne."],
       ["Heitor Villa-Lobos", "Brasilien", "Verband Bach mit brasilianischer Folklore."]]'::jsonb,
     '[["Österreich", "Mozart und Schubert stammten von dort, beide fehlen auf dem Brett."],
       ["Griechenland", "Mikis Theodorakis käme von dort, und der steht hier nicht."]]'::jsonb),

    ('musik', 'dirigenten-orchester', 'Dirigenten & ihre Orchester',
     'Welches Ensemble leitete die Person prägend?',
     'hard', 'Dirigent', 'https://de.wikipedia.org/wiki/Dirigent',
     '[["Herbert von Karajan", "Berliner Philharmoniker", "Über drei Jahrzehnte Chefdirigent."],
       ["Leonard Bernstein", "New York Philharmonic", "Machte mit Fernsehkonzerten Musik populär."],
       ["Georg Solti", "Chicago Symphony Orchestra", "Rekordhalter bei Grammy-Auszeichnungen."],
       ["Riccardo Muti", "Mailänder Scala", "Fast zwei Jahrzehnte an der Spitze des Hauses."],
       ["Simon Rattle", "London Symphony Orchestra", "Zuvor lange in Berlin."],
       ["Gustavo Dudamel", "Los Angeles Philharmonic", "Kam aus dem venezolanischen Jugendorchesterprogramm."],
       ["Mariss Jansons", "Symphonieorchester des BR", "Zugleich in Amsterdam tätig."],
       ["Christian Thielemann", "Sächsische Staatskapelle", "Schwerpunkt bei Wagner und Strauss."],
       ["Valery Gergiev", "Mariinski-Theater", "Dirigiert oft ohne Taktstock."],
       ["Iván Fischer", "Budapest Festival Orchestra", "Von ihm mitgegründet."],
       ["Andris Nelsons", "Gewandhausorchester", "Verbindet Leipzig und Boston."],
       ["Claudio Abbado", "Lucerne Festival Orchestra", "Stellte es aus befreundeten Solisten zusammen."]]'::jsonb,
     '[["Wiener Philharmoniker", "Kein Dirigent auf diesem Brett ist ihnen hier zugeordnet."],
       ["Concertgebouworkest", "Bernard Haitink leitete es, und der fehlt in dieser Liste."]]'::jsonb),

    ('musik', 'popstars-laender', 'Popstars & Herkunftsländer',
     'Aus welchem Land kommt die Person?',
     'medium', 'Popmusik', 'https://de.wikipedia.org/wiki/Popmusik',
     '[["Beyoncé", "USA", "Begann bei Destiny''s Child in Houston."],
       ["Shakira", "Kolumbien", "Aus Barranquilla an der Karibikküste."],
       ["Björk", "Island", "Zuerst mit den Sugarcubes bekannt geworden."],
       ["Rosalía", "Spanien", "Verbindet Flamenco mit modernem Pop."],
       ["Stromae", "Belgien", "Der Künstlername ist die Umkehrung von Maestro."],
       ["Sia", "Australien", "Zeigt ihr Gesicht auf der Bühne meist nicht."],
       ["Drake", "Kanada", "Begann als Schauspieler in einer Jugendserie."],
       ["Ed Sheeran", "England", "Spielt seine Konzerte allein mit Loop-Gerät."],
       ["Zaz", "Frankreich", "Aus Straßenmusik zur internationalen Bühne."],
       ["Nena", "Deutschland", "Ihr Neunundneunzig-Luftballons-Lied lief weltweit."],
       ["Robyn", "Schweden", "Prägte den melancholischen Elektropop."],
       ["Bad Bunny", "Puerto Rico", "Machte spanischsprachigen Trap weltweit populär."]]'::jsonb,
     '[["Irland", "Sinéad O''Connor käme von dort, und sie fehlt auf dem Brett."],
       ["Nigeria", "Burna Boy steht nicht in dieser Liste."]]'::jsonb),

    ('musik', 'songs-interpreten', 'Songs & Interpreten',
     'Wer hat den Song aufgenommen?',
     'hard', 'Lied', 'https://de.wikipedia.org/wiki/Lied',
     '[["Bohemian Rhapsody", "Queen", "Sechs Minuten ohne Refrainstruktur."],
       ["Imagine", "John Lennon", "Am Klavier eingespielt, 1971."],
       ["Billie Jean", "Michael Jackson", "Der Moonwalk wurde dazu erstmals gezeigt."],
       ["Smells Like Teen Spirit", "Nirvana", "Der Titel stammt von einem Deodorant."],
       ["Hotel California", "Eagles", "Endet mit einem langen Gitarrenduett."],
       ["Wonderwall", "Oasis", "Das meistgespielte Lagerfeuerlied der 1990er."],
       ["Hallelujah", "Leonard Cohen", "Erst durch spätere Fassungen ein Welthit."],
       ["Respect", "Aretha Franklin", "Aus einem Männerlied wurde eine Hymne."],
       ["What''s Going On", "Marvin Gaye", "Sein Label wollte es zunächst nicht veröffentlichen."],
       ["Lose Yourself", "Eminem", "Erster Rap-Song mit einem Oscar."],
       ["Rolling in the Deep", "Adele", "Im Wohnzimmer entstanden, sagt sie selbst."],
       ["Purple Haze", "Jimi Hendrix", "Bekannt für den überraschenden Akkord."]]'::jsonb,
     '[["The Rolling Stones", "Satisfaction wäre der Song dazu, und der fehlt hier."],
       ["Whitney Houston", "I Will Always Love You steht nicht auf diesem Brett."]]'::jsonb),

    ('musik', 'nationalhymnen', 'Nationalhymnen & Länder',
     'Zu welchem Land gehört die Hymne?',
     'hard', 'Nationalhymne', 'https://de.wikipedia.org/wiki/Nationalhymne',
     '[["La Marseillaise", "Frankreich", "1792 als Kriegslied für die Rheinarmee gedichtet."],
       ["God Save the King", "Vereinigtes Königreich", "Text und Melodie sind nie amtlich festgelegt worden."],
       ["Das Lied der Deutschen", "Deutschland", "Melodie von Haydn, gesungen wird die dritte Strophe."],
       ["The Star-Spangled Banner", "USA", "Die Melodie stammt aus einem englischen Trinklied."],
       ["Il Canto degli Italiani", "Italien", "Nach dem Dichter auch Inno di Mameli genannt."],
       ["Kimigayo", "Japan", "Kürzeste Hymne der Welt, mit sehr altem Text."],
       ["Het Wilhelmus", "Niederlande", "Älteste Hymne der Welt nach der Textentstehung."],
       ["Advance Australia Fair", "Australien", "Löste 1984 God Save the Queen ab."],
       ["Nkosi Sikelel’ iAfrika", "Südafrika", "Vereint fünf Sprachen in einem Lied."],
       ["Hatikwa", "Israel", "Der Titel bedeutet die Hoffnung."],
       ["Mazurek Dąbrowskiego", "Polen", "Im Rhythmus eines Volkstanzes."],
       ["Ode an die Freude", "Europäische Union", "Ohne Text, um keine Sprache zu bevorzugen."]]'::jsonb,
     '[["Spanien", "Die Marcha Real hat keinen Text, und sie fehlt auf dem Brett."],
       ["Österreich", "Land der Berge steht nicht in dieser Liste."]]'::jsonb),

    ('musik', 'musikstaedte', 'Städte & ihre Musik',
     'Wofür steht die Stadt in der Musik?',
     'medium', 'Popmusik', 'https://de.wikipedia.org/wiki/Popmusik',
     '[["Wien", "Klassik und Walzer", "Drei der größten Klassiker lebten hier."],
       ["Leipzig", "Thomanerchor und Bach", "Bach war 27 Jahre lang Thomaskantor."],
       ["Salzburg", "Mozarts Geburtsstadt", "Sein Geburtshaus steht in der Getreidegasse."],
       ["Nashville", "Country-Musik", "Die Grand Ole Opry sendet seit 1925."],
       ["Memphis", "Sun Studio", "Hier nahm Elvis Presley seine ersten Titel auf."],
       ["Liverpool", "The Cavern Club", "Die Beatles spielten dort Hunderte Male."],
       ["Detroit", "Motown", "Ein Label, das den Soul in die Charts brachte."],
       ["Kingston", "Reggae und Studio One", "Die Wiege des jamaikanischen Sounds."],
       ["New Orleans", "Preservation Hall", "Traditioneller Jazz, jeden Abend live."],
       ["Berlin", "Technoclubs", "Nach 1989 zogen Clubs in leerstehende Gebäude."],
       ["Bayreuth", "Wagner-Festspiele", "Nur Werke eines einzigen Komponisten."],
       ["Rio de Janeiro", "Samba-Schulen", "Ganzjährige Vorbereitung auf den Karneval."]]'::jsonb,
     '[["Seattle", "Der Grunge kam von dort, und die Stadt fehlt auf diesem Brett."],
       ["Manchester", "Die Hacienda stand dort, sie steht nicht in dieser Liste."]]'::jsonb),

    ('musik', 'spielweisen', 'Spielanweisungen für Streicher',
     'Wie wird gespielt?',
     'hard', 'Musikinstrument',
     'https://de.wikipedia.org/wiki/Musikinstrument',
     '[["Pizzicato", "Mit dem Finger gezupft", "Der Bogen bleibt in der Hand."],
       ["Arco", "Wieder mit dem Bogen", "Hebt ein vorheriges Pizzicato auf."],
       ["Con sordino", "Mit aufgesetztem Dämpfer", "Der Klang wird weicher und leiser."],
       ["Flageolett", "Nur Obertöne klingen", "Die Saite wird leicht berührt, nicht gegriffen."],
       ["Tremolo", "Sehr schnelle Wiederholung", "Erzeugt Spannung im Orchestersatz."],
       ["Glissando", "Gleitend zwischen Tönen", "Der Finger rutscht über die Saite."],
       ["Vibrato", "Leichtes Schwanken der Tonhöhe", "Gibt dem Ton Wärme."],
       ["Doppelgriff", "Zwei Saiten zugleich", "Der Bogen streicht beide gemeinsam."],
       ["Col legno", "Mit dem Bogenholz", "Erzeugt ein trockenes Klopfen."],
       ["Sul ponticello", "Dicht am Steg", "Klingt gläsern und obertonreich."],
       ["Sul tasto", "Über dem Griffbrett", "Weich und flötenartig."],
       ["Bartók-Pizzicato", "Saite schlägt aufs Griffbrett", "Ein hörbarer Knall."]]'::jsonb,
     '[["Mit der flachen Hand aufs Instrument", "Keine Anweisung auf diesem Brett meint das."],
       ["Auf zwei Instrumenten zugleich", "So etwas verlangt keine Zeile hier."]]'::jsonb),

    ('musik', 'kirchenmusik-formen', 'Formen der Kirchenmusik',
     'Was bezeichnet die Form?',
     'hard', 'Kirchenmusik', 'https://de.wikipedia.org/wiki/Kirchenmusik',
     '[["Messe", "Vertonung der Messteile", "Von Kyrie bis Agnus Dei."],
       ["Requiem", "Totenmesse", "Statt des Gloria steht das Dies irae."],
       ["Kantate", "Mehrsätziges Stück mit Chor", "Bach schrieb sie für jeden Sonntag."],
       ["Oratorium", "Geistliches Werk ohne Bühne", "Erzählt wird, nicht gespielt."],
       ["Passion", "Vertonte Leidensgeschichte", "Ein Evangelist führt durch die Handlung."],
       ["Motette", "Chorstück ohne Begleitung", "Meist auf einen biblischen Text."],
       ["Choral", "Lied der Gemeinde", "Schlicht gesetzt, damit alle mitsingen können."],
       ["Te Deum", "Feierlicher Lobgesang", "Bei Siegen und Krönungen angestimmt."],
       ["Magnificat", "Lobgesang Marias", "Text aus dem Lukasevangelium."],
       ["Gregorianischer Gesang", "Einstimmiger lateinischer Gesang", "Ohne Begleitung und ohne Taktordnung."],
       ["Choralvorspiel", "Orgelstück vor dem Lied", "Führt die Gemeinde in die Melodie ein."],
       ["Halleluja", "Jubelruf im Gottesdienst", "In der Fastenzeit ausgelassen."]]'::jsonb,
     '[["Stabat Mater", "Eine eigene Form, die auf diesem Brett fehlt."],
       ["Weihnachtslied der Gemeinde", "Das Adventslied steht nicht in dieser Liste."]]'::jsonb),

    ('musik', 'elektronische-geraete', 'Geräte der elektronischen Musik',
     'Was macht das Gerät?',
     'hard', 'Elektronische Musik',
     'https://de.wikipedia.org/wiki/Elektronische_Musik',
     '[["Minimoog", "Klangerzeuger mit Oszillatoren", "Machte den Synthesizer bühnentauglich."],
       ["TB-303", "Bassmaschine für Acid", "Ursprünglich als Begleitautomat gedacht."],
       ["TR-808", "Drumcomputer mit Analogklang", "Ihre Bassdrum prägt den Hip-Hop."],
       ["MPC", "Sampler mit Pads", "Ausschnitte werden per Fingerdruck gespielt."],
       ["Vocoder", "Stimme formt den Klang", "Sprache wird über einen Synthesizer gelegt."],
       ["Mellotron", "Bandschleifen je Taste", "Vorläufer des Samplers, mit echten Aufnahmen."],
       ["Sequenzer", "Spielt Tonfolgen automatisch", "Ursprünglich ein Schrittprogramm."],
       ["MIDI", "Steuerdaten statt Klang", "Geräte verschiedener Hersteller verstehen einander."],
       ["Digital Audio Workstation", "Studio als Software", "Aufnehmen, schneiden und mischen im Rechner."],
       ["Effektpedal", "Verändert das Signal", "Verzerrung, Hall oder Verzögerung."]]'::jsonb,
     '[["Verstärkt das Signal für die Box", "Der Verstärker ist keine Antwort auf diesem Brett."],
       ["Nimmt den Schall über eine Membran auf", "Das Mikrofon fehlt in dieser Liste."]]'::jsonb),

    ('musik', 'instrumentenbauer', 'Instrumentenbauer',
     'Wofür ist der Name bekannt?',
     'hard', 'Musikinstrumentenbau',
     'https://de.wikipedia.org/wiki/Musikinstrumentenbau',
     '[["Stradivari", "Geigen aus Cremona", "Rund 500 Instrumente sind erhalten."],
       ["Steinway & Sons", "Konzertflügel", "Von einem ausgewanderten Deutschen gegründet."],
       ["Gibson", "E-Gitarren mit massivem Korpus", "Die Les Paul ist ihr bekanntestes Modell."],
       ["Rickenbacker", "Bässe mit hellem Klang", "Im Beat der 1960er allgegenwärtig."],
       ["Selmer", "Saxophone", "Das Modell Mark VI gilt als Maßstab."],
       ["Buffet Crampon", "Klarinetten", "Standard in vielen Orchestern."],
       ["Ludwig", "Schlagzeuge", "Ringo Starrs Set machte die Marke bekannt."],
       ["Hammond", "Elektrische Orgeln", "Der Klang entsteht durch rotierende Zahnräder."],
       ["Silbermann", "Barockorgeln in Sachsen", "Bach schätzte und kritisierte sie zugleich."],
       ["Sabian", "Becken", "Aus einer kanadischen Familienwerkstatt hervorgegangen."]]'::jsonb,
     '[["Fender", "Auch für E-Gitarren bekannt, aber nicht auf diesem Brett."],
       ["Bösendorfer", "Die Wiener Flügel stehen nicht in dieser Liste."]]'::jsonb),

    ('musik', 'musikindustrie-begriffe', 'Begriffe der Musikbranche',
     'Was bedeutet der Begriff?',
     'medium', 'Musikindustrie',
     'https://de.wikipedia.org/wiki/Musikindustrie',
     '[["Label", "Plattenfirma", "Veröffentlicht und vermarktet die Aufnahmen."],
       ["EP", "Veröffentlichung mittlerer Länge", "Länger als eine Single, kürzer als ein Album."],
       ["Remix", "Neue Fassung eines Stücks", "Aus denselben Spuren neu gemischt."],
       ["Cover", "Neuaufnahme eines fremden Songs", "Rechte am Text bleiben beim Urheber."],
       ["Sampling", "Übernahme eines Ausschnitts", "Ohne Freigabe ein Rechtsstreit."],
       ["Feature", "Gastauftritt auf einem Titel", "Im Titel meist mit feat. gekennzeichnet."],
       ["A&R", "Künstlersuche und Betreuung", "Steht für Artists and Repertoire."],
       ["Tantiemen", "Vergütung pro Nutzung", "Fällt bei Rundfunk und Streaming an."],
       ["GEMA", "Verwertungsgesellschaft", "Zieht Gebühren ein und schüttet sie aus."],
       ["Goldene Schallplatte", "Auszeichnung ab einer Verkaufsschwelle", "Die Grenze ist je Land verschieden."],
       ["Booking", "Vermittlung von Auftritten", "Regelt Termine, Gage und Ablauf."],
       ["Mastering", "Letzter Schliff der Aufnahme", "Sorgt für einheitlichen Klang über alle Titel."]]'::jsonb,
     '[["Aufnahme im Studio", "Die Session ist kein Begriff auf diesem Brett."],
       ["Verkaufszahl in einer Woche", "Die Chartplatzierung fehlt in dieser Liste."]]'::jsonb),

    ('musik', 'musikalische-formen', 'Musikalische Formen',
     'Was kennzeichnet die Form?',
     'hard', 'Formenlehre (Musik)',
     'https://de.wikipedia.org/wiki/Formenlehre_%28Musik%29',
     '[["Sonate", "Mehrsätziges Instrumentalwerk", "Der erste Satz folgt meist der Sonatenhauptsatzform."],
       ["Sinfonie", "Werk für großes Orchester", "In der Regel vier Sätze."],
       ["Solokonzert", "Solist gegen Orchester", "Mit einer Kadenz für den Solisten."],
       ["Fuge", "Thema wandert durch Stimmen", "Jede Stimme setzt versetzt ein."],
       ["Kanon", "Dieselbe Melodie zeitversetzt", "Bruder Jakob ist das bekannteste Beispiel."],
       ["Rondo", "Refrain kehrt immer wieder", "Dazwischen stehen wechselnde Abschnitte."],
       ["Variationen", "Ein Thema, ständig abgewandelt", "Harmonie bleibt, Gestalt ändert sich."],
       ["Suite", "Folge von Tanzsätzen", "Allemande, Courante, Sarabande, Gigue."],
       ["Etüde", "Übungsstück mit einer Schwierigkeit", "Bei Chopin zugleich Konzertmusik."],
       ["Präludium", "Vorspiel zu einem Werk", "Oft frei und improvisatorisch."],
       ["Ouvertüre", "Eröffnung einer Oper", "Nimmt Themen des Abends vorweg."],
       ["Nocturne", "Ruhiges Nachtstück", "Meist für Klavier, sangliche Oberstimme."]]'::jsonb,
     '[["Streichquartett", "Eine Besetzung und eine Form, die hier nicht steht."],
       ["Serenade", "Ein Ständchen am Abend, und es fehlt auf diesem Brett."]]'::jsonb),

    ('musik', 'hiphop-begriffe', 'Begriffe des Hip-Hop',
     'Was bezeichnet der Begriff?',
     'hard', 'Hip-Hop', 'https://de.wikipedia.org/wiki/Hip-Hop',
     '[["MC", "Rappende Person am Mikrofon", "Steht für Master of Ceremonies."],
       ["Beatboxing", "Rhythmus mit dem Mund", "Ersetzt den Drumcomputer."],
       ["Scratchen", "Platte von Hand bewegen", "Der Ton wird zum rhythmischen Element."],
       ["Freestyle", "Aus dem Stegreif gereimt", "Ohne vorbereiteten Text."],
       ["Flow", "Rhythmus des Vortrags", "Wie die Silben über den Beat laufen."],
       ["Punchline", "Zugespitzte Pointe", "Sitzt meist am Ende einer Zeile."],
       ["Bar", "Ein Takt im Rap", "Vier Schläge, meist zwei Reimzeilen."],
       ["Battle", "Wettstreit zweier Rapper", "Entschieden vom Publikum."],
       ["Breakdance", "Tanz zu den Breaks", "Aus den Blockpartys der Bronx."],
       ["Crew", "Feste Gruppe", "Rapper, DJs, Tänzer und Sprüher zusammen."],
       ["Hook", "Wiederkehrender Refrain", "Bleibt im Ohr, oft gesungen."],
       ["Beat", "Instrumentales Grundgerüst", "Wird von Produzenten geliefert."]]'::jsonb,
     '[["Sprühbild an der Wand", "Graffiti gehört dazu, steht aber nicht auf dem Brett."],
       ["Party mit zwei Plattenspielern", "Der Block Party fehlt in dieser Liste."]]'::jsonb),

    ('musik', 'opernsaengerinnen', 'Opernsängerinnen & Länder',
     'Aus welchem Land stammt die Sängerin?',
     'hard', 'Oper', 'https://de.wikipedia.org/wiki/Oper',
     '[["Maria Callas", "Griechenland", "In New York geboren, griechischer Herkunft."],
       ["Anna Netrebko", "Russland", "Begann als Reinigungskraft am Mariinski-Theater."],
       ["Cecilia Bartoli", "Italien", "Spezialistin für Barock und Belcanto."],
       ["Diana Damrau", "Deutschland", "Berühmt als Königin der Nacht."],
       ["Elīna Garanča", "Lettland", "Mezzosopran, gefeiert als Carmen."],
       ["Renée Fleming", "USA", "Sang bei einer Amtseinführung und beim Super Bowl."],
       ["Joan Sutherland", "Australien", "Wegen ihrer Beweglichkeit La Stupenda genannt."],
       ["Montserrat Caballé", "Spanien", "Sang mit Freddie Mercury Barcelona."],
       ["Janet Baker", "England", "Vor allem im Konzertfach und bei Händel geschätzt."],
       ["Anne Sofie von Otter", "Schweden", "Vom Barock bis zum Chanson zu Hause."],
       ["Sonya Yoncheva", "Bulgarien", "Aus dem Barock ins große italienische Fach gewechselt."],
       ["Sumi Jo", "Südkorea", "Koloratursopran mit Karriere in ganz Europa."]]'::jsonb,
     '[["Frankreich", "Natalie Dessay käme von dort, und sie fehlt auf dem Brett."],
       ["Norwegen", "Kirsten Flagstad steht nicht in dieser Liste."]]'::jsonb),

    ('musik', 'songwriter-duos', 'Songwriter-Duos',
     'Wofür steht das Gespann?',
     'hard', 'Songwriting', 'https://de.wikipedia.org/wiki/Songwriting',
     '[["Lennon und McCartney", "Die Beatles", "Alle Titel wurden gemeinsam gezeichnet."],
       ["Jagger und Richards", "Die Rolling Stones", "Der Manager drängte sie zum Schreiben."],
       ["John und Taupin", "Elton Johns Texte", "Der eine schreibt Texte, der andere die Musik."],
       ["Rodgers und Hammerstein", "Broadway-Musicals", "Von Oklahoma bis The Sound of Music."],
       ["Leiber und Stoller", "Früher Rock and Roll", "Schrieben für Elvis und die Coasters."],
       ["Holland-Dozier-Holland", "Motown-Hits", "Fließbandarbeit im besten Sinne."],
       ["Bacharach und David", "Eleganter Sixties-Pop", "Ungewöhnliche Takte in Radiohits."],
       ["Gilbert und Sullivan", "Englische Operette", "Text und Musik im viktorianischen England."],
       ["Simon und Garfunkel", "Folk-Duo der 1960er", "Bridge over Troubled Water als Höhepunkt."],
       ["Ashford und Simpson", "Soul-Klassiker", "Ein Ehepaar mit langer Erfolgsliste."]]'::jsonb,
     '[["Abba", "Andersson und Ulvaeus schrieben dafür, das Gespann fehlt auf dem Brett."],
       ["Pet Shop Boys", "Tennant und Lowe stehen nicht in dieser Liste."]]'::jsonb),

    ('musik', 'perkussion-herkunft', 'Trommeln & ihre Herkunft',
     'Woher stammt das Schlaginstrument?',
     'medium', 'Schlaginstrument',
     'https://de.wikipedia.org/wiki/Schlaginstrument',
     '[["Cajón", "Peru", "Eine Kiste, auf der man sitzt und spielt."],
       ["Tabla", "Indien", "Zwei Trommeln, mit Handballen und Fingern gespielt."],
       ["Taiko", "Japan", "Große Trommeln, im Ensemble mit ganzem Körpereinsatz."],
       ["Bodhrán", "Irland", "Rahmentrommel, mit einem Doppelschlägel gespielt."],
       ["Darbuka", "Naher Osten", "Bechertrommel mit hellem Randton."],
       ["Steel Drum", "Trinidad", "Aus Ölfässern gehämmert."],
       ["Surdo", "Brasilien", "Gibt den Puls in der Sambabatterie vor."],
       ["Udu", "Nigeria", "Tongefäß, gespielt über das seitliche Loch."],
       ["Congas", "Kuba", "Aus afrokubanischen Zeremonien in die Tanzmusik."],
       ["Bendir", "Nordafrika", "Rahmentrommel mit Schnarrsaite."],
       ["Doira", "Zentralasien", "Rahmentrommel mit klingenden Ringen."],
       ["Pauke", "Europäisches Orchester", "Über ein Pedal auf feste Töne stimmbar."]]'::jsonb,
     '[["Ghana", "Die Djembé kommt aus Westafrika, Ghana steht hier aber nicht."],
       ["Australien", "Die Klanghölzer der Aborigines fehlen auf diesem Brett."]]'::jsonb),

    ('musik', 'musikhochschulen', 'Musikhochschulen & Städte',
     'In welcher Stadt steht das Haus?',
     'hard', 'Musikhochschule',
     'https://de.wikipedia.org/wiki/Musikhochschule',
     '[["Juilliard School", "New York", "Aufnahmequote im niedrigen einstelligen Bereich."],
       ["Curtis Institute", "Philadelphia", "Alle Studierenden erhalten ein Vollstipendium."],
       ["Royal Academy of Music", "London", "Älteste Musikhochschule Großbritanniens."],
       ["Conservatoire national supérieur", "Paris", "Aus der Zeit der Französischen Revolution."],
       ["Moskauer Konservatorium", "Moskau", "Nach Tschaikowsky benannt."],
       ["Mozarteum", "Salzburg", "Trägt den Namen des berühmtesten Sohnes der Stadt."],
       ["Sibelius-Akademie", "Helsinki", "Größte Musikhochschule Nordeuropas."],
       ["Accademia di Santa Cecilia", "Rom", "Aus einer Musikergilde des 16. Jahrhunderts."],
       ["Hochschule für Musik Hanns Eisler", "Berlin", "Im Osten der Stadt gegründet."],
       ["Berklee College of Music", "Boston", "Schwerpunkt auf Jazz und populärer Musik."]]'::jsonb,
     '[["Wien", "Die Universität für Musik steht dort, und sie fehlt auf dem Brett."],
       ["Tokio", "Die Geidai steht nicht in dieser Liste."]]'::jsonb),

    ('musik', 'elektronische-stile', 'Stile der elektronischen Tanzmusik',
     'Was kennzeichnet den Stil?',
     'hard', 'Elektronische Tanzmusik',
     'https://de.wikipedia.org/wiki/Elektronische_Tanzmusik',
     '[["House", "Vierviertel mit Offbeat-Hi-Hat", "In Chicagoer Clubs entstanden."],
       ["Trance", "Lange Steigerungen und Breaks", "Aufbau über viele Takte hinweg."],
       ["Drum and Bass", "Schnelle Breakbeats", "Rund 175 Schläge pro Minute."],
       ["Dubstep", "Halbierter Puls und Wobble-Bass", "Der Bass wird moduliert statt gespielt."],
       ["Ambient", "Musik ohne festen Beat", "Als Klangumgebung gedacht."],
       ["Gabber", "Sehr hohes Tempo", "In Rotterdam populär geworden."],
       ["Electro", "Roboterhafte Beats", "Angelehnt an die frühe Kraftwerk-Ästhetik."],
       ["Minimal", "Wenige Elemente, kleine Veränderungen", "Wirkung entsteht durch Geduld."],
       ["Downtempo", "Langsame elektronische Musik", "Für Lounge und Chill-out."],
       ["Hardstyle", "Verzerrte Kick mit Melodie", "Große Festivalbühnen prägen den Stil."]]'::jsonb,
     '[["Techno", "Der Ursprungsstil aus Detroit fehlt auf diesem Brett."],
       ["Ganz ohne Schlagzeug und Bass", "Auf keinen Stil in dieser Liste trifft das zu."]]'::jsonb),

    ('musik', 'klavierstuecke', 'Klavierstücke & Komponisten',
     'Wer schrieb das Klavierstück?',
     'hard', 'Klavier', 'https://de.wikipedia.org/wiki/Klavier',
     '[["Für Elise", "Ludwig van Beethoven", "Erst Jahrzehnte nach seinem Tod veröffentlicht."],
       ["Rondo alla turca", "Wolfgang Amadeus Mozart", "Der Schlusssatz einer Klaviersonate."],
       ["Minutenwalzer", "Frédéric Chopin", "Dauert trotz des Namens länger als eine Minute."],
       ["Clair de lune", "Claude Debussy", "Dritter Satz der Suite bergamasque."],
       ["Gymnopédie Nr. 1", "Erik Satie", "Ruhig, gleichmäßig und ohne Steigerung."],
       ["Ungarische Rhapsodie Nr. 2", "Franz Liszt", "Auch in Zeichentrickfilmen berühmt geworden."],
       ["Träumerei", "Robert Schumann", "Aus den Kinderszenen."],
       ["Goldberg-Variationen", "Johann Sebastian Bach", "Aria mit dreißig Variationen."],
       ["Prélude cis-Moll", "Sergei Rachmaninow", "Machte ihn mit neunzehn Jahren berühmt."],
       ["Für Alina", "Arvo Pärt", "Nur wenige Töne, in großer Ruhe gesetzt."]]'::jsonb,
     '[["Franz Schubert", "Die Impromptus wären die Stücke dazu, und sie fehlen hier."],
       ["Scott Joplin", "The Entertainer steht nicht auf diesem Brett."]]'::jsonb),

    ('musik', 'akustik-begriffe', 'Musik & Akustik',
     'Was beschreibt der Begriff?',
     'hard', 'Akustik', 'https://de.wikipedia.org/wiki/Akustik',
     '[["Frequenz", "Bestimmt die Tonhöhe", "Doppelte Frequenz heißt eine Oktave höher."],
       ["Amplitude", "Bestimmt die Lautstärke", "Größerer Ausschlag, lauterer Ton."],
       ["Obertonreihe", "Mitschwingende Teiltöne", "Sie machen die Klangfarbe aus."],
       ["Klangfarbe", "Unterschied gleicher Tonhöhen", "Deshalb klingt Geige anders als Flöte."],
       ["Schwebung", "Langsames Pulsieren", "Entsteht bei fast gleicher Frequenz."],
       ["Konsonanz", "Als ruhig empfundener Zusammenklang", "Einfache Frequenzverhältnisse."],
       ["Dissonanz", "Als spannungsreich empfunden", "Verlangt in der Tonalität eine Auflösung."],
       ["Kammerton", "Bezugston zum Stimmen", "Heute meist 440 Hertz."],
       ["Nachhallzeit", "Wie lange nachklingt", "Für Konzertsäle sorgfältig geplant."],
       ["Absolutes Gehör", "Tonhöhe ohne Vergleich erkennen", "Selten und meist früh erworben."]]'::jsonb,
     '[["Wie schnell der Schall reist", "Die Schallgeschwindigkeit fehlt auf diesem Brett."],
       ["Zahl der Instrumente im Raum", "Das beschreibt kein Begriff in dieser Liste."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

-- The answers that belong to no category. Numbered after the pairs so the two
-- sets never collide on `position`, though nothing reads it for a fake: the
-- pool is shuffled before a player sees it, and the review lists fakes on their
-- own rather than in board order.
fakes as (
    select q.id                                         as quiz_id,
           k.value ->> 0                                as label,
           k.value ->> 1                                as explanation,
           (jsonb_array_length(sp.pairs) + k.ord)::int  as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.fakes) with ordinality k(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
),

paired as (
    insert into items (quiz_id, category_id, label, position, explanation)
    select f.quiz_id, c.id, f.answer, f.position, f.explanation
      from flat f
      join new_categories c
        on c.quiz_id = f.quiz_id
       and c.label = f.label
    returning id
)

-- Same table, `category_id` left null. Both inserts run in the one statement,
-- so `items_quiz_id_label_key` still sees the pairs above: a fake written to
-- repeat an answer already on its own board fails the file rather than becoming
-- a second row nobody can tell apart.
insert into items (quiz_id, category_id, label, position, explanation)
select k.quiz_id, null, k.label, k.position, k.explanation
  from fakes k;
