-- Musik, file 1 of 2. Twenty questions, medium and hard.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs, fakes) as (
    values

    ('musik', 'instrumente-herkunft', 'Instrumente & ihre Herkunft',
     'Woher stammt das Instrument?',
     'medium', 'Musikinstrument',
     'https://de.wikipedia.org/wiki/Musikinstrument',
     '[["Didgeridoo", "Australien", "Blasinstrument der Aborigines, oft aus ausgehöhltem Eukalyptus."],
       ["Sitar", "Indien", "Mitschwingende Resonanzsaiten erzeugen den typischen Klang."],
       ["Balalaika", "Russland", "Dreieckiger Korpus, drei Saiten."],
       ["Dudelsack", "Schottland", "Der Luftsack hält den Ton auch beim Atmen."],
       ["Alphorn", "Schweiz", "Bis zu vier Meter lang, ohne Klappen oder Ventile."],
       ["Koto", "Japan", "Wölbbrettzither mit verschiebbaren Stegen."],
       ["Erhu", "China", "Zweisaitige Fiedel, der Bogen liegt zwischen den Saiten."],
       ["Bouzouki", "Griechenland", "Prägt den Klang des Rebetiko."],
       ["Panflöte", "Anden", "Mehrere Rohre unterschiedlicher Länge nebeneinander."],
       ["Ukulele", "Hawaii", "Aus einem portugiesischen Instrument entstanden."],
       ["Djembé", "Westafrika", "Bechertrommel, mit bloßen Händen gespielt."],
       ["Bandoneon", "Argentinien", "In Deutschland erfunden, im Tango heimisch geworden."]]'::jsonb,
     '[["Irland", "Die keltische Harfe käme von dort, und sie fehlt auf dem Brett."],
       ["Türkei", "Die Saz steht nicht in dieser Liste."]]'::jsonb),

    ('musik', 'musiktheorie-grundbegriffe', 'Grundbegriffe der Musiktheorie',
     'Was bezeichnet der Begriff?',
     'hard', 'Musiktheorie', 'https://de.wikipedia.org/wiki/Musiktheorie',
     '[["Intervall", "Abstand zweier Töne", "Wird nach Stufen gezählt, die Prime eingeschlossen."],
       ["Oktave", "Acht Stufen Abstand", "Der obere Ton hat die doppelte Frequenz."],
       ["Quinte", "Fünf Stufen Abstand", "Das Verhältnis ist einfach drei zu zwei."],
       ["Akkord", "Mehrere Töne zugleich", "Der Dreiklang ist die einfachste Form."],
       ["Tonleiter", "Geordnete Reihe von Tönen", "Dur und Moll unterscheiden sich in der dritten Stufe."],
       ["Kadenz", "Typische Schlusswendung", "Tonika, Subdominante, Dominante, Tonika."],
       ["Takt", "Gruppierung der Schläge", "Der erste Schlag ist der betonte."],
       ["Tempo", "Geschwindigkeit des Stücks", "In Schlägen pro Minute angegeben."],
       ["Dynamik", "Abstufung der Lautstärke", "Von pianissimo bis fortissimo."],
       ["Vorzeichen", "Kreuz oder B", "Am Zeilenanfang gelten sie für das ganze Stück."],
       ["Modulation", "Wechsel der Tonart", "Meist über einen gemeinsamen Akkord."],
       ["Transposition", "Versetzen in andere Tonhöhe", "Alle Abstände bleiben gleich."]]'::jsonb,
     '[["Anzahl der Musiker im Stück", "Die Besetzung ist kein Begriff auf diesem Brett."],
       ["Zusammenklang zweier Stücke", "So etwas gibt es in der Musiktheorie nicht."]]'::jsonb),

    ('musik', 'vortragsbezeichnungen', 'Italienische Vortragsbezeichnungen',
     'Was bedeutet die Anweisung?',
     'hard', 'Vortragsbezeichnung',
     'https://de.wikipedia.org/wiki/Vortragsbezeichnung',
     '[["Allegro", "Schnell und munter", "Wörtlich: fröhlich."],
       ["Adagio", "Langsam", "Wörtlich: gemächlich."],
       ["Andante", "Gehend", "Im Tempo eines ruhigen Schritts."],
       ["Presto", "Sehr schnell", "Noch schneller ist nur prestissimo."],
       ["Largo", "Breit und getragen", "Das langsamste der gebräuchlichen Tempi."],
       ["Forte", "Laut", "Im Notenbild als f abgekürzt."],
       ["Piano", "Leise", "Abgekürzt als p, daher der Name des Instruments."],
       ["Crescendo", "Allmählich lauter", "Als sich öffnende Gabel geschrieben."],
       ["Diminuendo", "Allmählich leiser", "Die Gabel schließt sich."],
       ["Staccato", "Kurz abgestoßen", "Ein Punkt über der Note."],
       ["Legato", "Gebunden gespielt", "Ein Bogen über mehreren Tönen."],
       ["Ritardando", "Langsamer werdend", "Häufig am Ende eines Satzes."]]'::jsonb,
     '[["Sehr langsam und feierlich", "Grave wäre die Anweisung dazu, und die fehlt hier."],
       ["Mit Nachdruck betont", "Marcato steht nicht auf diesem Brett."]]'::jsonb),

    ('musik', 'genres-ursprung', 'Musikrichtungen & ihre Wiege',
     'Wo entstand die Musikrichtung?',
     'medium', 'Genre', 'https://de.wikipedia.org/wiki/Genre',
     '[["Blues", "Mississippi-Delta", "Aus Arbeitsliedern und Spirituals entstanden."],
       ["Jazz", "New Orleans", "Brass Bands, Blues und Ragtime trafen aufeinander."],
       ["Reggae", "Jamaika", "Aus Ska und Rocksteady entwickelt."],
       ["Samba", "Brasilien", "Wurzeln in afrobrasilianischen Traditionen."],
       ["Flamenco", "Andalusien", "Gesang, Gitarre und Tanz gehören zusammen."],
       ["Fado", "Portugal", "Melancholischer Gesang aus den Vierteln Lissabons."],
       ["Techno", "Detroit", "Maschinenmusik aus einer Industriestadt."],
       ["Hip-Hop", "Bronx", "Aus Blockpartys mit zwei Plattenspielern."],
       ["Grunge", "Seattle", "Verzerrte Gitarren und Flanellhemden."],
       ["K-Pop", "Südkorea", "Ab den 1990er Jahren systematisch aufgebaut."],
       ["Bossa Nova", "Rio de Janeiro", "Leiser, harmonisch verfeinerter Samba."],
       ["Chanson", "Paris", "Der Text steht über der Melodie."]]'::jsonb,
     '[["Wien", "Der Walzer entstand dort, und der fehlt auf diesem Brett."],
       ["Trinidad", "Der Calypso steht nicht in dieser Liste."]]'::jsonb),

    ('musik', 'alben-interpreten', 'Alben & Interpreten',
     'Wer hat das Album aufgenommen?',
     'hard', 'Musikalbum', 'https://de.wikipedia.org/wiki/Musikalbum',
     '[["Thriller", "Michael Jackson", "Meistverkauftes Album aller Zeiten."],
       ["The Dark Side of the Moon", "Pink Floyd", "Über 700 Wochen in den US-Charts."],
       ["Abbey Road", "The Beatles", "Das Cover zeigt einen Zebrastreifen in London."],
       ["Nevermind", "Nirvana", "Brachte den Grunge in die Charts."],
       ["Back in Black", "AC/DC", "Aufgenommen kurz nach dem Tod des Sängers."],
       ["Rumours", "Fleetwood Mac", "Entstand, während sich die Band privat zerlegte."],
       ["Kind of Blue", "Miles Davis", "Meistverkauftes Jazzalbum überhaupt."],
       ["OK Computer", "Radiohead", "Album über Entfremdung und Technik."],
       ["Purple Rain", "Prince", "Soundtrack zu seinem eigenen Film."],
       ["Born in the U.S.A.", "Bruce Springsteen", "Oft als patriotisch missverstanden."],
       ["Like a Prayer", "Madonna", "Das Video kostete sie einen Werbevertrag."],
       ["21", "Adele", "Verkaufsstärkstes Album der 2010er Jahre."]]'::jsonb,
     '[["David Bowie", "Ziggy Stardust wäre das Album dazu, und es fehlt hier."],
       ["Led Zeppelin", "Ihr viertes Album steht nicht auf diesem Brett."]]'::jsonb),

    ('musik', 'musiker-instrumente', 'Musiker & ihre Instrumente',
     'Welches Instrument spielte die Person?',
     'medium', 'Musiker', 'https://de.wikipedia.org/wiki/Musiker',
     '[["Jimi Hendrix", "E-Gitarre", "Spielte linkshändig auf umgedrehter Gitarre."],
       ["Miles Davis", "Trompete", "Prägte gleich mehrere Jazzstile."],
       ["John Coltrane", "Saxophon", "Sein Album A Love Supreme gilt als Meilenstein."],
       ["Glenn Gould", "Klavier", "Berühmt für seine Bach-Aufnahmen und sein Summen."],
       ["Yo-Yo Ma", "Violoncello", "Spielte bei mehreren Amtseinführungen in den USA."],
       ["Ravi Shankar", "Sitar", "Brachte indische Musik in den Westen."],
       ["Jascha Heifetz", "Violine", "Maßstab für Geiger des 20. Jahrhunderts."],
       ["Keith Moon", "Schlagzeug", "Trommler von The Who, berüchtigt für Exzesse."],
       ["Jaco Pastorius", "E-Bass", "Spielte bundlos und veränderte die Rolle des Basses."],
       ["James Galway", "Querflöte", "Bekannt für seine goldene Flöte."],
       ["Andrés Segovia", "Konzertgitarre", "Machte die klassische Gitarre konzertfähig."],
       ["Toots Thielemans", "Mundharmonika", "Auch als Pfeifer auf Filmmusiken zu hören."]]'::jsonb,
     '[["Kontrabass", "Charles Mingus spielte ihn, und der fehlt auf diesem Brett."],
       ["Orgel", "Kein Musiker in dieser Liste ist dafür bekannt."]]'::jsonb),

    ('musik', 'musicals-komponisten', 'Musicals & ihre Musik',
     'Wer schrieb die Musik?',
     'hard', 'Musical', 'https://de.wikipedia.org/wiki/Musical',
     '[["Cats", "Andrew Lloyd Webber", "Nach Gedichten von T. S. Eliot."],
       ["West Side Story", "Leonard Bernstein", "Romeo und Julia in New York."],
       ["Les Misérables", "Claude-Michel Schönberg", "Nach dem Roman von Victor Hugo."],
       ["Hamilton", "Lin-Manuel Miranda", "Gründerväter, erzählt mit Hip-Hop."],
       ["Chicago", "John Kander", "Mord und Showgeschäft in den 1920ern."],
       ["My Fair Lady", "Frederick Loewe", "Nach Shaws Pygmalion."],
       ["Mamma Mia!", "Benny Andersson", "Aus dem Liedkatalog von ABBA gebaut."],
       ["Der König der Löwen", "Elton John", "Aus dem Zeichentrickfilm auf die Bühne."],
       ["The Rocky Horror Show", "Richard O''Brien", "Kultstück mit Publikumsritualen."],
       ["Wicked", "Stephen Schwartz", "Die Vorgeschichte der Hexen von Oz."],
       ["Sweeney Todd", "Stephen Sondheim", "Ein Barbier mit sehr dunklen Absichten."],
       ["Hair", "Galt MacDermot", "Das Musical der Hippiebewegung."]]'::jsonb,
     '[["Richard Rodgers", "The Sound of Music stammt von ihm, und das Musical fehlt hier."],
       ["Jule Styne", "Gypsy wäre sein Stück, und es steht nicht auf dem Brett."]]'::jsonb),

    ('musik', 'klassische-werke', 'Klassische Werke & Komponisten',
     'Wer komponierte das Werk?',
     'hard', 'Klassische Musik',
     'https://de.wikipedia.org/wiki/Klassische_Musik',
     '[["Die vier Jahreszeiten", "Antonio Vivaldi", "Vier Violinkonzerte mit erklärenden Sonetten."],
       ["Eine kleine Nachtmusik", "Wolfgang Amadeus Mozart", "Serenade in vier Sätzen."],
       ["Neunte Sinfonie", "Ludwig van Beethoven", "Mit dem Chorfinale über Schillers Ode."],
       ["Ave Maria", "Franz Schubert", "Ursprünglich ein Lied nach Walter Scott."],
       ["Ungarische Tänze", "Johannes Brahms", "Bearbeitungen ungarischer Melodien."],
       ["Die Moldau", "Bedřich Smetana", "Der Fluss von der Quelle bis nach Prag."],
       ["Der Nussknacker", "Pjotr Tschaikowsky", "Ballettmusik zum Weihnachtsmärchen."],
       ["Karneval der Tiere", "Camille Saint-Saëns", "Zu Lebzeiten wollte er es kaum aufführen lassen."],
       ["Peer-Gynt-Suite", "Edvard Grieg", "Enthält die Morgenstimmung."],
       ["Boléro", "Maurice Ravel", "Ein einziges Thema, immer lauter wiederholt."],
       ["Also sprach Zarathustra", "Richard Strauss", "Die Anfangstakte kennt fast jeder aus dem Kino."],
       ["Rhapsody in Blue", "George Gershwin", "Beginnt mit einem Klarinettenglissando."]]'::jsonb,
     '[["Johann Sebastian Bach", "Die Brandenburgischen Konzerte fehlen auf diesem Brett."],
       ["Joseph Haydn", "Die Schöpfung steht nicht in dieser Liste."]]'::jsonb),

    ('musik', 'tonerzeugung', 'Instrumente & Tonerzeugung',
     'Wie entsteht der Ton?',
     'hard', 'Musikinstrument',
     'https://de.wikipedia.org/wiki/Musikinstrument',
     '[["Klavier", "Hämmer schlagen Saiten", "Die Taste löst die Mechanik aus."],
       ["Cembalo", "Kiele zupfen die Saiten", "Deshalb lässt sich die Lautstärke kaum abstufen."],
       ["Orgel", "Luft strömt durch Pfeifen", "Die Register bestimmen die Klangfarbe."],
       ["Violine", "Bogen streicht die Saite", "Kolophonium sorgt für die nötige Haftung."],
       ["Harfe", "Finger zupfen die Saiten", "Sieben Pedale ändern die Tonhöhe."],
       ["Trompete", "Lippen schwingen im Mundstück", "Ventile verlängern den Luftweg."],
       ["Klarinette", "Einfaches Rohrblatt schwingt", "Überbläst in die Duodezime, nicht in die Oktave."],
       ["Oboe", "Zwei Rohrblätter gegeneinander", "Ihr Ton gibt dem Orchester das Stimm-A."],
       ["Querflöte", "Luftstrom an der Anblaskante", "Kein Rohrblatt, nur die Anblaskante."],
       ["Pauke", "Angeschlagenes Fell schwingt", "Über ein Pedal stimmbar."],
       ["Akkordeon", "Durchschlagende Zungen im Luftstrom", "Der Balg liefert den Wind."],
       ["Theremin", "Hand verändert ein Feld", "Wird gespielt, ohne es zu berühren."]]'::jsonb,
     '[["Zungen schwingen im Mundstück", "Die Mundharmonika fehlt auf diesem Brett."],
       ["Kristall schwingt im Stromkreis", "So arbeitet kein Instrument in dieser Liste."]]'::jsonb),

    ('musik', 'musikpreise-laender', 'Musikpreise & Länder',
     'In welchem Land wird der Preis vergeben?',
     'medium', 'Musikpreis', 'https://de.wikipedia.org/wiki/Musikpreis',
     '[["Grammy Award", "USA", "Vergeben von der Recording Academy."],
       ["Brit Awards", "Vereinigtes Königreich", "Seit 1977, zunächst einmalig gedacht."],
       ["Juno Award", "Kanada", "Benannt nach einem Rundfunkfunktionär."],
       ["ARIA Award", "Australien", "Vom Verband der Tonträgerindustrie vergeben."],
       ["Polar Music Prize", "Schweden", "Von einem ABBA-Manager gestiftet."],
       ["Victoires de la Musique", "Frankreich", "Seit 1985 im Fernsehen übertragen."],
       ["Amadeus Austrian Music Award", "Österreich", "Nachfolger einer älteren Auszeichnung."],
       ["Swiss Music Awards", "Schweiz", "Seit 2008 vergeben."],
       ["Fryderyk", "Polen", "Nach dem Vornamen Chopins benannt."],
       ["Echo", "Deutschland", "2018 nach einem Skandal abgeschafft."],
       ["Latin Grammy", "Lateinamerika", "Eigene Verleihung für spanische und portugiesische Musik."],
       ["Mercury Prize", "Irland und Großbritannien", "Für das beste Album des Jahres."]]'::jsonb,
     '[["Japan", "Der Japan Record Award wird dort vergeben, er fehlt auf dem Brett."],
       ["Norwegen", "Der Spellemannprisen steht nicht in dieser Liste."]]'::jsonb),

    ('musik', 'stimmlagen', 'Stimmlagen',
     'Welche Stimme ist gemeint?',
     'medium', 'Stimmlage', 'https://de.wikipedia.org/wiki/Stimmlage',
     '[["Sopran", "Höchste Frauenstimme", "Trägt in der Oper meist die Hauptrolle."],
       ["Mezzosopran", "Mittlere Frauenstimme", "Zwischen Sopran und Alt."],
       ["Alt", "Tiefe Frauenstimme", "Dunkel und tragfähig."],
       ["Countertenor", "Männerstimme im Falsett", "Singt Partien, die einst Kastraten gehörten."],
       ["Tenor", "Hohe Männerstimme", "Die klassische Heldenrolle."],
       ["Bariton", "Mittlere Männerstimme", "Die häufigste Männerstimmlage."],
       ["Bass", "Tiefe Männerstimme", "Oft in Rollen von Königen und Priestern."],
       ["Koloratursopran", "Besonders bewegliche Höhe", "Etwa die Königin der Nacht."],
       ["Basso profondo", "Sehr tiefer Bass", "In der russischen Kirchenmusik verbreitet."],
       ["Knabensopran", "Unmutierte Jungenstimme", "Endet mit dem Stimmbruch."]]'::jsonb,
     '[["Sehr hohe Männerstimme in voller Bruststimme", "Auf keine Lage in dieser Liste trifft das zu."],
       ["Stimme ohne feste Tonhöhe", "Der Sprechgesang steht nicht auf diesem Brett."]]'::jsonb),

    ('musik', 'notenwerte', 'Notenwerte & Zeichen',
     'Was bedeutet das im Notenbild?',
     'hard', 'Notenwert', 'https://de.wikipedia.org/wiki/Notenwert',
     '[["Ganze Note", "Vier Schläge lang", "Im Viervierteltakt der ganze Takt."],
       ["Halbe Note", "Zwei Schläge lang", "Notenkopf mit Hals, aber ohne Fähnchen."],
       ["Viertelnote", "Ein Schlag", "Der übliche Grundschlag."],
       ["Achtelnote", "Halber Schlag", "Mit einem Fähnchen oder Balken."],
       ["Sechzehntelnote", "Viertel eines Schlags", "Zwei Fähnchen oder zwei Balken."],
       ["Punktierte Note", "Anderthalbfache Dauer", "Der Punkt fügt die Hälfte hinzu."],
       ["Triole", "Drei statt zwei", "Drei gleiche Noten in der Zeit von zweien."],
       ["Pause", "Vorgeschriebenes Schweigen", "Auch Stille ist gemessen."],
       ["Fermate", "Länger aushalten", "Die Dauer entscheidet der Ausführende."],
       ["Haltebogen", "Zwei Noten zu einer", "Verbindet gleiche Tonhöhen über den Taktstrich."],
       ["Auftakt", "Unvollständiger erster Takt", "Die fehlenden Schläge stehen am Schluss."],
       ["Synkope", "Verschobene Betonung", "Betont wird gegen den Grundschlag."]]'::jsonb,
     '[["Acht Schläge lang", "Die Doppelganze wäre das, und die fehlt auf dem Brett."],
       ["Zwei Töne gleichzeitig", "Das ist ein Zusammenklang, kein Notenwert."]]'::jsonb),

    ('musik', 'bands-frontmaenner', 'Bands & ihre Sänger',
     'Wer stand am Mikrofon?',
     'hard', 'Rockband', 'https://de.wikipedia.org/wiki/Rockband',
     '[["Queen", "Freddie Mercury", "Vier Oktaven Stimmumfang, sagen Analysen."],
       ["The Doors", "Jim Morrison", "Starb 1971 mit 27 Jahren in Paris."],
       ["Led Zeppelin", "Robert Plant", "Seine hohe Stimme prägte den Hardrock."],
       ["The Rolling Stones", "Mick Jagger", "Seit über sechzig Jahren auf der Bühne."],
       ["U2", "Bono", "Der Name kommt von einem Hörgerätegeschäft."],
       ["Nirvana", "Kurt Cobain", "Wollte nie Sprecher einer Generation sein."],
       ["Iron Maiden", "Bruce Dickinson", "Nebenbei Verkehrspilot."],
       ["Guns N'' Roses", "Axl Rose", "Berüchtigt für verspätete Auftritte."],
       ["Metallica", "James Hetfield", "Singt und spielt Rhythmusgitarre."],
       ["Oasis", "Liam Gallagher", "Der Streit mit dem Bruder wurde legendär."],
       ["Depeche Mode", "Dave Gahan", "Der Bandname stammt aus einem Modemagazin."],
       ["Rammstein", "Till Lindemann", "Gelernter Korbmacher und früherer Leistungsschwimmer."]]'::jsonb,
     '[["Steven Tyler", "Er sang bei Aerosmith, und die Band fehlt auf dem Brett."],
       ["Ozzy Osbourne", "Black Sabbath steht nicht in dieser Liste."]]'::jsonb),

    ('musik', 'musikepochen-merkmale', 'Musikepochen & Merkmale',
     'Woran ist die Epoche zu erkennen?',
     'hard', 'Musikgeschichte',
     'https://de.wikipedia.org/wiki/Musikgeschichte',
     '[["Mittelalter", "Einstimmiger Choral", "Gesungenes Gebet ohne Begleitung."],
       ["Renaissance", "Verwobene Singstimmen", "Alle Stimmen gleichberechtigt geführt."],
       ["Barock", "Generalbass als Fundament", "Bezifferte Bassstimme, darüber wird ausgeziert."],
       ["Wiener Klassik", "Klare Perioden und Formen", "Acht Takte Frage, acht Takte Antwort."],
       ["Romantik", "Musik erzählt Geschichten", "Programmmusik und Kunstlied blühen auf."],
       ["Impressionismus", "Klangfarbe vor Harmonik", "Ganztonleitern und schwebende Akkorde."],
       ["Zwölftonmusik", "Alle zwölf Töne gleichberechtigt", "Eine Reihe bestimmt den Ablauf."],
       ["Neoklassizismus", "Rückgriff auf alte Formen", "Barocke Muster mit modernen Mitteln."],
       ["Serielle Musik", "Auch Rhythmus wird geordnet", "Nicht nur die Tonhöhen folgen einer Reihe."],
       ["Aleatorik", "Der Zufall entscheidet mit", "Der Ablauf ist nicht vollständig festgelegt."],
       ["Minimal Music", "Kleine Muster, ständig wiederholt", "Veränderung geschieht in winzigen Schritten."],
       ["Elektronische Musik", "Klang aus dem Generator", "Kein Instrument im herkömmlichen Sinn."]]'::jsonb,
     '[["Erste Aufnahmen auf Tonträger", "Eine technische Neuerung, keine Epoche auf dem Brett."],
       ["Improvisation über feste Akkordfolgen", "Das kennzeichnet den Jazz, der hier nicht steht."]]'::jsonb),

    ('musik', 'weltmusik-traditionen', 'Musiktraditionen der Welt',
     'Woher stammt die Tradition?',
     'medium', 'Weltmusik', 'https://de.wikipedia.org/wiki/Weltmusik',
     '[["Gamelan", "Indonesien", "Orchester aus Gongs und Metallophonen."],
       ["Mariachi", "Mexiko", "Trompeten, Geigen und die große Guitarrón."],
       ["Qawwali", "Pakistan", "Ekstatischer Sufi-Gesang mit Harmonium."],
       ["Griot-Gesang", "Westafrika", "Sänger als lebendiges Archiv einer Familie."],
       ["Jodeln", "Alpenraum", "Rascher Wechsel zwischen Brust- und Kopfstimme."],
       ["Obertongesang", "Tuwa", "Eine Stimme, zwei hörbare Töne zugleich."],
       ["Klezmer", "Osteuropa", "Musik jüdischer Hochzeiten, die Klarinette weint."],
       ["Rebetiko", "Griechenland", "Lieder der Hafenviertel, oft mit Bouzouki."],
       ["Highlife", "Ghana", "Blasinstrumente über westafrikanischen Rhythmen."],
       ["Cumbia", "Kolumbien", "Von der Karibikküste in ganz Lateinamerika verbreitet."],
       ["Enka", "Japan", "Sentimentale Balladen mit fester Gesangstechnik."],
       ["Morna", "Kap Verde", "Cesária Évora machte sie weltweit bekannt."]]'::jsonb,
     '[["Irland", "Die Sessions in den Pubs fehlen auf diesem Brett."],
       ["Peru", "Die Huayno-Musik steht nicht in dieser Liste."]]'::jsonb),

    ('musik', 'filmkomponisten', 'Filmkomponisten & Filme',
     'Zu welchem Film schrieb die Person die Musik?',
     'hard', 'Filmmusik', 'https://de.wikipedia.org/wiki/Filmmusik',
     '[["John Williams", "Star Wars", "Ein Leitmotiv für fast jede Figur."],
       ["Ennio Morricone", "Zwei glorreiche Halunken", "Die Titelmelodie kennt fast jeder."],
       ["Howard Shore", "Der Herr der Ringe", "Eigene Themen für Völker und Orte."],
       ["Nino Rota", "Der Pate", "Der Walzer wurde zum Erkennungszeichen."],
       ["Bernard Herrmann", "Psycho", "Nur Streicher, dafür schneidend."],
       ["Vangelis", "Die Stunde des Siegers", "Synthesizer zu Läufern in Zeitlupe."],
       ["Alan Silvestri", "Zurück in die Zukunft", "Fanfare zur Zeitmaschine."],
       ["Danny Elfman", "Batman", "Dunkler Marsch für die Fledermaus."],
       ["Ryuichi Sakamoto", "Der letzte Kaiser", "Verband westliche und ostasiatische Klangwelt."],
       ["Michael Giacchino", "Ratatouille", "Französische Akkordeonfarben in Paris."],
       ["Justin Hurwitz", "La La Land", "Jazzklavier als roter Faden."],
       ["Hildur Guðnadóttir", "Joker", "Cello als Stimme der Hauptfigur."]]'::jsonb,
     '[["Der weiße Hai", "Auch von John Williams, doch auf dem Brett steht Star Wars."],
       ["Der Pianist", "Wojciech Kilar schrieb die Musik, und der fehlt hier."]]'::jsonb),

    ('musik', 'tontraeger', 'Tonträger & Technik',
     'Wie wird die Musik gespeichert?',
     'medium', 'Tonträger', 'https://de.wikipedia.org/wiki/Tontr%C3%A4ger',
     '[["Wachswalze", "Rille in Wachs", "Frühestes Verfahren, jede Aufnahme ein Unikat."],
       ["Schallplatte", "Rille in Vinyl", "Die Nadel folgt der seitlichen Auslenkung."],
       ["Tonband", "Magnetisierte Schicht", "Erlaubte erstmals bequemen Schnitt."],
       ["Compact Cassette", "Magnetband in der Kassette", "Machte das Mixtape möglich."],
       ["Compact Disc", "Vertiefungen, vom Laser gelesen", "16 Bit bei 44100 Abtastungen je Sekunde."],
       ["Minidisc", "Magnetooptische Speicherung", "Klein, wiederbeschreibbar und schnell überholt."],
       ["DAT-Kassette", "Digitales Band", "Lange Standard im Studio."],
       ["MP3-Datei", "Verlustbehaftete Datei", "Was das Ohr verdeckt, wird weggelassen."],
       ["FLAC-Datei", "Verlustfreie Kompression", "Kleiner als WAV, klanglich identisch."],
       ["Streaming", "Abruf aus dem Netz", "Nichts liegt dauerhaft auf dem Gerät."]]'::jsonb,
     '[["Löcher in einer Papierrolle", "So arbeitet das Pianola, das hier nicht steht."],
       ["Ton auf dem Filmstreifen", "Die Lichttonspur fehlt auf diesem Brett."]]'::jsonb),

    ('musik', 'jazzstile', 'Jazzstile',
     'Was kennzeichnet den Stil?',
     'hard', 'Jazz', 'https://de.wikipedia.org/wiki/Jazz',
     '[["Dixieland", "Kollektive Improvisation", "Mehrere Bläser gleichzeitig, jeder eine Linie."],
       ["Swing", "Tanzbare Big Bands", "Arrangements für Bläsersätze."],
       ["Bebop", "Schnelle Soli über Akkorde", "Musik zum Zuhören, nicht zum Tanzen."],
       ["Cool Jazz", "Zurückgenommener Ton", "Leiser, klarer, an der Westküste gepflegt."],
       ["Hard Bop", "Blues und Gospel", "Erdiger als der Cool Jazz."],
       ["Modal Jazz", "Tonleitern statt Akkordfolgen", "Weniger Wechsel, mehr Raum."],
       ["Free Jazz", "Ohne feste Form", "Auch Tonart und Puls sind offen."],
       ["Jazz-Rock", "Elektrische Instrumente", "Rockrhythmus trifft Improvisation."],
       ["Latin Jazz", "Afrokubanische Rhythmen", "Clave statt Swingachtel."],
       ["Smooth Jazz", "Glatt produzierte Melodien", "Für das Radioformat gemacht."]]'::jsonb,
     '[["Mit indischen Ragas verbunden", "Der Indo-Jazz steht nicht auf diesem Brett."],
       ["Ganz ohne Improvisation", "Auf keinen Stil in dieser Liste trifft das zu."]]'::jsonb),

    ('musik', 'festivals-laender', 'Musikfestivals & Länder',
     'In welchem Land findet das Festival statt?',
     'medium', 'Musikfestival',
     'https://de.wikipedia.org/wiki/Musikfestival',
     '[["Woodstock", "USA", "1969 kamen weit mehr Menschen als erwartet."],
       ["Glastonbury", "England", "Beginnt auf einer Milchviehfarm in Somerset."],
       ["Roskilde", "Dänemark", "Der Gewinn geht an gemeinnützige Zwecke."],
       ["Sziget", "Ungarn", "Auf einer Donauinsel in Budapest."],
       ["Rock am Ring", "Deutschland", "An einer Rennstrecke in der Eifel gestartet."],
       ["Tomorrowland", "Belgien", "Elektronische Musik mit aufwendigen Bühnenbildern."],
       ["Primavera Sound", "Spanien", "Am Meer in Barcelona."],
       ["Montreux Jazz Festival", "Schweiz", "Am Ufer des Genfersees."],
       ["Fuji Rock", "Japan", "In einem Skigebiet in den Bergen."],
       ["Exit", "Serbien", "In einer Festung über der Donau."],
       ["Salzburger Festspiele", "Österreich", "Seit 1920, mit dem Jedermann am Domplatz."]]'::jsonb,
     '[["Frankreich", "Die Vieilles Charrues fänden dort statt, sie fehlen auf dem Brett."],
       ["Niederlande", "Das Lowlands steht nicht in dieser Liste."]]'::jsonb),

    ('musik', 'notation-zeichen', 'Zeichen der Notenschrift',
     'Was bedeutet das Zeichen?',
     'hard', 'Notation (Musik)',
     'https://de.wikipedia.org/wiki/Notation_%28Musik%29',
     '[["Violinschlüssel", "Legt das g fest", "Die Schnecke umkreist die zweite Linie."],
       ["Bassschlüssel", "Legt das f fest", "Zwei Punkte umschließen die vierte Linie."],
       ["Kreuz", "Halbton höher", "Gilt bis zum Ende des Takts."],
       ["B-Vorzeichen", "Halbton tiefer", "Aus einem runden b entstanden."],
       ["Auflösungszeichen", "Hebt Vorzeichen auf", "Stellt den Stammton wieder her."],
       ["Taktstrich", "Trennt die Takte", "Der doppelte Strich beendet einen Abschnitt."],
       ["Wiederholungszeichen", "Abschnitt noch einmal", "Zwei Punkte vor dem Doppelstrich."],
       ["Da capo", "Von vorn beginnen", "Meist bis zu einem Schlusszeichen."],
       ["Coda", "Eigener Schlussteil", "Wird über ein Zeichen angesprungen."],
       ["Triller", "Schneller Wechsel zweier Töne", "Als tr über der Note notiert."],
       ["Arpeggio", "Akkord nacheinander", "Als Wellenlinie vor dem Akkord."],
       ["Generalpause", "Alle schweigen", "Im Notenbild als G.P. vermerkt."]]'::jsonb,
     '[["Legt das c fest", "Das täte der C-Schlüssel, und der fehlt auf diesem Brett."],
       ["Zeigt die Anzahl der Musiker", "So ein Zeichen gibt es in der Notenschrift nicht."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

-- The answers that belong to no category. Numbered after the pairs so the two
-- sets never collide on `position`, though nothing reads it for a fake: the
-- pool is shuffled before a player sees it, and the review lists fakes on their
-- own rather than in board order.
fakes as (
    select q.id                                         as quiz_id,
           k.value ->> 0                                as label,
           k.value ->> 1                                as explanation,
           (jsonb_array_length(sp.pairs) + k.ord)::int  as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.fakes) with ordinality k(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
),

paired as (
    insert into items (quiz_id, category_id, label, position, explanation)
    select f.quiz_id, c.id, f.answer, f.position, f.explanation
      from flat f
      join new_categories c
        on c.quiz_id = f.quiz_id
       and c.label = f.label
    returning id
)

-- Same table, `category_id` left null. Both inserts run in the one statement,
-- so `items_quiz_id_label_key` still sees the pairs above: a fake written to
-- repeat an answer already on its own board fails the file rather than becoming
-- a second row nobody can tell apart.
insert into items (quiz_id, category_id, label, position, explanation)
select k.quiz_id, null, k.label, k.position, k.explanation
  from fakes k;
