-- Musik, leichte Fragen. Zwanzig Fragen, alle 'easy'.
--
-- Gefragt wird nach dem, was man aus Radio, Schule und Kinderzimmer kennt,
-- nicht nach Vortragsbezeichnungen und Formenlehre.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs, fakes) as (
    values

    ('musik', 'leicht-instrumentengruppen', 'Instrumente & Gruppen',
     'Wie spielt man dieses Instrument?',
     'easy', 'Musikinstrument',
     'https://de.wikipedia.org/wiki/Musikinstrument',
     '[["Geige", "Mit einem Bogen streichen", "Auch zupfen ist möglich."],
       ["Gitarre", "Saiten zupfen", "Sechs Saiten sind üblich."],
       ["Trompete", "Hineinblasen", "Die Lippen schwingen im Mundstück."],
       ["Klavier", "Tasten anschlagen", "Innen schlagen Hämmer auf Saiten."],
       ["Trommel", "Auf das Fell schlagen", "Mit Stöcken oder Händen."],
       ["Triangel", "Anschlagen und schwingen lassen", "Ein Metallstab genügt."],
       ["Harfe", "Mit den Fingern zupfen", "Sieben Pedale ändern die Tonhöhe."],
       ["Mundharmonika", "Blasen und ziehen", "Beide Richtungen ergeben Töne."],
       ["Xylophon", "Auf Holzstäbe schlagen", "Die Länge bestimmt den Ton."],
       ["Rassel", "Schütteln", "Eines der ersten Instrumente für Kinder."],
       ["Orgel", "Tasten und Pedale bedienen", "Auch die Füße spielen mit."],
       ["Kontrabass", "Im Stehen gespielt", "Das größte Streichinstrument."]]'::jsonb,
     '[["Mit dem Fuß treten", "Kein Instrument auf diesem Brett wird so gespielt."],
       ["Über die Saiten hauchen", "So klingt kein Instrument in dieser Liste."]]'::jsonb),

    ('musik', 'leicht-kinderlieder', 'Kinderlieder',
     'Wie geht das Lied weiter?',
     'easy', 'Kinderlied', 'https://de.wikipedia.org/wiki/Kinderlied',
     '[["Alle meine Entchen", "Schwimmen auf dem See", "Köpfchen in das Wasser."],
       ["Hänschen klein", "Ging allein", "In die weite Welt hinein."],
       ["Ein Männlein steht im Walde", "Ganz still und stumm", "Gemeint ist die Hagebutte."],
       ["Backe, backe Kuchen", "Der Bäcker hat gerufen", "Sieben Sachen braucht es dafür."],
       ["Laterne, Laterne", "Sonne, Mond und Sterne", "Gesungen zu Sankt Martin."],
       ["Der Mond ist aufgegangen", "Die goldnen Sternlein prangen", "Ein Abendlied von Matthias Claudius."],
       ["Old MacDonald hatte eine Farm", "Ia ia o", "Jede Strophe ein neues Tier."],
       ["Bruder Jakob", "Schläfst du noch", "Wird gern im Kanon gesungen."],
       ["Häschen in der Grube", "Saß und schlief", "Ein Bewegungslied."],
       ["Kuckuck, Kuckuck", "Ruft''s aus dem Wald", "Ein Frühlingslied."],
       ["Auf der Mauer, auf der Lauer", "Sitzt ''ne kleine Wanze", "Jede Strophe fehlt ein Buchstabe."],
       ["Summ, summ, summ", "Bienchen summ herum", "Ein Lied über die Biene."]]'::jsonb,
     '[["Wer will fleißige Handwerker sehn", "Ein Kinderlied, das auf diesem Brett fehlt."],
       ["Grün, grün, grün sind alle meine Kleider", "Es steht nicht in dieser Liste."]]'::jsonb),

    ('musik', 'leicht-lautstaerke-tempo', 'Laut, leise, schnell, langsam',
     'Was bedeutet das in der Musik?',
     'easy', 'Musik', 'https://de.wikipedia.org/wiki/Musik',
     '[["Forte", "Laut", "Im Notenbild ein f."],
       ["Piano", "Leise", "Im Notenbild ein p."],
       ["Crescendo", "Immer lauter", "Als sich öffnende Gabel gezeichnet."],
       ["Presto", "Sehr schnell", "Kaum noch mitzuklatschen."],
       ["Adagio", "Langsam", "Ruhig und getragen."],
       ["Pause", "Nicht spielen", "Auch Stille ist genau gemessen."],
       ["Fermate", "Länger aushalten", "Ein Punkt unter einem Bogen."],
       ["Wiederholungszeichen", "Noch einmal von vorn", "Zwei Punkte am Doppelstrich."],
       ["Takt", "Gleichmäßige Zählzeit", "Der erste Schlag wird betont."],
       ["Solo", "Eine Person allein", "Alle anderen schweigen."]]'::jsonb,
     '[["Immer leiser", "Das wäre Decrescendo, und es fehlt auf diesem Brett."],
       ["Gebunden spielen", "Legato steht nicht in dieser Liste."]]'::jsonb),

    ('musik', 'leicht-bands-erkennen', 'Bekannte Bands',
     'Woher kommt die Band?',
     'easy', 'Band (Musik)',
     'https://de.wikipedia.org/wiki/Band_%28Musik%29',
     '[["The Beatles", "England", "Sie kamen aus Liverpool."],
       ["ABBA", "Schweden", "Der Name besteht aus vier Anfangsbuchstaben."],
       ["Rammstein", "Deutschland", "Bekannt für ihre Bühnenshow mit Feuer."],
       ["U2", "Irland", "Gegründet in Dublin."],
       ["AC/DC", "Australien", "Gegründet in Sydney."],
       ["Nirvana", "USA", "Aus dem Bundesstaat Washington."],
       ["Måneskin", "Italien", "Der Name ist dänisch für Mondschein."],
       ["Daft Punk", "Frankreich", "Zwei Musiker mit Helmen."],
       ["BTS", "Südkorea", "Eine der bekanntesten K-Pop-Gruppen."],
       ["Rush", "Kanada", "Gegründet in Toronto."]]'::jsonb,
     '[["Niederlande", "Golden Earring käme von dort, und die Band fehlt hier."],
       ["Norwegen", "A-ha steht nicht auf diesem Brett."]]'::jsonb),

    ('musik', 'leicht-stimmen', 'Singstimmen',
     'Wie nennt man diese Stimme?',
     'easy', 'Gesang', 'https://de.wikipedia.org/wiki/Gesang',
     '[["Höchste Frauenstimme", "Sopran", "Sie singt meist die Hauptrolle."],
       ["Tiefe Frauenstimme", "Alt", "Dunkel und tragfähig."],
       ["Hohe Männerstimme", "Tenor", "Die klassische Heldenrolle."],
       ["Tiefste Männerstimme", "Bass", "Oft Könige und Priester in der Oper."],
       ["Viele Menschen singen zusammen", "Chor", "Nach Stimmlagen aufgeteilt."],
       ["Zwei Menschen singen zusammen", "Duett", "Beide gleichberechtigt."],
       ["Singen ohne Instrumente", "A cappella", "Nur mit Stimmen."],
       ["Leises Singen zwischen den Zähnen", "Summen", "Der Mund bleibt geschlossen."],
       ["Singen in sehr hoher Kopfstimme", "Falsett", "Männer erreichen so Frauenlagen."],
       ["Sprechgesang im Hip-Hop", "Rap", "Der Rhythmus steht über der Melodie."]]'::jsonb,
     '[["Mittlere Frauenstimme", "Der Mezzosopran fehlt auf diesem Brett."],
       ["Pfeifen statt singen", "Das ist keine Singstimme in dieser Liste."]]'::jsonb),

    ('musik', 'leicht-noten', 'Noten lesen',
     'Was bedeutet das Zeichen?',
     'easy', 'Notenschlüssel',
     'https://de.wikipedia.org/wiki/Notenschl%C3%BCssel',
     '[["Violinschlüssel", "Für hohe Töne", "Die Schnecke umkreist das g."],
       ["Bassschlüssel", "Für tiefe Töne", "Zwei Punkte um das f."],
       ["Ganze Note", "Vier Schläge lang", "Ein leerer Notenkopf ohne Hals."],
       ["Viertelnote", "Ein Schlag", "Ausgefüllter Kopf mit Hals."],
       ["Achtelnote", "Ein halber Schlag", "Mit einem Fähnchen."],
       ["Kreuz", "Einen Halbton höher", "Aus c wird cis."],
       ["B-Vorzeichen", "Einen Halbton tiefer", "Aus h wird b."],
       ["Taktstrich", "Trennt zwei Takte", "Am Ende steht ein doppelter."],
       ["Fünf waagerechte Linien", "Notenlinien", "Auf und zwischen ihnen stehen die Noten."],
       ["Punkt hinter der Note", "Hälfte länger", "Aus zwei Schlägen werden drei."]]'::jsonb,
     '[["Hebt ein Vorzeichen auf", "Das Auflösungszeichen fehlt auf diesem Brett."],
       ["Zeigt an, wie laut gespielt wird", "Danach fragt hier keine Zeile."]]'::jsonb),

    ('musik', 'leicht-musikrichtungen', 'Musikrichtungen',
     'Was ist typisch für die Musik?',
     'easy', 'Musikgenre', 'https://de.wikipedia.org/wiki/Genre',
     '[["Rock", "Verzerrte E-Gitarren", "Meist Gitarre, Bass und Schlagzeug."],
       ["Jazz", "Viel Improvisation", "Kein Abend klingt wie der andere."],
       ["Klassik", "Orchester und Notenblatt", "Alles ist genau aufgeschrieben."],
       ["Hip-Hop", "Sprechgesang über Beats", "Entstanden in der Bronx."],
       ["Techno", "Gleichmäßiger Beat vom Computer", "Zum Tanzen gemacht."],
       ["Volksmusik", "Regionale Melodien und Tracht", "Oft mit Akkordeon."],
       ["Reggae", "Betonung auf dem Nachschlag", "Aus Jamaika."],
       ["Schlager", "Einfache deutsche Texte", "Zum Mitsingen gedacht."],
       ["Blues", "Melancholische Tonfolgen", "Aus dem Süden der USA."],
       ["Metal", "Sehr laut und schnell", "Doppelte Basstrommel gehört dazu."],
       ["Country", "Gitarre und Fiedel", "Nashville ist das Zentrum."],
       ["Pop", "Eingängige Melodien", "Auf Radiotauglichkeit hin gemacht."]]'::jsonb,
     '[["Punk", "Kurz, schnell und roh, aber auf diesem Brett steht er nicht."],
       ["Soul", "Auch eine Richtung, die hier fehlt."]]'::jsonb),

    ('musik', 'leicht-instrumente-material', 'Woraus Instrumente sind',
     'Woraus besteht das Instrument vor allem?',
     'easy', 'Musikinstrument',
     'https://de.wikipedia.org/wiki/Musikinstrument',
     '[["Geige", "Holz", "Fichtendecke und Ahornboden."],
       ["Trompete", "Messing", "Deshalb heißt es Blechblasinstrument."],
       ["Trommelfell", "Tierhaut oder Kunststoff", "Früher ausschließlich Haut."],
       ["Triangel", "Stahl", "Ein gebogener Stab."],
       ["Blockflöte für Kinder", "Kunststoff", "Leicht zu reinigen."],
       ["Klaviersaiten", "Stahldraht", "Bis zu zwanzig Tonnen Zug im Rahmen."],
       ["Klaviertasten früher", "Elfenbein", "Heute längst verboten."],
       ["Djembe", "Ausgehöhlter Baumstamm", "Darüber eine Ziegenhaut."],
       ["Panflöte", "Bambusrohre", "Unterschiedlich lang gebunden."],
       ["Becken im Schlagzeug", "Bronze", "Die Legierung bestimmt den Klang."]]'::jsonb,
     '[["Glas", "Kein Instrument auf diesem Brett besteht daraus."],
       ["Ton gebrannt", "Die Okarina wäre das, und die fehlt in dieser Liste."]]'::jsonb),

    ('musik', 'leicht-wo-musik', 'Wo Musik erklingt',
     'Was passiert an diesem Ort?',
     'easy', 'Musik', 'https://de.wikipedia.org/wiki/Musik',
     '[["Konzertsaal", "Musik wird live gespielt", "Die Akustik ist genau geplant."],
       ["Tonstudio", "Musik wird aufgenommen", "Der Raum ist schallgedämmt."],
       ["Musikschule", "Musik wird gelernt", "Meist Einzelunterricht."],
       ["Kirche", "Orgel und Chor", "Sonntags im Gottesdienst."],
       ["Oper", "Gesungenes Theater", "Mit Orchester im Graben."],
       ["Club", "Musik zum Tanzen", "Meist abends und nachts."],
       ["Festivalgelände", "Viele Bands nacheinander", "Oft über mehrere Tage."],
       ["Straßenecke", "Straßenmusik", "Der Hut liegt offen davor."],
       ["Probenraum", "Eine Band übt", "Meist im Keller."],
       ["Blaskapelle im Festzelt", "Marsch und Polka", "Zum Volksfest gehört sie dazu."]]'::jsonb,
     '[["Bibliothek", "Dort ist es still, und Musik erklingt nicht."],
       ["Museum", "Auch dort spielt niemand, es steht nicht auf dem Brett."]]'::jsonb),

    ('musik', 'leicht-lieder-anlaesse', 'Lieder zu Anlässen',
     'Wann singt man das?',
     'easy', 'Lied', 'https://de.wikipedia.org/wiki/Lied',
     '[["Happy Birthday", "Zum Geburtstag", "Weltweit in vielen Sprachen."],
       ["Stille Nacht", "An Weihnachten", "1818 in Österreich entstanden."],
       ["Nationalhymne", "Bei Staatsakten", "Man steht dabei auf."],
       ["Hochzeitsmarsch", "Beim Auszug des Brautpaars", "Von Mendelssohn."],
       ["Schlaflied", "Vor dem Einschlafen", "Ruhig und gleichmäßig."],
       ["Karnevalsschlager", "In der Faschingszeit", "Zum Schunkeln gedacht."],
       ["Fußballgesang", "Im Stadion", "Die ganze Kurve singt mit."],
       ["Trauermusik", "Bei einer Beerdigung", "Meist langsam und leise."],
       ["Wanderlied", "Beim Wandern", "Es hält den Schritt im Takt."],
       ["Abendlied", "Zum Tagesabschluss", "Oft mit den Kindern gesungen."]]'::jsonb,
     '[["Beim Erntedankfest", "Ein Anlass, der auf diesem Brett fehlt."],
       ["Zum Schulanfang", "Er steht nicht in dieser Liste."]]'::jsonb),

    ('musik', 'leicht-beruehmte-musiker', 'Bekannte Musiker',
     'Wofür ist die Person bekannt?',
     'easy', 'Musiker', 'https://de.wikipedia.org/wiki/Musiker',
     '[["Wolfgang Amadeus Mozart", "Komponist der Zauberflöte", "Er komponierte schon als Kind."],
       ["Ludwig van Beethoven", "Neunte Sinfonie", "Er war am Ende taub."],
       ["Johann Sebastian Bach", "Kirchenmusik und Fugen", "Er hatte zwanzig Kinder."],
       ["Elvis Presley", "König des Rock", "Sein Haus heißt Graceland."],
       ["Michael Jackson", "König des Pop", "Er machte den Moonwalk bekannt."],
       ["Freddie Mercury", "Sänger von Queen", "Bekannt für Bohemian Rhapsody."],
       ["Beyoncé", "Weltbekannte Popsängerin", "Sie begann in einer Girlgroup."],
       ["Herbert Grönemeyer", "Deutscher Popsänger", "Sein Album Mensch ist das meistverkaufte."],
       ["Bob Marley", "Reggae aus Jamaika", "Seine Lieder gelten als Friedenshymnen."],
       ["Luciano Pavarotti", "Berühmter Operntenor", "Er sang auch in Stadien."],
       ["Nena", "Sängerin von 99 Luftballons", "Der Titel lief weltweit."],
       ["Taylor Swift", "Weltweite Stadiontourneen", "Sie schreibt ihre Lieder selbst."]]'::jsonb,
     '[["Erfinder des Klaviers", "Bartolomeo Cristofori war das, und der fehlt hier."],
       ["Sängerin von ABBA", "Agnetha Fältskog steht nicht auf diesem Brett."]]'::jsonb),

    ('musik', 'leicht-taktarten', 'Rhythmus & Takt',
     'Was gehört dazu?',
     'easy', 'Rhythmus', 'https://de.wikipedia.org/wiki/Rhythmus',
     '[["Walzer", "Dreivierteltakt", "Eins, zwei, drei."],
       ["Marsch", "Gleichmäßiger Schritt", "Links, rechts, links."],
       ["Herzschlag", "Zwei Schläge, einer betont", "Das erste Metrum, das jeder kennt."],
       ["Klatschen zum Lied", "Auf zwei und vier", "So macht es das Publikum richtig."],
       ["Metronom", "Gibt das Tempo vor", "Es tickt gleichmäßig."],
       ["Auftakt", "Vor dem ersten Takt", "Die Melodie beginnt vorher."],
       ["Pause im Takt", "Stille an fester Stelle", "Sie wird mitgezählt."],
       ["Trommelwirbel", "Sehr schnelle Schläge", "Kündigt oft etwas an."],
       ["Off-Beat", "Betonung dazwischen", "Typisch für Reggae."],
       ["Taktwechsel", "Der Takt ändert sich", "Man muss neu zählen."]]'::jsonb,
     '[["Ganz ohne Takt", "Kein Eintrag auf diesem Brett meint das."],
       ["Fünf Schläge im Takt", "Der Fünfvierteltakt fehlt in dieser Liste."]]'::jsonb),

    ('musik', 'leicht-musik-technik', 'Musik hören & aufnehmen',
     'Wozu dient das?',
     'easy', 'Tonträger', 'https://de.wikipedia.org/wiki/Tontr%C3%A4ger',
     '[["Kopfhörer", "Allein hören", "Stört niemanden im Raum."],
       ["Lautsprecher", "Für alle hörbar", "Eine Membran bewegt die Luft."],
       ["Mikrofon", "Stimme aufnehmen", "Es wandelt Schall in Spannung."],
       ["Schallplatte", "Musik in einer Rille", "Die Nadel tastet sie ab."],
       ["CD", "Musik als Vertiefungen", "Ein Laser liest sie."],
       ["Streamingdienst", "Musik aus dem Netz", "Nichts liegt auf dem Gerät."],
       ["Verstärker", "Signal lauter machen", "Ohne ihn bewegt sich keine Membran."],
       ["Plattenspieler", "Schallplatten abspielen", "Die Drehzahl muss stimmen."],
       ["Radio", "Musik über Funk empfangen", "Der Sender hat eine Frequenz."],
       ["Playlist", "Eigene Liederliste", "Man stellt sie selbst zusammen."]]'::jsonb,
     '[["Notenständer", "Er hält die Noten, aber Musik hört man damit nicht."],
       ["Stimmgerät", "Es hilft beim Stimmen, steht hier aber nicht."]]'::jsonb),

    ('musik', 'leicht-orchester', 'Im Orchester',
     'Wo sitzt oder was tut man?',
     'easy', 'Orchester', 'https://de.wikipedia.org/wiki/Orchester',
     '[["Dirigent", "Gibt vorn den Takt", "Mit dem Rücken zum Publikum."],
       ["Erste Geige", "Sitzt links vorn", "Der Konzertmeister sitzt hier."],
       ["Schlagwerk", "Steht ganz hinten", "Pauken und Becken."],
       ["Kontrabässe", "Stehen am Rand", "Sie sind zu groß zum Sitzen."],
       ["Holzbläser", "Sitzen in der Mitte", "Flöten, Oboen und Klarinetten."],
       ["Blechbläser", "Sitzen hinter den Holzbläsern", "Trompeten und Posaunen."],
       ["Oboe", "Gibt den Stimmton an", "Alle stimmen darauf ein."],
       ["Harfe", "Steht seitlich", "Sie braucht viel Platz."],
       ["Partitur", "Enthält alle Stimmen", "Nur der Dirigent liest sie."],
       ["Applaus", "Kommt am Ende", "Zwischen den Sätzen wird nicht geklatscht."]]'::jsonb,
     '[["Verkauft die Karten am Eingang", "Das gehört nicht ins Orchester."],
       ["Der Notenwart im Hintergrund", "Er kommt auf diesem Brett nicht vor."]]'::jsonb),

    ('musik', 'leicht-musik-laender', 'Musik aus aller Welt',
     'Woher stammt diese Musik?',
     'easy', 'Weltmusik', 'https://de.wikipedia.org/wiki/Weltmusik',
     '[["Samba", "Brasilien", "Herz des Karnevals in Rio."],
       ["Flamenco", "Spanien", "Gitarre, Gesang und Fußarbeit."],
       ["Reggae", "Jamaika", "Bob Marley machte ihn bekannt."],
       ["Tango", "Argentinien", "Aus den Hafenvierteln."],
       ["Jodeln", "Alpenraum", "Schneller Wechsel der Stimmlage."],
       ["Sirtaki", "Griechenland", "Er wird immer schneller."],
       ["K-Pop", "Südkorea", "Sorgfältig einstudierte Choreografien."],
       ["Dudelsackmusik", "Schottland", "Zu Paraden und Festen."],
       ["Gamelan", "Indonesien", "Orchester aus Gongs."],
       ["Fado", "Portugal", "Melancholischer Gesang aus Lissabon."],
       ["Mariachi", "Mexiko", "Trompeten und Geigen in Uniform."],
       ["Bollywoodmusik", "Indien", "Aus Filmen mit großen Tanzszenen."]]'::jsonb,
     '[["Kuba", "Die Salsa käme von dort, und sie fehlt auf diesem Brett."],
       ["Irland", "Die Fiddle-Musik steht nicht in dieser Liste."]]'::jsonb),

    ('musik', 'leicht-tanzen-musik', 'Musik zum Tanzen',
     'Wozu tanzt man das?',
     'easy', 'Tanz', 'https://de.wikipedia.org/wiki/Tanz',
     '[["Wiener Walzer", "Ballmusik im Dreivierteltakt", "Zur Eröffnung eines Balls."],
       ["Discofox", "Popmusik im Viervierteltakt", "Der häufigste Paartanz in Deutschland."],
       ["Polonaise", "Marschartige Musik", "Eine lange Reihe durch den Saal."],
       ["Breakdance", "Hip-Hop-Beats", "Auf dem Boden mit Drehungen."],
       ["Ententanz", "Einfache Melodie für Kinder", "Auf Kindergeburtstagen beliebt."],
       ["Macarena", "Feste Choreografie", "Alle machen dieselben Bewegungen."],
       ["Salsa", "Kubanische Rhythmen", "Als Paar mit vielen Drehungen."],
       ["Line Dance", "Countrymusik", "In Reihen, ohne Partner."],
       ["Rock n Roll", "Musik der 1950er", "Mit Sprüngen und Hebefiguren."],
       ["Sirtaki im Kreis", "Griechische Melodie", "Alle fassen sich an den Schultern."]]'::jsonb,
     '[["Walzer aus Wien im Zweivierteltakt", "Der Wiener Walzer geht im Dreivierteltakt."],
       ["Techno im Club", "Dazu tanzt man, auf diesem Brett steht es aber nicht."]]'::jsonb),

    ('musik', 'leicht-lied-teile', 'Aufbau eines Liedes',
     'Wie heißt dieser Teil?',
     'easy', 'Lied', 'https://de.wikipedia.org/wiki/Lied',
     '[["Der Teil, der immer wiederkehrt", "Refrain", "Ihn kennt man nach dem ersten Hören."],
       ["Der Teil mit wechselndem Text", "Strophe", "Sie erzählt die Geschichte weiter."],
       ["Der Anfang ohne Gesang", "Intro", "Es stimmt auf das Lied ein."],
       ["Das Ende eines Liedes", "Outro", "Oft langsam ausgeblendet."],
       ["Ein Instrument spielt allein", "Solo", "Häufig die Gitarre."],
       ["Kurze Überleitung zum Refrain", "Bridge", "Sie bringt etwas Neues."],
       ["Die Worte des Liedes", "Text", "Sie stehen im Booklet."],
       ["Die Tonfolge, die man mitsummt", "Melodie", "Sie bleibt am ehesten hängen."],
       ["Die Begleitung im Hintergrund", "Instrumentierung", "Sie trägt die Melodie."],
       ["Der Titel über allem", "Liedname", "Danach sucht man im Netz."]]'::jsonb,
     '[["Die Person, die das Lied singt", "Der Sänger ist kein Teil des Liedes."],
       ["Die Lautstärke im Refrain", "Danach fragt keine Zeile auf diesem Brett."]]'::jsonb),

    ('musik', 'leicht-schlager-charts', 'Charts & Erfolg',
     'Was bedeutet das?',
     'easy', 'Schlager', 'https://de.wikipedia.org/wiki/Schlager',
     '[["Charts", "Rangliste der meistgehörten Lieder", "Wöchentlich neu ermittelt."],
       ["Nummer eins", "Erfolgreichster Titel der Woche", "Das Ziel jedes Künstlers."],
       ["Goldene Schallplatte", "Auszeichnung für viele Verkäufe", "Die Grenze ist je Land verschieden."],
       ["Single", "Ein einzelnes Lied", "Früher eine kleine Schallplatte."],
       ["Album", "Sammlung vieler Lieder", "Meist zehn bis fünfzehn Stück."],
       ["Tournee", "Konzertreise durch viele Städte", "Monatelang unterwegs."],
       ["Zugabe", "Zusätzliches Lied am Ende", "Erst nach anhaltendem Applaus."],
       ["Fanclub", "Zusammenschluss von Anhängern", "Oft mit eigener Mitgliedskarte."],
       ["Autogramm", "Unterschrift des Künstlers", "Nach dem Konzert erbeten."],
       ["Coverversion", "Neuaufnahme eines fremden Liedes", "Der Urheber bekommt weiter Geld."]]'::jsonb,
     '[["Platin für sehr viele Verkäufe", "Es gibt sie, auf diesem Brett steht aber nur Gold."],
       ["Das Konzert in der Heimatstadt", "Es fehlt in dieser Liste."]]'::jsonb),

    ('musik', 'leicht-musik-schule', 'Musik in der Schule',
     'Was macht man dabei?',
     'easy', 'Musikunterricht',
     'https://de.wikipedia.org/wiki/Musikunterricht',
     '[["Blockflöte spielen", "Erstes Instrument lernen", "Es braucht keine Vorkenntnisse."],
       ["Im Chor singen", "Mehrstimmig zusammen singen", "Jede Gruppe hat ihre Stimme."],
       ["Noten lesen üben", "Zeichen in Töne übersetzen", "Wie eine zweite Schrift."],
       ["Rhythmus klatschen", "Den Takt fühlen", "Ohne Instrument möglich."],
       ["Musik hören und beschreiben", "Genau hinhören", "Laut, leise, schnell, langsam."],
       ["Ein Lied auswendig lernen", "Text und Melodie merken", "Am besten Strophe für Strophe."],
       ["Instrumente kennenlernen", "Klänge zuordnen", "Wer spielt hier gerade?"],
       ["Selbst eine Melodie erfinden", "Komponieren", "Auch mit wenigen Tönen möglich."],
       ["Vor der Klasse vorspielen", "Auftreten üben", "Lampenfieber gehört dazu."],
       ["Trommeln im Kreis", "Gemeinsam den Puls halten", "Alle hören aufeinander."]]'::jsonb,
     '[["Ein Instrument selbst bauen", "Das kommt auf diesem Brett nicht vor."],
       ["Ein Konzert besuchen", "Es steht nicht in dieser Liste."]]'::jsonb),

    ('musik', 'leicht-instrumente-zahl', 'Instrumente in Zahlen',
     'Wie viele sind es?',
     'easy', 'Musikinstrument',
     'https://de.wikipedia.org/wiki/Musikinstrument',
     '[["Musiker in einem Duo", "2", "Zwei, die zusammen auftreten."],
       ["Ventile einer Trompete", "3", "Damit sind alle Töne erreichbar."],
       ["Saiten einer Geige", "4", "Gestimmt in Quinten."],
       ["Linien im Notensystem", "5", "Auf und zwischen ihnen stehen die Noten."],
       ["Saiten einer normalen Gitarre", "6", "Von tief nach hoch E bis e."],
       ["Grifflöcher der Blockflöte vorn", "7", "Dazu eines hinten für den Daumen."],
       ["Töne einer Tonleiter bis zur Oktave", "8", "Von do bis do."],
       ["Finger beim Klavierspielen", "10", "Beide Hände zusammen."],
       ["Halbtöne in einer Oktave", "12", "Weiße und schwarze Tasten zusammen."],
       ["Saiten einer Konzertharfe", "47", "Dazu sieben Pedale."],
       ["Tasten eines Konzertflügels", "88", "Weiße und schwarze zusammen."]]'::jsonb,
     '[["9", "Keine Zahl auf diesem Brett meint das."],
       ["61", "So viele Tasten hat ein kleines Keyboard, und das fehlt hier."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

-- The answers that belong to no category. Numbered after the pairs so the two
-- sets never collide on `position`, though nothing reads it for a fake: the
-- pool is shuffled before a player sees it, and the review lists fakes on their
-- own rather than in board order.
fakes as (
    select q.id                                         as quiz_id,
           k.value ->> 0                                as label,
           k.value ->> 1                                as explanation,
           (jsonb_array_length(sp.pairs) + k.ord)::int  as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.fakes) with ordinality k(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
),

paired as (
    insert into items (quiz_id, category_id, label, position, explanation)
    select f.quiz_id, c.id, f.answer, f.position, f.explanation
      from flat f
      join new_categories c
        on c.quiz_id = f.quiz_id
       and c.label = f.label
    returning id
)

-- Same table, `category_id` left null. Both inserts run in the one statement,
-- so `items_quiz_id_label_key` still sees the pairs above: a fake written to
-- repeat an answer already on its own board fails the file rather than becoming
-- a second row nobody can tell apart.
insert into items (quiz_id, category_id, label, position, explanation)
select k.quiz_id, null, k.label, k.position, k.explanation
  from fakes k;
