-- Naturwissenschaft, leichte Fragen. Zwanzig Fragen, alle 'easy'.
--
-- Das Fach hatte bis hierher keine einzige leichte Frage. Der Zuschnitt ist
-- deshalb bewusst anders als in den anderen Dateien: gefragt wird, was man aus
-- dem Alltag kennt, nicht aus dem Unterricht.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs, fakes) as (
    values

    ('naturwissenschaft', 'leicht-tierkinder', 'Tierkinder',
     'Wie heißt das Junge dieses Tieres?',
     'easy', 'Juvenil', 'https://de.wikipedia.org/wiki/Juvenil',
     '[["Hund", "Welpe", "Kommt blind und taub zur Welt."],
       ["Katze", "Kätzchen", "Öffnet die Augen erst nach etwa einer Woche."],
       ["Kuh", "Kalb", "Steht schon nach wenigen Stunden."],
       ["Pferd", "Fohlen", "Kann am ersten Tag laufen."],
       ["Schaf", "Lamm", "Erkennt die Mutter an der Stimme."],
       ["Schwein", "Ferkel", "Ein Wurf hat oft zehn und mehr."],
       ["Huhn", "Küken", "Pickt sich selbst aus dem Ei."],
       ["Frosch", "Kaulquappe", "Hat zuerst einen Schwanz und keine Beine."],
       ["Reh", "Kitz", "Liegt die ersten Tage regungslos im Gras."],
       ["Ziege", "Zicklein", "Springt schon nach wenigen Tagen herum."],
       ["Gans", "Gössel", "Folgt dem ersten, das es sieht."],
       ["Hirsch", "Hirschkalb", "Trägt im ersten Jahr noch weiße Flecken."]]'::jsonb,
     '[["Fohlen im Beutel", "Ein Känguru-Junges heißt Joey, und das Tier fehlt hier."],
       ["Rehkitz-Zwilling", "Auf diesem Brett steht nur das Kitz selbst."]]'::jsonb),

    ('naturwissenschaft', 'leicht-tierlaute', 'Tierstimmen',
     'Welches Geräusch macht das Tier?',
     'easy', 'Haustier', 'https://de.wikipedia.org/wiki/Haustier',
     '[["Hund", "Bellen", "Wölfe bellen kaum, Hunde umso mehr."],
       ["Katze", "Miauen", "Erwachsene Katzen miauen fast nur mit Menschen."],
       ["Kuh", "Muhen", "Jede Kuh klingt ein wenig anders."],
       ["Pferd", "Wiehern", "Über weite Entfernungen hörbar."],
       ["Schaf", "Blöken", "Mutter und Lamm finden sich am Ruf."],
       ["Schwein", "Grunzen", "Ferkel quieken, ausgewachsene Tiere grunzen."],
       ["Ente", "Schnattern", "Weibchen sind lauter als Erpel."],
       ["Hahn", "Krähen", "Kräht nicht nur bei Sonnenaufgang."],
       ["Biene", "Summen", "Der Ton kommt von den Flügelschlägen."],
       ["Frosch", "Quaken", "Die Schallblase verstärkt den Ruf."],
       ["Löwe", "Brüllen", "Bis zu acht Kilometer weit zu hören."],
       ["Maus", "Piepsen", "Vieles davon liegt über unserer Hörgrenze."]]'::jsonb,
     '[["Zwitschern", "Der Singvogel wäre das Tier dazu, und der fehlt auf dem Brett."],
       ["Fauchen", "Kein Tier in dieser Liste ist dafür genannt."]]'::jsonb),

    ('naturwissenschaft', 'leicht-sinne', 'Die fünf Sinne',
     'Womit nimmt man das wahr?',
     'easy', 'Sinnesorgan', 'https://de.wikipedia.org/wiki/Sinnesorgan',
     '[["Sehen", "Auge", "Die Linse stellt scharf wie bei einer Kamera."],
       ["Hören", "Ohr", "Drei winzige Knöchelchen übertragen den Schall."],
       ["Riechen", "Nase", "Der Geruchssinn weckt besonders starke Erinnerungen."],
       ["Schmecken", "Zunge", "Süß, sauer, salzig, bitter und umami."],
       ["Tasten", "Haut", "Das größte Organ des Menschen."],
       ["Atmen", "Lunge", "Rund zwölfmal in der Minute in Ruhe."],
       ["Blut pumpen", "Herz", "Etwa hunderttausend Schläge am Tag."],
       ["Verdauen", "Magen", "Die Säure darin ist stark genug für Metall."],
       ["Denken", "Gehirn", "Verbraucht ein Fünftel unserer Energie."],
       ["Gleichgewicht halten", "Innenohr", "Drei Bogengänge messen jede Drehung."],
       ["Kauen", "Zähne", "Erwachsene haben davon zweiunddreißig."],
       ["Blut filtern", "Niere", "Zwei Stück, jede etwa faustgroß."]]'::jsonb,
     '[["Leber", "Sie entgiftet, danach fragt auf diesem Brett aber keine Zeile."],
       ["Darm", "Er nimmt Nährstoffe auf, und das steht hier nicht."]]'::jsonb),

    ('naturwissenschaft', 'leicht-planeten', 'Unser Sonnensystem',
     'Welcher Himmelskörper ist gemeint?',
     'easy', 'Sonne', 'https://de.wikipedia.org/wiki/Sonne',
     '[["Der sonnennächste Planet", "Merkur", "Am Tag glühend heiß, nachts eisig kalt."],
       ["Der rote Planet", "Mars", "Rostiger Staub gibt ihm die Farbe."],
       ["Der größte Planet", "Jupiter", "Alle anderen Planeten passen in ihn hinein."],
       ["Der Planet mit den Ringen", "Saturn", "Die Ringe bestehen aus Eisbrocken."],
       ["Unser Heimatplanet", "Erde", "Der einzige mit Ozeanen aus flüssigem Wasser."],
       ["Der äußerste Planet", "Neptun", "Von der Erde aus nur im Fernrohr zu sehen."],
       ["Der Stern in unserer Mitte", "Sonne", "Ihr Licht braucht acht Minuten zu uns."],
       ["Der Begleiter der Erde", "Mond", "Zeigt uns immer dieselbe Seite."],
       ["Ein Schweifstern aus Eis", "Komet", "Der Schweif entsteht erst nahe der Sonne."],
       ["Eine Sternschnuppe am Himmel", "Meteor", "Meist nur ein Staubkorn, das verglüht."]]'::jsonb,
     '[["Der zweite Planet von der Sonne", "Das ist die Venus, und die fehlt auf dem Brett."],
       ["Ein Zwergplanet weit draußen", "Pluto wäre das, und der steht nicht in dieser Liste."]]'::jsonb),

    ('naturwissenschaft', 'leicht-lebensraeume', 'Wo Tiere leben',
     'Wo lebt das Tier?',
     'easy', 'Tier', 'https://de.wikipedia.org/wiki/Tier',
     '[["Eisbär", "Arktis", "Unter dem weißen Fell ist die Haut schwarz."],
       ["Kamel", "Wüste", "Der Höcker speichert Fett, nicht Wasser."],
       ["Pinguin", "Antarktis", "Er fliegt nicht, aber er schwimmt hervorragend."],
       ["Maulwurf", "Unter der Erde", "Seine Schaufelhände graben ganze Gangsysteme."],
       ["Delfin", "Meer", "Er muss zum Atmen an die Oberfläche."],
       ["Affe", "Regenwald", "Viele Arten verlassen nie die Baumkronen."],
       ["Biber", "Fluss", "Er staut das Wasser mit Ästen."],
       ["Fledermaus", "Höhle", "Sie schläft kopfüber hängend."],
       ["Kuh", "Weide", "Sie kaut ihr Futter mehrfach wieder."],
       ["Adler", "Berge", "Er baut den Horst an steilen Felsen."],
       ["Känguru", "Steppe", "Es bewegt sich springend fort."],
       ["Regenwurm", "Gartenboden", "Er lockert die Erde beim Fressen."]]'::jsonb,
     '[["Korallenriff", "Kein Tier auf diesem Brett lebt dort."],
       ["Hochmoor", "Es kommt in dieser Liste nicht vor."]]'::jsonb),

    ('naturwissenschaft', 'leicht-farben-mischen', 'Farben mischen',
     'Welche Farbe entsteht?',
     'easy', 'Farbe', 'https://de.wikipedia.org/wiki/Farbe',
     '[["Blau und Gelb", "Grün", "Die klassische Mischung aus dem Malkasten."],
       ["Rot und Gelb", "Orange", "Die Frucht trägt denselben Namen."],
       ["Rot und Blau", "Violett", "Auch Lila genannt."],
       ["Rot und Weiß", "Rosa", "Je mehr Weiß, desto heller."],
       ["Schwarz und Weiß", "Grau", "Das Verhältnis bestimmt den Ton."],
       ["Gelb und ein wenig Schwarz", "Olivgrün", "Schwarz macht Gelb überraschend grün."],
       ["Blau und Weiß", "Hellblau", "Wie ein Himmel im Sommer."],
       ["Rot und Grün in der Farbe", "Braun", "Zwei Gegenfarben ergeben ein trübes Braun."],
       ["Alle Regenbogenfarben im Licht", "Weiß", "Beim Licht mischt sich alles zu Weiß."],
       ["Gar keine Farbe im Licht", "Schwarz", "Wo kein Licht ankommt, sehen wir Schwarz."]]'::jsonb,
     '[["Türkis", "Diese Farbe entsteht auf diesem Brett aus keiner Mischung."],
       ["Gold", "Es lässt sich gar nicht anmischen."]]'::jsonb),

    ('naturwissenschaft', 'leicht-koerper-zahlen', 'Der Körper in Zahlen',
     'Wie viele sind es beim Menschen?',
     'easy', 'Menschlicher Körper',
     'https://de.wikipedia.org/wiki/Menschlicher_K%C3%B6rper',
     '[["Finger an beiden Händen", "10", "Fünf an jeder Hand."],
       ["Zähne bei Erwachsenen", "32", "Mit den Weisheitszähnen gezählt."],
       ["Sinne im klassischen Sinn", "5", "Sehen, Hören, Riechen, Schmecken, Tasten."],
       ["Herzkammern", "4", "Zwei Vorhöfe und zwei Kammern."],
       ["Lungenflügel", "2", "Der linke ist kleiner, das Herz braucht Platz."],
       ["Knochen im Körper", "206", "Babys haben sogar mehr."],
       ["Rippenpaare", "12", "Die untersten enden frei."],
       ["Halswirbel", "7", "Die Giraffe hat ebenso viele."],
       ["Milchzähne bei Kindern", "20", "Sie fallen alle wieder aus."],
       ["Beine eines Insekts", "6", "Daran erkennt man jedes Insekt."]]'::jsonb,
     '[["1", "Danach fragt keine Zeile auf diesem Brett."],
       ["24", "So viele Rippen hat der Mensch insgesamt, gefragt sind hier die Paare."]]'::jsonb),

    ('naturwissenschaft', 'leicht-jahreszeiten', 'Jahreszeiten',
     'Zu welcher Jahreszeit gehört das?',
     'easy', 'Jahreszeit', 'https://de.wikipedia.org/wiki/Jahreszeit',
     '[["Bäume schlagen aus", "Frühling", "Die Tage werden schnell länger."],
       ["Längster Tag des Jahres", "Sommer", "Um den 21. Juni herum."],
       ["Bunte Blätter fallen", "Herbst", "Der Baum zieht das Blattgrün zurück."],
       ["Kürzester Tag des Jahres", "Winter", "Um den 21. Dezember herum."],
       ["Ernte auf den Feldern", "Spätsommer", "Getreide wird eingefahren."],
       ["Erster Frost am Morgen", "Spätherbst", "Reif überzieht die Wiesen."],
       ["Schneeglöckchen blühen", "Vorfrühling", "Die erste Blüte des Jahres."],
       ["Zugvögel kehren zurück", "Frühjahr", "Sie folgen dem wärmeren Wetter."],
       ["Tage und Nächte gleich lang", "Tagundnachtgleiche", "Zweimal im Jahr, im März und September."],
       ["Sonne geht nördlich nicht unter", "Polartag", "Nördlich des Polarkreises im Sommer."]]'::jsonb,
     '[["Die Uhren werden umgestellt", "Das gehört zu keiner Jahreszeit auf diesem Brett."],
       ["Regenzeit im Monsun", "Sie kommt in dieser Liste nicht vor."]]'::jsonb),

    ('naturwissenschaft', 'leicht-wasser', 'Wasser im Alltag',
     'Wie nennt man das?',
     'easy', 'Wasser', 'https://de.wikipedia.org/wiki/Wasser',
     '[["Wasser als Feststoff", "Eis", "Es schwimmt, weil es leichter ist als Wasser."],
       ["Wasser als Gas", "Wasserdampf", "Unsichtbar; die Wolke darüber ist schon wieder flüssig."],
       ["Gefrierpunkt von Wasser", "0 Grad", "Der Nullpunkt der Celsius-Skala."],
       ["Siedepunkt auf Meereshöhe", "100 Grad", "Auf dem Berg kocht es früher."],
       ["Wasser aus den Wolken", "Regen", "Tropfen werden zu schwer und fallen."],
       ["Gefrorener Regen", "Hagel", "Wächst im Aufwind eines Gewitters."],
       ["Wolke am Boden", "Nebel", "Sichtweite unter einem Kilometer."],
       ["Wasser auf dem Gras am Morgen", "Tau", "Die Luft kühlt ab und gibt Feuchtigkeit ab."],
       ["Salziges Wasser", "Meerwasser", "Rund fünfunddreißig Gramm Salz je Liter."],
       ["Wasser tief unter der Erde", "Grundwasser", "Daraus kommt unser Trinkwasser."]]'::jsonb,
     '[["Wasser mit Kohlensäure", "Sprudel steht nicht auf diesem Brett."],
       ["Wasser im Wasserhahn", "Das Leitungswasser fehlt in dieser Liste."]]'::jsonb),

    ('naturwissenschaft', 'leicht-obst-gemuese', 'Obst & Gemüse',
     'Was ist es?',
     'easy', 'Obst', 'https://de.wikipedia.org/wiki/Obst',
     '[["Wächst am Baum und ist rot oder grün", "Apfel", "Es gibt Tausende Sorten."],
       ["Gelb und krumm", "Banane", "Wächst an einer riesigen Staude, nicht am Baum."],
       ["Klein, rot und wächst am Boden", "Erdbeere", "Botanisch keine Beere."],
       ["Orange und lang, wächst in der Erde", "Karotte", "Kaninchen mögen auch das Grün."],
       ["Rund, rot und Grundlage von Ketchup", "Tomate", "Botanisch eine Beere."],
       ["Wird in der Erde geerntet und oft gebraten", "Kartoffel", "Kam erst spät nach Europa."],
       ["Sauer und gelb", "Zitrone", "Enthält viel Vitamin C."],
       ["Grün, lang und zu über neunzig Prozent Wasser", "Gurke", "Wird auch eingelegt gegessen."],
       ["Wächst als Kopf und wird zu Sauerkraut", "Weißkohl", "Milchsauer vergoren haltbar gemacht."],
       ["Klein, grün und in einer Hülse", "Erbse", "Mendel forschte an ihr."],
       ["Braune Schale, innen grün, mit Kernen", "Kiwi", "Trotz des Namens aus China."],
       ["Wächst am Strauch und färbt die Zunge blau", "Heidelbeere", "Auch Blaubeere genannt."]]'::jsonb,
     '[["Rund, orange und schwer, gut für Suppe", "Der Kürbis fehlt auf diesem Brett."],
       ["Grün und rund, mit vielen Blättern innen", "Der Kopfsalat steht nicht in dieser Liste."]]'::jsonb),

    ('naturwissenschaft', 'leicht-vogel-oder-nicht', 'Vögel & andere Tiere',
     'Um was für ein Tier handelt es sich?',
     'easy', 'Vogel', 'https://de.wikipedia.org/wiki/Vogel',
     '[["Fledermaus", "Säugetier", "Das einzige, das richtig fliegen kann."],
       ["Pinguin", "Vogel", "Federn hat er, fliegen kann er nicht."],
       ["Hai", "Fisch", "Sein Skelett besteht aus Knorpel."],
       ["Schildkröte", "Reptil", "Der Panzer gehört zum Skelett."],
       ["Frosch", "Amphibie", "Er lebt im Wasser und an Land."],
       ["Biene", "Insekt", "Sechs Beine und zwei Flügelpaare."],
       ["Spinne", "Spinnentier", "Acht Beine, kein Insekt."],
       ["Schnecke", "Weichtier", "Das Haus wächst mit ihr mit."],
       ["Krebs", "Krebstier", "Er wirft seinen Panzer beim Wachsen ab."],
       ["Regenwurm", "Ringelwurm", "Der Körper besteht aus vielen Ringen."],
       ["Seestern", "Stachelhäuter", "Er kann verlorene Arme nachbilden."]]'::jsonb,
     '[["Säugetier, das Eier legt", "Das Schnabeltier fehlt auf diesem Brett."],
       ["Quallentier", "Kein Tier in dieser Liste gehört dazu."]]'::jsonb),

    ('naturwissenschaft', 'leicht-wetter', 'Wetter',
     'Wie heißt diese Wettererscheinung?',
     'easy', 'Wetter', 'https://de.wikipedia.org/wiki/Wetter',
     '[["Buntes Band am Himmel nach dem Regen", "Regenbogen", "Immer der Sonne gegenüber."],
       ["Heller Blitzstrahl mit lautem Knall", "Gewitter", "Fünf Sekunden Abstand sind ein Kilometer."],
       ["Weiße Flocken im Winter", "Schnee", "Jede Flocke ist sechseckig."],
       ["Starker Wind mit hoher Geschwindigkeit", "Sturm", "Ab Windstärke neun."],
       ["Lange Zeit ohne Regen", "Dürre", "Böden reißen auf, Flüsse fallen trocken."],
       ["Wasserdampf, der als Wolke am Boden liegt", "Nebel", "Autofahrer müssen langsamer fahren."],
       ["Eiskörner aus der Gewitterwolke", "Hagel", "Kann Autos und Ernten beschädigen."],
       ["Wirbelnder Schlauch bis zum Boden", "Tornado", "Windgeschwindigkeiten über 400 km/h möglich."],
       ["Feiner, lang anhaltender Regen", "Nieselregen", "Sehr kleine Tropfen."],
       ["Wolkenloser blauer Himmel", "Sonnenschein", "Hochdruckgebiete bringen ihn."]]'::jsonb,
     '[["Warmer Fallwind über die Berge", "Der Föhn steht nicht auf diesem Brett."],
       ["Glatte Straße durch gefrorenen Regen", "Das Glatteis fehlt in dieser Liste."]]'::jsonb),

    ('naturwissenschaft', 'leicht-baeume', 'Bäume erkennen',
     'Zu welchem Baum gehört das?',
     'easy', 'Baum', 'https://de.wikipedia.org/wiki/Baum',
     '[["Eichel", "Eiche", "Wildschweine und Eichhörnchen fressen sie."],
       ["Kastanie in stacheliger Hülle", "Rosskastanie", "Beliebt zum Basteln im Herbst."],
       ["Weiße Rinde, die sich abschält", "Birke", "Auffällig hell im Wald."],
       ["Nadeln und hängende Zapfen", "Fichte", "Der klassische Weihnachtsbaum ist meist eine andere Art."],
       ["Flügelfrüchte, die sich drehen", "Ahorn", "Kinder nennen sie Nasenzwicker."],
       ["Bucheckern als Frucht", "Buche", "Glatte, graue Rinde."],
       ["Nadeln, die im Herbst abfallen", "Lärche", "Der einzige heimische Nadelbaum, der kahl wird."],
       ["Kätzchen im zeitigen Frühjahr", "Weide", "Blüht, bevor die Blätter kommen."],
       ["Herzförmige Blätter und Duft im Juni", "Linde", "Bienen lieben ihre Blüten."],
       ["Rote Beeren, aber giftig", "Eibe", "Nur der rote Mantel ist ungiftig."],
       ["Süße Früchte am Steinobstbaum", "Kirsche", "Blüht im Frühling weiß."],
       ["Zapfen und lange Nadeln zu zweit", "Kiefer", "Wächst auch auf sandigem Boden."]]'::jsonb,
     '[["Bittere Nüsse in grüner Schale", "Der Walnussbaum fehlt auf diesem Brett."],
       ["Blätter wie eine Hand mit fünf Fingern", "Kein Baum in dieser Liste ist so beschrieben."]]'::jsonb),

    ('naturwissenschaft', 'leicht-magnet-strom', 'Strom & Magnet',
     'Was passiert hier?',
     'easy', 'Elektrizität', 'https://de.wikipedia.org/wiki/Elektrizit%C3%A4t',
     '[["Zwei gleiche Magnetpole", "Sie stoßen sich ab", "Nord und Nord mögen sich nicht."],
       ["Nord- und Südpol eines Magneten", "Sie ziehen sich an", "Deshalb klebt der Magnet am Kühlschrank."],
       ["Kompassnadel in Ruhe", "Zeigt nach Norden", "Die Erde selbst ist ein Magnet."],
       ["Stromkreis ist unterbrochen", "Nichts leuchtet", "Der Strom braucht einen geschlossenen Weg."],
       ["Metalllöffel in heißer Suppe", "Wird warm", "Metall leitet Wärme gut."],
       ["Holzlöffel in heißer Suppe", "Bleibt kühl", "Holz leitet Wärme schlecht."],
       ["Blitz am Himmel", "Elektrische Entladung", "Spannungen von Millionen Volt."],
       ["Wollpullover über den Kopf gezogen", "Haare stehen ab", "Statische Aufladung."],
       ["Batterie falsch herum eingelegt", "Gerät bleibt aus", "Plus und Minus müssen stimmen."],
       ["Glühbirne nach langer Brenndauer", "Wird sehr heiß", "Der größte Teil des Stroms wird Wärme."]]'::jsonb,
     '[["Wasser leitet gar keinen Strom", "Das stimmt nicht, und auf dem Brett steht es auch nicht."],
       ["Ein Magnet zieht Holz an", "Magnete wirken nicht auf Holz."]]'::jsonb),

    ('naturwissenschaft', 'leicht-blumen', 'Blumen',
     'Welche Blume ist gemeint?',
     'easy', 'Blume', 'https://de.wikipedia.org/wiki/Blume',
     '[["Dreht sich nach der Sonne", "Sonnenblume", "Der Kopf besteht aus Hunderten Einzelblüten."],
       ["Klassische Blume zum Valentinstag", "Rose", "Die Dornen sind eigentlich Stacheln."],
       ["Wächst aus einer Zwiebel, Symbol der Niederlande", "Tulpe", "Löste im 17. Jahrhundert eine Spekulationsblase aus."],
       ["Weiß mit gelber Mitte, im Rasen", "Gänseblümchen", "Schließt sich bei Regen."],
       ["Gelb, dann eine Pusteblume", "Löwenzahn", "Die Samen fliegen mit dem Wind."],
       ["Blau und wächst im Kornfeld", "Kornblume", "Früher häufiges Ackerkraut."],
       ["Erste Blüte im Jahr, weiß und nickend", "Schneeglöckchen", "Blüht oft noch im Schnee."],
       ["Duftet stark und wächst in der Provence", "Lavendel", "Sein Öl gilt als beruhigend."],
       ["Wasserpflanze mit großen Blättern", "Seerose", "Die Blätter tragen kleine Tiere."],
       ["Rot und steht für den Klatschmohn", "Mohnblume", "Die Blüte hält nur wenige Tage."],
       ["Wächst in den Alpen und steht unter Schutz", "Edelweiß", "Der weiße Filz schützt vor Kälte."],
       ["Blüht im Advent in vielen Wohnzimmern", "Weihnachtsstern", "Die roten Teile sind Blätter, keine Blüten."]]'::jsonb,
     '[["Blüht als Strauch und duftet im Mai", "Der Flieder fehlt auf diesem Brett."],
       ["Wächst als Zwiebel und blüht gelb im März", "Die Narzisse steht nicht in dieser Liste."]]'::jsonb),

    ('naturwissenschaft', 'leicht-insekten', 'Kleine Tiere',
     'Welches Tier ist das?',
     'easy', 'Insekten', 'https://de.wikipedia.org/wiki/Insekten',
     '[["Sammelt Nektar und macht Honig", "Biene", "Ein Volk zählt Zehntausende Tiere."],
       ["Schwarz-gelb und sticht mehrfach", "Wespe", "Sie verliert den Stachel nicht."],
       ["Rot mit schwarzen Punkten", "Marienkäfer", "Frisst Blattläuse."],
       ["Zirpt an warmen Sommerabenden", "Grille", "Der Ton entsteht durch Reiben der Flügel."],
       ["Baut ein Netz aus Fäden", "Spinne", "Kein Insekt, sondern ein Spinnentier."],
       ["Trägt Lasten, die schwerer sind als es selbst", "Ameise", "Lebt in großen Staaten."],
       ["Aus der Raupe wird sie schön", "Schmetterling", "Die Verwandlung geschieht in der Puppe."],
       ["Sticht und überträgt Krankheiten", "Stechmücke", "Nur die Weibchen stechen."],
       ["Leuchtet nachts im Gras", "Glühwürmchen", "Das Licht entsteht ohne Wärme."],
       ["Rollt Mist zu einer Kugel", "Mistkäfer", "Räumt die Weiden auf."],
       ["Springt weit und war eine Plage", "Heuschrecke", "Schwärme können Felder kahl fressen."],
       ["Lebt im Holz und nagt Gänge", "Holzwurm", "Eigentlich die Larve eines Käfers."]]'::jsonb,
     '[["Frisst Blattläuse als Larve", "Das tut der Marienkäfer, gefragt ist dort sein Aussehen."],
       ["Läuft über Wasser, ohne einzusinken", "Der Wasserläufer fehlt auf diesem Brett."]]'::jsonb),

    ('naturwissenschaft', 'leicht-koerperpflege', 'Gesundheit im Alltag',
     'Warum macht man das?',
     'easy', 'Gesundheit', 'https://de.wikipedia.org/wiki/Gesundheit',
     '[["Zähne putzen", "Gegen Karies", "Bakterien machen aus Zucker Säure."],
       ["Hände waschen", "Gegen Krankheitserreger", "Zwanzig Sekunden mit Seife."],
       ["Sonnencreme auftragen", "Gegen Sonnenbrand", "UV-Strahlen schädigen die Haut."],
       ["Ausreichend trinken", "Gegen Austrocknung", "Etwa anderthalb Liter am Tag."],
       ["Sport treiben", "Für Herz und Kreislauf", "Schon Spazierengehen hilft."],
       ["Genug schlafen", "Zur Erholung", "Im Schlaf sortiert das Gehirn Erlerntes."],
       ["Obst und Gemüse essen", "Für Vitamine", "Fünf Portionen am Tag gelten als Ziel."],
       ["Fahrradhelm tragen", "Zum Schutz des Kopfes", "Er verteilt die Wucht eines Aufpralls."],
       ["Impfen lassen", "Zum Schutz vor Infektionen", "Der Körper übt an einem harmlosen Reiz."],
       ["Lüften im Winter", "Für frische Luft", "Stoßlüften kostet wenig Wärme."]]'::jsonb,
     '[["Gegen Langeweile", "Das ist kein Grund für etwas auf diesem Brett."],
       ["Für schönere Kleidung", "Danach fragt hier keine Zeile."]]'::jsonb),

    ('naturwissenschaft', 'leicht-himmel', 'Am Himmel',
     'Was sieht man da?',
     'easy', 'Mond', 'https://de.wikipedia.org/wiki/Mond',
     '[["Der Mond ist ganz rund", "Vollmond", "Etwa alle 29 Tage."],
       ["Der Mond ist nicht zu sehen", "Neumond", "Er steht zwischen Erde und Sonne."],
       ["Die Erde schiebt sich vor den Mond", "Mondfinsternis", "Der Mond färbt sich rötlich."],
       ["Der Mond schiebt sich vor die Sonne", "Sonnenfinsternis", "Nur in einem schmalen Streifen total."],
       ["Ein heller Streifen am Nachthimmel", "Milchstraße", "Der Blick in unsere eigene Galaxie."],
       ["Sieben helle Sterne als Wagen", "Großer Wagen", "Teil des Sternbilds Großer Bär."],
       ["Der Stern, der immer im Norden steht", "Polarstern", "Er zeigt Wanderern die Richtung."],
       ["Bunte Lichter am Polarhimmel", "Polarlicht", "Teilchen der Sonne treffen die Luft."],
       ["Ein künstlicher Punkt, der stetig zieht", "Satellit", "Er blinkt nicht wie ein Flugzeug."],
       ["Die Sonne verschwindet am Abend", "Sonnenuntergang", "Nicht die Sonne wandert, sondern die Erde dreht sich."]]'::jsonb,
     '[["Der Mond ist halb zu sehen", "Der Halbmond fehlt auf diesem Brett."],
       ["Ein Regenbogen bei Nacht", "Er kommt in dieser Liste nicht vor."]]'::jsonb),

    ('naturwissenschaft', 'leicht-stoffe', 'Stoffe im Haushalt',
     'Was trifft zu?',
     'easy', 'Wasser', 'https://de.wikipedia.org/wiki/Wasser',
     '[["Zucker im Tee", "Löst sich auf", "Er verschwindet nicht, er verteilt sich."],
       ["Öl im Wasserglas", "Schwimmt oben", "Öl ist leichter als Wasser."],
       ["Salz auf vereister Straße", "Lässt das Eis schmelzen", "Salzwasser gefriert erst später."],
       ["Backpulver im Teig", "Bildet Gasbläschen", "Der Kuchen geht dadurch auf."],
       ["Eisen an feuchter Luft", "Rostet", "Sauerstoff und Wasser zusammen."],
       ["Butter in der Pfanne", "Schmilzt", "Fest wird flüssig durch Wärme."],
       ["Luftballon in der Kälte", "Wird kleiner", "Kalte Luft braucht weniger Platz."],
       ["Brausetablette im Wasser", "Sprudelt", "Es entsteht Kohlendioxid."],
       ["Kerze unter einem Glas", "Geht aus", "Ohne Sauerstoff kein Feuer."],
       ["Apfel an der Luft aufgeschnitten", "Wird braun", "Zitronensaft bremst das."]]'::jsonb,
     '[["Sand im Wasserglas", "Er sinkt zu Boden, steht aber nicht auf diesem Brett."],
       ["Milch in heißem Kaffee", "Sie mischt sich, und das fehlt in dieser Liste."]]'::jsonb),

    ('naturwissenschaft', 'leicht-saeugetiere', 'Säugetiere',
     'Welches Tier ist gesucht?',
     'easy', 'Säugetiere', 'https://de.wikipedia.org/wiki/S%C3%A4ugetiere',
     '[["Größtes Tier der Erde", "Blauwal", "Sein Herz ist so groß wie ein Kleinwagen."],
       ["Größtes Landtier", "Elefant", "Die Ohren dienen der Kühlung."],
       ["Höchstes Tier", "Giraffe", "Sieben Halswirbel wie beim Menschen."],
       ["Schnellstes Landtier", "Gepard", "Nur über kurze Strecken."],
       ["Bekannt für seinen Winterschlaf", "Igel", "Er rollt sich zur Kugel zusammen."],
       ["Trägt sein Junges im Beutel", "Känguru", "Das Junge ist bei der Geburt winzig."],
       ["Lebt im Wasser und ist sehr klug", "Delfin", "Er verständigt sich mit Pfiffen."],
       ["Bekannt für Stacheln auf dem Rücken", "Stachelschwein", "Die Stacheln lösen sich leicht."],
       ["Hängt kopfüber und schläft am Tag", "Fledermaus", "Sie orientiert sich mit Ultraschall."],
       ["Frisst fast nur Bambus", "Großer Panda", "Er ist eigentlich ein Raubtier."],
       ["Trägt ein Horn auf der Nase", "Nashorn", "Das Horn besteht aus Keratin."],
       ["Lebt in Rudeln und heult den Mond an", "Wolf", "Stammvater aller Haushunde."]]'::jsonb,
     '[["Trägt einen Panzer aus Hornplatten", "Das Gürteltier fehlt auf diesem Brett."],
       ["Hat den längsten Winterschlaf im Wald", "Der Siebenschläfer steht nicht in dieser Liste."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

-- The answers that belong to no category. Numbered after the pairs so the two
-- sets never collide on `position`, though nothing reads it for a fake: the
-- pool is shuffled before a player sees it, and the review lists fakes on their
-- own rather than in board order.
fakes as (
    select q.id                                         as quiz_id,
           k.value ->> 0                                as label,
           k.value ->> 1                                as explanation,
           (jsonb_array_length(sp.pairs) + k.ord)::int  as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.fakes) with ordinality k(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
),

paired as (
    insert into items (quiz_id, category_id, label, position, explanation)
    select f.quiz_id, c.id, f.answer, f.position, f.explanation
      from flat f
      join new_categories c
        on c.quiz_id = f.quiz_id
       and c.label = f.label
    returning id
)

-- Same table, `category_id` left null. Both inserts run in the one statement,
-- so `items_quiz_id_label_key` still sees the pairs above: a fake written to
-- repeat an answer already on its own board fails the file rather than becoming
-- a second row nobody can tell apart.
insert into items (quiz_id, category_id, label, position, explanation)
select k.quiz_id, null, k.label, k.position, k.explanation
  from fakes k;
