-- Naturwissenschaft, file 2 of 2. Twenty questions, medium and hard.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs) as (
    values

    ('naturwissenschaft', 'tierklassen-merkmale', 'Tiergruppen & Merkmale',
     'Woran ist die Tiergruppe zu erkennen?',
     'medium', 'Tier', 'https://de.wikipedia.org/wiki/Tier',
     '[["Säugetiere", "Milchdrüsen", "Sie säugen ihre Jungen, auch die eierlegenden."],
       ["Vögel", "Federn", "Kein anderes heutiges Tier hat sie."],
       ["Reptilien", "Hornschuppen", "Trockene Haut, die vor Austrocknung schützt."],
       ["Amphibien", "Verwandlung im Wasser", "Aus Kiemenatmern werden Lungenatmer."],
       ["Fische", "Kiemen", "Sie nehmen den im Wasser gelösten Sauerstoff auf."],
       ["Insekten", "Sechs Beine", "Der Körper besteht aus Kopf, Brust und Hinterleib."],
       ["Spinnentiere", "Acht Beine", "Keine Fühler und keine Flügel."],
       ["Krebstiere", "Zwei Fühlerpaare", "Meist mit Kalkpanzer, der bei der Häutung abgeworfen wird."],
       ["Weichtiere", "Mantel und Schale", "Schnecken, Muscheln und Tintenfische gehören dazu."],
       ["Stachelhäuter", "Fünfstrahliger Bau", "Seesterne und Seeigel sind fünfteilig gegliedert."],
       ["Nesseltiere", "Nesselzellen", "Quallen und Korallen lähmen damit ihre Beute."],
       ["Ringelwürmer", "Gegliederte Segmente", "Der Körper besteht aus fast gleichen Ringen."]]'::jsonb),

    ('naturwissenschaft', 'pflanzenteile-funktionen', 'Pflanzenteile & ihre Aufgaben',
     'Wozu dient dieser Teil der Pflanze?',
     'medium', 'Pflanze', 'https://de.wikipedia.org/wiki/Pflanze',
     '[["Wurzel", "Aufnahme von Wasser", "Sie verankert die Pflanze und zieht Nährsalze aus dem Boden."],
       ["Blatt", "Fotosynthese", "Hier wird aus Licht, Wasser und Kohlendioxid Zucker."],
       ["Blüte", "Fortpflanzung", "Lockt Bestäuber an und bildet Samen aus."],
       ["Frucht", "Verbreitung der Samen", "Oft süß, damit Tiere sie fressen und die Samen weitertragen."],
       ["Sprossachse", "Transport nach oben", "Leitet Wasser und Nährstoffe zwischen Wurzel und Blatt."],
       ["Rinde", "Schutz des Stammes", "Hält Verdunstung, Frost und Schädlinge ab."],
       ["Kambium", "Dickenwachstum", "Diese Zellschicht bildet die Jahresringe."],
       ["Spaltöffnung", "Gasaustausch", "Kleine Poren, die sich bei Trockenheit schließen."],
       ["Chloroplast", "Ort des Blattgrüns", "Enthält das Chlorophyll, das Licht einfängt."],
       ["Knolle", "Speicher für Stärke", "Erlaubt das Überdauern im Boden, etwa bei der Kartoffel."]]'::jsonb),

    ('naturwissenschaft', 'wetterphaenomene', 'Wetterphänomene & Ursachen',
     'Wie entsteht das Phänomen?',
     'hard', 'Wetter', 'https://de.wikipedia.org/wiki/Wetter',
     '[["Regenbogen", "Brechung in Wassertropfen", "Jeder Tropfen zerlegt das Sonnenlicht in seine Farben."],
       ["Blitz", "Ladungsausgleich", "Spannung zwischen Wolke und Boden entlädt sich schlagartig."],
       ["Föhn", "Trockenwarmer Fallwind", "Luft regnet sich am Berg ab und erwärmt sich beim Absinken."],
       ["Nebel", "Kondensation am Boden", "Wolke, die den Erdboden berührt."],
       ["Hagel", "Aufwind im Gewitter", "Körner wachsen, solange der Wind sie oben hält."],
       ["Polarlicht", "Sonnenwind trifft Atmosphäre", "Geladene Teilchen bringen Gasteilchen zum Leuchten."],
       ["Fata Morgana", "Lichtbrechung über heißer Luft", "Der Himmel spiegelt sich und wirkt wie Wasser."],
       ["Raureif", "Dampf gefriert unmittelbar", "Ohne den flüssigen Zwischenschritt."],
       ["Halo", "Eiskristalle in hohen Wolken", "Der Lichtring um Sonne oder Mond."],
       ["Monsun", "Jahreszeitlicher Windwechsel", "Land und Meer erwärmen sich unterschiedlich schnell."],
       ["El Niño", "Erwärmung des Pazifiks", "Verschiebt Regen- und Dürregebiete weltweit."],
       ["Tornado", "Rotierender Aufwind", "Ein Wirbel reicht von der Gewitterwolke bis zum Boden."]]'::jsonb),

    ('naturwissenschaft', 'zellorganellen', 'Zellbestandteile & ihre Aufgaben',
     'Was tut dieser Teil der Zelle?',
     'hard', 'Zelle (Biologie)',
     'https://de.wikipedia.org/wiki/Zelle_%28Biologie%29',
     '[["Zellkern", "Verwahrt die Erbinformation", "Enthält die Chromosomen, abgetrennt durch eine Hülle."],
       ["Mitochondrium", "Kraftwerk der Zelle", "Gewinnt Energie aus Zucker und Sauerstoff."],
       ["Chloroplast", "Betreibt Fotosynthese", "Nur in Pflanzenzellen, mit eigenem Erbgut."],
       ["Golgi-Apparat", "Verpackt und versendet", "Bereitet Proteine für den Export auf."],
       ["Lysosom", "Verdaut Abfall", "Enthält Enzyme, die Zellbestandteile abbauen."],
       ["Endoplasmatisches Retikulum", "Kanalsystem für Stoffe", "Mit Ribosomen besetzt oder glatt."],
       ["Zellmembran", "Grenzt die Zelle ab", "Lässt gezielt Stoffe hinein und hinaus."],
       ["Zellwand", "Gibt Pflanzenzellen Halt", "Aus Cellulose, außerhalb der Membran."],
       ["Vakuole", "Speichert Wasser", "Ihr Innendruck hält Pflanzen aufrecht."],
       ["Zellskelett", "Formgebendes Fasergerüst", "Netz aus Fasern, an dem Transporte entlanglaufen."]]'::jsonb),

    ('naturwissenschaft', 'krankheiten-organe', 'Krankheiten & betroffene Organe',
     'Welches Organ ist betroffen?',
     'medium', 'Krankheit', 'https://de.wikipedia.org/wiki/Krankheit',
     '[["Hepatitis", "Leber", "Entzündung, ausgelöst durch Viren, Alkohol oder Medikamente."],
       ["Nephritis", "Niere", "Entzündung, die die Filterleistung beeinträchtigt."],
       ["Gastritis", "Magen", "Die Schleimhaut entzündet sich, oft durch ein Bakterium."],
       ["Arthritis", "Gelenk", "Schmerzhafte Entzündung mit Schwellung."],
       ["Meningitis", "Hirnhaut", "Kann bakteriell binnen Stunden lebensbedrohlich werden."],
       ["Karies", "Zahn", "Säuren von Bakterien lösen den Zahnschmelz auf."],
       ["Grauer Star", "Augenlinse", "Die Linse trübt ein und wird ersetzt."],
       ["Asthma", "Bronchien", "Die Atemwege verengen sich anfallsartig."],
       ["Angina Pectoris", "Herzkranzgefäße", "Verengte Gefäße lassen den Herzmuskel unterversorgt."],
       ["Osteoporose", "Knochen", "Die Dichte nimmt ab, schon kleine Stürze brechen."],
       ["Otitis media", "Mittelohr", "Häufig bei Kindern, oft nach einer Erkältung."],
       ["Neurodermitis", "Haut", "Chronisch entzündliche, stark juckende Hauterkrankung."]]'::jsonb),

    ('naturwissenschaft', 'formelzeichen', 'Größen & Formelzeichen',
     'Welches Zeichen steht für die Größe?',
     'hard', 'Physikalische Größe',
     'https://de.wikipedia.org/wiki/Physikalische_Gr%C3%B6%C3%9Fe',
     '[["Geschwindigkeit", "v", "Vom lateinischen velocitas."],
       ["Beschleunigung", "a", "Vom lateinischen acceleratio."],
       ["Kraft", "F", "Vom englischen force."],
       ["Masse", "m", "Nicht zu verwechseln mit dem Meter als Einheit."],
       ["Energie", "E", "Auch für die elektrische Feldstärke gebräuchlich."],
       ["Leistung", "P", "Vom englischen power."],
       ["Zeit", "t", "Vom lateinischen tempus."],
       ["Elektrische Stromstärke", "I", "Von der französischen intensité du courant."],
       ["Elektrische Spannung", "U", "Von der lateinischen Bezeichnung urgere, drängen."],
       ["Elektrischer Widerstand", "R", "Vom englischen resistance."],
       ["Wellenlänge", "λ", "Griechisches Lambda."],
       ["Dichte", "ρ", "Griechisches Rho."]]'::jsonb),

    ('naturwissenschaft', 'astronomie-begriffe', 'Begriffe der Astronomie',
     'Was bezeichnet der Begriff?',
     'hard', 'Astronomie', 'https://de.wikipedia.org/wiki/Astronomie',
     '[["Supernova", "Explodierender Stern", "Kann heller leuchten als seine ganze Galaxie."],
       ["Roter Riese", "Aufgeblähter alter Stern", "Die Sonne wird in Milliarden Jahren einer."],
       ["Weißer Zwerg", "Ausgeglühter Sternkern", "So dicht, dass ein Löffel Tonnen wöge."],
       ["Neutronenstern", "Rest nach einer Explosion", "Ein Sonnengewicht in einer Kugel von 20 Kilometern."],
       ["Schwarzes Loch", "Nicht einmal Licht entkommt", "Die Fluchtgeschwindigkeit übersteigt die des Lichts."],
       ["Quasar", "Leuchtender Galaxienkern", "Materie strahlt beim Sturz ins zentrale Schwarze Loch."],
       ["Komet", "Schweifstern aus Eis", "Nahe der Sonne verdampft er und bildet den Schweif."],
       ["Meteorit", "Gelandeter Gesteinsbrocken", "In der Luft leuchtet er noch als Meteor."],
       ["Asteroid", "Kleinkörper zwischen Planeten", "Die meisten kreisen zwischen Mars und Jupiter."],
       ["Lichtjahr", "Entfernungsmaß", "Die Strecke, die Licht in einem Jahr zurücklegt."],
       ["Parallaxe", "Scheinbare Verschiebung", "Aus ihr lässt sich die Entfernung naher Sterne berechnen."],
       ["Rotverschiebung", "Zeichen der Entfernung", "Licht ferner Galaxien erscheint langwelliger."]]'::jsonb),

    ('naturwissenschaft', 'blut-kreislauf', 'Blut & Kreislauf',
     'Welche Aufgabe hat dieser Bestandteil?',
     'medium', 'Blut', 'https://de.wikipedia.org/wiki/Blut',
     '[["Rote Blutkörperchen", "Sauerstofftransport", "Sie enthalten den roten Blutfarbstoff."],
       ["Weiße Blutkörperchen", "Abwehr von Erregern", "Sie erkennen und vernichten Eindringlinge."],
       ["Blutplättchen", "Blutgerinnung", "Sie verkleben die Wunde und stoppen die Blutung."],
       ["Blutplasma", "Flüssiger Anteil", "Zu über 90 Prozent Wasser, mit gelösten Stoffen."],
       ["Hämoglobin", "Bindet den Sauerstoff", "Das Eisen darin macht das Blut rot."],
       ["Arterie", "Führt vom Herzen weg", "Dicke Wände halten dem Druck stand."],
       ["Vene", "Führt zum Herzen hin", "Klappen verhindern das Zurückfließen."],
       ["Kapillare", "Stoffaustausch im Gewebe", "So dünn, dass Blutkörperchen einzeln passieren."],
       ["Herzvorhof", "Sammelt ankommendes Blut", "Gibt es an die Kammer weiter."],
       ["Herzkammer", "Pumpt das Blut hinaus", "Die linke muss den ganzen Körper versorgen."],
       ["Lymphe", "Gewebsflüssigkeit", "Transportiert Fette und Abwehrzellen."],
       ["Milz", "Filtert alte Blutzellen", "Baut ausgediente rote Blutkörperchen ab."]]'::jsonb),

    ('naturwissenschaft', 'saeuren-vorkommen', 'Säuren & ihr Vorkommen',
     'Worin steckt diese Säure?',
     'medium', 'Säuren', 'https://de.wikipedia.org/wiki/S%C3%A4uren',
     '[["Zitronensäure", "Zitrusfrüchte", "Auch als Entkalker im Haushalt."],
       ["Milchsäure", "Sauermilch", "Entsteht, wenn Bakterien Milchzucker vergären."],
       ["Ameisensäure", "Ameisen", "Wird zur Verteidigung versprüht."],
       ["Oxalsäure", "Rhabarber", "Deshalb sind große Mengen roher Blätter gefährlich."],
       ["Salzsäure", "Magensaft", "Tötet Keime und hilft, Eiweiß zu spalten."],
       ["Kohlensäure", "Sprudelwasser", "Entsteht, wenn Kohlendioxid sich im Wasser löst."],
       ["Gerbsäure", "Eichenrinde", "Wurde früher zum Gerben von Leder genutzt."],
       ["Weinsäure", "Weintrauben", "Setzt sich im Fass als Weinstein ab."],
       ["Apfelsäure", "Unreife Äpfel", "Sorgt für den herben Geschmack."],
       ["Blausäure", "Bittermandeln", "Schon in kleinen Mengen sehr giftig."],
       ["Phosphorsäure", "Cola", "Gibt dem Getränk den säuerlichen Geschmack."],
       ["Buttersäure", "Ranzige Butter", "Riecht schon in kleinsten Mengen unangenehm."]]'::jsonb),

    ('naturwissenschaft', 'erneuerbare-energien', 'Erneuerbare Energien',
     'Woraus gewinnt die Anlage ihre Energie?',
     'medium', 'Erneuerbare Energien',
     'https://de.wikipedia.org/wiki/Erneuerbare_Energien',
     '[["Photovoltaik", "Sonnenlicht", "Halbleiter erzeugen aus Licht direkt Strom."],
       ["Solarthermie", "Sonnenwärme", "Kollektoren erhitzen Wasser statt Strom zu erzeugen."],
       ["Windkraftanlage", "Bewegte Luft", "Der Rotor entzieht dem Wind einen Teil seiner Energie."],
       ["Laufwasserkraftwerk", "Fließendes Wasser", "Turbinen nutzen den stetigen Strom des Flusses."],
       ["Pumpspeicherwerk", "Höhenunterschied", "Speichert Strom, indem es Wasser bergauf pumpt."],
       ["Gezeitenkraftwerk", "Tidenhub", "Nutzt den Wechsel von Ebbe und Flut."],
       ["Wellenkraftwerk", "Seegang", "Wandelt die Auf- und Abbewegung der Wellen um."],
       ["Geothermiekraftwerk", "Erdwärme", "Heißes Tiefenwasser treibt eine Turbine an."],
       ["Biogasanlage", "Vergorene Biomasse", "Bakterien erzeugen aus Gülle und Mais Methan."],
       ["Wärmepumpe", "Wärme der Umgebung", "Hebt niedrige Temperaturen auf Heizniveau."]]'::jsonb),

    ('naturwissenschaft', 'meeresstroemungen', 'Meeresströmungen & Küsten',
     'An welcher Küste wirkt die Strömung?',
     'hard', 'Meeresströmung',
     'https://de.wikipedia.org/wiki/Meeresstr%C3%B6mung',
     '[["Golfstrom", "Westeuropa", "Ihm verdankt Nordwesteuropa seine milden Winter."],
       ["Humboldtstrom", "Peru und Chile", "Kaltes Auftriebswasser macht das Meer fischreich."],
       ["Kuroshio", "Japan", "Warme Strömung entlang der Ostküste."],
       ["Benguelastrom", "Namibia", "Kaltes Wasser erzeugt die Nebel der Küstenwüste."],
       ["Agulhasstrom", "Südostafrika", "Warme Strömung, berüchtigt für hohe Kreuzseen."],
       ["Kanarenstrom", "Nordwestafrika", "Kühlt die Küste der Sahara ab."],
       ["Labradorstrom", "Neufundland", "Bringt Eisberge nach Süden in die Schifffahrtsrouten."],
       ["Ostaustralstrom", "Ostaustralien", "Transportiert warmes Korallenmeerwasser nach Süden."],
       ["Nordatlantikstrom", "Norwegen", "Hält Häfen bis zum Polarkreis eisfrei."],
       ["Somalistrom", "Ostafrika", "Kehrt mit dem Monsun die Richtung um."]]'::jsonb),

    ('naturwissenschaft', 'ordnungszahlen', 'Elemente & Ordnungszahlen',
     'Welche Ordnungszahl hat das Element?',
     'hard', 'Periodensystem', 'https://de.wikipedia.org/wiki/Periodensystem',
     '[["Wasserstoff", "1", "Leichtestes Element, ein einziges Proton."],
       ["Helium", "2", "Im Universum das zweithäufigste Element."],
       ["Kohlenstoff", "6", "Grundlage aller organischen Verbindungen."],
       ["Stickstoff", "7", "Macht 78 Prozent der Luft aus."],
       ["Sauerstoff", "8", "Häufigstes Element der Erdkruste."],
       ["Natrium", "11", "Reagiert mit Wasser heftig."],
       ["Calcium", "20", "Baustoff von Knochen und Zähnen."],
       ["Eisen", "26", "Der Erdkern besteht überwiegend daraus."],
       ["Silber", "47", "Bester elektrischer Leiter aller Metalle."],
       ["Gold", "79", "Reagiert kaum, deshalb bleibt es glänzend."],
       ["Blei", "82", "Schwerstes stabiles Element."],
       ["Uran", "92", "Schwerstes natürlich häufig vorkommendes Element."]]'::jsonb),

    ('naturwissenschaft', 'oekologie-begriffe', 'Begriffe der Ökologie',
     'Was bezeichnet der Begriff?',
     'medium', 'Ökologie', 'https://de.wikipedia.org/wiki/%C3%96kologie',
     '[["Symbiose", "Beide Seiten profitieren", "Flechten sind Pilz und Alge zugleich."],
       ["Parasitismus", "Einer profitiert, einer leidet", "Der Wirt wird geschwächt, aber meist nicht getötet."],
       ["Konkurrenz", "Streit um dieselbe Ressource", "Zwei Arten mit gleichem Bedarf verdrängen einander."],
       ["Räuber-Beute-Beziehung", "Fressen und gefressen werden", "Die Bestände schwanken zeitversetzt gegeneinander."],
       ["Nahrungskette", "Abfolge des Fressens", "Von der Pflanze über den Pflanzenfresser zum Räuber."],
       ["Biotop", "Lebensraum", "Der Ort mit seinen unbelebten Bedingungen."],
       ["Biozönose", "Lebensgemeinschaft", "Alle Arten, die diesen Ort teilen."],
       ["Ökosystem", "Lebensraum und Gemeinschaft", "Beides zusammen mit allen Wechselwirkungen."],
       ["Sukzession", "Abfolge der Besiedlung", "Von der Rohfläche über Gräser bis zum Wald."],
       ["Population", "Individuen einer Art", "Alle, die am selben Ort zur selben Zeit leben."],
       ["Ökologische Nische", "Rolle im Gefüge", "Nicht der Ort, sondern der Beruf einer Art."],
       ["Bioindikator", "Zeigerart", "Ihr Vorkommen verrät die Qualität von Luft oder Wasser."]]'::jsonb),

    ('naturwissenschaft', 'skalen-messung', 'Skalen & was sie messen',
     'Was wird mit dieser Skala erfasst?',
     'hard', 'Naturkatastrophe',
     'https://de.wikipedia.org/wiki/Naturkatastrophe',
     '[["Momenten-Magnituden-Skala", "Stärke von Erdbeben", "Löste die Richterskala ab, weil diese nach oben ungenau wird."],
       ["Beaufortskala", "Windstärke", "Von Windstille bis Orkan in zwölf Stufen."],
       ["Fujita-Skala", "Zerstörung durch Tornados", "Abgeleitet aus den Schäden, nicht aus gemessenem Wind."],
       ["Saffir-Simpson-Skala", "Kategorie von Hurrikanen", "Fünf Stufen nach anhaltender Windgeschwindigkeit."],
       ["Vulkanexplosivitätsindex", "Wucht von Vulkanausbrüchen", "Bemisst das ausgeworfene Material."],
       ["INES-Skala", "Schwere nuklearer Ereignisse", "Von der Störung bis zum katastrophalen Unfall."],
       ["Mohs-Skala", "Ritzhärte von Mineralien", "Zehn Stufen, jedes Mineral ritzt die weicheren."],
       ["Celsius-Skala", "Temperatur", "Null und hundert Grad an den Fixpunkten des Wassers."],
       ["pH-Skala", "Saurer oder basischer Charakter", "Sieben ist neutral, darunter sauer."],
       ["Dezibel-Skala", "Schalldruckpegel", "Logarithmisch: zehn Dezibel mehr klingen doppelt so laut."]]'::jsonb),

    ('naturwissenschaft', 'formeln-bedeutung', 'Formeln & ihre Bedeutung',
     'Was beschreibt die Formel?',
     'hard', 'Formel', 'https://de.wikipedia.org/wiki/Formel',
     '[["E = mc²", "Masse ist Energie", "Ein kleiner Massenverlust setzt gewaltige Energie frei."],
       ["F = m · a", "Zweites Newtonsches Gesetz", "Das zweite Newtonsche Gesetz."],
       ["a² + b² = c²", "Satz des Pythagoras", "Gilt in jedem rechtwinkligen Dreieck."],
       ["U = R · I", "Ohmsches Gesetz", "Spannung, Widerstand und Stromstärke hängen zusammen."],
       ["p · V = n · R · T", "Zustand eines idealen Gases", "Druck, Volumen und Temperatur sind gekoppelt."],
       ["E = h · f", "Energie eines Lichtquants", "Je höher die Frequenz, desto energiereicher."],
       ["c = λ · f", "Wellenlänge mal Frequenz", "Ergibt die Ausbreitungsgeschwindigkeit."],
       ["W = F · s", "Verrichtete Arbeit", "Ohne Weg wird keine Arbeit verrichtet."],
       ["ρ = m / V", "Dichte", "Masse bezogen auf das Volumen."],
       ["p = F / A", "Druck", "Dieselbe Kraft auf kleiner Fläche drückt stärker."],
       ["s = ½ · a · t²", "Weg beim freien Fall", "Die Strecke wächst mit dem Quadrat der Zeit."],
       ["λ = h / p", "Materiewellenlänge", "Auch Teilchen haben eine Wellenlänge."]]'::jsonb),

    ('naturwissenschaft', 'tierbauten', 'Tiere & ihre Bauten',
     'Welches Tier baut das?',
     'medium', 'Nest', 'https://de.wikipedia.org/wiki/Nest',
     '[["Damm aus Ästen im Bach", "Biber", "Der Stau schützt den Eingang zur Burg unter Wasser."],
       ["Radnetz aus Seide", "Kreuzspinne", "Wird oft jede Nacht neu gebaut."],
       ["Meterhoher Erdhügel mit Klimaschächten", "Termite", "Die Luftführung hält das Innere kühl."],
       ["Napfnest aus Lehm unter dem Dach", "Mehlschwalbe", "Aus Hunderten Lehmkügelchen zusammengetragen."],
       ["Höhle im Baumstamm", "Specht", "Er zimmert sie jedes Jahr neu; Nachmieter ziehen ein."],
       ["Verzweigtes Gangsystem im Boden", "Maulwurf", "Die Erdhaufen sind nur der Aushub."],
       ["Hügel aus Nadeln und Zweigen", "Waldameise", "Die Südseite ist flacher, damit die Sonne wärmt."],
       ["Nest aus Papier", "Wespe", "Zerkautes Holz wird zu grauem Papierbrei."],
       ["Hängendes Flechtnest", "Webervogel", "Das Männchen baut, das Weibchen prüft die Arbeit."],
       ["Unterirdischer Bau mit mehreren Ausgängen", "Dachs", "Wird über Generationen erweitert und vererbt."]]'::jsonb),

    ('naturwissenschaft', 'gifte-herkunft', 'Gifte & ihre Herkunft',
     'Woher stammt das Gift?',
     'hard', 'Gift', 'https://de.wikipedia.org/wiki/Gift',
     '[["Tetrodotoxin", "Kugelfisch", "Deshalb darf Fugu nur ein geprüfter Koch zubereiten."],
       ["Botulinumtoxin", "Bakterium", "Stärkstes bekanntes Gift, in kleinsten Mengen ein Faltenmittel."],
       ["Nikotin", "Tabakpflanze", "Ursprünglich ein Fraßschutz der Pflanze."],
       ["Atropin", "Tollkirsche", "Weitet die Pupille, wird in der Augenheilkunde genutzt."],
       ["Coniin", "Schierling", "Damit wurde Sokrates hingerichtet."],
       ["Strychnin", "Brechnuss", "Löst Krämpfe der gesamten Muskulatur aus."],
       ["Amanitin", "Knollenblätterpilz", "Die Vergiftung zeigt sich erst nach Stunden."],
       ["Digitoxin", "Fingerhut", "In kleiner Dosis ein altes Herzmedikament."],
       ["Rizin", "Rizinussamen", "Bleibt beim Ölpressen im Presskuchen zurück."],
       ["Batrachotoxin", "Pfeilgiftfrosch", "Die Frösche beziehen es über ihre Nahrung."],
       ["Curare", "Lianenrinde", "Pfeilgift, das die Muskeln lähmt."],
       ["Muscarin", "Fliegenpilz", "Namensgebend für einen ganzen Rezeptortyp."]]'::jsonb),

    ('naturwissenschaft', 'muskeln-bewegungen', 'Muskeln & Bewegungen',
     'Was bewirkt dieser Muskel?',
     'hard', 'Muskulatur', 'https://de.wikipedia.org/wiki/Muskulatur',
     '[["Bizeps", "Beugt den Arm", "Zweiköpfiger Muskel an der Oberarmvorderseite."],
       ["Trizeps", "Streckt den Arm", "Sein Gegenspieler auf der Rückseite."],
       ["Quadrizeps", "Streckt das Knie", "Vierköpfiger Muskel an der Oberschenkelvorderseite."],
       ["Zwerchfell", "Bewirkt das Einatmen", "Zieht sich zusammen und vergrößert den Brustraum."],
       ["Wadenmuskel", "Senkt den Fuß", "Über die Achillessehne mit der Ferse verbunden."],
       ["Kaumuskel", "Schließt den Kiefer", "Einer der kräftigsten Muskeln bezogen auf sein Gewicht."],
       ["Herzmuskel", "Pumpt ohne Ermüdung", "Arbeitet unwillkürlich, ein Leben lang."],
       ["Ringmuskel des Auges", "Schließt das Lid", "Auch für das Blinzeln zuständig."],
       ["Großer Gesäßmuskel", "Streckt die Hüfte", "Wichtig beim Aufstehen und Treppensteigen."],
       ["Kapuzenmuskel", "Hebt die Schulter", "Zieht das Schulterblatt zur Wirbelsäule."]]'::jsonb),

    ('naturwissenschaft', 'klimazonen', 'Klimazonen & Kennzeichen',
     'Wodurch ist die Zone gekennzeichnet?',
     'medium', 'Klimazone', 'https://de.wikipedia.org/wiki/Klimazone',
     '[["Tropen", "Ganzjährig heiß und feucht", "Kaum Jahreszeiten, dafür Tages- statt Jahresklima."],
       ["Subtropen", "Heiße Sommer, milde Winter", "Übergang zwischen Tropen und gemäßigter Zone."],
       ["Gemäßigte Zone", "Vier deutliche Jahreszeiten", "Laubbäume werfen im Winter ihre Blätter ab."],
       ["Polarzone", "Dauerfrostboden", "Die Sonne geht monatelang nicht auf oder nicht unter."],
       ["Wüstenklima", "Kaum Niederschlag", "Starke Temperaturunterschiede zwischen Tag und Nacht."],
       ["Mittelmeerklima", "Trockene Sommer, feuchte Winter", "Hartlaubgewächse überstehen die Dürre."],
       ["Monsunklima", "Ausgeprägte Regenzeit", "Der Wind dreht mit den Jahreszeiten."],
       ["Steppenklima", "Halbtrocken mit Gräsern", "Zu wenig Regen für Wald, genug für Gras."],
       ["Ozeanisches Klima", "Milde Winter, kühle Sommer", "Das Meer dämpft die Ausschläge."],
       ["Kontinentalklima", "Große Temperaturschwankungen", "Heiße Sommer und sehr kalte Winter."],
       ["Hochgebirgsklima", "Klima nach Höhenstufen", "In wenigen Kilometern durchläuft man mehrere Zonen."],
       ["Tundrenklima", "Kurze Vegetationszeit", "Nur Moose, Flechten und Zwergsträucher wachsen."]]'::jsonb),

    ('naturwissenschaft', 'medizin-erfindungen', 'Meilensteine der Medizin',
     'Wer steht hinter dem Fortschritt?',
     'hard', 'Geschichte der Medizin',
     'https://de.wikipedia.org/wiki/Geschichte_der_Medizin',
     '[["Beschreibung des Blutkreislaufs", "William Harvey", "Zeigte 1628, dass das Blut im Kreis fließt."],
       ["Händedesinfektion in der Klinik", "Ignaz Semmelweis", "Senkte das Kindbettfieber drastisch, wurde dennoch angefeindet."],
       ["Antiseptische Chirurgie", "Joseph Lister", "Karbolsäure im Operationssaal senkte die Sterblichkeit."],
       ["Narkose mit Äther", "William Morton", "1846 erstmals öffentlich vorgeführt."],
       ["Stethoskop", "René Laënnec", "Erfunden, um Patientinnen nicht direkt abhören zu müssen."],
       ["Insulin als Therapie", "Frederick Banting", "Machte aus einer tödlichen Krankheit eine behandelbare."],
       ["Elektrokardiogramm", "Willem Einthoven", "Machte die elektrische Aktivität des Herzens sichtbar."],
       ["Künstliche Niere", "Willem Kolff", "Erste Dialyse während der Besatzungszeit in den Niederlanden."],
       ["Computertomografie", "Godfrey Hounsfield", "Rechner setzen viele Röntgenbilder zu Schnitten zusammen."],
       ["Magnetresonanztomografie", "Paul Lauterbur", "Bilder ohne Röntgenstrahlen, mit Magnetfeldern."],
       ["Tragbarer Herzschrittmacher", "Rune Elmqvist", "Erstes Gerät 1958 einem Patienten eingesetzt."],
       ["Erste Herztransplantation", "Christiaan Barnard", "1967 in Kapstadt, der Patient überlebte 18 Tage."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
)

insert into items (quiz_id, category_id, label, position, explanation)
select f.quiz_id, c.id, f.answer, f.position, f.explanation
  from flat f
  join new_categories c
    on c.quiz_id = f.quiz_id
   and c.label = f.label;
