-- Naturwissenschaft, file 1 of 2. Twenty questions, medium and hard.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs, fakes) as (
    values

    ('naturwissenschaft', 'elemente-verwendung', 'Elemente & ihre Verwendung',
     'Wofür wird das Element gebraucht?',
     'medium', 'Chemisches Element',
     'https://de.wikipedia.org/wiki/Chemisches_Element',
     '[["Helium", "Ballonfüllung", "Leichter als Luft und nicht brennbar."],
       ["Neon", "Leuchtreklame", "Gibt im Gasentladungsrohr rotes Licht."],
       ["Chlor", "Desinfektion", "Tötet Keime im Trink- und Badewasser."],
       ["Uran", "Kernbrennstoff", "Nur das Isotop 235 ist leicht spaltbar."],
       ["Wolfram", "Glühwendel", "Höchster Schmelzpunkt aller Metalle."],
       ["Silicium", "Mikrochips", "Halbleiter, aus Quarzsand gewonnen."],
       ["Titan", "Implantate", "Leicht, fest und vom Körper vertragen."],
       ["Lithium", "Akkus", "Leichtestes Metall, speichert viel Energie pro Gramm."],
       ["Iod", "Schilddrüsenhormone", "Ohne Zufuhr wächst die Drüse zum Kropf."],
       ["Argon", "Schutzgas beim Schweißen", "Reagiert mit nichts und hält Luft von der Naht fern."],
       ["Fluor", "Zahnpasta", "Härtet den Zahnschmelz gegen Säure."],
       ["Platin", "Autokatalysator", "Wandelt Abgase um, ohne selbst verbraucht zu werden."]]'::jsonb,
     '[["Bleistiftminen", "Dafür braucht es Graphit, und Kohlenstoff steht nicht auf dem Brett."],
       ["Fieberthermometer von früher", "Das war Quecksilber, und das fehlt in dieser Liste."]]'::jsonb),

    ('naturwissenschaft', 'planeten-merkmale', 'Planeten & ihre Besonderheiten',
     'Welcher Himmelskörper ist gemeint?',
     'medium', 'Planet', 'https://de.wikipedia.org/wiki/Planet',
     '[["Kleinster Planet", "Merkur", "Kaum größer als der Erdmond, ohne Atmosphäre."],
       ["Heißeste Oberfläche", "Venus", "Der Treibhauseffekt hält über 460 Grad."],
       ["Flüssiges Wasser an der Oberfläche", "Erde", "Einziger bekannter Planet mit Ozeanen."],
       ["Größter Vulkan", "Mars", "Olympus Mons ist rund 22 Kilometer hoch."],
       ["Großer Roter Fleck", "Jupiter", "Ein Sturm, größer als die Erde, seit Jahrhunderten."],
       ["Auffälliges Ringsystem", "Saturn", "Milliarden Eisbrocken, kaum einen Kilometer dick."],
       ["Liegende Rotationsachse", "Uranus", "Rollt praktisch auf seiner Bahn um die Sonne."],
       ["Stärkste Winde", "Neptun", "Bis zu 2000 Kilometer pro Stunde."],
       ["2006 zum Zwergplaneten erklärt", "Pluto", "Er räumt seine Bahn nicht frei."],
       ["Größter Körper im Asteroidengürtel", "Ceres", "Rund ein Viertel der Masse des ganzen Gürtels."]]'::jsonb,
     '[["Größter Mond des Sonnensystems", "Das ist Ganymed, und der fehlt auf diesem Brett."],
       ["Schweif aus Staub und Gas", "Das trifft auf Kometen zu, die hier nicht stehen."]]'::jsonb),

    ('naturwissenschaft', 'knochen-namen', 'Knochen & ihre deutschen Namen',
     'Welcher Knochen ist das?',
     'hard', 'Knochen', 'https://de.wikipedia.org/wiki/Knochen',
     '[["Femur", "Oberschenkelknochen", "Längster und kräftigster Knochen des Körpers."],
       ["Humerus", "Oberarmknochen", "Trägt am unteren Ende das Ellenbogengelenk."],
       ["Tibia", "Schienbein", "Der dickere der beiden Unterschenkelknochen."],
       ["Fibula", "Wadenbein", "Der dünne Knochen neben dem Schienbein."],
       ["Radius", "Speiche", "Dreht sich beim Handwenden um die Elle."],
       ["Ulna", "Elle", "Bildet die Spitze des Ellenbogens."],
       ["Clavicula", "Schlüsselbein", "Bricht bei Stürzen auf die Schulter besonders oft."],
       ["Scapula", "Schulterblatt", "Liegt beweglich auf dem Brustkorb auf."],
       ["Sternum", "Brustbein", "An ihm setzen die Rippenknorpel an."],
       ["Patella", "Kniescheibe", "Größter Knochen, der in einer Sehne liegt."],
       ["Mandibula", "Unterkiefer", "Einziger frei beweglicher Schädelknochen."],
       ["Calcaneus", "Fersenbein", "Größter Knochen des Fußes."]]'::jsonb,
     '[["Wirbel", "Vertebra wäre der Name dazu, und der fehlt auf diesem Brett."],
       ["Steißbein", "Das Os coccygis steht nicht in dieser Liste."]]'::jsonb),

    ('naturwissenschaft', 'hormone-wirkungen', 'Hormone & ihre Wirkung',
     'Was bewirkt das Hormon?',
     'hard', 'Hormon', 'https://de.wikipedia.org/wiki/Hormon',
     '[["Insulin", "Senkt den Blutzucker", "Schleust Zucker aus dem Blut in die Zellen."],
       ["Glukagon", "Hebt den Blutzucker", "Gegenspieler des Insulins, holt Zucker aus der Leber."],
       ["Adrenalin", "Kampf oder Flucht", "Puls und Blutdruck steigen binnen Sekunden."],
       ["Cortisol", "Antwort auf Dauerstress", "Stellt Energie bereit und dämpft Entzündungen."],
       ["Melatonin", "Steuert den Schlaf", "Wird im Dunkeln ausgeschüttet."],
       ["Thyroxin", "Treibt den Stoffwechsel an", "Aus der Schilddrüse, braucht Iod als Baustein."],
       ["Testosteron", "Männliche Merkmale", "Bewirkt Bartwuchs und Stimmbruch."],
       ["Östrogen", "Weiblicher Zyklus", "Baut die Gebärmutterschleimhaut auf."],
       ["Oxytocin", "Wehen und Bindung", "Löst Kontraktionen aus und stärkt die Bindung."],
       ["Somatropin", "Längenwachstum", "Wachstumshormon aus der Hirnanhangdrüse."],
       ["Prolaktin", "Milchbildung", "Steigt nach der Geburt stark an."],
       ["Vasopressin", "Hält Wasser zurück", "Die Niere gibt weniger Harn ab."]]'::jsonb,
     '[["Bindet Sauerstoff im Blut", "Das leistet Hämoglobin, und das ist kein Hormon."],
       ["Löst Niesreiz aus", "Kein Hormon auf diesem Brett tut das."]]'::jsonb),

    ('naturwissenschaft', 'vitamine-mangel', 'Vitamine & Mangelkrankheiten',
     'Welcher Mangel ruft die Krankheit hervor?',
     'hard', 'Vitamin', 'https://de.wikipedia.org/wiki/Vitamin',
     '[["Skorbut", "Vitamin C", "Zahnfleischbluten auf langen Seereisen ohne Obst."],
       ["Rachitis", "Vitamin D", "Weiche Knochen bei Kindern ohne Sonnenlicht."],
       ["Nachtblindheit", "Vitamin A", "Die Netzhaut braucht es für das Sehen im Dämmerlicht."],
       ["Beriberi", "Vitamin B1", "Trat auf, als Reis geschält gegessen wurde."],
       ["Pellagra", "Vitamin B3", "Haut, Darm und Nerven leiden zugleich."],
       ["Perniziöse Anämie", "Vitamin B12", "Fehlt vor allem bei rein pflanzlicher Kost."],
       ["Blutungsneigung", "Vitamin K", "Ohne es fehlen Gerinnungsfaktoren."],
       ["Neuralrohrdefekt", "Folsäure", "Deshalb wird sie in der Frühschwangerschaft empfohlen."],
       ["Eingerissene Mundwinkel", "Vitamin B2", "Auch Haut und Schleimhäute werden empfindlich."],
       ["Kropf", "Iod", "Die Schilddrüse wächst, um den Mangel auszugleichen."],
       ["Blutarmut mit Blässe", "Eisen", "Ohne es fehlt der rote Blutfarbstoff."],
       ["Osteoporose", "Calcium", "Die Knochendichte nimmt ab, Brüche häufen sich."]]'::jsonb,
     '[["Vitamin E", "Sein Mangel ruft keine Krankheit auf diesem Brett hervor."],
       ["Magnesium", "Ein Mangel führt zu Krämpfen, die hier nicht stehen."]]'::jsonb),

    ('naturwissenschaft', 'wissenschaftler-theorien', 'Forscher & ihre Theorien',
     'Wer steht hinter dieser Erkenntnis?',
     'medium', 'Naturwissenschaft',
     'https://de.wikipedia.org/wiki/Naturwissenschaft',
     '[["Gravitationsgesetz", "Isaac Newton", "Dieselbe Kraft hält den Mond und lässt den Apfel fallen."],
       ["Relativitätstheorie", "Albert Einstein", "Zeit und Raum hängen vom Bewegungszustand ab."],
       ["Evolution durch Auslese", "Charles Darwin", "Wer besser passt, hinterlässt mehr Nachkommen."],
       ["Vererbungsregeln", "Gregor Mendel", "Kreuzungsversuche mit Erbsen im Klostergarten."],
       ["Gesetze der Planetenbahnen", "Johannes Kepler", "Die Bahnen sind Ellipsen, nicht Kreise."],
       ["Quantenhypothese", "Max Planck", "Energie wird nur in Portionen abgegeben."],
       ["Atommodell mit Schalen", "Niels Bohr", "Elektronen springen zwischen festen Bahnen."],
       ["Erhaltung der Masse", "Antoine Lavoisier", "Bei einer Reaktion geht nichts verloren."],
       ["Keime als Krankheitsursache", "Louis Pasteur", "Erhitzen tötet die Erreger in Milch und Wein."],
       ["Kontinentaldrift", "Alfred Wegener", "Die Kontinente passen wie Puzzleteile zusammen."],
       ["Radioaktivität", "Marie Curie", "Sie fand Polonium und Radium in der Pechblende."],
       ["Bau der DNA-Doppelhelix", "Rosalind Franklin", "Ihr Röntgenbild 51 zeigte die Schraubenform."]]'::jsonb,
     '[["Periodensystem der Elemente", "Das geht auf Mendelejew zurück, der hier fehlt."],
       ["Nikolaus Kopernikus", "Das heliozentrische Weltbild steht nicht auf diesem Brett."]]'::jsonb),

    ('naturwissenschaft', 'tiere-rekorde', 'Tiere & ihre Rekorde',
     'Welches Tier hält diesen Rekord?',
     'medium', 'Tier', 'https://de.wikipedia.org/wiki/Tier',
     '[["Größtes Tier der Erde", "Blauwal", "Bis zu 30 Meter lang und 150 Tonnen schwer."],
       ["Schnellstes Landtier", "Gepard", "Über kurze Strecken mehr als 100 km/h."],
       ["Schnellster Sturzflug", "Wanderfalke", "Im Sturzflug über 300 km/h."],
       ["Größte Augen", "Riesenkalmar", "Augen so groß wie Teller, für das Dunkel der Tiefsee."],
       ["Kleinster Vogel", "Bienenelfe", "Wiegt weniger als zwei Gramm."],
       ["Größtes Landtier", "Afrikanischer Elefant", "Bis zu sechs Tonnen schwer."],
       ["Höchstes Tier", "Giraffe", "Der Hals hat sieben Wirbel, wie bei fast allen Säugern."],
       ["Längster Zug im Jahr", "Küstenseeschwalbe", "Pendelt zwischen Arktis und Antarktis."],
       ["Ältestes Wirbeltier", "Grönlandhai", "Wird über 250 Jahre alt."],
       ["Überlebt selbst im Vakuum", "Bärtierchen", "Übersteht Kälte, Hitze und Strahlung im Trockenstarre-Zustand."],
       ["Stärkstes Gift im Tierreich", "Seewespe", "Eine Würfelqualle, deren Nesselgift binnen Minuten tötet."],
       ["Lauteste Rufe", "Pistolenkrebs", "Der Knall seiner Schere übertönt ein Schiffsmotorengeräusch."]]'::jsonb,
     '[["Längstes Tier der Erde", "Das ist der Nesseltier-Staat, der hier nicht steht."],
       ["Kleinstes Säugetier", "Die Schweinsnasenfledermaus fehlt auf diesem Brett."]]'::jsonb),

    ('naturwissenschaft', 'mohs-haerteskala', 'Mohssche Härteskala',
     'Welche Härte hat das Mineral auf der Skala?',
     'hard', 'Härte', 'https://de.wikipedia.org/wiki/H%C3%A4rte',
     '[["Talk", "1", "Lässt sich mit dem Fingernagel abschaben."],
       ["Gips", "2", "Noch mit dem Fingernagel ritzbar."],
       ["Calcit", "3", "Mit einer Kupfermünze ritzbar."],
       ["Fluorit", "4", "Mit einem Messer leicht zu ritzen."],
       ["Apatit", "5", "Der Hauptbestandteil von Zahnschmelz und Knochen."],
       ["Feldspat", "6", "Ritzt Fensterglas gerade eben."],
       ["Quarz", "7", "Ritzt Glas; als Sandkorn überall vorhanden."],
       ["Topas", "8", "Ritzt Quarz, wird selbst von Korund geritzt."],
       ["Korund", "9", "Als Rubin und Saphir ein Schmuckstein."],
       ["Diamant", "10", "Härtestes natürliches Mineral, nur von sich selbst ritzbar."]]'::jsonb,
     '[["0", "Die Skala beginnt bei eins, eine Null gibt es nicht."],
       ["11", "Die Skala endet beim Diamanten mit zehn."]]'::jsonb),

    ('naturwissenschaft', 'verbindungen-alltagsnamen', 'Chemische Namen & Alltagsnamen',
     'Wie heißt der Stoff im Alltag?',
     'medium', 'Chemische Verbindung',
     'https://de.wikipedia.org/wiki/Chemische_Verbindung',
     '[["Natriumchlorid", "Kochsalz", "Im Meerwasser gelöst und im Bergwerk abgebaut."],
       ["Saccharose", "Haushaltszucker", "Aus Zuckerrübe oder Zuckerrohr gewonnen."],
       ["Ethanol", "Trinkalkohol", "Entsteht, wenn Hefe Zucker vergärt."],
       ["Essigsäure", "Essig", "In verdünnter Form Würz- und Konserviermittel."],
       ["Natriumhydrogencarbonat", "Natron", "Treibmittel im Teig und Mittel gegen Sodbrennen."],
       ["Calciumcarbonat", "Kalk", "Baustoff von Muschelschalen und Kalkstein."],
       ["Acetylsalicylsäure", "Aspirin", "Abkömmling eines Wirkstoffs aus der Weidenrinde."],
       ["Natriumhydroxid", "Ätznatron", "Starke Lauge, in Rohrreinigern enthalten."],
       ["Ammoniak in Wasser", "Salmiakgeist", "Stechend riechender Haushaltsreiniger."],
       ["Schwefelsäure", "Batteriesäure", "Im Bleiakku des Autos enthalten."],
       ["Wasserstoffperoxid", "Bleichmittel", "Zerfällt zu Wasser und Sauerstoff."],
       ["Distickstoffmonoxid", "Lachgas", "Früher als Narkosemittel beim Zahnarzt."]]'::jsonb,
     '[["Zitronensäure", "Sie steckt in Entkalkern, ihr chemischer Name fehlt hier."],
       ["Trockeneis", "Das ist festes Kohlendioxid, und das steht nicht auf dem Brett."]]'::jsonb),

    ('naturwissenschaft', 'erreger-krankheiten', 'Erreger & Krankheiten',
     'Welche Krankheit löst der Erreger aus?',
     'hard', 'Krankheitserreger',
     'https://de.wikipedia.org/wiki/Krankheitserreger',
     '[["Plasmodium", "Malaria", "Ein einzelliger Parasit, übertragen von der Anophelesmücke."],
       ["Mycobacterium tuberculosis", "Tuberkulose", "Robert Koch stellte den Erreger 1882 vor."],
       ["Vibrio cholerae", "Cholera", "Kommaförmiges Bakterium in verunreinigtem Wasser."],
       ["Yersinia pestis", "Pest", "Über Flöhe von Ratten auf Menschen übertragen."],
       ["Treponema pallidum", "Syphilis", "Schraubenförmiges Bakterium, im 16. Jahrhundert gefürchtet."],
       ["HIV", "Aids", "Zerstört die Helferzellen des Immunsystems."],
       ["Influenzavirus", "Grippe", "Verändert seine Oberfläche und entkommt der Immunabwehr."],
       ["Varizella-Zoster-Virus", "Windpocken", "Bleibt lebenslang im Körper und kann als Gürtelrose wiederkehren."],
       ["Borrelia burgdorferi", "Borreliose", "Von Zecken übertragen, oft mit Wanderröte."],
       ["Clostridium tetani", "Wundstarrkrampf", "Sein Gift lässt die Muskeln verkrampfen."],
       ["Rabiesvirus", "Tollwut", "Wandert entlang der Nerven ins Gehirn."],
       ["Salmonella", "Salmonellose", "Häufig über rohe Eier oder Geflügel übertragen."]]'::jsonb,
     '[["Masern", "Das Masernvirus wäre der Erreger dazu, und der fehlt hier."],
       ["Fußpilz", "Er wird von Pilzen verursacht, die in dieser Liste nicht stehen."]]'::jsonb),

    ('naturwissenschaft', 'sterne-sternbilder', 'Sterne & Sternbilder',
     'In welchem Sternbild steht der Stern?',
     'hard', 'Sternbild', 'https://de.wikipedia.org/wiki/Sternbild',
     '[["Sirius", "Großer Hund", "Hellster Stern am Nachthimmel, nur 8,6 Lichtjahre entfernt."],
       ["Beteigeuze", "Orion", "Roter Überriese in der Schulter des Jägers."],
       ["Polarstern", "Kleiner Bär", "Steht fast genau über dem Nordpol der Erde."],
       ["Wega", "Leier", "In 12000 Jahren wird sie der Polarstern sein."],
       ["Aldebaran", "Stier", "Das rötliche Auge des Stiers."],
       ["Antares", "Skorpion", "Sein Name bedeutet Gegen-Mars, wegen der roten Farbe."],
       ["Regulus", "Löwe", "Steht fast genau auf der Bahn der Sonne."],
       ["Deneb", "Schwan", "Einer der leuchtkräftigsten bekannten Sterne."],
       ["Spica", "Jungfrau", "Der Name bedeutet Kornähre."],
       ["Capella", "Fuhrmann", "In Mitteleuropa das ganze Jahr über sichtbar."],
       ["Prokyon", "Kleiner Hund", "Geht kurz vor Sirius auf, daher der Name."],
       ["Arktur", "Bärenhüter", "Zu finden, indem man die Deichsel des Wagens verlängert."]]'::jsonb,
     '[["Kassiopeia", "Kein Stern auf diesem Brett steht in diesem Sternbild."],
       ["Großer Wagen", "Das ist kein eigenes Sternbild, sondern Teil des Großen Bären."]]'::jsonb),

    ('naturwissenschaft', 'erdzeitalter', 'Erdzeitalter & ihre Kennzeichen',
     'Wofür steht diese Periode der Erdgeschichte?',
     'hard', 'Geologische Zeitskala',
     'https://de.wikipedia.org/wiki/Geologische_Zeitskala',
     '[["Kambrium", "Explosion der Tierstämme", "Fast alle heutigen Baupläne treten binnen weniger Millionen Jahre auf."],
       ["Ordovizium", "Erste Landpflanzen", "Moosartige Pflanzen besiedeln das Festland."],
       ["Silur", "Erste Kiefermäuler", "Fische mit Kiefern beginnen zu jagen."],
       ["Devon", "Zeitalter der Fische", "Erste Wirbeltiere gehen an Land."],
       ["Karbon", "Steinkohlewälder", "Riesige Sumpfwälder werden später zu Kohle."],
       ["Perm", "Größtes Massenaussterben", "Rund drei Viertel der Landarten verschwinden."],
       ["Trias", "Erste Dinosaurier", "Auch die ersten Säugetiere treten auf."],
       ["Jura", "Archaeopteryx", "Der Urvogel verbindet Reptil und Vogel."],
       ["Kreide", "Ende der Dinosaurier", "Ein Einschlag auf Yucatán beendet die Epoche."],
       ["Paläogen", "Aufstieg der Säugetiere", "Die frei gewordenen Lebensräume werden neu besetzt."],
       ["Neogen", "Erste Menschenaffen", "In Afrika entstehen die Vorfahren des Menschen."],
       ["Quartär", "Eiszeiten", "Gletscher reichen mehrfach bis nach Norddeutschland."]]'::jsonb,
     '[["Erste Vielzeller im Wasser", "Das gehört ins Ediacarium, das hier fehlt."],
       ["Bildung der ersten Kontinente", "Das war im Präkambrium, und das steht nicht auf dem Brett."]]'::jsonb),

    ('naturwissenschaft', 'baumarten-merkmale', 'Bäume & ihre Merkmale',
     'Woran ist der Baum zu erkennen?',
     'medium', 'Baum', 'https://de.wikipedia.org/wiki/Baum',
     '[["Eiche", "Eicheln", "Ihre Früchte sitzen in einem Becher."],
       ["Buche", "Bucheckern", "Dreikantige Nüsschen in einer stacheligen Hülle."],
       ["Birke", "Weiße Rinde", "Sie schält sich in dünnen Streifen ab."],
       ["Fichte", "Hängende Zapfen", "Die Nadeln sitzen einzeln und stechen."],
       ["Kiefer", "Nadeln zu zweit", "Die langen Nadeln stehen paarweise."],
       ["Lärche", "Wirft die Nadeln ab", "Einziger heimischer Nadelbaum, der kahl überwintert."],
       ["Ahorn", "Flügelfrüchte", "Die Nüsschen drehen sich beim Fallen wie Propeller."],
       ["Rosskastanie", "Stachelige Fruchthülle", "Darin sitzt die glänzend braune Kastanie."],
       ["Weide", "Kätzchen im Frühjahr", "Blüht, bevor die Blätter kommen."],
       ["Linde", "Herzförmige Blätter", "Der Fruchtstand hängt an einem Flugblatt."],
       ["Esche", "Schwarze Knospen", "Im Winter das sicherste Erkennungszeichen."],
       ["Eibe", "Roter Samenmantel", "Alle übrigen Teile des Baums sind giftig."]]'::jsonb,
     '[["Stachelige Blätter und rote Beeren", "Das wäre die Stechpalme, und die fehlt hier."],
       ["Rinde löst sich in Platten ab", "Die Platane steht nicht auf diesem Brett."]]'::jsonb),

    ('naturwissenschaft', 'gesteine-entstehung', 'Gesteine & ihre Entstehung',
     'Woraus ist das Gestein entstanden?',
     'medium', 'Gestein', 'https://de.wikipedia.org/wiki/Gestein',
     '[["Granit", "Erstarrtes Tiefenmagma", "Langsame Abkühlung ließ große Kristalle wachsen."],
       ["Basalt", "Erstarrte Lava", "Schnelle Abkühlung, oft in sechseckigen Säulen."],
       ["Obsidian", "Vulkanisches Glas", "So rasch erstarrt, dass sich keine Kristalle bildeten."],
       ["Bimsstein", "Erstarrter Lavaschaum", "Voller Gasblasen und leicht genug zum Schwimmen."],
       ["Sandstein", "Verfestigter Sand", "Körner, durch Druck und Kittmasse verbunden."],
       ["Kalkstein", "Schalen von Meerestieren", "Aus abgelagerten Kalkskeletten entstanden."],
       ["Steinkohle", "Verkohlte Pflanzenreste", "Sumpfwälder unter Druck und Luftabschluss."],
       ["Steinsalz", "Eingedampftes Meerwasser", "Blieb zurück, als flache Meere austrockneten."],
       ["Konglomerat", "Verkittete Kiesel", "Runde Gerölle in feiner Grundmasse."],
       ["Marmor", "Umgewandelter Kalkstein", "Hitze und Druck ließen den Kalk neu kristallisieren."],
       ["Gneis", "Umgewandelter Granit", "Zeigt eine deutliche Bänderung."],
       ["Tonschiefer", "Umgewandelter Ton", "Spaltet sich in dünne Platten, früher für Dächer."]]'::jsonb,
     '[["Zusammengepresster Meeresschlamm", "Der Tonstein fehlt auf diesem Brett."],
       ["Eingeschlagener Meteorit", "Impaktgestein steht nicht in dieser Liste."]]'::jsonb),

    ('naturwissenschaft', 'raumsonden-ziele', 'Raumsonden & ihre Ziele',
     'Wohin flog die Mission?',
     'hard', 'Raumsonde', 'https://de.wikipedia.org/wiki/Raumsonde',
     '[["Apollo 11", "Mond", "1969 landeten zwei Menschen im Mare Tranquillitatis."],
       ["Voyager 1", "Interstellarer Raum", "Verließ 2012 als erstes Objekt die Heliosphäre."],
       ["Cassini", "Saturn", "13 Jahre im Orbit, am Ende gezielt in den Planeten gestürzt."],
       ["Juno", "Jupiter", "Vermisst das Magnetfeld des Riesenplaneten."],
       ["New Horizons", "Pluto", "Lieferte 2015 die ersten scharfen Bilder."],
       ["Rosetta", "Komet Tschurjumow-Gerassimenko", "Setzte mit Philae einen Lander auf einem Kometen ab."],
       ["Curiosity", "Mars", "Rover, der seit 2012 den Gale-Krater durchfährt."],
       ["Parker Solar Probe", "Sonne", "Fliegt näher an die Sonne als je ein Objekt zuvor."],
       ["Hayabusa2", "Asteroid Ryugu", "Brachte Bodenproben zur Erde zurück."],
       ["Venera 7", "Venus", "Erste weiche Landung auf einem anderen Planeten."],
       ["Messenger", "Merkur", "Erste Sonde im Orbit des sonnennächsten Planeten."],
       ["James-Webb-Teleskop", "Frühes Universum", "Beobachtet im Infraroten von einem Punkt hinter der Erde aus."]]'::jsonb,
     '[["Uranus", "Nur Voyager 2 flog dorthin, und die Sonde fehlt auf dem Brett."],
       ["Titan", "Die Landesonde Huygens erreichte ihn, sie steht hier nicht."]]'::jsonb),

    ('naturwissenschaft', 'einheiten-praefixe', 'Vorsätze der Maßeinheiten',
     'Für welchen Faktor steht der Vorsatz?',
     'medium', 'Vorsätze für Maßeinheiten',
     'https://de.wikipedia.org/wiki/Vors%C3%A4tze_f%C3%BCr_Ma%C3%9Feinheiten',
     '[["Kilo", "Tausend", "Vom griechischen chilioi."],
       ["Mega", "Million", "Vom griechischen megas, groß."],
       ["Giga", "Milliarde", "Vom griechischen gigas, Riese."],
       ["Tera", "Billion", "Vom griechischen teras, Ungeheuer."],
       ["Hekto", "Hundert", "Steckt im Hektar und im Hektoliter."],
       ["Dezi", "Zehntel", "Steckt im Deziliter."],
       ["Zenti", "Hundertstel", "Vom lateinischen centum."],
       ["Milli", "Tausendstel", "Vom lateinischen mille."],
       ["Mikro", "Millionstel", "Geschrieben mit dem griechischen my."],
       ["Nano", "Milliardstel", "Vom griechischen nanos, Zwerg."],
       ["Piko", "Billionstel", "Gebräuchlich bei Kondensatoren."],
       ["Femto", "Billiardstel", "In dieser Größenordnung dauern chemische Reaktionsschritte."]]'::jsonb,
     '[["Milliardstel eines Milliardstels", "Kein Vorsatz auf diesem Brett meint das."],
       ["Zehn", "Deka wäre der Vorsatz dazu, und der fehlt in dieser Liste."]]'::jsonb),

    ('naturwissenschaft', 'genetik-begriffe', 'Begriffe der Genetik',
     'Was bezeichnet der Begriff?',
     'hard', 'Genetik', 'https://de.wikipedia.org/wiki/Genetik',
     '[["Gen", "Bauplan eines Proteins", "Ein Abschnitt der DNA mit einer Bedeutung."],
       ["Chromosom", "Verpackte DNA", "Der Mensch hat davon 46 in jeder Körperzelle."],
       ["Allel", "Variante eines Gens", "Zum Beispiel für braune oder blaue Augen."],
       ["Genom", "Gesamtes Erbgut", "Beim Menschen rund drei Milliarden Basenpaare."],
       ["Mutation", "Änderung der Erbinformation", "Zufällig, aber Rohstoff der Evolution."],
       ["Ribosom", "Ort der Proteinsynthese", "Liest die Abschrift und fügt Aminosäuren zusammen."],
       ["Boten-RNA", "Abschrift eines Gens", "Trägt die Information aus dem Kern hinaus."],
       ["Mitose", "Teilung mit gleichem Satz", "Aus einer Zelle werden zwei identische."],
       ["Meiose", "Halbierung des Chromosomensatzes", "Führt zu Ei- und Samenzellen."],
       ["Phänotyp", "Äußeres Erscheinungsbild", "Ergebnis von Erbgut und Umwelt."],
       ["Genotyp", "Genetische Ausstattung", "Die Anlagen selbst, unabhängig vom Aussehen."],
       ["Rezessiv", "Nur doppelt sichtbar", "Zeigt sich erst, wenn beide Allele gleich sind."]]'::jsonb,
     '[["Zelle ohne Zellkern", "Das beschreibt Prokaryoten, kein Begriff auf dem Brett."],
       ["Übertragung durch Viren", "Die Transduktion steht nicht in dieser Liste."]]'::jsonb),

    ('naturwissenschaft', 'nobelpreise-entdeckungen', 'Nobelpreise & Entdeckungen',
     'Wer wurde dafür ausgezeichnet?',
     'hard', 'Nobelpreis', 'https://de.wikipedia.org/wiki/Nobelpreis',
     '[["Unschärferelation", "Werner Heisenberg", "Ort und Impuls sind nicht zugleich scharf bestimmbar."],
       ["Wellengleichung der Quantenmechanik", "Erwin Schrödinger", "Beschreibt Teilchen als Wellenfunktion."],
       ["Entdeckung des Atomkerns", "Ernest Rutherford", "Goldfolienversuch: fast alles ist leer."],
       ["Entdeckung des Neutrons", "James Chadwick", "Das fehlende, ungeladene Kernteilchen."],
       ["Kernspaltung", "Otto Hahn", "Uran zerfiel unerwartet in leichtere Elemente."],
       ["Photoelektrischer Effekt", "Albert Einstein", "Dafür, nicht für die Relativitätstheorie, gab es den Preis."],
       ["Quantenelektrodynamik", "Richard Feynman", "Diagramme machten die Rechnungen anschaulich."],
       ["Vorhersage des Higgs-Bosons", "Peter Higgs", "Fast fünfzig Jahre später am CERN nachgewiesen."],
       ["Genschere CRISPR", "Emmanuelle Charpentier", "Erlaubt gezielte Schnitte im Erbgut."],
       ["Blaue Leuchtdiode", "Shuji Nakamura", "Machte weißes LED-Licht überhaupt erst möglich."],
       ["Struktur des Insulins", "Frederick Sanger", "Erste vollständig entschlüsselte Proteinsequenz."],
       ["Gravitationswellen", "Rainer Weiss", "2015 erstmals direkt gemessen, von LIGO."]]'::jsonb,
     '[["Entdeckung des Penicillins", "Alexander Fleming wurde dafür geehrt, er fehlt hier."],
       ["Niels Bohr", "Sein Atommodell steht nicht auf diesem Brett."]]'::jsonb),

    ('naturwissenschaft', 'experimente-personen', 'Berühmte Experimente',
     'Wer führte den Versuch durch?',
     'hard', 'Experiment', 'https://de.wikipedia.org/wiki/Experiment',
     '[["Messung des Erdumfangs", "Eratosthenes", "Aus zwei Schattenlängen und dem Abstand zweier Städte."],
       ["Fallversuche am schiefen Turm", "Galileo Galilei", "Schwere und leichte Körper fallen gleich schnell."],
       ["Doppelspaltversuch", "Thomas Young", "Licht zeigte Interferenz und damit Wellencharakter."],
       ["Pendel im Panthéon", "Léon Foucault", "Die Schwingungsebene dreht sich, weil die Erde rotiert."],
       ["Öltröpfchenversuch", "Robert Millikan", "Bestimmte die Ladung eines einzelnen Elektrons."],
       ["Impfung mit Kuhpocken", "Edward Jenner", "Der Junge blieb danach gegen Pocken geschützt."],
       ["Speichelfluss bei Hunden", "Iwan Pawlow", "Der Glockenton allein löste die Reaktion aus."],
       ["Drachen im Gewitter", "Benjamin Franklin", "Zeigte, dass Blitze elektrische Entladungen sind."],
       ["Magdeburger Halbkugeln", "Otto von Guericke", "Sechzehn Pferde bekamen die leergepumpten Kugeln nicht auseinander."],
       ["Wärmeäquivalent", "James Prescott Joule", "Rührwerk im Wasser: Arbeit lässt sich in Wärme umrechnen."],
       ["Nachweis der Radiowellen", "Heinrich Hertz", "Bestätigte die Vorhersage von Maxwell."],
       ["Ursuppen-Experiment", "Stanley Miller", "Aus einfachen Gasen entstanden Aminosäuren."]]'::jsonb,
     '[["Nachweis der Erdrotation im Labor", "Das leistete Foucaults Pendel, und das steht schon da."],
       ["Kartoffelversuche zur Vererbung", "Mendel arbeitete mit Erbsen, und er fehlt auf dem Brett."]]'::jsonb),

    ('naturwissenschaft', 'mathematische-konstanten', 'Mathematische Konstanten',
     'Wofür steht diese Zahl?',
     'medium', 'Mathematische Konstante',
     'https://de.wikipedia.org/wiki/Mathematische_Konstante',
     '[["Pi", "Umfang durch Durchmesser", "Bei jedem Kreis dasselbe Verhältnis, rund 3,14159."],
       ["Eulersche Zahl", "Basis des natürlichen Logarithmus", "Rund 2,71828; beschreibt stetiges Wachstum."],
       ["Goldener Schnitt", "Teilung im Verhältnis 1,618", "Das Ganze zum größeren Teil wie der größere zum kleineren."],
       ["Wurzel zwei", "Diagonale im Einheitsquadrat", "Die erste Zahl, die als irrational erkannt wurde."],
       ["Imaginäre Einheit", "Wurzel aus minus eins", "Erweitert die Zahlen in die komplexe Ebene."],
       ["Null", "Neutrales Element der Addition", "Aus Indien nach Europa gelangt."],
       ["Eins", "Neutrales Element der Multiplikation", "Jede Zahl bleibt bei Multiplikation sie selbst."],
       ["Unendlich", "Größer als jede Zahl", "Kein Zahlenwert, sondern ein Grenzverhalten."],
       ["Feigenbaum-Konstante", "Weg ins Chaos", "Taucht bei Periodenverdopplungen immer wieder auf."],
       ["Eulersche Identität", "Verknüpft fünf Grundzahlen", "Verbindet e, i, Pi, Eins und Null in einer Gleichung."]]'::jsonb,
     '[["Verhältnis von Fläche zu Umfang", "Keine Konstante auf diesem Brett steht dafür."],
       ["Kleinste Primzahl", "Die Zwei ist es, und danach fragt hier keine Zeile."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

-- The answers that belong to no category. Numbered after the pairs so the two
-- sets never collide on `position`, though nothing reads it for a fake: the
-- pool is shuffled before a player sees it, and the review lists fakes on their
-- own rather than in board order.
fakes as (
    select q.id                                         as quiz_id,
           k.value ->> 0                                as label,
           k.value ->> 1                                as explanation,
           (jsonb_array_length(sp.pairs) + k.ord)::int  as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.fakes) with ordinality k(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
),

paired as (
    insert into items (quiz_id, category_id, label, position, explanation)
    select f.quiz_id, c.id, f.answer, f.position, f.explanation
      from flat f
      join new_categories c
        on c.quiz_id = f.quiz_id
       and c.label = f.label
    returning id
)

-- Same table, `category_id` left null. Both inserts run in the one statement,
-- so `items_quiz_id_label_key` still sees the pairs above: a fake written to
-- repeat an answer already on its own board fails the file rather than becoming
-- a second row nobody can tell apart.
insert into items (quiz_id, category_id, label, position, explanation)
select k.quiz_id, null, k.label, k.position, k.explanation
  from fakes k;
