-- Sport, file 2 of 2. Twenty questions, medium and hard.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs, fakes) as (
    values

    ('sport', 'sportler-laender', 'Sportgrößen & ihre Länder',
     'Für welches Land trat die Person an?',
     'medium', 'Sport', 'https://de.wikipedia.org/wiki/Sport',
     '[["Usain Bolt", "Jamaika", "Der schnellste Mensch kam von einer Karibikinsel."],
       ["Roger Federer", "Schweiz", "Achtmal Wimbledonsieger."],
       ["Cristiano Ronaldo", "Portugal", "Führte sein Land 2016 zum Europameistertitel."],
       ["Novak Djokovic", "Serbien", "Rekordhalter bei Grand-Slam-Titeln der Männer."],
       ["Lewis Hamilton", "Vereinigtes Königreich", "Sieben Formel-1-Weltmeistertitel."],
       ["Simone Biles", "USA", "Mehrere Turnelemente tragen ihren Namen."],
       ["Eliud Kipchoge", "Kenia", "Lief einen Marathon unter zwei Stunden, außerhalb der Wertung."],
       ["Yuzuru Hanyu", "Japan", "Zweimal olympisches Gold im Eiskunstlauf."],
       ["Marit Bjørgen", "Norwegen", "Erfolgreichste Wintersportlerin der Olympiageschichte."],
       ["Sachin Tendulkar", "Indien", "Im Cricket zu Lebzeiten wie ein Gott verehrt."],
       ["Nadia Comăneci", "Rumänien", "Mit 14 Jahren die erste perfekte Wertung."],
       ["Ian Thorpe", "Australien", "Schwimmer mit den auffällig großen Füßen."]]'::jsonb,
     '[["Spanien", "Rafael Nadal träte dafür an, und der fehlt auf diesem Brett."],
       ["Äthiopien", "Haile Gebrselassie käme von dort, er steht nicht in dieser Liste."]]'::jsonb),

    ('sport', 'motorsport-serien', 'Motorsport-Serien',
     'Was kennzeichnet diese Rennserie?',
     'hard', 'Motorsport', 'https://de.wikipedia.org/wiki/Motorsport',
     '[["Formel 1", "Offene Räder und Cockpits", "Höchste Klasse des Formelsports."],
       ["MotoGP", "Prototyp-Motorräder", "Die Fahrer legen sich bis zum Ellenbogen in die Kurve."],
       ["Rallye-Weltmeisterschaft", "Sonderprüfungen auf Landstraßen", "Gefahren wird gegen die Uhr, nicht gegeneinander."],
       ["NASCAR", "Seriennahe Wagen auf Ovalen", "Vor allem in den USA populär."],
       ["IndyCar", "Indianapolis 500", "Ovale und Rundkurse in einer Meisterschaft."],
       ["Langstrecken-WM", "24 Stunden am Stück", "Mehrere Fahrer teilen sich ein Auto."],
       ["Rallye Dakar", "Wüstenetappen mit Navigation", "Führt heute durch Saudi-Arabien."],
       ["Formel E", "Rein elektrische Rennwagen", "Gefahren wird meist auf Stadtkursen."],
       ["DTM", "Tourenwagen mit Serienbezug", "Aus der Deutschen Tourenwagen-Meisterschaft hervorgegangen."],
       ["Dragster-Rennen", "Viertelmeile geradeaus", "Entschieden wird in unter vier Sekunden."],
       ["Trial", "Hindernisse ohne Fußaufsetzen", "Gewertet werden Fehlerpunkte, nicht die Zeit."],
       ["Speedway", "Bahnrennen ohne Bremsen", "Vier Fahrer, vier Runden, linksherum."]]'::jsonb,
     '[["Rennen nur bergauf", "Das Bergrennen fehlt auf diesem Brett."],
       ["Rundenrennen mit Karts", "Der Kartsport steht nicht in dieser Liste."]]'::jsonb),

    ('sport', 'fussball-regeln', 'Fußballregeln & Begriffe',
     'Was bedeutet der Begriff?',
     'hard', 'Fußballregeln',
     'https://de.wikipedia.org/wiki/Fu%C3%9Fballregeln',
     '[["Abseits", "Position beim Abspiel", "Entscheidend ist der Moment, in dem der Ball gespielt wird."],
       ["Strafstoß", "Foul im eigenen Strafraum", "Vom Punkt aus elf Metern ausgeführt."],
       ["Gelbe Karte", "Verwarnung", "Zwei davon ergeben den Platzverweis."],
       ["Rote Karte", "Platzverweis", "Die Mannschaft spielt in Unterzahl weiter."],
       ["Eckstoß", "Ball zuletzt vom Verteidiger", "Über die eigene Torlinie ins Aus."],
       ["Einwurf", "Ball über die Seitenlinie", "Beidhändig über den Kopf, mit Bodenkontakt."],
       ["Vorteil", "Weiterspielen trotz Foul", "Der Schiedsrichter lässt laufen, wenn es der Mannschaft nützt."],
       ["Nachspielzeit", "Ausgleich für Unterbrechungen", "Wechsel, Verletzungen und Jubel werden aufgeschlagen."],
       ["Videobeweis", "Überprüfung strittiger Szenen", "Nur bei Toren, Platzverweisen und Strafstößen."],
       ["Eigentor", "Treffer ins eigene Netz", "Wird dem Team gutgeschrieben, das angegriffen hat."],
       ["Elfmeterschießen", "Entscheidung nach Verlängerung", "Erst fünf Schützen, dann abwechselnd bis zur Entscheidung."],
       ["Handspiel", "Berührung mit dem Arm", "Der Torwart ist im eigenen Strafraum ausgenommen."]]'::jsonb,
     '[["Wechsel eines Spielers", "Die Auswechslung fehlt auf diesem Brett."],
       ["Anstoß nach einem Tor", "Er steht nicht in dieser Liste."]]'::jsonb),

    ('sport', 'derbys', 'Derbys & ihre Vereine',
     'Welche beiden Klubs treffen aufeinander?',
     'hard', 'Derby (Mannschaftssport)',
     'https://de.wikipedia.org/wiki/Derby_%28Mannschaftssport%29',
     '[["El Clásico", "Real und Barcelona", "Mehr als ein Spiel: auch ein politisches Thema."],
       ["Superclásico", "Boca und River", "Buenos Aires steht dabei still."],
       ["Old Firm", "Celtic und Rangers", "Glasgower Duell mit konfessionellem Hintergrund."],
       ["Revierderby", "Schalke und Dortmund", "Zwei Zechenstädte, wenige Kilometer auseinander."],
       ["Derby della Madonnina", "Inter und Milan", "Beide spielen im selben Stadion."],
       ["North West Derby", "Liverpool und United", "Die beiden Rekordmeister Englands."],
       ["Ewiges Derby", "Roter Stern und Partizan", "Das Belgrader Duell."],
       ["Le Classique", "Paris und Marseille", "Nord gegen Süd in Frankreich."],
       ["Derby d''Italia", "Juventus und Inter", "Die beiden nie abgestiegenen Klubs Italiens."],
       ["Interkontinentales Derby", "Galatasaray und Fenerbahçe", "Istanbul, europäische gegen asiatische Seite."],
       ["Kairoer Derby", "Al Ahly und Zamalek", "Eines der meistbesuchten Spiele Afrikas."],
       ["Nordderby", "Hamburg und Bremen", "Die beiden großen Nordklubs Deutschlands."]]'::jsonb,
     '[["Bayern und Nürnberg", "Das bayerische Derby fehlt auf diesem Brett."],
       ["Ajax und Feyenoord", "De Klassieker steht nicht in dieser Liste."]]'::jsonb),

    ('sport', 'extremsport', 'Extremsportarten',
     'Was macht man dabei?',
     'medium', 'Extremsport', 'https://de.wikipedia.org/wiki/Extremsport',
     '[["Base-Jumping", "Sprung von festen Objekten", "Von Antenne, Brücke, Klippe oder Gebäude."],
       ["Wingsuit-Fliegen", "Gleiten im Flügelanzug", "Stoffbahnen zwischen Armen und Beinen tragen."],
       ["Bungeejumping", "Sturz am Gummiseil", "Angeregt von einem Ritual auf Vanuatu."],
       ["Apnoetauchen", "Tauchen ohne Gerät", "Mit einem einzigen Atemzug in die Tiefe."],
       ["Kitesurfen", "Zug durch einen Lenkdrachen", "Der Wind zieht Board und Fahrer über das Wasser."],
       ["Gleitschirmfliegen", "Start am Hang", "Aufwinde tragen den Schirm nach oben."],
       ["Wildwasser-Rafting", "Schlauchboot im Stromschnellenwasser", "Eine Mannschaft paddelt im Takt."],
       ["Canyoning", "Schluchten abwärts", "Springen, Abseilen und Rutschen im Bachbett."],
       ["Slacklining", "Balancieren auf Gurtband", "In großer Höhe gespannt heißt es Highline."],
       ["Eisklettern", "Aufstieg an gefrorenen Wasserfällen", "Mit Steigeisen und zwei Eisgeräten."],
       ["Freeclimbing", "Klettern ohne technische Hilfsmittel", "Gesichert wird, aber nicht am Seil hochgezogen."],
       ["Skitourengehen", "Aufstieg mit Fellen", "Abfahrt abseits präparierter Pisten."]]'::jsonb,
     '[["Sprung aus dem Flugzeug am Schirm", "Das Fallschirmspringen fehlt auf diesem Brett."],
       ["Radfahren über steile Felsen", "Das Downhill steht nicht in dieser Liste."]]'::jsonb),

    ('sport', 'laufveranstaltungen-laender', 'Große Läufe & Länder',
     'In welchem Land findet der Lauf statt?',
     'medium', 'Marathonlauf',
     'https://de.wikipedia.org/wiki/Marathonlauf',
     '[["Boston-Marathon", "USA", "Ältester jährlicher Marathon der Welt."],
       ["Comrades Marathon", "Südafrika", "89 Kilometer zwischen Durban und Pietermaritzburg."],
       ["Marathon des Sables", "Marokko", "Sechs Etappen durch die Sahara, Gepäck inklusive."],
       ["Vasaloppet", "Schweden", "90 Kilometer Skilanglauf, seit 1922."],
       ["Birkebeinerrennet", "Norwegen", "Die Läufer tragen symbolisch ein Kindergewicht im Rucksack."],
       ["Engadin Skimarathon", "Schweiz", "Zehntausende laufen durch das Oberengadin."],
       ["Ultra-Trail du Mont-Blanc", "Frankreich", "170 Kilometer rund um das Massiv."],
       ["Berlin-Marathon", "Deutschland", "Flacher Kurs, auf dem viele Weltrekorde fielen."],
       ["Tokio-Marathon", "Japan", "Jüngster der großen Weltmarathons."],
       ["Great North Run", "England", "Größter Halbmarathon der Welt."],
       ["City2Surf", "Australien", "Von Sydney zum Bondi Beach."]]'::jsonb,
     '[["Niederlande", "Der Rotterdam-Marathon fehlt auf diesem Brett."],
       ["Kenia", "Kein Lauf in dieser Liste findet dort statt."]]'::jsonb),

    ('sport', 'spielzeiten-punkte', 'Spielzeiten & Zählweisen',
     'Wie lange oder bis wohin wird gespielt?',
     'hard', 'Sportart', 'https://de.wikipedia.org/wiki/Sportart',
     '[["Fußballspiel", "90 Minuten", "Zwei Halbzeiten plus Nachspielzeit."],
       ["Handballspiel", "60 Minuten", "Zwei Hälften zu je dreißig Minuten."],
       ["Eishockeydrittel", "20 Minuten", "Effektive Spielzeit, die Uhr wird angehalten."],
       ["Viertel im American Football", "15 Minuten", "Die reine Spielzeit ist dennoch kurz."],
       ["Rugby-Halbzeit", "40 Minuten", "Durchgespielt, ohne Auszeiten."],
       ["Boxrunde", "3 Minuten", "Dazwischen eine Minute Pause."],
       ["Volleyballsatz", "25 Punkte", "Mit zwei Punkten Vorsprung."],
       ["Badmintonsatz", "21 Punkte", "Ebenfalls mit zwei Punkten Abstand."],
       ["Tischtennissatz", "11 Punkte", "Aufschlagwechsel alle zwei Punkte."],
       ["Darts-Leg", "501 Punkte", "Heruntergespielt und mit einem Doppel beendet."],
       ["Tennisspiel", "15, 30, 40", "Die Zählweise stammt vermutlich vom Zifferblatt."],
       ["Basketballviertel", "10 Minuten", "In der NBA sind es zwölf."]]'::jsonb,
     '[["45 Minuten", "So lang ist eine Fußballhalbzeit, gefragt ist hier das ganze Spiel."],
       ["6 Punkte", "Keine Zählweise auf diesem Brett endet dort."]]'::jsonb),

    ('sport', 'segeln-wassersport', 'Segeln & Wassersport',
     'Was verbirgt sich dahinter?',
     'hard', 'Segeln', 'https://de.wikipedia.org/wiki/Segeln',
     '[["Vendée Globe", "Einhand ohne Zwischenstopp", "Ohne Hilfe und ohne Zwischenstopp."],
       ["The Ocean Race", "Etappenrennen um den Globus", "Mit Crew und Zwischenstopps in Häfen."],
       ["Rolex Sydney Hobart", "Hochseeregatta am zweiten Weihnachtstag", "Berüchtigt für die Bass-Straße."],
       ["Kieler Woche", "Größtes Segelfest der Welt", "Regatten und Volksfest zugleich."],
       ["Optimist", "Jolle für Kinder", "Fast alle Spitzensegler haben darin angefangen."],
       ["Laser", "Einhandjolle mit einem Segel", "Olympische Klasse, heute ILCA genannt."],
       ["Katamaran", "Zwei Rümpfe nebeneinander", "Weniger Wasserwiderstand, mehr Tempo."],
       ["Windsurfen", "Segel auf dem Brett", "Der Mast wird mit dem Gabelbaum geführt."],
       ["The Boat Race", "Oxford gegen Cambridge", "Achter gegen Achter auf der Themse."],
       ["Kanuslalom", "Tore im Wildwasser", "Rote Tore müssen stromaufwärts durchfahren werden."]]'::jsonb,
     '[["Rudern zu acht mit Steuermann", "Der Achter fehlt auf diesem Brett."],
       ["Wasserski hinter dem Boot", "Es steht nicht in dieser Liste."]]'::jsonb),

    ('sport', 'sportler-spitznamen', 'Sportler & ihre Beinamen',
     'Wer wurde so genannt?',
     'hard', 'Spitzname', 'https://de.wikipedia.org/wiki/Spitzname',
     '[["Der Kaiser", "Franz Beckenbauer", "Als Spieler und als Trainer Weltmeister."],
       ["Der Bomber der Nation", "Gerd Müller", "365 Bundesligatore in 427 Spielen."],
       ["The Greatest", "Muhammad Ali", "Er nannte sich selbst so, und behielt recht."],
       ["El Pibe de Oro", "Diego Maradona", "Der Goldjunge aus Buenos Aires."],
       ["Die schwarze Perle", "Pelé", "Dreimal Weltmeister mit Brasilien."],
       ["Der Kannibale", "Eddy Merckx", "Er ließ den Gegnern nichts übrig."],
       ["Der Zar der Lüfte", "Sergej Bubka", "35 Weltrekorde im Stabhochsprung."],
       ["King James", "LeBron James", "Schon als Schüler auf dem Titel eines Magazins."],
       ["Der fliegende Finne", "Paavo Nurmi", "Neun olympische Goldmedaillen im Laufen."],
       ["Der Titan", "Oliver Kahn", "Torwart, der 2002 fast im Alleingang ins WM-Finale hielt."],
       ["Der Terrier", "Berti Vogts", "Als Verteidiger klebte er an jedem Gegenspieler."],
       ["Der Thorpedo", "Ian Thorpe", "Wortspiel aus seinem Namen und dem Torpedo."]]'::jsonb,
     '[["Der fliegende Holländer", "So hieß Johan Cruyff, und der fehlt auf diesem Brett."],
       ["Air Jordan", "Michael Jordan steht nicht in dieser Liste."]]'::jsonb),

    ('sport', 'nationalstadien-laender', 'Nationalstadien & Länder',
     'In welchem Land steht das Stadion?',
     'medium', 'Stadion', 'https://de.wikipedia.org/wiki/Stadion',
     '[["Wembley-Stadion", "England", "Neubau von 2007 mit dem markanten Bogen."],
       ["Maracanã", "Brasilien", "Herz des brasilianischen Fußballs."],
       ["Estadio Azteca", "Mexiko", "Über 2200 Meter hoch gelegen."],
       ["Stade de France", "Frankreich", "Für die Weltmeisterschaft 1998 errichtet."],
       ["Stadio Olimpico", "Italien", "Im Foro Italico in Rom."],
       ["Estadio Santiago Bernabéu", "Spanien", "Rundum erneuert, mit einziehbarem Rasen."],
       ["Ernst-Happel-Stadion", "Österreich", "Benannt nach dem erfolgreichsten Trainer des Landes."],
       ["Puskás Aréna", "Ungarn", "Nach dem berühmtesten Spieler des Landes benannt."],
       ["Estádio da Luz", "Portugal", "Das Stadion des Lichts in Lissabon."],
       ["Johan Cruijff Arena", "Niederlande", "Erstes europäisches Stadion mit verschiebbarem Dach."],
       ["Luschniki-Stadion", "Russland", "Finalort der Weltmeisterschaft 2018."],
       ["Nissan Stadium", "Japan", "Hier fiel die Entscheidung der WM 2002."]]'::jsonb,
     '[["Argentinien", "Das Monumental stünde dort, und es fehlt auf dem Brett."],
       ["Südafrika", "Das Soccer City steht nicht in dieser Liste."]]'::jsonb),

    ('sport', 'golf-begriffe', 'Golfbegriffe',
     'Was bedeutet der Begriff?',
     'hard', 'Golf', 'https://de.wikipedia.org/wiki/Golf',
     '[["Par", "Sollschlagzahl eines Lochs", "Meist drei bis fünf Schläge."],
       ["Eagle", "Zwei unter Par", "Seltener als ein Birdie."],
       ["Bogey", "Einen über Par", "Der häufigste Fall für Freizeitspieler."],
       ["Albatros", "Drei unter Par", "Kommt in Profiturnieren kaum vor."],
       ["Hole in One", "Ein einziger Schlag", "Vom Abschlag direkt ins Loch."],
       ["Fairway", "Kurz gemähte Spielbahn", "Zwischen Abschlag und Grün."],
       ["Rough", "Hohes Gras am Rand", "Der Ball liegt schlecht und fliegt kürzer."],
       ["Bunker", "Sandhindernis", "Der Schläger darf den Sand vorher nicht berühren."],
       ["Green", "Fläche um das Loch", "Ganz kurz gemäht, für das Putten."],
       ["Handicap", "Vorgabe eines Spielers", "Macht Spieler unterschiedlicher Stärke vergleichbar."],
       ["Caddie", "Träger und Berater", "Kennt Schläge, Wind und Distanzen."],
       ["Tee", "Abschlagpunkt und Stift", "Der Ball liegt erhöht auf einem Stift."]]'::jsonb,
     '[["Sieger eines Major-Turniers", "Danach fragt keine Zeile auf diesem Brett."],
       ["Schlag über das Wasser hinweg", "Kein Begriff in dieser Liste meint das."]]'::jsonb),

    ('sport', 'radklassiker-laender', 'Radklassiker & Länder',
     'In welchem Land wird gefahren?',
     'hard', 'Radsport', 'https://de.wikipedia.org/wiki/Radsport',
     '[["Paris–Roubaix", "Frankreich", "Die Hölle des Nordens, über Kopfsteinpflaster."],
       ["Flandern-Rundfahrt", "Belgien", "Steile, gepflasterte Anstiege in kurzer Folge."],
       ["Mailand–Sanremo", "Italien", "Längster Klassiker, fast 300 Kilometer."],
       ["Amstel Gold Race", "Niederlande", "Ständiges Auf und Ab in Limburg."],
       ["Clásica San Sebastián", "Spanien", "Baskisches Eintagesrennen im Hochsommer."],
       ["Tour de Suisse", "Schweiz", "Generalprobe für die Tour de France."],
       ["Eschborn-Frankfurt", "Deutschland", "Traditionsrennen am ersten Mai."],
       ["Tour Down Under", "Australien", "Eröffnet die Saison im Januar."],
       ["Tour of Britain", "Vereinigtes Königreich", "Etappenrennen quer über die Insel."],
       ["Tour de Pologne", "Polen", "Rundfahrt mit Bergankünften in der Tatra."],
       ["Tour of Oman", "Oman", "Frühjahrsrennen mit Anstieg zum Green Mountain."]]'::jsonb,
     '[["Österreich", "Die Österreich-Rundfahrt fehlt auf diesem Brett."],
       ["Norwegen", "Kein Rennen in dieser Liste wird dort gefahren."]]'::jsonb),

    ('sport', 'sportgeschichte-erste-male', 'Premieren des Sports',
     'Wann fand das zum ersten Mal statt?',
     'hard', 'Sportgeschichte',
     'https://de.wikipedia.org/wiki/Sportgeschichte',
     '[["Erste Tour de France", "1903", "Sechs Etappen, teils über Nacht gefahren."],
       ["Erste Olympische Winterspiele", "1924", "In Chamonix, zunächst als Wintersportwoche."],
       ["Erste Fußball-Weltmeisterschaft", "1930", "Uruguay gewann im eigenen Land."],
       ["Erste Formel-1-Weltmeisterschaft", "1950", "Auftakt in Silverstone."],
       ["Erste Fußball-Europameisterschaft", "1960", "Nur vier Mannschaften in der Endrunde."],
       ["Erster Super Bowl", "1967", "Damals noch AFL-NFL World Championship Game."],
       ["Erste Frauen-Fußball-WM", "1991", "In China, mit zwölf Mannschaften."],
       ["Erste Leichtathletik-WM", "1983", "In Helsinki, zuvor gab es nur Olympia."],
       ["Erstes Wimbledonturnier", "1877", "Nur Herreneinzel, 22 Teilnehmer."],
       ["Erster Marathon der Neuzeit", "1896", "Bei den ersten Spielen in Athen."]]'::jsonb,
     '[["1972", "Kein Ereignis auf diesem Brett fand zum ersten Mal in diesem Jahr statt."],
       ["1904", "Die zweiten Spiele der Neuzeit, aber keine Premiere in dieser Liste."]]'::jsonb),

    ('sport', 'turngeraete', 'Turngeräte & Merkmale',
     'Woran wird hier geturnt?',
     'medium', 'Turnen', 'https://de.wikipedia.org/wiki/Turnen',
     '[["Reck", "Waagerechte Stange", "Riesenfelgen und Flugelemente."],
       ["Barren", "Zwei parallele Holme", "Männerdisziplin mit Stütz- und Schwungteilen."],
       ["Stufenbarren", "Zwei Holme in Höhen", "Frauendisziplin mit ständigen Wechseln."],
       ["Ringe", "Zwei hängende Griffe", "Kraftteile wie das Kreuzhängen."],
       ["Pauschenpferd", "Körper kreist über Griffen", "Die Beine dürfen das Gerät nicht berühren."],
       ["Sprungtisch", "Anlauf und Sprungbrett", "Ersetzte das frühere Sprungpferd."],
       ["Schwebebalken", "Zehn Zentimeter Breite", "In 1,25 Metern Höhe."],
       ["Boden", "Federnde Fläche", "Zwölf mal zwölf Meter, bei Frauen mit Musik."],
       ["Trampolin", "Sprungtuch mit Federn", "Seit 2000 olympische Disziplin."],
       ["Rhönrad", "Zwei verbundene Reifen", "Der Turner steht im Inneren."]]'::jsonb,
     '[["Kletterstange an der Wand", "Sie ist kein Turngerät auf diesem Brett."],
       ["Sprungseil", "Es steht nicht in dieser Liste."]]'::jsonb),

    ('sport', 'boxgewichtsklassen', 'Gewichtsklassen im Boxen',
     'Welche Grenze gilt für die Klasse?',
     'hard', 'Boxen', 'https://de.wikipedia.org/wiki/Boxen',
     '[["Schwergewicht", "Über 90,7 Kilogramm", "Nach oben offen."],
       ["Cruisergewicht", "Bis 90,7 Kilogramm", "1979 eingeführt, um die Lücke zu schließen."],
       ["Halbschwergewicht", "Bis 79,4 Kilogramm", "Klassische Klasse mit langer Geschichte."],
       ["Supermittelgewicht", "Bis 76,2 Kilogramm", "Erst in den 1980er Jahren eingerichtet."],
       ["Mittelgewicht", "Bis 72,6 Kilogramm", "Gilt als technischste Klasse."],
       ["Weltergewicht", "Bis 66,7 Kilogramm", "Viele Legenden boxten hier."],
       ["Leichtgewicht", "Bis 61,2 Kilogramm", "Schnelle Kämpfe mit hoher Schlagzahl."],
       ["Federgewicht", "Bis 57,2 Kilogramm", "Der Name steht sprichwörtlich für leicht."],
       ["Bantamgewicht", "Bis 53,5 Kilogramm", "Benannt nach einer Hühnerrasse."],
       ["Fliegengewicht", "Bis 50,8 Kilogramm", "Leichteste klassische Klasse."]]'::jsonb,
     '[["Bis 100 Kilogramm", "Keine Klasse auf diesem Brett hat diese Grenze."],
       ["Bis 48 Kilogramm", "Das Strohgewicht fehlt in dieser Liste."]]'::jsonb),

    ('sport', 'eishockey-begriffe', 'Eishockeybegriffe',
     'Was bedeutet der Begriff?',
     'hard', 'Eishockey', 'https://de.wikipedia.org/wiki/Eishockey',
     '[["Bully", "Anspiel zwischen zwei Spielern", "Der Puck wird zwischen die Schläger geworfen."],
       ["Powerplay", "Spiel in Überzahl", "Nach einer Strafe gegen den Gegner."],
       ["Icing", "Unerlaubter Weitschuss", "Von der eigenen Hälfte über die gegnerische Torlinie."],
       ["Penalty", "Strafschuss allein aufs Tor", "Nach einer Regelwidrigkeit gegen eine klare Chance."],
       ["Body-Check", "Erlaubter Körperangriff", "Nur gegen den puckführenden Spieler."],
       ["Strafbank", "Zwei Minuten außerhalb", "Bei schweren Vergehen auch fünf oder zehn."],
       ["Empty Net", "Tor ohne Torwart", "Am Ende für einen zusätzlichen Feldspieler geräumt."],
       ["Slapshot", "Schlagschuss mit Ausholen", "Der schnellste, aber ungenaueste Schuss."],
       ["Blaue Linie", "Grenze der Angriffszone", "Wer sie zu früh überquert, steht im Abseits."],
       ["Shutout", "Spiel ohne Gegentor", "Wird dem Torwart gutgeschrieben."]]'::jsonb,
     '[["Wechsel bei laufendem Spiel", "Der fliegende Wechsel fehlt auf diesem Brett."],
       ["Verlängerung nach Unentschieden", "Sie steht nicht in dieser Liste."]]'::jsonb),

    ('sport', 'baelle-sportarten', 'Bälle & Sportarten',
     'Zu welcher Sportart gehört der Ball?',
     'medium', 'Ball', 'https://de.wikipedia.org/wiki/Ball',
     '[["Ball mit Dellen im Mantel", "Golf", "Die Dellen verlängern den Flug erheblich."],
       ["Gelber Filzball", "Tennis", "Gelb, seit das Fernsehen ihn sichtbar machen musste."],
       ["Ball aus 32 Feldern", "Fußball", "Klassisch aus Fünf- und Sechsecken genäht."],
       ["Genoppter oranger Ball", "Basketball", "Die Noppen sorgen für Griff beim Dribbeln."],
       ["Ovaler Ball mit Naht", "Rugby", "Springt absichtlich unberechenbar auf."],
       ["Spitz zulaufender Lederball", "American Football", "Für den Spiralwurf geformt."],
       ["Kleiner Ball mit roter Naht", "Baseball", "Die Naht macht die Wurfvarianten möglich."],
       ["Hohle Zelluloidkugel", "Tischtennis", "Heute meist aus Kunststoff, 40 Millimeter groß."],
       ["Klebriger Handball", "Handball", "Harz sorgt für den Halt in einer Hand."],
       ["Ball mit Korkkern", "Cricket", "Hart genug, dass Helme Pflicht wurden."],
       ["Griffiger Ball fürs Wasser", "Wasserball", "Muss auch nass einhändig zu halten sein."],
       ["Leichter Ball für den Innenraum", "Volleyball", "Wird nur gespielt, nie gefangen."]]'::jsonb,
     '[["Sehr harter Ball mit Löchern zum Greifen", "Die Bowlingkugel fehlt auf diesem Brett."],
       ["Kleiner Ball mit Federkranz", "Der Federball steht nicht in dieser Liste."]]'::jsonb),

    ('sport', 'sportverletzungen', 'Verletzungen & Körperteile',
     'Wo tritt die Verletzung auf?',
     'medium', 'Sportverletzung',
     'https://de.wikipedia.org/wiki/Sportverletzung',
     '[["Kreuzbandriss", "Knie", "Klassische Verletzung bei Drehbewegungen mit fixiertem Fuß."],
       ["Achillessehnenriss", "Ferse", "Oft mit einem hörbaren Knall verbunden."],
       ["Tennisarm", "Ellenbogen", "Überlastung der Sehnenansätze am Außenknochen."],
       ["Schulterluxation", "Schulter", "Der Oberarmkopf springt aus der Pfanne."],
       ["Ermüdungsbruch", "Mittelfuß", "Entsteht ohne Sturz, allein durch Dauerbelastung."],
       ["Schleudertrauma", "Halswirbelsäule", "Peitschenartige Bewegung des Kopfes."],
       ["Muskelfaserriss", "Oberschenkel", "Häufig beim Antritt aus dem Stand."],
       ["Gehirnerschütterung", "Kopf", "Im Kampfsport und beim Football besonders beachtet."],
       ["Bandscheibenvorfall", "Lendenwirbelsäule", "Oft bei Gewichthebern und Ruderern."],
       ["Karpaltunnelsyndrom", "Handgelenk", "Der Nerv wird im Kanal eingeengt."]]'::jsonb,
     '[["Nasenbeinbruch", "Er trifft die Nase, und die fehlt auf diesem Brett."],
       ["Rippenprellung", "Sie steht nicht in dieser Liste."]]'::jsonb),

    ('sport', 'skisprungschanzen', 'Skisprungschanzen & Orte',
     'Wo steht die Schanze?',
     'hard', 'Skisprungschanze',
     'https://de.wikipedia.org/wiki/Skisprungschanze',
     '[["Bergiselschanze", "Innsbruck", "Über der Stadt, mit einem Turm von Zaha Hadid."],
       ["Schattenbergschanze", "Oberstdorf", "Auftakt der Vierschanzentournee."],
       ["Große Olympiaschanze", "Garmisch-Partenkirchen", "Springen am Neujahrstag."],
       ["Paul-Ausserleitner-Schanze", "Bischofshofen", "Letzte Station der Tournee."],
       ["Holmenkollbakken", "Oslo", "Traditionsreichste Schanze Norwegens."],
       ["Vikersundbakken", "Vikersund", "Hier fielen mehrere Weltrekorde im Skifliegen."],
       ["Letalnica", "Planica", "Skiflugschanze in den slowenischen Alpen."],
       ["Mühlenkopfschanze", "Willingen", "Größte Großschanze der Welt nach Größe des Hügels."],
       ["Okurayama", "Sapporo", "Schauplatz der Winterspiele 1972."],
       ["Kulm", "Bad Mitterndorf", "Österreichische Skiflugschanze in der Steiermark."],
       ["Wielka Krokiew", "Zakopane", "Vor bis zu 50000 Zuschauern."]]'::jsonb,
     '[["Klingenthal", "Die Vogtlandschanze steht dort, und sie fehlt auf dem Brett."],
       ["Lahti", "Die finnische Schanze kommt in dieser Liste nicht vor."]]'::jsonb),

    ('sport', 'sportpionierinnen', 'Pionierinnen des Sports',
     'Wofür steht ihr Name?',
     'hard', 'Sportgeschichte',
     'https://de.wikipedia.org/wiki/Sportgeschichte',
     '[["Alice Milliat", "Eigene Frauenspiele", "Erzwang damit die Aufnahme der Frauen bei Olympia."],
       ["Kathrine Switzer", "Erste Frau im Boston-Marathon", "Ein Funktionär versuchte 1967, sie von der Strecke zu ziehen."],
       ["Billie Jean King", "Kampf der Geschlechter", "Sie schlug 1973 Bobby Riggs vor Millionenpublikum."],
       ["Junko Tabei", "Erste Everest-Besteigerin", "Erreichte den Gipfel 1975."],
       ["Nawal El Moutawakel", "Erste muslimische Olympiasiegerin", "Siegte 1984 über 400 Meter Hürden."],
       ["Marta Vieira da Silva", "Rekordtorschützin der WM", "Traf bei fünf Turnieren hintereinander."],
       ["Danica Patrick", "Erste IndyCar-Siegerin", "Gewann 2008 in Japan."],
       ["Ellen MacArthur", "Schnellste Weltumseglung allein", "2005 in 71 Tagen um den Globus."],
       ["Wilma Rudolph", "Dreimal Gold nach Kinderlähmung", "Siegte 1960 in Rom über Sprint und Staffel."],
       ["Fanny Blankers-Koen", "Vier Goldmedaillen als Mutter", "1948 in London, gegen alle Erwartungen."]]'::jsonb,
     '[["Erste Frau im Formel-1-Rennen", "Das war Maria Teresa de Filippis, die hier fehlt."],
       ["Steffi Graf", "Der Golden Slam von 1988 steht nicht auf diesem Brett."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

-- The answers that belong to no category. Numbered after the pairs so the two
-- sets never collide on `position`, though nothing reads it for a fake: the
-- pool is shuffled before a player sees it, and the review lists fakes on their
-- own rather than in board order.
fakes as (
    select q.id                                         as quiz_id,
           k.value ->> 0                                as label,
           k.value ->> 1                                as explanation,
           (jsonb_array_length(sp.pairs) + k.ord)::int  as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.fakes) with ordinality k(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
),

paired as (
    insert into items (quiz_id, category_id, label, position, explanation)
    select f.quiz_id, c.id, f.answer, f.position, f.explanation
      from flat f
      join new_categories c
        on c.quiz_id = f.quiz_id
       and c.label = f.label
    returning id
)

-- Same table, `category_id` left null. Both inserts run in the one statement,
-- so `items_quiz_id_label_key` still sees the pairs above: a fake written to
-- repeat an answer already on its own board fails the file rather than becoming
-- a second row nobody can tell apart.
insert into items (quiz_id, category_id, label, position, explanation)
select k.quiz_id, null, k.label, k.position, k.explanation
  from fakes k;
