-- Sport, leichte Fragen. Zwanzig Fragen, alle 'easy'.
--
-- Gefragt wird nach dem, was man vom Schulhof, aus dem Schwimmbad und vom
-- Fernsehsofa kennt, nicht nach Verbandssitzen und Gewichtsklassen.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs) as (
    values

    ('sport', 'leicht-baelle', 'Bälle & Sportarten',
     'In welcher Sportart spielt man damit?',
     'easy', 'Ball', 'https://de.wikipedia.org/wiki/Ball',
     '[["Runder Ball mit schwarzen und weißen Feldern", "Fußball", "Der klassische Ball auf jedem Bolzplatz."],
       ["Oranger Ball mit Noppen", "Basketball", "Er wird geprellt, nicht getragen."],
       ["Kleiner gelber Filzball", "Tennis", "Er wird über ein Netz geschlagen."],
       ["Kleiner weißer Ball mit Dellen", "Golf", "Er fliegt dadurch weiter."],
       ["Ovaler Ball mit Nähten", "Rugby", "Er springt unberechenbar auf."],
       ["Sehr leichter Hohlball", "Tischtennis", "Nur wenige Gramm schwer."],
       ["Ball, der über ein hohes Netz geschlagen wird", "Volleyball", "Er darf nie gefangen werden."],
       ["Ball, der mit Harz gehalten wird", "Handball", "Er passt in eine Hand."],
       ["Federleichtes Ding mit Kranz", "Badminton", "Kein Ball, sondern ein Federball."],
       ["Harte Scheibe aus Gummi", "Eishockey", "Sie wird vor dem Spiel gekühlt."],
       ["Ball mit roter Naht", "Baseball", "Der Werfer nutzt die Naht für Effet."],
       ["Ball, der im Wasser gespielt wird", "Wasserball", "Er muss auch nass greifbar sein."]]'::jsonb),

    ('sport', 'leicht-sportarten-orte', 'Wo wird gespielt?',
     'Wo findet die Sportart statt?',
     'easy', 'Sportstätte', 'https://de.wikipedia.org/wiki/Sportst%C3%A4tte',
     '[["Fußball", "Auf dem Rasen", "Elf gegen elf."],
       ["Schwimmen", "Im Becken", "Fünfzig Meter im olympischen Becken."],
       ["Eishockey", "Auf dem Eis", "Mit Schlittschuhen."],
       ["Skifahren", "Auf der Piste", "Bergab, mit Liften hinauf."],
       ["Turnen", "In der Halle", "An Geräten und auf der Matte."],
       ["Golf", "Auf dem Platz", "Achtzehn Löcher gehören zur Runde."],
       ["Klettern", "An der Wand", "Drinnen an Griffen, draußen am Fels."],
       ["Segeln", "Auf dem Wasser", "Der Wind treibt das Boot."],
       ["Radrennen", "Auf der Straße", "Oder auf der überhöhten Bahn."],
       ["Reiten", "Auf dem Reitplatz", "Dressur oder Springen."],
       ["Tennis", "Auf dem Court", "Sand, Rasen oder Hartplatz."],
       ["Boxen", "Im Ring", "Zwischen den Seilen."]]'::jsonb),

    ('sport', 'leicht-ausruestung', 'Ausrüstung',
     'Wofür braucht man das?',
     'easy', 'Sportgerät',
     'https://de.wikipedia.org/wiki/Sportger%C3%A4t',
     '[["Helm", "Schutz des Kopfes", "Beim Radfahren und Skifahren."],
       ["Schwimmbrille", "Klare Sicht unter Wasser", "Sie hält Chlorwasser fern."],
       ["Schienbeinschoner", "Schutz beim Fußball", "Vorgeschrieben im Spiel."],
       ["Turnschuhe", "Halt in der Halle", "Mit heller Sohle, die nicht abfärbt."],
       ["Skistöcke", "Rhythmus und Abstoßen", "Die Schlaufe hält sie am Handgelenk."],
       ["Handschuhe des Torwarts", "Besserer Griff am Ball", "Das Latex haftet leicht angefeuchtet."],
       ["Startblock", "Fester Abdruck beim Sprint", "Auch im Schwimmbecken."],
       ["Trillerpfeife", "Signal des Schiedsrichters", "Sie unterbricht das Spiel."],
       ["Stoppuhr", "Zeit messen", "Auf Hundertstel genau."],
       ["Sprungmatte", "Weiche Landung", "Beim Hochsprung und Turnen."],
       ["Schwimmflügel", "Auftrieb für Kinder", "Zum Üben im flachen Wasser."],
       ["Trikot mit Nummer", "Spieler erkennen", "Jede Nummer nur einmal pro Team."]]'::jsonb),

    ('sport', 'leicht-regeln', 'Einfache Regeln',
     'Was bedeutet das?',
     'easy', 'Sport', 'https://de.wikipedia.org/wiki/Sport',
     '[["Gelbe Karte im Fußball", "Verwarnung", "Zwei davon bedeuten Feierabend."],
       ["Rote Karte im Fußball", "Platzverweis", "Das Team spielt in Unterzahl weiter."],
       ["Anpfiff", "Das Spiel beginnt", "Meist nach dem Münzwurf."],
       ["Abpfiff", "Das Spiel ist vorbei", "Auch nach der Nachspielzeit."],
       ["Halbzeit", "Pause in der Mitte", "Danach wird die Seite gewechselt."],
       ["Foul", "Regelwidriges Vergehen", "Es gibt Freistoß oder Freiwurf."],
       ["Aus", "Ball außerhalb des Feldes", "Er kommt von der Seitenlinie zurück."],
       ["Unentschieden", "Beide gleich viele Punkte", "Im Pokal folgt die Verlängerung."],
       ["Verlängerung", "Zusatzzeit bei Gleichstand", "Zweimal fünfzehn Minuten im Fußball."],
       ["Elfmeterschießen", "Entscheidung vom Punkt", "Wenn auch die Verlängerung nichts bringt."]]'::jsonb),

    ('sport', 'leicht-olympia', 'Olympische Spiele',
     'Was gehört zu Olympia?',
     'easy', 'Olympische Spiele',
     'https://de.wikipedia.org/wiki/Olympische_Spiele',
     '[["Fünf farbige Ringe", "Das Symbol der Spiele", "Sie stehen für die Kontinente."],
       ["Feuer, das brennt", "Olympisches Feuer", "Entzündet in Olympia in Griechenland."],
       ["Lauf mit der Fackel", "Fackellauf", "Bis zur Eröffnungsfeier."],
       ["Erster Platz", "Goldmedaille", "Sie ist vergoldetes Silber."],
       ["Zweiter Platz", "Silbermedaille", "Der knappste Rang von allen."],
       ["Dritter Platz", "Bronzemedaille", "Auch sie steht auf dem Podest."],
       ["Abstand zwischen zwei Spielen", "Vier Jahre", "Sommer und Winter versetzt."],
       ["Spiele im Schnee und auf Eis", "Winterspiele", "Seit 1924 ausgetragen."],
       ["Spiele für Menschen mit Behinderung", "Paralympics", "Kurz nach den Olympischen Spielen."],
       ["Land, das immer zuerst einmarschiert", "Griechenland", "Als Ursprungsland der Spiele."]]'::jsonb),

    ('sport', 'leicht-fussball', 'Fußball',
     'Wer oder was ist das?',
     'easy', 'Fußball', 'https://de.wikipedia.org/wiki/Fu%C3%9Fball',
     '[["Spieler, der die Bälle hält", "Torwart", "Nur er darf im Strafraum die Hände nutzen."],
       ["Spieler, der Tore schießen soll", "Stürmer", "Er steht am weitesten vorn."],
       ["Spieler, der Tore verhindern soll", "Verteidiger", "Er räumt vor dem eigenen Tor auf."],
       ["Wer das Spiel leitet", "Schiedsrichter", "Er entscheidet allein auf dem Platz."],
       ["Trainer an der Seitenlinie", "Coach", "Er wechselt Spieler ein und aus."],
       ["Zuschauer, die anfeuern", "Fans", "Sie singen die ganze Partie."],
       ["Wettbewerb aller Bundesligavereine", "Bundesliga", "Achtzehn Vereine, vierunddreißig Spieltage."],
       ["Größtes Turnier der Nationalteams", "Weltmeisterschaft", "Alle vier Jahre."],
       ["Drei Tore eines Spielers in einem Spiel", "Hattrick", "Klassisch sogar in einer Halbzeit."],
       ["Tor ins eigene Netz", "Eigentor", "Es zählt für den Gegner."],
       ["Elf Meter vor dem Tor", "Elfmeter", "Nur Torwart gegen Schütze."],
       ["Runder Pokal für den Meister", "Meisterschale", "In Deutschland seit 1949."]]'::jsonb),

    ('sport', 'leicht-schwimmen', 'Im Schwimmbad',
     'Wie heißt das?',
     'easy', 'Schwimmsport',
     'https://de.wikipedia.org/wiki/Schwimmsport',
     '[["Schwimmen auf dem Bauch mit Kraulzug", "Kraulen", "Die schnellste Schwimmart."],
       ["Schwimmen auf dem Rücken", "Rückenschwimmen", "Der Blick geht nach oben."],
       ["Beine wie ein Frosch", "Brustschwimmen", "Die häufigste Art im Freibad."],
       ["Beide Arme gleichzeitig nach vorn", "Schmetterling", "Die anstrengendste Schwimmart."],
       ["Sprung vom Beckenrand ins Wasser", "Startsprung", "Flach und weit."],
       ["Wende an der Beckenwand", "Rollwende", "Man dreht sich unter Wasser ab."],
       ["Erstes Schwimmabzeichen für Kinder", "Seepferdchen", "Fünfundzwanzig Meter am Stück."],
       ["Person, die am Becken aufpasst", "Bademeister", "Er greift bei Gefahr sofort ein."],
       ["Turm zum Springen", "Sprungturm", "Ein, drei, fünf oder zehn Meter."],
       ["Leine, die die Bahnen trennt", "Bahnleine", "Sie bricht auch die Wellen."]]'::jsonb),

    ('sport', 'leicht-wintersport', 'Wintersport',
     'Wie heißt die Sportart?',
     'easy', 'Wintersport', 'https://de.wikipedia.org/wiki/Wintersport',
     '[["Auf zwei Brettern den Berg hinunter", "Skifahren", "Der Schwung geht über die Kanten."],
       ["Auf einem Brett den Berg hinunter", "Snowboarden", "Beide Füße sind fest gebunden."],
       ["Von der Schanze weit fliegen", "Skispringen", "Weite und Haltung zählen."],
       ["Laufen auf schmalen Skiern in der Loipe", "Langlauf", "Klassisch oder im Skating-Schritt."],
       ["Laufen und Schießen zusammen", "Biathlon", "Jeder Fehlschuss kostet."],
       ["Mit Kufen über das Eis gleiten", "Eislaufen", "Auf dem See oder in der Halle."],
       ["Sprünge und Pirouetten auf dem Eis", "Eiskunstlauf", "Zur Musik und mit Wertung."],
       ["Steine über das Eis schieben", "Curling", "Zwei Spieler wischen davor."],
       ["Mit dem Schlitten kopfüber ins Tal", "Skeleton", "Gesteuert nur mit dem Körper."],
       ["Zu viert im Schlitten durch den Eiskanal", "Bobfahren", "Der Start entscheidet oft."]]'::jsonb),

    ('sport', 'leicht-sportarten-erkennen', 'Sportarten erkennen',
     'Welche Sportart ist gemeint?',
     'easy', 'Sportart', 'https://de.wikipedia.org/wiki/Sportart',
     '[["Ball in den Korb werfen", "Basketball", "Der Korb hängt in 3,05 Metern."],
       ["Über eine Latte springen", "Hochsprung", "Rücklings seit Fosbury."],
       ["So weit wie möglich in die Grube springen", "Weitsprung", "Gemessen wird der hinterste Abdruck."],
       ["Eine Kugel möglichst weit stoßen", "Kugelstoßen", "Gestoßen, nicht geworfen."],
       ["Auf einem Pferd über Hindernisse", "Springreiten", "Fehler kosten Punkte."],
       ["Mit einem Boot ohne Motor", "Rudern", "Die Ruderer sitzen rückwärts."],
       ["Über Hindernisse laufen", "Hürdenlauf", "Sie kippen um, wenn man sie trifft."],
       ["Mit dem Degen kämpfen", "Fechten", "Treffer werden elektrisch gemessen."],
       ["Möglichst schnell 100 Meter laufen", "Sprint", "Unter zehn Sekunden bei den Besten."],
       ["Auf einem Brett auf Wellen stehen", "Wellenreiten", "Aus Hawaii in die Welt gekommen."],
       ["Mit Pfeil und Bogen ins Ziel", "Bogenschießen", "Die Zehn liegt in der Mitte."],
       ["Gegner auf die Matte bringen", "Ringen", "Beide Schultern müssen den Boden berühren."]]'::jsonb),

    ('sport', 'leicht-koerper-sport', 'Sport & Körper',
     'Was passiert dabei?',
     'easy', 'Sport', 'https://de.wikipedia.org/wiki/Sport',
     '[["Beim schnellen Laufen", "Der Puls steigt", "Das Herz pumpt mehr Blut."],
       ["Vor dem Sport", "Aufwärmen", "Es schützt vor Verletzungen."],
       ["Nach dem Sport", "Dehnen und auslaufen", "Der Körper kommt langsam zur Ruhe."],
       ["Bei großer Anstrengung", "Man kommt ins Schwitzen", "So kühlt sich der Körper."],
       ["Am Tag nach ungewohntem Training", "Muskelkater", "Kleinste Risse in den Fasern."],
       ["Wenn man zu wenig trinkt", "Leistung lässt nach", "Schon zwei Prozent Verlust sind spürbar."],
       ["Regelmäßiges Training", "Ausdauer wächst", "Das Herz wird kräftiger."],
       ["Beim Krafttraining", "Muskeln wachsen", "In den Pausen, nicht beim Heben."],
       ["Bei einem Sturz auf das Gelenk", "Verstauchung möglich", "Kühlen und hochlegen."],
       ["Zu wenig Schlaf vor dem Wettkampf", "Reaktion wird langsamer", "Schlaf ist Teil des Trainings."]]'::jsonb),

    ('sport', 'leicht-mannschaft-zahl', 'Wie viele spielen?',
     'Wie viele Spieler hat ein Team auf dem Feld?',
     'easy', 'Mannschaftssport',
     'https://de.wikipedia.org/wiki/Mannschaftssport',
     '[["Fußball", "11", "Ein Torwart und zehn Feldspieler."],
       ["Basketball", "5", "Fünf gegen fünf."],
       ["Handball", "7", "Sechs Feldspieler und ein Torwart."],
       ["Volleyball", "6", "Nach jedem Punktgewinn wird gedreht."],
       ["Beachvolleyball", "2", "Ohne Auswechslung."],
       ["Baseball", "9", "Neun Positionen im Feld."],
       ["Rugby Union", "15", "Acht Stürmer, sieben Hintermannschaft."],
       ["Tennis-Einzel", "1", "Einer gegen einen."],
       ["Ruder-Achter", "8", "Dazu der Steuermann."],
       ["3x3-Basketball", "3", "Auf einem halben Feld gespielt."],
       ["Viererbob", "4", "Pilot, zwei Anschieber, ein Bremser."],
       ["Rugby League", "13", "Zwei Spieler weniger als Rugby Union."]]'::jsonb),

    ('sport', 'leicht-turnier', 'Beim Turnier',
     'Was bedeutet das?',
     'easy', 'Wettkampf', 'https://de.wikipedia.org/wiki/Wettkampf',
     '[["Erste Runde mit allen Teams", "Vorrunde", "Danach folgt die Endrunde."],
       ["Spiel um den Einzug ins Halbfinale", "Viertelfinale", "Acht Teams sind noch dabei."],
       ["Vorletztes Spiel eines Turniers", "Halbfinale", "Der Sieger spielt um den Titel."],
       ["Letztes Spiel eines Turniers", "Finale", "Es entscheidet über den Titel."],
       ["Spiel um Platz drei", "Kleines Finale", "Für die Verlierer der Halbfinals."],
       ["Ausscheiden nach einer Niederlage", "K.-o.-System", "Kein zweiter Versuch."],
       ["Jeder spielt gegen jeden", "Gruppenphase", "Punkte entscheiden über das Weiterkommen."],
       ["Ehrenrunde nach dem Sieg", "Ehrenrunde", "Mit dem Pokal in der Hand."],
       ["Erhöhung für die ersten drei", "Siegerpodest", "Der Sieger steht in der Mitte."],
       ["Wer als Erster ins Ziel kommt", "Sieger", "Manchmal entscheidet das Zielfoto."]]'::jsonb),

    ('sport', 'leicht-tiere-sport', 'Sport mit Tieren',
     'Welches Tier gehört dazu?',
     'easy', 'Sportart', 'https://de.wikipedia.org/wiki/Sportart',
     '[["Springreiten", "Pferd", "Es überwindet Hindernisse mit Reiter."],
       ["Schlittenrennen im Schnee", "Hund", "Meist Huskys im Gespann."],
       ["Galopprennen auf der Bahn", "Rennpferd", "Sehr leichte Jockeys reiten es."],
       ["Brieftaubenwettflug", "Taube", "Sie findet über Hunderte Kilometer heim."],
       ["Falknerei", "Greifvogel", "Ein altes Vorrecht des Adels."],
       ["Agility-Parcours", "Hütehund", "Er läuft durch Tunnel und über Wippen."],
       ["Kamelrennen in der Wüste", "Kamel", "Vor allem auf der Arabischen Halbinsel."],
       ["Ochsengespann beim Ziehen", "Ochse", "Ein Kräftemessen auf dem Land."],
       ["Polo", "Poloponys", "Vier Reiter je Mannschaft."],
       ["Voltigieren", "Longiertes Pferd", "Turnen auf dem galoppierenden Pferd."]]'::jsonb),

    ('sport', 'leicht-sport-woerter', 'Wörter aus dem Sport',
     'Was bedeutet das Wort?',
     'easy', 'Sportjargon',
     'https://de.wikipedia.org/wiki/Sportjargon',
     '[["Rekord", "Bestleistung", "Sie kann jederzeit überboten werden."],
       ["Training", "Regelmäßiges Üben", "Ohne es keine Leistung."],
       ["Aufwärmen", "Vorbereitung der Muskeln", "Erhöht die Körpertemperatur."],
       ["Auswechslung", "Spielerwechsel", "Der Erschöpfte geht vom Platz."],
       ["Abseits", "Position beim Abspiel", "Nur im Fußball und Eishockey."],
       ["Doping", "Verbotene Leistungssteigerung", "Es wird durch Tests verfolgt."],
       ["Fairplay", "Faires Verhalten", "Auch ohne Schiedsrichter gilt es."],
       ["Amateur", "Sport ohne Bezahlung", "Der Gegensatz zum Profi."],
       ["Profi", "Sport als Beruf", "Er lebt von seinem Sport."],
       ["Turnier", "Wettkampf mit mehreren Runden", "Am Ende steht ein Sieger."],
       ["Titelverteidiger", "Sieger des Vorjahres", "Er tritt erneut an."],
       ["Aufstieg", "Sprung in die Oberliga", "Am Ende der Saison."]]'::jsonb),

    ('sport', 'leicht-laufen', 'Laufen & Leichtathletik',
     'Was ist gemeint?',
     'easy', 'Leichtathletik',
     'https://de.wikipedia.org/wiki/Leichtathletik',
     '[["Sehr kurze, sehr schnelle Strecke", "Sprint", "Hundert oder zweihundert Meter."],
       ["Lauf über 42 Kilometer", "Marathon", "Benannt nach einem Ort in Griechenland."],
       ["Vier Läufer nacheinander", "Staffel", "Der Stab muss in der Zone übergeben werden."],
       ["Laufen im Gelände", "Crosslauf", "Über Wiesen, Matsch und Hügel."],
       ["Möglichst hoch über die Latte", "Hochsprung", "Angelaufen wird im Bogen."],
       ["Mit einem Stab in die Höhe", "Stabhochsprung", "Der Stab biegt sich stark."],
       ["Speer werfen", "Speerwurf", "Er muss mit der Spitze zuerst landen."],
       ["Zehn Disziplinen an zwei Tagen", "Zehnkampf", "Der Sieger gilt als Allrounder."],
       ["Gehen statt Laufen im Wettkampf", "Gehen", "Ein Fuß muss immer Bodenkontakt haben."],
       ["Ziellinie überqueren", "Zieleinlauf", "Der Oberkörper zählt, nicht der Fuß."]]'::jsonb),

    ('sport', 'leicht-sport-zuhause', 'Sport ohne Verein',
     'Was braucht man dafür?',
     'easy', 'Freizeitsport',
     'https://de.wikipedia.org/wiki/Freizeitsport',
     '[["Joggen", "Gute Laufschuhe", "Mehr braucht es nicht."],
       ["Radfahren", "Fahrrad und Helm", "Auch der Weg zur Arbeit zählt."],
       ["Wandern", "Feste Schuhe", "Dazu Wasser und eine Karte."],
       ["Yoga", "Eine Matte", "Und etwas Platz im Zimmer."],
       ["Seilspringen", "Ein Springseil", "Ein sehr wirksames Ausdauertraining."],
       ["Schwimmen", "Badesachen", "Im See oder im Bad."],
       ["Tischtennis im Park", "Schläger und Ball", "Die Platte steht fest."],
       ["Klettern in der Halle", "Kletterschuhe und Gurt", "Gesichert wird zu zweit."],
       ["Skateboarden", "Board und Schoner", "Handgelenke brechen am häufigsten."],
       ["Wintersport auf dem See", "Schlittschuhe", "Nur bei sicherer Eisdecke."]]'::jsonb),

    ('sport', 'leicht-sportler-laender', 'Sportler & Länder',
     'Aus welchem Land kommt die Person?',
     'easy', 'Sport', 'https://de.wikipedia.org/wiki/Sport',
     '[["Usain Bolt", "Jamaika", "Der schnellste Mensch der Welt."],
       ["Michael Schumacher", "Deutschland", "Sieben Formel-1-Titel."],
       ["Lionel Messi", "Argentinien", "Weltmeister 2022."],
       ["Cristiano Ronaldo", "Portugal", "Europameister 2016."],
       ["Roger Federer", "Schweiz", "Achtmal Wimbledonsieger."],
       ["Serena Williams", "USA", "23 Grand-Slam-Titel."],
       ["Eliud Kipchoge", "Kenia", "Marathon in Weltbestzeit."],
       ["Novak Djokovic", "Serbien", "Rekordhalter bei Grand Slams."],
       ["Yuzuru Hanyu", "Japan", "Zweimal Olympiasieger im Eiskunstlauf."],
       ["Ian Thorpe", "Australien", "Schwimmer mit vielen Goldmedaillen."],
       ["Nadia Comăneci", "Rumänien", "Die erste perfekte Zehn."]]'::jsonb),

    ('sport', 'leicht-vereine', 'Bekannte Vereine',
     'In welcher Stadt spielt der Verein?',
     'easy', 'Fußballverein',
     'https://de.wikipedia.org/wiki/Fu%C3%9Fballverein',
     '[["FC Bayern", "München", "Rekordmeister der Bundesliga."],
       ["Borussia Dortmund", "Dortmund", "Bekannt für die gelbe Wand."],
       ["Real Madrid", "Madrid", "Rekordsieger der Champions League."],
       ["FC Barcelona", "Barcelona", "Spielt im Camp Nou."],
       ["Manchester United", "Manchester", "Heimat ist Old Trafford."],
       ["Juventus", "Turin", "Der italienische Rekordmeister."],
       ["Ajax", "Amsterdam", "Bekannt für seine Jugendarbeit."],
       ["Paris Saint-Germain", "Paris", "Der dominierende Klub Frankreichs."],
       ["FC Schalke 04", "Gelsenkirchen", "Der Rivale aus dem Ruhrgebiet."],
       ["Benfica", "Lissabon", "Rekordmeister Portugals."],
       ["Celtic", "Glasgow", "Eine Hälfte des Old Firm."],
       ["Werder Bremen", "Bremen", "Spielt im Weserstadion."]]'::jsonb),

    ('sport', 'leicht-sport-jahreszeiten', 'Sport im Jahreslauf',
     'Wann macht man das vor allem?',
     'easy', 'Sport', 'https://de.wikipedia.org/wiki/Sport',
     '[["Skifahren", "Im Winter", "Wenn Schnee liegt."],
       ["Freibadbesuch", "Im Sommer", "Bei warmem Wetter."],
       ["Drachensteigen", "Im Herbst", "Wenn es kräftig weht."],
       ["Radtour bei mildem Wetter", "Im Frühling", "Wenn die Tage länger werden."],
       ["Fußball-Weltmeisterschaft in Europa", "Im Juni und Juli", "Zwischen den Ligaspielzeiten."],
       ["Tour de France", "Im Juli", "Drei Wochen lang."],
       ["Skisprung-Vierschanzentournee", "Um den Jahreswechsel", "Zwischen Weihnachten und Dreikönig."],
       ["Wimbledon", "Anfang Juli", "Auf Rasen in London."],
       ["Berlin-Marathon", "Im September", "Bei kühlem Laufwetter."],
       ["Eislaufen auf natürlichem Eis", "Bei Dauerfrost", "Nur wenn die Decke trägt."]]'::jsonb),

    ('sport', 'leicht-fairness', 'Fair bleiben',
     'Was gehört zum fairen Sport?',
     'easy', 'Fair Play', 'https://de.wikipedia.org/wiki/Fair_Play',
     '[["Nach dem Spiel", "Handschlag mit dem Gegner", "Ob gewonnen oder verloren."],
       ["Wenn der Gegner am Boden liegt", "Ball ins Aus spielen", "Damit behandelt werden kann."],
       ["Bei einer Fehlentscheidung für das eigene Team", "Auf den Fehler hinweisen", "Selten, aber es kommt vor."],
       ["Gegenüber dem Schiedsrichter", "Entscheidungen akzeptieren", "Auch die falschen."],
       ["Als Zuschauer", "Auch den Gegner respektieren", "Pfiffe gegen Kinder gehen gar nicht."],
       ["Bei einer Niederlage", "Fair gratulieren", "Der Bessere hat gewonnen."],
       ["Bei einem Sieg", "Nicht überheblich werden", "Nächste Woche kann es anders sein."],
       ["Gegenüber schwächeren Mitspielern", "Alle mitspielen lassen", "Niemand bleibt am Rand."],
       ["Mit dem eigenen Körper", "Kein Doping", "Auch nicht als Freizeitsportler."],
       ["Mit der Ausrüstung", "Nichts manipulieren", "Auch das ist Betrug."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
)

insert into items (quiz_id, category_id, label, position, explanation)
select f.quiz_id, c.id, f.answer, f.position, f.explanation
  from flat f
  join new_categories c
    on c.quiz_id = f.quiz_id
   and c.label = f.label;
