-- Sport, file 1 of 2. Twenty questions, medium and hard.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs) as (
    values

    ('sport', 'olympiastaedte-sommer', 'Olympische Sommerspiele',
     'In welcher Stadt fanden die Spiele statt?',
     'hard', 'Olympische Sommerspiele',
     'https://de.wikipedia.org/wiki/Olympische_Sommerspiele',
     '[["1896", "Athen", "Die ersten Spiele der Neuzeit."],
       ["1936", "Berlin", "Erstmals mit Fackellauf aus Olympia."],
       ["1964", "Tokio", "Erste Spiele in Asien, live per Satellit übertragen."],
       ["1968", "Mexiko-Stadt", "In 2240 Metern Höhe, mit Rekorden in den Sprints."],
       ["1972", "München", "Die heiteren Spiele endeten im Attentat."],
       ["1984", "Los Angeles", "Der Ostblock blieb fern."],
       ["1992", "Barcelona", "Die Stadt öffnete sich dabei zum Meer hin."],
       ["2000", "Sydney", "Im September ausgetragen, wegen der Südhalbkugel."],
       ["2008", "Peking", "Eröffnung am achten Tag des achten Monats."],
       ["2012", "London", "Erste Stadt mit drei Sommerspielen."],
       ["2016", "Rio de Janeiro", "Erste Spiele in Südamerika."],
       ["2024", "Paris", "Die Eröffnung fand auf der Seine statt."]]'::jsonb),

    ('sport', 'olympiastaedte-winter', 'Olympische Winterspiele',
     'Wo wurden die Winterspiele ausgetragen?',
     'hard', 'Olympische Winterspiele',
     'https://de.wikipedia.org/wiki/Olympische_Winterspiele',
     '[["1976", "Innsbruck", "Sprang für Denver ein, das abgesagt hatte."],
       ["1980", "Lake Placid", "Das Eishockeyfinale ging als Wunder auf dem Eis um die Welt."],
       ["1988", "Calgary", "Erstmals trat ein Bob-Team aus Jamaika an."],
       ["1992", "Albertville", "Letzte Winterspiele im selben Jahr wie die Sommerspiele."],
       ["1994", "Lillehammer", "Nur zwei Jahre nach den vorigen, wegen des neuen Rhythmus."],
       ["1998", "Nagano", "Snowboard wurde olympisch."],
       ["2002", "Salt Lake City", "Im Zentrum der Mormonen im Bundesstaat Utah."],
       ["2006", "Turin", "Die Wettbewerbe verteilten sich weit ins Aostatal."],
       ["2010", "Vancouver", "Regen und Schneemangel begleiteten die Spiele."],
       ["2014", "Sotschi", "Subtropischer Kurort am Schwarzen Meer."],
       ["2018", "Pyeongchang", "Nord- und Südkorea liefen gemeinsam ein."],
       ["2022", "Peking", "Erste Stadt mit Sommer- und Winterspielen."]]'::jsonb),

    ('sport', 'fussball-wm-gastgeber', 'Fußball-Weltmeisterschaften',
     'In welchem Land wurde das Turnier ausgetragen?',
     'hard', 'Fußball-Weltmeisterschaft',
     'https://de.wikipedia.org/wiki/Fu%C3%9Fball-Weltmeisterschaft',
     '[["1954", "Schweiz", "Das Wunder von Bern fiel in dieses Turnier."],
       ["1966", "England", "Das umstrittene Wembley-Tor im Finale."],
       ["1974", "Deutschland", "Erstes Turnier mit dem heutigen WM-Pokal."],
       ["1978", "Argentinien", "Ausgetragen unter der Militärdiktatur."],
       ["1990", "Italien", "Das Finale entschied ein später Elfmeter."],
       ["1994", "USA", "Rekordzuschauerzahlen in einem Land ohne Fußballtradition."],
       ["1998", "Frankreich", "Erstmals mit 32 Mannschaften."],
       ["2002", "Japan und Südkorea", "Erste WM in Asien und erste mit zwei Gastgebern."],
       ["2010", "Südafrika", "Erste WM auf dem afrikanischen Kontinent."],
       ["2014", "Brasilien", "Das Halbfinale endete 7:1."],
       ["2018", "Russland", "Elf Spielorte von Kaliningrad bis Jekaterinburg."],
       ["2022", "Katar", "Wegen der Hitze im November und Dezember gespielt."]]'::jsonb),

    ('sport', 'sportler-disziplinen', 'Sportgrößen & ihre Disziplin',
     'In welcher Sportart wurde die Person berühmt?',
     'medium', 'Sport', 'https://de.wikipedia.org/wiki/Sport',
     '[["Usain Bolt", "Sprint", "Weltrekorde über 100 und 200 Meter."],
       ["Michael Phelps", "Schwimmen", "23 olympische Goldmedaillen."],
       ["Serena Williams", "Tennis", "23 Grand-Slam-Titel im Einzel."],
       ["Michael Jordan", "Basketball", "Sechs Meisterschaften mit den Chicago Bulls."],
       ["Lionel Messi", "Fußball", "Achtmal mit dem Ballon d''Or ausgezeichnet."],
       ["Muhammad Ali", "Boxen", "Schwebe wie ein Schmetterling, stich wie eine Biene."],
       ["Michael Schumacher", "Formel 1", "Sieben Weltmeistertitel."],
       ["Tiger Woods", "Golf", "Jüngster Masters-Sieger seiner Zeit."],
       ["Wayne Gretzky", "Eishockey", "Seine Rückennummer 99 ist ligaweit gesperrt."],
       ["Eddy Merckx", "Radsport", "Der Kannibale gewann fünfmal die Tour."],
       ["Nadia Comăneci", "Turnen", "Erste perfekte Zehn bei Olympischen Spielen."],
       ["Katarina Witt", "Eiskunstlauf", "Zweimal olympisches Gold in Folge."]]'::jsonb),

    ('sport', 'sportbegriffe', 'Fachbegriffe & Sportarten',
     'Zu welcher Sportart gehört der Begriff?',
     'hard', 'Sport', 'https://de.wikipedia.org/wiki/Sport',
     '[["Birdie", "Golf", "Ein Schlag unter Par."],
       ["Ass", "Tennis", "Aufschlag, den der Gegner nicht berührt."],
       ["Strike", "Bowling", "Alle zehn Pins mit dem ersten Wurf."],
       ["Touchdown", "American Football", "Sechs Punkte für den Ball in der Endzone."],
       ["Slam Dunk", "Basketball", "Der Ball wird von oben in den Korb gestopft."],
       ["Ippon", "Judo", "Der ganze Punkt beendet den Kampf sofort."],
       ["Homerun", "Baseball", "Der Schlagmann läuft alle vier Bases durch."],
       ["Half-Pipe", "Snowboard", "Halbrohr aus Schnee für Sprünge an beiden Kanten."],
       ["Peloton", "Radsport", "Das geschlossene Hauptfeld im Rennen."],
       ["Pirouette", "Eiskunstlauf", "Drehung auf der Stelle um die eigene Achse."],
       ["Schmetterball", "Volleyball", "Angriffsschlag von oben über das Netz."],
       ["Rochade", "Schach", "Der einzige Zug, bei dem zwei Figuren zugleich ziehen."]]'::jsonb),

    ('sport', 'stadien-staedte', 'Stadien & Städte',
     'In welcher Stadt steht das Stadion?',
     'medium', 'Stadion', 'https://de.wikipedia.org/wiki/Stadion',
     '[["Camp Nou", "Barcelona", "Größtes Stadion Europas nach Plätzen."],
       ["Santiago Bernabéu", "Madrid", "Benannt nach einem früheren Vereinspräsidenten."],
       ["Old Trafford", "Manchester", "Das Theater der Träume."],
       ["Anfield", "Liverpool", "Vor dem Anpfiff erklingt You''ll Never Walk Alone."],
       ["San Siro", "Mailand", "Zwei Vereine teilen sich das Haus."],
       ["Allianz Arena", "München", "Die Außenhaut lässt sich farbig beleuchten."],
       ["Signal Iduna Park", "Dortmund", "Die Südtribüne fasst fast 25000 Stehplätze."],
       ["Maracanã", "Rio de Janeiro", "1950 sahen dort fast 200000 Menschen ein Endspiel."],
       ["Wembley", "London", "Erkennbar am Bogen über dem Dach."],
       ["Stade de France", "Paris", "Für die WM 1998 in Saint-Denis gebaut."],
       ["Estadio Azteca", "Mexiko-Stadt", "Schauplatz zweier WM-Endspiele."],
       ["Olympiastadion", "Berlin", "Austragungsort des DFB-Pokalfinales."]]'::jsonb),

    ('sport', 'formel1-strecken', 'Formel-1-Strecken & Länder',
     'In welchem Land liegt die Strecke?',
     'hard', 'Formel 1', 'https://de.wikipedia.org/wiki/Formel_1',
     '[["Monza", "Italien", "Der Tempel der Geschwindigkeit."],
       ["Silverstone", "Vereinigtes Königreich", "Auf einem früheren Militärflugplatz."],
       ["Spa-Francorchamps", "Belgien", "Berühmt für die Eau Rouge."],
       ["Circuit de Monaco", "Monaco", "Stadtkurs mit Tunnel und Hafenschikane."],
       ["Suzuka", "Japan", "Einzige Strecke im Kalender in Form einer Acht."],
       ["Interlagos", "Brasilien", "Wird gegen den Uhrzeigersinn gefahren."],
       ["Hungaroring", "Ungarn", "Enge Strecke, auf der Überholen schwerfällt."],
       ["Zandvoort", "Niederlande", "Dünenkurs mit überhöhten Steilkurven."],
       ["Red Bull Ring", "Österreich", "Kurze Runde in der Steiermark."],
       ["Hockenheimring", "Deutschland", "Früher mit langen Geraden durch den Wald."],
       ["Circuit of the Americas", "USA", "Steile Anfahrt auf die erste Kurve."],
       ["Marina Bay", "Singapur", "Nachtrennen unter Flutlicht."]]'::jsonb),

    ('sport', 'tennisturniere-orte', 'Tennisturniere & Orte',
     'Wo wird das Turnier gespielt?',
     'medium', 'Tennis', 'https://de.wikipedia.org/wiki/Tennis',
     '[["Wimbledon", "London", "Auf Rasen, mit weißer Kleiderordnung."],
       ["French Open", "Paris", "Auf Sand in Roland Garros."],
       ["US Open", "New York", "Hartplatz in Flushing Meadows."],
       ["Australian Open", "Melbourne", "Erstes Grand-Slam-Turnier des Jahres."],
       ["Monte-Carlo Masters", "Monaco", "Sandplatzturnier mit Blick aufs Mittelmeer."],
       ["Indian Wells", "Kalifornien", "Wegen seiner Größe das fünfte Grand Slam genannt."],
       ["Miami Open", "Florida", "Findet direkt nach Indian Wells statt."],
       ["Internazionali d''Italia", "Rom", "Sandplatzturnier im Foro Italico."],
       ["Mutua Madrid Open", "Madrid", "Auf über 600 Metern Höhe gespielt."],
       ["Rolex Shanghai Masters", "Shanghai", "Wichtigstes Turnier der Asienserie."],
       ["ATP Finals", "Turin", "Nur die besten acht der Saison treten an."],
       ["Canada Masters", "Toronto", "Wechselt jährlich mit Montreal."]]'::jsonb),

    ('sport', 'kampfsport-herkunft', 'Kampfkünste & Herkunft',
     'Woher stammt die Kampfkunst?',
     'medium', 'Kampfkunst', 'https://de.wikipedia.org/wiki/Kampfkunst',
     '[["Judo", "Japan", "Der sanfte Weg, 1882 von Jigorō Kanō begründet."],
       ["Taekwondo", "Südkorea", "Bekannt für hohe und schnelle Fußtechniken."],
       ["Kung Fu", "China", "Sammelbegriff für viele Schulen, oft mit Shaolin verbunden."],
       ["Muay Thai", "Thailand", "Auch Ellenbogen und Knie sind erlaubt."],
       ["Capoeira", "Brasilien", "Kampf, Tanz und Musik in einem Kreis."],
       ["Sambo", "Russland", "In den 1920er Jahren fürs Militär entwickelt."],
       ["Krav Maga", "Israel", "Auf Selbstverteidigung ohne Regeln ausgelegt."],
       ["Pencak Silat", "Indonesien", "Über Hunderte Stile auf den Inseln verteilt."],
       ["Savate", "Frankreich", "Fußkampf, der mit Schuhen ausgeübt wird."],
       ["Escrima", "Philippinen", "Kampf mit kurzen Rattanstöcken."],
       ["Kalarippayattu", "Indien", "Gilt als eine der ältesten Kampfkünste überhaupt."],
       ["Lucha Libre", "Mexiko", "Ringkampf mit Masken und fliegenden Manövern."]]'::jsonb),

    ('sport', 'mannschaftsgroessen', 'Mannschaften & Spielerzahl',
     'Wie viele Spieler stehen pro Team auf dem Feld?',
     'medium', 'Mannschaftssport',
     'https://de.wikipedia.org/wiki/Mannschaftssport',
     '[["Fußball", "11", "Ein Torwart und zehn Feldspieler."],
       ["Basketball", "5", "Fünf gegen fünf auf dem Parkett."],
       ["Handball", "7", "Sechs Feldspieler und ein Torwart."],
       ["Volleyball", "6", "Nach jedem Aufschlaggewinn wird rotiert."],
       ["Rugby Union", "15", "Acht Stürmer und sieben Hintermannschaftsspieler."],
       ["Rugby League", "13", "Zwei Spieler weniger als in der Union-Variante."],
       ["Baseball", "9", "Neun Positionen im Feld, vom Pitcher bis zum Right Fielder."],
       ["Beachvolleyball", "2", "Kein Auswechseln, kein Rotationszwang."],
       ["Viererbob", "4", "Pilot, zwei Anschieber und ein Bremser."],
       ["Ruder-Achter", "8", "Dazu kommt der Steuermann, der nicht rudert."],
       ["3x3-Basketball", "3", "Seit 2021 olympisch, auf einem halben Feld."]]'::jsonb),

    ('sport', 'nationalteam-spitznamen', 'Nationalmannschaften & Spitznamen',
     'Wie wird die Mannschaft genannt?',
     'hard', 'Fußballnationalmannschaft',
     'https://de.wikipedia.org/wiki/Fu%C3%9Fballnationalmannschaft',
     '[["Italien", "Squadra Azzurra", "Das Blau geht auf das Haus Savoyen zurück."],
       ["Niederlande", "Elftal", "Oranje nach dem Königshaus."],
       ["Brasilien", "Seleção", "Schlicht: die Auswahl."],
       ["Argentinien", "Albiceleste", "Weiß-himmelblau, wie die Flagge."],
       ["Frankreich", "Les Bleus", "Die Blauen, nach dem Trikot."],
       ["England", "Three Lions", "Drei Löwen aus dem königlichen Wappen."],
       ["Spanien", "La Roja", "Die Rote, seit den Erfolgen ab 2008 fest im Sprachgebrauch."],
       ["Uruguay", "La Celeste", "Die Himmelblaue, zweimal Weltmeister."],
       ["Mexiko", "El Tri", "Nach den drei Farben der Flagge."],
       ["Belgien", "Rote Teufel", "Der Name stammt aus den 1900er Jahren."],
       ["Kroatien", "Vatreni", "Die Feurigen, im rot-weißen Schachbrettmuster."],
       ["Kamerun", "Unbezähmbare Löwen", "Erste afrikanische Mannschaft im WM-Viertelfinale."]]'::jsonb),

    ('sport', 'radsport-trikots', 'Radsport & Trikots',
     'Welches Trikot gehört zu dieser Wertung?',
     'hard', 'Tour de France',
     'https://de.wikipedia.org/wiki/Tour_de_France',
     '[["Gesamtwertung der Tour de France", "Gelbes Trikot", "Die Farbe der Zeitung, die das Rennen erfand."],
       ["Punktewertung der Tour", "Grünes Trikot", "Für die konstantesten Sprinter."],
       ["Bergwertung der Tour", "Gepunktetes Trikot", "Rote Punkte auf weißem Grund."],
       ["Bester Jungprofi der Tour", "Weißes Trikot", "Für Fahrer unter 26 Jahren."],
       ["Gesamtwertung des Giro", "Rosa Trikot", "Nach dem rosa Papier der Gazzetta dello Sport."],
       ["Bergwertung des Giro", "Blaues Trikot", "Der König der Berge in Italien."],
       ["Gesamtwertung der Vuelta", "Rotes Trikot", "Seit 2010 in dieser Farbe."],
       ["Weltmeister im Straßenrennen", "Regenbogentrikot", "Fünf Streifen in den olympischen Farben."],
       ["Führender im Weltcup der Bahn", "Blau-weißes Trikot", "Für die Führung in der Gesamtwertung auf der Bahn."],
       ["Kämpferischster Fahrer der Tour", "Rote Startnummer", "Wird täglich von einer Jury vergeben."]]'::jsonb),

    ('sport', 'sportmasse', 'Maße im Sport',
     'Welches Maß gilt hier?',
     'hard', 'Sportart', 'https://de.wikipedia.org/wiki/Sportart',
     '[["Höhe des Basketballkorbs", "3,05 Meter", "Zehn Fuß, seit der Erfindung des Spiels unverändert."],
       ["Breite des Fußballtors", "7,32 Meter", "Acht Yards, aus dem englischen Maßsystem."],
       ["Länge des Marathonlaufs", "42,195 Kilometer", "Die krumme Zahl stammt von den Spielen 1908."],
       ["Durchmesser des Golflochs", "108 Millimeter", "Angeblich vom Durchmesser eines Abflussrohrs."],
       ["Netzhöhe im Volleyball der Männer", "2,43 Meter", "Bei den Frauen 24 Zentimeter niedriger."],
       ["Länge einer Stadionrunde", "400 Meter", "Auf der innersten Bahn gemessen."],
       ["Länge eines olympischen Beckens", "50 Meter", "Kurzbahn ist halb so lang."],
       ["Abstand beim Dartwurf", "2,37 Meter", "Gemessen von der Scheibe zur Abwurflinie."],
       ["Länge der Tischtennisplatte", "2,74 Meter", "Neun Fuß, bei 1,525 Meter Breite."],
       ["Disziplinen im Zehnkampf", "10", "An zwei Tagen zu absolvieren."],
       ["Elfmeterpunkt vom Tor", "11 Meter", "Daher der deutsche Name des Strafstoßes."],
       ["Seitenlänge des Boxrings", "6,10 Meter", "Zwischen den Seilen gemessen."]]'::jsonb),

    ('sport', 'vereins-spitznamen', 'Vereine & ihre Spitznamen',
     'Wie wird der Verein genannt?',
     'hard', 'Fußballverein',
     'https://de.wikipedia.org/wiki/Fu%C3%9Fballverein',
     '[["Juventus Turin", "Alte Dame", "Vecchia Signora, wegen der langen Geschichte."],
       ["Manchester United", "Red Devils", "Der Spitzname stammt aus den 1960er Jahren."],
       ["Arsenal", "Gunners", "Der Verein entstand in einer Waffenfabrik."],
       ["FC Barcelona", "Blaugrana", "Nach den blau-roten Streifen."],
       ["Real Madrid", "Die Königlichen", "Real bedeutet königlich."],
       ["Inter Mailand", "Nerazzurri", "Die Schwarz-Blauen."],
       ["AC Mailand", "Rossoneri", "Die Rot-Schwarzen."],
       ["FC Schalke 04", "Königsblaue", "Nach dem Blau der Trikots."],
       ["Borussia Dortmund", "Die Schwarzgelben", "Vereinsfarben seit der Gründung 1909."],
       ["Tottenham Hotspur", "Spurs", "Kurzform des Vereinsnamens."],
       ["Ajax Amsterdam", "Godenzonen", "Die Göttersöhne, nach dem griechischen Helden."],
       ["Celtic Glasgow", "The Bhoys", "Schreibweise aus einer alten Postkarte übernommen."]]'::jsonb),

    ('sport', 'wintersport-disziplinen', 'Wintersport & seine Regeln',
     'Was kennzeichnet die Disziplin?',
     'medium', 'Wintersport', 'https://de.wikipedia.org/wiki/Wintersport',
     '[["Biathlon", "Langlauf und Schießen", "Jeder Fehlschuss kostet eine Strafrunde."],
       ["Skeleton", "Kopfvoraus auf dem Bauch", "Gesteuert wird mit Schulter- und Beindruck."],
       ["Rodeln", "Rücklings, Füße voran", "Auf derselben Bahn wie Bob und Skeleton."],
       ["Curling", "Steine und Wischbesen", "Das Wischen verlängert den Lauf des Steins."],
       ["Eisschnelllauf", "Ovale Bahn zu zweit", "Die Läufer wechseln pro Runde die Bahn."],
       ["Shorttrack", "Pulkstart auf Kurzbahn", "Gerangel und Stürze gehören dazu."],
       ["Skispringen", "Weite und Haltungsnoten", "Auch der Wind wird verrechnet."],
       ["Nordische Kombination", "Springen und Langlauf", "Der Sprung bestimmt den Startabstand im Rennen."],
       ["Snowboardcross", "Vier fahren gegeneinander", "Sprünge und Wellen auf einem engen Kurs."],
       ["Eiskunstlauf", "Sprünge zur Musik", "Bewertet werden Technik und künstlerischer Ausdruck."],
       ["Buckelpiste", "Buckel und zwei Sprünge", "Tempo, Technik und Sprünge zählen zusammen."],
       ["Eisstockschießen", "Stöcke auf eine Daube", "Vor allem im Alpenraum verbreitet."]]'::jsonb),

    ('sport', 'schach-weltmeister', 'Schachweltmeister & Länder',
     'Aus welchem Land kam der Weltmeister?',
     'hard', 'Schachweltmeister',
     'https://de.wikipedia.org/wiki/Schachweltmeister',
     '[["Wilhelm Steinitz", "Österreich", "Erster offizieller Weltmeister ab 1886."],
       ["Emanuel Lasker", "Deutschland", "Hielt den Titel 27 Jahre lang."],
       ["José Raúl Capablanca", "Kuba", "Galt als die Schachmaschine."],
       ["Max Euwe", "Niederlande", "Gewann den Titel 1935 und verlor ihn zwei Jahre später."],
       ["Michail Botwinnik", "Sowjetunion", "Begründete die sowjetische Schachschule."],
       ["Tigran Petrosjan", "Armenien", "Berühmt für seine Verteidigungskunst."],
       ["Bobby Fischer", "USA", "Sein Sieg 1972 fiel mitten in den Kalten Krieg."],
       ["Garri Kasparow", "Aserbaidschan", "In Baku geboren, verlor 1997 gegen einen Computer."],
       ["Viswanathan Anand", "Indien", "Löste in seiner Heimat einen Schachboom aus."],
       ["Magnus Carlsen", "Norwegen", "Gab den Titel 2023 freiwillig ab."],
       ["Ding Liren", "China", "Erster Weltmeister seines Landes."]]'::jsonb),

    ('sport', 'sportverbaende', 'Verbände & Sportarten',
     'Welche Sportart vertritt der Verband?',
     'hard', 'Sportverband', 'https://de.wikipedia.org/wiki/Sportverband',
     '[["FIFA", "Fußball", "Sitz in Zürich, gegründet 1904."],
       ["UCI", "Radsport", "Vergibt auch das Regenbogentrikot."],
       ["FIA", "Motorsport", "Dachverband auch der Formel 1."],
       ["FIS", "Skisport", "Zuständig von Abfahrt bis Skisprung."],
       ["World Athletics", "Leichtathletik", "Hieß bis 2019 IAAF."],
       ["FINA", "Schwimmsport", "Heute unter dem Namen World Aquatics."],
       ["ITF", "Tennis", "Organisiert unter anderem den Davis Cup."],
       ["IIHF", "Eishockey", "Richtet die Weltmeisterschaften aus."],
       ["FIDE", "Schach", "Ihr Motto: Gens una sumus."],
       ["IBU", "Biathlon", "1993 vom Verband der Modernen Fünfkämpfer getrennt."],
       ["World Rugby", "Rugby", "Vergibt die Weltmeisterschaft alle vier Jahre."],
       ["FEI", "Reitsport", "Zuständig für Dressur, Springen und Vielseitigkeit."]]'::jsonb),

    ('sport', 'nba-teams-staedte', 'NBA-Teams & Städte',
     'In welcher Stadt spielt das Team?',
     'medium', 'National Basketball Association',
     'https://de.wikipedia.org/wiki/National_Basketball_Association',
     '[["Lakers", "Los Angeles", "Der Name stammt aus der Seenlandschaft Minnesotas."],
       ["Celtics", "Boston", "Rekordmeister der Liga."],
       ["Bulls", "Chicago", "Sechs Titel in den 1990er Jahren."],
       ["Knicks", "New York", "Spielen im Madison Square Garden."],
       ["Heat", "Miami", "Gegründet 1988 in Florida."],
       ["Warriors", "San Francisco", "Vorher jahrzehntelang in Oakland."],
       ["Spurs", "San Antonio", "Fünf Titel unter demselben Trainer."],
       ["Mavericks", "Dallas", "2011 Meister mit Dirk Nowitzki."],
       ["Rockets", "Houston", "Der Name spielt auf die Raumfahrtindustrie an."],
       ["Raptors", "Toronto", "Einziges Team außerhalb der USA."],
       ["Nuggets", "Denver", "Der Name erinnert an den Goldrausch."],
       ["Suns", "Phoenix", "Passend zur Wüstenstadt in Arizona."]]'::jsonb),

    ('sport', 'leichtathletik-geraete', 'Leichtathletik & Geräte',
     'Womit wird die Disziplin ausgetragen?',
     'medium', 'Leichtathletik',
     'https://de.wikipedia.org/wiki/Leichtathletik',
     '[["Kugelstoßen", "Kugel", "7,26 Kilogramm bei den Männern."],
       ["Speerwurf", "Speer", "Seit 1986 mit verlagertem Schwerpunkt, für kürzere Weiten."],
       ["Diskuswurf", "Diskus", "Aus dem Ring heraus, nach anderthalb Drehungen."],
       ["Hammerwurf", "Hammer an Stahldraht", "Trotz des Namens eine Kugel."],
       ["Stabhochsprung", "Stab aus Kunststoff", "Früher aus Bambus oder Aluminium."],
       ["Hürdenlauf", "Hürden", "Sie kippen um, wenn man sie trifft."],
       ["Hochsprung", "Latte über zwei Ständern", "Seit Fosbury wird rücklings gesprungen."],
       ["Weitsprung", "Absprungbalken und Sandgrube", "Ein Übertritt macht den Versuch ungültig."],
       ["Staffellauf", "Staffelstab", "Der Wechsel muss innerhalb einer Zone erfolgen."],
       ["Hindernislauf", "Feste Balken und Wassergraben", "3000 Meter mit 28 Hindernissen und sieben Wassersprüngen."]]'::jsonb),

    ('sport', 'sportarten-herkunft', 'Sportarten & ihre Herkunft',
     'Wo entstand die Sportart?',
     'medium', 'Sportart', 'https://de.wikipedia.org/wiki/Sportart',
     '[["Fußball", "England", "Die ersten Regeln entstanden 1863 in London."],
       ["Basketball", "USA", "1891 mit Pfirsichkörben in einer Turnhalle erfunden."],
       ["Eishockey", "Kanada", "Erstes Hallenspiel 1875 in Montreal."],
       ["Curling", "Schottland", "Schon im 16. Jahrhundert auf zugefrorenen Teichen."],
       ["Handball", "Dänemark", "Die frühe Hallenform entstand in Skandinavien."],
       ["Judo", "Japan", "Aus dem Jiu-Jitsu der Samurai entwickelt."],
       ["Taekwondo", "Südkorea", "Nach 1945 aus mehreren Schulen zusammengeführt."],
       ["Skispringen", "Norwegen", "Erste Wettkämpfe im Telemark im 19. Jahrhundert."],
       ["Pelota", "Baskenland", "Der Ball wird gegen eine Wand geschlagen."],
       ["Sepak Takraw", "Malaysia", "Volleyball, aber nur mit Fuß, Knie und Kopf."],
       ["Polo", "Persien", "Ursprünglich ein Training für die Reiterei."],
       ["Surfen", "Hawaii", "Von den Königen der Inseln überliefert."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
)

insert into items (quiz_id, category_id, label, position, explanation)
select f.quiz_id, c.id, f.answer, f.position, f.explanation
  from flat f
  join new_categories c
    on c.quiz_id = f.quiz_id
   and c.label = f.label;
