-- Sport, file 3. Twenty questions, medium and hard.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs, fakes) as (
    values

    ('sport', 'sportjargon', 'Sprüche & Sportarten',
     'Aus welcher Sportart stammt die Redewendung?',
     'hard', 'Sportjargon', 'https://de.wikipedia.org/wiki/Sportjargon',
     '[["Am Ball bleiben", "Fußball", "Wer den Ball hält, bestimmt das Spiel."],
       ["In die Bredouille kommen", "Schach", "Von der bedrängten Stellung auf dem Brett."],
       ["Unter die Räder kommen", "Radsport", "Wer stürzt, wird vom Feld überrollt."],
       ["Ins Schwarze treffen", "Bogenschießen", "Der innerste Ring war ursprünglich schwarz."],
       ["Die Hürde nehmen", "Leichtathletik", "Ein Hindernis, das man überlaufen muss."],
       ["Handtuch werfen", "Boxen", "Die Ecke gibt den Kampf für den Boxer auf."],
       ["Auf die Pauke hauen", "Turnen", "Vom lauten Anschlagen am Gerät."],
       ["Die Segel streichen", "Segeln", "Wer einholt, gibt die Fahrt auf."],
       ["Aus dem Rennen sein", "Pferderennen", "Wer zurückfällt, spielt keine Rolle mehr."],
       ["Volle Deckung", "Fechten", "Die Klinge schützt die Trefferfläche."],
       ["Den Kürzeren ziehen", "Ringen", "Beim Losen um die Ausgangsposition."]]'::jsonb,
     '[["Tennis", "Auch daher stammen Redewendungen, auf diesem Brett aber keine."],
       ["Rudern", "Aus dem Wasser stammt hier keine Wendung."]]'::jsonb),

    ('sport', 'trikotnummern', 'Trikotnummern & Bedeutung',
     'Wofür steht die Nummer traditionell?',
     'hard', 'Trikot', 'https://de.wikipedia.org/wiki/Trikot',
     '[["Nummer 1 im Fußball", "Torwart", "Seit den Anfängen für den Mann im Kasten reserviert."],
       ["Nummer 10 im Fußball", "Spielmacher", "Die Nummer der Kreativen, von Pelé bis Maradona."],
       ["Nummer 9 im Fußball", "Mittelstürmer", "Der klassische Torjäger."],
       ["Nummer 23 im Basketball", "Michael Jordan", "Aus Ehrfurcht von vielen nicht mehr getragen."],
       ["Nummer 99 im Eishockey", "Wayne Gretzky", "Ligaweit gesperrt, für niemanden mehr zu haben."],
       ["Gelbes Trikot", "Gesamtführung der Tour", "Die Farbe der Zeitung, die das Rennen erfand."],
       ["Grünes Trikot", "Punktbester Sprinter", "Für Konstanz auf flachen Etappen."],
       ["Regenbogentrikot", "Amtierender Weltmeister", "Fünf Streifen in den olympischen Farben."],
       ["Rosa Trikot", "Führung beim Giro", "Nach dem Papier der Gazzetta dello Sport."],
       ["Nummer 12 im Fußballstadion", "Die Fans", "Der zwölfte Mann auf den Rängen."],
       ["Nummer 7 bei Manchester United", "Vereinserbe", "Von Best über Cantona bis Ronaldo."],
       ["Nummer 3 im Baseball", "First Baseman", "Die Positionen sind fest durchnummeriert."]]'::jsonb,
     '[["Nummer 8 im Fußball", "Sie steht für den zentralen Mittelfeldspieler und fehlt hier."],
       ["Gepunktetes Trikot", "Es steht für die Bergwertung und ist auf diesem Brett keine Antwort."]]'::jsonb),

    ('sport', 'schiedsrichterzeichen', 'Schiedsrichter & Regeln',
     'Was zeigt der Schiedsrichter damit an?',
     'hard', 'Schiedsrichter',
     'https://de.wikipedia.org/wiki/Schiedsrichter',
     '[["Arm senkrecht nach oben", "Indirekter Freistoß", "Der Arm bleibt oben, bis der Ball gespielt ist."],
       ["Zeigen auf den Punkt", "Strafstoß", "Elf Meter vor dem Tor."],
       ["Beide Hände formen ein Rechteck", "Videobeweis", "Der Schiedsrichter fordert die Überprüfung an."],
       ["Gelbe Karte", "Verwarnung", "Zwei davon ergeben den Platzverweis."],
       ["Pfiff und Arm zur Seitenlinie", "Einwurf", "Die Richtung zeigt, wer den Ball bekommt."],
       ["Kreisende Arme im Basketball", "Zeitspiel", "Der Angriff muss abgeschlossen werden."],
       ["Gestreckter Arm im Volleyball", "Ball im Aus", "Die Hand zeigt senkrecht nach oben."],
       ["Gekreuzte Arme im Handball", "Passives Spiel", "Der Angriff läuft ohne Zielstrebigkeit."],
       ["Weiße Fahne im American Football", "Regelverstoß", "Die Flagge fliegt auf das Feld."],
       ["Schwarze Karte im Fechten", "Ausschluss vom Turnier", "Die schärfste aller Strafen."],
       ["Grüne Karte im Hockey", "Zweiminutenstrafe", "Danach folgen Gelb und Rot."],
       ["Ausgestreckter Finger im Cricket", "Der Schlagmann ist out", "Das gefürchtetste Zeichen im Spiel."]]'::jsonb,
     '[["Anstoß nach dem Wechsel", "Kein Zeichen auf diesem Brett meint das."],
       ["Beide Arme über dem Kopf gekreuzt", "So etwas zeigt kein Schiedsrichter in dieser Liste."]]'::jsonb),

    ('sport', 'olympische-symbole', 'Olympische Bräuche',
     'Was hat es damit auf sich?',
     'medium', 'Olympische Spiele',
     'https://de.wikipedia.org/wiki/Olympische_Spiele',
     '[["Fünf Ringe", "Die verbundenen Kontinente", "Jede Flagge der Welt enthält eine ihrer Farben."],
       ["Olympisches Feuer", "Entzündet in Olympia", "Mit einem Hohlspiegel und Sonnenlicht."],
       ["Fackellauf", "Weg zum Austragungsort", "Erstmals 1936 in dieser Form."],
       ["Olympischer Eid", "Versprechen der Athleten", "Gesprochen stellvertretend für alle."],
       ["Motto Citius, altius, fortius", "Schneller, höher, stärker", "Seit 2021 ergänzt um gemeinsam."],
       ["Einmarsch Griechenlands zuerst", "Ehre des Ursprungslandes", "Das Gastgeberland geht zuletzt."],
       ["Olympisches Dorf", "Unterkunft aller Athleten", "Seit 1932 fester Bestandteil."],
       ["Übergabe der Flagge", "Weitergabe der Gastgeberrolle", "Am Ende der Schlussfeier."],
       ["Medaillen aus Gold, Silber und Bronze", "Rang eins bis drei", "Gold ist tatsächlich vergoldetes Silber."],
       ["Olympische Waffenruhe", "Antiker Gottesfrieden", "Ekecheiria erlaubte die sichere Anreise."]]'::jsonb,
     '[["Das Maskottchen der Spiele", "Es gehört dazu, steht auf diesem Brett aber nicht."],
       ["Die Eröffnungsfeier im Stadion", "Sie fehlt in dieser Liste."]]'::jsonb),

    ('sport', 'paralympics', 'Paralympischer Sport',
     'Was kennzeichnet die Disziplin?',
     'hard', 'Paralympische Spiele',
     'https://de.wikipedia.org/wiki/Paralympische_Spiele',
     '[["Goalball", "Ball mit Glöckchen", "Alle Spieler tragen lichtdichte Brillen."],
       ["Boccia", "Zielwurf mit Lederbällen", "Auch für schwerste Behinderungen offen."],
       ["Sitzvolleyball", "Gesäßkontakt zum Boden", "Das Netz hängt deutlich tiefer."],
       ["Rollstuhlrugby", "Vollkontakt im Rollstuhl", "Früher treffend Murderball genannt."],
       ["Para-Schwimmen", "Start auch im Wasser", "Startklassen von S1 bis S14."],
       ["Blindenfußball", "Ball mit Rasseln", "Ein Guide hinter dem Tor gibt Anweisungen."],
       ["Para-Radsport", "Handbike und Tandem", "Sehbehinderte fahren mit Pilot."],
       ["Rollstuhlbasketball", "Zwei Schübe je Ballkontakt", "Danach muss geprellt oder gepasst werden."],
       ["Para-Biathlon", "Schießen auf Gehör", "Sehbehinderte zielen mit akustischem Signal."],
       ["Klassifizierung", "Einteilung nach Beeinträchtigung", "Sie macht Ergebnisse überhaupt vergleichbar."]]'::jsonb,
     '[["Bogenschießen im Sitzen", "Es gehört zum Programm, fehlt aber auf diesem Brett."],
       ["Rollstuhltanz", "Er steht nicht in dieser Liste."]]'::jsonb),

    ('sport', 'sportskandale', 'Wendepunkte des Sports',
     'Wofür steht das Ereignis?',
     'hard', 'Doping', 'https://de.wikipedia.org/wiki/Doping',
     '[["Seoul 1988", "Dopingfall im Sprint", "Der Sieger verlor sein Gold nach zwei Tagen."],
       ["Festina-Affäre 1998", "Doping im Radsport", "Ein Betreuerauto voller Ampullen flog auf."],
       ["Bosman-Urteil 1995", "Freie Spielerwechsel in Europa", "Ablösefreiheit nach Vertragsende."],
       ["Heysel 1985", "Katastrophe im Stadion", "Danach jahrelanger Ausschluss englischer Klubs."],
       ["Miracle on Ice 1980", "Amateure schlagen die Übermacht", "Ein Eishockeyspiel als politisches Ereignis."],
       ["Black Power 1968", "Protest auf dem Siegerpodest", "Zwei erhobene Fäuste in Mexiko-Stadt."],
       ["Boykott 1980", "Politisch bedingtes Fernbleiben", "Über sechzig Länder blieben Moskau fern."],
       ["Hand Gottes 1986", "Umstrittenes Tor im Viertelfinale", "Der Schiedsrichter sah das Handspiel nicht."],
       ["Wembley-Tor 1966", "Strittige Torentscheidung", "Bis heute nicht restlos geklärt."],
       ["Einführung des VAR 2018", "Videobeweis bei der WM", "Erstmals bei einer Weltmeisterschaft im Einsatz."]]'::jsonb,
     '[["Handschlag der Gegner nach dem Spiel", "Das ist kein Wendepunkt auf diesem Brett."],
       ["München 1972", "Das Attentat auf die Spiele fehlt in dieser Liste."]]'::jsonb),

    ('sport', 'sportstaetten-begriffe', 'Orte des Sports',
     'Was bezeichnet der Begriff?',
     'medium', 'Stadion', 'https://de.wikipedia.org/wiki/Stadion',
     '[["Tartanbahn", "Kunststoffbelag der Laufbahn", "Löste ab 1968 die Aschenbahn ab."],
       ["Velodrom", "Radrennbahn mit Steilkurven", "Die Überhöhung erreicht über vierzig Grad."],
       ["Halfpipe", "Halbrohr für Sprünge", "Aus Schnee, Holz oder Beton."],
       ["Tatami", "Mattenfläche im Kampfsport", "Begrenzt zugleich den Kampfbereich."],
       ["Green", "Kurzrasen ums Loch", "Hier wird nur noch geputtet."],
       ["Oktogon", "Achteckiger Käfig", "Kampffläche im Mixed Martial Arts."],
       ["Bullpen", "Aufwärmzone der Werfer", "Seitlich neben dem Baseballfeld."],
       ["Schanzentisch", "Absprungkante beim Skispringen", "Von hier zählt die Weite."],
       ["Peloton-Zielgerade", "Letzte Meter eines Radrennens", "Oft nur wenige Zentimeter entscheiden."],
       ["Faceoff-Punkt", "Anspielpunkt im Eishockey", "Neun davon sind aufs Eis gemalt."],
       ["Boxengasse", "Bereich für Reifenwechsel", "Mit strikt begrenztem Tempo."],
       ["Trockendock der Ruderer", "Bootshaus am Wasser", "Hier lagern die Achter zwischen den Trainings."]]'::jsonb,
     '[["Zielhang beim Skirennen", "Kein Begriff auf diesem Brett meint das."],
       ["Sprungturm im Schwimmbad", "Er steht nicht in dieser Liste."]]'::jsonb),

    ('sport', 'sport-mathematik', 'Zahlen des Sports',
     'Welche Zahl gehört dazu?',
     'hard', 'Sportart', 'https://de.wikipedia.org/wiki/Sportart',
     '[["Löcher einer Golfrunde", "18", "Neun hin, neun zurück."],
       ["Felder eines Schachbretts", "64", "Acht mal acht, abwechselnd hell und dunkel."],
       ["Steine eines Curling-Teams", "8", "Je zwei pro Spieler."],
       ["Runden eines Profiboxkampfs", "12", "Früher waren fünfzehn üblich."],
       ["Ringe einer Zielscheibe", "10", "Der innerste zählt am meisten."],
       ["Spieler einer Wasserballmannschaft", "7", "Sechs Feldspieler und ein Torwart."],
       ["Meter zur Dartscheibe", "2,37", "Gemessen von der Abwurflinie."],
       ["Punkte für einen Touchdown", "6", "Der Zusatzpunkt kommt danach."],
       ["Sätze für einen Grand-Slam-Sieg der Männer", "3", "Best of five, drei Gewinnsätze."],
              ["Minuten Strafzeit im Eishockey", "2", "Bei schweren Vergehen fünf."]]'::jsonb,
     '[["11", "Die Spielerzahl im Fußball, nach der hier keine Zeile fragt."],
       ["26", "Keine Zahl auf diesem Brett meint das."]]'::jsonb),

    ('sport', 'sportarten-laender-dominanz', 'Länder & ihre Sportarten',
     'Welches Land prägt diese Sportart?',
     'medium', 'Sport', 'https://de.wikipedia.org/wiki/Sport',
     '[["Sumo", "Japan", "Nationalsport mit jahrhundertealtem Zeremoniell."],
       ["Cricket", "Indien", "Die Liga dort ist die größte der Welt."],
       ["Eishockey", "Kanada", "Nationalsport im Winter."],
       ["Sepak Takraw", "Malaysia", "Volleyball nur mit Fuß, Knie und Kopf."],
       ["Hurling", "Irland", "Eines der schnellsten Feldspiele überhaupt."],
       ["Pelota", "Baskenland", "Der Ball wird gegen eine Wand geschlagen."],
       ["Langlauf", "Norwegen", "Kinder lernen es fast wie das Gehen."],
       ["Taekwondo", "Südkorea", "Aus mehreren Schulen zusammengeführt."],
       ["Capoeira", "Brasilien", "Kampf, Tanz und Musik zugleich."],
       ["Bandy", "Schweden", "Eishockey auf Fußballfeldgröße."],
       ["Kabaddi", "Bangladesch", "Angreifer müssen ohne Luftholen zurückkommen."],
       ["Rugby Union", "Neuseeland", "Der Haka vor jedem Länderspiel."]]'::jsonb,
     '[["Kenia", "Der Langstreckenlauf wäre die Sportart dazu, und die fehlt hier."],
       ["Ungarn", "Der Wasserball steht nicht auf diesem Brett."]]'::jsonb),

    ('sport', 'trainerlegenden', 'Trainer & ihre Handschrift',
     'Wofür steht dieser Name an der Seitenlinie?',
     'hard', 'Sport', 'https://de.wikipedia.org/wiki/Sport',
     '[["Rinus Michels", "Totaler Fußball", "Jeder Spieler kann jede Position ausfüllen."],
       ["Arrigo Sacchi", "Ballorientierte Viererkette", "Verschieben als Einheit statt Manndeckung."],
       ["Pep Guardiola", "Ballbesitz als Prinzip", "Der Gegner soll den Ball gar nicht erst bekommen."],
       ["Jürgen Klopp", "Gegenpressing", "Der Moment nach dem Ballverlust ist der beste."],
       ["Helenio Herrera", "Catenaccio", "Die Abwehr mit freiem Ausputzer dahinter."],
       ["Phil Jackson", "Triangle Offense", "Elf Meisterschaften mit zwei Teams."],
       ["Vince Lombardi", "Disziplin im Football", "Die Trophäe des Super Bowl trägt seinen Namen."],
       ["Bill Belichick", "Anpassung an jeden Gegner", "Jede Woche ein neuer Spielplan."],
       ["Sepp Herberger", "Der Ball ist rund", "Sein Satz überlebte das Wunder von Bern."],
       ["Anatoli Tarassow", "Sowjetische Eishockeyschule", "Ballett und Schach als Training."]]'::jsonb,
     '[["Ottmar Hitzfeld", "Der Doppelsieger der Champions League fehlt auf diesem Brett."],
       ["Alex Ferguson", "Die lange Ära in Manchester steht nicht in dieser Liste."]]'::jsonb),

    ('sport', 'sportmedien', 'Sport & Medien',
     'Was verbirgt sich dahinter?',
     'medium', 'Sport', 'https://de.wikipedia.org/wiki/Sport',
     '[["Konferenzschaltung", "Wechsel zwischen Parallelspielen", "Am Bundesliga-Samstag seit Jahrzehnten üblich."],
       ["Zeitlupe von hinten", "Überprüfung strittiger Szenen", "Erst die Wiederholung entscheidet."],
       ["Sportschau", "Zusammenfassung am Abend", "Läuft seit 1961."],
       ["Torlinientechnik", "Elektronische Torentscheidung", "Ein Signal geht an die Uhr des Schiedsrichters."],
       ["Hawk-Eye", "Berechnete Ballflugbahn", "Zuerst im Cricket, dann im Tennis."],
       ["Onboard-Kamera", "Blick aus dem Cockpit", "Zeigt Lenkbewegungen und Tempo."],
       ["Spidercam", "Seilkamera über dem Feld", "Bewegt sich frei über der Spielfläche."],
       ["Photofinish", "Zielbild in Tausendstelsekunden", "Ein Schlitzverschluss belichtet die Ziellinie."],
       ["Kommentatorenkabine", "Arbeitsplatz über der Tribüne", "Mit Blick auf das ganze Feld."],
       ["Rechtepaket", "Übertragungslizenz einer Liga", "Größte Einnahmequelle des Profisports."]]'::jsonb,
     '[["Radioreportage vom Spielfeldrand", "Sie fehlt auf diesem Brett."],
       ["Livestream über das Internet", "Er steht nicht in dieser Liste."]]'::jsonb),

    ('sport', 'wintersport-orte', 'Wintersportorte & Länder',
     'In welchem Land liegt der Ort?',
     'medium', 'Wintersport', 'https://de.wikipedia.org/wiki/Wintersport',
     '[["Kitzbühel", "Österreich", "Die Streif gilt als schwerste Abfahrt."],
       ["Wengen", "Schweiz", "Das Lauberhornrennen ist das längste im Weltcup."],
       ["Val d''Isère", "Frankreich", "Austragungsort auf der Face de Bellevarde."],
       ["Cortina d''Ampezzo", "Italien", "Schon 1956 Olympiaort."],
       ["Oberstdorf", "Deutschland", "Auftakt der Vierschanzentournee."],
       ["Holmenkollen", "Norwegen", "Traditionsreichste Schanze des Landes."],
       ["Ruka", "Finnland", "Weltcupauftakt im hohen Norden."],
       ["Åre", "Schweden", "Mehrfach Gastgeber der Ski-WM."],
       ["Planica", "Slowenien", "Hier fielen viele Skiflugrekorde."],
       ["Whistler", "Kanada", "Alpinort der Spiele von 2010."],
       ["Sapporo", "Japan", "Erste Winterspiele in Asien, 1972."],
       ["Zakopane", "Polen", "Skisprungfeste vor riesigem Publikum."]]'::jsonb,
     '[["Tschechien", "Špindlerův Mlýn läge dort, und der Ort fehlt auf dem Brett."],
       ["USA", "Aspen steht nicht in dieser Liste."]]'::jsonb),

    ('sport', 'ballsport-varianten', 'Verwandte Ballsportarten',
     'Was unterscheidet die Sportart?',
     'hard', 'Mannschaftssport',
     'https://de.wikipedia.org/wiki/Mannschaftssport',
     '[["Futsal", "Hallenfußball mit kleinem Ball", "Der Ball springt bewusst wenig."],
       ["Beachsoccer", "Fußball im Sand", "Barfuß und mit fliegendem Wechsel."],
       ["Faustball", "Ball darf aufspringen", "Geschlagen wird mit Faust oder Unterarm."],
       ["Korbball", "Korb ohne Brett", "Vor allem im Schulsport verbreitet."],
       ["Netball", "Kein Dribbling erlaubt", "Verbreitet in Commonwealth-Ländern."],
       ["Feldhockey", "Nur eine Schlägerseite", "Die runde Seite bleibt ungenutzt."],
       ["Unihockey", "Leichter Kunststoffschläger", "In der Halle mit Lochball."],
       ["Australian Football", "Vier Torpfosten", "Punkte je nach getroffenem Torpfosten."],
       ["Gaelic Football", "Fangen und Fußspiel gemischt", "Alle vier Schritte muss geprellt werden."],
       ["Wasserball", "Spiel ohne Bodenkontakt", "Nur der Torwart darf mit beiden Händen fassen."],
       ["Ultimate Frisbee", "Wurfscheibe ohne Schiedsrichter", "Die Spieler regeln Fouls selbst."],
       ["Rollhockey", "Hockey auf Rollschuhen", "Vor allem in Portugal und Spanien beliebt."]]'::jsonb,
     '[["Fußball auf Kunstrasen statt Naturrasen", "Der Belag macht keine eigene Sportart."],
       ["Basketball mit drei gegen drei", "Das 3x3 fehlt auf diesem Brett."]]'::jsonb),

    ('sport', 'sportbegriffe-herkunft', 'Woher der Name kommt',
     'Woher stammt die Bezeichnung?',
     'hard', 'Sportjargon', 'https://de.wikipedia.org/wiki/Sportjargon',
     '[["Marathon", "Ort einer Schlacht", "Nach dem Läufer, der den Sieg meldete."],
       ["Derby", "Englischer Adliger", "Ein Earl stiftete das Pferderennen."],
       ["Slalom", "Norwegisches Wort", "Bedeutet abschüssige Skispur."],
       ["Karate", "Leere Hand", "Kampf ohne Waffen."],
       ["Judo", "Sanfter Weg", "Nachgeben, um zu siegen."],
       ["Tennis", "Französischer Zuruf", "Von tenez, haltet, beim Aufschlag."],
       ["Golf", "Schottisch-niederländisch", "Vermutlich von kolf, der Keule."],
       ["Rugby", "Englische Schule", "Dort soll ein Schüler den Ball aufgenommen haben."],
       ["Badminton", "Englischer Landsitz", "Dort wurde das indische Spiel gespielt."],
       ["Volleyball", "Flugball", "Der Ball wird geschlagen, bevor er aufkommt."],
       ["Curling", "Schottisches Verb", "Von der kurvigen Bahn des Steins."],
       ["Biathlon", "Zweikampf", "Griechisch für zwei Wettkämpfe."]]'::jsonb,
     '[["Griechisch für Wettlauf", "Kein Name auf diesem Brett kommt daher."],
       ["Nach einem Erfinder benannt", "Keine Bezeichnung in dieser Liste geht so zurück."]]'::jsonb),

    ('sport', 'sportverbaende-sitze', 'Verbände & ihre Sitze',
     'Wo hat der Verband seinen Sitz?',
     'hard', 'Sportverband', 'https://de.wikipedia.org/wiki/Sportverband',
     '[["FIFA", "Zürich", "Seit 1932 in der Schweiz ansässig."],
       ["Internationales Olympisches Komitee", "Lausanne", "Seit 1915 am Genfersee."],
       ["UEFA", "Nyon", "Ebenfalls in der Westschweiz."],
       ["FIA", "Paris", "Dachverband auch der Formel 1."],
       ["World Athletics", "Monaco", "Zog 1993 aus London dorthin."],
       ["FIS", "Oberhofen", "Skisport am Thunersee verwaltet."],
       ["NBA", "New York", "Zentrale an der Fifth Avenue."],
       ["Internationaler Tennisverband", "London", "Sitz im Stadtteil Roehampton."],
       ["Welt-Anti-Doping-Agentur", "Montreal", "Gegründet 1999 nach der Festina-Affäre."],
       ["Internationaler Radsportverband", "Aigle", "Mit eigenem Weltradsportzentrum."],
       ["Deutscher Olympischer Sportbund", "Frankfurt", "Dachverband des deutschen Sports."]]'::jsonb,
     '[["Genf", "Kein Verband auf diesem Brett sitzt dort."],
       ["Brüssel", "Auch dort hat keiner in dieser Liste seinen Sitz."]]'::jsonb),

    ('sport', 'sport-koerper', 'Körper & Leistung',
     'Was beschreibt der Begriff?',
     'hard', 'Sport', 'https://de.wikipedia.org/wiki/Sport',
     '[["VO2max", "Maximale Sauerstoffaufnahme", "Kennzahl der Ausdauerleistung."],
       ["Laktatschwelle", "Grenze der Dauerbelastung", "Darüber übersäuert die Muskulatur."],
       ["Superkompensation", "Erholung über das Ausgangsniveau", "Deshalb gehören Pausen zum Training."],
       ["Muskelkater", "Feinste Faserrisse", "Nicht die früher vermutete Milchsäure."],
       ["Höhentraining", "Anpassung an dünne Luft", "Der Körper bildet mehr rote Blutkörperchen."],
       ["Tapering", "Belastung vor dem Wettkampf", "Damit die Form auf den Punkt kommt."],
       ["Schnellkraft", "Kraft in kürzester Zeit", "Entscheidend bei Sprung und Wurf."],
       ["Ausdauerschwelle", "Tempo über lange Strecken", "Grundlage jedes Marathonplans."],
       ["Runner''s High", "Euphorie bei langer Belastung", "Körpereigene Botenstoffe sind beteiligt."],
       ["Übertraining", "Leistungsabfall trotz Mehrarbeit", "Der Körper kommt nicht mehr hinterher."]]'::jsonb,
     '[["Ruhepuls", "Ein Maß für die Fitness, aber keine Antwort auf diesem Brett."],
       ["Körperfettanteil", "Er steht nicht in dieser Liste."]]'::jsonb),

    ('sport', 'olympische-sportarten-wandel', 'Olympia im Wandel',
     'Was gilt für diese Sportart bei Olympia?',
     'hard', 'Olympische Spiele',
     'https://de.wikipedia.org/wiki/Olympische_Spiele',
     '[["Tauziehen", "Aus dem Programm gestrichen", "Zwischen 1900 und 1920 im Programm."],
       ["Skateboarding", "Seit 2021 im Programm", "In Tokio erstmals ausgetragen."],
       ["Sportklettern", "Ebenfalls seit Tokio dabei", "Mit Bouldern, Lead und Speed."],
       ["Golf", "Nach langer Pause zurück", "Ab 2016 wieder olympisch."],
       ["Baseball", "Mehrfach aufgenommen und gestrichen", "Zuletzt in Tokio wieder dabei."],
       ["Breaking", "2024 erstmals ausgetragen", "In Paris als Wettkampf im Tanzduell."],
       ["Kunstwettbewerbe", "Bis 1948 medaillenwürdig", "Es gab Gold für Malerei und Dichtung."],
       ["Snowboard", "Seit 1998 olympisch", "In Nagano erstmals im Programm."],
       ["Trampolinturnen", "Seit 2000 dabei", "In Sydney aufgenommen."],
       ["Softball", "Nur zeitweise im Programm", "Zwischen 1996 und 2008, dann wieder 2021."]]'::jsonb,
     '[["Squash", "Es wurde lange abgelehnt und fehlt auf diesem Brett."],
       ["Cricket", "Die Rückkehr 2028 steht nicht in dieser Liste."]]'::jsonb),

    ('sport', 'rekordjagd', 'Rekorde & ihre Geschichte',
     'Was zeichnet den Rekord aus?',
     'hard', 'Sportgeschichte',
     'https://de.wikipedia.org/wiki/Sportgeschichte',
     '[["Vier-Minuten-Meile", "Lange für unmöglich gehalten", "1954 zuerst unterboten, danach von vielen."],
       ["Sprung von Bob Beamon", "Jahrzehnte unerreicht", "Der Weitsprung von 1968 hielt 23 Jahre."],
       ["Neunundzwanzig Weltrekorde Bubkas", "Zentimeterweise gesteigert", "Jede Verbesserung brachte eine Prämie."],
       ["Perfekte Zehn von 1976", "Anzeigetafel überfordert", "Sie zeigte 1,00 statt 10,00."],
       ["Marathon unter zwei Stunden", "Außerhalb der Wertung gelaufen", "Mit Tempomachern und idealer Strecke."],
       ["Der Fosbury-Flop", "Technik statt Kraft", "Rückwärts über die Latte."],
       ["Sieben Tour-Siege gestrichen", "Titel nachträglich aberkannt", "Die Jahre bleiben ohne Sieger."],
       ["Höhenrekord im Fallschirmsprung", "Sprung aus der Stratosphäre", "Mit Überschallgeschwindigkeit im freien Fall."],
       ["Schnellster Torhüter-Treffer", "Treffer über das Feld", "Wind und ein weit vorgerückter Kollege."],
       ["Längste Ungeschlagen-Serie", "Saison ohne Niederlage", "In England zuletzt 2004 gelungen."]]'::jsonb,
     '[["Der erste Weltrekord überhaupt", "Kein Rekord auf diesem Brett ist so beschrieben."],
       ["Rekord, der nie anerkannt wurde", "So etwas steht nicht in dieser Liste."]]'::jsonb),

    ('sport', 'sportkleidung', 'Ausrüstung & Vorschrift',
     'Warum trägt man das?',
     'medium', 'Sportgerät',
     'https://de.wikipedia.org/wiki/Sportger%C3%A4t',
     '[["Stollenschuhe", "Halt auf weichem Boden", "Länge und Zahl je nach Untergrund."],
       ["Mundschutz", "Schutz der Zähne", "Im Kampfsport und Hockey Pflicht."],
       ["Schwimmbrille", "Klare Sicht unter Wasser", "Erst seit den 1970ern im Wettkampf erlaubt."],
       ["Startblock", "Fester Abdruck beim Sprint", "Mit Fehlstart-Sensoren ausgestattet."],
       ["Handschuhe im Torwartspiel", "Griff und Dämpfung", "Das Latex haftet erst leicht angefeuchtet."],
       ["Helm im Radrennen", "Schutz bei Stürzen", "Seit 2003 im Profifeld vorgeschrieben."],
       ["Kompressionsstrümpfe", "Unterstützung der Venen", "Sollen die Erholung beschleunigen."],
       ["Magnesia", "Trockene Hände am Gerät", "Im Turnen und beim Klettern üblich."],
       ["Steigfelle", "Halt beim Aufstieg", "Gleiten vorwärts, greifen rückwärts."],
       ["Bindung beim Ski", "Auslösen bei Sturz", "Der Wert wird nach Gewicht eingestellt."]]'::jsonb,
     '[["Trikot mit Rückennummer", "Es dient der Erkennbarkeit, danach fragt hier keine Zeile."],
       ["Schienbeinschoner", "Sie schützen das Bein, stehen aber nicht auf diesem Brett."]]'::jsonb),

    ('sport', 'sportarten-zaehlweise', 'Wie gewonnen wird',
     'Wie entscheidet sich der Sieg?',
     'hard', 'Sportart', 'https://de.wikipedia.org/wiki/Sportart',
     '[["Marathon", "Kürzeste Zeit gewinnt", "Gemessen ab dem Startschuss."],
       ["Weitsprung", "Größte Weite zählt", "Gemessen am hintersten Abdruck."],
       ["Turnen", "Kampfrichter vergeben Noten", "Schwierigkeit und Ausführung getrennt."],
       ["Boxen", "Punkte oder vorzeitiges Ende", "Drei Kampfrichter werten jede Runde."],
       ["Fußball", "Mehr Tore zählen", "Bei Gleichstand ein Unentschieden."],
       ["Tennis", "Sätze statt Gesamtpunkte", "Man kann mehr Punkte holen und verlieren."],
       ["Zehnkampf", "Punktetabelle über zehn Disziplinen", "Jede Leistung wird umgerechnet."],
       ["Segelregatta", "Platzierungen über mehrere Wettfahrten", "Das schlechteste Ergebnis darf gestrichen werden."],
       ["Golf", "Wenigste Schläge gewinnen", "Im Lochspiel zählen dagegen gewonnene Löcher."],
       ["Skispringen", "Weite und Haltungsnoten", "Wind und Anlauflänge werden verrechnet."],
       ["Formel 1", "Punkte über die Saison", "Der Sieger eines Rennens bekommt fünfundzwanzig."],
       ["Ringen", "Schultersieg oder Punkte", "Beide Schultern eine Sekunde am Boden."]]'::jsonb,
     '[["Höchste Punktzahl aus drei Versuchen", "Keine Sportart auf diesem Brett zählt so."],
       ["Das Los entscheidet", "So wird in dieser Liste nirgends gewonnen."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

-- The answers that belong to no category. Numbered after the pairs so the two
-- sets never collide on `position`, though nothing reads it for a fake: the
-- pool is shuffled before a player sees it, and the review lists fakes on their
-- own rather than in board order.
fakes as (
    select q.id                                         as quiz_id,
           k.value ->> 0                                as label,
           k.value ->> 1                                as explanation,
           (jsonb_array_length(sp.pairs) + k.ord)::int  as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.fakes) with ordinality k(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
),

paired as (
    insert into items (quiz_id, category_id, label, position, explanation)
    select f.quiz_id, c.id, f.answer, f.position, f.explanation
      from flat f
      join new_categories c
        on c.quiz_id = f.quiz_id
       and c.label = f.label
    returning id
)

-- Same table, `category_id` left null. Both inserts run in the one statement,
-- so `items_quiz_id_label_key` still sees the pairs above: a fake written to
-- repeat an answer already on its own board fails the file rather than becoming
-- a second row nobody can tell apart.
insert into items (quiz_id, category_id, label, position, explanation)
select k.quiz_id, null, k.label, k.position, k.explanation
  from fakes k;
