-- Technik, file 2 of 2. Twenty questions, medium and hard.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs) as (
    values

    ('technik', 'codes-standards', 'Codes & Kennnummern',
     'Was wird damit gekennzeichnet?',
     'hard', 'Code', 'https://de.wikipedia.org/wiki/Code',
     '[["ASCII", "Schriftzeichen in sieben Bit", "128 Zeichen, praktisch nur für Englisch."],
       ["Unicode", "Zeichen aller Schriften", "Auch Emoji haben darin einen festen Platz."],
       ["ISBN", "Bücher", "Die letzte Ziffer ist eine Prüfziffer."],
       ["IBAN", "Bankkonten", "Länderkürzel, Prüfziffer und Kontoangaben."],
       ["EAN", "Handelsware", "Der Strichcode auf der Verpackung."],
       ["IMEI", "Mobilfunkgeräte", "Gerätenummer, unabhängig von der SIM."],
       ["MAC-Adresse", "Netzwerkschnittstellen", "Wird beim Hersteller fest vergeben."],
       ["Fahrgestellnummer", "Fahrzeuge", "17 Stellen, weltweit eindeutig."],
       ["ISO 9001", "Qualitätsmanagement", "Zertifiziert Abläufe, nicht Produkte."],
       ["RFC", "Internetstandards", "Der Name heißt bescheiden Bitte um Kommentare."],
       ["DIN A4", "Papierformate", "Halbieren ergibt immer das nächste Format."],
       ["Morsecode", "Buchstaben als Töne", "Punkt und Strich, für die Telegrafie erfunden."]]'::jsonb),

    ('technik', 'motorentypen', 'Motoren & ihr Prinzip',
     'Wie arbeitet dieser Antrieb?',
     'hard', 'Verbrennungsmotor',
     'https://de.wikipedia.org/wiki/Verbrennungsmotor',
     '[["Ottomotor", "Zündung durch Funken", "Benzin und Luft werden gemischt und gezündet."],
       ["Dieselmotor", "Selbstzündung durch Verdichtung", "Die Luft wird so heiß, dass der Kraftstoff zündet."],
       ["Wankelmotor", "Kreiskolben statt Hubkolben", "Ein Dreiecksläufer dreht sich exzentrisch."],
       ["Zweitaktmotor", "Arbeitstakt bei jeder Umdrehung", "Leicht und einfach, dafür schmutzig."],
       ["Stirlingmotor", "Verbrennung von außen", "Arbeitet mit einem geschlossenen Gasvolumen."],
       ["Elektromotor", "Magnetfelder treiben den Läufer", "Nahezu volles Drehmoment ab dem Stillstand."],
       ["Gasturbine", "Kontinuierlicher Gasstrom", "Verdichter, Brennkammer und Turbine auf einer Welle."],
       ["Turboprop", "Turbine treibt den Propeller", "Auf Kurzstrecken sparsamer als der Jet."],
       ["Raketentriebwerk", "Rückstoß ohne Außenluft", "Funktioniert auch im Vakuum."],
       ["Hybridantrieb", "Zwei Antriebe kombiniert", "Der Verbrenner läuft nur im günstigen Bereich."]]'::jsonb),

    ('technik', 'werkstoffe', 'Werkstoffe & Eigenschaften',
     'Was zeichnet den Werkstoff aus?',
     'hard', 'Werkstoff', 'https://de.wikipedia.org/wiki/Werkstoff',
     '[["Stahl", "Eisen mit wenig Kohlenstoff", "Der Kohlenstoffgehalt entscheidet über Härte."],
       ["Aluminium", "Leicht und korrosionsfest", "Eine dünne Oxidschicht schützt von selbst."],
       ["Kupfer", "Sehr guter Stromleiter", "Deshalb steckt es in fast jedem Kabel."],
       ["Beton", "Druckfest, aber zugschwach", "Deshalb wird er mit Stahl bewehrt."],
       ["Stahlbeton", "Druck und Zug zugleich", "Beide Baustoffe dehnen sich bei Wärme fast gleich."],
       ["Kohlenstofffaser", "Steif bei geringem Gewicht", "In Kunstharz eingebettet zum Verbundwerkstoff."],
       ["Glas", "Erstarrte Schmelze ohne Kristall", "Physikalisch weder fest noch flüssig im üblichen Sinn."],
       ["Technische Keramik", "Hitzefest und hart", "Bleibt formstabil, wo Metall längst weich ist."],
       ["Gummi", "Elastisch und rückstellend", "Vulkanisation vernetzt die Molekülketten."],
       ["Thermoplast", "Bei Wärme formbar", "Lässt sich mehrfach einschmelzen."],
       ["Holz", "Nachwachsend und faserig", "Trägt längs der Fasern deutlich mehr als quer."],
       ["Titan", "Fest, leicht und körperverträglich", "Teuer, weil die Gewinnung aufwendig ist."]]'::jsonb),

    ('technik', 'zeitmessung', 'Uhren & Zeitmessung',
     'Womit misst diese Uhr die Zeit?',
     'hard', 'Uhr', 'https://de.wikipedia.org/wiki/Uhr',
     '[["Sonnenuhr", "Wandernder Schatten", "Funktioniert nur bei Sonnenschein."],
       ["Wasseruhr", "Gleichmäßiger Ausfluss", "Schon im alten Ägypten benutzt."],
       ["Sanduhr", "Rinnender Sand", "Misst eine feste Spanne, keine Uhrzeit."],
       ["Pendeluhr", "Schwingung eines Pendels", "Die Länge des Pendels bestimmt den Takt."],
       ["Unruhuhr", "Schwingende Unruh mit Spiralfeder", "Machte tragbare Uhren möglich."],
       ["Quarzuhr", "Schwingender Kristall", "32768 Schwingungen je Sekunde."],
       ["Atomuhr", "Übergang im Cäsiumatom", "Definiert heute die Sekunde."],
       ["Funkuhr", "Empfangenes Zeitsignal", "Stellt sich selbst nach einem Langwellensender."],
       ["Schiffschronometer", "Ganggenauigkeit auf See", "Machte die Bestimmung der Länge möglich."],
       ["Stoppuhr", "Gemessene Zeitspanne", "Zeigt keine Tageszeit an."]]'::jsonb),

    ('technik', 'drucktechnik', 'Druckverfahren',
     'Wie überträgt das Verfahren die Farbe?',
     'hard', 'Drucktechnik', 'https://de.wikipedia.org/wiki/Drucktechnik',
     '[["Hochdruck", "Erhabene Stellen drucken", "Prinzip des Buchdrucks von Gutenberg."],
       ["Tiefdruck", "Farbe sitzt in Vertiefungen", "Für sehr hohe Auflagen wirtschaftlich."],
       ["Flachdruck", "Fett stößt Wasser ab", "Grundlage des heutigen Offsetdrucks."],
       ["Durchdruck", "Farbe durch ein Gewebe", "Beim Siebdruck auf T-Shirts und Plakaten."],
       ["Laserdruck", "Toner an geladene Stellen", "Anschließend eingebrannt durch Hitze."],
       ["Tintenstrahldruck", "Kleinste Tröpfchen", "Ausgestoßen durch Hitze oder Piezokristall."],
       ["Thermodruck", "Hitze auf Spezialpapier", "Kassenbons verblassen deshalb mit der Zeit."],
       ["Nadeldruck", "Anschlag durch ein Farbband", "Einziges Verfahren für Durchschläge."],
       ["3D-Druck", "Aufbau in dünnen Schichten", "Material wird hinzugefügt statt abgetragen."],
       ["Plotten", "Gezeichnete Linien", "Stift oder Messer folgen einer Bahn."]]'::jsonb),

    ('technik', 'verschluesselung', 'Verschlüsselung',
     'Was steckt hinter dem Verfahren?',
     'hard', 'Kryptographie',
     'https://de.wikipedia.org/wiki/Kryptographie',
     '[["Cäsar-Chiffre", "Verschieben im Alphabet", "Mit 25 Versuchen geknackt."],
       ["Enigma", "Rotoren im Wechsel", "Die Verdrahtung änderte sich mit jedem Anschlag."],
       ["One-Time-Pad", "Einmal verwendeter Zufallsschlüssel", "Beweisbar sicher, aber unpraktisch."],
       ["AES", "Symmetrische Blockchiffre", "Ein Schlüssel für Ver- und Entschlüsselung."],
       ["RSA", "Öffentlicher und privater Schlüssel", "Beruht auf der Schwierigkeit der Faktorisierung."],
       ["Diffie-Hellman", "Schlüsselaustausch über offene Leitung", "Beide errechnen dasselbe Geheimnis."],
       ["TLS", "Verschlüsselte Webverbindung", "Das S in HTTPS."],
       ["PGP", "Verschlüsselte E-Mail", "Vertrauen entsteht über ein Netz von Signaturen."],
       ["Digitale Signatur", "Nachweis der Urheberschaft", "Mit dem privaten Schlüssel erzeugt."],
       ["Steganografie", "Verstecken statt Verschlüsseln", "Die Nachricht sieht aus wie ein harmloses Bild."]]'::jsonb),

    ('technik', 'robotik', 'Robotik & Automatisierung',
     'Was macht diese Maschine?',
     'medium', 'Robotik', 'https://de.wikipedia.org/wiki/Robotik',
     '[["Industrieroboter", "Schweißen und Montieren", "Arbeitet meist hinter einem Schutzzaun."],
       ["Kollaborierender Roboter", "Arbeitet neben dem Menschen", "Stoppt bei Berührung sofort."],
       ["Fahrerloses Transportfahrzeug", "Transport durch die Halle", "Folgt Markierungen oder Karten."],
       ["Drohne", "Fliegt unbemannt", "Von der Vermessung bis zur Paketzustellung."],
       ["Exoskelett", "Verstärkt die Körperkraft", "Entlastet beim Heben schwerer Lasten."],
       ["Melkroboter", "Melkt ohne Personal", "Die Kuh entscheidet selbst, wann sie kommt."],
       ["Saugroboter", "Reinigt den Boden allein", "Erstellt dabei eine Karte der Wohnung."],
       ["Chirurgieroboter", "Führt Instrumente ruhig", "Der Arzt steuert von der Konsole aus."],
       ["Rover", "Fährt über fremde Planeten", "Muss verzögerte Befehle verkraften."],
       ["Pick-and-Place-Automat", "Setzt Bauteile auf Platinen", "Zehntausende Bauteile je Stunde."]]'::jsonb),

    ('technik', 'satellitensysteme', 'Satellitensysteme & Betreiber',
     'Wer betreibt das System?',
     'hard', 'Satellit', 'https://de.wikipedia.org/wiki/Satellit',
     '[["GPS", "USA", "Ursprünglich rein militärisch betrieben."],
       ["GLONASS", "Russland", "Nach dem Zerfall der Sowjetunion neu aufgebaut."],
       ["Galileo", "Europäische Union", "Bewusst unter ziviler Kontrolle."],
       ["Beidou", "China", "Seit 2020 weltweit verfügbar."],
       ["NavIC", "Indien", "Deckt vor allem den eigenen Subkontinent ab."],
       ["QZSS", "Japan", "Satelliten stehen lange hoch über Ostasien."],
       ["Starlink", "SpaceX", "Tausende Satelliten in niedriger Umlaufbahn."],
       ["Iridium", "Iridium Communications", "Satellitentelefonie bis in die Polarregionen."],
       ["Sentinel", "Europäische Weltraumorganisation", "Erdbeobachtung im Programm Copernicus."],
       ["Meteosat", "EUMETSAT", "Wetterbilder aus 36000 Kilometern Höhe."],
       ["Hubble", "NASA und ESA", "Seit 1990 im Orbit, mehrfach repariert."],
       ["Kuiper", "Amazon", "Antwort auf die Satelliteninternet-Konkurrenz."]]'::jsonb),

    ('technik', 'brueckentypen', 'Brückentypen',
     'Wie trägt diese Brücke die Last?',
     'hard', 'Brücke', 'https://de.wikipedia.org/wiki/Br%C3%BCcke',
     '[["Balkenbrücke", "Träger auf Stützen", "Einfachste und häufigste Bauform."],
       ["Bogenbrücke", "Druck in die Widerlager", "Schon die Römer bauten so."],
       ["Hängebrücke", "Tragseile über hohen Pylonen", "Erlaubt die größten Spannweiten."],
       ["Schrägseilbrücke", "Seile direkt zum Pylon", "Steifer als die Hängebrücke."],
       ["Fachwerkbrücke", "Dreiecke aus Stäben", "Kräfte laufen nur längs der Stäbe."],
       ["Auslegerbrücke", "Frei vorkragende Arme", "Kommt ohne Gerüst im Fluss aus."],
       ["Klappbrücke", "Fahrbahn wird hochgeklappt", "Macht die Durchfahrt für Schiffe frei."],
       ["Drehbrücke", "Fahrbahn schwenkt seitlich", "Braucht einen mittigen Drehpfeiler."],
       ["Hubbrücke", "Ganze Fahrbahn steigt an", "Bleibt dabei waagerecht."],
       ["Pontonbrücke", "Schwimmkörper tragen", "Schnell aufgebaut, oft nur vorübergehend."],
       ["Aquädukt", "Führt Wasser statt Fahrzeuge", "Gefälle von wenigen Zentimetern je Kilometer."],
       ["Viadukt", "Lange Reihe von Pfeilern", "Überspannt ein ganzes Tal."]]'::jsonb),

    ('technik', 'haushaltstechnik', 'Haushaltsgeräte & ihr Prinzip',
     'Wie funktioniert das Gerät?',
     'medium', 'Haushaltsgerät',
     'https://de.wikipedia.org/wiki/Haushaltsger%C3%A4t',
     '[["Mikrowelle", "Regt Wassermoleküle an", "Erwärmt von innen heraus, nicht über die Oberfläche."],
       ["Kühlschrank", "Verdampfendes Kältemittel", "Die Wärme wandert nach hinten außen."],
       ["Induktionsherd", "Wirbelströme im Topfboden", "Die Platte selbst bleibt vergleichsweise kühl."],
       ["Wasserkocher", "Heizspirale mit Thermostat", "Der Dampf löst die Abschaltung aus."],
       ["Toaster", "Glühender Heizdraht", "Die Strahlungswärme bräunt das Brot."],
       ["Staubsauger", "Unterdruck durch Gebläse", "Der Filter hält den Staub zurück."],
       ["Waschmaschine", "Trommel, Lauge und Zeit", "Mechanik, Chemie und Temperatur zusammen."],
       ["Geschirrspüler", "Rotierende Sprüharme", "Heißes Wasser mit Reiniger unter Druck."],
       ["Wäschetrockner", "Warme Luft entzieht Feuchtigkeit", "Moderne Geräte gewinnen die Wärme zurück."],
       ["Dunstabzugshaube", "Fettfilter und Gebläse", "Im Umluftbetrieb zusätzlich Aktivkohle."]]'::jsonb),

    ('technik', 'audiotechnik', 'Audiotechnik',
     'Was tut dieses Gerät oder Verfahren?',
     'hard', 'Tontechnik', 'https://de.wikipedia.org/wiki/Tontechnik',
     '[["Mikrofon", "Wandelt Schall in Spannung", "Membran und Wandler, dynamisch oder kapazitiv."],
       ["Lautsprecher", "Wandelt Spannung in Schall", "Im Prinzip ein umgekehrtes Mikrofon."],
       ["Verstärker", "Hebt den Signalpegel", "Ohne ihn bewegt das Signal keine Membran."],
       ["Equalizer", "Hebt und senkt Frequenzbereiche", "Für Klangkorrektur im Raum."],
       ["Kompressor", "Verringert die Dynamik", "Leises wird lauter, Lautes gedämpft."],
       ["Hallgerät", "Simuliert einen Raum", "Aus trockener Aufnahme wird Kirche oder Halle."],
       ["Mischpult", "Führt viele Kanäle zusammen", "Pegel, Klang und Effektwege je Kanal."],
       ["Sampler", "Spielt aufgenommene Klänge", "Ein Ton wird über die Tastatur verteilt."],
       ["Synthesizer", "Erzeugt Klänge elektronisch", "Oszillator, Filter und Hüllkurve."],
       ["Phantomspeisung", "Versorgt Kondensatormikrofone", "48 Volt über dasselbe Kabel wie das Signal."]]'::jsonb),

    ('technik', 'datenbank-begriffe', 'Begriffe aus Datenbanken',
     'Was bezeichnet der Begriff?',
     'hard', 'Datenbank', 'https://de.wikipedia.org/wiki/Datenbank',
     '[["Primärschlüssel", "Macht eine Zeile eindeutig", "Kein zweiter Datensatz darf ihn haben."],
       ["Fremdschlüssel", "Verweis auf andere Tabelle", "Sichert, dass der Bezug wirklich existiert."],
       ["Index", "Beschleunigt das Suchen", "Kostet Platz und macht Schreiben langsamer."],
       ["Transaktion", "Ganz oder gar nicht", "Bei Fehlern wird alles zurückgerollt."],
       ["Join", "Verknüpft Tabellen", "Über gemeinsame Spalten zusammengeführt."],
       ["Normalisierung", "Vermeidet doppelte Daten", "Jede Information steht nur an einer Stelle."],
       ["Replikation", "Kopie auf Zweitserver", "Für Ausfallsicherheit und Leseverteilung."],
       ["Deadlock", "Gegenseitige Blockade", "Jeder wartet auf das, was der andere hält."],
       ["Cache", "Zwischenspeicher für Häufiges", "Spart den teuren Weg zur Platte."],
       ["Schema", "Bauplan der Tabellen", "Legt Spalten, Typen und Regeln fest."],
       ["Migration", "Änderung der Struktur", "Wird versioniert, damit sie nachvollziehbar bleibt."],
       ["Backup", "Sicherungskopie", "Ist erst dann eines, wenn die Rücksicherung geprüft wurde."]]'::jsonb),

    ('technik', 'programmiersprachen-einsatz', 'Programmiersprachen & Einsatz',
     'Wofür wird die Sprache vor allem genutzt?',
     'medium', 'Programmiersprache',
     'https://de.wikipedia.org/wiki/Programmiersprache',
     '[["Python", "Datenanalyse und Skripte", "Lesbarkeit steht im Vordergrund."],
       ["JavaScript", "Programme im Browser", "Läuft heute auch auf dem Server."],
       ["C", "Systemnahe Programmierung", "Betriebssysteme und Treiber."],
       ["Java", "Große Unternehmensanwendungen", "Läuft auf einer virtuellen Maschine."],
       ["Swift", "Apps für Apple-Geräte", "2014 als Nachfolger von Objective-C vorgestellt."],
       ["Kotlin", "Android-Entwicklung", "Von Google offiziell empfohlen."],
       ["R", "Statistik und Grafiken", "In der Forschung weit verbreitet."],
       ["Rust", "Sichere Systemsoftware", "Der Compiler verhindert ganze Fehlerklassen."],
       ["Go", "Netzwerkdienste", "Nebenläufigkeit ist eingebaut."],
       ["PHP", "Dynamische Webseiten", "Läuft auf einem großen Teil aller Webserver."],
       ["Fortran", "Numerische Simulation", "Seit 1957 im wissenschaftlichen Rechnen."],
       ["COBOL", "Bankensoftware", "Läuft in vielen Rechenzentren bis heute."]]'::jsonb),

    ('technik', 'netzwerkgeraete', 'Netzwerktechnik',
     'Welche Aufgabe hat das?',
     'hard', 'Rechnernetz', 'https://de.wikipedia.org/wiki/Rechnernetz',
     '[["Router", "Verbindet verschiedene Netze", "Entscheidet, wohin ein Paket als Nächstes geht."],
       ["Switch", "Verteilt im lokalen Netz", "Schickt Pakete nur an den richtigen Anschluss."],
       ["Hub", "Sendet an alle Anschlüsse", "Veraltet, weil ineffizient."],
       ["Gateway", "Übergang zwischen Welten", "Übersetzt zwischen unterschiedlichen Protokollen."],
       ["Proxy", "Stellvertreter für Anfragen", "Kann filtern, zwischenspeichern und verbergen."],
       ["Load Balancer", "Verteilt die Last", "Hält Dienste auch bei Ausfällen erreichbar."],
       ["Content Delivery Network", "Inhalte nah beim Nutzer", "Kürzere Wege, geringere Verzögerung."],
       ["DHCP", "Vergibt Adressen automatisch", "Ohne Konfiguration am Endgerät."],
       ["NAT", "Viele Geräte, eine Adresse", "Merkt sich, welche Antwort zu wem gehört."],
       ["VLAN", "Trennt Netze logisch", "Ein Kabel, mehrere getrennte Bereiche."],
       ["MTU", "Größte Paketlänge", "Zu große Pakete müssen zerlegt werden."],
       ["Latenz", "Verzögerung der Übertragung", "Für Spiele wichtiger als die Bandbreite."]]'::jsonb),

    ('technik', 'elektromobilitaet', 'Elektromobilität',
     'Was bedeutet der Begriff?',
     'medium', 'Elektroauto', 'https://de.wikipedia.org/wiki/Elektroauto',
     '[["Rekuperation", "Bremsenergie zurückgewinnen", "Der Motor arbeitet dabei als Generator."],
       ["Kilowattstunde", "Maß für den Energieinhalt", "Gibt an, wie viel der Akku speichert."],
       ["Wallbox", "Ladestation für zu Hause", "Lädt deutlich schneller als die Steckdose."],
       ["Schnellladen", "Laden mit Gleichstrom", "Der Gleichrichter steht in der Säule, nicht im Auto."],
       ["CCS", "Steckerstandard in Europa", "Vereint Wechsel- und Gleichstromladen."],
       ["Bidirektionales Laden", "Strom zurück ins Netz", "Das Auto wird zum Zwischenspeicher."],
       ["Ladekurve", "Leistung über den Ladestand", "Ab etwa 80 Prozent wird deutlich gedrosselt."],
       ["Range Extender", "Kleiner Verbrenner als Generator", "Lädt den Akku, treibt aber nicht an."],
       ["Feststoffakku", "Fester statt flüssiger Elektrolyt", "Verspricht mehr Energie und weniger Brandgefahr."],
       ["Wärmepumpe im Auto", "Heizen ohne viel Strom", "Verlängert die Reichweite im Winter."]]'::jsonb),

    ('technik', 'heimcomputer-konsolen', 'Heimcomputer & Konsolen',
     'Von welchem Hersteller stammt das Gerät?',
     'medium', 'Heimcomputer', 'https://de.wikipedia.org/wiki/Heimcomputer',
     '[["C64", "Commodore", "Meistverkaufter Heimcomputer aller Zeiten."],
       ["ZX Spectrum", "Sinclair", "Gummitastatur und Farbe auf dem Fernseher."],
       ["Apple II", "Apple", "Mit der Tabellenkalkulation VisiCalc im Büro angekommen."],
       ["IBM PC", "IBM", "Der offene Aufbau ermöglichte die Nachbauten."],
       ["Atari 2600", "Atari", "Machte Steckmodule zum Standard."],
       ["NES", "Nintendo", "Rettete den Konsolenmarkt nach dem Einbruch von 1983."],
       ["Mega Drive", "Sega", "Der große Rivale des Super Nintendo."],
       ["PlayStation", "Sony", "Setzte auf CD statt auf Module."],
       ["Xbox", "Microsoft", "Erste Konsole mit Festplatte serienmäßig."],
       ["Schneider CPC", "Amstrad", "In Deutschland unter anderem Namen verkauft."]]'::jsonb),

    ('technik', 'datentechnik-einheiten', 'Einheiten der Datentechnik',
     'Was gibt die Einheit an?',
     'hard', 'Byte', 'https://de.wikipedia.org/wiki/Byte',
     '[["Bit", "Kleinste Informationseinheit", "Entweder null oder eins."],
       ["Byte", "Acht Bit", "Reicht für ein Zeichen im ASCII-Code."],
       ["Kilobyte", "Tausend Byte", "Nach SI-Definition genau 1000."],
       ["Kibibyte", "1024 Byte", "Die Zweierpotenz, seit 1998 mit eigenem Namen."],
       ["Megabit pro Sekunde", "Übertragungsrate", "Internetanschlüsse werden so beworben."],
       ["Hertz", "Takt pro Sekunde", "Beim Prozessor meist in Gigahertz."],
       ["FLOPS", "Gleitkommaoperationen je Sekunde", "Maß für die Leistung von Supercomputern."],
       ["DPI", "Druckpunkte je Zoll", "Bestimmt die Feinheit des Ausdrucks."],
       ["PPI", "Bildpunkte je Zoll", "Entscheidet, ob man Bildpunkte sieht."],
       ["Baud", "Symbole je Sekunde", "Nicht dasselbe wie Bit pro Sekunde."]]'::jsonb),

    ('technik', 'ingenieure-bauten', 'Ingenieure & ihre Werke',
     'Womit ist der Name verbunden?',
     'hard', 'Ingenieur', 'https://de.wikipedia.org/wiki/Ingenieur',
     '[["Isambard Kingdom Brunel", "Great Western Railway", "Bahn, Tunnel und Dampfschiffe aus einer Hand."],
       ["John Roebling", "Brooklyn Bridge", "Er starb vor der Fertigstellung, sein Sohn führte weiter."],
       ["Nikola Tesla", "Wechselstromsystem", "Setzte sich gegen Edisons Gleichstrom durch."],
       ["Ferdinand Porsche", "Volkswagen Käfer", "Über zwanzig Millionen Stück gebaut."],
       ["Sergei Koroljow", "Sputnik", "Sein Name blieb zu Lebzeiten geheim."],
       ["Wernher von Braun", "Saturn V", "Vom Raketenprogramm der Wehrmacht zur NASA."],
       ["Fritz Todt", "Reichsautobahn", "Namensgeber einer berüchtigten Bauorganisation."],
       ["Gustave Eiffel", "Freiheitsstatue-Gerüst", "Das innere Tragwerk stammt von ihm."],
       ["Frank Whittle", "Strahltriebwerk", "Patentiert 1930, in Serie erst im Krieg."],
       ["Hedy Lamarr", "Frequenzsprungverfahren", "Grundgedanke moderner Funkübertragung."]]'::jsonb),

    ('technik', 'schiffstechnik', 'Schiffstechnik',
     'Was bezeichnet der Begriff am Schiff?',
     'hard', 'Schiff', 'https://de.wikipedia.org/wiki/Schiff',
     '[["Kiel", "Rückgrat des Rumpfes", "Läuft von vorn nach achtern durch."],
       ["Bug", "Vorderteil des Schiffes", "Seine Form entscheidet über den Widerstand."],
       ["Heck", "Hinterer Abschluss", "Dort sitzen meist Ruder und Schraube."],
       ["Ruderblatt", "Lenkt durch Wasserdruck", "Wirkt nur bei Fahrt durchs Wasser."],
       ["Schiffsschraube", "Treibt das Schiff an", "Zu hohe Drehzahl erzeugt Kavitation."],
       ["Schott", "Wasserdichte Trennwand", "Begrenzt, wie viel Wasser eindringen kann."],
       ["Tiefgang", "Eintauchtiefe des Rumpfes", "Entscheidet, welche Häfen erreichbar sind."],
       ["Freibord", "Abstand Wasserlinie zum Deck", "Die Lademarke am Rumpf zeigt die Grenze."],
       ["Ballastwasser", "Sorgt für Stabilität", "Muss heute behandelt werden, wegen eingeschleppter Arten."],
       ["Echolot", "Misst die Wassertiefe", "Über die Laufzeit eines Schallimpulses."],
       ["Anker", "Hält die Position", "Die Kette trägt mehr zur Haltekraft bei als das Eisen."],
       ["Stabilisatoren", "Dämpfen das Rollen", "Flossen unter Wasser, elektronisch gesteuert."]]'::jsonb),

    ('technik', 'gebaeudetechnik', 'Gebäudetechnik',
     'Wozu dient das im Haus?',
     'medium', 'Versorgungstechnik',
     'https://de.wikipedia.org/wiki/Versorgungstechnik',
     '[["Wärmedämmung", "Hält Wärme im Haus", "Senkt den Heizbedarf oft um die Hälfte."],
       ["Fußbodenheizung", "Heizt über große Flächen", "Kommt mit niedrigen Vorlauftemperaturen aus."],
       ["Fernwärme", "Wärme aus dem Leitungsnetz", "Nutzt Abwärme aus Kraftwerken mit."],
       ["Lüftungsanlage mit Wärmerückgewinnung", "Frische Luft ohne Wärmeverlust", "Die Abluft wärmt die Zuluft vor."],
       ["Brennwertkessel", "Nutzt die Abgaswärme mit", "Der Wasserdampf im Abgas wird kondensiert."],
       ["Smart Meter", "Zählt und meldet Verbrauch", "Macht zeitabhängige Tarife möglich."],
       ["Rauchwarnmelder", "Warnt vor Brandrauch", "In Wohnungen inzwischen überall Pflicht."],
       ["Regenwasserzisterne", "Sammelt Regenwasser", "Entlastet zugleich die Kanalisation."],
       ["Aufzugsschacht", "Führt die Kabine", "Gegengewicht spart Antriebsenergie."],
       ["Blitzschutzanlage", "Leitet Blitze ab", "Fangstange, Ableiter und Erder gehören zusammen."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
)

insert into items (quiz_id, category_id, label, position, explanation)
select f.quiz_id, c.id, f.answer, f.position, f.explanation
  from flat f
  join new_categories c
    on c.quiz_id = f.quiz_id
   and c.label = f.label;
