-- Technik, file 1 of 2. Twenty questions, medium und hard.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs, fakes) as (
    values

    ('technik', 'dateiformate', 'Dateiformate & ihr Zweck',
     'Wofür wird das Format verwendet?',
     'medium', 'Dateiformat', 'https://de.wikipedia.org/wiki/Dateiformat',
     '[["JPEG", "Fotos mit Verlust", "Kleine Dateien, dafür sichtbare Artefakte bei starker Kompression."],
       ["PNG", "Grafiken mit Transparenz", "Verlustfrei, deshalb größer als JPEG."],
       ["GIF", "Kurze Animationen", "Nur 256 Farben, dafür bewegt."],
       ["SVG", "Vektorgrafik", "Beliebig skalierbar, weil aus Formeln statt Pixeln."],
       ["MP3", "Musik in kleiner Datei", "Weggelassen wird, was das Ohr kaum hört."],
       ["WAV", "Unkomprimiertes Audio", "Studioqualität bei großem Speicherbedarf."],
       ["MP4", "Video mit Ton", "Heute der Standard für Streaming und Kameras."],
       ["PDF", "Seitengetreues Dokument", "Sieht auf jedem Gerät gleich aus."],
       ["CSV", "Tabellendaten als Text", "Werte, durch Kommas getrennt."],
       ["ZIP", "Gepacktes Archiv", "Mehrere Dateien in einer, komprimiert."],
       ["HTML", "Aufbau einer Webseite", "Beschreibt Struktur, nicht Aussehen."],
       ["EXE", "Ausführbares Programm", "Unter Windows direkt startbar."]]'::jsonb,
     '[["Tabelle mit Formeln und Formatierung", "Das wäre XLSX, und das fehlt auf diesem Brett."],
       ["Schriftart für den Rechner", "Die Datei TTF steht nicht in dieser Liste."]]'::jsonb),

    ('technik', 'netzwerk-ports', 'Netzwerkdienste & Ports',
     'Auf welchem Port läuft der Dienst üblicherweise?',
     'hard', 'Liste der Portnummern',
     'https://de.wikipedia.org/wiki/Liste_der_Portnummern',
     '[["HTTP", "80", "Unverschlüsselter Webverkehr."],
       ["HTTPS", "443", "Der verschlüsselte Nachfolger, heute die Regel."],
       ["SSH", "22", "Verschlüsselte Fernwartung."],
       ["FTP", "21", "Dateiübertragung, Steuerkanal."],
       ["Telnet", "23", "Unverschlüsselt und deshalb praktisch abgelöst."],
       ["SMTP", "25", "Versand von E-Mail zwischen Servern."],
       ["DNS", "53", "Übersetzt Namen in Adressen."],
       ["POP3", "110", "Holt E-Mail ab und löscht sie meist vom Server."],
       ["NTP", "123", "Hält Uhren im Netz synchron."],
       ["IMAP", "143", "Lässt Postfächer auf dem Server liegen."],
       ["RDP", "3389", "Fernzugriff auf einen Windows-Desktop."],
       ["PostgreSQL", "5432", "Standardport der Datenbank."]]'::jsonb,
     '[["3306", "Der Port von MySQL, und die Datenbank fehlt auf diesem Brett."],
       ["8080", "Ein häufiger Ausweichport für HTTP, hier aber keine Antwort."]]'::jsonb),

    ('technik', 'it-abkuerzungen', 'Abkürzungen der Informatik',
     'Wofür steht die Abkürzung?',
     'hard', 'Informatik', 'https://de.wikipedia.org/wiki/Informatik',
     '[["CPU", "Hauptprozessor", "Führt die Befehle eines Programms aus."],
       ["RAM", "Arbeitsspeicher", "Flüchtig: beim Ausschalten ist der Inhalt weg."],
       ["SSD", "Halbleiterlaufwerk", "Speicher ohne bewegliche Teile."],
       ["GPU", "Grafikprozessor", "Rechnet viele einfache Aufgaben parallel."],
       ["USB", "Universeller serieller Bus", "Ersetzte seriellen und parallelen Anschluss."],
       ["API", "Programmierschnittstelle", "Vereinbarung, wie Programme miteinander sprechen."],
       ["SQL", "Datenbank-Abfragesprache", "Beschreibt, was man will, nicht wie es geholt wird."],
       ["VPN", "Virtuelles privates Netz", "Tunnelt Verkehr verschlüsselt durch fremde Netze."],
       ["RAID", "Verbund mehrerer Festplatten", "Für Ausfallsicherheit oder Geschwindigkeit."],
       ["BIOS", "Startprogramm der Hardware", "Läuft vor dem Betriebssystem, heute meist UEFI."],
       ["URL", "Adresse einer Ressource", "Protokoll, Host und Pfad in einer Zeile."],
       ["IDE", "Integrierte Entwicklungsumgebung", "Editor, Compiler und Debugger in einem."]]'::jsonb,
     '[["Nur-Lese-Speicher", "Das wäre ROM, und das fehlt auf diesem Brett."],
       ["Adresse eines Geräts im Netz", "Die IP-Adresse steht nicht in dieser Liste."]]'::jsonb),

    ('technik', 'betriebssysteme-hersteller', 'Betriebssysteme & Hersteller',
     'Wer steht hinter dem System?',
     'medium', 'Betriebssystem',
     'https://de.wikipedia.org/wiki/Betriebssystem',
     '[["Windows", "Microsoft", "Seit 1985, lange der Standard auf Bürorechnern."],
       ["macOS", "Apple", "Beruht auf einem Unix-Kern."],
       ["Android", "Google", "2005 zugekauft, heute das meistgenutzte Mobilsystem."],
       ["Ubuntu", "Canonical", "Linux-Distribution mit festem Halbjahresrhythmus."],
       ["Red Hat Enterprise Linux", "Red Hat", "Linux mit langfristigem Support für Firmen."],
       ["Solaris", "Sun Microsystems", "Unix-System, das mit den Workstations groß wurde."],
       ["AIX", "IBM", "Unix für die eigenen Großrechner."],
       ["HarmonyOS", "Huawei", "Nach dem Ausschluss von Google-Diensten entwickelt."],
       ["OS/2", "IBM und Microsoft", "Gemeinsam begonnen, dann getrennt weitergeführt."],
       ["FreeBSD", "FreeBSD-Projekt", "Aus der Berkeley-Unix-Linie hervorgegangen."]]'::jsonb,
     '[["Oracle", "Oracle Linux käme von dort, und das fehlt auf diesem Brett."],
       ["Nokia", "Symbian stammte von dort, es steht nicht in dieser Liste."]]'::jsonb),

    ('technik', 'computerpioniere', 'Computerpioniere',
     'Wofür steht der Name?',
     'hard', 'Informatik', 'https://de.wikipedia.org/wiki/Informatik',
     '[["Alan Turing", "Turingmaschine", "Modell dessen, was überhaupt berechenbar ist."],
       ["Konrad Zuse", "Rechner Z3", "1941 in Berlin, der erste frei programmierbare Rechner."],
       ["John von Neumann", "Rechnerarchitektur", "Programm und Daten liegen im selben Speicher."],
       ["Claude Shannon", "Informationstheorie", "Führte das Bit als Maß der Information ein."],
       ["Grace Hopper", "Erster Compiler", "Übersetzte Klartextbefehle in Maschinencode."],
       ["Douglas Engelbart", "Computermaus", "1968 in der Mutter aller Demos vorgeführt."],
       ["Vint Cerf", "TCP/IP", "Regelt, wie Datenpakete durchs Internet finden."],
       ["Tim Berners-Lee", "World Wide Web", "Am CERN aus Hypertext und Netz zusammengefügt."],
       ["Linus Torvalds", "Linux-Kernel", "1991 als Studentenprojekt begonnen."],
       ["Steve Wozniak", "Apple I", "Er baute den Rechner, den Jobs verkaufte."],
       ["Edsger Dijkstra", "Kürzeste-Wege-Algorithmus", "Steckt in jedem Navigationsgerät."],
       ["Barbara Liskov", "Substitutionsprinzip", "Grundregel für saubere Vererbung."]]'::jsonb,
     '[["Erste Programmiererin der Geschichte", "Das wäre Ada Lovelace, und die fehlt hier."],
       ["Objektorientierung mit Smalltalk", "Alan Kay steht nicht auf diesem Brett."]]'::jsonb),

    ('technik', 'elektronik-bauteile', 'Elektronische Bauteile',
     'Was tut das Bauteil?',
     'hard', 'Elektrisches Bauelement',
     'https://de.wikipedia.org/wiki/Elektrisches_Bauelement',
     '[["Widerstand", "Begrenzt den Strom", "Setzt elektrische Energie in Wärme um."],
       ["Kondensator", "Speichert Ladung", "Lädt und entlädt sich, sperrt Gleichstrom."],
       ["Spule", "Speichert im Magnetfeld", "Wirkt Stromänderungen entgegen."],
       ["Diode", "Lässt Strom nur einseitig", "Grundlage jedes Gleichrichters."],
       ["Transistor", "Schaltet und verstärkt", "Baustein jedes digitalen Schaltkreises."],
       ["Leuchtdiode", "Wandelt Strom in Licht", "Braucht einen Vorwiderstand."],
       ["Relais", "Schaltet mit Magnetkraft", "Trennt Steuer- und Lastkreis."],
       ["Transformator", "Ändert die Spannung", "Funktioniert nur mit Wechselstrom."],
       ["Sicherung", "Unterbricht bei Überlast", "Ein Draht schmilzt, bevor die Leitung brennt."],
       ["Schwingquarz", "Gibt den Takt vor", "Schwingt mechanisch mit fester Frequenz."],
       ["Fotowiderstand", "Reagiert auf Licht", "Bei Helligkeit sinkt sein Widerstand."],
       ["Thermistor", "Reagiert auf Wärme", "Wird als Temperaturfühler eingesetzt."]]'::jsonb,
     '[["Wandelt Schall in Spannung", "Das Mikrofon ist kein Bauteil auf diesem Brett."],
       ["Erzeugt eine feste Ausgangsspannung", "Der Spannungsregler fehlt in dieser Liste."]]'::jsonb),

    ('technik', 'automarken-konzerne', 'Automarken & Konzerne',
     'Zu welchem Konzern gehört die Marke?',
     'hard', 'Kraftfahrzeughersteller',
     'https://de.wikipedia.org/wiki/Kraftfahrzeughersteller',
     '[["Bentley", "Volkswagen", "Seit 1998 im Konzern, nach einem Bieterstreit."],
       ["Mini", "BMW", "Aus der Rover-Übernahme geblieben."],
       ["Jaguar", "Tata Motors", "2008 von Ford an den indischen Konzern verkauft."],
       ["Volvo", "Geely", "Seit 2010 in chinesischem Besitz."],
       ["Opel", "Stellantis", "Erst PSA, dann der Zusammenschluss mit Fiat Chrysler."],
       ["Lexus", "Toyota", "1989 als Luxusmarke für den US-Markt gegründet."],
       ["Kia", "Hyundai", "Zwei Marken, ein Konzern aus Südkorea."],
       ["Acura", "Honda", "Erste japanische Luxusmarke in Nordamerika."],
       ["Infiniti", "Nissan", "Als Antwort auf Lexus gestartet."],
       ["Dacia", "Renault", "Seit 1999 französisch geführt."],
       ["Cadillac", "General Motors", "Traditionsmarke aus Detroit."],
       ["Ferrari", "Exor", "Seit 2016 eigenständig, kontrolliert von der Agnelli-Holding."]]'::jsonb,
     '[["Ford", "Lincoln gehörte dazu, und die Marke fehlt auf diesem Brett."],
       ["Mercedes-Benz Group", "Smart gehört dorthin, es steht nicht in dieser Liste."]]'::jsonb),

    ('technik', 'smartphone-technik', 'Technik im Smartphone',
     'Was steckt hinter dem Begriff?',
     'medium', 'Smartphone', 'https://de.wikipedia.org/wiki/Smartphone',
     '[["Bluetooth", "Funk auf kurze Distanz", "Benannt nach einem dänischen König."],
       ["NFC", "Bezahlen durch Auflegen", "Reichweite nur wenige Zentimeter."],
       ["GPS", "Ortung über Satelliten", "Braucht Sicht auf mehrere Satelliten."],
       ["LTE", "Mobilfunk der vierten Generation", "Löste UMTS ab, heute neben 5G im Einsatz."],
       ["WLAN", "Drahtloses lokales Netz", "Der Router spannt die Funkzelle auf."],
       ["OLED", "Selbstleuchtende Bildpunkte", "Schwarz bleibt wirklich dunkel, weil Pixel ausgehen."],
       ["Touchscreen", "Eingabe durch Berührung", "Meist kapazitiv, misst die Änderung des Feldes."],
       ["SIM-Karte", "Ausweis im Mobilfunknetz", "Heute oft nur noch als eSIM im Gerät."],
       ["IP68", "Staub- und wasserdicht", "Die erste Ziffer steht für Staub, die zweite für Wasser."],
       ["QR-Code", "Zweidimensionaler Strichcode", "Speichert deutlich mehr als ein Barcode."],
       ["Firmware", "Fest eingebaute Software", "Sitzt zwischen Hardware und Betriebssystem."],
       ["Gyroskop", "Erkennt Drehungen", "Dreht das Bild und stabilisiert die Kamera."]]'::jsonb,
     '[["Funk der fünften Generation", "Das wäre 5G, und das fehlt auf diesem Brett."],
       ["Entsperren per Fingerabdruck", "Der Sensor steht nicht in dieser Liste."]]'::jsonb),

    ('technik', 'flugzeuge-hersteller', 'Flugzeuge & Hersteller',
     'Wer hat das Flugzeug gebaut?',
     'medium', 'Flugzeug', 'https://de.wikipedia.org/wiki/Flugzeug',
     '[["747", "Boeing", "Der Jumbo mit dem markanten Buckel."],
       ["A380", "Airbus", "Größtes Passagierflugzeug, zwei durchgehende Decks."],
       ["Concorde", "Aérospatiale und BAC", "Überschallverkehr in britisch-französischer Gemeinschaft."],
       ["Cessna 172", "Cessna", "Meistgebautes Flugzeug der Geschichte."],
       ["Ju 52", "Junkers", "Wellblechrumpf mit drei Motoren."],
       ["DC-3", "Douglas", "Machte den Linienflug in den 1930ern wirtschaftlich."],
       ["Spitfire", "Supermarine", "Elliptische Tragflächen, Symbol der Luftschlacht um England."],
       ["MiG-21", "Mikojan-Gurewitsch", "Meistgebautes Überschall-Kampfflugzeug."],
       ["An-225", "Antonow", "Sechs Triebwerke, gebaut für den Transport einer Raumfähre."],
       ["E195", "Embraer", "Regionaljet aus Brasilien."],
       ["CRJ", "Bombardier", "Kanadischer Regionaljet auf Kurzstrecken."],
       ["Gripen", "Saab", "Schwedischer Jäger, für Starts von Landstraßen ausgelegt."]]'::jsonb,
     '[["Lockheed", "Die SR-71 käme von dort, und sie fehlt auf diesem Brett."],
       ["Tupolew", "Die Tu-144 steht nicht in dieser Liste."]]'::jsonb),

    ('technik', 'raketen-laender', 'Trägerraketen & Länder',
     'Aus welchem Land oder Verbund stammt die Rakete?',
     'hard', 'Trägerrakete', 'https://de.wikipedia.org/wiki/Tr%C3%A4gerrakete',
     '[["Saturn V", "USA", "Brachte die Apollo-Mannschaften zum Mond."],
       ["Sojus", "Russland", "Meistgeflogene Rakete der Raumfahrtgeschichte."],
       ["Ariane", "Europa", "Startet von Kourou nahe dem Äquator."],
       ["Langer Marsch", "China", "Trägt auch die Module der Raumstation Tiangong."],
       ["PSLV", "Indien", "Brachte eine Sonde zum Mars beim ersten Versuch."],
       ["H-IIA", "Japan", "Startet von der Insel Tanegashima."],
       ["Electron", "Neuseeland", "Kleinrakete mit gedruckten Triebwerken."],
       ["Shavit", "Israel", "Startet nach Westen, gegen die Erdrotation."],
       ["Safir", "Iran", "Brachte 2009 den ersten eigenen Satelliten ins All."],
       ["Naro-1", "Südkorea", "Erste eigene Trägerrakete des Landes."],
       ["VLS-1", "Brasilien", "Vom Startplatz Alcântara nahe dem Äquator."]]'::jsonb,
     '[["Nordkorea", "Die Unha stammt von dort, und sie fehlt auf diesem Brett."],
       ["Ukraine", "Die Zenit steht nicht in dieser Liste."]]'::jsonb),

    ('technik', 'top-level-domains', 'Länderdomains',
     'Zu welchem Land gehört die Endung?',
     'medium', 'Top-Level-Domain',
     'https://de.wikipedia.org/wiki/Top-Level-Domain',
     '[[".de", "Deutschland", "Eine der am häufigsten vergebenen Länderdomains."],
       [".ch", "Schweiz", "Von Confoederatio Helvetica."],
       [".at", "Österreich", "Kurz für Austria."],
       [".jp", "Japan", "Verwaltet von einer eigenen Registrierungsstelle."],
       [".br", "Brasilien", "Registrierung meist nur mit Bezug zum Land."],
       [".za", "Südafrika", "Von Zuid-Afrika, dem niederländischen Namen."],
       [".no", "Norwegen", "Strenge Regeln, wie viele Domains eine Firma halten darf."],
       [".cz", "Tschechien", "Nach der Trennung von der Slowakei eingeführt."],
       [".hu", "Ungarn", "Von Hungaria."],
       [".hr", "Kroatien", "Von Hrvatska."],
       [".in", "Indien", "Auch für viele englischsprachige Wortspiele beliebt."],
       [".mx", "Mexiko", "Beliebt bei Kurz-URLs."]]'::jsonb,
     '[["Italien", "Die Endung .it gehört dorthin, und sie fehlt auf dem Brett."],
       ["Schweden", "Die Endung .se steht nicht in dieser Liste."]]'::jsonb),

    ('technik', 'werkzeuge-verwendung', 'Werkzeuge & ihr Zweck',
     'Wozu dient das Werkzeug?',
     'medium', 'Werkzeug', 'https://de.wikipedia.org/wiki/Werkzeug',
     '[["Wasserwaage", "Waagerechte prüfen", "Die Luftblase zeigt die Neigung."],
       ["Senklot", "Senkrechte bestimmen", "Ein Gewicht an der Schnur, seit der Antike."],
       ["Feile", "Material abtragen", "Der Hieb bestimmt, wie grob sie arbeitet."],
       ["Hobel", "Holz glätten", "Die Späne laufen durch das Maul ab."],
       ["Meißel", "Stein und Metall stemmen", "Wird mit dem Hammer geführt."],
       ["Winkelschleifer", "Trennen und Schleifen", "Die Scheibe läuft mit hoher Drehzahl."],
       ["Lötkolben", "Bauteile verbinden", "Das Lot schmilzt, die Bauteile nicht."],
       ["Schraubstock", "Werkstück festhalten", "Lässt beide Hände frei."],
       ["Bandmaß", "Längen messen", "Rollt sich selbst wieder auf."],
       ["Schleifpapier", "Oberflächen glätten", "Die Körnung gibt die Feinheit an."],
       ["Drehmomentschlüssel", "Schrauben genau anziehen", "Klickt beim eingestellten Wert."],
       ["Schieblehre", "Genau messen", "Der Nonius erlaubt Zehntelmillimeter."]]'::jsonb,
     '[["Löcher in Wände bohren", "Die Bohrmaschine fehlt auf diesem Brett."],
       ["Nägel einschlagen", "Der Hammer steht nicht in dieser Liste."]]'::jsonb),

    ('technik', 'autotechnik-bauteile', 'Autotechnik & Funktion',
     'Was macht dieses Bauteil im Auto?',
     'hard', 'Automobil', 'https://de.wikipedia.org/wiki/Automobil',
     '[["Kupplung", "Trennt Motor und Getriebe", "Ohne sie ließe sich kein Gang wechseln."],
       ["Differential", "Erlaubt unterschiedliche Raddrehzahlen", "In der Kurve dreht das äußere Rad schneller."],
       ["Turbolader", "Verdichtet die Ansaugluft", "Angetrieben von den Abgasen."],
       ["Katalysator", "Wandelt Schadstoffe um", "Braucht Betriebstemperatur, um zu wirken."],
       ["Nockenwelle", "Steuert die Ventile", "Ihre Form bestimmt den Charakter des Motors."],
       ["Lichtmaschine", "Erzeugt Strom im Betrieb", "Lädt die Batterie während der Fahrt."],
       ["Anlasser", "Startet den Motor", "Zieht kurzzeitig sehr hohen Strom."],
       ["Zündkerze", "Zündet das Gemisch", "Nur im Benziner, der Diesel zündet durch Verdichtung."],
       ["Stoßdämpfer", "Beruhigt die Federung", "Ohne ihn schaukelt das Auto nach."],
       ["Kardanwelle", "Überträgt zur Hinterachse", "Gleicht Bewegungen über Kreuzgelenke aus."],
       ["ABS", "Verhindert blockierende Räder", "Lenken bleibt auch bei Vollbremsung möglich."],
       ["ESP", "Stabilisiert bei Schleudergefahr", "Bremst einzelne Räder gezielt ab."]]'::jsonb,
     '[["Kühlt den Motor mit Flüssigkeit", "Der Kühler fehlt auf diesem Brett."],
       ["Filtert Ruß aus den Abgasen", "Der Partikelfilter steht nicht in dieser Liste."]]'::jsonb),

    ('technik', 'software-zweck', 'Programme & ihr Zweck',
     'Wofür wird das Programm benutzt?',
     'medium', 'Software', 'https://de.wikipedia.org/wiki/Software',
     '[["Photoshop", "Bildbearbeitung", "Der Name wurde zum Verb."],
       ["Excel", "Tabellenkalkulation", "Rechnet mit Zellbezügen statt festen Zahlen."],
       ["AutoCAD", "Technisches Zeichnen", "Seit 1982 Standard in Konstruktionsbüros."],
       ["Blender", "Dreidimensionale Grafik", "Modellieren, Animieren und Rendern, quelloffen."],
       ["Git", "Versionsverwaltung", "Von Linus Torvalds für die Kernelentwicklung geschrieben."],
       ["Docker", "Anwendungen in Containern", "Packt Programm und Umgebung zusammen."],
       ["Firefox", "Webbrowser", "Aus dem Quellcode des alten Netscape entstanden."],
       ["VLC", "Medienwiedergabe", "Spielt fast jedes Format ohne Zusatzpakete."],
       ["WordPress", "Verwaltung von Webseiten", "Ein erheblicher Teil aller Websites läuft damit."],
       ["Ableton Live", "Musikproduktion", "Auf Auftritte in Echtzeit ausgelegt."],
       ["MATLAB", "Numerische Berechnungen", "Rechnet von Haus aus mit Matrizen."],
       ["QGIS", "Geografische Karten", "Quelloffene Alternative für Geodaten."]]'::jsonb,
     '[["Präsentationen erstellen", "PowerPoint fehlt auf diesem Brett."],
       ["Videos schneiden", "Ein Schnittprogramm steht nicht in dieser Liste."]]'::jsonb),

    ('technik', 'messgeraete', 'Messgeräte & Messgrößen',
     'Was misst das Gerät?',
     'hard', 'Messgerät', 'https://de.wikipedia.org/wiki/Messger%C3%A4t',
     '[["Barometer", "Luftdruck", "Fallender Druck kündigt schlechtes Wetter an."],
       ["Hygrometer", "Luftfeuchtigkeit", "Manche arbeiten mit einem gespannten Haar."],
       ["Anemometer", "Windgeschwindigkeit", "Meist mit drei rotierenden Schalen."],
       ["Seismograph", "Erdbebenwellen", "Eine träge Masse bleibt stehen, der Boden bewegt sich."],
       ["Geigerzähler", "Ionisierende Strahlung", "Jedes Teilchen erzeugt einen hörbaren Impuls."],
       ["Tachometer", "Geschwindigkeit", "Im Auto meist etwas zu hoch anzeigend."],
       ["Voltmeter", "Elektrische Spannung", "Wird parallel geschaltet."],
       ["Amperemeter", "Stromstärke", "Muss in den Stromkreis eingefügt werden."],
       ["Ohmmeter", "Elektrischen Widerstand", "Legt eine kleine Spannung an und misst den Strom."],
       ["Luxmeter", "Beleuchtungsstärke", "Wichtig für Arbeitsplätze und Fotografie."],
       ["Schallpegelmesser", "Lautstärke", "Bewertet nach dem Empfinden des Ohrs."],
       ["Refraktometer", "Zuckergehalt in Flüssigkeit", "Über die Lichtbrechung bestimmt."]]'::jsonb,
     '[["Temperatur", "Das Thermometer fehlt auf diesem Brett."],
       ["Höhe über dem Meer", "Der Höhenmesser steht nicht in dieser Liste."]]'::jsonb),

    ('technik', 'it-sicherheit', 'Begriffe der IT-Sicherheit',
     'Was bezeichnet der Begriff?',
     'hard', 'Informationssicherheit',
     'https://de.wikipedia.org/wiki/Informationssicherheit',
     '[["Phishing", "Gefälschte Nachrichten", "Ziel sind Zugangsdaten, nicht der Rechner."],
       ["Firewall", "Filtert Datenverkehr", "Erlaubt nur, was ausdrücklich vorgesehen ist."],
       ["Ende-zu-Ende-Verschlüsselung", "Nur die Gesprächspartner lesen", "Auch der Betreiber sieht nur Kauderwelsch."],
       ["Zwei-Faktor-Authentisierung", "Zweiter Nachweis nötig", "Wissen plus Besitz, etwa Passwort und Code."],
       ["Ransomware", "Erpressung durch Verschlüsselung", "Die Daten bleiben da, aber unlesbar."],
       ["Zertifikat", "Bestätigt eine Identität", "Eine Stelle bürgt für den Schlüssel."],
       ["Hashwert", "Prüfsumme fester Länge", "Aus ihr lässt sich das Original nicht zurückrechnen."],
       ["Brute Force", "Systematisches Durchprobieren", "Nur eine Frage der Rechenzeit."],
       ["Zero-Day", "Noch unbekannte Lücke", "Es gibt noch keinen Patch dagegen."],
       ["Backdoor", "Heimlicher Zugang", "Absichtlich eingebaut oder nachträglich gesetzt."],
       ["Sandbox", "Abgeschottete Umgebung", "Schadcode kann dort nichts anrichten."],
       ["Social Engineering", "Angriff auf den Menschen", "Kein System wird geknackt, sondern Vertrauen."]]'::jsonb,
     '[["Kopie der Daten für den Notfall", "Das Backup fehlt auf diesem Brett."],
       ["Programm, das sich selbst verbreitet", "Der Wurm steht nicht in dieser Liste."]]'::jsonb),

    ('technik', 'marken-branchen', 'Marken & Branchen',
     'In welcher Branche ist die Marke zu Hause?',
     'medium', 'Marke (Marketing)',
     'https://de.wikipedia.org/wiki/Marke_%28Marketing%29',
     '[["Zeiss", "Optik", "Objektive, Mikroskope und Brillengläser."],
       ["Nestlé", "Lebensmittel", "Größter Nahrungsmittelkonzern der Welt."],
       ["Adidas", "Sportartikel", "Aus dem Streit zweier Brüder in Herzogenaurach entstanden."],
       ["Lego", "Spielzeug", "Der Name kommt vom dänischen leg godt, spiel gut."],
       ["Rolex", "Uhren", "Bekannt für die wasserdichte Oyster-Gehäuseform."],
       ["Michelin", "Reifen", "Der Restaurantführer war ursprünglich Werbung."],
       ["Kärcher", "Reinigungsgeräte", "Der Hochdruckreiniger wurde zum Gattungsbegriff."],
       ["Miele", "Hausgeräte", "Wirbt seit über hundert Jahren mit Immer besser."],
       ["Fender", "Musikinstrumente", "Die Stratocaster prägte den Klang des Rock."],
       ["Canon", "Kameras", "Der Name geht auf eine buddhistische Gottheit zurück."],
       ["Caterpillar", "Baumaschinen", "Das Gelb ist als Farbe eingetragen."],
       ["Pfizer", "Pharmazie", "Gegründet 1849 in Brooklyn."]]'::jsonb,
     '[["Möbel", "Ikea wäre die Marke dazu, und die fehlt auf diesem Brett."],
       ["Fluggesellschaften", "Keine Marke in dieser Liste gehört dorthin."]]'::jsonb),

    ('technik', 'bahntechnik', 'Bahntechnik',
     'Was bezeichnet der Begriff bei der Eisenbahn?',
     'hard', 'Eisenbahn', 'https://de.wikipedia.org/wiki/Eisenbahn',
     '[["Weiche", "Wechsel zwischen Gleisen", "Zunge und Herzstück lenken die Räder."],
       ["Stellwerk", "Steuert Signale und Weichen", "Verhindert, dass zwei Züge dieselbe Fahrstraße bekommen."],
       ["Oberleitung", "Stromversorgung von oben", "Der Fahrdraht hängt im Zickzack, damit der Schleifer gleichmäßig verschleißt."],
       ["Stromabnehmer", "Greift den Fahrdraht ab", "Wird pneumatisch angehoben."],
       ["Drehgestell", "Trägt die Achsen beweglich", "Erlaubt langen Wagen enge Kurven."],
       ["Puffer", "Fängt Stöße auf", "Bei modernen Zügen durch Mittelpufferkupplungen ersetzt."],
       ["Schotterbett", "Verteilt die Last", "Hält zugleich die Schwellen in Lage."],
       ["Spurweite", "Abstand der Schienen", "Die Normalspur misst 1435 Millimeter."],
       ["Zahnstange", "Hilft an starken Steigungen", "Ein Zahnrad greift in die Mitte des Gleises."],
       ["ETCS", "Europäische Zugsicherung", "Signale wandern in den Führerstand."],
       ["Rangierbahnhof", "Sortiert Güterwagen", "Über den Ablaufberg rollen sie in die richtigen Gleise."],
       ["Blockabschnitt", "Sichert den Abstand", "In einen Abschnitt darf immer nur ein Zug."]]'::jsonb,
     '[["Rad, das auf der Schiene läuft", "Der Radsatz fehlt auf diesem Brett."],
       ["Bremsen mit Druckluft", "Die Druckluftbremse steht nicht in dieser Liste."]]'::jsonb),

    ('technik', 'ki-begriffe', 'Begriffe der künstlichen Intelligenz',
     'Was bedeutet der Begriff?',
     'hard', 'Künstliche Intelligenz',
     'https://de.wikipedia.org/wiki/K%C3%BCnstliche_Intelligenz',
     '[["Neuronales Netz", "Schichten verbundener Knoten", "Lose an Nervenzellen angelehnt."],
       ["Training", "Anpassen der Gewichte", "Der Fehler wird schrittweise kleiner gemacht."],
       ["Überwachtes Lernen", "Lernen an gelabelten Daten", "Zu jedem Beispiel gibt es die richtige Antwort."],
       ["Bestärkendes Lernen", "Lernen durch Belohnung", "Gut für Spiele und Steuerungsaufgaben."],
       ["Token", "Kleinste Texteinheit", "Oft ein Wortteil, nicht ein ganzes Wort."],
       ["Halluzination", "Erfundene, falsche Ausgabe", "Klingt plausibel, ist aber unbelegt."],
       ["Transformer", "Architektur mit Aufmerksamkeit", "Seit 2017 Grundlage der großen Sprachmodelle."],
       ["Inferenz", "Anwenden des fertigen Modells", "Kostet Rechenzeit bei jeder Anfrage."],
       ["Überanpassung", "Auswendiglernen der Beispiele", "Das Modell versagt bei neuen Daten."],
       ["Prompt", "Eingabe an das Modell", "Formulierung und Kontext ändern das Ergebnis."],
       ["Embedding", "Bedeutung als Zahlenvektor", "Ähnliche Begriffe liegen nah beieinander."],
       ["Benchmark", "Standardisierter Vergleichstest", "Erlaubt es, Modelle nebeneinander zu stellen."]]'::jsonb,
     '[["Zahl der Bilder pro Sekunde", "Das hat mit künstlicher Intelligenz nichts zu tun."],
       ["Modell ohne jedes Training", "Kein Begriff auf diesem Brett meint das."]]'::jsonb),

    ('technik', 'fototechnik', 'Fototechnik',
     'Was stellt man damit ein?',
     'hard', 'Fotografie', 'https://de.wikipedia.org/wiki/Fotografie',
     '[["Blende", "Lichtmenge und Schärfentiefe", "Kleine Zahl heißt große Öffnung."],
       ["Belichtungszeit", "Bewegung einfrieren oder verwischen", "Lange Zeiten brauchen ein Stativ."],
       ["ISO-Wert", "Empfindlichkeit des Sensors", "Hohe Werte bringen Bildrauschen."],
       ["Brennweite", "Bildwinkel des Objektivs", "Klein heißt weitwinklig, groß heißt Tele."],
       ["Weißabgleich", "Farbstimmung des Lichts", "Sonst wirkt Kunstlicht orange."],
       ["Autofokus", "Automatisches Scharfstellen", "Arbeitet über Kontrast oder Phasenvergleich."],
       ["Rohdatenformat", "Unbearbeitete Sensordaten", "Erlaubt später mehr Spielraum bei der Korrektur."],
       ["Bokeh", "Aussehen der Unschärfe", "Hängt von Blendenform und Objektivbau ab."],
       ["Polfilter", "Spiegelungen und Himmelsblau", "Wirkt nur in bestimmten Winkeln zur Sonne."],
       ["Stativ", "Ruhige Kameraposition", "Voraussetzung für Langzeitbelichtungen."],
       ["Belichtungskorrektur", "Bewusst heller oder dunkler", "Gegen die Fehleinschätzung der Automatik."],
       ["Blitzsynchronzeit", "Kürzeste Zeit mit Blitz", "Darunter wäre der Sensor nur teilweise offen."]]'::jsonb,
     '[["Bildgröße in Megapixeln", "Sie lässt sich nicht einstellen und fehlt hier."],
       ["Selbstauslöser mit Verzögerung", "Er steht nicht auf diesem Brett."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

-- The answers that belong to no category. Numbered after the pairs so the two
-- sets never collide on `position`, though nothing reads it for a fake: the
-- pool is shuffled before a player sees it, and the review lists fakes on their
-- own rather than in board order.
fakes as (
    select q.id                                         as quiz_id,
           k.value ->> 0                                as label,
           k.value ->> 1                                as explanation,
           (jsonb_array_length(sp.pairs) + k.ord)::int  as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.fakes) with ordinality k(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
),

paired as (
    insert into items (quiz_id, category_id, label, position, explanation)
    select f.quiz_id, c.id, f.answer, f.position, f.explanation
      from flat f
      join new_categories c
        on c.quiz_id = f.quiz_id
       and c.label = f.label
    returning id
)

-- Same table, `category_id` left null. Both inserts run in the one statement,
-- so `items_quiz_id_label_key` still sees the pairs above: a fake written to
-- repeat an answer already on its own board fails the file rather than becoming
-- a second row nobody can tell apart.
insert into items (quiz_id, category_id, label, position, explanation)
select k.quiz_id, null, k.label, k.position, k.explanation
  from fakes k;
