-- Technik, leichte Fragen. Zwanzig Fragen, alle 'easy'.
--
-- Gefragt wird nach Dingen, die im Haushalt stehen oder auf der Straße fahren,
-- nicht nach Portnummern und Werkstoffkennwerten.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs) as (
    values

    ('technik', 'leicht-haushaltsgeraete', 'Geräte im Haushalt',
     'Womit macht man das?',
     'easy', 'Haushaltsgerät',
     'https://de.wikipedia.org/wiki/Haushaltsger%C3%A4t',
     '[["Wäsche sauber machen", "Waschmaschine", "Trommel, Wasser und Waschmittel."],
       ["Geschirr spülen ohne Hände", "Geschirrspüler", "Sprüharme drehen sich unter Druck."],
       ["Lebensmittel kühl halten", "Kühlschrank", "Hinten gibt er die Wärme wieder ab."],
       ["Brot bräunen", "Toaster", "Ein Draht glüht und strahlt Wärme ab."],
       ["Wasser schnell heiß machen", "Wasserkocher", "Schaltet beim Dampf selbst ab."],
       ["Boden von Staub befreien", "Staubsauger", "Ein Gebläse erzeugt Unterdruck."],
       ["Essen in Minuten erwärmen", "Mikrowelle", "Sie bringt Wassermoleküle in Bewegung."],
       ["Obst zu Saft zerkleinern", "Mixer", "Die Messer drehen sich sehr schnell."],
       ["Kleidung glatt machen", "Bügeleisen", "Dampf hilft gegen hartnäckige Falten."],
       ["Kaffee aufbrühen", "Kaffeemaschine", "Heißes Wasser läuft durch den Filter."],
       ["Haare trocknen", "Föhn", "Ein Gebläse bläst über eine Heizspirale."],
       ["Zeit beim Kochen messen", "Küchenwecker", "Er klingelt, wenn die Zeit um ist."]]'::jsonb),

    ('technik', 'leicht-werkzeuge', 'Werkzeuge',
     'Wofür braucht man das?',
     'easy', 'Werkzeug', 'https://de.wikipedia.org/wiki/Werkzeug',
     '[["Hammer", "Nägel einschlagen", "Die Klaue zieht sie auch wieder heraus."],
       ["Schraubendreher", "Schrauben drehen", "Kreuz- oder Schlitzform."],
       ["Säge", "Holz durchtrennen", "Die Zähne schneiden in eine Richtung."],
       ["Zange", "Festhalten und Biegen", "Die Kombizange kann auch kneifen."],
       ["Zollstock", "Längen messen", "Klassisch aus zehn Holzgliedern."],
       ["Wasserwaage", "Waagerecht ausrichten", "Die Luftblase muss in die Mitte."],
       ["Bohrmaschine", "Löcher bohren", "Für Stein braucht es den Schlagbohrer."],
       ["Feile", "Kanten glätten", "Sie trägt feinen Staub ab."],
       ["Schraubstock", "Werkstück einspannen", "So bleiben beide Hände frei."],
       ["Pinsel", "Farbe auftragen", "Danach gut auswaschen."],
       ["Schleifpapier", "Oberflächen glätten", "Je höher die Zahl, desto feiner."],
       ["Leiter", "Höhe erreichen", "Immer im richtigen Winkel anstellen."]]'::jsonb),

    ('technik', 'leicht-fahrzeuge', 'Fahrzeuge',
     'Wozu dient das Fahrzeug?',
     'easy', 'Fahrzeug', 'https://de.wikipedia.org/wiki/Fahrzeug',
     '[["Krankenwagen", "Kranke transportieren", "Er hat Vorfahrt mit Blaulicht."],
       ["Feuerwehrauto", "Brände löschen", "Es führt eigenes Wasser mit."],
       ["Müllwagen", "Abfall abholen", "Er presst den Müll zusammen."],
       ["Bagger", "Erde ausheben", "Die Schaufel sitzt am Arm."],
       ["Kran", "Lasten heben", "Das Gegengewicht hält ihn stabil."],
       ["Traktor", "Felder bearbeiten", "Er zieht Pflug und Anhänger."],
       ["Schneepflug", "Straßen räumen", "Das Schild schiebt den Schnee zur Seite."],
       ["Betonmischer", "Beton flüssig halten", "Die Trommel dreht sich ständig."],
       ["Schulbus", "Kinder befördern", "Er hält an festen Haltestellen."],
       ["Rettungshubschrauber", "Schnell zum Unfallort", "Er landet auch auf der Autobahn."],
       ["Straßenbahn", "Nahverkehr auf Schienen", "Sie fährt auf Schienen im Straßenraum."],
       ["Gabelstapler", "Paletten heben", "Das Gegengewicht sitzt hinten."]]'::jsonb),

    ('technik', 'leicht-verkehrszeichen', 'Verkehrszeichen',
     'Was bedeutet das Schild?',
     'easy', 'Verkehrszeichen',
     'https://de.wikipedia.org/wiki/Verkehrszeichen',
     '[["Rotes Achteck mit weißer Schrift", "Halt, Vorfahrt gewähren", "Das einzige achteckige Schild."],
       ["Auf der Spitze stehendes Dreieck", "Vorfahrt gewähren", "Rot umrandet und weiß."],
       ["Gelbe Raute", "Vorfahrtstraße", "Sie gilt bis zum Ende-Schild."],
       ["Roter Kreis mit Zahl", "Höchstgeschwindigkeit", "Gilt bis zur Aufhebung."],
       ["Blauer Kreis mit weißem Fahrrad", "Radweg benutzen", "Blau bedeutet Gebot."],
       ["Rotes Dreieck mit Ausrufezeichen", "Gefahrenstelle", "Ein Zusatzschild erklärt sie."],
       ["Roter Kreis, weiß gefüllt, roter Balken", "Durchfahrt verboten", "Für alle Fahrzeuge."],
       ["Rotes Dreieck mit spielenden Kindern", "Kinder in der Nähe", "Oft vor Schulen."],
       ["Blaues Schild mit weißem Pfeil", "Vorgeschriebene Fahrtrichtung", "Man muss dorthin abbiegen."],
       ["Weiße Zickzacklinie am Rand", "Halteverbot", "Meist an Haltestellen."]]'::jsonb),

    ('technik', 'leicht-computer', 'Am Computer',
     'Wie heißt das Teil?',
     'easy', 'Computer', 'https://de.wikipedia.org/wiki/Computer',
     '[["Damit tippt man Buchstaben", "Tastatur", "Die Anordnung heißt QWERTZ."],
       ["Damit zeigt und klickt man", "Maus", "Erfunden schon in den 1960er Jahren."],
       ["Darauf sieht man das Bild", "Bildschirm", "Heute meist flach und beleuchtet."],
       ["Damit hört man Ton", "Lautsprecher", "Eine Membran bewegt die Luft."],
       ["Damit druckt man auf Papier", "Drucker", "Tinte oder Toner."],
       ["Darin werden Dateien gespeichert", "Festplatte", "Moderne haben keine beweglichen Teile."],
       ["Damit kommt man ins Internet", "Router", "Er verteilt die Verbindung im Haus."],
       ["Damit sieht man sein Gegenüber", "Webcam", "Meist oben im Bildschirmrand."],
       ["Kleiner Stecker zum Mitnehmen von Dateien", "USB-Stick", "Passt in jede Hosentasche."],
       ["Damit spricht man in Videokonferenzen", "Mikrofon", "Es wandelt Schall in Spannung."],
       ["Ein tragbarer Computer", "Laptop", "Bildschirm und Tastatur klappen zusammen."],
       ["Das Bild, das man aufhebt", "Screenshot", "Ein Foto vom eigenen Bildschirm."]]'::jsonb),

    ('technik', 'leicht-fahrrad', 'Am Fahrrad',
     'Wie heißt der Teil?',
     'easy', 'Fahrrad', 'https://de.wikipedia.org/wiki/Fahrrad',
     '[["Darauf sitzt man", "Sattel", "Höhe verstellbar für die Beinlänge."],
       ["Damit lenkt man", "Lenker", "Rennräder haben ihn gebogen."],
       ["Damit tritt man", "Pedale", "Die Kraft geht über die Kette."],
       ["Verbindet Pedale und Hinterrad", "Kette", "Muss regelmäßig geölt werden."],
       ["Damit hält man an", "Bremse", "Vorn wirkt sie stärker als hinten."],
       ["Sorgt für Licht nach vorn", "Scheinwerfer", "Vorgeschrieben bei Dunkelheit."],
       ["Warnt andere mit einem Ton", "Klingel", "Sie ist gesetzlich Pflicht."],
       ["Füllt sich mit Luft", "Reifen", "Zu wenig Druck kostet Kraft."],
       ["Hält das Rad im Stand aufrecht", "Ständer", "Meist am Rahmen unten."],
       ["Schützt vor Spritzwasser", "Schutzblech", "Rennräder verzichten darauf."],
       ["Erzeugt Strom beim Fahren", "Dynamo", "Am Reifen oder in der Nabe."],
       ["Trägt Gepäck über dem Hinterrad", "Gepäckträger", "Mit Spanngurten gesichert."]]'::jsonb),

    ('technik', 'leicht-erfindungen-alltag', 'Erfindungen des Alltags',
     'Wozu wurde das erfunden?',
     'easy', 'Erfindung', 'https://de.wikipedia.org/wiki/Erfindung',
     '[["Rad", "Lasten leichter bewegen", "Eine der wichtigsten Erfindungen überhaupt."],
       ["Glühlampe", "Licht ohne Feuer", "Sie löste Kerze und Gaslaterne ab."],
       ["Telefon", "Über Entfernung sprechen", "Zuerst nur zwischen zwei festen Punkten."],
       ["Buchdruck", "Bücher vervielfältigen", "Wissen wurde plötzlich bezahlbar."],
       ["Kühlschrank", "Essen haltbar machen", "Vorher half nur Eis aus dem Winter."],
       ["Reißverschluss", "Kleidung schnell schließen", "Zwei Zahnreihen greifen ineinander."],
       ["Klettverschluss", "Ohne Knoten befestigen", "Abgeschaut bei einer Pflanze."],
       ["Papier", "Gedanken festhalten", "Aus China nach Europa gekommen."],
       ["Brille", "Schärfer sehen", "Linsen gleichen den Augenfehler aus."],
       ["Kompass", "Die Richtung finden", "Die Nadel zeigt nach Norden."],
       ["Batterie", "Strom mitnehmen", "Chemische Energie wird elektrisch."],
       ["Streichholz", "Feuer schnell entzünden", "Der Kopf entzündet sich durch Reibung."]]'::jsonb),

    ('technik', 'leicht-energie', 'Woher der Strom kommt',
     'Was liefert hier die Energie?',
     'easy', 'Energie', 'https://de.wikipedia.org/wiki/Energie',
     '[["Windrad", "Wind", "Je höher der Turm, desto stetiger weht es."],
       ["Solarzelle", "Sonnenlicht", "Auch bei Bewölkung liefert sie etwas."],
       ["Wasserkraftwerk", "Fließendes Wasser", "Turbinen im Fluss oder unter dem Stausee."],
       ["Kohlekraftwerk", "Verbrennung von Kohle", "Dabei entsteht viel Kohlendioxid."],
       ["Kernkraftwerk", "Spaltung von Uran", "Der Abfall strahlt sehr lange."],
       ["Biogasanlage", "Vergorene Pflanzenreste", "Bakterien erzeugen Methan."],
       ["Erdwärmekraftwerk", "Wärme aus der Tiefe", "Heißes Wasser treibt eine Turbine."],
       ["Gezeitenkraftwerk", "Ebbe und Flut", "Der Wechsel treibt die Turbine an."],
       ["Batterie im Handy", "Gespeicherte Chemie", "Sie wird beim Laden wieder aufgefüllt."],
       ["Fahrraddynamo", "Muskelkraft", "Der Widerstand ist beim Treten zu spüren."]]'::jsonb),

    ('technik', 'leicht-kueche-technik', 'Technik in der Küche',
     'Was passiert dabei?',
     'easy', 'Küche', 'https://de.wikipedia.org/wiki/K%C3%BCche',
     '[["Wasser im Topf bei 100 Grad", "Es kocht", "Blasen steigen auf."],
       ["Butter in der heißen Pfanne", "Sie schmilzt", "Fest wird flüssig."],
       ["Ei in kochendem Wasser", "Es wird fest", "Das Eiweiß gerinnt."],
       ["Milch bleibt zu lange auf dem Herd", "Sie kocht über", "Die Haut hält den Dampf zurück."],
       ["Zucker in heißer Pfanne", "Er karamellisiert", "Er wird braun und riecht anders."],
       ["Teig mit Hefe an einem warmen Ort", "Er geht auf", "Hefe bildet Gasbläschen."],
       ["Brot bleibt offen liegen", "Es wird hart", "Es verliert Feuchtigkeit."],
       ["Salat mit Salz bestreut", "Er zieht Wasser", "Das Salz entzieht es den Zellen."],
       ["Kaltes Glas an einem warmen Tag", "Es beschlägt", "Luftfeuchtigkeit schlägt sich nieder."],
       ["Öl wird zu heiß", "Es raucht", "Dann sollte man es nicht mehr verwenden."]]'::jsonb),

    ('technik', 'leicht-telefon', 'Telefon & Handy',
     'Was bedeutet das?',
     'easy', 'Telefon', 'https://de.wikipedia.org/wiki/Telefon',
     '[["SMS", "Kurznachricht", "Ursprünglich auf 160 Zeichen begrenzt."],
       ["Akku", "Wiederaufladbarer Speicher", "Er altert mit jedem Ladezyklus."],
       ["SIM-Karte", "Ausweis im Mobilfunknetz", "Heute oft fest im Gerät."],
       ["WLAN", "Drahtloses Netz zu Hause", "Der Router spannt es auf."],
       ["Flugmodus", "Alle Funkverbindungen aus", "Beim Start und der Landung nötig."],
       ["App", "Programm auf dem Handy", "Kurz für Applikation."],
       ["Ladekabel", "Strom für den Akku", "Heute meist mit USB-C."],
       ["Klingelton", "Signal bei einem Anruf", "Lässt sich pro Kontakt einstellen."],
       ["Mailbox", "Anrufbeantworter im Netz", "Sie springt nach einigen Sekunden an."],
       ["Vorwahl", "Kennzahl für einen Ort", "Bei Auslandsgesprächen mit zwei Nullen."],
       ["Kontakte", "Gespeicherte Rufnummern", "Früher stand alles im Telefonbuch."],
       ["Notruf 112", "Feuerwehr und Rettungsdienst", "In ganz Europa dieselbe Nummer."]]'::jsonb),

    ('technik', 'leicht-material', 'Woraus ist das gemacht?',
     'Aus welchem Material besteht es meistens?',
     'easy', 'Werkstoff', 'https://de.wikipedia.org/wiki/Werkstoff',
     '[["Fensterscheibe", "Glas", "Durchsichtig und zerbrechlich."],
       ["Autoreifen", "Gummi", "Ruß macht ihn schwarz und haltbar."],
       ["Bleistiftmine", "Graphit", "Trotz des Namens ohne Blei."],
       ["Stromkabel im Inneren", "Kupfer", "Sehr guter Leiter."],
       ["Konservendose", "Weißblech", "Dünner Stahl mit Zinnschicht."],
       ["Fahrradrahmen im Rennsport", "Karbon", "Leicht und sehr steif."],
       ["Trinkflasche für unterwegs", "Edelstahl", "Rostet nicht und schmeckt neutral."],
       ["Tischplatte im Wohnzimmer", "Holz", "Warm und nachwachsend."],
       ["Plastiktüte", "Kunststoff", "Aus Erdöl hergestellt."],
       ["Gehweg vor dem Haus", "Beton", "Druckfest, aber ohne Stahl zugschwach."],
       ["Dachziegel", "Gebrannter Ton", "Hält Jahrzehnte."],
       ["Löffel im Besteckkasten", "Metall", "Meist rostfreier Stahl."]]'::jsonb),

    ('technik', 'leicht-sicherheit', 'Sicherheit im Alltag',
     'Wozu dient das?',
     'easy', 'Sicherheit', 'https://de.wikipedia.org/wiki/Sicherheit',
     '[["Rauchmelder", "Warnt vor Brandrauch", "In Wohnungen inzwischen Pflicht."],
       ["Sicherheitsgurt", "Hält im Auto zurück", "Rettet mehr Leben als jede andere Maßnahme."],
       ["Fahrradhelm", "Schützt den Kopf", "Er verteilt die Wucht eines Aufpralls."],
       ["Feuerlöscher", "Löscht kleine Brände", "Vorher prüfen, welche Art Brand es ist."],
       ["Warnweste", "Macht sichtbar", "Muss im Auto mitgeführt werden."],
       ["Sicherung im Stromkasten", "Trennt bei Überlast", "Sie fliegt raus, bevor etwas brennt."],
       ["Verbandskasten", "Erste Hilfe leisten", "Das Verfallsdatum sollte stimmen."],
       ["Notausgangsschild", "Zeigt den Fluchtweg", "Grün mit weißer Figur."],
       ["Kindersicherung an der Steckdose", "Schützt vor Stromschlag", "Kleine Klappen im Inneren."],
       ["Blitzableiter", "Leitet den Blitz ab", "Über einen Draht ins Erdreich."]]'::jsonb),

    ('technik', 'leicht-messen', 'Messen im Alltag',
     'Womit misst man das?',
     'easy', 'Messgerät', 'https://de.wikipedia.org/wiki/Messger%C3%A4t',
     '[["Körpertemperatur", "Fieberthermometer", "Ab 38 Grad spricht man von Fieber."],
       ["Gewicht eines Menschen", "Personenwaage", "Morgens ist man leichter."],
       ["Länge eines Zimmers", "Maßband", "Rollt sich selbst wieder auf."],
       ["Zeit beim Kochen", "Uhr", "Küchenwecker klingeln am Ende."],
       ["Luftdruck für das Wetter", "Barometer", "Fällt der Druck, wird es schlechter."],
       ["Geschwindigkeit im Auto", "Tacho", "Er zeigt meist etwas zu viel an."],
       ["Strom im Haushalt", "Stromzähler", "Er läuft, solange etwas eingeschaltet ist."],
       ["Mehl beim Backen", "Küchenwaage", "Genauer als jeder Messbecher."],
       ["Blutdruck", "Blutdruckmessgerät", "Zwei Werte, oberer und unterer."],
       ["Regenmenge im Garten", "Regenmesser", "Angegeben in Millimetern."]]'::jsonb),

    ('technik', 'leicht-internet', 'Im Internet',
     'Was ist das?',
     'easy', 'Internet', 'https://de.wikipedia.org/wiki/Internet',
     '[["Adresse einer Webseite", "URL", "Beginnt meist mit https."],
       ["Programm zum Surfen", "Browser", "Firefox und Chrome sind zwei davon."],
       ["Elektronische Post", "E-Mail", "Das at-Zeichen trennt Name und Anbieter."],
       ["Gespeicherte Lieblingsseite", "Lesezeichen", "Damit man sie wiederfindet."],
       ["Nachschlagewerk zum Mitschreiben", "Wikipedia", "Jeder darf mitarbeiten."],
       ["Suchen im Netz", "Suchmaschine", "Sie kennt die Seiten aus einem Index."],
       ["Geheimes Wort zum Anmelden", "Passwort", "Je länger, desto besser."],
       ["Kleine Datei, die Seiten wiedererkennen lässt", "Cookie", "Man muss ihr zustimmen."],
       ["Betrugsmail, die Daten abgreifen will", "Phishing", "Sie sieht echten Mails täuschend ähnlich."],
       ["Videos ansehen ohne Herunterladen", "Streaming", "Die Daten kommen laufend an."],
       ["Regelmäßige Aktualisierung eines Programms", "Update", "Es schließt oft Sicherheitslücken."],
       ["Sicherungskopie der eigenen Daten", "Backup", "Erst die Rücksicherung beweist, dass es funktioniert."]]'::jsonb),

    ('technik', 'leicht-bauen', 'Auf der Baustelle',
     'Wer oder was macht das?',
     'easy', 'Bauwesen', 'https://de.wikipedia.org/wiki/Bauwesen',
     '[["Mauert Wände aus Steinen", "Maurer", "Der Mörtel hält alles zusammen."],
       ["Setzt den Dachstuhl", "Zimmerer", "Traditionell in Kluft und mit Hut."],
       ["Verlegt Rohre für Wasser", "Installateur", "Auch für Heizung zuständig."],
       ["Zieht Kabel durch das Haus", "Elektriker", "Er schließt auch den Sicherungskasten an."],
       ["Streicht Wände", "Maler", "Er grundiert, bevor er streicht."],
       ["Deckt das Dach mit Ziegeln", "Dachdecker", "Von unten nach oben gearbeitet."],
       ["Plant das Haus vorher", "Architekt", "Ohne Plan keine Baugenehmigung."],
       ["Hebt Erde für den Keller aus", "Bagger", "Der Aushub wird abgefahren."],
       ["Hebt schwere Teile nach oben", "Kran", "Er wächst mit dem Gebäude."],
       ["Gerüst an der Fassade", "Gerüstbauer", "Es muss geprüft und freigegeben werden."]]'::jsonb),

    ('technik', 'leicht-flugzeug-schiff', 'Flugzeug & Schiff',
     'Wie heißt der Teil oder die Person?',
     'easy', 'Flugzeug', 'https://de.wikipedia.org/wiki/Flugzeug',
     '[["Steuert das Flugzeug", "Pilot", "Meist sitzen zwei im Cockpit."],
       ["Betreut die Gäste an Bord", "Flugbegleiter", "Sie zeigen vorher die Sicherheitshinweise."],
       ["Tragen das Flugzeug in der Luft", "Tragflächen", "Der Auftrieb entsteht an ihrer Wölbung."],
       ["Bremst nach der Landung mit", "Schubumkehr", "Der Strahl wird nach vorn gelenkt."],
       ["Führt das Schiff", "Kapitän", "Er trägt die Verantwortung an Bord."],
       ["Hält das Schiff an einer Stelle", "Anker", "Die Kette hält mehr als das Eisen."],
       ["Vorderes Ende des Schiffs", "Bug", "Er teilt das Wasser."],
       ["Hinteres Ende des Schiffs", "Heck", "Dort sitzt meist die Schraube."],
       ["Rettet bei Seenot", "Rettungsring", "Er ist auffällig orange."],
       ["Startbahn für Flugzeuge", "Landebahn", "Ihre Nummer zeigt die Himmelsrichtung."],
       ["Ort, an dem Schiffe anlegen", "Hafen", "Kräne heben die Container."],
       ["Kleines Boot an Bord", "Rettungsboot", "Es hängt an Davits an der Seite."]]'::jsonb),

    ('technik', 'leicht-zeichen', 'Symbole an Geräten',
     'Was bedeutet das Zeichen?',
     'easy', 'Piktogramm', 'https://de.wikipedia.org/wiki/Piktogramm',
     '[["Kreis mit senkrechtem Strich", "Ein- und Ausschalten", "Aus null und eins zusammengesetzt."],
       ["Dreieck nach rechts", "Wiedergabe starten", "Auf jeder Fernbedienung."],
       ["Zwei senkrechte Balken", "Pause", "Die Wiedergabe hält an."],
       ["Quadrat", "Stopp", "Anders als Pause beginnt es danach von vorn."],
       ["Haus", "Startseite", "Zurück zum Anfang."],
       ["Lupe", "Suchen", "Am häufigsten benutzte Funktion."],
       ["Zahnrad", "Einstellungen", "Alles, was man verändern kann."],
       ["Mülleimer", "Löschen", "Oft lässt sich das rückgängig machen."],
       ["Diskette", "Speichern", "Ein Gerät, das kaum jemand mehr kennt."],
       ["Batteriesymbol mit Blitz", "Wird geladen", "Es füllt sich langsam auf."],
       ["Drei waagerechte Striche", "Menü", "Es heißt scherzhaft Hamburger."],
       ["Wolke", "Speicher im Netz", "Die Daten liegen auf fremden Servern."]]'::jsonb),

    ('technik', 'leicht-strom-sparen', 'Strom & Wasser sparen',
     'Was hilft dabei?',
     'easy', 'Energie', 'https://de.wikipedia.org/wiki/Energie',
     '[["Licht in leeren Räumen", "Ausschalten", "Der einfachste Spartipp überhaupt."],
       ["Alte Glühlampen", "Durch LED ersetzen", "Sie brauchen einen Bruchteil des Stroms."],
       ["Geräte im Bereitschaftsbetrieb", "Ganz vom Netz nehmen", "Standby summiert sich übers Jahr."],
       ["Wäsche nach dem Waschen", "An der Luft trocknen", "Der Trockner ist ein großer Verbraucher."],
       ["Beim Kochen auf dem Topf", "Deckel benutzen", "Spart einen erheblichen Teil der Energie."],
       ["Beim Zähneputzen", "Wasser abstellen", "Es läuft sonst minutenlang ungenutzt."],
       ["Beim Heizen im Winter", "Stoßlüften statt Kipplüften", "Kurz und weit öffnen."],
       ["Kühlschranktür", "Nicht lange offen lassen", "Die kalte Luft fällt heraus."],
       ["Beim Duschen statt Baden", "Weniger Warmwasser", "Eine Wanne fasst ein Vielfaches."],
       ["Beim Wasserkocher", "Nur nötige Menge erhitzen", "Überschüssiges Wasser wird umsonst erhitzt."]]'::jsonb),

    ('technik', 'leicht-medien-geraete', 'Geräte für Bild & Ton',
     'Wofür ist das Gerät da?',
     'easy', 'Unterhaltungselektronik',
     'https://de.wikipedia.org/wiki/Unterhaltungselektronik',
     '[["Fernseher", "Bild und Ton empfangen", "Heute meist über Kabel oder Internet."],
       ["Radio", "Nur Ton empfangen", "Sender werden über Frequenzen gefunden."],
       ["Kopfhörer", "Ton für eine Person", "Er stört niemanden im Raum."],
       ["Fotoapparat", "Bilder festhalten", "Der Sensor ersetzte den Film."],
       ["Videokamera", "Bewegte Bilder aufnehmen", "Mit Ton zugleich."],
       ["Beamer", "Bild an die Wand", "Je dunkler der Raum, desto besser."],
       ["Plattenspieler", "Schallplatten abspielen", "Die Nadel folgt der Rille."],
       ["Fernbedienung", "Aus der Ferne steuern", "Meist über Infrarot."],
       ["Spielkonsole", "Videospiele spielen", "Anschluss an den Fernseher."],
       ["Bluetooth-Box", "Musik drahtlos abspielen", "Verbindung über kurze Distanz."]]'::jsonb),

    ('technik', 'leicht-berufe-technik', 'Technische Berufe',
     'Wer macht das?',
     'easy', 'Beruf', 'https://de.wikipedia.org/wiki/Beruf',
     '[["Repariert Autos", "Kfz-Mechatroniker", "Er liest auch den Fehlerspeicher aus."],
       ["Backt Brot und Brötchen", "Bäcker", "Der Arbeitstag beginnt nachts."],
       ["Schneidet Haare", "Friseur", "Ausbildung dauert drei Jahre."],
       ["Baut Möbel aus Holz", "Tischler", "In Süddeutschland Schreiner genannt."],
       ["Repariert Wasserleitungen", "Klempner", "Auch Installateur genannt."],
       ["Prüft Brücken und Gebäude", "Bauingenieur", "Er rechnet Lasten nach."],
       ["Schreibt Programme", "Softwareentwickler", "Er testet, was er baut."],
       ["Fliegt Flugzeuge", "Pilot", "Regelmäßige Prüfungen gehören dazu."],
       ["Kümmert sich um kranke Tiere", "Tierarzt", "Auch nachts im Einsatz."],
       ["Baut und wartet Heizungen", "Anlagenmechaniker", "Zunehmend mit Wärmepumpen."],
       ["Verlegt Fliesen", "Fliesenleger", "Die Fugen kommen ganz zum Schluss."],
       ["Steuert einen Zug", "Lokführer", "Er kennt die Strecke auswendig."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
)

insert into items (quiz_id, category_id, label, position, explanation)
select f.quiz_id, c.id, f.answer, f.position, f.explanation
  from flat f
  join new_categories c
    on c.quiz_id = f.quiz_id
   and c.label = f.label;
