-- Unnützes Wissen, vierte Datei: Körper, Medizin und Wissenschaft.
--
-- Zwanzig Bretter über den eigenen Körper und darüber, wie man ihn im Lauf der
-- Zeit verstanden hat -- einschließlich der Umwege. Zwei Bretter sammeln
-- ausdrücklich das Verworfene: `medizin-frueher` und `verworfene-theorien`.
--
-- Vorher anwenden: supabase/questions/subject-unnuetzes-wissen.sql.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs, fakes) as (
    values

    ('unnuetzes-wissen', 'rudimente-koerper', 'Überbleibsel am Körper',
     'Wozu diente das einmal?',
     'hard', 'Rudiment', 'https://de.wikipedia.org/wiki/Rudiment',
     '[["Wurmfortsatz", "Rest eines größeren Blinddarms", "Er hilft wohl noch der Darmflora."],
       ["Weisheitszähne", "Für härtere Nahrung gedacht", "Der Kiefer wurde im Lauf der Zeit kürzer."],
       ["Steißbein", "Der Rest eines Schwanzes", "Aus mehreren verwachsenen Wirbeln."],
       ["Ohrmuskeln", "Sie bewegten früher die Ohrmuschel", "Nur wenige Menschen können es noch."],
       ["Gänsehaut", "Sie stellte einst ein Fell auf", "Das Fell fehlt, der Reflex blieb."],
       ["Nickhautfalte im Augenwinkel", "Ein drittes Augenlid", "Vögel und Reptilien haben es noch."],
       ["Palmaris-longus-Sehne", "Half beim Klettern", "Vielen Menschen fehlt sie ganz."],
       ["Darwin-Höcker am Ohr", "Rest einer zugespitzten Ohrmuschel", "Etwa jeder Zehnte trägt ihn."],
       ["Körperbehaarung", "Sie wärmte, als sie dichter war", "Übrig ist ein feiner Flaum."],
       ["Musculus pyramidalis", "Ein Bauchmuskel ohne erkennbare Aufgabe", "Bei manchen fehlt er beidseitig."]]'::jsonb,
     '[["Diente der Verdauung von Gras", "Kein Überbleibsel auf diesem Brett tat das."],
       ["Half beim Atmen unter Wasser", "Auf keines in dieser Liste trifft das zu."]]'::jsonb),

    ('unnuetzes-wissen', 'reflexe-namen', 'Reflexe',
     'Was geschieht dabei?',
     'medium', 'Reflex', 'https://de.wikipedia.org/wiki/Reflex',
     '[["Patellarsehnenreflex", "Der Unterschenkel schnellt nach vorn", "Der Klassiker beim Arzt."],
       ["Lidschlussreflex", "Das Auge schließt sich bei Gefahr", "Schneller, als man denken kann."],
       ["Würgereflex", "Der Rachen wehrt Fremdes ab", "Er schützt die Atemwege."],
       ["Greifreflex", "Der Säugling umklammert den Finger", "Er verschwindet nach Monaten."],
       ["Moro-Reflex", "Der Säugling breitet die Arme aus", "Eine Schreckreaktion."],
       ["Singultus", "Das Zwerchfell krampft ruckartig", "Auf Deutsch der Schluckauf."],
       ["Niesreflex", "Ein Luftstoß reinigt die Nase", "Er lässt sich kaum unterdrücken."],
       ["Hustenreflex", "Die Atemwege werden freigeblasen", "Ausgelöst in Kehlkopf und Bronchien."],
       ["Pupillenreflex", "Die Pupille verengt sich bei Licht", "Beide Augen zugleich."],
       ["Suchreflex", "Der Säugling dreht den Kopf zur Berührung", "Er findet so die Brust."]]'::jsonb,
     '[["Die Haare stellen sich auf", "Das ist die Gänsehaut, und die steht nicht auf dem Brett."],
       ["Der Magen knurrt hörbar", "Kein Reflex in dieser Liste meint das."]]'::jsonb),

    ('unnuetzes-wissen', 'schlaf-und-traum', 'Schlaf & Traum',
     'Was bezeichnet der Begriff?',
     'medium', 'Schlaf', 'https://de.wikipedia.org/wiki/Schlafphase',
     '[["REM-Schlaf", "Die Augen bewegen sich schnell", "In dieser Phase träumt man am meisten."],
       ["Tiefschlaf", "Am schwersten zu wecken", "Der Körper erholt sich vor allem hier."],
       ["Schlafwandeln", "Aufstehen ohne aufzuwachen", "Meist aus dem Tiefschlaf heraus."],
       ["Schlafparalyse", "Der Körper bleibt kurz gelähmt", "Der Kopf ist schon wach."],
       ["Luzider Traum", "Man weiß im Traum, dass man träumt", "Manche können ihn steuern."],
       ["Einschlafzucken", "Ein plötzlicher Muskelruck", "Oft mit dem Gefühl zu fallen."],
       ["Schnarchen", "Erschlafftes Gewebe flattert im Rachen", "Auf dem Rücken wird es lauter."],
       ["Zirkadianer Rhythmus", "Die innere Uhr über 24 Stunden", "Licht stellt sie täglich nach."],
       ["Melatonin", "Ein Hormon, das bei Dunkelheit steigt", "Es macht müde."],
       ["Sekundenschlaf", "Wegnicken für den Bruchteil einer Minute", "Am Steuer besonders gefährlich."]]'::jsonb,
     '[["Träume in Schwarzweiß", "Kein Begriff auf diesem Brett meint das."],
       ["Der Schlaf vor Mitternacht", "Er ist keine eigene Phase in dieser Liste."]]'::jsonb),

    ('unnuetzes-wissen', 'sinnestaeuschungen', 'Sinnestäuschungen',
     'Worin besteht die Täuschung?',
     'hard', 'Optische Täuschung',
     'https://de.wikipedia.org/wiki/Optische_T%C3%A4uschung',
     '[["Müller-Lyer-Täuschung", "Pfeilspitzen verändern die gefühlte Länge", "Zwei gleiche Strecken wirken ungleich."],
       ["Ponzo-Täuschung", "Fluchtlinien lassen Gleiches ungleich wirken", "Das Gehirn rechnet Tiefe mit ein."],
       ["Nachbild", "Nach dem Wegsehen erscheint die Gegenfarbe", "Die Sehzellen sind ermüdet."],
       ["Blinder Fleck", "Das Gehirn füllt eine echte Lücke auf", "Dort tritt der Sehnerv aus."],
       ["McGurk-Effekt", "Das Gesehene verändert das Gehörte", "Lippen schlagen die Ohren."],
       ["Phantomschmerz", "Ein fehlendes Glied schmerzt", "Das Gehirn hält die Karte aufrecht."],
       ["Bewegungsnachbild", "Nach dem Wasserfall scheint alles zu steigen", "Auch Wasserfalltäuschung genannt."],
       ["Cocktailparty-Effekt", "Der eigene Name dringt durch den Lärm", "Das Gehör filtert vor."],
       ["Mondtäuschung", "Der Mond wirkt am Horizont größer", "Gemessen ist er gleich groß."],
       ["Stroboskopeffekt", "Räder scheinen sich rückwärts zu drehen", "Die Bildfolge täuscht die Richtung vor."]]'::jsonb,
     '[["Farben verblassen im Dunkeln", "Das ist kein Täuschungseffekt auf diesem Brett."],
       ["Ein Spiegel dreht links und rechts", "Er tut es nicht, und hier steht er nicht."]]'::jsonb),

    ('unnuetzes-wissen', 'medizin-frueher', 'Was einmal als Heilmittel galt',
     'Wogegen wurde das verordnet?',
     'hard', 'Medizingeschichte',
     'https://de.wikipedia.org/wiki/Medizingeschichte',
     '[["Aderlass", "Gegen fast alles", "Krankheit galt als Überschuss an Säften."],
       ["Quecksilber", "Gegen Syphilis", "Die Behandlung war oft tödlicher als die Krankheit."],
       ["Radium", "Als belebender Zusatz", "In Zahnpasta und Trinkwasser verkauft."],
       ["Heroin", "Gegen Husten", "Als angeblich unbedenkliches Mittel im Handel."],
       ["Kokain", "Gegen Zahnschmerzen bei Kindern", "In Tropfen frei erhältlich."],
       ["Trepanation", "Gegen Kopfleiden und Besessenheit", "Ein Loch im Schädel, schon in der Steinzeit."],
       ["Tabakrauch als Einlauf", "Zur Wiederbelebung Ertrunkener", "Es gab dafür eigene Geräte."],
       ["Arsen", "Als Stärkungsmittel", "In kleinen Dosen eingenommen."],
       ["Mumienpulver", "Gegen innere Beschwerden", "Zerriebene Mumien als Arznei."],
       ["Lobotomie", "Gegen seelische Unruhe", "Dafür gab es 1949 einen Nobelpreis."]]'::jsonb,
     '[["Gegen Zahnstein", "Kein Mittel auf diesem Brett wurde dafür verordnet."],
       ["Gegen Kurzsichtigkeit", "Auch dafür steht keines in dieser Liste."]]'::jsonb),

    ('unnuetzes-wissen', 'koerper-lebensleistung', 'Was der Körper in einem Leben schafft',
     'Welche Leistung gehört dazu?',
     'hard', 'Physiologie', 'https://de.wikipedia.org/wiki/Physiologie',
     '[["Das Herz", "Rund drei Milliarden Schläge", "Ohne eine einzige Pause."],
       ["Die Lunge", "Hunderte Millionen Atemzüge", "Rund zwölf in jeder Minute."],
       ["Die Haut", "Erneuert sich etwa alle vier Wochen", "Der Staub im Haus besteht zum Teil daraus."],
       ["Die Kopfhaare", "Zusammengelegt viele Kilometer", "Rund einen Zentimeter im Monat je Haar."],
       ["Die Fingernägel", "Etwa zwei Meter je Nagel", "Über achtzig Jahre gerechnet."],
       ["Die Speicheldrüsen", "Genug für ein kleines Schwimmbecken", "Rund ein Liter am Tag."],
       ["Die Augenlider", "Viele Hundert Millionen Lidschläge", "Etwa alle vier Sekunden einer."],
       ["Der Darm", "Mehrere Dutzend Tonnen Nahrung", "Alles einzeln zerlegt."],
       ["Das Knochenmark", "Milliarden neue Blutzellen am Tag", "Ständiger Ersatz für Verbrauchtes."],
       ["Das Gehirn", "Wird nie ganz abgeschaltet", "Auch im Tiefschlaf arbeitet es weiter."]]'::jsonb,
     '[["Wächst ein Leben lang gleichmäßig weiter", "Auf nichts auf diesem Brett trifft das zu."],
       ["Wird einmal vollständig ersetzt", "Kein Organ in dieser Liste steht dafür."]]'::jsonb),

    ('unnuetzes-wissen', 'vererbung-kurios', 'Vererbung',
     'Was gilt dafür?',
     'hard', 'Vererbung', 'https://de.wikipedia.org/wiki/Vererbung',
     '[["Eineiige Zwillinge", "Gleiche Gene, verschiedene Fingerabdrücke", "Die Muster entstehen im Mutterleib."],
       ["Zweieiige Zwillinge", "Nicht ähnlicher als gewöhnliche Geschwister", "Zwei Eizellen, zwei Samenzellen."],
       ["Rote Haare", "Beide Eltern müssen die Anlage tragen", "Sie kann Generationen überspringen."],
       ["Zungenrollen", "Galt zu Unrecht als einfaches Erbmerkmal", "Es steht bis heute in alten Schulbüchern."],
       ["Farbenblindheit", "Deutlich häufiger bei Männern", "Das Gen sitzt auf dem X-Chromosom."],
       ["Mitochondrien", "Werden nur von der Mutter weitergegeben", "Sie haben eigenes Erbgut."],
       ["Das Y-Chromosom", "Kommt ausschließlich vom Vater", "Und ist deutlich kleiner als das X."],
       ["Laktosetoleranz", "Eine junge Anpassung des Menschen", "Sie breitete sich mit der Viehhaltung aus."],
       ["Chimärismus", "Ein Mensch mit zwei verschiedenen Zellsätzen", "Zwei Embryonen sind verschmolzen."],
       ["Epigenetik", "Gene werden an- und abgeschaltet", "Der Text bleibt, die Lesart ändert sich."]]'::jsonb,
     '[["Wird ausschließlich über den Vater vererbt", "Auf dem Brett steht dafür schon das Y-Chromosom."],
       ["Ändert sich mit der Ernährung dauerhaft im Erbgut", "So arbeitet nichts in dieser Liste."]]'::jsonb),

    ('unnuetzes-wissen', 'einheiten-namensgeber', 'Maßeinheiten & ihre Namensgeber',
     'Nach wem ist die Einheit benannt?',
     'hard', 'SI-Einheit', 'https://de.wikipedia.org/wiki/Internationales_Einheitensystem',
     '[["Newton", "Isaac Newton", "Die Einheit der Kraft."],
       ["Watt", "James Watt", "Die Einheit der Leistung."],
       ["Volt", "Alessandro Volta", "Die Einheit der Spannung."],
       ["Ampere", "André-Marie Ampère", "Die Einheit der Stromstärke."],
       ["Ohm", "Georg Simon Ohm", "Die Einheit des Widerstands."],
       ["Hertz", "Heinrich Hertz", "Die Einheit der Frequenz."],
       ["Kelvin", "William Thomson", "Er wurde zum Lord Kelvin geadelt."],
       ["Pascal", "Blaise Pascal", "Die Einheit des Drucks."],
       ["Joule", "James Prescott Joule", "Die Einheit der Energie."],
       ["Tesla", "Nikola Tesla", "Die Einheit der magnetischen Flussdichte."],
       ["Becquerel", "Henri Becquerel", "Die Einheit der Radioaktivität."],
       ["Celsius", "Anders Celsius", "Seine Skala lief ursprünglich andersherum."]]'::jsonb,
     '[["Albert Einstein", "Nach ihm ist keine Einheit auf diesem Brett benannt."],
       ["Galileo Galilei", "Auch er steht nicht in dieser Liste."]]'::jsonb),

    ('unnuetzes-wissen', 'elemente-namensherkunft', 'Elemente & ihre Namen',
     'Woher hat das Element seinen Namen?',
     'hard', 'Chemisches Element',
     'https://de.wikipedia.org/wiki/Chemisches_Element',
     '[["Helium", "Von der Sonne", "Es wurde zuerst im Sonnenlicht gefunden."],
       ["Cobalt", "Von einem Berggeist", "Bergleute gaben dem tückischen Erz die Schuld."],
       ["Nickel", "Von einem neckenden Kobold", "Kupfernickel galt als wertloses Erz."],
       ["Wolfram", "Es fraß das Zinn wie ein Wolf", "So klagten die Zinnschmelzer."],
       ["Iod", "Von der Farbe Violett", "Der Dampf ist tiefviolett."],
       ["Chlor", "Von der Farbe Grüngelb", "Das Gas ist deutlich gefärbt."],
       ["Chrom", "Von der Farbe schlechthin", "Seine Verbindungen sind sehr bunt."],
       ["Phosphor", "Der Lichtträger", "Er leuchtet an der Luft."],
       ["Germanium", "Von Deutschland", "Der Entdecker war Deutscher."],
       ["Americium", "Von einem Kontinent", "Passend zum darüber stehenden Europium."],
       ["Einsteinium", "Von einem Physiker", "Gefunden im Staub eines Kernwaffentests."],
       ["Neptunium", "Von einem Planeten", "Es folgt im System auf das Uran."]]'::jsonb,
     '[["Von einem griechischen Gott des Meeres", "Kein Element auf diesem Brett trägt seinen Namen so."],
       ["Von einer Stadt in Japan", "Keines in dieser Liste kommt daher."]]'::jsonb),

    ('unnuetzes-wissen', 'alltagsphysik', 'Warum das so ist',
     'Woran liegt das?',
     'medium', 'Optik', 'https://de.wikipedia.org/wiki/Optik',
     '[["Der Himmel ist blau", "Kurzwelliges Licht streut am stärksten", "Blau wird am weitesten verteilt."],
       ["Der Sonnenuntergang ist rot", "Das Licht nimmt den längeren Weg", "Das Blau ist unterwegs herausgestreut."],
       ["Wolken sind weiß", "Große Tropfen streuen alle Farben gleich", "Deshalb bleibt es unbunt."],
       ["Das Meer wirkt blau", "Wasser schluckt rotes Licht zuerst", "In der Tiefe bleibt nur Blau übrig."],
       ["Seifenblasen schillern", "Licht überlagert sich in der dünnen Haut", "Die Dicke bestimmt die Farbe."],
       ["Ein Strohhalm im Glas knickt", "Licht wird beim Übergang gebrochen", "Wasser und Luft leiten es verschieden."],
       ["Metall fühlt sich kälter an als Holz", "Es leitet die Wärme schneller ab", "Beide sind gleich warm."],
       ["Heiße Luft steigt auf", "Sie ist leichter als kalte", "Deshalb fliegt der Ballon."],
       ["Der Blitz kommt vor dem Donner", "Licht ist viel schneller als Schall", "Drei Sekunden bedeuten einen Kilometer."],
       ["Ein Regenbogen steht immer gegenüber der Sonne", "Das Licht wird im Tropfen zurückgeworfen", "Er erscheint unter einem festen Winkel."]]'::jsonb,
     '[["Die Erdanziehung ist am Äquator stärker", "Sie ist dort sogar etwas schwächer."],
       ["Kaltes Wasser ist schwerer als Eis", "Auf keine Zeile auf diesem Brett trifft das als Erklärung zu."]]'::jsonb),

    ('unnuetzes-wissen', 'temperaturen-vergleich', 'Temperaturen im Vergleich',
     'Welche Temperatur gehört dazu?',
     'hard', 'Temperatur', 'https://de.wikipedia.org/wiki/Temperatur',
     '[["Der absolute Nullpunkt", "Minus 273,15 Grad", "Kälter geht es nicht."],
       ["Flüssiger Stickstoff", "Minus 196 Grad", "Er siedet bei dieser Temperatur."],
       ["Der kälteste bewohnte Ort", "Unter minus 60 Grad", "Oimjakon in Sibirien."],
       ["Der Gefrierpunkt von Wasser", "Null Grad", "Auf Meereshöhe."],
       ["Die menschliche Körpertemperatur", "Rund 37 Grad", "Sie schwankt über den Tag."],
       ["Der Siedepunkt von Wasser", "Hundert Grad", "Auf dem Berg deutlich weniger."],
       ["Ein Backofen beim Brotbacken", "Rund 250 Grad", "Zu Beginn oft heißer."],
       ["Fließende Lava", "Bis über 1.200 Grad", "Je nach Zusammensetzung."],
       ["Die Oberfläche der Sonne", "Rund 5.500 Grad", "Die Flecken sind kühler."],
       ["Der Kern der Sonne", "Rund 15 Millionen Grad", "Dort verschmelzen die Kerne."]]'::jsonb,
     '[["Genau tausend Grad", "Nichts auf diesem Brett hat diese Temperatur."],
       ["Minus 500 Grad", "Unter den absoluten Nullpunkt kommt nichts."]]'::jsonb),

    ('unnuetzes-wissen', 'geschwindigkeiten-vergleich', 'Geschwindigkeiten im Vergleich',
     'Wie schnell ist das?',
     'medium', 'Geschwindigkeit', 'https://de.wikipedia.org/wiki/Geschwindigkeit',
     '[["Licht im Vakuum", "Rund 300.000 Kilometer je Sekunde", "Die Grenze für alles."],
       ["Schall in Luft", "Rund 340 Meter je Sekunde", "Bei Zimmertemperatur."],
       ["Die Erde um die Sonne", "Rund 30 Kilometer je Sekunde", "Ohne dass wir es merken."],
       ["Die Raumstation im Orbit", "Rund 28.000 Stundenkilometer", "Eine Erdumrundung in 90 Minuten."],
       ["Ein Passagierflugzeug", "Rund 900 Stundenkilometer", "In Reiseflughöhe."],
       ["Ein Gepard über kurze Strecke", "Rund 110 Stundenkilometer", "Nur für wenige Sekunden."],
       ["Ein Nervensignal", "Bis zu 120 Meter je Sekunde", "In dick isolierten Fasern."],
       ["Ein Marathonläufer an der Spitze", "Rund 20 Stundenkilometer", "Über zwei Stunden gehalten."],
       ["Eine Weinbergschnecke", "Rund drei Meter je Minute", "Und das nur zügig unterwegs."],
       ["Die Kontinentaldrift", "Wenige Zentimeter im Jahr", "Etwa so schnell wie Fingernägel wachsen."]]'::jsonb,
     '[["Doppelte Lichtgeschwindigkeit", "Schneller als Licht ist nichts auf diesem Brett."],
       ["Genau ein Kilometer je Stunde", "Nichts in dieser Liste bewegt sich so."]]'::jsonb),

    ('unnuetzes-wissen', 'gewichte-vergleich', 'Gewichte im Vergleich',
     'Wie schwer ist das?',
     'hard', 'Masse', 'https://de.wikipedia.org/wiki/Masse_(Physik)',
     '[["Ein Liter Wasser", "Ein Kilogramm", "Daher stammt die alte Definition."],
       ["Ein Kubikmeter Luft", "Rund 1,2 Kilogramm", "Auf Meereshöhe."],
       ["Ein Zuckerwürfel", "Rund drei Gramm", "Ein handliches Vergleichsmaß."],
       ["Ein Blatt Druckerpapier", "Rund fünf Gramm", "Bei achtzig Gramm je Quadratmeter."],
       ["Eine Ein-Euro-Münze", "7,5 Gramm", "Ein genormtes Gewicht."],
       ["Das menschliche Gehirn", "Rund 1,4 Kilogramm", "Etwa zwei Prozent des Körpers."],
       ["Eine mittlere Schönwetterwolke", "Mehrere hundert Tonnen", "Verteilt auf winzige Tröpfchen."],
       ["Das Herz eines Blauwals", "Mehrere hundert Kilogramm", "So schwer wie ein Kleinwagen."],
       ["Ein Kubikmeter Osmium", "Über 22 Tonnen", "Das dichteste natürliche Element."],
       ["Die Luftsäule über einem Quadratmeter", "Rund zehn Tonnen", "Wir merken es nicht."]]'::jsonb,
     '[["Genau eine Tonne", "Nichts auf diesem Brett wiegt exakt so viel."],
       ["Gar nichts, weil es schwerelos ist", "Auf nichts in dieser Liste trifft das zu."]]'::jsonb),

    ('unnuetzes-wissen', 'medizin-erfindungen-alltag', 'Medizin im Alltag',
     'Wie kam es dazu?',
     'medium', 'Medizintechnik',
     'https://de.wikipedia.org/wiki/Medizintechnik',
     '[["Das Pflaster", "Ein Angestellter bastelte es für seine Frau", "Sie schnitt sich beim Kochen ständig."],
       ["Das Röntgenbild", "Die erste Aufnahme zeigte eine Hand", "Es war die Hand seiner Frau."],
       ["Das Stethoskop", "Aus einer zusammengerollten Papierrolle", "Der Arzt wollte das Ohr nicht auflegen."],
       ["Die Impfung", "Der Name kommt von der Kuh", "Vacca heißt Kuh auf Latein."],
       ["Die Narkose", "Zuerst öffentlich 1846 vorgeführt", "Mit Äther in Boston."],
       ["Die Brille", "Im 13. Jahrhundert in Italien", "Zuerst nur zum Lesen."],
       ["Die Nylon-Zahnbürste", "1938 auf den Markt gebracht", "Davor waren es Schweineborsten."],
       ["Aspirin", "Aus der Weidenrinde entwickelt", "Deren Wirkstoff war lange bekannt."],
       ["Die Blutdruckmanschette", "Seit 1896 am Oberarm gemessen", "Vorher war es kaum praktikabel."],
       ["Der Gipsverband", "Von einem Militärarzt eingeführt", "Er brauchte etwas Schnelles im Feld."]]'::jsonb,
     '[["Aus einem Spielzeug entstanden", "Nichts auf diesem Brett kam so zustande."],
       ["Von einem Patienten selbst erfunden", "Auf nichts in dieser Liste trifft das zu."]]'::jsonb),

    ('unnuetzes-wissen', 'krankheitsnamen-kurios', 'Krankheiten mit seltsamen Namen',
     'Was steckt wirklich dahinter?',
     'hard', 'Krankheit', 'https://de.wikipedia.org/wiki/Krankheit',
     '[["Hexenschuss", "Ein plötzlicher Schmerz im unteren Rücken", "Man dachte an einen Schuss von außen."],
       ["Tennisarm", "Eine Reizung der Sehnen am Ellenbogen", "Auch ohne je Tennis gespielt zu haben."],
       ["Mausarm", "Beschwerden durch immer gleiche Bewegungen", "Vor allem am Bildschirmarbeitsplatz."],
       ["Schaufensterkrankheit", "Durchblutungsstörung in den Beinen", "Man bleibt vor Schmerz stehen und tut, als schaue man."],
       ["Wolfsrachen", "Eine Spalte im Gaumen", "Sie entsteht vor der Geburt."],
       ["Ziegenpeter", "Der Mumps", "Die Wangen schwellen deutlich an."],
       ["Pfeiffersches Drüsenfieber", "Eine Virusinfektion mit langer Müdigkeit", "Auch Kusskrankheit genannt."],
       ["Katzenschrei-Syndrom", "Ein Gendefekt mit auffälligem Weinen", "Der Name beschreibt den Klang."],
       ["Gürtelrose", "Ein wiedererwachtes Windpockenvirus", "Es bleibt lebenslang im Körper."],
       ["Fuchsbandwurm", "Ein Parasit, der die Leber befällt", "Die Ansteckung ist selten, der Verlauf schwer."]]'::jsonb,
     '[["Eine Allergie gegen Katzenhaare", "Kein Name auf diesem Brett meint das."],
       ["Ein gebrochener Zeh", "Dafür steht keiner in dieser Liste."]]'::jsonb),

    ('unnuetzes-wissen', 'selbstversuche', 'Forscher an sich selbst',
     'Was tat die Person sich selbst an?',
     'hard', 'Selbstversuch', 'https://de.wikipedia.org/wiki/Selbstversuch',
     '[["Barry Marshall", "Trank eine Bakterienkultur", "Er bewies damit die Ursache von Magengeschwüren."],
       ["Werner Forßmann", "Schob sich einen Schlauch ins eigene Herz", "Und ging damit zum Röntgen."],
       ["Albert Hofmann", "Nahm LSD und fuhr Fahrrad", "Der Tag hat einen eigenen Namen bekommen."],
       ["Max von Pettenkofer", "Trank Cholerabakterien", "Er wollte seine Theorie bestätigen."],
       ["Humphry Davy", "Atmete Lachgas ein", "Und beschrieb die Wirkung genau."],
       ["Isaac Newton", "Schob sich eine Nadel hinter das Auge", "Um die Wahrnehmung von Farbe zu prüfen."],
       ["Jonas Salk", "Impfte sich und seine Familie", "Noch vor der großen Erprobung."],
       ["Stubbins Ffirth", "Rieb sich Erbrochenes in Schnitte", "Er hielt Gelbfieber für nicht ansteckend."],
       ["John Haldane", "Setzte sich extremen Drücken aus", "Für die Tauchmedizin."],
       ["Nicolae Minovici", "Ließ sich mehrfach selbst aufhängen", "Für eine Arbeit über den Strangtod."]]'::jsonb,
     '[["Ließ sich einfrieren und wieder auftauen", "Niemand auf diesem Brett tat das."],
       ["Verbrachte ein Jahr ohne Schlaf", "Auf niemanden in dieser Liste trifft das zu."]]'::jsonb),

    ('unnuetzes-wissen', 'laborgeraete', 'Im Labor',
     'Wozu dient das Gerät?',
     'medium', 'Laborgerät', 'https://de.wikipedia.org/wiki/Laborger%C3%A4t',
     '[["Bunsenbrenner", "Erhitzen mit regelbarer Flamme", "Die Luftzufuhr steuert die Hitze."],
       ["Reagenzglas", "Kleine Mengen aufnehmen", "Ein Röhrchen mit rundem Boden."],
       ["Erlenmeyerkolben", "Schwenken ohne Verschütten", "Der Hals ist bewusst eng."],
       ["Pipette", "Genau abgemessene Mengen übertragen", "Auf den Tropfen genau."],
       ["Zentrifuge", "Nach Dichte trennen", "Durch sehr schnelle Drehung."],
       ["Mikroskop", "Kleines stark vergrößern", "Über mehrere Linsen."],
       ["Petrischale", "Kulturen wachsen lassen", "Flach und mit Deckel."],
       ["Mörser", "Feste Stoffe zerreiben", "Mit dem Pistill dazu."],
       ["Bürette", "Tropfenweise zugeben", "Für Titrationen unentbehrlich."],
       ["Abzug", "Dämpfe absaugen", "Er schützt die Arbeitenden."]]'::jsonb,
     '[["Temperatur messen", "Das Thermometer steht nicht auf diesem Brett."],
       ["Proben tiefkühlen", "Kein Gerät in dieser Liste tut das."]]'::jsonb),

    ('unnuetzes-wissen', 'verworfene-theorien', 'Verworfene Theorien',
     'Was behauptete die Theorie?',
     'hard', 'Wissenschaftsgeschichte',
     'https://de.wikipedia.org/wiki/Wissenschaftsgeschichte',
     '[["Phlogiston", "Beim Verbrennen entweiche ein Stoff", "Tatsächlich kommt Sauerstoff hinzu."],
       ["Lichtäther", "Licht brauche ein Trägermedium", "Ein Versuch von 1887 fand keines."],
       ["Urzeugung", "Leben entstehe aus Unbelebtem", "Maden aus Fleisch, Mäuse aus Getreide."],
       ["Viersäftelehre", "Gesundheit sei ein Gleichgewicht von Körpersäften", "Sie hielt sich fast zweitausend Jahre."],
       ["Lamarckismus", "Erworbene Eigenschaften würden vererbt", "Die Giraffe recke den Hals länger."],
       ["Geozentrisches Weltbild", "Die Erde stehe im Mittelpunkt", "Alles kreise um sie herum."],
       ["Phrenologie", "Der Charakter lasse sich am Schädel ablesen", "Mit Tastkarten und Messgeräten."],
       ["Marskanäle", "Auf dem Mars gebe es angelegte Wasserwege", "Ein Beobachtungsfehler am Fernrohr."],
       ["Feste Kontinente", "Kontinente könnten sich nicht bewegen", "Wegeners Idee galt lange als abwegig."],
       ["Kalorikum", "Wärme sei eine unsichtbare Flüssigkeit", "Sie sollte von warm nach kalt fließen."]]'::jsonb,
     '[["Die Erde sei eine Scheibe", "Das lehrte die Wissenschaft nie so, und hier steht es nicht."],
       ["Atome seien unteilbar", "Als Theorie stand das lange, auf diesem Brett aber nicht."]]'::jsonb),

    ('unnuetzes-wissen', 'mathematik-kurios', 'Mathematik zum Staunen',
     'Was besagt das?',
     'hard', 'Mathematik', 'https://de.wikipedia.org/wiki/Mathematik',
     '[["Geburtstagsparadoxon", "Ab 23 Personen ist ein gemeinsamer Geburtstag wahrscheinlich", "Es zählen alle Paare, nicht die Tage."],
       ["Hilberts Hotel", "Ein volles Hotel nimmt weitere Gäste auf", "Wenn es unendlich viele Zimmer hat."],
       ["Möbiusband", "Eine Fläche mit nur einer Seite", "Ein Streifen, einmal verdreht und geklebt."],
       ["Vier-Farben-Satz", "Vier Farben genügen für jede Landkarte", "Bewiesen erst mit Computerhilfe."],
       ["Monty-Hall-Problem", "Wechseln verdoppelt die Gewinnchance", "Selbst Fachleute stritten darüber."],
       ["Satz des Euklid", "Es gibt unendlich viele Primzahlen", "Der Beweis ist über zweitausend Jahre alt."],
       ["Cantors Diagonalargument", "Manche Unendlichkeiten sind größer als andere", "Die reellen Zahlen sind nicht abzählbar."],
       ["Fibonacci-Folge", "Jede Zahl ist die Summe der beiden davor", "Sie taucht in Blüten und Zapfen auf."],
       ["Kleinsche Flasche", "Ein Körper ohne Innen und Außen", "Im dreidimensionalen Raum nicht sauber baubar."],
       ["Die Null", "Kam als eigene Zahl erst spät hinzu", "Über Indien und die arabische Welt."]]'::jsonb,
     '[["Die größte Primzahl ist bekannt", "Es gibt keine größte, wie das Brett selbst sagt."],
       ["Pi endet nach tausend Stellen", "Es endet nie."]]'::jsonb),

    ('unnuetzes-wissen', 'arztdeutsch', 'Was der Arzt meint',
     'Was bedeutet der Begriff?',
     'medium', 'Medizinische Fachsprache',
     'https://de.wikipedia.org/wiki/Medizinische_Fachsprache',
     '[["Idiopathisch", "Ohne bekannte Ursache", "Ein ehrliches Wort für Ratlosigkeit."],
       ["Akut", "Plötzlich und heftig", "Das Gegenteil von chronisch."],
       ["Chronisch", "Über lange Zeit bestehend", "Oft über Jahre."],
       ["Benigne", "Gutartig", "Es wuchert nicht in Nachbargewebe."],
       ["Maligne", "Bösartig", "Es kann streuen."],
       ["Anamnese", "Die Vorgeschichte im Gespräch", "Griechisch für Erinnerung."],
       ["Diagnose", "Die Feststellung der Krankheit", "Am Ende der Untersuchung."],
       ["Prognose", "Die erwartete Entwicklung", "Ein Blick nach vorn."],
       ["Rezidiv", "Das Wiederauftreten nach Besserung", "Besonders gefürchtet nach Krebs."],
       ["Indikation", "Der Grund für eine Behandlung", "Ohne sie wird nicht behandelt."]]'::jsonb,
     '[["Die Rechnung an die Krankenkasse", "Kein Begriff auf diesem Brett meint das."],
       ["Der Termin beim Facharzt", "Dafür steht keiner in dieser Liste."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

fakes as (
    select q.id                                         as quiz_id,
           k.value ->> 0                                as label,
           k.value ->> 1                                as explanation,
           (jsonb_array_length(sp.pairs) + k.ord)::int  as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.fakes) with ordinality k(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
),

paired as (
    insert into items (quiz_id, category_id, label, position, explanation)
    select f.quiz_id, c.id, f.answer, f.position, f.explanation
      from flat f
      join new_categories c
        on c.quiz_id = f.quiz_id
       and c.label = f.label
    returning id
)

insert into items (quiz_id, category_id, label, position, explanation)
select k.quiz_id, null, k.label, k.position, k.explanation
  from fakes k;
