-- Unnützes Wissen, dritte Datei: Tiere und Natur.
--
-- Zwanzig Bretter über Lebewesen und die Erde, die sie tragen. Die Regel für
-- dieses Gebiet gilt auch hier: nur Belegbares. Gerade über Tiere kursieren
-- besonders viele hübsche Sätze, die niemand nachgerechnet hat.
--
-- Vorher anwenden: supabase/questions/subject-unnuetzes-wissen.sql.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs, fakes) as (
    values

    ('unnuetzes-wissen', 'tiergruppen-namen', 'Wie eine Gruppe heißt',
     'Wie nennt man eine Gruppe dieser Tiere?',
     'medium', 'Kollektivum', 'https://de.wikipedia.org/wiki/Kollektivum',
     '[["Wölfe", "Ein Rudel", "Auch bei Hunden gebräuchlich."],
       ["Fische", "Ein Schwarm", "Tausende bewegen sich wie einer."],
       ["Kühe", "Eine Herde", "Das Wort gilt für viele Weidetiere."],
       ["Wildschweine", "Eine Rotte", "Ein Begriff aus der Jägersprache."],
       ["Jagdhunde", "Eine Meute", "Nur für die Jagdhunde gemeinsam."],
       ["Pinguine", "Eine Kolonie", "Oft Zehntausende Brutpaare."],
       ["Bienen", "Ein Volk", "Mit einer einzigen Königin."],
       ["Ameisen", "Ein Staat", "Mit fester Arbeitsteilung."],
       ["Rebhühner", "Eine Kette", "Ebenfalls Jägersprache."],
       ["Krähen", "Eine Schar", "Für viele Vögel gebräuchlich."],
       ["Wale", "Eine Schule", "Aus dem Englischen übernommen."]]'::jsonb,
     '[["Ein Schwarm Wölfe", "Wölfe bilden ein Rudel, keinen Schwarm."],
       ["Ein Verband", "So heißt keine Tiergruppe auf diesem Brett."]]'::jsonb),

    ('unnuetzes-wissen', 'tierschlaf', 'Schlaf im Tierreich',
     'Wie schläft das Tier?',
     'medium', 'Schlaf', 'https://de.wikipedia.org/wiki/Schlaf',
     '[["Giraffe", "Nur wenige Stunden, meist im Stehen", "Aufstehen kostet zu viel Zeit."],
       ["Koala", "Bis zu zwanzig Stunden am Tag", "Die Blätterkost gibt wenig Energie."],
       ["Mauersegler", "Im Flug, monatelang ohne Landung", "Er schläft in der Luft."],
       ["Fledermaus", "Kopfüber hängend", "Die Krallen halten ohne Kraftaufwand."],
       ["Seeotter", "Treibend, an Tang festgehalten", "Sonst würde er abgetrieben."],
       ["Braunbär", "Winterruhe, aus der er aufwacht", "Kein echter Winterschlaf."],
       ["Murmeltier", "Echter Winterschlaf mit stark gesenktem Puls", "Der Herzschlag fällt auf wenige Schläge."],
       ["Weinbergschnecke", "Kann Jahre in Trockenstarre überdauern", "Mit einem Kalkdeckel verschlossen."],
       ["Elefant", "Nur rund zwei Stunden", "Der kürzeste Schlaf aller Säugetiere."],
       ["Pferd", "Im Stehen dösend, im Liegen tief", "Ein Bandapparat hält die Beine gestreckt."]]'::jsonb,
     '[["Gar nicht, ein Leben lang", "Kein Tier auf diesem Brett kommt ohne Schlaf aus."],
       ["Nur bei Vollmond", "Auf keines in dieser Liste trifft das zu."]]'::jsonb),

    ('unnuetzes-wissen', 'tierische-sinne', 'Tierische Sinne',
     'Was nimmt das Tier wahr?',
     'hard', 'Sinnesorgan', 'https://de.wikipedia.org/wiki/Sinnesorgan',
     '[["Hund", "Gerüche millionenfach feiner als wir", "Die Riechschleimhaut ist riesig."],
       ["Fledermaus", "Die Umgebung über Echos", "Sie ruft und hört das Zurückgeworfene."],
       ["Hai", "Elektrische Felder", "Über Sinnesgruben an der Schnauze."],
       ["Grubenotter", "Wärmebilder ihrer Beute", "Zwei Gruben zwischen Auge und Nase."],
       ["Brieftaube", "Das Magnetfeld der Erde", "Sie findet damit nach Hause."],
       ["Katze", "Umrisse bei fast völliger Dunkelheit", "Eine spiegelnde Schicht hinter der Netzhaut."],
       ["Elefant", "Töne unterhalb unserer Hörschwelle", "Infraschall über viele Kilometer."],
       ["Nachtfalter", "Duftstoffe über Kilometer hinweg", "Die Fühler sind fein gefiedert."],
       ["Fangschreckenkrebs", "Sehr viel mehr Farbkanäle als wir", "Sein Auge ist einzigartig gebaut."],
       ["Schlange", "Geruchsspuren mit der Zunge", "Sie führt sie zu einem Sinnesorgan im Gaumen."],
       ["Biene", "Ultraviolettes Licht", "Blüten tragen für sie unsichtbare Muster."]]'::jsonb,
     '[["Röntgenstrahlen", "Kein Tier auf diesem Brett nimmt sie wahr."],
       ["Radiowellen", "Auch die spürt keines in dieser Liste."]]'::jsonb),

    ('unnuetzes-wissen', 'tier-lebenserwartung', 'Wie alt Tiere werden',
     'Wie alt wird das Tier ungefähr?',
     'medium', 'Lebenserwartung', 'https://de.wikipedia.org/wiki/Lebenserwartung',
     '[["Islandmuschel", "Über 500 Jahre", "Die Ringe der Schale lassen sich zählen."],
       ["Grönlandhai", "Über 300 Jahre", "Das älteste bekannte Wirbeltier."],
       ["Riesenschildkröte", "Über 150 Jahre", "Manche überlebten ihre Entdecker."],
       ["Blauwal", "Etwa 80 bis 90 Jahre", "Ähnlich wie ein Mensch."],
       ["Graupapagei", "Bis zu 60 Jahre", "Er wird oft vererbt."],
       ["Elefant", "Rund 60 bis 70 Jahre", "Die Backenzähne begrenzen das Leben."],
       ["Koi", "Über 50 Jahre", "Einzelne Fische wurden weit älter."],
       ["Nacktmull", "Rund 30 Jahre", "Für ein Nagetier außergewöhnlich."],
       ["Haushund", "Etwa 10 bis 15 Jahre", "Kleine Rassen leben länger."],
       ["Hausmaus", "Ein bis zwei Jahre", "In Gefangenschaft etwas länger."]]'::jsonb,
     '[["Genau tausend Jahre", "Kein Tier auf diesem Brett wird so alt."],
       ["Nur wenige Stunden", "Keines in dieser Liste lebt so kurz."]]'::jsonb),

    ('unnuetzes-wissen', 'tiere-im-weltraum', 'Tiere im Weltraum',
     'Wofür steht dieses Tier in der Raumfahrt?',
     'hard', 'Tiere im Weltraum',
     'https://de.wikipedia.org/wiki/Tiere_im_Weltraum',
     '[["Fruchtfliegen", "Die ersten Tiere überhaupt im All", "1947 an Bord einer erbeuteten Rakete."],
       ["Laika", "Der erste Hund im Erdorbit", "1957 an Bord von Sputnik 2."],
       ["Ham", "Der erste Schimpanse im All", "1961, kurz vor dem ersten Menschen."],
       ["Félicette", "Die erste Katze im All", "1963 von Frankreich gestartet."],
       ["Zwei Schildkröten", "Die ersten Lebewesen um den Mond", "1968 an Bord von Zond 5."],
       ["Bärtierchen", "Überlebten offen im Vakuum", "2007 in einem europäischen Versuch."],
       ["Kreuzspinnen", "Wobten Netze in Schwerelosigkeit", "Die ersten waren sichtlich unordentlich."],
       ["Fadenwürmer", "Überstanden ein Shuttleunglück", "Sie wurden im Wrack lebend gefunden."],
       ["Quallen", "Wurden im Orbit herangezogen", "Ihr Gleichgewichtssinn litt danach."],
       ["Mäuse", "Standardtiere für Langzeitversuche", "Sie fliegen bis heute mit."]]'::jsonb,
     '[["Das erste Tier auf dem Mond", "Auf dem Mond stand nie ein Tier."],
       ["Der erste Fisch im Orbit", "Kein Tier auf diesem Brett steht dafür."]]'::jsonb),

    ('unnuetzes-wissen', 'ausgestorbene-tiere', 'Ausgestorbene Tiere',
     'Wo und wann verschwand die Art?',
     'hard', 'Ausgestorbene Art',
     'https://de.wikipedia.org/wiki/Aussterben',
     '[["Dodo", "Mauritius, um 1690", "Flugunfähig und ohne Fluchtinstinkt."],
       ["Riesenalk", "Nordatlantik, 1844", "Die letzten beiden wurden erschlagen."],
       ["Steller-Seekuh", "Beringmeer, 1768", "27 Jahre nach ihrer Entdeckung."],
       ["Auerochse", "Polen, 1627", "Das letzte Tier starb in einem Wildpark."],
       ["Quagga", "Südafrika, 1883", "Die letzte Stute starb in Amsterdam."],
       ["Wandertaube", "Nordamerika, 1914", "Zuvor der häufigste Vogel des Kontinents."],
       ["Karolinasittich", "USA, 1918", "Der einzige Papagei im Osten der USA."],
       ["Beutelwolf", "Tasmanien, 1936", "Das letzte Tier starb im Zoo von Hobart."],
       ["Moa", "Neuseeland, um 1400", "Kurz nach der Besiedlung verschwunden."],
       ["Goldkröte", "Costa Rica, 1989", "Nur in einem einzigen Nebelwald zu Hause."]]'::jsonb,
     '[["Australien, 1952", "Keine Art auf diesem Brett verschwand dort."],
       ["Sibirien, vor 4.000 Jahren", "Das Mammut hielt sich so lange, steht hier aber nicht."]]'::jsonb),

    ('unnuetzes-wissen', 'tierische-verteidigung', 'Wie Tiere sich wehren',
     'Womit verteidigt sich das Tier?',
     'medium', 'Abwehrmechanismus',
     'https://de.wikipedia.org/wiki/Verteidigung_(Biologie)',
     '[["Stinktier", "Ein übel riechendes Sekret", "Es trifft auf mehrere Meter."],
       ["Igel", "Aufgestellte Stacheln", "Rund 8.000 Stück auf dem Rücken."],
       ["Tintenfisch", "Eine Wolke aus Tinte", "Sie verwirrt und riecht zugleich."],
       ["Eidechse", "Der abgeworfene Schwanz", "Er zuckt weiter und lenkt ab."],
       ["Bombardierkäfer", "Ein heißer Flüssigkeitsstrahl", "Die Mischung entsteht erst beim Ausstoß."],
       ["Opossum", "Sich totstellen", "Es wirkt bis hin zum Geruch."],
       ["Pfeilgiftfrosch", "Eine grelle Warnfarbe", "Wer ihn einmal probiert, lässt es künftig."],
       ["Seegurke", "Ausgestoßene Innereien", "Sie wachsen nach."],
       ["Krake", "Farbe und Struktur der Haut", "Sie verschwindet vor dem Untergrund."],
       ["Klapperschlange", "Ein warnendes Geräusch", "Erst danach beißt sie."]]'::jsonb,
     '[["Ein lauter Schrei", "Kein Tier auf diesem Brett wehrt sich so."],
       ["Ein elektrischer Schlag", "Der Zitteraal kann das, und der fehlt hier."]]'::jsonb),

    ('unnuetzes-wissen', 'nutztiere-leistung', 'Was Nutztiere leisten',
     'Was leistet das Tier?',
     'medium', 'Nutztier', 'https://de.wikipedia.org/wiki/Nutztier',
     '[["Milchkuh", "Rund 8.000 Liter Milch im Jahr", "Vor hundert Jahren war es ein Bruchteil."],
       ["Legehenne", "Rund 300 Eier im Jahr", "Fast eines an jedem Tag."],
       ["Honigbiene", "Etwa einen Teelöffel Honig im Leben", "Das ganze Volk schafft die Ernte."],
       ["Merinoschaf", "Mehrere Kilogramm Wolle im Jahr", "Es wird einmal jährlich geschoren."],
       ["Seidenraupe", "Einen Faden von fast einem Kilometer", "Aus einem einzigen Kokon."],
       ["Brieftaube", "Heimflug über Hunderte Kilometer", "Sie orientiert sich mehrfach."],
       ["Kaltblutpferd", "Zugkraft weit über dem eigenen Gewicht", "Zu zweit noch mehr als doppelt so viel."],
       ["Trüffelschwein", "Pilze tief unter der Erde erschnüffeln", "Heute nehmen viele lieber Hunde."],
       ["Blindenführhund", "Dutzende Kommandos sicher ausführen", "Die Ausbildung dauert Jahre."],
       ["Wasserbüffel", "Den Pflug im nassen Reisfeld ziehen", "Auf Böden, die Traktoren nicht tragen."]]'::jsonb,
     '[["Wolle und Milch zugleich in großer Menge", "Kein Tier auf diesem Brett steht dafür."],
       ["Ganz ohne Futter auskommen", "Auf keines in dieser Liste trifft das zu."]]'::jsonb),

    ('unnuetzes-wissen', 'tiere-rekord-koerperteile', 'Rekorde am Körper',
     'Welcher Körperteil ist gemeint?',
     'hard', 'Anatomie', 'https://de.wikipedia.org/wiki/Anatomie',
     '[["Chamäleon", "Eine Zunge länger als der eigene Körper", "Sie schnellt in Sekundenbruchteilen hervor."],
       ["Giraffe", "Der längste Hals", "Mit denselben sieben Wirbeln wie wir."],
       ["Afrikanischer Elefant", "Die größten Ohren", "Sie dienen auch der Kühlung."],
       ["Riesenkalmar", "Die größten Augen im Tierreich", "So groß wie Teller."],
       ["Narwal", "Ein Stoßzahn wie eine Lanze", "Es ist ein verlängerter Eckzahn."],
       ["Ameisenbär", "Ein röhrenförmiges Maul ohne Zähne", "Er schluckt die Beute unzerkaut."],
       ["Kolibri", "Der schnellste Flügelschlag", "Bis zu achtzig Mal je Sekunde."],
       ["Blauwal", "Das größte Herz aller Tiere", "So schwer wie ein Kleinwagen."],
       ["Fledermaus", "Flughäute zwischen den Fingern", "Die Hand ist der Flügel."],
       ["Seepferdchen", "Ein Greifschwanz zum Festhalten", "Damit hält es sich an Pflanzen."]]'::jsonb,
     '[["Der längste Stoßzahn an Land", "Als Antwort passt das zu nichts auf diesem Brett."],
       ["Ein drittes Auge auf der Stirn", "Kein Tier in dieser Liste hat eines."]]'::jsonb),

    ('unnuetzes-wissen', 'pilze-kurios', 'Pilze',
     'Was zeichnet den Pilz aus?',
     'hard', 'Pilze', 'https://de.wikipedia.org/wiki/Pilze',
     '[["Hallimasch", "Das größte bekannte Lebewesen der Erde", "Ein Geflecht über viele Quadratkilometer."],
       ["Trüffel", "Wächst vollständig unter der Erde", "Deshalb die Suche mit Tieren."],
       ["Hefe", "Ein einzelliger Pilz", "Ohne ihn kein Bier und kein Brot."],
       ["Penicillium", "Lieferte das erste Antibiotikum", "Fleming fand es 1928 im Labor."],
       ["Zunderschwamm", "Diente jahrtausendelang zum Feuermachen", "Auch Ötzi trug ihn bei sich."],
       ["Stinkmorchel", "Lockt Fliegen mit Aasgeruch", "Sie tragen die Sporen fort."],
       ["Grüner Knollenblätterpilz", "Der gefährlichste Giftpilz Europas", "Die Wirkung setzt erst nach Stunden ein."],
       ["Ölbaumtrichterling", "Glimmt im Dunkeln grünlich", "Das Leuchten ist schwach, aber echt."],
       ["Fliegenpilz", "Das rot-weiße Sinnbild schlechthin", "Giftig, aber selten tödlich."],
       ["Edelschimmel auf Käse", "Wird bewusst zugesetzt", "Er macht Roquefort und Camembert aus."]]'::jsonb,
     '[["Betreibt Fotosynthese wie eine Pflanze", "Kein Pilz auf diesem Brett tut das, und Pilze generell nicht."],
       ["Wächst ausschließlich im Salzwasser", "Keiner in dieser Liste lebt dort."]]'::jsonb),

    ('unnuetzes-wissen', 'baeume-rekorde', 'Bäume mit Rekorden',
     'Wofür steht dieser Baum?',
     'medium', 'Baum', 'https://de.wikipedia.org/wiki/Baum',
     '[["Küstenmammutbaum", "Der höchste Baum der Erde", "Über 115 Meter."],
       ["Riesenmammutbaum", "Der massereichste Einzelbaum", "Der General Sherman in Kalifornien."],
       ["Pando", "Ein ganzer Wald aus einem Wurzelstock", "Zehntausende Stämme, ein Lebewesen."],
       ["Ginkgo", "Überlebte die Bombe von Hiroshima", "Mehrere Bäume trieben wieder aus."],
       ["Eibe", "Wird über tausend Jahre alt", "Der Stamm höhlt sich dabei aus."],
       ["Drachenbaum", "Sein Harz ist blutrot", "Daher der Name Drachenblut."],
       ["Korkeiche", "Ihre Rinde wächst nach der Ernte nach", "Alle neun bis zwölf Jahre."],
       ["Banyan", "Bildet aus Luftwurzeln neue Stämme", "Ein Baum wird zum Hain."],
       ["Mangrove", "Wurzelt im Salzwasser", "Sie filtert das Salz heraus."],
       ["Zitterpappel", "Ihre Blätter zittern beim leisesten Wind", "Der Blattstiel ist abgeflacht."]]'::jsonb,
     '[["Wächst kopfüber aus dem Boden", "Kein Baum auf diesem Brett tut das."],
       ["Trägt nur alle hundert Jahre Blätter", "Auf keinen in dieser Liste trifft das zu."]]'::jsonb),

    ('unnuetzes-wissen', 'wetter-kurios', 'Seltene Wettererscheinungen',
     'Wie entsteht die Erscheinung?',
     'hard', 'Wetter', 'https://de.wikipedia.org/wiki/Wetter',
     '[["Blutregen", "Saharastaub im Regenwasser", "Der Wind trägt ihn bis nach Mitteleuropa."],
       ["Elmsfeuer", "Eine Entladung an Spitzen und Masten", "Bei starker elektrischer Spannung in der Luft."],
       ["Grüner Blitz", "Ein grüner Saum beim Sonnenuntergang", "Nur Sekunden lang und selten zu sehen."],
       ["Fischregen", "Ein Wirbelsturm über Wasser", "Er saugt Tiere auf und lässt sie fallen."],
       ["Haareis", "Ein Pilz presst Eisfäden aus Totholz", "Es sieht aus wie weiße Watte."],
       ["Nebelbogen", "Ein Regenbogen fast ohne Farbe", "Die Tropfen sind zu klein für die Brechung."],
       ["Diamantstaub", "Eiskristalle bei klarem Himmel", "Sie funkeln in der Sonne."],
       ["Perlmuttwolken", "Wolken, die nach Sonnenuntergang leuchten", "Sie stehen sehr hoch in der Stratosphäre."],
       ["Wetterleuchten", "Ein Blitz ohne hörbaren Donner", "Das Gewitter ist zu weit entfernt."],
       ["Mammatuswolken", "Beutelförmige Ausbuchtungen nach unten", "Meist an der Unterseite eines Ambosses."]]'::jsonb,
     '[["Ein Loch in der Ozonschicht", "Es ist keine Wettererscheinung auf diesem Brett."],
       ["Nordlicht am Äquator", "So etwas gibt es nicht."]]'::jsonb),

    ('unnuetzes-wissen', 'gesteine-kurios', 'Steine mit Eigenheiten',
     'Was ist das Besondere daran?',
     'hard', 'Mineral', 'https://de.wikipedia.org/wiki/Mineral',
     '[["Bimsstein", "Schwimmt auf Wasser", "Erstarrter Lavaschaum voller Blasen."],
       ["Diamant", "Das härteste natürliche Mineral", "Nur ein Diamant ritzt einen Diamanten."],
       ["Graphit", "Dieselben Atome, aber sehr weich", "Es färbt ab und schreibt."],
       ["Bernstein", "Fossiles Harz mit Einschlüssen", "Manchmal steckt ein Insekt darin."],
       ["Obsidian", "Vulkanisches Glas ohne Kristalle", "Die Bruchkanten werden messerscharf."],
       ["Magnetit", "Zieht Eisen von selbst an", "Damit fand man früher die Nordrichtung."],
       ["Halit", "Man erkennt es am Geschmack", "Es ist schlicht Steinsalz."],
       ["Talk", "Lässt sich mit dem Fingernagel ritzen", "Der weichste Stein der Härteskala."],
       ["Uranglas", "Leuchtet unter Schwarzlicht grün", "Der Urangehalt ist sehr gering."],
       ["Fulgurit", "Vom Blitz geschmolzener Sand", "Eine Glasröhre im Boden."]]'::jsonb,
     '[["Wächst wie eine Pflanze weiter", "Kein Stein auf diesem Brett tut das."],
       ["Löst sich in Luft auf", "Auf keinen in dieser Liste trifft das zu."]]'::jsonb),

    ('unnuetzes-wissen', 'wasser-kurios', 'Wasser, unnütz betrachtet',
     'Was stimmt darüber?',
     'medium', 'Wasser', 'https://de.wikipedia.org/wiki/Wasser',
     '[["Eis", "Ist leichter als flüssiges Wasser", "Deshalb schwimmt es oben."],
       ["Regentropfen", "Fallen nicht in Tropfenform", "Sie sind eher abgeplattet rund."],
       ["Schneeflocke", "Immer sechsstrahlig aufgebaut", "Die Molekülform gibt es vor."],
       ["Meerwasser", "Enthält gelöstes Gold", "Nur viel zu wenig zum Fördern."],
       ["Wasserdampf", "Ist unsichtbar", "Was man sieht, ist bereits Nebel."],
       ["Destilliertes Wasser", "Leitet kaum Strom", "Erst die gelösten Salze machen es leitfähig."],
       ["Grundwasser", "Kann Jahrtausende alt sein", "Es sickert außerordentlich langsam."],
       ["Heißes Wasser", "Gefriert unter Umständen schneller", "Der Effekt ist umstritten und heißt Mpemba."],
       ["Totes Meer", "So salzig, dass man an der Oberfläche treibt", "Fast dreißig Prozent Salzgehalt."],
       ["Der Mensch", "Übersteht Wochen ohne Essen, aber nur Tage ohne Wasser", "Der Körper verliert ständig Flüssigkeit."]]'::jsonb,
     '[["Kocht überall bei genau hundert Grad", "In den Bergen kocht es früher."],
       ["Ist bei jeder Temperatur flüssig", "Auf nichts auf diesem Brett trifft das zu."]]'::jsonb),

    ('unnuetzes-wissen', 'hoehen-und-tiefen', 'Höhen & Tiefen der Erde',
     'Wofür hält dieser Ort den Rekord?',
     'hard', 'Geographie', 'https://de.wikipedia.org/wiki/Geographie',
     '[["Mount Everest", "Der höchste Punkt über dem Meeresspiegel", "8.849 Meter."],
       ["Mauna Kea", "Vom Fuß aus gemessen der höchste Berg", "Der größte Teil liegt unter Wasser."],
       ["Chimborazo", "Der Gipfel am weitesten vom Erdmittelpunkt", "Die Erde ist am Äquator dicker."],
       ["Marianengraben", "Die tiefste Stelle der Ozeane", "Fast elf Kilometer."],
       ["Totes Meer", "Der tiefste Punkt an Land", "Über 400 Meter unter dem Meeresspiegel."],
       ["Kola-Bohrung", "Das tiefste von Menschen gegrabene Loch", "Über zwölf Kilometer."],
       ["Bentley-Subglazialgraben", "Der tiefste Punkt unter Eis", "In der Antarktis."],
       ["Salto Ángel", "Der höchste freie Wasserfall", "Fast tausend Meter."],
       ["Burj Khalifa", "Das höchste Bauwerk der Welt", "Über 800 Meter."],
       ["Challenger-Tief", "Die tiefste je erreichte Stelle", "Erstmals 1960 besucht."]]'::jsonb,
     '[["Der größte See der Erde", "Danach fragt kein Rekord auf diesem Brett."],
       ["Der längste Tunnel der Welt", "Er steht nicht in dieser Liste."]]'::jsonb),

    ('unnuetzes-wissen', 'wolken-arten', 'Wolken & ihre Namen',
     'Welche Wolke ist beschrieben?',
     'medium', 'Wolke', 'https://de.wikipedia.org/wiki/Wolke',
     '[["Federartig und in großer Höhe", "Cirrus", "Sie besteht ganz aus Eiskristallen."],
       ["Haufenwolke mit flachem Boden", "Cumulus", "Die Schönwetterwolke."],
       ["Gleichmäßige graue Decke", "Stratus", "Hochnebel, der den Himmel schließt."],
       ["Türmt sich zum Amboss auf", "Cumulonimbus", "Die Gewitterwolke."],
       ["Bringt anhaltenden Landregen", "Nimbostratus", "Stundenlang und ohne Lücke."],
       ["Schäfchen in mittlerer Höhe", "Altocumulus", "In regelmäßigen Bänken geordnet."],
       ["Linsenförmig über einem Berg", "Lenticularis", "Sie steht still, während der Wind zieht."],
       ["Beutel an der Unterseite", "Mammatus", "Oft nach einem schweren Gewitter."],
       ["Leuchtet nachts in großer Höhe", "Leuchtende Nachtwolke", "Sie steht bis zu 85 Kilometer hoch."],
       ["Von einem Flugzeug gezogen", "Kondensstreifen", "Abgase und Feuchtigkeit gefrieren."]]'::jsonb,
     '[["Nebelbank am Boden", "Nebel ist keine der Wolken auf diesem Brett."],
       ["Rauchwolke über einem Feuer", "Sie steht nicht in dieser Liste."]]'::jsonb),

    ('unnuetzes-wissen', 'insekten-kurios', 'Insekten',
     'Was kann das Insekt?',
     'medium', 'Insekten', 'https://de.wikipedia.org/wiki/Insekten',
     '[["Libelle", "In alle Richtungen fliegen, auch rückwärts", "Beide Flügelpaare arbeiten getrennt."],
       ["Ameise", "Ein Vielfaches des eigenen Gewichts tragen", "Kleine Körper sind im Verhältnis stärker."],
       ["Floh", "Das Hundertfache der eigenen Länge springen", "Ein Sprungfederprotein macht es möglich."],
       ["Marienkäfer", "Die Punkte verraten nicht das Alter", "Sie zeigen die Art an."],
       ["Grille", "Schneller zirpen, je wärmer es ist", "Aus der Zahl lässt sich die Temperatur schätzen."],
       ["Stubenfliege", "Mit den Füßen schmecken", "Sie prüft die Landefläche sofort."],
       ["Honigbiene", "Den Weg zur Tracht vortanzen", "Der Schwänzeltanz nennt Richtung und Entfernung."],
       ["Periodische Zikade", "Nach genau 17 Jahren erscheinen", "Alle zugleich, in Millionenzahl."],
       ["Mistkäfer", "Sich an der Milchstraße orientieren", "Er rollt seine Kugel geradeaus."],
       ["Schmetterling", "Den Körper vollständig umbauen", "In der Puppe wird fast alles neu."]]'::jsonb,
     '[["Unter Wasser atmen wie ein Fisch", "Kein Insekt auf diesem Brett kann das."],
       ["Ein Netz aus Seide spannen", "Das tun Spinnen, und die sind keine Insekten."]]'::jsonb),

    ('unnuetzes-wissen', 'vogel-kurios', 'Vögel',
     'Was zeichnet den Vogel aus?',
     'medium', 'Vögel', 'https://de.wikipedia.org/wiki/V%C3%B6gel',
     '[["Strauß", "Der größte Vogel und flugunfähig", "Dafür läuft er sehr schnell."],
       ["Bienenelfe", "Der kleinste Vogel der Welt", "Sie wiegt weniger als zwei Gramm."],
       ["Wanderfalke", "Das schnellste Tier im Sturzflug", "Über 300 Stundenkilometer."],
       ["Kuckuck", "Legt seine Eier in fremde Nester", "Das Junge wirft die anderen hinaus."],
       ["Pinguin", "Fliegt unter Wasser statt in der Luft", "Die Flügel sind zu Rudern geworden."],
       ["Küstenseeschwalbe", "Zieht jedes Jahr von Pol zu Pol", "Die längste Wanderung im Tierreich."],
       ["Laubenvogel", "Baut und schmückt eine Laube", "Er sortiert die Fundstücke nach Farbe."],
       ["Specht", "Der Schädel dämpft die eigenen Schläge", "Bis zu zwanzig Mal je Sekunde."],
       ["Waldkauz", "Dreht den Kopf sehr weit herum", "Die Augen selbst sind unbeweglich."],
       ["Albatros", "Gleitet stundenlang ohne Flügelschlag", "Er nutzt den Wind über den Wellen."]]'::jsonb,
     '[["Baut sein Nest unter Wasser", "Kein Vogel auf diesem Brett tut das."],
       ["Hat Zähne im Schnabel", "Heutige Vögel haben keine."]]'::jsonb),

    ('unnuetzes-wissen', 'meerestiere-kurios', 'Im Meer',
     'Was ist das Besondere an dem Tier?',
     'hard', 'Meerestier', 'https://de.wikipedia.org/wiki/Meer',
     '[["Qualle", "Besteht fast nur aus Wasser", "Über 95 Prozent."],
       ["Turritopsis", "Kann in ein früheres Lebensstadium zurück", "Sie gilt als biologisch unsterblich."],
       ["Tiefsee-Anglerfisch", "Lockt Beute mit einem Leuchtorgan", "Leuchtbakterien erzeugen das Licht."],
       ["Clownfisch", "Lebt unbeschadet in der Seeanemone", "Eine Schleimschicht schützt ihn."],
       ["Schwertfisch", "Wärmt seine Augen aktiv auf", "So sieht er in kaltem Wasser schärfer."],
       ["Papageifisch", "Schläft in einer selbstgemachten Schleimhülle", "Sie hält Parasiten ab."],
       ["Riesenmuschel", "Wird über hundert Jahre alt", "Und mehrere Zentner schwer."],
       ["Krake", "Ändert die Farbe, obwohl farbenblind", "Wie sie es steuert, ist nicht ganz geklärt."],
       ["Zitteraal", "Erzeugt Stromstöße von mehreren hundert Volt", "Er ist gar kein echter Aal."],
       ["Segelfisch", "Der schnellste Fisch im Meer", "Über hundert Stundenkilometer."]]'::jsonb,
     '[["Atmet Luft an der Oberfläche", "Wale tun das, und die fehlen auf diesem Brett."],
       ["Lebt ausschließlich im Süßwasser", "Kein Tier in dieser Liste tut das."]]'::jsonb),

    ('unnuetzes-wissen', 'haustiere-kurios', 'Haustiere',
     'Was stimmt über das Tier?',
     'easy', 'Haustier', 'https://de.wikipedia.org/wiki/Haustier',
     '[["Katze", "Schnurrt nicht nur, wenn es ihr gut geht", "Auch bei Schmerz und Angst."],
       ["Hund", "Erkennt Menschen sicher am Geruch", "Selbst nach Jahren."],
       ["Meerschweinchen", "Braucht Vitamin C aus dem Futter", "Es kann es nicht selbst bilden."],
       ["Kaninchen", "Die Zähne wachsen ein Leben lang", "Sie müssen abgenutzt werden."],
       ["Wellensittich", "Kann einzelne Wörter nachsprechen", "Manche lernen Hunderte."],
       ["Goldhamster", "Fast alle stammen von einem Wurf ab", "1930 in Syrien gefunden."],
       ["Goldfisch", "Merkt sich weit mehr als drei Sekunden", "Im Versuch über Monate."],
       ["Landschildkröte", "Kann Jahrzehnte alt werden", "Oft älter als ihr Halter."],
       ["Pferd", "Kann sich nicht übergeben", "Der Magenmuskel lässt es nicht zu."],
       ["Frettchen", "Verschläft den größten Teil des Tages", "Bis zu achtzehn Stunden."]]'::jsonb,
     '[["Sieht nur schwarz und weiß", "Auf kein Tier auf diesem Brett trifft das zu."],
       ["Muss überhaupt nicht trinken", "Keines in dieser Liste kommt ohne Wasser aus."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

fakes as (
    select q.id                                         as quiz_id,
           k.value ->> 0                                as label,
           k.value ->> 1                                as explanation,
           (jsonb_array_length(sp.pairs) + k.ord)::int  as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.fakes) with ordinality k(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
),

paired as (
    insert into items (quiz_id, category_id, label, position, explanation)
    select f.quiz_id, c.id, f.answer, f.position, f.explanation
      from flat f
      join new_categories c
        on c.quiz_id = f.quiz_id
       and c.label = f.label
    returning id
)

insert into items (quiz_id, category_id, label, position, explanation)
select k.quiz_id, null, k.label, k.position, k.explanation
  from fakes k;
