-- Unnützes Wissen, zweite Datei: Sprache und Wörter.
--
-- Zwanzig Bretter über das, was man täglich sagt, ohne es zu wissen: woher
-- Redewendungen kommen, was Abkürzungen auflösen, welche deutschen Wörter
-- andere Sprachen übernommen haben.
--
-- Vorher anwenden: supabase/questions/subject-unnuetzes-wissen.sql.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs, fakes) as (
    values

    ('unnuetzes-wissen', 'redewendungen-herkunft', 'Redewendungen & ihre Herkunft',
     'Woher kommt die Redewendung?',
     'hard', 'Redewendung', 'https://de.wikipedia.org/wiki/Redewendung',
     '[["Etwas auf die lange Bank schieben", "Eine Truhe im Gerichtssaal", "Akten kamen hinein und lange nicht heraus."],
       ["Ins Fettnäpfchen treten", "Ein Napf mit Stiefelfett an der Tür", "Wer ihn umstieß, blamierte sich vor allen."],
       ["Jemandem einen Bären aufbinden", "Eine schwere Last, die keiner bemerkt", "Bär stand früher für eine drückende Schuld."],
       ["Auf den Hund kommen", "Der Boden der Geldtruhe", "War alles Geld weg, sah man den aufgemalten Hund."],
       ["Alles in Butter", "Zerbrechliches wurde in Butter verschickt", "In der erstarrten Masse überstand Glas den Transport."],
       ["Blau machen", "Der Wartetag der Färber", "Der Stoff wurde an der Luft erst blau."],
       ["Über die Wupper gehen", "Auf der anderen Flussseite lag das Gefängnis", "In Wuppertal stand es jenseits des Wassers."],
       ["Null acht fünfzehn", "Ein Maschinengewehr des Ersten Weltkriegs", "Es war überall gleich und darum gewöhnlich."],
       ["Hals- und Beinbruch", "Ein verballhorntes jiddisches Segenswort", "Hazloche und broche heißt Glück und Segen."],
       ["Tacheles reden", "Das jiddische Wort für Zweck", "Gemeint ist: zur Sache kommen."],
       ["Da liegt der Hund begraben", "Vermutlich ein Wort für Beute", "Mit dem Tier hat es wohl nichts zu tun."]]'::jsonb,
     '[["Aus einem lateinischen Rechtssatz", "Keine Wendung auf diesem Brett kommt daher."],
       ["Aus einem Werbespruch der 1950er Jahre", "Keine in dieser Liste geht darauf zurück."]]'::jsonb),

    ('unnuetzes-wissen', 'falsche-freunde', 'Falsche Freunde',
     'Was heißt das englische Wort wirklich?',
     'medium', 'Falscher Freund', 'https://de.wikipedia.org/wiki/Falscher_Freund',
     '[["gift", "Geschenk", "Das deutsche Gift heißt poison."],
       ["become", "werden", "Bekommen heißt to get."],
       ["eventually", "schließlich", "Eventuell heißt possibly."],
       ["actually", "tatsächlich", "Aktuell heißt current."],
       ["brave", "tapfer", "Brav heißt well-behaved."],
       ["chef", "Küchenchef", "Der Chef heißt boss."],
       ["handy", "praktisch", "Das Handy heißt mobile phone."],
       ["rent", "mieten", "Rente heißt pension."],
       ["sensible", "vernünftig", "Sensibel heißt sensitive."],
       ["billion", "Milliarde", "Die deutsche Billion heißt trillion."],
       ["mist", "Nebel", "Der deutsche Mist heißt manure."],
       ["blame", "beschuldigen", "Blamieren heißt to embarrass."]]'::jsonb,
     '[["Sofort", "Kein Wort auf diesem Brett bedeutet das."],
       ["Kostenlos", "Auf keines in dieser Liste trifft das zu."]]'::jsonb),

    ('unnuetzes-wissen', 'scheinanglizismen', 'Wörter, die nur deutsch englisch sind',
     'Wie sagt man es tatsächlich auf Englisch?',
     'medium', 'Scheinanglizismus',
     'https://de.wikipedia.org/wiki/Scheinanglizismus',
     '[["Handy", "mobile phone", "Im Englischen heißt handy nur praktisch."],
       ["Beamer", "projector", "Ein beamer ist dort ein Fahrzeug von BMW."],
       ["Oldtimer", "classic car", "Ein old-timer ist ein alter Mensch."],
       ["Public Viewing", "outdoor screening", "Im Englischen die Aufbahrung eines Toten."],
       ["Showmaster", "host", "Ein reines Kunstwort aus dem Deutschen."],
       ["Dressman", "male model", "Im Englischen völlig unbekannt."],
       ["Smoking", "dinner jacket", "In Amerika tuxedo."],
       ["Pullunder", "sleeveless sweater", "Gebildet als Gegenstück zum Pullover."],
       ["Bodybag", "messenger bag", "Ein body bag ist ein Leichensack."],
       ["Wellness", "spa", "Als Bezeichnung für Bäder unüblich."],
       ["Messie", "hoarder", "Von messy abgeleitet, aber nicht so gebraucht."]]'::jsonb,
     '[["fitness studio", "So heißt keines der Wörter auf diesem Brett."],
       ["parking lot", "Auf keines in dieser Liste trifft das zu."]]'::jsonb),

    ('unnuetzes-wissen', 'lehnwoerter-arabisch', 'Wörter aus dem Arabischen',
     'Was steckt hinter dem Wort?',
     'hard', 'Arabische Sprache', 'https://de.wikipedia.org/wiki/Arabische_Sprache',
     '[["Algebra", "Das Zusammenfügen", "Aus dem Titel eines Rechenbuchs."],
       ["Alkohol", "Ein feines Pulver", "Erst später auf den Weingeist übertragen."],
       ["Ziffer", "Die Null", "Aus sifr für leer."],
       ["Admiral", "Der Befehlshaber", "Aus amir al-bahr, Fürst des Meeres."],
       ["Magazin", "Das Lager", "Erst später auch eine Zeitschrift."],
       ["Sofa", "Die erhöhte Sitzbank", "Aus suffa."],
       ["Tarif", "Die Bekanntmachung", "Über das Italienische ins Deutsche."],
       ["Havarie", "Die Schiffsbeschädigung", "Über das Mittelmeer in den Handel."],
       ["Zucker", "Der Kies", "Über das Arabische aus dem Sanskrit."],
       ["Matratze", "Der hingeworfene Kissenplatz", "Aus matrah."],
       ["Giraffe", "Die Liebliche", "Aus zarafa."]]'::jsonb,
     '[["Der Sternenhimmel", "Auf kein Wort auf diesem Brett geht das zurück."],
       ["Das Salz der Wüste", "Kein Begriff in dieser Liste kommt daher."]]'::jsonb),

    ('unnuetzes-wissen', 'akronyme-aufgeloest', 'Abkürzungen, die niemand auflöst',
     'Wofür steht das Wort ausgeschrieben?',
     'medium', 'Akronym', 'https://de.wikipedia.org/wiki/Akronym',
     '[["Laser", "Lichtverstärkung durch angeregte Emission", "Ein englisches Akronym."],
       ["Radar", "Funkortung und Entfernungsmessung", "Ebenfalls aus dem Englischen."],
       ["Scuba", "Eigenständiges Unterwasser-Atemgerät", "Der Tauchbegriff schlechthin."],
       ["Taser", "Nach einem Jugendbuchhelden benannt", "Thomas A. Swifts elektrisches Gewehr."],
       ["Gestapo", "Geheime Staatspolizei", "Eine Silbenkurzform."],
       ["Kripo", "Kriminalpolizei", "Ebenfalls aus Silben gebildet."],
       ["Hanuta", "Haselnusstafel", "Der Markenname sagt die Zutat."],
       ["Haribo", "Hans Riegel Bonn", "Gründer und Ort in einem Wort."],
       ["Adidas", "Adi Dassler", "Spitzname und Nachname."],
       ["Modem", "Modulator und Demodulator", "Zwei Aufgaben in einem Gerät."],
       ["Bit", "Binäre Ziffer", "Aus binary digit gekürzt."]]'::jsonb,
     '[["Elektronisches Rechenwerk", "Kein Wort auf diesem Brett löst sich so auf."],
       ["Internationale Norm", "Auf keine Abkürzung in dieser Liste trifft das zu."]]'::jsonb),

    ('unnuetzes-wissen', 'satzzeichen-namen', 'Satzzeichen & Sonderzeichen',
     'Wie heißt das Zeichen?',
     'medium', 'Satzzeichen', 'https://de.wikipedia.org/wiki/Satzzeichen',
     '[["Drei Punkte am Satzende", "Auslassungspunkte", "Sie zeigen, dass etwas fehlt."],
       ["Der waagerechte Strich im Wort", "Bindestrich", "Kürzer als der Gedankenstrich."],
       ["Der längere Strich im Satz", "Gedankenstrich", "Er schiebt einen Einschub ein."],
       ["Der hochgestellte Strich beim Auslassen", "Apostroph", "Er ersetzt einen weggefallenen Buchstaben."],
       ["Der Punkt über dem kleinen j", "i-Punkt", "Auch das j trägt einen."],
       ["Das Zeichen §", "Paragrafenzeichen", "Zwei verschlungene S für signum sectionis."],
       ["Das Zeichen ~", "Tilde", "In Spanien macht sie aus n ein ñ."],
       ["Das Zeichen ^", "Zirkumflex", "Im Französischen ein Dach über dem Vokal."],
       ["Das Zeichen †", "Kreuz", "In Texten der Hinweis auf ein Sterbedatum."],
       ["Das Zeichen ¶", "Absatzmarke", "Sie zeigt den Beginn eines Absatzes."],
       ["Das Zeichen ‰", "Promillezeichen", "Ein Tausendstel statt eines Hundertstels."]]'::jsonb,
     '[["Sternchen", "Es steht für eine Fußnote, und danach fragt hier keine Zeile."],
       ["Schrägstrich", "Er trennt Alternativen und fehlt auf diesem Brett."]]'::jsonb),

    ('unnuetzes-wissen', 'sprichwoerter-welt', 'Sprichwörter aus aller Welt',
     'Aus welchem Land stammt das Sprichwort?',
     'hard', 'Sprichwort', 'https://de.wikipedia.org/wiki/Sprichwort',
     '[["Der Nagel, der herausragt, wird eingeschlagen", "Japan", "Auffallen gilt als heikel."],
       ["Ein Freund ist jemand, der dich singen hört", "Italien", "Und sich an die Melodie erinnert."],
       ["Wer keine Katze hat, füttert Mäuse", "Frankreich", "Untätigkeit hat Folgen."],
       ["Wer langsam geht, kommt weit", "China", "Beharrlichkeit schlägt Eile."],
       ["Auch ein blindes Huhn findet ein Korn", "Deutschland", "Zufall schlägt manchmal Können."],
       ["Der Elefant kümmert sich nicht um den Hund", "Indien", "Größe muss sich nicht rechtfertigen."],
       ["Wer nur einen Hammer hat, sieht überall Nägel", "USA", "Ein Werkzeug prägt den Blick."],
       ["Eile mit Weile", "Rom", "Festina lente war ein Kaiserwort."],
       ["Auch das längste Fest geht zu Ende", "Spanien", "Nichts hält ewig."],
       ["Wer Honig will, muss den Bienenstock ertragen", "Griechenland", "Ohne Mühe kein Ertrag."]]'::jsonb,
     '[["Island", "Kein Sprichwort auf diesem Brett stammt von dort."],
       ["Australien", "Auch von dort steht keines in dieser Liste."]]'::jsonb),

    ('unnuetzes-wissen', 'woerter-ohne-uebersetzung', 'Wörter ohne deutsche Entsprechung',
     'Aus welcher Sprache stammt das Wort?',
     'hard', 'Unübersetzbarkeit', 'https://de.wikipedia.org/wiki/Unübersetzbarkeit',
     '[["Hygge für gemütliche Geborgenheit", "Dänisch", "Ein halbes Lebensgefühl in fünf Buchstaben."],
       ["Saudade für sehnsuchtsvolle Wehmut", "Portugiesisch", "Die Sehnsucht nach etwas Verlorenem."],
       ["Sisu für zähe Entschlossenheit", "Finnisch", "Durchhalten, wenn nichts mehr geht."],
       ["Ubuntu für Menschlichkeit durch andere", "Zulu", "Ich bin, weil wir sind."],
       ["Komorebi für Licht durch Blätter", "Japanisch", "Das Sonnenlicht im Blattwerk."],
       ["Mamihlapinatapai für einen wortlosen Blick", "Yámana", "Beide hoffen, der andere fange an."],
       ["Gigil für den Drang, Süßes zu drücken", "Filipino", "Das Zwicken vor Zuneigung."],
       ["Iktsuarpok für das Hinausgehen vor Erwartung", "Inuktitut", "Man schaut, ob der Gast schon kommt."],
       ["Potschemutschka für jemanden, der ständig fragt", "Russisch", "Von potschemu, dem Wort für warum."],
       ["Jayus für einen so schlechten Witz, dass man lacht", "Indonesisch", "Er scheitert sich zum Erfolg."]]'::jsonb,
     '[["Isländisch", "Kein Wort auf diesem Brett stammt von dort."],
       ["Latein", "Auch aus dem Lateinischen steht keines in dieser Liste."]]'::jsonb),

    ('unnuetzes-wissen', 'markennamen-gattung', 'Marken, die Gattungsnamen wurden',
     'Wofür steht der Markenname heute?',
     'medium', 'Gattungsname', 'https://de.wikipedia.org/wiki/Gattungsname',
     '[["Tempo", "Papiertaschentuch", "Seit 1929 auf dem Markt."],
       ["Zewa", "Küchenrolle", "Der Name steckt in der Zellstofffabrik."],
       ["Tesa", "Klebeband", "Aus dem Namen einer Sekretärin."],
       ["Föhn", "Haartrockner", "Nach dem warmen Alpenwind benannt."],
       ["Flex", "Winkelschleifer", "Nach dem Hersteller der ersten Geräte."],
       ["Jeep", "Geländewagen", "Aus dem Militärfahrzeug hervorgegangen."],
       ["Labello", "Lippenpflegestift", "Lateinisch für schöne Lippe."],
       ["Uhu", "Alleskleber", "Nach dem Vogel benannt."],
       ["Nutella", "Nuss-Nougat-Creme", "Nut und die italienische Endung."],
       ["Edding", "Permanentmarker", "Nach dem Firmengründer."],
       ["Aspirin", "Schmerztablette mit Acetylsalicylsäure", "Der Name enthält die Spierstaude."]]'::jsonb,
     '[["Kühlschrank", "Er war nie ein Markenname und fehlt auf diesem Brett."],
       ["Staubsauger", "Auch er ist keine Marke in dieser Liste."]]'::jsonb),

    ('unnuetzes-wissen', 'woerter-bedeutungswandel', 'Wörter, die die Seite wechselten',
     'Was bedeutete das Wort früher?',
     'hard', 'Bedeutungswandel', 'https://de.wikipedia.org/wiki/Bedeutungswandel',
     '[["Geil", "Üppig und fruchtbar", "So sprach man von Pflanzen."],
       ["Elend", "In der Fremde lebend", "Aus eli-lenti, außer Landes."],
       ["Frech", "Mutig und tapfer", "Ein Lob, kein Vorwurf."],
       ["Albern", "Ganz und einfältig zugleich", "Aus alawari, völlig wahr."],
       ["Weib", "Die Frau ohne jede Wertung", "Erst später abwertend gebraucht."],
       ["Dirne", "Das junge Mädchen", "Ohne jeden Nebensinn."],
       ["Arbeit", "Mühsal und Not", "Verwandt mit dem slawischen Wort für Sklave."],
       ["Bube", "Der Knabe", "Im Kartenspiel blieb die alte Bedeutung."],
       ["Selig", "Glücklich im Diesseits", "Erst später jenseitig gemeint."],
       ["Klug", "Fein und zierlich", "Erst danach verständig."],
       ["Toll", "Verrückt und wahnsinnig", "In Tollwut ist es geblieben."]]'::jsonb,
     '[["Heilig und unantastbar", "Kein Wort auf diesem Brett bedeutete das."],
       ["Teuer im Sinne von kostspielig", "Auf keines in dieser Liste trifft das zu."]]'::jsonb),

    ('unnuetzes-wissen', 'tierlaute-sprachen', 'Tierlaute in anderen Sprachen',
     'Wie klingt der Hahn in dieser Sprache?',
     'easy', 'Onomatopoesie', 'https://de.wikipedia.org/wiki/Onomatopoesie',
     '[["Kikeriki", "Deutsch", "Der Hahn am Morgen."],
       ["Cock-a-doodle-doo", "Englisch", "Deutlich länger als bei uns."],
       ["Cocorico", "Französisch", "Fast schon ein Nationalsymbol."],
       ["Chicchirichì", "Italienisch", "Mit vielen i hintereinander."],
       ["Quiquiriquí", "Spanisch", "Ähnlich, aber mit q geschrieben."],
       ["Kokekokko", "Japanisch", "Ganz ohne r."],
       ["Kukeleku", "Niederländisch", "Kurz und rund."],
       ["Kykyliky", "Norwegisch", "Mit y statt i."],
       ["Kukuriku", "Polnisch", "In vielen slawischen Sprachen ähnlich."],
       ["Ü-ü-ürü-üü", "Türkisch", "Mit dem ü am Anfang."]]'::jsonb,
     '[["Wau wau", "So bellt der Hund, und danach fragt hier keine Zeile."],
       ["Muh", "Das ist die Kuh und steht nicht auf diesem Brett."]]'::jsonb),

    ('unnuetzes-wissen', 'woerter-aus-namen', 'Wörter, die aus Namen wurden',
     'Nach wem oder was ist das Wort benannt?',
     'hard', 'Eponym', 'https://de.wikipedia.org/wiki/Eponym',
     '[["Boykott", "Ein irischer Gutsverwalter", "Charles Boycott wurde geschnitten."],
       ["Silhouette", "Ein französischer Finanzminister", "Étienne de Silhouette sparte an allem."],
       ["Sandwich", "Ein englischer Earl", "Er wollte beim Spiel nicht aufstehen."],
       ["Guillotine", "Ein französischer Arzt", "Er schlug das Gerät nur vor."],
       ["Nikotin", "Ein französischer Gesandter", "Jean Nicot brachte den Tabak nach Paris."],
       ["Diesel", "Ein deutscher Ingenieur", "Rudolf Diesel erfand den Motor."],
       ["Zeppelin", "Ein deutscher Graf", "Ferdinand von Zeppelin baute die Luftschiffe."],
       ["Ohm", "Ein deutscher Physiker", "Georg Simon Ohm fand das Gesetz."],
       ["Praline", "Ein französischer Marschall", "Sein Koch kandierte die Mandeln."],
       ["Jeans", "Die Stadt Genua", "Über das französische Gênes."],
       ["Denim", "Die Stadt Nîmes", "Aus de Nîmes wurde denim."]]'::jsonb,
     '[["Ein griechischer Gott", "Kein Wort auf diesem Brett geht darauf zurück."],
       ["Ein Fluss in Afrika", "Keines in dieser Liste kommt daher."]]'::jsonb),

    ('unnuetzes-wissen', 'latein-im-alltag', 'Latein, das jeder benutzt',
     'Was heißt die Wendung wörtlich?',
     'medium', 'Lateinische Phrase', 'https://de.wikipedia.org/wiki/Liste_lateinischer_Phrasen',
     '[["Et cetera", "Und die übrigen Dinge", "Deshalb usw. auf Deutsch."],
       ["Alibi", "Anderswo", "Der Beschuldigte war woanders."],
       ["Agenda", "Was zu tun ist", "Wörtlich das zu Handelnde."],
       ["Album", "Das Weiße", "Ursprünglich eine leere Tafel."],
       ["Bonus", "Das Gute", "Erst später der Zuschlag."],
       ["Curriculum Vitae", "Der Lauf des Lebens", "Deshalb Lebenslauf."],
       ["Deficit", "Es fehlt", "Eine ganze Verbform als Substantiv."],
       ["Exemplar", "Das Muster", "Erst danach das einzelne Stück."],
       ["Video", "Ich sehe", "Ebenfalls eine Verbform."],
       ["Audio", "Ich höre", "Das Gegenstück dazu."],
       ["Placebo", "Ich werde gefallen", "Aus einem Totengebet übernommen."]]'::jsonb,
     '[["Ich weiß es nicht", "Keine Wendung auf diesem Brett heißt das."],
       ["Auf ewig", "Auf keine in dieser Liste trifft das zu."]]'::jsonb),

    ('unnuetzes-wissen', 'buchstaben-kurios', 'Buchstaben & ihre Eigenheiten',
     'Was gilt für den Buchstaben?',
     'medium', 'Alphabet', 'https://de.wikipedia.org/wiki/Alphabet',
     '[["Das ß", "Gibt es nur im Deutschen", "Die Schweiz schreibt stattdessen ss."],
       ["Das W", "Entstand aus zwei V", "Der Name sagt es noch."],
       ["Das J", "Löste sich spät vom I", "Erst in der Neuzeit ein eigener Buchstabe."],
       ["Das Q", "Steht fast immer vor einem U", "Ausnahmen sind Fremdwörter."],
       ["Das X", "Kommt im Deutschen selten vor", "Meist in entlehnten Wörtern."],
       ["Das Y", "Hieß griechisches I", "Daher der französische Name i grec."],
       ["Das C", "Steht im Deutschen kaum allein", "Fast immer in ch oder ck."],
       ["Das E", "Der häufigste Buchstabe", "In fast jedem zweiten Wort mehrfach."],
       ["Das Ä", "Entstand aus einem kleinen e", "Es stand früher über dem a."],
       ["Das Z", "Stand im Griechischen an sechster Stelle", "Im Lateinischen rutschte es ans Ende."]]'::jsonb,
     '[["Wird nur in Großbuchstaben geschrieben", "Auf keinen Buchstaben auf diesem Brett trifft das zu."],
       ["Kommt in keinem deutschen Wort vor", "Keiner in dieser Liste fehlt ganz."]]'::jsonb),

    ('unnuetzes-wissen', 'vornamen-bedeutung', 'Vornamen & ihre Bedeutung',
     'Was bedeutet der Name ursprünglich?',
     'medium', 'Vorname', 'https://de.wikipedia.org/wiki/Vorname',
     '[["Andreas", "Der Männliche", "Aus dem Griechischen."],
       ["Barbara", "Die Fremde", "Aus dem Wort für nicht-griechisch."],
       ["Philipp", "Der Pferdefreund", "Aus philos und hippos."],
       ["Nikolaus", "Der Sieg des Volkes", "Aus nike und laos."],
       ["Klara", "Die Helle", "Aus dem lateinischen clarus."],
       ["Viktor", "Der Sieger", "Ebenfalls aus dem Lateinischen."],
       ["Ludwig", "Der berühmte Kämpfer", "Aus dem Althochdeutschen."],
       ["Wilhelm", "Der entschlossene Beschützer", "Wille und Helm."],
       ["Sophie", "Die Weisheit", "Aus dem Griechischen sophia."],
       ["Miriam", "Die Widerspenstige", "Umstritten, aber häufig so gedeutet."],
       ["Bernhard", "Der starke Bär", "Bär und hart."]]'::jsonb,
     '[["Der Sohn des Donners", "Kein Name auf diesem Brett bedeutet das."],
       ["Die am Fluss Geborene", "Auf keinen in dieser Liste trifft das zu."]]'::jsonb),

    ('unnuetzes-wissen', 'schriften-kurios', 'Schriften & ihre Eigenheiten',
     'Was zeichnet die Schrift aus?',
     'hard', 'Schrift', 'https://de.wikipedia.org/wiki/Schrift',
     '[["Arabisch", "Wird von rechts nach links geschrieben", "Zahlen aber von links nach rechts."],
       ["Chinesisch", "Ein Zeichen steht für ein Wort", "Es sind Zehntausende."],
       ["Koreanisch", "Wurde bewusst am Reißbrett entworfen", "1443 von König Sejong veranlasst."],
       ["Japanisch", "Nutzt drei Schriftsysteme nebeneinander", "Kanji, Hiragana und Katakana."],
       ["Thai", "Kennt keine Wortzwischenräume", "Gelesen wird ohne Lücken."],
       ["Hebräisch", "Schreibt die Vokale meist nicht mit", "Sie werden mitgedacht."],
       ["Georgisch", "Kennt keine Groß- und Kleinschreibung", "Alle Buchstaben sind gleich hoch."],
       ["Ogham", "Wurde an Steinkanten entlang geritzt", "Eine irische Kerbschrift."],
       ["Blindenschrift", "Besteht aus sechs erhabenen Punkten", "Nach Louis Braille benannt."],
       ["Ägyptische Hieroglyphen", "Konnten in mehrere Richtungen laufen", "Die Figuren blicken zum Zeilenanfang."]]'::jsonb,
     '[["Wird ausschließlich senkrecht geschrieben", "Auf keine Schrift auf diesem Brett trifft das zwingend zu."],
       ["Hat genau 26 Zeichen", "Keine in dieser Liste ist so beschrieben."]]'::jsonb),

    ('unnuetzes-wissen', 'zahlwoerter-herkunft', 'Zahlen im Wort',
     'Welche Zahl steckt darin?',
     'hard', 'Zahlwort', 'https://de.wikipedia.org/wiki/Numerale',
     '[["Dezember", "Zehn", "Im alten römischen Kalender der zehnte Monat."],
       ["Oktober", "Acht", "Damals der achte Monat."],
       ["September", "Sieben", "Der siebte Monat des alten Kalenders."],
       ["November", "Neun", "Entsprechend der neunte."],
       ["Duett", "Zwei", "Zwei Singende oder Spielende."],
       ["Quarantäne", "Vierzig", "So viele Tage lagen Schiffe vor Anker."],
       ["Dutzend", "Zwölf", "Aus dem französischen douzaine."],
       ["Trilogie", "Drei", "Drei zusammengehörige Werke."],
       ["Pentagon", "Fünf", "Ein Fünfeck."],
       ["Zentner", "Hundert", "Ursprünglich hundert Pfund."],
       ["Sextett", "Sechs", "Sechs Musizierende."],
       ["Millennium", "Tausend", "Tausend Jahre."]]'::jsonb,
     '[["Elf", "Keine Zahl auf diesem Brett steckt in einem dieser Wörter."],
       ["Eine Million", "Auch die kommt in dieser Liste nicht vor."]]'::jsonb),

    ('unnuetzes-wissen', 'fachwoerter-alltag', 'Fachwörter für Alltägliches',
     'Was beschreibt der Fachbegriff?',
     'hard', 'Terminologie', 'https://de.wikipedia.org/wiki/Terminologie',
     '[["Petrichor", "Der Geruch nach dem ersten Regen", "Aus Stein und Götterblut zusammengesetzt."],
       ["Sonnenniesreflex", "Das Niesen beim Blick ins Licht", "Etwa jeder Vierte kennt es."],
       ["Borborygmus", "Das Knurren des Magens", "Ein lautmalerischer Fachbegriff."],
       ["Singultus", "Der Schluckauf", "Ein Krampf des Zwerchfells."],
       ["Phosphene", "Die Muster beim Augenreiben", "Licht ohne Lichtquelle."],
       ["Ohrwurm", "Die Melodie, die nicht weggeht", "Fachlich eine unwillkürliche Bildwiederholung."],
       ["Déjà-vu", "Das Gefühl, das schon erlebt zu haben", "Französisch für schon gesehen."],
       ["Aglet", "Die Hülse am Schnürsenkelende", "Im Deutschen Nestelspitze."],
       ["Kraspedon", "Der Saum eines Gewandes", "Ein Begriff aus der Antike."],
       ["Interrobang", "Frage- und Ausrufezeichen in einem", "1962 vorgeschlagen, nie durchgesetzt."]]'::jsonb,
     '[["Das Kribbeln vor Aufregung", "Kein Begriff auf diesem Brett meint das."],
       ["Der Nachhall in einem leeren Raum", "Dafür steht keines in dieser Liste."]]'::jsonb),

    ('unnuetzes-wissen', 'ortsnamen-kurios', 'Ortsnamen, die stutzen lassen',
     'In welchem Land liegt der Ort?',
     'hard', 'Ortsname', 'https://de.wikipedia.org/wiki/Ortsname',
     '[["Fucking, seit 2021 Fugging", "Österreich", "Der Ort ließ sich aus Not umbenennen."],
       ["Hell", "Norwegen", "Der Bahnhof ist ein beliebtes Fotomotiv."],
       ["Batman", "Türkei", "Eine Provinzhauptstadt am gleichnamigen Fluss."],
       ["Dull", "Schottland", "Es unterhält eine Partnerschaft mit Boring in Oregon."],
       ["Bitche", "Frankreich", "Die Stadt in Lothringen hatte Ärger mit sozialen Netzwerken."],
       ["Silly", "Belgien", "Eine Gemeinde in der Wallonie."],
       ["Kissing", "Deutschland", "Eine Gemeinde in Bayern."],
       ["Ai", "Japan", "Ein sehr kurzer Ortsname."],
       ["Å", "Schweden", "Ein Ortsname aus einem Buchstaben."],
       ["Zzyzx", "USA", "Der Name wurde 1944 frei erfunden, um ganz hinten im Register zu stehen."]]'::jsonb,
     '[["Neuseeland", "Kein Ort auf diesem Brett liegt dort."],
       ["Island", "Auch dort liegt keiner aus dieser Liste."]]'::jsonb),

    ('unnuetzes-wissen', 'dialekt-hochdeutsch', 'Dialekt & Hochdeutsch',
     'Was heißt das Wort auf Hochdeutsch?',
     'medium', 'Deutsche Dialekte', 'https://de.wikipedia.org/wiki/Deutsche_Dialekte',
     '[["Fisimatenten", "Ausflüchte", "Die Herleitung aus dem Französischen ist umstritten."],
       ["Schnodderig", "Vorlaut", "Vor allem im Norden gebräuchlich."],
       ["Kabuff", "Abstellkammer", "Ein enger, dunkler Raum."],
       ["Gedöns", "Umstand", "Viel Aufhebens um wenig."],
       ["Pfnüsel", "Schnupfen", "Aus der Schweiz."],
       ["Hutzelig", "Verschrumpelt", "Von hutzeln, dörren."],
       ["Bammel", "Angst", "Aus dem Rotwelschen."],
       ["Grantig", "Schlecht gelaunt", "In Bayern und Österreich zu Hause."],
       ["Fisselig", "Nervös und fahrig", "Norddeutsch für zappelig."],
       ["Marode", "Erschöpft", "Aus dem Französischen entlehnt."],
       ["Schmarrn", "Unsinn", "Eigentlich eine Mehlspeise."]]'::jsonb,
     '[["Sehr schnell", "Kein Wort auf diesem Brett heißt das."],
       ["Kostenlos", "Auf keines in dieser Liste trifft das zu."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

fakes as (
    select q.id                                         as quiz_id,
           k.value ->> 0                                as label,
           k.value ->> 1                                as explanation,
           (jsonb_array_length(sp.pairs) + k.ord)::int  as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.fakes) with ordinality k(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
),

paired as (
    insert into items (quiz_id, category_id, label, position, explanation)
    select f.quiz_id, c.id, f.answer, f.position, f.explanation
      from flat f
      join new_categories c
        on c.quiz_id = f.quiz_id
       and c.label = f.label
    returning id
)

insert into items (quiz_id, category_id, label, position, explanation)
select k.quiz_id, null, k.label, k.position, k.explanation
  from fakes k;
