-- Unnützes Wissen, fünfte Datei: Geschichte und Gesellschaft.
--
-- Zwanzig Bretter über das, was Menschen einander angetan, verkauft, verboten
-- und angezogen haben. Wo eine Anekdote nur überliefert und nicht belegt ist,
-- sagt die Antwort das ausdrücklich -- siehe `herrscher-eigenheiten`.
--
-- Vorher anwenden: supabase/questions/subject-unnuetzes-wissen.sql.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs, fakes) as (
    values

    ('unnuetzes-wissen', 'berufe-verschwunden', 'Berufe, die es nicht mehr gibt',
     'Was tat diese Person?',
     'hard', 'Historischer Beruf',
     'https://de.wikipedia.org/wiki/Liste_historischer_Berufe',
     '[["Laternenanzünder", "Zündete abends die Gaslaternen an", "Und löschte sie morgens wieder."],
       ["Weckrufer", "Klopfte Arbeiter an den Fenstern wach", "Mit einer langen Stange."],
       ["Kegeljunge", "Stellte die Kegel wieder auf", "Am Ende der Bahn, von Hand."],
       ["Eisschneider", "Sägte Blöcke aus zugefrorenen Seen", "Für die Kühlung im Sommer."],
       ["Rechner", "Rechnete lange Zahlenreihen von Hand", "Ganze Säle voller Menschen."],
       ["Telefonistin", "Steckte Gespräche von Hand zusammen", "Ohne sie kam keine Verbindung."],
       ["Schriftsetzer", "Setzte Bleilettern für den Druck", "Spiegelverkehrt und von Hand."],
       ["Nachtwächter", "Rief die Stunden durch die Gassen", "Und achtete auf Feuer."],
       ["Rattenfänger", "Bekämpfte Ratten in den Städten", "Bezahlt nach Stückzahl."],
       ["Milchmann", "Brachte die Milch bis an die Tür", "In Kannen und später in Flaschen."]]'::jsonb,
     '[["Bediente die ersten Computer", "Der Beruf verschwand nicht, er wandelte sich."],
       ["Malte Verkehrsschilder von Hand", "Er steht nicht auf diesem Brett."]]'::jsonb),

    ('unnuetzes-wissen', 'kriege-kuriose-anlaesse', 'Kriege mit seltsamen Anlässen',
     'Was war der Anlass?',
     'hard', 'Kriegsursache', 'https://de.wikipedia.org/wiki/Krieg',
     '[["Krieg um den Eimer", "Ein gestohlener Holzeimer", "Modena und Bologna, 1325."],
       ["Krieg um Jenkins Ohr", "Ein abgeschnittenes Ohr", "Ein Kapitän zeigte es dem Parlament, 1739."],
       ["Pastetenkrieg", "Eine geplünderte Konditorei", "Frankreich gegen Mexiko, 1838."],
       ["Schweinekrieg", "Ein erschossenes Schwein", "USA und Großbritannien, 1859."],
       ["Emu-Krieg", "Eine Plage von Laufvögeln", "Australien setzte 1932 Soldaten ein."],
       ["Fußballkrieg", "Ausschreitungen bei Qualifikationsspielen", "El Salvador und Honduras, 1969."],
       ["Kabeljaukriege", "Streit um Fischgründe", "Island gegen Großbritannien."],
       ["Opiumkriege", "Der erzwungene Opiumhandel", "Großbritannien gegen China."],
       ["Whisky-Rebellion", "Eine Steuer auf gebrannten Schnaps", "In den jungen USA, 1791."],
       ["Krieg um den Goldenen Stuhl", "Ein beanspruchter Thron", "Britische Truppen gegen die Aschanti, 1900."]]'::jsonb,
     '[["Ein zerbrochener Spiegel", "Kein Krieg auf diesem Brett begann so."],
       ["Ein verlorenes Pferderennen", "Auch das steht nicht in dieser Liste."]]'::jsonb),

    ('unnuetzes-wissen', 'alte-masse-heute', 'Alte Maße, die geblieben sind',
     'Wo begegnet einem das Maß noch?',
     'medium', 'Maßeinheit', 'https://de.wikipedia.org/wiki/Ma%C3%9Feinheit',
     '[["Zoll", "Bei der Bildschirmdiagonale", "Auch beim Reifen und beim Rohr."],
       ["Pferdestärke", "Beim Motor", "Neben der amtlichen Angabe in Kilowatt."],
       ["Karat", "Beim Edelstein", "Ein Fünftel Gramm."],
       ["Unze", "Beim Goldpreis", "Die Feinunze, rund 31 Gramm."],
       ["Seemeile", "In der Schifffahrt", "Eine Bogenminute auf dem Globus."],
       ["Knoten", "Bei der Schiffsgeschwindigkeit", "Eine Seemeile je Stunde."],
       ["Fuß", "Bei der Flughöhe", "Auch im deutschen Luftraum."],
       ["Barrel", "Beim Rohöl", "Rund 159 Liter."],
       ["Pfund", "Auf dem Wochenmarkt", "Ein halbes Kilo im Sprachgebrauch."],
       ["Dutzend", "Beim Eierkauf", "Zwölf Stück."]]'::jsonb,
     '[["Beim Messen der Temperatur", "Kein Maß auf diesem Brett wird dafür genutzt."],
       ["Bei der Angabe der Uhrzeit", "Dafür steht keines in dieser Liste."]]'::jsonb),

    ('unnuetzes-wissen', 'herrscher-sammlungen', 'Was Herrscher sammelten',
     'Was sammelte diese Person?',
     'hard', 'Kunstkammer', 'https://de.wikipedia.org/wiki/Kunstkammer',
     '[["August der Starke", "Ostasiatisches Porzellan", "Er tauschte dafür sogar Soldaten."],
       ["Rudolf II.", "Kuriositäten aller Art", "Seine Kunstkammer war berühmt."],
       ["Peter der Große", "Zähne, die er selbst gezogen hatte", "Sie sind bis heute erhalten."],
       ["Katharina die Große", "Gemälde für die Eremitage", "Ganze Sammlungen auf einmal."],
       ["Ludwig XIV.", "Orangenbäume", "Für eine eigene Orangerie."],
       ["Friedrich Wilhelm I.", "Besonders große Soldaten", "Die Langen Kerls aus ganz Europa."],
       ["Ludwig II. von Bayern", "Schlösser und Baupläne", "Bis an den Rand des Staatsbankrotts."],
       ["Zar Nikolaus II.", "Kunstvolle Ostereier", "Von der Werkstatt Fabergé."],
       ["Napoleon", "Kunst aus eroberten Ländern", "Vieles kam später zurück."],
       ["Wilhelm II.", "Uniformen für jeden Anlass", "Er wechselte sie mehrfach am Tag."]]'::jsonb,
     '[["Briefmarken aus aller Welt", "Niemand auf diesem Brett sammelte sie."],
       ["Meteoritenbruchstücke", "Auch die stehen nicht in dieser Liste."]]'::jsonb),

    ('unnuetzes-wissen', 'kalender-kurios', 'Kalender & Zeitrechnung',
     'Was steckt dahinter?',
     'hard', 'Kalender', 'https://de.wikipedia.org/wiki/Kalender',
     '[["Die zehn fehlenden Tage von 1582", "Der Wechsel zum gregorianischen Kalender", "Auf den 4. folgte der 15. Oktober."],
       ["Der 30. Februar", "Gab es in Schweden im Jahr 1712", "Ein Zwischenschritt beim Kalenderwechsel."],
       ["Das Schaltjahr", "Alle vier Jahre, mit Ausnahmen", "Volle Jahrhunderte nur, wenn durch 400 teilbar."],
       ["Die Schaltsekunde", "Gleicht die ungleichmäßige Erddrehung aus", "Sie wird gelegentlich eingefügt."],
       ["Das Jahr null", "Gibt es in unserer Zählung nicht", "Auf 1 vor folgt 1 nach Christus."],
       ["Der Revolutionskalender", "Zehn Tage machten eine Woche", "In Frankreich ab 1793."],
       ["Die Sieben-Tage-Woche", "Ohne astronomischen Grund", "Sie geht auf alte Überlieferung zurück."],
       ["Die Oktoberrevolution im November", "Russland zählte noch julianisch", "Der Unterschied betrug 13 Tage."],
       ["Juli und August", "Nach zwei Römern benannt", "Nach Caesar und Augustus."],
       ["Der Jahresbeginn", "Lag jahrhundertelang nicht im Januar", "Vielerorts begann das Jahr im März."]]'::jsonb,
     '[["Ein Monat mit 32 Tagen", "So einen Monat gab es in keinem Kalender hier."],
       ["Eine Woche mit fünf Tagen", "Sie steht nicht auf diesem Brett."]]'::jsonb),

    ('unnuetzes-wissen', 'laender-die-es-nicht-mehr-gibt', 'Länder, die es nicht mehr gibt',
     'Was wurde daraus?',
     'hard', 'Untergegangener Staat',
     'https://de.wikipedia.org/wiki/Liste_untergegangener_Staaten',
     '[["Preußen", "1947 förmlich aufgelöst", "Durch ein Gesetz des Kontrollrats."],
       ["Österreich-Ungarn", "1918 in mehrere Staaten zerfallen", "Am Ende des Ersten Weltkriegs."],
       ["Osmanisches Reich", "1922 beendet, es folgte die Türkei", "Der letzte Sultan ging ins Exil."],
       ["Sowjetunion", "1991 aufgelöst", "Es entstanden fünfzehn Staaten."],
       ["Tschechoslowakei", "1993 friedlich geteilt", "Die samtene Scheidung."],
       ["Jugoslawien", "In den 1990er Jahren zerfallen", "Nach mehreren Kriegen."],
       ["DDR", "1990 der Bundesrepublik beigetreten", "Über Artikel 23 des Grundgesetzes."],
       ["Zaire", "Heißt heute Demokratische Republik Kongo", "Umbenannt 1997."],
       ["Siam", "Heißt heute Thailand", "Umbenannt 1939."],
       ["Ceylon", "Heißt heute Sri Lanka", "Umbenannt 1972."],
       ["Burma", "Heißt heute Myanmar", "Umbenannt 1989."],
       ["Persien", "Heißt heute Iran", "Umbenannt 1935."]]'::jsonb,
     '[["Ging im Römischen Reich auf", "Kein Staat auf diesem Brett endete so."],
       ["Versank im Meer", "Auf keinen in dieser Liste trifft das zu."]]'::jsonb),

    ('unnuetzes-wissen', 'hauptstadt-umgezogen', 'Hauptstädte, die umzogen',
     'Wohin wechselte die Hauptstadt?',
     'hard', 'Hauptstadt', 'https://de.wikipedia.org/wiki/Hauptstadt',
     '[["Brasilien", "Von Rio de Janeiro nach Brasília", "1960 auf dem Reißbrett gebaut."],
       ["Nigeria", "Von Lagos nach Abuja", "1991, mehr in der Landesmitte."],
       ["Tansania", "Von Daressalam nach Dodoma", "Beschlossen 1973, vollzogen viel später."],
       ["Kasachstan", "Von Almaty nach Astana", "1997 in den Norden verlegt."],
       ["Myanmar", "Von Rangun nach Naypyidaw", "2005 überraschend verkündet."],
       ["Deutschland", "Von Bonn nach Berlin", "Beschlossen 1991."],
       ["Pakistan", "Von Karatschi nach Islamabad", "In den 1960er Jahren neu gebaut."],
       ["Indien", "Von Kalkutta nach Neu-Delhi", "Ab 1911 geplant."],
       ["Türkei", "Von Istanbul nach Ankara", "1923 mit der Republik."],
       ["Elfenbeinküste", "Von Abidjan nach Yamoussoukro", "1983, in den Geburtsort des Präsidenten."],
       ["Indonesien", "Von Jakarta nach Nusantara", "Beschlossen, weil Jakarta absinkt."]]'::jsonb,
     '[["Von Madrid nach Barcelona", "Spanien verlegte seine Hauptstadt nicht."],
       ["Von Rom nach Mailand", "Auch Italien steht nicht auf diesem Brett."]]'::jsonb),

    ('unnuetzes-wissen', 'aberglaube-herkunft', 'Aberglaube & seine Herkunft',
     'Woher kommt der Aberglaube?',
     'medium', 'Aberglaube', 'https://de.wikipedia.org/wiki/Aberglaube',
     '[["Schwarze Katze von links", "Ein alter Unglücksbote", "Von rechts galt sie mancherorts als Glück."],
       ["Unter einer Leiter hindurchgehen", "Sie bildet mit der Wand ein Dreieck", "Das galt als geheiligte Form."],
       ["Ein zerbrochener Spiegel", "Sieben Jahre Unglück", "Der Spiegel galt als Abbild der Seele."],
       ["Die Zahl dreizehn", "Ein Gast zu viel beim Abendmahl", "Sie fehlt bis heute in manchem Hotel."],
       ["Auf Holz klopfen", "Schutzgeister sollten im Baum wohnen", "Man weckte sie mit dem Klopfen."],
       ["Die Daumen drücken", "Der Daumen sollte Unheil bannen", "Er wurde von den Fingern eingeschlossen."],
       ["Der Schornsteinfeger", "Er brachte Wärme und Sicherheit", "Ein verstopfter Kamin war lebensgefährlich."],
       ["Das vierblättrige Kleeblatt", "Es ist einfach sehr selten", "Auf Zehntausende kommt eines."],
       ["Freitag der dreizehnte", "Zwei Unglückszeichen fallen zusammen", "Der Freitag galt schon vorher als heikel."],
       ["Verschüttetes Salz", "Salz war einmal sehr kostbar", "Es über die Schulter zu werfen soll helfen."]]'::jsonb,
     '[["Weil es im Gesetz steht", "Kein Aberglaube auf diesem Brett kommt daher."],
       ["Aus einer wissenschaftlichen Studie", "Auf keinen in dieser Liste trifft das zu."]]'::jsonb),

    ('unnuetzes-wissen', 'waehrungen-kurios', 'Geld, unnütz betrachtet',
     'Was stimmt darüber?',
     'hard', 'Geld', 'https://de.wikipedia.org/wiki/Geld',
     '[["Die Euro-Banknoten", "Zeigen erfundene Bauwerke", "Damit sich kein Land bevorzugt fühlt."],
       ["Der größte Geldschein der Geschichte", "Hundert Trillionen Pengő", "In Ungarn, 1946."],
       ["Das erste staatliche Papiergeld", "China im 11. Jahrhundert", "Lange vor Europa."],
       ["Die Rai-Steine", "Riesige Steinscheiben als Geld", "Auf der Insel Yap, oft unbewegt."],
       ["Kaurischnecken", "Zahlungsmittel in Afrika und Asien", "Über Jahrhunderte hinweg."],
       ["Der Dollar", "Der Name stammt vom Joachimsthaler", "Über das niederländische Daler."],
       ["Der erste Kauf mit Bitcoin", "Zwei Pizzen", "2010, für 10.000 Einheiten."],
       ["Die Mark der DDR", "Durfte nicht ausgeführt werden", "Ein Umtausch war stark begrenzt."],
       ["Der Schweizer Franken", "Ist auch in Liechtenstein gesetzliches Zahlungsmittel", "Auf Grundlage eines Vertrags."],
       ["Der Pfennig", "Verschwand mit der Euro-Einführung", "Nach über tausend Jahren."]]'::jsonb,
     '[["Wurde nie aus Metall geprägt", "Auf nichts auf diesem Brett trifft das zu."],
       ["Gilt heute weltweit als Zahlungsmittel", "Keines in dieser Liste tut das."]]'::jsonb),

    ('unnuetzes-wissen', 'postgeschichte', 'Post & Briefe',
     'Was gehört dazu?',
     'medium', 'Postgeschichte', 'https://de.wikipedia.org/wiki/Postgeschichte',
     '[["Die erste Briefmarke", "Die Penny Black von 1840", "Sie zeigte Königin Victoria."],
       ["Die Postleitzahl", "In Deutschland seit 1941", "Zuerst nur zweistellig."],
       ["Die Feldpost", "Für Soldaten kostenlos befördert", "In beiden Weltkriegen millionenfach."],
       ["Die Rohrpost", "Briefe fuhren durch Druckluftröhren", "Unter den Straßen großer Städte."],
       ["Das Posthorn", "Das Signal der Postkutsche", "Es kündigte die Ankunft an."],
       ["Das Einschreiben", "Zustellung mit Nachweis", "Gegen Unterschrift übergeben."],
       ["Die Ansichtskarte", "Erst ab 1870 verbreitet", "Vorher galt offene Post als unschicklich."],
       ["Die Luftpost", "Begann mit Ballons", "Aus dem belagerten Paris 1870."],
       ["Der öffentliche Briefkasten", "Zuerst in Florenz aufgestellt", "Im 16. Jahrhundert."],
       ["Das Porto", "Zahlte früher der Empfänger", "Wer nicht wollte, nahm den Brief nicht an."]]'::jsonb,
     '[["Die E-Mail", "Sie ist keine Post auf diesem Brett."],
       ["Das Telegramm", "Es steht nicht in dieser Liste."]]'::jsonb),

    ('unnuetzes-wissen', 'mode-folgen', 'Mode & ihre Folgen',
     'Welche Folge hatte das Kleidungsstück?',
     'hard', 'Modegeschichte', 'https://de.wikipedia.org/wiki/Modegeschichte',
     '[["Die Halskrause", "Der Kopf ließ sich kaum drehen", "Essen wurde zur Übung."],
       ["Der Reifrock", "Türen und Kutschen wurden breiter gebaut", "Zwei Damen passten nicht nebeneinander."],
       ["Das Korsett", "Es verformte auf Dauer die Rippen", "Ärzte warnten früh davor."],
       ["Die Allongeperücke", "Sie verbarg Haarausfall", "Auch den durch Krankheit."],
       ["Der Schnabelschuh", "Die Länge zeigte den Rang", "Sie wurde per Verordnung begrenzt."],
       ["Die Krinoline", "Sie geriet leicht in Brand", "Offenes Feuer war überall."],
       ["Grüne Kleider mit Schweinfurter Grün", "Der Farbstoff enthielt Arsen", "Näherinnen erkrankten reihenweise."],
       ["Bleiweiß als Schminke", "Es zerstörte die Haut darunter", "Man trug immer mehr davon auf."],
       ["Der Zylinder", "Sein erstes Tragen soll einen Auflauf ausgelöst haben", "Die Geschichte ist überliefert, nicht belegt."],
       ["Der Minirock", "Ein sichtbarer Bruch mit der Kleiderordnung", "In den 1960er Jahren."]]'::jsonb,
     '[["Er machte die Träger unsichtbar", "Kein Kleidungsstück auf diesem Brett tat das."],
       ["Er wurde weltweit verboten", "Auf keines in dieser Liste trifft das zu."]]'::jsonb),

    ('unnuetzes-wissen', 'erfindungen-spaetzuender', 'Erfindungen, die zuerst scheiterten',
     'Warum kam sie nicht sofort an?',
     'hard', 'Innovation', 'https://de.wikipedia.org/wiki/Innovation',
     '[["Das Telefon", "Galt als Spielzeug ohne Nutzen", "Ein Gutachten riet vom Kauf ab."],
       ["Der Reißverschluss", "Brauchte über zwanzig Jahre bis zum Erfolg", "Erst die Stiefelindustrie griff zu."],
       ["Der Kugelschreiber", "Die ersten Modelle klecksten", "Erst spätere Tinten funktionierten."],
       ["Der Bildtelegraf", "Er war älter als das Telefon", "Und blieb doch lange ungenutzt."],
       ["Die Rechenmaschine Z3", "Wurde als nicht kriegswichtig eingestuft", "Der Antrag auf Mittel wurde abgelehnt."],
       ["Der Fernseher", "Wurde als sinnlose Spielerei verspottet", "Auch von Fachleuten."],
       ["Der Sinclair C5", "Ein Elektrofahrzeug viel zu früh", "1985 nach wenigen Monaten eingestellt."],
       ["Die Bildplatte", "Sie kam vor der DVD und ging unter", "Zu groß und zu teuer."],
       ["Der Videotext", "Vom Internet überholt", "In manchen Ländern läuft er weiter."],
       ["Der Segway", "Sollte Städte umkrempeln", "Am Ende ein Nischengerät."]]'::jsonb,
     '[["Sie war technisch unmöglich", "Auf keine Erfindung auf diesem Brett trifft das zu."],
       ["Sie wurde vom Erfinder geheim gehalten", "Keine in dieser Liste blieb verborgen."]]'::jsonb),

    ('unnuetzes-wissen', 'vertraege-kurios', 'Verträge mit Folgen',
     'Was wurde darin geregelt?',
     'hard', 'Völkerrechtlicher Vertrag',
     'https://de.wikipedia.org/wiki/V%C3%B6lkerrechtlicher_Vertrag',
     '[["Vertrag von Tordesillas", "Die Welt wurde entlang einer Linie geteilt", "Zwischen Spanien und Portugal, 1494."],
       ["Vertrag von Verdun", "Das Frankenreich wurde in drei Teile zerlegt", "843 unter Karls Enkeln."],
       ["Kauf von Louisiana", "Frankreich verkaufte ein Drittel der heutigen USA", "1803, für 15 Millionen Dollar."],
       ["Kauf von Alaska", "Russland verkaufte an die USA", "1867, für 7,2 Millionen Dollar."],
       ["Kauf von Manhattan", "Eine Insel gegen Waren geringen Werts", "Die Überlieferung ist umstritten."],
       ["Helgoland-Sansibar-Vertrag", "Eine Nordseeinsel gegen Ansprüche in Afrika", "1890 zwischen Deutschland und Großbritannien."],
       ["Vertrag von Waitangi", "Zwei Fassungen mit unterschiedlichem Inhalt", "Die Māori unterschrieben einen anderen Text."],
       ["Antarktisvertrag", "Ein ganzer Kontinent ohne Besitzer", "Seit 1961 in Kraft."],
       ["Weltraumvertrag", "Niemand darf den Mond beanspruchen", "Seit 1967 in Kraft."],
       ["Torrijos-Carter-Verträge", "Ein Kanal wurde zurückgegeben", "Zum Jahrtausendwechsel an Panama."]]'::jsonb,
     '[["Die Abschaffung aller Grenzen", "Kein Vertrag auf diesem Brett regelt das."],
       ["Ein Verbot der Seefahrt", "Auch das steht in keinem dieser Verträge."]]'::jsonb),

    ('unnuetzes-wissen', 'proteste-kurios', 'Ungewöhnliche Proteste',
     'Worin bestand der Protest?',
     'hard', 'Protest', 'https://de.wikipedia.org/wiki/Protest',
     '[["Boston Tea Party", "Ganze Teeladungen gingen über Bord", "1773 im Hafen von Boston."],
       ["Salzmarsch", "Ein Marsch ans Meer, um Salz zu gewinnen", "Gandhi brach damit ein Monopol."],
       ["Rosa Parks", "Eine Frau blieb im Bus sitzen", "Montgomery, 1955."],
       ["Suffragetten", "Frauen ketteten sich an Geländer", "Für das Wahlrecht in England."],
       ["Prager Fenstersturz", "Beamte flogen aus dem Fenster", "1618, mit weitreichenden Folgen."],
       ["Nelkenrevolution", "Blumen steckten in den Gewehrläufen", "Portugal, 1974."],
       ["Singende Revolution", "Ein ganzes Land sang sich frei", "Im Baltikum, ab 1987."],
       ["Montagsdemonstrationen", "Kerzen statt Steine in den Händen", "Leipzig, 1989."],
       ["Regenschirmbewegung", "Schirme gegen Pfefferspray", "Hongkong, 2014."],
       ["Hungerstreik", "Der Verzicht auf Nahrung als letztes Mittel", "Immer wieder in Gefängnissen eingesetzt."]]'::jsonb,
     '[["Eine Unterschriftensammlung", "Kein Protest auf diesem Brett bestand darin."],
       ["Ein Boykott von Fernsehsendungen", "Er steht nicht in dieser Liste."]]'::jsonb),

    ('unnuetzes-wissen', 'adelstitel-rang', 'Adelstitel der Reihe nach',
     'Was bedeutete der Titel?',
     'medium', 'Adelstitel', 'https://de.wikipedia.org/wiki/Adelstitel',
     '[["Kaiser", "Steht über den Königen", "Abgeleitet vom Namen Caesar."],
       ["König", "Herrscht über ein Königreich", "Meist erblich."],
       ["Erzherzog", "Ein Titel allein der Habsburger", "Eigens für sie geschaffen."],
       ["Kurfürst", "Durfte den Kaiser mitwählen", "Sieben von ihnen, später mehr."],
       ["Herzog", "Ursprünglich ein Heerführer", "Der vor dem Heer zog."],
       ["Markgraf", "Verwaltete eine Grenzmark", "Mit besonderen Vollmachten."],
       ["Fürst", "Der Erste unter den Adligen", "Verwandt mit dem englischen first."],
       ["Graf", "Ursprünglich ein Amtsträger des Königs", "Erst später erblich."],
       ["Freiherr", "Auch Baron genannt", "Ein niederer Adelstitel."],
       ["Ritter", "Der unterste Rang des Adels", "Ursprünglich an den Kriegsdienst geknüpft."]]'::jsonb,
     '[["Der gewählte Bürgermeister", "Er ist kein Adelstitel auf diesem Brett."],
       ["Der Statthalter einer Kolonie", "Er steht nicht in dieser Liste."]]'::jsonb),

    ('unnuetzes-wissen', 'spionage-kurios', 'Handwerk der Spionage',
     'Was steckt dahinter?',
     'hard', 'Spionage', 'https://de.wikipedia.org/wiki/Spionage',
     '[["Unsichtbare Tinte", "Zitronensaft wird beim Erwärmen sichtbar", "Ein Verfahren aus der Antike."],
       ["Mikropunkt", "Ein ganzer Text, zum Punkt verkleinert", "Getarnt als Satzzeichen im Brief."],
       ["Navajo-Codesprecher", "Eine ganze Sprache als Code", "Im Pazifikkrieg nie gebrochen."],
       ["Toter Briefkasten", "Übergabe ohne jede Begegnung", "Ein Versteck an vereinbarter Stelle."],
       ["Essbares Papier", "Der Schlüssel ließ sich verschlucken", "Auf dünnem Seidenpapier gedruckt."],
       ["Der präparierte Regenschirm", "Eine winzige Giftkugel als Waffe", "Ein Anschlag in London, 1978."],
       ["Die Wanze im Wappen", "Ein geschnitztes Geschenk mit Mikrofon", "Sie hing jahrelang in der US-Botschaft."],
       ["Die Legende", "Eine vollständig erfundene Lebensgeschichte", "Mit Papieren und Zeugen unterlegt."],
       ["Der Doppelagent", "Arbeitet zugleich für beide Seiten", "Meist ohne dass eine davon es weiß."],
       ["Der Schuhabsatz mit Sender", "Ein Gerät im Absatz eines Diplomaten", "Im Kalten Krieg mehrfach gefunden."]]'::jsonb,
     '[["Das Abhören über Satellit", "Kein Verfahren auf diesem Brett meint das."],
       ["Der Lügendetektor", "Er steht nicht in dieser Liste."]]'::jsonb),

    ('unnuetzes-wissen', 'herrscher-eigenheiten', 'Herrscher mit Eigenheiten',
     'Was wird über die Person berichtet?',
     'hard', 'Herrscher', 'https://de.wikipedia.org/wiki/Monarch',
     '[["Ludwig II. von Bayern", "Ließ sich nachts durch die Berge fahren", "In einem vergoldeten Schlitten."],
       ["Karl VI. von Frankreich", "Glaubte zeitweise, er sei aus Glas", "Ein überliefertes Krankheitsbild."],
       ["Heinrich VIII.", "Ging sechs Ehen ein", "Zwei davon endeten auf dem Schafott."],
       ["Joshua Norton", "Rief sich selbst zum Kaiser aus", "San Francisco spielte jahrelang mit."],
       ["Ludwig XIV.", "Ließ dem Hof beim Aufstehen zusehen", "Das Lever war ein Staatsakt."],
       ["Christian VII. von Dänemark", "Regierte kaum je selbst", "Andere führten die Geschäfte."],
       ["Kaiserin Elisabeth", "Ließ ein Turnzimmer einrichten", "Mit Ringen und Reck im Palast."],
       ["Katharina die Große", "Führte Briefwechsel mit Voltaire", "Über Jahrzehnte hinweg."],
       ["Friedrich der Große", "Wollte neben seinen Hunden begraben werden", "Erfüllt wurde es erst 1991."],
       ["Zar Peter III.", "Soll eine Ratte förmlich hingerichtet haben", "Die Anekdote ist überliefert, nicht belegt."]]'::jsonb,
     '[["Verbot in seinem Reich die Farbe Blau", "Niemand auf diesem Brett tat das."],
       ["Ließ sich zu Lebzeiten einbalsamieren", "Auf niemanden in dieser Liste trifft das zu."]]'::jsonb),

    ('unnuetzes-wissen', 'rechtsgeschichte-kurios', 'Recht aus alter Zeit',
     'Was war das?',
     'hard', 'Rechtsgeschichte',
     'https://de.wikipedia.org/wiki/Rechtsgeschichte',
     '[["Tierprozess", "Auch Tiere standen vor Gericht", "Schweine wurden verurteilt und bestraft."],
       ["Gottesurteil", "Feuer oder Wasser sollten die Wahrheit zeigen", "Wer unverletzt blieb, galt als unschuldig."],
       ["Hexenwaage", "Wer zu leicht war, galt als schuldig", "In Oudewater erhielt man ein Freizeugnis."],
       ["Femegericht", "Heimliche Gerichte mit eigenen Regeln", "Vor allem in Westfalen."],
       ["Pranger", "Angebunden auf dem Marktplatz", "Die Schande war die eigentliche Strafe."],
       ["Schandmaske", "Eine Maske zur öffentlichen Bloßstellung", "Oft mit Eselsohren oder langer Zunge."],
       ["Blutrache", "Die Familie vollstreckte selbst", "Frühe Rechtsordnungen wollten das ersetzen."],
       ["Reichsacht", "Ausschluss aus jeder Rechtsgemeinschaft", "Der Geächtete war vogelfrei."],
       ["Gottesgnadentum", "Herrschaft als göttlicher Auftrag", "Damit war sie keiner Wahl unterworfen."],
       ["Zweikampf vor Gericht", "Der Streit wurde ausgefochten", "Der Sieger galt als im Recht."]]'::jsonb,
     '[["Die Berufung an ein höheres Gericht", "Sie ist keine Besonderheit auf diesem Brett."],
       ["Die Verjährung nach dreißig Jahren", "Sie steht nicht in dieser Liste."]]'::jsonb),

    ('unnuetzes-wissen', 'essen-geschichte', 'Essen im Wandel',
     'Wie war das früher?',
     'medium', 'Ernährungsgeschichte',
     'https://de.wikipedia.org/wiki/Essen_und_Trinken',
     '[["Die Kartoffel", "Zuerst als Zierpflanze angebaut", "Die Blüte gefiel besser als die Knolle."],
       ["Die Tomate", "Galt lange als giftig", "Sie gehört zu den Nachtschattengewächsen."],
       ["Der Kaffee", "Wurde zeitweise verboten", "Preußen wollte das Geld im Land halten."],
       ["Der Zucker", "War eine Ware der Apotheken", "Verkauft in kleinen Mengen als Arznei."],
       ["Der Pfeffer", "Wurde mit Gold aufgewogen", "Daher der Pfeffersack als Spottname."],
       ["Die Gabel", "Galt als unzüchtiges Gerät", "Man aß mit Messer und Fingern."],
       ["Das Weißbrot", "War ein Zeichen des Wohlstands", "Dunkles Brot aß, wer musste."],
       ["Die Ananas", "Wurde für Feste ausgeliehen", "Zu teuer, um sie zu essen."],
       ["Der Hummer", "Galt als Essen der Armen", "Man verfütterte ihn an Gefangene."],
       ["Die Butter", "War in der Fastenzeit verboten", "Wer zahlte, bekam eine Ausnahme."]]'::jsonb,
     '[["Wurde nur roh gegessen", "Auf nichts auf diesem Brett trifft das zu."],
       ["Kam erst im 20. Jahrhundert nach Europa", "Nichts in dieser Liste kam so spät."]]'::jsonb),

    ('unnuetzes-wissen', 'epochennamen', 'Namen für ganze Epochen',
     'Was steckt hinter dem Namen?',
     'hard', 'Epoche', 'https://de.wikipedia.org/wiki/Epoche',
     '[["Das finstere Mittelalter", "Ein Schlagwort späterer Jahrhunderte", "Die Zeitgenossen sahen sich nicht so."],
       ["Die Renaissance", "Der Begriff kam erst im 19. Jahrhundert auf", "Wörtlich die Wiedergeburt."],
       ["Die Goldenen Zwanziger", "Gemeint ist nur ein Teil des Jahrzehnts", "Anfang und Ende waren alles andere als golden."],
       ["Die Belle Époque", "Erst im Rückblick verklärt", "Benannt nach dem Ersten Weltkrieg."],
       ["Der Kalte Krieg", "Ein Krieg ohne direkte Schlacht", "Der Begriff stammt von einem Publizisten."],
       ["Das Wirtschaftswunder", "Der rasche Aufschwung nach 1948", "Fachleute halten das Wunder für erklärbar."],
       ["Die Steinzeit", "Nach dem wichtigsten Werkstoff benannt", "Ebenso Bronze- und Eisenzeit."],
       ["Die Völkerwanderung", "Kein einheitlicher Vorgang", "Eher viele Bewegungen über Jahrhunderte."],
       ["Die Aufklärung", "Das Licht der Vernunft steckt im Namen", "Auf Englisch enlightenment."],
       ["Die Gründerzeit", "Benannt nach der Reichsgründung", "Sie endete im Börsenkrach von 1873."]]'::jsonb,
     '[["Benannt nach einem Herrscherhaus", "Kein Name auf diesem Brett kommt daher."],
       ["Von den Zeitgenossen selbst gewählt", "Auf keinen in dieser Liste trifft das zu."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

fakes as (
    select q.id                                         as quiz_id,
           k.value ->> 0                                as label,
           k.value ->> 1                                as explanation,
           (jsonb_array_length(sp.pairs) + k.ord)::int  as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.fakes) with ordinality k(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
),

paired as (
    insert into items (quiz_id, category_id, label, position, explanation)
    select f.quiz_id, c.id, f.answer, f.position, f.explanation
      from flat f
      join new_categories c
        on c.quiz_id = f.quiz_id
       and c.label = f.label
    returning id
)

insert into items (quiz_id, category_id, label, position, explanation)
select k.quiz_id, null, k.label, k.position, k.explanation
  from fakes k;
