-- Videospiele, mittlere Fragen. Zwanzig Fragen, alle 'medium'.
--
-- Vorher anwenden: supabase/questions/subject-videospiele.sql.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs, fakes) as (
    values

    ('videospiele', 'studios-hauptwerke', 'Studios & ihre Hauptwerke',
     'Wofür ist das Studio bekannt?',
     'medium', 'Spieleentwickler',
     'https://de.wikipedia.org/wiki/Spieleentwickler',
     '[["Rockstar Games", "Grand Theft Auto V", "Eines der umsatzstärksten Unterhaltungsprodukte überhaupt."],
       ["Valve", "Half-Life", "Danach kam jahrelang keine Fortsetzung."],
       ["Blizzard Entertainment", "World of Warcraft", "Seit 2004 durchgehend im Betrieb."],
       ["Mojang", "Minecraft", "2014 von Microsoft gekauft."],
       ["CD Projekt Red", "The Witcher 3", "Nach den Romanen von Sapkowski."],
       ["FromSoftware", "Dark Souls", "Namensgeber eines ganzen Genres."],
       ["Bethesda Game Studios", "Skyrim", "Auf sehr viele Plattformen portiert."],
       ["id Software", "Doom", "Es machte den Ego-Shooter populär."],
       ["Naughty Dog", "The Last of Us", "Später auch als Serie verfilmt."],
       ["Bungie", "Halo", "Der Startschuss für die erste Xbox."],
       ["Epic Games", "Fortnite", "Groß wurde erst der Battle-Royale-Modus."],
       ["Rare", "GoldenEye 007", "Der Mehrspielermodus wurde spät eingebaut."]]'::jsonb,
     '[["Half-Life 2", "Auch von Valve, doch auf dem Brett steht der erste Teil."],
       ["Portal 2", "Ebenfalls aus dem Hause Valve, hier aber keine Antwort."]]'::jsonb),

    ('videospiele', 'spiele-erscheinungsjahre', 'Wann kam das Spiel heraus?',
     'In welchem Jahr erschien es?',
     'medium', 'Geschichte der Videospiele',
     'https://de.wikipedia.org/wiki/Geschichte_der_Videospiele',
     '[["Pong", "1972", "Der Automat, der die Branche startete."],
       ["Space Invaders", "1978", "In Japan wurden Münzen knapp."],
       ["Pac-Man", "1980", "Bis heute die bekannteste Spielfigur der Spielhalle."],
       ["Tetris", "1984", "Entstanden in der Sowjetunion."],
       ["Super Mario Bros.", "1985", "Es rettete den Konsolenmarkt."],
       ["Doom", "1993", "Es verbreitete sich über Shareware."],
       ["Half-Life", "1998", "Erzählt ohne einzige Zwischensequenz."],
       ["Die Sims", "2000", "Zielgruppe weit über Spieler hinaus."],
       ["World of Warcraft", "2004", "Millionen Abonnenten in der Blütezeit."],
       ["Wii Sports", "2006", "Es lag der Konsole bei."],
       ["Minecraft", "2011", "Die Vollversion nach zwei Jahren Testphase."],
       ["Fortnite", "2017", "Der kostenlose Modus kam kurz nach dem Start."]]'::jsonb,
     '[["1996", "Tomb Raider kam damals, das Spiel fehlt auf diesem Brett."],
       ["2007", "Portal erschien in dem Jahr, das hier nicht steht."]]'::jsonb),

    ('videospiele', 'reihen-publisher', 'Reihen & Publisher',
     'Wer bringt die Reihe heraus?',
     'medium', 'Publisher', 'https://de.wikipedia.org/wiki/Publisher',
     '[["Assassin’s Creed", "Ubisoft", "Ein französisches Unternehmen."],
       ["EA Sports FC", "Electronic Arts", "Bis 2023 unter dem Namen FIFA."],
       ["Resident Evil", "Capcom", "In Japan heißt die Reihe Biohazard."],
       ["Metal Gear", "Konami", "Lange geprägt von Hideo Kojima."],
       ["Final Fantasy", "Square Enix", "Aus der Fusion zweier Firmen entstanden."],
       ["Halo", "Microsoft", "Die Reihe blieb Konsolen-exklusiv."],
       ["Uncharted", "Sony", "Erschien zuerst nur für PlayStation."],
       ["The Elder Scrolls", "Bethesda", "Seit 2021 unter Microsofts Dach."],
       ["Mario Kart", "Nintendo", "Seit 1992 auf jeder eigenen Konsole."],
       ["Total War", "Sega", "Der japanische Konzern kaufte den Entwickler."],
       ["Civilization", "2K Games", "Teil des Take-Two-Konzerns."]]'::jsonb,
     '[["Activision", "Call of Duty käme von dort, und die Reihe fehlt auf dem Brett."],
       ["Bandai Namco", "Tekken erscheint dort, es steht nicht in dieser Liste."]]'::jsonb),

    ('videospiele', 'genres-musterbeispiele', 'Genres & Musterbeispiele',
     'Welches Spiel steht für das Genre?',
     'medium', 'Computerspielgenre',
     'https://de.wikipedia.org/wiki/Computerspielgenre',
     '[["MOBA", "League of Legends", "Zwei Teams, drei Wege, ein Hauptgebäude."],
       ["Battle Royale", "PUBG", "Der Kreis zwingt alle zusammen."],
       ["Soulslike", "Elden Ring", "Hoher Schwierigkeitsgrad als Prinzip."],
       ["Metroidvania", "Hollow Knight", "Neue Fähigkeiten öffnen alte Wege."],
       ["Echtzeitstrategie", "StarCraft", "Drei Völker, ausbalanciert bis heute."],
       ["Rundenstrategie", "Sid Meier’s Civilization", "Ein Zug nach dem anderen."],
       ["Aufbausimulation", "Anno 1800", "Warenketten statt Kämpfe."],
       ["Rhythmusspiel", "Beat Saber", "Zwei Lichtschwerter im Takt."],
       ["Survival", "Rust", "Andere Spieler sind die größte Gefahr."],
       ["Point-and-Click", "Monkey Island", "Gelöst wird mit Wortwitz."],
       ["Roguelike", "Hades", "Jeder Tod beginnt einen neuen Versuch."],
       ["Autobattler", "Teamfight Tactics", "Aufstellen, dann zusehen."]]'::jsonb,
     '[["Tetris", "Ein Puzzlespiel, aber kein Genre auf diesem Brett."],
       ["Gran Turismo", "Die Rennsimulation fehlt in dieser Liste."]]'::jsonb),

    ('videospiele', 'engines-firmen', 'Spiel-Engines',
     'Von wem stammt die Engine?',
     'medium', 'Spiel-Engine', 'https://de.wikipedia.org/wiki/Spiel-Engine',
     '[["Unreal Engine", "Epic Games", "Auch außerhalb der Spielebranche im Einsatz."],
       ["Unity", "Unity Technologies", "Sehr verbreitet bei kleinen Studios."],
       ["Source", "Valve", "Basis von Half-Life 2 und Portal."],
       ["CryEngine", "Crytek", "Bekannt geworden mit Far Cry."],
       ["Frostbite", "DICE", "Konzernweit bei Electronic Arts eingesetzt."],
       ["RE Engine", "Capcom", "Seit Resident Evil 7 im Einsatz."],
       ["Creation Engine", "Bethesda", "Grundlage von Skyrim und Fallout 4."],
       ["id Tech", "id Software", "Frühe Versionen wurden quelloffen."],
       ["Godot", "Quelloffenes Projekt", "Von einer Gemeinschaft entwickelt."],
       ["Decima", "Guerrilla Games", "Auch von Hideo Kojima genutzt."],
       ["Anvil", "Ubisoft", "Trägt seit Assassin’s Creed die Reihe."]]'::jsonb,
     '[["Electronic Arts", "Die Frostbite gehört zu DICE, das zum Konzern zählt."],
       ["Rockstar Games", "Die RAGE-Engine steht nicht auf diesem Brett."]]'::jsonb),

    ('videospiele', 'schoepfer-werke', 'Schöpfer & ihre Werke',
     'Wofür steht diese Person?',
     'medium', 'Computerspiel', 'https://de.wikipedia.org/wiki/Computerspiel',
     '[["Shigeru Miyamoto", "Super Mario", "Er erfand auch Zelda und Donkey Kong."],
       ["Hideo Kojima", "Metal Gear", "Bekannt für lange Zwischensequenzen."],
       ["Alexei Paschitnow", "Tetris", "Verdient hat er lange nichts daran."],
       ["Sid Meier", "Civilization", "Sein Name steht im Titel."],
       ["Will Wright", "Die Sims", "Zuvor schuf er SimCity."],
       ["Markus Persson", "Minecraft", "Bekannt unter dem Namen Notch."],
       ["Hidetaka Miyazaki", "Dark Souls", "Er prägte den Ruf von FromSoftware."],
       ["John Carmack", "Doom", "Der Programmierer hinter der 3D-Technik."],
       ["Toru Iwatani", "Pac-Man", "Er wollte ein Spiel auch für Frauen."],
       ["Gunpei Yokoi", "Game Boy", "Sein Prinzip: bewährte Technik neu genutzt."],
       ["Yuji Naka", "Sonic", "Er programmierte den ersten Teil."],
       ["Eric Barone", "Stardew Valley", "Vier Jahre lang allein entwickelt."]]'::jsonb,
     '[["Yuji Horii", "Dragon Quest stammt von ihm, und das fehlt auf diesem Brett."],
       ["Fumito Ueda", "Shadow of the Colossus steht nicht in dieser Liste."]]'::jsonb),

    ('videospiele', 'schauplaetze', 'Schauplätze',
     'Wo spielt das Spiel?',
     'medium', 'Computerspiel', 'https://de.wikipedia.org/wiki/Computerspiel',
     '[["Grand Theft Auto V", "Los Santos", "Nachbau von Los Angeles."],
       ["Fallout 3", "Washington", "Die Hauptstadt nach dem Atomkrieg."],
       ["Skyrim", "Himmelsrand", "Die nördlichste Provinz Tamriels."],
       ["BioShock", "Rapture", "Eine Stadt tief unter dem Meer."],
       ["Half-Life", "Black Mesa", "Ein Forschungskomplex in der Wüste."],
       ["Cyberpunk 2077", "Night City", "Zwischen Los Angeles und San Francisco gedacht."],
       ["Red Dead Redemption 2", "Wilder Westen", "Am Ende der Ära der Revolverhelden."],
       ["Resident Evil 2", "Raccoon City", "Eine Stadt voller Untoter."],
       ["The Witcher 3", "Novigrad", "Größte Stadt des Nordens."],
       ["Dishonored", "Dunwall", "Eine Hafenstadt in der Rattenplage."],
       ["Hollow Knight", "Hallownest", "Ein verfallenes Insektenreich."]]'::jsonb,
     '[["City 17", "Auch aus Half-Life, doch auf dem Brett steht Black Mesa."],
       ["Hyrule", "Zelda fehlt in dieser Liste."]]'::jsonb),

    ('videospiele', 'spielemusik-komponisten', 'Musik im Spiel',
     'Welche Reihe hat diese Person vertont?',
     'medium', 'Videospielmusik',
     'https://de.wikipedia.org/wiki/Videospielmusik',
     '[["Koji Kondo", "Super Mario", "Seine Melodie kennt fast jeder."],
       ["Nobuo Uematsu", "Final Fantasy", "Orchesterkonzerte füllen ganze Säle."],
       ["Jeremy Soule", "The Elder Scrolls", "Breite Chöre und Hörner."],
       ["Mick Gordon", "Doom", "Metallgitarren als Antrieb."],
       ["Yoko Shimomura", "Kingdom Hearts", "Zuvor arbeitete sie bei Capcom."],
       ["Martin O’Donnell", "Halo", "Der Chorgesang wurde zum Markenzeichen."],
       ["Jesper Kyd", "Assassin’s Creed", "Auch für Hitman verantwortlich."],
       ["C418", "Minecraft", "Ein deutscher Musiker."],
       ["Austin Wintory", "Journey", "Erste Spielmusik mit Grammy-Nominierung."],
       ["Michiru Yamane", "Castlevania", "Barock trifft auf Rock."]]'::jsonb,
     '[["Grant Kirkhope", "Banjo-Kazooie stammt von ihm, und das fehlt auf diesem Brett."],
       ["Darren Korb", "Hades hat er vertont, das steht nicht in dieser Liste."]]'::jsonb),

    ('videospiele', 'esport-turniere', 'E-Sport-Turniere',
     'Wie heißt der große Wettbewerb des Spiels?',
     'medium', 'E-Sport', 'https://de.wikipedia.org/wiki/E-Sport',
     '[["League of Legends", "Worlds", "Die Weltmeisterschaft im Herbst."],
       ["Dota 2", "The International", "Das Preisgeld kommt von den Spielern."],
       ["Counter-Strike", "Major", "Vom Entwickler unterstütztes Turnier."],
       ["Overwatch", "Overwatch League", "Nach Vorbild klassischer Sportligen."],
       ["Rocket League", "RLCS", "Weltmeisterschaft mit Autos."],
       ["Fortnite", "World Cup", "2019 mit dem größten Einzelpreisgeld."],
       ["Valorant", "Champions", "Der Saisonabschluss."],
       ["StarCraft II", "GSL", "Die südkoreanische Liga."],
       ["Call of Duty", "Call of Duty League", "Mit festen Stadtteams."],
       ["Street Fighter", "EVO", "Das größte Turnier für Prügelspiele."]]'::jsonb,
     '[["Six Invitational", "Das Turnier von Rainbow Six, und das Spiel fehlt hier."],
       ["Apex Legends Global Series", "Sie steht nicht auf diesem Brett."]]'::jsonb),

    ('videospiele', 'abkuerzungen', 'Abkürzungen',
     'Wofür steht das Kürzel?',
     'medium', 'Nicht-Spieler-Charakter',
     'https://de.wikipedia.org/wiki/Nicht-Spieler-Charakter',
     '[["NPC", "Vom Spiel gesteuerte Figur", "Sie gehört niemandem am Controller."],
       ["DLC", "Herunterladbare Erweiterung", "Meist kostenpflichtig."],
       ["FPS", "Bilder pro Sekunde", "Je mehr, desto flüssiger."],
       ["RPG", "Rollenspiel", "Charakterwerte steigen mit der Zeit."],
       ["MMO", "Sehr viele Spieler gleichzeitig", "Alle in derselben Welt."],
       ["HUD", "Anzeige am Bildschirmrand", "Leben, Munition, Karte."],
       ["AFK", "Gerade nicht am Gerät", "Der Rest wartet."],
       ["RNG", "Zufallsgenerator", "Er entscheidet über Beute."],
       ["QTE", "Taste im richtigen Moment", "Sonst scheitert die Szene."],
       ["DPS", "Schaden pro Sekunde", "Maß für die Kampfkraft."],
       ["XP", "Erfahrungspunkte", "Sie führen zum Stufenaufstieg."],
       ["GOTY", "Spiel des Jahres", "Ein Titel, viele Verleiher."]]'::jsonb,
     '[["Spielstand zum Weiterspielen", "Der Speicherpunkt hat kein Kürzel auf diesem Brett."],
       ["Zwei Spieler an einem Gerät", "Der Splitscreen fehlt in dieser Liste."]]'::jsonb),

    ('videospiele', 'speichermedien', 'Was steckt in der Konsole?',
     'Auf welchem Medium kamen die Spiele?',
     'medium', 'Speichermedium', 'https://de.wikipedia.org/wiki/Speichermedium',
     '[["Nintendo Entertainment System", "Steckmodul", "Pusten half angeblich."],
       ["PlayStation", "CD-ROM", "Der Wechsel weg vom Modul."],
       ["PlayStation 2", "DVD", "Sie war zugleich ein DVD-Player."],
       ["PlayStation 3", "Blu-ray", "Sie half dem Format zum Durchbruch."],
       ["PlayStation Portable", "UMD", "Eine kleine Scheibe im Schuber."],
       ["Commodore 64", "Kassette", "Das Laden dauerte Minuten."],
       ["Amiga", "Diskette", "Oft mehrere pro Spiel."],
       ["Nintendo Switch", "Spielkarte", "Winzig und bitter beschichtet."],
       ["Xbox Series S", "Nur Download", "Kein Laufwerk verbaut."],
       ["Dreamcast", "GD-ROM", "Ein eigenes Format gegen Raubkopien."]]'::jsonb,
     '[["Magnetband auf Spulen", "So kam kein Spiel auf diesem Brett heraus."],
       ["Laserdisc", "Ein Format, das in dieser Liste nicht vorkommt."]]'::jsonb),

    ('videospiele', 'handhelds', 'Handhelds im Vergleich',
     'Was war das Besondere am Gerät?',
     'medium', 'Handheld-Konsole',
     'https://de.wikipedia.org/wiki/Handheld-Konsole',
     '[["Game Boy", "Vier Grüntöne", "Dafür sehr lange Batterielaufzeit."],
       ["Game Boy Color", "Farbe, gleiche Spiele", "Alte Module liefen weiter."],
       ["Game Boy Advance", "Breites Format", "Schultertasten an den Seiten."],
       ["Nintendo DS", "Zwei Bildschirme", "Der untere per Stift bedient."],
       ["Nintendo 3DS", "3D ohne Brille", "Der Effekt ließ sich abschalten."],
       ["Virtual Boy", "Rot-schwarzes Stereobild", "Ein kommerzieller Fehlschlag."],
       ["Game & Watch", "Ein Spiel pro Gerät", "Mit Uhr und Wecker."],
       ["PlayStation Portable", "Filme auf UMD", "Auch als Medienspieler gedacht."],
       ["PlayStation Vita", "Feld auf der Rückseite", "Berührung von hinten."],
       ["Game Gear", "Kurze Batterielaufzeit", "Farbe kostete sechs Batterien."],
       ["Switch Lite", "Nur für unterwegs", "Kein Anschluss an den Fernseher."]]'::jsonb,
     '[["Erstes Gerät mit Farbdisplay überhaupt", "Der Game Gear hatte es zuerst, gefragt ist dort anderes."],
       ["Handheld mit Auswechseln von Modulen im Betrieb", "Das kann kein Gerät in dieser Liste."]]'::jsonb),

    ('videospiele', 'studios-laender', 'Woher kommt das Spiel?',
     'In welchem Land sitzt das Entwicklerstudio?',
     'medium', 'Spieleentwickler',
     'https://de.wikipedia.org/wiki/Spieleentwickler',
     '[["The Witcher 3", "Polen", "Entwickelt in Warschau."],
       ["Minecraft", "Schweden", "Ursprünglich aus Stockholm."],
       ["Angry Birds", "Finnland", "Von Rovio in Espoo."],
       ["Anno", "Deutschland", "Lange in Mainz entwickelt."],
       ["Rayman", "Frankreich", "Von Ubisoft in Montpellier."],
       ["Cuphead", "Kanada", "Von drei Personen begonnen."],
       ["Hollow Knight", "Australien", "Ein Studio aus Adelaide."],
       ["Grand Theft Auto", "Schottland", "Rockstar North sitzt in Edinburgh."],
       ["Super Mario", "Japan", "Nintendo residiert in Kyoto."],
       ["Halo", "USA", "Bungie kam aus Chicago."]]'::jsonb,
     '[["Niederlande", "Guerrilla Games sitzt dort, und das Studio fehlt auf dem Brett."],
       ["Südkorea", "Kein Spiel in dieser Liste stammt von dort."]]'::jsonb),

    ('videospiele', 'alterskennzeichen', 'Alterskennzeichen',
     'Was bedeutet die Angabe?',
     'medium', 'Unterhaltungssoftware Selbstkontrolle',
     'https://de.wikipedia.org/wiki/Unterhaltungssoftware_Selbstkontrolle',
     '[["USK 0", "Ohne Altersbeschränkung", "Für jedes Alter geeignet."],
       ["USK 6", "Ab sechs Jahren", "Gelbes Kennzeichen."],
       ["USK 12", "Ab zwölf Jahren", "Grünes Kennzeichen."],
       ["USK 16", "Ab sechzehn Jahren", "Blaues Kennzeichen."],
       ["USK 18", "Keine Jugendfreigabe", "Rotes Kennzeichen."],
       ["PEGI", "Kennzeichen in Europa", "In Deutschland nicht bindend."],
       ["ESRB", "Kennzeichen in Nordamerika", "Von M bis E eingeteilt."],
       ["Indizierung", "Nicht öffentlich beworben", "Verkauf nur unter der Theke."],
       ["USK-Prüfung", "Vor dem Verkauf nötig", "Sonst gilt der Titel als ungeprüft."],
       ["Gesetzliche Grundlage", "Jugendschutzgesetz", "Anders als in vielen Ländern verbindlich."]]'::jsonb,
     '[["Ab vierzehn Jahren", "Eine solche Stufe gibt es bei der USK nicht."],
       ["CERO", "Das japanische Kennzeichen fehlt auf diesem Brett."]]'::jsonb),

    ('videospiele', 'technik-begriffe', 'Technik im Spiel',
     'Was steckt hinter dem Begriff?',
     'medium', 'Grafikkarte', 'https://de.wikipedia.org/wiki/Grafikkarte',
     '[["Bildrate", "Bilder pro Sekunde", "Meist 30 oder 60."],
       ["Auflösung", "Zahl der Bildpunkte", "Von HD bis 4K."],
       ["Raytracing", "Berechnete Lichtstrahlen", "Spiegelungen werden realistisch."],
       ["SSD", "Kurze Ladezeiten", "Ohne bewegliche Teile."],
       ["VRAM", "Speicher der Grafikkarte", "Er begrenzt die Texturqualität."],
       ["Kantenglättung", "Glättet Treppenstufen", "Schräge Linien wirken weicher."],
       ["Eingabeverzögerung", "Zeit bis zur Reaktion", "Besonders in Prügelspielen wichtig."],
       ["Tearing", "Zerrissenes Bild", "Bild und Monitor laufen auseinander."],
       ["Upscaling", "Klein rechnen, groß zeigen", "Spart Leistung."],
       ["HDR", "Größerer Kontrastumfang", "Hell und dunkel zugleich."]]'::jsonb,
     '[["Zahl der Spieler im Netz", "Kein Begriff auf diesem Brett meint das."],
       ["Speicherplatz auf der Festplatte", "Danach fragt hier keine Zeile."]]'::jsonb),

    ('videospiele', 'geschaeftsmodelle', 'Womit verdienen Spiele Geld?',
     'Wie funktioniert das Modell?',
     'medium', 'Free-to-play', 'https://de.wikipedia.org/wiki/Free-to-play',
     '[["Vollpreisspiel", "Einmal zahlen", "Alles ist danach enthalten."],
       ["Free-to-play", "Kostenlos einsteigen", "Bezahlt wird später oder nie."],
       ["Mikrotransaktion", "Kleine Käufe im Spiel", "Oft nur Aussehen."],
       ["DLC", "Kostenpflichtige Erweiterung", "Neue Karten oder Kapitel."],
       ["Season Pass", "Erweiterungen im Voraus", "Gekauft wird ungesehen."],
       ["Abo-Dienst", "Monatlich viele Spiele", "Der Katalog wechselt."],
       ["Early Access", "Kauf vor der Fertigstellung", "Der Preis steigt oft später."],
       ["Demo", "Kostenlose Probe", "Früher auf Heft-CDs."],
       ["Crowdfunding", "Fans zahlen vorab", "Ohne Garantie auf ein Ergebnis."],
       ["Beutekiste", "Zufälliger Inhalt gegen Geld", "In einigen Ländern reguliert."]]'::jsonb,
     '[["Werbung zwischen den Runden", "Sie finanziert manches Spiel, steht aber nicht auf dem Brett."],
       ["Verleih auf Zeit im Laden", "Ein altes Modell, das hier fehlt."]]'::jsonb),

    ('videospiele', 'konsolen-jahre', 'Konsolen & ihre Jahrgänge',
     'Wann kam die Konsole heraus?',
     'medium', 'Spielkonsole', 'https://de.wikipedia.org/wiki/Spielkonsole',
     '[["Nintendo Entertainment System", "1983", "In Japan als Famicom gestartet."],
       ["Mega Drive", "1988", "In Nordamerika hieß sie Genesis."],
       ["Game Boy", "1989", "Verkauft mit Tetris im Bündel."],
       ["PlayStation", "1994", "Aus einem geplatzten Nintendo-Projekt entstanden."],
       ["Nintendo 64", "1996", "Vier Anschlüsse ab Werk."],
       ["Dreamcast", "1998", "Segas letzte Konsole."],
       ["PlayStation 2", "2000", "Die meistverkaufte Konsole überhaupt."],
       ["Xbox", "2001", "Microsofts Einstieg ins Geschäft."],
       ["Wii", "2006", "Bewegungssteuerung als Verkaufsargument."],
       ["PlayStation 4", "2013", "Start mit deutlichem Vorsprung."],
       ["Nintendo Switch", "2017", "Handheld und Heimkonsole zugleich."],
       ["Xbox Series X", "2020", "Zeitgleich mit der PlayStation 5."]]'::jsonb,
     '[["1977", "Das Atari VCS kam damals, es fehlt auf diesem Brett."],
       ["2005", "Die Xbox 360 erschien in dem Jahr, das hier nicht steht."]]'::jsonb),

    ('videospiele', 'neunziger-klassiker', 'Klassiker der Neunziger',
     'Wofür wurde das Spiel bekannt?',
     'medium', 'Geschichte der Videospiele',
     'https://de.wikipedia.org/wiki/Geschichte_der_Videospiele',
     '[["Doom", "Shooter im Netzwerk", "Ganze Büros spielten nach Feierabend."],
       ["Myst", "Rätsel auf einer Insel", "Lange das meistverkaufte PC-Spiel."],
       ["Monkey Island", "Piraten und Wortduelle", "Gefochten wird mit Beleidigungen."],
       ["Command & Conquer", "Strategie mit Realfilm", "Schauspieler in den Zwischenszenen."],
       ["Tomb Raider", "Heldin in 3D", "Ungewöhnlich für die Zeit."],
       ["GoldenEye 007", "Splitscreen am N64", "Zu viert vor einem Fernseher."],
       ["Diablo", "Klicken in Verliesen", "Beute als Antrieb."],
       ["Quake", "Vollständig dreidimensional", "Auch die Gegner waren Modelle."],
       ["Pokémon Rot", "Tausch per Kabel", "Manche Entwicklungen gehen nur so."],
       ["Final Fantasy VII", "Drei CDs Handlung", "Der Durchbruch in Europa."],
       ["Age of Empires", "Völker durch Zeitalter", "Vom Faustkeil zur Belagerung."]]'::jsonb,
     '[["Erste offene Welt in 3D", "Kein Spiel auf diesem Brett steht dafür."],
       ["Kämpfe mit sehr blutigen Finishern", "Mortal Kombat wäre das, und es fehlt hier."]]'::jsonb),

    ('videospiele', 'spielkultur', 'Rund ums Spielen',
     'Was ist damit gemeint?',
     'medium', 'Let’s Play', 'https://de.wikipedia.org/wiki/Let%E2%80%99s_Play',
     '[["Twitch", "Übertragung in Echtzeit", "Zuschauer schreiben im Chat mit."],
       ["Let’s Play", "Kommentiertes Durchspielen", "Aufgenommen statt live."],
       ["Speedrun", "So schnell wie möglich", "Fehler im Spiel sind erlaubt."],
       ["Mod", "Veränderung durch Fans", "Manche wurden eigene Spiele."],
       ["Emulator", "Altes System nachgebildet", "Rechtlich oft eine Grauzone."],
       ["Retrogaming", "Bewusst alte Spiele", "Original oder als Neuauflage."],
       ["Cosplay", "Verkleidung als Figur", "Auf Messen sehr präsent."],
       ["Achievement", "Belohnung für Sonderleistung", "Sammelbar ohne Spielvorteil."],
       ["Fotomodus", "Bilder im Spiel schießen", "Kamera frei beweglich."],
       ["Backseat-Gaming", "Ungefragte Ratschläge", "Der Zuschauer weiß es besser."]]'::jsonb,
     '[["Turnier unter Freunden im Wohnzimmer", "Es hat keinen Begriff auf diesem Brett."],
       ["Sammeln alter Konsolen im Regal", "Das fehlt in dieser Liste."]]'::jsonb),

    ('videospiele', 'messen-preise', 'Messen & Preise',
     'Worum handelt es sich?',
     'medium', 'The Game Awards',
     'https://de.wikipedia.org/wiki/The_Game_Awards',
     '[["gamescom", "Größte Spielemesse Europas", "Jedes Jahr in Köln."],
       ["The Game Awards", "Preisverleihung im Dezember", "Zugleich Bühne für Ankündigungen."],
       ["Deutscher Computerspielpreis", "Staatlich unterstützte Auszeichnung", "Vergeben seit 2009."],
       ["Game Developers Conference", "Fachtreffen der Entwickler", "Vorträge statt Publikum."],
       ["E3", "Messe in Los Angeles", "Jahrzehntelang der Branchentermin."],
       ["Tokyo Game Show", "Japanische Publikumsmesse", "Im Herbst bei Tokio."],
       ["Games Convention", "Vorgängerin in Leipzig", "Bis 2008, dann Umzug nach Köln."],
       ["IGF", "Preis für Independent-Spiele", "Sprungbrett für kleine Studios."],
       ["BAFTA Games Award", "Britische Auszeichnung", "Von derselben Akademie wie beim Film."],
       ["Spiel des Jahres", "Preis für Brettspiele", "Trotz des Namens kein Videospielpreis."]]'::jsonb,
     '[["PAX", "Eine Publikumsmesse in den USA, die hier fehlt."],
       ["DreamHack", "Ein Festival mit LAN-Party, das nicht auf dem Brett steht."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

-- The answers that belong to no category. Numbered after the pairs so the two
-- sets never collide on `position`, though nothing reads it for a fake: the
-- pool is shuffled before a player sees it, and the review lists fakes on their
-- own rather than in board order.
fakes as (
    select q.id                                         as quiz_id,
           k.value ->> 0                                as label,
           k.value ->> 1                                as explanation,
           (jsonb_array_length(sp.pairs) + k.ord)::int  as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.fakes) with ordinality k(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
),

paired as (
    insert into items (quiz_id, category_id, label, position, explanation)
    select f.quiz_id, c.id, f.answer, f.position, f.explanation
      from flat f
      join new_categories c
        on c.quiz_id = f.quiz_id
       and c.label = f.label
    returning id
)

-- Same table, `category_id` left null. Both inserts run in the one statement,
-- so `items_quiz_id_label_key` still sees the pairs above: a fake written to
-- repeat an answer already on its own board fails the file rather than becoming
-- a second row nobody can tell apart.
insert into items (quiz_id, category_id, label, position, explanation)
select k.quiz_id, null, k.label, k.position, k.explanation
  from fakes k;
