-- Videospiele, Reihen und Serien. Zwanzig Fragen, mittel und schwer.
--
-- Der Schwerpunkt liegt hier auf einzelnen Marken: welcher Teil spielt wo,
-- welcher Held gehört zu welcher Nummer, welcher Untertitel zu welcher Reihe.
--
-- Vorher anwenden: supabase/questions/subject-videospiele.sql.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs, fakes) as (
    values

    ('videospiele', 'zelda-teile', 'Zelda-Teile',
     'Was ist das Besondere an diesem Teil?',
     'hard', 'The Legend of Zelda',
     'https://de.wikipedia.org/wiki/The_Legend_of_Zelda',
     '[["Ocarina of Time", "Erster Teil in 3D", "Es prägte das Zielsystem vieler Nachfolger."],
       ["Majora’s Mask", "Immer dieselben drei Tage", "Die Zeit wird zurückgedreht."],
       ["The Wind Waker", "Comicgrafik und Seefahrt", "Gesegelt wird zwischen Inseln."],
       ["Twilight Princess", "Link wird zum Wolf", "In der Schattenwelt."],
       ["Skyward Sword", "Steuerung per Schwertschwung", "Mit der Bewegungssteuerung der Wii."],
       ["Breath of the Wild", "Offene Welt zum Erklettern", "Fast jede Wand ist begehbar."],
       ["Tears of the Kingdom", "Bauen und Verschmelzen", "Gegenstände lassen sich zusammensetzen."],
       ["A Link to the Past", "Zwei Welten von oben", "Licht- und Schattenwelt im Wechsel."],
       ["Link’s Awakening", "Traum auf einer Insel", "Ohne Prinzessin Zelda."],
       ["Four Swords", "Mehrere Links zugleich", "Gedacht für gemeinsames Spielen."],
       ["Phantom Hourglass", "Gesteuert per Stift", "Auf dem Nintendo DS."]]'::jsonb,
     '[["Gesteuert per Dampflok", "Das wäre Spirit Tracks, und der Teil steht nicht auf dem Brett."],
       ["Link wird zum Wandbild", "Das kann nur A Link Between Worlds, hier fehlt es."]]'::jsonb),

    ('videospiele', 'mario-ableger', 'Mario-Ableger',
     'Welches Genre bedient der Ableger?',
     'medium', 'Super Mario', 'https://de.wikipedia.org/wiki/Super_Mario',
     '[["Mario Kart", "Rennspiel", "Mit Gegenständen gegen die Führenden."],
       ["Mario Party", "Partyspiel", "Brettspiel plus Minispiele."],
       ["Dr. Mario", "Puzzlespiel", "Viren mit Pillen bekämpfen."],
       ["Paper Mario", "Rollenspiel", "Papierfiguren mit Rundenkämpfen."],
       ["Mario Tennis", "Tennis", "Mit Spezialschlägen."],
       ["Mario Golf", "Golf", "Auch mit Rollenspielanteil erschienen."],
       ["Luigi’s Mansion", "Geisterjagd", "Mit einem Staubsauger."],
       ["Super Mario Maker", "Levelbaukasten", "Selbst gebaute Strecken zum Teilen."],
       ["Mario Strikers", "Fußball", "Ohne Schiedsrichter und ohne Regeln."],
       ["Mario & Sonic", "Olympische Disziplinen", "Zwei Maskottchen in einem Spiel."]]'::jsonb,
     '[["Basketball", "Mario Hoops 3 on 3 gibt es wirklich, auf diesem Brett steht es nicht."],
       ["Schreibmaschinenkurs", "Mario Teaches Typing war ein Lernspiel und gehört zu keinem Eintrag hier."]]'::jsonb),

    ('videospiele', 'pokemon-regionen', 'Pokémon-Regionen',
     'In welcher Region spielt das Spiel?',
     'medium', 'Pokémon', 'https://de.wikipedia.org/wiki/Pok%C3%A9mon',
     '[["Rot und Blau", "Kanto", "Die erste Generation."],
       ["Gold und Silber", "Johto", "Danach geht es zurück nach Kanto."],
       ["Rubin und Saphir", "Hoenn", "Viel Wasser auf der Karte."],
       ["Diamant und Perl", "Sinnoh", "Mit dem Berg Kronberg in der Mitte."],
       ["Schwarz und Weiß", "Einall", "Nur neue Pokémon bis zum Abspann."],
       ["X und Y", "Kalos", "An Frankreich angelehnt."],
       ["Sonne und Mond", "Alola", "Inseln statt Arenen."],
       ["Schwert und Schild", "Galar", "An Großbritannien angelehnt."],
       ["Karmesin und Purpur", "Paldea", "Erstmals ganz offen aufgebaut."],
       ["Legenden: Arceus", "Hisui", "Dieselbe Region in ferner Vergangenheit."]]'::jsonb,
     '[["Orre", "Die Region der Colosseum-Ableger, kein Hauptspiel auf diesem Brett."],
       ["Fiore", "Schauplatz der Ranger-Spiele, die hier nicht vorkommen."]]'::jsonb),

    ('videospiele', 'final-fantasy-helden', 'Final-Fantasy-Helden',
     'Wer ist die Hauptfigur dieses Teils?',
     'hard', 'Final Fantasy', 'https://de.wikipedia.org/wiki/Final_Fantasy',
     '[["Final Fantasy IV", "Cecil", "Ein Ritter, der die Seite wechselt."],
       ["Final Fantasy VI", "Terra", "Halb Mensch, halb Esper."],
       ["Final Fantasy VII", "Cloud", "Söldner mit übergroßem Schwert."],
       ["Final Fantasy VIII", "Squall", "Wortkarger Schüler einer Kriegsakademie."],
       ["Final Fantasy IX", "Zidane", "Ein Dieb mit Schwanz."],
       ["Final Fantasy X", "Tidus", "Sportler aus einer anderen Zeit."],
       ["Final Fantasy XII", "Vaan", "Straßenjunge in Rabanastre."],
       ["Final Fantasy XIII", "Lightning", "Erste alleinige Heldin der Hauptreihe."],
       ["Final Fantasy XV", "Noctis", "Ein Prinz auf Autoreise."],
       ["Final Fantasy XVI", "Clive", "Deutlich düsterer als die Vorgänger."]]'::jsonb,
     '[["Bartz", "Hauptfigur von Final Fantasy V, und der Teil fehlt auf dem Brett."],
       ["Y’shtola", "Aus dem Onlineteil XIV, und dort ohnehin nicht die Hauptfigur."]]'::jsonb),

    ('videospiele', 'assassins-creed-epochen', 'Assassin’s Creed & Epochen',
     'In welcher Zeit und Gegend spielt der Teil?',
     'medium', 'Assassin’s Creed',
     'https://de.wikipedia.org/wiki/Assassin%E2%80%99s_Creed',
     '[["Assassin’s Creed", "Dritter Kreuzzug", "Jerusalem, Akkon und Damaskus."],
       ["Assassin’s Creed II", "Renaissance in Italien", "Mit Leonardo da Vinci als Verbündetem."],
       ["Assassin’s Creed III", "Amerikanische Revolution", "Zwischen Boston und New York."],
       ["Black Flag", "Karibische Piraten", "Das Schiff wird zum Hauptquartier."],
       ["Unity", "Französische Revolution", "Paris kurz vor dem Terror."],
       ["Syndicate", "Viktorianisches London", "Zur Zeit der Industrialisierung."],
       ["Origins", "Altes Ägypten", "Der Ursprung des Ordens."],
       ["Odyssey", "Antikes Griechenland", "Im Peloponnesischen Krieg."],
       ["Valhalla", "Wikinger in England", "Siedeln statt nur meucheln."],
       ["Mirage", "Bagdad", "Rückkehr zum alten Schleichen."],
       ["Shadows", "Feudales Japan", "Zwei sehr verschiedene Spielfiguren."]]'::jsonb,
     '[["Kolonialindien", "Schauplatz von Chronicles: India, das hier nicht steht."],
       ["Russische Revolution", "Auch ein Chronicles-Ableger, kein Teil auf diesem Brett."]]'::jsonb),

    ('videospiele', 'elder-scrolls-provinzen', 'Die Provinzen von Tamriel',
     'Wo spielt dieser Teil?',
     'hard', 'The Elder Scrolls',
     'https://de.wikipedia.org/wiki/The_Elder_Scrolls',
     '[["Arena", "Ganz Tamriel", "Der erste Teil, riesig und leer."],
       ["Daggerfall", "Hochfels", "Eine der größten Spielwelten überhaupt."],
       ["Morrowind", "Vvardenfell", "Pilzwälder und Aschestürme."],
       ["Oblivion", "Cyrodiil", "Die Hauptprovinz des Kaiserreichs."],
       ["Skyrim", "Himmelsrand", "Der Norden, mit Drachen."],
       ["Redguard", "Hammerfell", "Ein Ableger im Stil eines Abenteuerspiels."],
       ["The Elder Scrolls Online", "Mehrere Provinzen", "Das Online-Rollenspiel der Reihe."],
       ["Legends", "Ein Kartenspiel", "Kein Rollenspiel, sondern Karten."],
       ["Blades", "Für Mobilgeräte", "Kurze Kämpfe fürs Handy."],
       ["Shivering Isles", "Reich des Wahnsinns", "Erweiterung zu Oblivion."]]'::jsonb,
     '[["Elsweyr", "Die Heimat der Khajiit ist eine Erweiterung, kein Teil hier."],
       ["Schwarzmarsch", "Die Provinz der Argonier war noch nie Schauplatz eines Hauptteils."]]'::jsonb),

    ('videospiele', 'fallout-schauplaetze', 'Fallout',
     'Wo spielt der Teil, oder was ist das?',
     'hard', 'Fallout (Computerspielreihe)',
     'https://de.wikipedia.org/wiki/Fallout_(Computerspielreihe)',
     '[["Fallout", "Südkalifornien", "Noch aus der Vogelperspektive."],
       ["Fallout 2", "Nordkalifornien", "Der Nachfolger derselben Bauart."],
       ["Fallout 3", "Hauptstadtödland", "Rund um Washington."],
       ["Fallout: New Vegas", "Mojave-Wüste", "Von Obsidian entwickelt."],
       ["Fallout 4", "Boston", "Mit Siedlungsbau."],
       ["Fallout 76", "West Virginia", "Der Onlineteil der Reihe."],
       ["Fallout Tactics", "Rund um Chicago", "Taktik statt Rollenspiel."],
       ["Fallout Shelter", "Ein eigener Bunker", "Aufbauspiel fürs Handy."],
       ["Pip-Boy", "Computer am Arm", "Karte, Inventar und Radio in einem."],
       ["Vault-Tec", "Baute die Bunker", "Und benutzte sie für Experimente."],
       ["Nuka-Cola", "Das Getränk der Reihe", "Die Kronkorken sind die Währung."]]'::jsonb,
     '[["Van Buren", "Der dritte Teil, den Black Isle nie fertigstellte."],
       ["Stimpak", "Das Heilmittel der Reihe, aber keine Antwort auf dem Brett."]]'::jsonb),

    ('videospiele', 'resident-evil-teile', 'Resident Evil',
     'Was zeichnet den Teil aus?',
     'hard', 'Resident Evil', 'https://de.wikipedia.org/wiki/Resident_Evil',
     '[["Resident Evil", "Villa vor der Stadt", "Feste Kameraperspektiven."],
       ["Resident Evil 2", "Polizeirevier", "Zwei Figuren, zwei Durchgänge."],
       ["Resident Evil 3", "Flucht aus der Stadt", "Verfolgt von einem Verfolger."],
       ["Resident Evil 4", "Blick über die Schulter", "Es prägte eine Generation von Shootern."],
       ["Resident Evil 5", "Zu zweit in Afrika", "Erstmals durchgehend zu zweit."],
       ["Resident Evil 6", "Vier Kampagnen", "Der actionreichste Teil."],
       ["Resident Evil 7", "Ich-Sicht in Louisiana", "Rückkehr zum Horror."],
       ["Resident Evil Village", "Dorf mit Vampirin", "Eine Figur wurde zum Internetphänomen."],
       ["Code: Veronica", "Auf einer Gefängnisinsel", "Zuerst für den Dreamcast."],
       ["Revelations", "Auf einem Schiff", "Zuerst für den Nintendo 3DS."]]'::jsonb,
     '[["Rein auf Mehrspieler ausgelegt", "Das trifft auf Outbreak und Resistance zu, die hier fehlen."],
       ["Ein Ableger mit Lichtpistole", "Die Chronicles-Spiele auf der Wii stehen nicht auf dem Brett."]]'::jsonb),

    ('videospiele', 'souls-reihe', 'Souls und Verwandte',
     'Was ist das Kennzeichen des Spiels?',
     'hard', 'Dark Souls', 'https://de.wikipedia.org/wiki/Dark_Souls',
     '[["Demon’s Souls", "Der Anfang der Formel", "Zuerst nur in Japan erschienen."],
       ["Dark Souls", "Verbundene Welt", "Abkürzungen öffnen sich rückwärts."],
       ["Dark Souls II", "Ohne Miyazaki entstanden", "Deshalb bis heute umstritten."],
       ["Dark Souls III", "Abschluss der Trilogie", "Viele Anspielungen auf den ersten Teil."],
       ["Bloodborne", "Angriff statt Schild", "Verlorene Energie lässt sich zurückschlagen."],
       ["Sekiro", "Parieren statt ausweichen", "Ein Balken für die Haltung."],
       ["Elden Ring", "Offene Welt mit Pferd", "Von George R. R. Martin mitgestaltet."],
       ["Shadow of the Erdtree", "Erweiterung von 2024", "Eigenes Aufwertungssystem."],
       ["Nioh", "Von Team Ninja", "Japanische Geschichte mit Dämonen."],
       ["Lies of P", "Pinocchio als Vorlage", "Aus Südkorea."]]'::jsonb,
     '[["Von Team Cherry entwickelt", "Das wäre Hollow Knight, das zu keiner Zeile hier gehört."],
       ["Ein Ableger als Kartenspiel", "So etwas hat die Reihe nie hervorgebracht."]]'::jsonb),

    ('videospiele', 'gta-teile', 'Grand Theft Auto',
     'Was ist das Besondere an dem Teil?',
     'medium', 'Grand Theft Auto',
     'https://de.wikipedia.org/wiki/Grand_Theft_Auto',
     '[["Grand Theft Auto", "Ansicht von oben", "1997, noch zweidimensional."],
       ["Grand Theft Auto III", "Der Sprung in 3D", "Es machte die offene Welt zum Standard."],
       ["Vice City", "Achtziger mit Neonlicht", "Angelehnt an Miami."],
       ["San Andreas", "Drei Städte, ein Staat", "Mit Fitness, Frisuren und Flugzeugen."],
       ["Grand Theft Auto IV", "Einwanderer in Liberty City", "Deutlich ernsterer Ton."],
       ["Grand Theft Auto V", "Drei spielbare Hauptfiguren", "Jederzeit umschaltbar."],
       ["GTA Online", "Seit 2013 gepflegt", "Der eigentliche Umsatzbringer."],
       ["Chinatown Wars", "Für den Nintendo DS", "Zurück zur Draufsicht."],
       ["Vice City Stories", "Für die PSP", "Eine Vorgeschichte."],
       ["London 1969", "Erweiterung in England", "Linksverkehr inklusive."]]'::jsonb,
     '[["Zwei Städte in Japan", "Kein Teil der Reihe spielt dort."],
       ["Mit rundenbasierten Kämpfen", "Die Reihe hat so etwas nie gehabt."]]'::jsonb),

    ('videospiele', 'untertitel-reihen', 'Untertitel raten',
     'Zu welcher Reihe gehört der Untertitel?',
     'medium', 'Fortsetzung', 'https://de.wikipedia.org/wiki/Fortsetzung',
     '[["Breath of the Wild", "The Legend of Zelda", "2017 zum Start der Switch."],
       ["Odyssey", "Super Mario", "Mit einer Mütze zum Werfen."],
       ["Infinite", "BioShock", "Eine Stadt in den Wolken."],
       ["Origins", "Assassin’s Creed", "Im alten Ägypten."],
       ["Reach", "Halo", "Die Vorgeschichte zum ersten Teil."],
       ["Modern Warfare", "Call of Duty", "Der Bruch mit dem Zweiten Weltkrieg."],
       ["Legenden: Arceus", "Pokémon", "Fangen statt Arenakämpfe."],
       ["New Vegas", "Fallout", "Von einem anderen Studio entwickelt."],
       ["Wild Hunt", "The Witcher", "Der dritte und größte Teil."],
       ["Andromeda", "Mass Effect", "Eine andere Galaxie."],
       ["Awakening", "Fire Emblem", "Es rettete die Reihe vor dem Aus."],
       ["Forbidden West", "Horizon", "Roboter-Tiere an der Westküste."]]'::jsonb,
     '[["Gears of War", "Auch eine Reihe mit Untertiteln, nur keinem von diesen."],
       ["Metroid", "Prime und Dread sind Untertitel, stehen hier aber nicht."]]'::jsonb),

    ('videospiele', 'gegenstaende-reihen', 'Berühmte Gegenstände',
     'Aus welcher Reihe stammt der Gegenstand?',
     'medium', 'Computerspiel', 'https://de.wikipedia.org/wiki/Computerspiel',
     '[["Portalkanone", "Portal", "Zwei Öffnungen, ein Weg."],
       ["Schwerkraftpistole", "Half-Life", "Sie zieht und schleudert Gegenstände."],
       ["Pokéball", "Pokémon", "Wird geworfen, nicht abgefeuert."],
       ["Pip-Boy", "Fallout", "Ein Computer am Handgelenk."],
       ["Master-Schwert", "The Legend of Zelda", "Nur der Auserwählte zieht es."],
       ["Buster Sword", "Final Fantasy VII", "Größer als sein Träger."],
       ["Nanosuit", "Crysis", "Panzerung, Tarnung oder Kraft."],
       ["Energieschwert", "Halo", "Die Waffe der Eliten."],
       ["Bananenschale", "Mario Kart", "Wird hinter sich abgelegt."],
       ["Versteckte Klinge", "Assassin’s Creed", "Unterm Ärmel getragen."],
       ["Goldene Waffe", "GoldenEye 007", "Ein Treffer genügt."]]'::jsonb,
     '[["Doom", "Die BFG wäre der Gegenstand dazu, und sie fehlt auf dem Brett."],
       ["BioShock", "Die Plasmide gehören dorthin, sind hier aber nicht aufgeführt."]]'::jsonb),

    ('videospiele', 'spielorte-reihen', 'Erfundene Orte',
     'Zu welcher Reihe gehört der Ort?',
     'hard', 'Computerspiel', 'https://de.wikipedia.org/wiki/Computerspiel',
     '[["Hyrule", "The Legend of Zelda", "Das Königreich mit dem Triforce."],
       ["Tamriel", "The Elder Scrolls", "Neun Provinzen auf einem Kontinent."],
       ["Midgar", "Final Fantasy VII", "Eine Stadt auf einer Platte."],
       ["Pilzkönigreich", "Super Mario", "Regiert von Prinzessin Peach."],
       ["Azeroth", "Warcraft", "Heimat von Horde und Allianz."],
       ["Zebes", "Metroid", "Der Planet aus dem ersten Teil."],
       ["Columbia", "BioShock Infinite", "Eine Stadt in den Wolken."],
       ["Kamurocho", "Yakuza", "Nachbau eines Tokioter Viertels."],
       ["Ivalice", "Final Fantasy Tactics", "Auch in späteren Teilen wiederverwendet."],
       ["Vault 111", "Fallout 4", "Hier beginnt das Spiel im Kälteschlaf."],
       ["Sanktuario", "Diablo", "Zwischen Himmel und Hölle."]]'::jsonb,
     '[["Mass Effect", "Die Zitadelle wäre der Ort dazu, sie steht nicht auf dem Brett."],
       ["Kingdom Hearts", "Kein Ort in dieser Liste stammt aus der Reihe."]]'::jsonb),

    ('videospiele', 'pruegelspiel-reihen', 'Prügelspiele & Studios',
     'Wer steckt hinter der Reihe?',
     'medium', 'Beat ’em up',
     'https://de.wikipedia.org/wiki/Beat_%E2%80%99em_up',
     '[["Street Fighter", "Capcom", "Der zweite Teil begründete den Boom."],
       ["Tekken", "Bandai Namco", "Ein Knopf je Gliedmaße."],
       ["Mortal Kombat", "NetherRealm Studios", "Berüchtigt für seine Finisher."],
       ["Super Smash Bros.", "Nintendo", "Kein Lebensbalken, sondern Prozente."],
       ["Guilty Gear", "Arc System Works", "Handgezeichnet wirkende 3D-Grafik."],
       ["The King of Fighters", "SNK", "Kämpfe in Dreierteams."],
       ["Virtua Fighter", "Sega", "Das erste 3D-Prügelspiel."],
       ["Killer Instinct", "Rare", "Bekannt für endlose Kombos."],
       ["Dead or Alive", "Team Ninja", "Kontern als Kernmechanik."],
       ["Injustice", "Warner Bros.", "Superhelden von DC."]]'::jsonb,
     '[["Konami", "Auch Konami hat Prügelspiele gemacht, keines davon steht hier."],
       ["Square Enix", "Ehrgeiz erschien unter diesem Namen, gehört aber zu keiner Zeile."]]'::jsonb),

    ('videospiele', 'metal-gear-reihe', 'Metal Gear',
     'Was gehört zu diesem Teil?',
     'hard', 'Metal Gear', 'https://de.wikipedia.org/wiki/Metal_Gear',
     '[["Metal Gear", "Zuerst auf dem MSX", "1987, lange vor der PlayStation."],
       ["Metal Gear Solid", "Debüt auf der PlayStation", "Der internationale Durchbruch."],
       ["Sons of Liberty", "Raiden statt Snake", "Der Wechsel überraschte alle."],
       ["Snake Eater", "Dschungel der Sechziger", "Tarnung und Essen als Mechanik."],
       ["Guns of the Patriots", "Ein gealterter Snake", "Der Abschluss seiner Geschichte."],
       ["Peace Walker", "Zuerst für die PSP", "Mit Basisaufbau."],
       ["The Phantom Pain", "Offene Welt in Afghanistan", "Der letzte Teil von Kojima."],
       ["Metal Gear Rising", "Von PlatinumGames", "Schwertaction statt Schleichen."],
       ["Metal Gear Survive", "Ohne Kojima entstanden", "Von Fans weitgehend abgelehnt."],
       ["Kartonkiste", "Tarnung mit Humor", "Das Markenzeichen der Reihe."]]'::jsonb,
     '[["Zuerst für den Game Boy Color", "Das war Ghost Babel, und der Teil fehlt hier."],
       ["Ein Rennspiel mit Snake", "So einen Ableger hat es nie gegeben."]]'::jsonb),

    ('videospiele', 'valve-spiele', 'Das Valve-Universum',
     'Worum geht es dabei?',
     'medium', 'Valve', 'https://de.wikipedia.org/wiki/Valve',
     '[["Half-Life", "Wissenschaftler mit Brechstange", "Er sagt kein einziges Wort."],
       ["Half-Life 2", "Rätsel mit Schwerkraft", "Die Schwerkraftpistole trägt das halbe Spiel."],
       ["Portal", "Zwei verbundene Öffnungen", "Das Kuchenversprechen ist eine Lüge."],
       ["Team Fortress 2", "Neun feste Klassen", "Comicstil statt Realismus."],
       ["Counter-Strike", "Terroristen gegen Einsatzkräfte", "Aus einer Half-Life-Mod entstanden."],
       ["Dota 2", "Aus einer Warcraft-Mod", "Heute ein eigenes Spiel."],
       ["Left 4 Dead", "Vier gegen Zombiehorden", "Ein Regisseur steuert die Wellen."],
       ["Steam", "Laden und Bibliothek", "Anfangs nur für Updates gedacht."],
       ["Steam Deck", "Handheld von Valve", "PC-Spiele mit Linux darunter."],
       ["Half-Life: Alyx", "Nur in VR spielbar", "Nach dreizehn Jahren Pause."]]'::jsonb,
     '[["Ein Kartenspiel um Dota", "Artifact erschien 2018 und wurde rasch aufgegeben."],
       ["Ein eigenes Rollenspiel", "Valve hat so etwas nie veröffentlicht."]]'::jsonb),

    ('videospiele', 'blizzard-universen', 'Die Welten von Blizzard',
     'Was steckt dahinter?',
     'medium', 'Blizzard Entertainment',
     'https://de.wikipedia.org/wiki/Blizzard_Entertainment',
     '[["Warcraft", "Orcs gegen Menschen", "Als Echtzeitstrategie gestartet."],
       ["World of Warcraft", "Das große Online-Rollenspiel", "Seit 2004 ununterbrochen im Betrieb."],
       ["StarCraft", "Terraner, Zerg und Protoss", "In Südkorea ein Nationalsport."],
       ["Diablo", "Verliese voller Beute", "Klicken, sammeln, wiederholen."],
       ["Overwatch", "Helden mit Sonderfähigkeiten", "Teams aus sehr verschiedenen Rollen."],
       ["Hearthstone", "Karten aus Azeroth", "Ein Sammelkartenspiel."],
       ["Heroes of the Storm", "Blizzards eigenes MOBA", "Mit Figuren aus allen Reihen."],
       ["BlizzCon", "Hausmesse der Firma", "Ankündigungen vor eigenem Publikum."],
       ["Battle.net", "Eigene Onlineplattform", "Schon zu Diablo-Zeiten gestartet."],
       ["Diablo Immortal", "Zuerst fürs Handy", "Die Ankündigung wurde ausgebuht."]]'::jsonb,
     '[["The Lost Vikings", "Ein frühes Spiel der Firma, aber kein Universum auf diesem Brett."],
       ["Ein Rennspiel in Azeroth", "Angekündigt wurde so etwas nie."]]'::jsonb),

    ('videospiele', 'rennspiel-reihen', 'Rennspiel-Reihen',
     'Wofür steht die Reihe?',
     'medium', 'Rennspiel', 'https://de.wikipedia.org/wiki/Rennspiel',
     '[["Gran Turismo", "Simulation für PlayStation", "Sehr auf Fahrphysik bedacht."],
       ["Forza Motorsport", "Simulation für Xbox", "Das Gegenstück von Microsoft."],
       ["Need for Speed", "Polizei im Nacken", "Illegale Rennen bei Nacht."],
       ["Mario Kart", "Gegenstände im Rennen", "Der Letzte bekommt die besten."],
       ["Burnout", "Unfälle als Spielziel", "Punkte für Blechschaden."],
       ["F1", "Offizielle Formel-1-Lizenz", "Jährlich zur Saison."],
       ["Dirt", "Rallye auf Schotter", "Mit Ansagen des Beifahrers."],
       ["Trackmania", "Loopings und Schanzen", "Strecken bauen die Spieler selbst."],
       ["WipEout", "Schwebende Gleiter", "Mit Technomusik der Neunziger."],
       ["Ridge Racer", "Driften als Markenzeichen", "Startspiel der ersten PlayStation."]]'::jsonb,
     '[["Lastwagen quer durch Europa", "Das beschreibt den Euro Truck Simulator."],
       ["Rennen mit lizenzierten Motorrädern", "Das trifft auf MotoGP zu, auf keine Reihe hier."]]'::jsonb),

    ('videospiele', 'survival-sandbox', 'Überleben & Bauen',
     'Was macht man in dem Spiel?',
     'medium', 'Survival-Spiel',
     'https://de.wikipedia.org/wiki/Survival-Spiel',
     '[["Minecraft", "Blöcke abbauen und bauen", "Erst Holz, dann alles Weitere."],
       ["Terraria", "Zweidimensional statt würfelig", "Mit sehr vielen Bossgegnern."],
       ["Rust", "Andere Spieler sind gefährlich", "Die größte Bedrohung ist menschlich."],
       ["Ark", "Dinosaurier zähmen", "Und danach reiten."],
       ["Valheim", "Wikinger im Zwischenreich", "Aus Schweden, überraschend erfolgreich."],
       ["Subnautica", "Überleben unter Wasser", "Auf einem Ozeanplaneten."],
       ["No Man’s Sky", "Errechnete Planeten", "Praktisch unbegrenzt viele."],
       ["Don’t Starve", "Nicht verhungern", "Im Stil einer Tuschezeichnung."],
       ["7 Days to Die", "Wellen alle sieben Tage", "Dazwischen wird befestigt."],
       ["Raft", "Treiben auf einem Floß", "Material kommt aus dem Meer."]]'::jsonb,
     '[["Eine Raumstation am Leben halten", "Das ist Space Station 13, das hier nicht steht."],
       ["Eine Kolonie von oben verwalten", "So spielt sich RimWorld, kein Eintrag auf dem Brett."]]'::jsonb),

    ('videospiele', 'japanische-reihen', 'Japanische Reihen',
     'Wofür ist die Reihe bekannt?',
     'hard', 'Computerspiel', 'https://de.wikipedia.org/wiki/Computerspiel',
     '[["Monster Hunter", "Große Biester jagen", "Aus der Beute wird Ausrüstung."],
       ["Yakuza", "Verbrecher in Tokio", "Ernste Handlung, alberne Nebenaufgaben."],
       ["Persona", "Schule und Dämonen", "Ein Kalenderjahr als Rahmen."],
       ["Splatoon", "Farbe statt Kugeln", "Es zählt die bemalte Fläche."],
       ["Animal Crossing", "Leben im Dorf", "Es läuft in Echtzeit."],
       ["Kirby", "Gegner einsaugen", "Und ihre Fähigkeit übernehmen."],
       ["Fire Emblem", "Taktik auf Feldern", "Gefallene bleiben oft tot."],
       ["Bayonetta", "Hexe mit Pistolen", "Auch an den Absätzen."],
       ["Nier", "Androiden in Ruinen", "Erst mehrere Durchgänge ergeben ein Ganzes."],
       ["Xenoblade", "Riesige offene Welten", "Mit sehr langen Handlungen."]]'::jsonb,
     '[["Trommeln im Takt der Musik", "Das wäre Taiko no Tatsujin, das hier fehlt."],
       ["Eine Idolgruppe verwalten", "Ein eigenes Genre, aber keine Reihe auf diesem Brett."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

-- The answers that belong to no category. Numbered after the pairs so the two
-- sets never collide on `position`, though nothing reads it for a fake: the
-- pool is shuffled before a player sees it, and the review lists fakes on their
-- own rather than in board order.
fakes as (
    select q.id                                         as quiz_id,
           k.value ->> 0                                as label,
           k.value ->> 1                                as explanation,
           (jsonb_array_length(sp.pairs) + k.ord)::int  as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.fakes) with ordinality k(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
),

paired as (
    insert into items (quiz_id, category_id, label, position, explanation)
    select f.quiz_id, c.id, f.answer, f.position, f.explanation
      from flat f
      join new_categories c
        on c.quiz_id = f.quiz_id
       and c.label = f.label
    returning id
)

-- Same table, `category_id` left null. Both inserts run in the one statement,
-- so `items_quiz_id_label_key` still sees the pairs above: a fake written to
-- repeat an answer already on its own board fails the file rather than becoming
-- a second row nobody can tell apart.
insert into items (quiz_id, category_id, label, position, explanation)
select k.quiz_id, null, k.label, k.position, k.explanation
  from fakes k;
