-- Videospiele, schwere Fragen. Zwanzig Fragen, alle 'hard'.
--
-- Vorher anwenden: supabase/questions/subject-videospiele.sql.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs) as (
    values

    ('videospiele', 'regionale-namen', 'Anderer Name, gleiches Spiel',
     'Wie heißt es in der anderen Region?',
     'hard', 'Portierung (Software)',
     'https://de.wikipedia.org/wiki/Portierung_(Software)',
     '[["Resident Evil", "Biohazard", "So heißt die Reihe in Japan bis heute."],
       ["Mega Drive", "Genesis", "In Nordamerika war der Name schon vergeben."],
       ["Super Nintendo", "Super Famicom", "Japanisches Modell mit anderem Gehäuse."],
       ["Nintendo Entertainment System", "Famicom", "Kurz für Family Computer."],
       ["Star Fox 64", "Lylat Wars", "In Europa wegen eines Markenstreits umbenannt."],
       ["Contra", "Probotector", "In Europa kämpften Roboter statt Soldaten."],
       ["Mega Man", "Rockman", "Der japanische Originalname."],
       ["Dragon Quest", "Dragon Warrior", "Der frühere US-Titel, ebenfalls wegen Markenrechten."],
       ["Kirby’s Dream Land", "Hoshi no Kirby", "Japanischer Reihentitel."],
       ["Pro Evolution Soccer", "Winning Eleven", "In Japan hieß die Reihe anders."]]'::jsonb),

    ('videospiele', 'gescheiterte-hardware', 'Hardware, die scheiterte',
     'Woran krankte das Gerät?',
     'hard', 'Virtual Boy', 'https://de.wikipedia.org/wiki/Virtual_Boy',
     '[["Virtual Boy", "Rotes Stereobild", "Vielen wurde davon übel."],
       ["Atari Jaguar", "Warb mit 64 Bit", "Die Zahl war kaum die halbe Wahrheit."],
       ["3DO", "Extrem hoher Verkaufspreis", "Lizenznehmer setzten den Preis selbst."],
       ["Philips CD-i", "Multimedia statt Spiele", "Berüchtigt für seine Zelda-Ableger."],
       ["Nokia N-Gage", "Telefonieren an der Kante", "Das Gerät wurde seitlich ans Ohr gehalten."],
       ["Ouya", "Per Crowdfunding finanziert", "Das Interesse hielt nicht lange."],
       ["Wii U", "Name stiftete Verwirrung", "Viele hielten sie für Zubehör."],
       ["Sega 32X", "Aufsatz aufs Mega Drive", "Kurz vor der nächsten Konsole erschienen."],
       ["Apple Pippin", "Ausflug ins Spielgeschäft", "Kaum ein Dutzend Titel erschien."],
       ["Gizmondo", "Skandal um die Firma", "Der Vertrieb endete vor Gericht."]]'::jsonb),

    ('videospiele', 'crash-1983', 'Der Crash von 1983',
     'Was gehört zum Zusammenbruch des US-Marktes?',
     'hard', 'Video Game Crash',
     'https://de.wikipedia.org/wiki/Video_Game_Crash',
     '[["E.T.", "In Wochen entwickelt", "Der Termin stand vor dem Spiel."],
       ["Alamogordo", "Vergrabene Module", "1983 verscharrt, 2014 ausgegraben."],
       ["Überproduktion", "Mehr Spiele als Käufer", "Die Lager quollen über."],
       ["Fehlende Kontrolle", "Jeder durfte veröffentlichen", "Atari prüfte fremde Titel nicht."],
       ["Heimcomputer", "Billigere Alternative", "Der C64 konnte mehr als eine Konsole."],
       ["Nintendo 1985", "Neustart des Marktes", "Das NES kam als Spielzeug in die Regale."],
       ["Seal of Quality", "Prüfsiegel gegen Schrott", "Nintendo kontrollierte jede Veröffentlichung."],
       ["Pac-Man am 2600", "Missratene Umsetzung", "Flackernde Geister, riesige Auflage."],
       ["Marktvolumen", "Einbruch um Milliarden", "In zwei Jahren blieb ein Bruchteil übrig."],
       ["Handel", "Regale wurden geräumt", "Viele Ketten nahmen Spiele ganz aus dem Sortiment."]]'::jsonb),

    ('videospiele', 'game-awards-goty', 'Spiel des Jahres',
     'In welchem Jahr gewann der Titel bei den Game Awards?',
     'hard', 'The Game Awards',
     'https://de.wikipedia.org/wiki/The_Game_Awards',
     '[["Dragon Age: Inquisition", "2014", "Die erste Verleihung überhaupt."],
       ["The Witcher 3", "2015", "Der Durchbruch für CD Projekt Red."],
       ["Overwatch", "2016", "Ein Shooter mit Heldenrollen."],
       ["The Legend of Zelda: Breath of the Wild", "2017", "Startspiel der Nintendo Switch."],
       ["God of War", "2018", "Neuausrichtung einer alten Reihe."],
       ["Sekiro: Shadows Die Twice", "2019", "Von FromSoftware, ohne Rollenspielwerte."],
       ["The Last of Us Part II", "2020", "Trotz heftiger Debatten ausgezeichnet."],
       ["It Takes Two", "2021", "Nur zu zweit spielbar."],
       ["Elden Ring", "2022", "Offene Welt im Soulslike."],
       ["Baldur’s Gate 3", "2023", "Regelwerk aus dem Pen-and-Paper."]]'::jsonb),

    ('videospiele', 'arcade-hersteller', 'Automaten & ihre Hersteller',
     'Von welcher Firma stammt der Automat?',
     'hard', 'Taito', 'https://de.wikipedia.org/wiki/Taito',
     '[["Taito", "Space Invaders", "Der Auslöser des Automatenbooms."],
       ["Namco", "Pac-Man", "Entworfen von Toru Iwatani."],
       ["Nintendo", "Donkey Kong", "Der erste Auftritt von Mario."],
       ["Atari", "Pong", "Der Automat, mit dem alles begann."],
       ["Capcom", "Street Fighter II", "Es begründete das Prügelspiel-Genre neu."],
       ["SNK", "Metal Slug", "Handgezeichnete Animation in Serie."],
       ["Midway", "Mortal Kombat", "Digitalisierte Schauspieler statt Zeichnungen."],
       ["Sega", "OutRun", "Ferrari, Radio und Gabelungen."],
       ["Data East", "BurgerTime", "Hamburger stapeln statt schießen."],
       ["Irem", "R-Type", "Der Waffenaufsatz als Spielmechanik."]]'::jsonb),

    ('videospiele', 'chips-systeme', 'Chips & Systeme',
     'In welchem Gerät steckt die Technik?',
     'hard', 'Mikroprozessor', 'https://de.wikipedia.org/wiki/Mikroprozessor',
     '[["SID", "Commodore 64", "Sein Klang prägte eine ganze Musikszene."],
       ["Paula", "Amiga", "Vier Kanäle mit gesampelten Klängen."],
       ["Yamaha YM2612", "Mega Drive", "Der typisch blecherne FM-Sound."],
       ["SPC700", "Super Nintendo", "Sample-basiert und für die Zeit weich."],
       ["Ricoh 2A03", "Nintendo Entertainment System", "Ein 6502 mit eingebautem Tongenerator."],
       ["Cell", "PlayStation 3", "Schwer zu programmieren, sehr leistungsfähig."],
       ["Emotion Engine", "PlayStation 2", "Der Name war Teil der Werbung."],
       ["Reality Coprocessor", "Nintendo 64", "Gemeinsam mit Silicon Graphics entwickelt."],
       ["Tegra X1", "Nintendo Switch", "Ein Chip aus der Tablet-Welt."],
       ["Zen 2", "PlayStation 5", "Dieselbe Grundarchitektur wie in der Xbox Series X."]]'::jsonb),

    ('videospiele', 'fehlstarts', 'Berüchtigte Fehlstarts',
     'Womit fiel der Start auf?',
     'hard', 'Programmfehler', 'https://de.wikipedia.org/wiki/Programmfehler',
     '[["No Man’s Sky", "Versprochene Funktionen fehlten", "Nachgereicht wurde jahrelang."],
       ["Cyberpunk 2077", "Rücknahme im PlayStation Store", "Die alten Konsolen brachen ein."],
       ["Fallout 76", "Welt ohne Gesprächsfiguren", "Alles Menschliche war tot."],
       ["Diablo III", "Error 37", "Die Server hielten dem Ansturm nicht stand."],
       ["SimCity", "Onlinezwang trotz Solospiel", "Ohne Verbindung ging nichts."],
       ["Battlefield 2042", "Start ohne Kernfunktionen", "Gewohnte Modi fehlten."],
       ["Anthem", "Früh aufgegeben", "Der geplante Umbau wurde gestrichen."],
       ["Warcraft III Reforged", "Ersetzte das alte Spiel", "Auch wer nichts kaufte, verlor die alte Fassung."],
       ["Aliens: Colonial Marines", "Trailer zeigte anderes Spiel", "Das Endprodukt sah deutlich schlechter aus."],
       ["Overwatch 2", "Story-Modus gestrichen", "Er war der Grund für die Fortsetzung gewesen."]]'::jsonb),

    ('videospiele', 'speedrun-begriffe', 'Speedrunning',
     'Was bedeutet der Begriff?',
     'hard', 'Speedrun', 'https://de.wikipedia.org/wiki/Speedrun',
     '[["Any%", "So schnell wie möglich", "Abkürzungen ausdrücklich erlaubt."],
       ["100%", "Alles einsammeln", "Deutlich längere Läufe."],
       ["Glitchless", "Ohne Programmfehler", "Nur reguläre Wege zählen."],
       ["RTA", "Echtzeit ab Start", "Ladezeiten inklusive."],
       ["TAS", "Vom Werkzeug gesteuert", "Bild für Bild vorgeplant."],
       ["Splits", "Zwischenzeiten je Abschnitt", "Sie zeigen den Rückstand sofort."],
       ["Skip", "Abschnitt wird übersprungen", "Oft über eine Wand hinweg."],
       ["Reset", "Neustart nach Fehlversuch", "Nach schlechtem Beginn üblich."],
       ["Randomizer", "Gegenstände zufällig verteilt", "Jeder Lauf verlangt neue Planung."],
       ["Marathon", "Sammelaktion mit Zuschauern", "Läufe für den guten Zweck."]]'::jsonb),

    ('videospiele', 'mmo-geschichte', 'Geschichte der Online-Welten',
     'Wofür steht das MMO?',
     'hard', 'Massively Multiplayer Online Role-Playing Game',
     'https://de.wikipedia.org/wiki/Massively_Multiplayer_Online_Role-Playing_Game',
     '[["Ultima Online", "Wegbereiter von 1997", "Spieler konnten einander bestehlen."],
       ["EverQuest", "Erstes großes 3D-MMO", "Bekannt als Zeitfresser."],
       ["World of Warcraft", "Millionen Abonnenten", "Es machte das Genre massentauglich."],
       ["RuneScape", "Lief im Browser", "Keine Installation nötig."],
       ["EVE Online", "Eine einzige Welt", "Alle Spieler auf demselben Server."],
       ["Final Fantasy XI", "Konsole und PC zusammen", "Früh plattformübergreifend."],
       ["Guild Wars", "Ohne monatliche Gebühr", "Bezahlt wurde nur der Kauf."],
       ["Lineage", "Riesig in Südkorea", "Dort ein gesellschaftliches Phänomen."],
       ["Star Wars Galaxies", "Umbau vergraulte Spieler", "Das Klassensystem wurde ersetzt."],
       ["Meridian 59", "Frühes 3D von 1996", "Noch vor Ultima Online online."]]'::jsonb),

    ('videospiele', 'adventure-legenden', 'Adventures der Neunziger',
     'Wofür ist das Adventure bekannt?',
     'hard', 'Lucasfilm Games',
     'https://de.wikipedia.org/wiki/Lucasfilm_Games',
     '[["Monkey Island", "Beleidigungsfechten", "Gewonnen wird mit der besseren Antwort."],
       ["Day of the Tentacle", "Drei Zeitebenen", "Handlungen wirken über Jahrhunderte."],
       ["Grim Fandango", "Totenreich im Art-déco", "Ein Reisebüro für Verstorbene."],
       ["Full Throttle", "Rocker auf der Straße", "Mit Musik der Gone Jackals."],
       ["Maniac Mansion", "Der erste SCUMM-Titel", "Die Steuerung prägte ein Jahrzehnt."],
       ["King’s Quest", "Sierras Aushängeschild", "Der Tod lauerte hinter jedem Schritt."],
       ["Space Quest", "Hausmeister im All", "Der unfreiwillige Held heißt Roger Wilco."],
       ["Leisure Suit Larry", "Fragen als Alterskontrolle", "Wer die Achtziger nicht kannte, kam nicht rein."],
       ["Loom", "Rätsel per Melodie", "Zauber werden gespielt, nicht gesprochen."],
       ["Fate of Atlantis", "Drei Wege zum Ziel", "Faust, Verstand oder Begleiterin."]]'::jsonb),

    ('videospiele', 'kult-fehler', 'Kult-Fehler & Codes',
     'Zu welchem Spiel gehört das?',
     'hard', 'Computerspiel', 'https://de.wikipedia.org/wiki/Computerspiel',
     '[["Minus World", "Super Mario Bros.", "Eine endlose Unterwasserwelt hinter Level 1-2."],
       ["MissingNo", "Pokémon Rot", "Der Fehler vervielfacht Gegenstände."],
       ["Bunnyhopping", "Half-Life", "Springen war schneller als Laufen."],
       ["Hot Coffee", "GTA San Andreas", "Eine versteckte Szene kostete das Alterskennzeichen."],
       ["Fliegende Riesen", "Skyrim", "Ein Keulenschlag katapultiert in den Himmel."],
       ["Konami-Code", "Contra", "Oben, oben, unten, unten und dreißig Leben."],
       ["Rocket Jump", "Quake", "Die eigene Rakete als Sprungbrett."],
       ["Herobrine", "Minecraft", "Eine Legende, die es nie ins Spiel schaffte."],
       ["Backwards Long Jump", "Super Mario 64", "Rückwärts durch verschlossene Türen."],
       ["Wrong Warp", "Ocarina of Time", "Der Abspann in unter zehn Minuten."]]'::jsonb),

    ('videospiele', 'jrpg', 'Japanische Rollenspiele',
     'Was zeichnet die Reihe aus?',
     'hard', 'Computer-Rollenspiel',
     'https://de.wikipedia.org/wiki/Computer-Rollenspiel',
     '[["Dragon Quest", "In Japan Kulturgut", "Erscheinungstermine lagen früher auf Wochenenden."],
       ["Chrono Trigger", "Viele mögliche Enden", "Je nachdem, wann man den Endgegner stellt."],
       ["Persona", "Alltag und Dämonen", "Schule am Tag, Verlies in der Nacht."],
       ["Xenoblade Chronicles", "Welt auf zwei Titanen", "Die Landschaft ist ein Körper."],
       ["Nier: Automata", "Mehrere Durchgänge nötig", "Erst danach ergibt die Handlung ein Ganzes."],
       ["Fire Emblem", "Gefallene bleiben tot", "Klassisch ohne Wiederbelebung."],
       ["Octopath Traveler", "Acht Figuren, acht Anfänge", "Die Reihenfolge wählt der Spieler."],
       ["Suikoden", "108 Verbündete sammeln", "Nach einem chinesischen Roman."],
       ["Shin Megami Tensei", "Dämonen verhandeln statt fangen", "Man redet sie ins eigene Team."],
       ["Final Fantasy Tactics", "Kämpfe auf Rasterfeldern", "Höhe entscheidet über Treffer."]]'::jsonb),

    ('videospiele', 'indie-erfolge', 'Indie-Erfolge',
     'Was ist das Besondere am Spiel?',
     'hard', 'Indie-Spiel', 'https://de.wikipedia.org/wiki/Indie-Spiel',
     '[["Braid", "Zeit zurückspulen", "Jede Welt dreht die Regel anders."],
       ["Fez", "Zwei Dimensionen drehen", "Die flache Welt ist in Wahrheit ein Würfel."],
       ["Super Meat Boy", "Tausend Tode pro Level", "Der Neustart dauert Sekundenbruchteile."],
       ["Undertale", "Kämpfe lassen sich vermeiden", "Das Spiel merkt sich jede Entscheidung."],
       ["Celeste", "Ein Berg als Metapher", "Es geht um Angst und Selbstzweifel."],
       ["Hades", "Sterben treibt die Handlung", "Jeder Lauf bringt neue Gespräche."],
       ["Papers, Please", "Grenzbeamter mit Stempel", "Bürokratie als Spielmechanik."],
       ["Vampire Survivors", "Angriffe laufen automatisch", "Gesteuert wird nur die Bewegung."],
       ["Stardew Valley", "Von einer Person entwickelt", "Grafik, Code und Musik aus einer Hand."],
       ["Hollow Knight", "Insektenreich unter der Erde", "Handgezeichnet und ohne Wegweiser."]]'::jsonb),

    ('videospiele', 'jugendschutz-deutschland', 'Jugendschutz in Deutschland',
     'Was steckt dahinter?',
     'hard', 'Jugendschutzgesetz',
     'https://de.wikipedia.org/wiki/Jugendschutzgesetz',
     '[["Wolfenstein", "Hakenkreuze früher entfernt", "Symbole wurden durch andere ersetzt."],
       ["Command & Conquer", "Roboter statt Soldaten", "Die deutsche Fassung tauschte die Einheiten."],
       ["Doom", "Bis 2011 indiziert", "Danach neu geprüft und freigegeben."],
       ["Manhunt", "In Deutschland beschlagnahmt", "Ein Gericht ordnete das Verbot an."],
       ["Grünes Blut", "Farbe statt Rot", "Ein alter Trick für eine niedrigere Freigabe."],
       ["Sozialadäquanz", "Symbole seit 2018 erlaubt", "Spiele gelten seither als Kunst."],
       ["USK", "Prüfung vor dem Verkauf", "Sonst darf der Titel nicht an Minderjährige."],
       ["Liste der BzKJ", "Jugendgefährdende Medien", "Früher als Index der BPjM bekannt."],
       ["Indizierung", "Werbung wird verboten", "Verkauft wird nur unter der Theke."],
       ["Jugendschutzgesetz", "Kennzeichen ist bindend", "Anders als das freiwillige PEGI."]]'::jsonb),

    ('videospiele', 'netzwerk-technik', 'Technik hinter dem Onlinespiel',
     'Was bedeutet der Begriff?',
     'hard', 'Crossplay', 'https://de.wikipedia.org/wiki/Crossplay',
     '[["Ping", "Zeit hin und zurück", "Gemessen in Millisekunden."],
       ["Tickrate", "Aktualisierungen pro Sekunde", "Je höher, desto genauer die Treffer."],
       ["Netcode", "Regeln der Synchronisierung", "Er entscheidet über das Spielgefühl."],
       ["Rollback", "Zurückspulen und neu berechnen", "In Prügelspielen der Standard."],
       ["Lag-Kompensation", "Server rechnet zurück", "Der Schuss zählt für den Zeitpunkt des Zielens."],
       ["Dedizierter Server", "Eigener Rechner als Gastgeber", "Niemand hat Heimvorteil."],
       ["Peer-to-Peer", "Ein Spieler ist Gastgeber", "Verlässt er das Spiel, endet die Runde."],
       ["Paketverlust", "Daten kommen nicht an", "Es ruckelt, obwohl der Ping stimmt."],
       ["Interpolation", "Bewegung wird geglättet", "Sie füllt die Lücken zwischen Aktualisierungen."],
       ["Crossplay", "Plattformen spielen zusammen", "Lange von den Herstellern blockiert."]]'::jsonb),

    ('videospiele', 'emulation-retro', 'Emulation & Retro',
     'Was ist damit gemeint?',
     'hard', 'Emulator', 'https://de.wikipedia.org/wiki/Emulator',
     '[["ROM", "Kopie des Spielmoduls", "Rechtlich nur mit eigenem Original."],
       ["BIOS", "Startprogramm des Systems", "Ohne es läuft mancher Emulator nicht."],
       ["Virtual Console", "Nintendos Klassikerladen", "Titel alter Konsolen zum Kauf."],
       ["Mini-Konsole", "Spiele fest eingebaut", "Nachbau im verkleinerten Gehäuse."],
       ["Fan-Übersetzung", "Text von Freiwilligen übertragen", "Oft für nie exportierte Titel."],
       ["Modulbatterie", "Speicherstand geht verloren", "Nach Jahrzehnten ist sie leer."],
       ["Rewind", "Zurückspulen im Emulator", "Eine Funktion, die es nie gab."],
       ["Shader", "Röhrenbild nachgeahmt", "Scanlinien für den alten Look."],
       ["Preservation", "Bewahren alter Spiele", "Vieles existiert nur noch als Kopie."],
       ["Abandonware", "Nirgends mehr verkäuflich", "Rechtlich trotzdem geschützt."]]'::jsonb),

    ('videospiele', 'konsolenkriege', 'Konsolenkriege',
     'Worum ging es dabei?',
     'hard', 'Spielkonsole', 'https://de.wikipedia.org/wiki/Spielkonsole',
     '[["Blast Processing", "Werbebegriff ohne Substanz", "Sega verkaufte damit Geschwindigkeit."],
       ["Mode 7", "Gedrehte Hintergrundebene", "Damit fuhr Mario Kart in die Tiefe."],
       ["Sony und Nintendo", "Geplatzte CD-Kooperation", "Aus dem Bruch entstand die PlayStation."],
       ["Xbox Live", "Frühes Onlinenetzwerk", "Es setzte den Standard für Konsolen."],
       ["Wii gegen PlayStation 3", "Bewegung schlug Rechenleistung", "Die schwächere Konsole verkaufte sich besser."],
       ["Blu-ray gegen HD DVD", "Formatstreit über Konsolen", "Die PlayStation 3 entschied ihn mit."],
       ["Dreamcast", "Zu früh am Markt", "Modem eingebaut, aber ohne Nachfolger."],
       ["Xbox Series S", "Günstiger, aber schwächer", "Entwickler müssen zwei Ziele bedienen."],
       ["Nintendo Switch", "Verzicht auf das Grafikrennen", "Der Erfolg kam über die Bauform."],
       ["Exklusivtitel", "Nur auf einer Konsole", "Das schärfste Argument im Streit."]]'::jsonb),

    ('videospiele', 'rekorde', 'Rekorde der Branche',
     'Welcher Titel oder welches Gerät hält den Rekord?',
     'hard', 'Computerspiel', 'https://de.wikipedia.org/wiki/Computerspiel',
     '[["Meistverkauftes Spiel", "Minecraft", "Über 300 Millionen verkaufte Exemplare."],
       ["Meistverkaufte Konsole", "PlayStation 2", "Rund 155 Millionen Stück."],
       ["Meistverkaufter Handheld", "Nintendo DS", "Zwei Bildschirme, gewaltige Stückzahl."],
       ["Meistverkaufte Spielereihe", "Mario", "Über alle Ableger hinweg gerechnet."],
       ["Beigelegter Verkaufsschlager", "Wii Sports", "Es lag der Konsole in vielen Ländern bei."],
       ["Erste Heimkonsole", "Magnavox Odyssey", "1972, noch ohne Tonausgabe."],
       ["Erster Münzautomat", "Computer Space", "Zu kompliziert für die Kneipe."],
       ["Größtes E-Sport-Preisgeld", "The International", "Von der Spielerschaft mitfinanziert."],
       ["Meistgespieltes MOBA", "League of Legends", "Seit 2009 an der Spitze."],
       ["Teuerste Produktion ihrer Zeit", "Grand Theft Auto V", "Entwicklung und Werbung im dreistelligen Millionenbereich."]]'::jsonb),

    ('videospiele', 'pruegelspiel-begriffe', 'Prügelspiel-Vokabular',
     'Was bedeutet der Fachbegriff?',
     'hard', 'Beat ’em up', 'https://de.wikipedia.org/wiki/Beat_%E2%80%99em_up',
     '[["Combo", "Kette ohne Gegenwehr", "Der Getroffene kann nichts tun."],
       ["Parry", "Abwehr im richtigen Moment", "Belohnt mit einem Konterfenster."],
       ["Cancel", "Animation vorzeitig abbrechen", "Damit werden Ketten überhaupt möglich."],
       ["Hitbox", "Trefferfläche der Figur", "Sie stimmt selten genau mit dem Bild überein."],
       ["Frame Data", "Bilder pro Aktion", "Sie entscheidet, wer zuerst wieder handeln darf."],
       ["Zoning", "Gegner auf Abstand halten", "Die Waffe der Fernkämpfer."],
       ["Mixup", "Gegner raten lassen", "Oben oder unten, das ist die Frage."],
       ["Wake-up", "Aufstehen nach dem Sturz", "Der gefährlichste Moment einer Runde."],
       ["Super-Leiste", "Füllt sich im Kampf", "Sie schaltet die stärksten Angriffe frei."],
       ["Trainingsmodus", "Üben gegen einen Dummy", "Ohne ihn ist das Genre kaum lernbar."]]'::jsonb),

    ('videospiele', 'vorlagen', 'Spiele nach Vorlage',
     'Worauf beruht das Spiel?',
     'hard', 'Computerspiel', 'https://de.wikipedia.org/wiki/Computerspiel',
     '[["The Witcher", "Romane von Sapkowski", "Die Spiele setzen die Bücher fort."],
       ["Metro 2033", "Roman von Glukhowski", "Der Autor arbeitete an den Spielen mit."],
       ["Marvel’s Spider-Man", "Comicreihe von Marvel", "Eine eigene Fassung der Figur."],
       ["Total War: Warhammer", "Tabletop von Games Workshop", "Zinnfiguren in Echtzeit."],
       ["Alien: Isolation", "Kinofilm von 1979", "Die Optik folgt dem Original."],
       ["Der Pate", "Filmklassiker von Coppola", "Mit Stimmen aus dem Film."],
       ["Cyberpunk 2077", "Pen-and-Paper-Regelwerk", "Nach Cyberpunk 2020."],
       ["Hogwarts Legacy", "Bücher von Rowling", "Lange vor der Handlung der Romane."],
       ["Dune: Spice Wars", "Romanreihe von Herbert", "Der Kampf um den Wüstenplaneten."],
       ["South Park", "Zeichentrickserie", "Von den Serienmachern selbst geschrieben."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
)

insert into items (quiz_id, category_id, label, position, explanation)
select f.quiz_id, c.id, f.answer, f.position, f.explanation
  from flat f
  join new_categories c
    on c.quiz_id = f.quiz_id
   and c.label = f.label;
