-- Videospiele, leichte Fragen. Zwanzig Fragen, alle 'easy'.
--
-- Gefragt wird nach dem, was jeder kennt, der mal einen Controller in der Hand
-- hatte: Maskottchen, Genres, Spielhallenklassiker. Keine Patchnotes.
--
-- Vorher anwenden: supabase/questions/subject-videospiele.sql -- ohne die Zeile
-- in subjects findet der Join hier nichts und es wird still nichts eingefügt.
--
-- Shape, rules and how to apply: see supabase/questions/batch-01.sql.

with spec (subject_slug, slug, title, description, difficulty,
           source_title, source_url, pairs) as (
    values

    ('videospiele', 'leicht-konsolen-hersteller', 'Firmen & ihre Konsolen',
     'Welche Konsole kommt von dieser Firma?',
     'easy', 'Spielkonsole', 'https://de.wikipedia.org/wiki/Spielkonsole',
     '[["Nintendo", "Switch", "Ein Gerät für Fernseher und unterwegs."],
       ["Sony", "PlayStation", "Seit 1994 auf dem Markt."],
       ["Microsoft", "Xbox", "Die erste kam 2001."],
       ["Sega", "Mega Drive", "Der große Rivale des SNES."],
       ["Atari", "Atari 2600", "Sie machte Module populär."],
       ["Valve", "Steam Deck", "Ein Handheld für PC-Spiele."],
       ["Commodore", "C64", "Ein Heimcomputer, kein reines Spielgerät."],
       ["SNK", "Neo Geo", "Spielhallentechnik fürs Wohnzimmer."],
       ["Sinclair", "ZX Spectrum", "In Großbritannien sehr verbreitet."],
       ["NEC", "PC Engine", "In Japan ein großer Erfolg."]]'::jsonb),

    ('videospiele', 'leicht-spiele-figuren', 'Spiele & ihre Helden',
     'Wer ist die Hauptfigur?',
     'easy', 'Spielfigur', 'https://de.wikipedia.org/wiki/Spielfigur',
     '[["Super Mario", "Mario", "Ein Klempner mit roter Mütze."],
       ["The Legend of Zelda", "Link", "Nicht Zelda, wie oft geraten wird."],
       ["Tomb Raider", "Lara Croft", "Archäologin mit Doppelpistolen."],
       ["Metroid", "Samus Aran", "Kopfgeldjägerin im Kampfanzug."],
       ["God of War", "Kratos", "Ein Krieger mit roter Bemalung."],
       ["Halo", "Master Chief", "Sein Helm bleibt fast immer auf."],
       ["Uncharted", "Nathan Drake", "Schatzsucher mit lockerem Spruch."],
       ["The Witcher", "Geralt von Riva", "Der Hexer mit weißem Haar."],
       ["Minecraft", "Steve", "Die Standardfigur der Klötzchenwelt."],
       ["Final Fantasy VII", "Cloud Strife", "Er trägt ein überdimensioniertes Schwert."]]'::jsonb),

    ('videospiele', 'leicht-spielgenres', 'Genres einfach erklärt',
     'Was macht man in diesem Genre?',
     'easy', 'Computerspielgenre',
     'https://de.wikipedia.org/wiki/Computerspielgenre',
     '[["Ego-Shooter", "Schießen aus Ich-Sicht", "Man sieht nur die eigenen Hände."],
       ["Jump ’n’ Run", "Springen und Laufen", "Von Plattform zu Plattform."],
       ["Rennspiel", "Autos im Wettrennen", "Wer zuerst durchs Ziel fährt."],
       ["Strategiespiel", "Planen und Truppen führen", "Oft von oben betrachtet."],
       ["Rollenspiel", "Held wird stärker", "Erfahrung sammeln und aufsteigen."],
       ["Simulation", "Alltag nachgestellt", "Vom Bauernhof bis zum Flugzeug."],
       ["Puzzlespiel", "Rätsel lösen", "Meist ohne Zeitdruck."],
       ["Aufbauspiel", "Städte errichten", "Erst planen, dann wachsen lassen."],
       ["Musikspiel", "Im Takt drücken", "Punkte gibt es für Timing."],
       ["Sportspiel", "Sport am Bildschirm", "Mit echten Vereinen und Regeln."]]'::jsonb),

    ('videospiele', 'leicht-mario-welt', 'Die Welt von Super Mario',
     'Wer oder was ist das?',
     'easy', 'Super Mario', 'https://de.wikipedia.org/wiki/Super_Mario',
     '[["Mario", "Klempner in Rot", "Das Maskottchen von Nintendo."],
       ["Luigi", "Bruder in Grün", "Etwas größer und ängstlicher."],
       ["Peach", "Herrscherin des Pilzkönigreichs", "Sie wird oft entführt."],
       ["Bowser", "Der gehörnte Bösewicht", "Ein Drache mit Panzer."],
       ["Yoshi", "Grüner Dinosaurier", "Er schluckt Gegner mit der Zunge."],
       ["Toad", "Figur mit Pilzkopf", "Meist Helfer im Hintergrund."],
       ["Wario", "Gieriger Gegenspieler", "Gelb statt rot, Z statt M."],
       ["Feuerblume", "Ermöglicht Feuerbälle", "Mario wird dabei weiß-rot."],
       ["Superpilz", "Lässt Mario wachsen", "Der bekannteste Gegenstand der Reihe."],
       ["Warpröhre", "Grüne Röhre zum Reisen", "Man springt einfach hinein."]]'::jsonb),

    ('videospiele', 'leicht-pokemon-typen', 'Pokémon & ihre Typen',
     'Welchen Typ hat das Pokémon?',
     'easy', 'Pokémon', 'https://de.wikipedia.org/wiki/Pok%C3%A9mon',
     '[["Glumanda", "Feuer", "Die Flamme am Schwanz verrät es."],
       ["Schiggy", "Wasser", "Eine Schildkröte mit Panzer."],
       ["Bisasam", "Pflanze", "Mit einer Knolle auf dem Rücken."],
       ["Pikachu", "Elektro", "Rote Backen speichern die Ladung."],
       ["Abra", "Psycho", "Es schläft fast den ganzen Tag."],
       ["Machollo", "Kampf", "Muskeln statt Angriffszauber."],
       ["Zubat", "Gift", "Eine Fledermaus ohne Augen."],
       ["Digda", "Boden", "Nur der Kopf schaut aus der Erde."],
       ["Onix", "Gestein", "Eine Schlange aus Felsbrocken."],
       ["Nebulak", "Geist", "Ein Schatten mit Grinsen."],
       ["Sichlor", "Käfer", "Sicheln statt Arme."],
       ["Dratini", "Drache", "Sehr selten zu finden."]]'::jsonb),

    ('videospiele', 'leicht-zelda', 'The Legend of Zelda',
     'Was gehört dazu?',
     'easy', 'The Legend of Zelda',
     'https://de.wikipedia.org/wiki/The_Legend_of_Zelda',
     '[["Link", "Held in Grün", "Er spricht so gut wie nie."],
       ["Zelda", "Prinzessin von Hyrule", "Namensgeberin der ganzen Reihe."],
       ["Ganondorf", "Der dunkle Widersacher", "Er will das Triforce."],
       ["Hyrule", "Das Königreich der Reihe", "Fast jeder Teil spielt dort."],
       ["Master-Schwert", "Klinge gegen das Böse", "Nur der Auserwählte zieht sie."],
       ["Triforce", "Dreieck aus drei Teilen", "Kraft, Weisheit und Mut."],
       ["Epona", "Links Pferd", "Sie kommt auf einen Pfiff."],
       ["Herzcontainer", "Mehr Lebensenergie", "Belohnung nach einem Bosskampf."],
       ["Okarina", "Instrument für Melodien", "Lieder verändern die Welt."],
       ["Navi", "Begleiterin mit Hinweisen", "Eine Fee, die ständig ruft."]]'::jsonb),

    ('videospiele', 'leicht-minecraft', 'Minecraft',
     'Was ist das im Spiel?',
     'easy', 'Minecraft', 'https://de.wikipedia.org/wiki/Minecraft',
     '[["Kreativmodus", "Bauen ohne Grenzen", "Unbegrenztes Material, kein Schaden."],
       ["Überlebensmodus", "Sammeln und überleben", "Hunger und Monster inklusive."],
       ["Creeper", "Grüner Gegner mit Explosion", "Das Zischen ist die Warnung."],
       ["Diamant", "Sehr seltener Fund", "Tief unten im Stein."],
       ["Spitzhacke", "Werkzeug zum Abbauen", "Ohne sie geht fast nichts."],
       ["Nether", "Rote Parallelwelt", "Erreichbar durch ein Portal."],
       ["Enderdrache", "Endgegner des Spiels", "Er wartet in der Endwelt."],
       ["Redstone", "Rohstoff für Schaltungen", "Damit baut man Maschinen."],
       ["Dorfbewohner", "Handelspartner", "Sie tauschen gegen Smaragde."],
       ["Bett", "Überspringt die Nacht", "Und setzt den Startpunkt."],
       ["Fackel", "Licht gegen Monster", "Im Dunkeln entstehen Gegner."],
       ["Ofen", "Zum Schmelzen und Braten", "Braucht Kohle oder Holz."]]'::jsonb),

    ('videospiele', 'leicht-spielhalle', 'Klassiker der Spielhalle',
     'Worum geht es in dem Automatenspiel?',
     'easy', 'Arcade-Spiel', 'https://de.wikipedia.org/wiki/Arcade-Spiel',
     '[["Pac-Man", "Punkte fressen im Labyrinth", "Verfolgt von vier Geistern."],
       ["Space Invaders", "Aliens abschießen", "Sie werden immer schneller."],
       ["Pong", "Zwei Balken, ein Ball", "Eines der ersten Videospiele überhaupt."],
       ["Donkey Kong", "Fässern ausweichen", "Hier trat Mario zum ersten Mal auf."],
       ["Tetris", "Fallende Steine stapeln", "Volle Reihen verschwinden."],
       ["Street Fighter", "Zweikampf von der Seite", "Mit Spezialattacken per Tastenfolge."],
       ["Asteroids", "Felsen im Weltall zerschießen", "Sie zerbrechen in kleinere Stücke."],
       ["Frogger", "Straße und Fluss überqueren", "Als Frosch, ohne getroffen zu werden."],
       ["Breakout", "Steine wegschlagen", "Der Vorläufer vieler Klonspiele."],
       ["Galaga", "Angreifende Raumschiffe", "Sie fliegen in Formation."]]'::jsonb),

    ('videospiele', 'leicht-tiere', 'Tiere als Spielhelden',
     'Welches Tier ist die Figur?',
     'easy', 'Computerspiel', 'https://de.wikipedia.org/wiki/Computerspiel',
     '[["Sonic", "Igel", "Blau und sehr schnell."],
       ["Donkey Kong", "Gorilla", "Mit Krawatte und Fässern."],
       ["Yoshi", "Dinosaurier", "Er trägt Mario auf dem Rücken."],
       ["Crash Bandicoot", "Beuteldachs", "Ein Beuteltier aus Australien."],
       ["Pikachu", "Maus", "Trotz der Ohren keine Katze."],
       ["Banjo", "Bär", "Mit einem Vogel im Rucksack."],
       ["Spyro", "Drache", "Lila und noch klein."],
       ["Ecco", "Delfin", "Ein Spiel unter Wasser."],
       ["Fox McCloud", "Fuchs", "Anführer eines Raumschiffgeschwaders."],
       ["Bowser", "Schildkröte", "Genauer: ein Koopa."]]'::jsonb),

    ('videospiele', 'leicht-sportspiele', 'Sportspiele',
     'Welche Sportart wird gespielt?',
     'easy', 'Sportsimulation', 'https://de.wikipedia.org/wiki/Sportsimulation',
     '[["EA Sports FC", "Fußball", "Früher hieß die Reihe FIFA."],
       ["NBA 2K", "Basketball", "Die bekannteste Basketballreihe."],
       ["Madden NFL", "American Football", "Benannt nach einem Trainer."],
       ["Gran Turismo", "Autorennen", "Sehr auf Realismus bedacht."],
       ["Tony Hawks Pro Skater", "Skateboard", "Benannt nach einem Profi."],
       ["NHL", "Eishockey", "Jährlich neu aufgelegt."],
       ["PGA Tour", "Golf", "Wind und Neigung zählen mit."],
       ["SSX", "Snowboard", "Sprünge weit jenseits der Physik."],
       ["MotoGP", "Motorradrennen", "Mit lizenzierten Fahrern."],
       ["Rocket League", "Fußball mit Autos", "Die Tore fallen in der Luft."]]'::jsonb),

    ('videospiele', 'leicht-handyspiele', 'Spiele auf dem Handy',
     'Was macht man in dem Spiel?',
     'easy', 'Handyspiel', 'https://de.wikipedia.org/wiki/Handyspiel',
     '[["Angry Birds", "Vögel per Schleuder", "Ziel sind grüne Schweine."],
       ["Candy Crush Saga", "Bonbons kombinieren", "Drei gleiche in einer Reihe."],
       ["Pokémon Go", "Draußen Monster fangen", "Das Handy zeigt sie in der Umgebung."],
       ["Clash of Clans", "Dorf aufbauen und angreifen", "Mit einem Clan im Rücken."],
       ["Among Us", "Verräter entlarven", "Einer sabotiert heimlich."],
       ["Flappy Bird", "Durch Lücken fliegen", "Es wurde freiwillig zurückgezogen."],
       ["Temple Run", "Endlos weglaufen", "Verfolgt von Affen."],
       ["Fruit Ninja", "Früchte zerschneiden", "Bomben besser stehen lassen."],
       ["Subway Surfers", "Vor dem Wächter fliehen", "Über Gleise und Züge."],
       ["2048", "Zahlen verdoppeln", "Bis eine Kachel 2048 zeigt."]]'::jsonb),

    ('videospiele', 'leicht-begriffe', 'Wörter aus dem Spiel',
     'Was bedeutet der Begriff?',
     'easy', 'Computerspiel', 'https://de.wikipedia.org/wiki/Computerspiel',
     '[["Level", "Abschnitt eines Spiels", "Danach kommt der nächste."],
       ["Bosskampf", "Kampf gegen den Endgegner", "Meist am Ende eines Abschnitts."],
       ["Speicherstand", "Gesicherter Fortschritt", "Ohne ihn fängt man von vorn an."],
       ["Highscore", "Beste Punktzahl", "Früher mit drei Buchstaben eingetragen."],
       ["Game Over", "Alle Leben verloren", "Der klassische Abbruch."],
       ["Tutorial", "Einführung am Anfang", "Es erklärt die Steuerung."],
       ["Cheat", "Trick zum Schummeln", "Oft als Tastenfolge eingegeben."],
       ["Respawn", "Rückkehr ins Spiel", "Meist am letzten Kontrollpunkt."],
       ["Inventar", "Liste der Gegenstände", "Oft mit begrenztem Platz."],
       ["Patch", "Nachträgliche Verbesserung", "Sie behebt Fehler."]]'::jsonb),

    ('videospiele', 'leicht-konsolen-merkmale', 'Was kann die Konsole?',
     'Wodurch fällt das Gerät auf?',
     'easy', 'Handheld-Konsole',
     'https://de.wikipedia.org/wiki/Handheld-Konsole',
     '[["Game Boy", "Tragbar mit Batterien", "Grünes Display, sehr lange Laufzeit."],
       ["Wii", "Steuerung durch Bewegung", "Man schwingt den Controller."],
       ["Nintendo Switch", "Mobil und am Fernseher", "Der Bildschirm kommt mit."],
       ["Nintendo DS", "Zwei Bildschirme", "Der untere reagiert auf Berührung."],
       ["Kinect", "Steuerung ohne Controller", "Eine Kamera erkennt den Körper."],
       ["Steam Deck", "PC-Spiele unterwegs", "Ein Handheld mit PC-Innereien."],
       ["VR-Brille", "Bild vor den Augen", "Der Kopf steuert die Blickrichtung."],
       ["Spielautomat", "Münze einwerfen", "Das Spiel endet mit dem Guthaben."],
       ["Nintendo 64", "Controller mit drei Griffen", "Ungewöhnlich, aber durchdacht."],
       ["Sega Mega Drive", "Modul einstecken", "Ladezeiten gab es damals nicht."]]'::jsonb),

    ('videospiele', 'leicht-steuerung', 'Steuerung & Zubehör',
     'Wozu dient das Gerät?',
     'easy', 'Gamecontroller', 'https://de.wikipedia.org/wiki/Gamecontroller',
     '[["Gamepad", "Liegt in beiden Händen", "Daumen auf Sticks und Knöpfen."],
       ["Joystick", "Stab zum Kippen", "Vor allem für Flugspiele."],
       ["Maus", "Genaues Zielen am PC", "Deshalb sind Shooter dort beliebt."],
       ["Tastatur", "Laufen mit vier Tasten", "W, A, S und D."],
       ["Headset", "Hören und sprechen", "Wichtig im Team."],
       ["Lenkrad", "Für Rennspiele", "Oft mit Pedalen."],
       ["Tanzmatte", "Steuerung mit den Füßen", "Man tritt auf Pfeile."],
       ["Lichtpistole", "Zielen auf den Bildschirm", "Funktioniert nur mit Röhrenfernsehern."],
       ["Vibration", "Spürbare Rückmeldung", "Ein kleiner Motor im Gehäuse."],
       ["Touchscreen", "Bedienung mit dem Finger", "Auf Handy und Tablet üblich."]]'::jsonb),

    ('videospiele', 'leicht-mario-kart', 'Mario Kart',
     'Was bewirkt das im Rennen?',
     'easy', 'Mario Kart', 'https://de.wikipedia.org/wiki/Mario_Kart',
     '[["Bananenschale", "Gegner rutschen aus", "Man legt sie hinter sich ab."],
       ["Roter Panzer", "Verfolgt den Vordermann", "Er trifft fast immer."],
       ["Blauer Panzer", "Trifft den Ersten", "Der Schrecken der Führenden."],
       ["Pilz", "Kurzer Schub", "Gut für Abkürzungen."],
       ["Stern", "Kurz unverwundbar", "Und dazu noch schneller."],
       ["Tintenklecks", "Verdeckt die Sicht", "Trifft alle vor einem."],
       ["Regenbogen-Boulevard", "Strecke im Weltall", "Ohne Leitplanken."],
       ["Drift", "Kurve mit Extraschub", "Belohnt sauberes Fahren."],
       ["Zeitfahren", "Allein gegen die Uhr", "Ohne Gegner und Gegenstände."],
       ["Startbeschleunigung", "Schub beim Startsignal", "Gas geben im richtigen Moment."]]'::jsonb),

    ('videospiele', 'leicht-reihen-thema', 'Bekannte Reihen',
     'Worum geht es in der Spielereihe?',
     'easy', 'Computerspiel', 'https://de.wikipedia.org/wiki/Computerspiel',
     '[["Need for Speed", "Illegale Straßenrennen", "Meist mit Polizei im Nacken."],
       ["Die Sims", "Ein Leben nachspielen", "Vom Hausbau bis zur Karriere."],
       ["Tomb Raider", "Gräber erkunden", "Fallen und Rätsel inklusive."],
       ["Assassins Creed", "Meucheln in der Geschichte", "Jeder Teil in einer anderen Epoche."],
       ["Call of Duty", "Krieg aus Ich-Sicht", "Jährlich ein neuer Teil."],
       ["Civilization", "Ein Volk durch Jahrtausende", "Von der Steinzeit ins Weltall."],
       ["Anno", "Inseln besiedeln", "Jeder Teil nennt eine Jahreszahl."],
       ["Die Siedler", "Warenketten aufbauen", "Erst Holz, dann alles andere."],
       ["Farming Simulator", "Landwirtschaft mit Traktoren", "Mit echten Maschinenmarken."],
       ["Guitar Hero", "Gitarrenriffs nachspielen", "Auf einer Plastikgitarre."]]'::jsonb),

    ('videospiele', 'leicht-maskottchen', 'Maskottchen der Firmen',
     'Welche Figur steht für das Studio?',
     'easy', 'Spieleentwickler',
     'https://de.wikipedia.org/wiki/Spieleentwickler',
     '[["Nintendo", "Mario", "Er ziert seit 1985 fast jede Konsole."],
       ["Sega", "Sonic", "Als Gegenentwurf zu Mario erdacht."],
       ["Namco", "Pac-Man", "Angeblich von einer Pizza inspiriert."],
       ["Game Freak", "Pikachu", "Das Gesicht einer ganzen Reihe."],
       ["Mojang", "Steve", "Die Standardfigur der Klötzchenwelt."],
       ["Rovio", "Angry Birds", "Ein Handyspiel wurde zur Marke."],
       ["Microsoft", "Master Chief", "Sein Start rettete die erste Xbox."],
       ["Capcom", "Mega Man", "Blauer Roboter mit Armkanone."],
       ["Konami", "Solid Snake", "Ein Soldat mit Pappkarton."],
       ["Ubisoft", "Rayman", "Eine Figur ganz ohne Arme und Beine."]]'::jsonb),

    ('videospiele', 'leicht-zusammen-spielen', 'Zusammen spielen',
     'Was bedeutet das?',
     'easy', 'Mehrspieler', 'https://de.wikipedia.org/wiki/Mehrspieler',
     '[["Koop", "Gemeinsam gegen das Spiel", "Statt gegeneinander."],
       ["Splitscreen", "Geteilter Bildschirm", "Jeder bekommt eine Hälfte."],
       ["Online-Modus", "Über das Internet", "Mitspieler weltweit."],
       ["LAN-Party", "Rechner vor Ort verbunden", "Früher schleppte man Türme."],
       ["Party-Spiel", "Viele kurze Minispiele", "Gut für einen ganzen Abend."],
       ["Lobby", "Warteraum vor der Runde", "Hier wird das Team gebildet."],
       ["Voice-Chat", "Reden während des Spiels", "Absprachen in Echtzeit."],
       ["Ranglistenspiel", "Zählt für die Platzierung", "Niederlagen kosten Punkte."],
       ["Zuschauermodus", "Nur zusehen", "Ohne selbst einzugreifen."],
       ["Turnier", "Wettbewerb mit vielen Teams", "Meist im K.-o.-System."]]'::jsonb),

    ('videospiele', 'leicht-wo-spielt-man', 'Wo wird gespielt?',
     'Was ist typisch für diese Art zu spielen?',
     'easy', 'Spieleplattform', 'https://de.wikipedia.org/wiki/Spieleplattform',
     '[["Spielhalle", "Automaten mit Münzeinwurf", "Eine Partie kostet eine Münze."],
       ["Handy", "Spielen in der Hosentasche", "Meist kurze Runden."],
       ["PC", "Tastatur und Maus", "Aufrüsten jederzeit möglich."],
       ["Heimkonsole", "Am Fernseher im Wohnzimmer", "Mit Controller vom Sofa aus."],
       ["VR-Brille", "Mitten im Bild", "Der Kopf ist die Kamera."],
       ["Browser", "Direkt im Internet", "Ohne Installation."],
       ["Handheld", "Unterwegs in der Hand", "Bildschirm und Tasten in einem."],
       ["Cloud-Gaming", "Rechenarbeit im Rechenzentrum", "Nur das Bild kommt an."],
       ["Tablet", "Größer als das Handy", "Bedienung per Berührung."],
       ["Smart-TV", "Ohne zusätzliches Gerät", "Die App steckt im Fernseher."]]'::jsonb),

    ('videospiele', 'leicht-bosewichte', 'Bekannte Bösewichte',
     'Aus welchem Spiel stammt der Schurke?',
     'easy', 'Antagonist', 'https://de.wikipedia.org/wiki/Antagonist',
     '[["Bowser", "Super Mario", "Er entführt regelmäßig die Prinzessin."],
       ["Ganondorf", "The Legend of Zelda", "Er will das Triforce."],
       ["Dr. Eggman", "Sonic", "Ein Erfinder mit riesigem Schnurrbart."],
       ["Team Rocket", "Pokémon", "Sie stehlen fremde Pokémon."],
       ["Sephiroth", "Final Fantasy VII", "Bekannt für sein überlanges Schwert."],
       ["M. Bison", "Street Fighter", "Der Endgegner im roten Mantel."],
       ["Enderdrache", "Minecraft", "Er wartet in der letzten Welt."],
       ["Dr. Neo Cortex", "Crash Bandicoot", "Er erschuf den Helden selbst."],
       ["Ridley", "Metroid", "Ein Weltraumdrache."],
       ["GLaDOS", "Portal", "Eine Computerstimme mit Kuchenversprechen."]]'::jsonb)
),

new_quizzes as (
    insert into quizzes (subject_id, slug, title, description,
                         difficulty, source_title, source_url, origin)
    select s.id, sp.slug, sp.title, sp.description,
           sp.difficulty::difficulty, sp.source_title, sp.source_url, 'seed'
      from spec sp
      join subjects s on s.slug = sp.subject_slug
     where not exists (select 1 from quizzes q where q.slug = sp.slug)
    returning id, slug
),

flat as (
    select q.id          as quiz_id,
           p.value ->> 0 as label,
           p.value ->> 1 as answer,
           p.value ->> 2 as explanation,
           p.ord::int    as position
      from spec sp
      join new_quizzes q on q.slug = sp.slug
     cross join lateral jsonb_array_elements(sp.pairs) with ordinality p(value, ord)
),

new_categories as (
    insert into categories (quiz_id, label, position)
    select quiz_id, label, position from flat
    returning id, quiz_id, label
)

insert into items (quiz_id, category_id, label, position, explanation)
select f.quiz_id, c.id, f.answer, f.position, f.explanation
  from flat f
  join new_categories c
    on c.quiz_id = f.quiz_id
   and c.label = f.label;
