-- Who wrote a question: a person, or the machine.
--
-- The pool has two origins and, until this column, nothing to tell them apart.
-- The questions in `seed.sql` were written by hand, checked against their
-- sources and played. Everything `tools/ingest/` adds was written by a 9B model
-- out of a Wikipedia article and passed two gates. Both kinds carry a Wikipedia
-- `source_url`, both fill the same columns, and `created_at` says nothing --
-- `supabase db reset` re-stamps the seeded rows and drops the generated ones,
-- so locally the ordering flips on every reset.
--
-- Three things need the distinction. Reading a batch before trusting it.
-- Deleting one ingest run without touching the hand-written pool. And telling
-- which of two near-identical titles is the vetted one: `chemische-elemente`
-- beside `chemische-elemente-2` is what a slug collision looks like, and the
-- suffix records which was written second, not which was written by whom. That
-- collision became likelier when the ingest prompt started teaching style with
-- four real questions out of the seed.
--
-- The default is `ingest` -- the weaker claim, on purpose. A write path that
-- forgets this column marks its question as machine-written, which is the
-- harmless direction to be wrong in: nothing hand-written is claimed for the
-- model, and no generated question inherits a person's vetting. `seed.sql`
-- names itself explicitly.

alter table quizzes
  add column origin text not null default 'ingest'
    check (origin in ('seed', 'ingest'));

comment on column quizzes.origin is
  'Who wrote this question. "seed" = by hand, in supabase/seed.sql. '
  '"ingest" = generated by tools/ingest from source_url.';

create index quizzes_origin_idx on quizzes (origin);

-- Backfill, for a database that already holds both kinds. On a fresh
-- `db reset` this runs against an empty table and does nothing at all; the seed
-- then names its own rows as it inserts them.
--
-- The test is the pair count. `MIN_PAIRS` in tools/ingest/domain/rules.py is 10
-- and the validator rejects anything below it, while the seeded boards hold six
-- to nine -- so on a database written by these two paths and no other, the split
-- is exact. It is a one-time repair rather than a rule, and it stops being true
-- the moment that bound moves. Which is the whole argument for storing the
-- answer instead of re-deriving it.
update quizzes q
   set origin = 'seed'
 where (select count(*) from categories c where c.quiz_id = q.id) < 10;
